import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[access-to-justice-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Access to Justice Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/access-to-justice-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Access to Justice Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Access to Justice Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "AJ-001", name: "Afghanistan Taliban — Tribunaux Charia, Femmes Exclues Justice & Impunité Totale", country: "Asie Centrale", sector: "Afghanistan Taliban Tribunaux Charia Exclusifs 2021, Femmes Interdites Exercer Droit, Juges Indépendants Fuient, Prisonniers Politiques Sans Procès & Aide Juridictionnelle Inexistante", composite_score: 88.35, legal_aid_absence_score: 92.0, judicial_corruption_score: 85.0, impunity_accountability_score: 90.0, discrimination_access_score: 85.0, risk_level: "critique", primary_pattern: "legal_aid_absence", key_signals: ["Violation du droit d'accès à la justice documentée — Afghanistan avec score composite 88.35/100 révélant le démantèlement total du système judiciaire par les Taliban, remplacé par des tribunaux charia excluant les femmes et tout défenseur indépendant, violant l'Article 14 PIDCP sur l'égalité devant les tribunaux", "Absence aide juridictionnelle (92.0/100) — l'interdiction faite aux femmes d'exercer la profession d'avocat et la fuite de la quasi-totalité des juges indépendants depuis 2021 a créé un vide juridique complet pour des millions d'Afghans, notamment les femmes et les minorités religieuses, violant le droit à un procès équitable", "Activer la procédure spéciale du Conseil des droits de l'homme ONU contre les Taliban pour leur destruction systémique de l'État de droit et soutenir les mécanismes d'aide juridictionnelle à distance pour les Afghans via les programmes PNUD d'accès à la justice dans les contextes de crise"], estimated_access_to_justice_index: 8.84, last_updated: "2026-06-20" },
    { id: "AJ-002", name: "Myanmar — Justice Junta, Tribunaux Militaires & 20 000 Prisonniers Politiques", country: "Asie du Sud-Est", sector: "Myanmar Junta Tribunaux Militaires Depuis 2021, 20 000+ Prisonniers Politiques AAPP, Avocats Arrêtés Pour Défense Clients, Corruption Judiciaire Systémique & Aide Juridictionnelle Criminalisée", composite_score: 84.25, legal_aid_absence_score: 80.0, judicial_corruption_score: 92.0, impunity_accountability_score: 85.0, discrimination_access_score: 80.0, risk_level: "critique", primary_pattern: "judicial_corruption", key_signals: ["Violation du droit d'accès à la justice documentée — Myanmar avec score composite 84.25/100 révélant la corruption totale du système judiciaire par la junta militaire, avec 20 000+ prisonniers politiques jugés par des tribunaux militaires et des avocats arrêtés pour avoir défendu leurs clients", "Corruption judiciaire (92.0/100) — la capture du système judiciaire birman par la junta depuis le coup d'État de 2021, obligeant les juges à rendre des verdicts dictés par l'armée, constitue une violation systémique de l'indépendance de la justice et du droit à un tribunal impartial garanti par l'Article 14 PIDCP", "Soutenir le mécanisme d'enquête indépendant ONU sur le Myanmar (IIMM) et créer une juridiction complémentaire internationale pour juger les crimes de la junta, en application du principe de compétence universelle et de la résolution du Conseil de sécurité ONU sur la responsabilité au Myanmar"], estimated_access_to_justice_index: 8.43, last_updated: "2026-06-20" },
    { id: "AJ-003", name: "Venezuela — Pouvoir Judiciaire Capturé, Prisonniers Politiques & Corruption", country: "Amérique Latine", sector: "Venezuela TSJ Tribunal Suprême Capturé Maduro, 270+ Prisonniers Politiques Foro Penal, Juges Nommés Par Exécutif, Corruption 10% PIB Transparency International & Opposants Condamnés 30 Ans", composite_score: 81.0, legal_aid_absence_score: 75.0, judicial_corruption_score: 78.0, impunity_accountability_score: 92.0, discrimination_access_score: 80.0, risk_level: "critique", primary_pattern: "impunity_accountability", key_signals: ["Violation du droit d'accès à la justice documentée — Venezuela avec score composite 81.0/100 révélant la capture complète du Tribunal Suprême par l'exécutif, 270+ prisonniers politiques selon le Foro Penal et l'impunité totale pour les crimes commis par les forces de sécurité de Maduro", "Impunité/Responsabilité (92.0/100) — l'impunité quasi-totale des agents de la FAES documentée par le Panel d'experts ONU pour plus de 5 000 executions extrajudiciaires révèle un système judiciaire incapable de garantir la responsabilité, violant l'Article 2 PIDCP sur l'obligation de recours effectif", "Renforcer la CPI pour enquêter sur les crimes contre l'humanité vénézuéliens (enquête ouverte en 2021) et créer un fonds d'aide juridictionnelle pour les 270+ prisonniers politiques venezueliens conformément aux Principes de base ONU relatifs au rôle du barreau"], estimated_access_to_justice_index: 8.1, last_updated: "2026-06-20" },
    { id: "AJ-004", name: "RDC — Justice Pour Victimes Civiles, FDLR/M23 Impunité & Aide Juridictionnelle", country: "Afrique Centrale", sector: "RDC 6M+ Morts Conflits Armés Impunité Quasi-Totale, FDLR/M23 Crimes Non Jugés, Aide Juridictionnelle 0,3$/An/Habitant, Femmes Victimes Viols Armes Sans Recours & Chambres Mixtes Non-Créées", composite_score: 84.15, legal_aid_absence_score: 88.0, judicial_corruption_score: 82.0, impunity_accountability_score: 85.0, discrimination_access_score: 80.0, risk_level: "critique", primary_pattern: "legal_aid_absence", key_signals: ["Violation du droit d'accès à la justice documentée — RDC avec score composite 84.15/100 révélant que les victimes civiles de 30 ans de conflits armés n'ont presque aucun accès à la justice : aide juridictionnelle à 0,3$/habitant/an, impunité quasi-totale des groupes armés et absence des chambres mixtes promise depuis 2010", "Absence aide juridictionnelle (88.0/100) — avec 0,3$ par habitant et par an alloué à l'aide juridictionnelle, la RDC prive de facto des millions de victimes civiles de tout accès effectif à la justice, violant l'Article 14 PIDCP et les Principes de base ONU sur l'accès à la justice", "Créer les chambres mixtes congolaises promises depuis 2010 pour juger les crimes internationaux commis en RDC et tripler l'aide internationale à l'accès à la justice conformément aux Principes des Nations Unies sur la justice transitionnelle et aux obligations de réparation du droit international humanitaire"], estimated_access_to_justice_index: 8.42, last_updated: "2026-06-20" },
    { id: "AJ-005", name: "USA — Incarcération Masse, Public Defenders Surchargés & Bail Injuste", country: "Amérique du Nord", sector: "USA 2,2M Détenus Plus Grande Prison Monde, Avocats Commis Office 1 000 Dossiers/An, Cash Bail Système Inégal Pauvres, Condamnations ADN 190+ Innocents Couloir Mort & Accès Justice Classe/Race", composite_score: 53.1, legal_aid_absence_score: 55.0, judicial_corruption_score: 52.0, impunity_accountability_score: 48.0, discrimination_access_score: 58.0, risk_level: "élevé", primary_pattern: "judicial_corruption", key_signals: ["Violation du droit d'accès à la justice documentée — USA avec score composite 53.1/100 révélant des avocats commis d'office gérant jusqu'à 1 000 dossiers par an (vs 150 recommandés) et un système de caution monétaire (cash bail) emprisonnant les pauvres avant tout jugement, violant l'Article 14 PIDCP", "Corruption judiciaire (52.0/100) — le système de caution monétaire américain contraignant 70% des détenus pré-jugés à rester incarcérés faute de moyens révèle une justice à deux vitesses fondée sur la richesse, incompatible avec l'égalité devant la loi garantie par l'Article 14 PIDCP", "Abolir le système de caution monétaire et garantir un ratio maximal de 150 dossiers par avocat commis d'office conformément aux recommandations du Comité des droits de l'homme ONU dans ses observations finales sur les États-Unis et aux Standards ABA sur l'aide juridictionnelle"], estimated_access_to_justice_index: 5.31, last_updated: "2026-06-20" },
    { id: "AJ-006", name: "Inde — 50M Affaires Pendantes, Accès Femmes/Castes & Dalits Sans Recours", country: "Asie du Sud", sector: "Inde 50M Affaires Judiciaires Pendantes Délais 10-20 Ans, Dalits Discrimination Accès Justice, Femmes Violences Sous-Reportées 1/5 FIR Déposés, Aide Juridictionnelle NALSA Insuffisante & Langue Barrière Tribunaux", composite_score: 53.0, legal_aid_absence_score: 45.0, judicial_corruption_score: 50.0, impunity_accountability_score: 48.0, discrimination_access_score: 75.0, risk_level: "élevé", primary_pattern: "discrimination_access", key_signals: ["Violation du droit d'accès à la justice documentée — Inde avec score composite 53.0/100 révélant 50 millions d'affaires judiciaires pendantes créant des délais de 10-20 ans, une discrimination systémique dans l'accès à la justice pour les Dalits et les femmes et une aide juridictionnelle structurellement insuffisante", "Discrimination accès (75.0/100) — les Dalits, femmes et minorités religieuses font face à des barrières systémiques d'accès à la justice : peur des représailles pour déposer une plainte, corruption des policiers locaux, barrière linguistique dans les tribunaux et biais des juges documenté dans les affaires de castes violant les Articles 14 et 26 PIDCP", "Renforcer la National Legal Services Authority (NALSA) avec des ressources triplées et déployer des tribunaux mobiles dans les zones rurales pour garantir un accès effectif à la justice pour les 800 millions d'Indiens ruraux, conformément à l'Article 39A de la Constitution indienne sur l'aide juridictionnelle gratuite"], estimated_access_to_justice_index: 5.3, last_updated: "2026-06-20" },
    { id: "AJ-007", name: "UE/CEDH — Délais Excessifs, Legal Aid Variations & Accès Migrants", country: "Europe", sector: "UE CEDH Délais Excessifs 1ère Violation Art 6, Legal Aid Variations 8-80$/H Selon État, Migrants Accès Justice Limité CJUE, Arrêts Non-Exécutés Italie/Grèce & Comité Ministres Supervision", composite_score: 28.9, legal_aid_absence_score: 28.0, judicial_corruption_score: 30.0, impunity_accountability_score: 32.0, discrimination_access_score: 25.0, risk_level: "modéré", primary_pattern: "impunity_accountability", key_signals: ["Défis d'accès à la justice en Europe — les délais excessifs constituent la première cause de condamnation des États membres par la CEDH (Article 6), et les variations drastiques des systèmes d'aide juridictionnelle entre États membres créent des inégalités d'accès au sein de l'espace juridique européen", "Impunité/Responsabilité (32.0/100) — la non-exécution par l'Italie et la Grèce de centaines d'arrêts de la CEDH révèlent des lacunes dans la responsabilisation des États membres pour les violations du droit à un procès équitable malgré le système CEDH le plus avancé au monde", "Harmoniser les systèmes d'aide juridictionnelle européens en établissant un standard minimum de 50€/h pour les avocats commis d'office et renforcer le mécanisme d'exécution des arrêts CEDH pour les États récalcitrants, conformément à la Recommandation du Conseil de l'Europe Rec(2000)21"], estimated_access_to_justice_index: 2.89, last_updated: "2026-06-20" },
    { id: "AJ-008", name: "ONU/Règles Mandela & Principes Bangalore — Standards Accès Justice International", country: "Global", sector: "Règles Minima ONU Traitement Prisonniers Nelson Mandela 2015, Principes Bangalore Conduite Judiciaire 2002, Principes de Base Rôle Barreau 1990 & Déclaration Vienne Accès Justice 2013", composite_score: 4.45, legal_aid_absence_score: 5.0, judicial_corruption_score: 4.0, impunity_accountability_score: 3.0, discrimination_access_score: 6.0, risk_level: "faible", primary_pattern: "discrimination_access", key_signals: ["ONU/Règles Mandela incarne le cadre normatif exemplaire de l'accès à la justice — les Règles Minima ONU révisées en 2015 et les Principes Bangalore de conduite judiciaire (2002) créant des standards internationaux sur l'indépendance judiciaire, l'impartialité et l'accès effectif à la justice", "Principes de base ONU sur le rôle du barreau (1990) — garantissent le droit à l'assistance juridique dans toutes les procédures pénales, l'indépendance des avocats et leur protection contre les poursuites pour l'exercice légitime de leur profession, créant des obligations pour les États de maintenir des systèmes d'aide juridictionnelle effectifs", "Universaliser la mise en œuvre des Principes de base ONU sur le rôle du barreau et adopter un indicateur SDG dédié à l'aide juridictionnelle dans le cadre de l'ODD 16 sur les sociétés pacifiques et inclusives pour mesurer les progrès vers l'accès universel à la justice d'ici 2030"], estimated_access_to_justice_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { legal_aid_absence: 2, judicial_corruption: 2, impunity_accountability: 2, discrimination_access: 2 },
    top_risk_entities: ["Afghanistan Taliban — Tribunaux Charia, Femmes Exclues Justice & Impunité Totale", "Myanmar — Justice Junta, Tribunaux Militaires & 20 000 Prisonniers Politiques", "RDC — Justice Pour Victimes Civiles, FDLR/M23 Impunité & Aide Juridictionnelle"],
    critical_alerts: ["Afghanistan Taliban: legal aid absence", "Myanmar: judicial corruption", "Venezuela: impunity accountability", "RDC: legal aid absence"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "access_to_justice",
    confidence_score: 0.82,
    data_sources: ["world_justice_project_rule_of_law_index_annual_report", "transparency_international_corruption_perceptions_judicial_sector", "un_special_rapporteur_independence_judges_lawyers_country_reports"],
    entities,
    avg_estimated_access_to_justice_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
