import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[ecocide-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Ecocide Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/ecocide-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Ecocide Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Ecocide Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "EC-001", name: "Brésil/Amazonie — Déforestation Bolsonaro & Feux Criminels", country: "Amérique du Sud", sector: "11 000 km² Déboisés/An, Feux Délibérés +80%, Terres Indigènes Envahies & Puits Carbone Détruit", composite_score: 87.1, deliberate_ecosystem_destruction_score: 92.0, toxic_contamination_weaponization_score: 75.0, deforestation_carbon_arson_score: 95.0, biodiversity_collapse_acceleration_score: 85.0, risk_level: "critique", primary_pattern: "ecocide_delibere_industriel", key_signals: ["Écocide délibéré critique de Brésil/Amazonie — destruction intentionnelle d'écosystèmes vitaux au détriment des générations futures et de la biodiversité mondiale irremplaçable", "Crime environnemental d'État — complicité ou inaction délibérée des autorités face aux destructions massives d'écosystèmes protégés par le droit international", "Point de bascule climatique franchi — la destruction des écosystèmes atteint des seuils irréversibles menaçant l'équilibre climatique régional et mondial"], estimated_ecocide_index: 8.71, last_updated: "2026-06-20" },
    { id: "EC-002", name: "Chine/Industrie — Pollution Systémique & Rivières Toxiques", country: "Asie", sector: "70% Rivières Contaminées, 16% Terres Agricoles Polluées, Métaux Lourds Systémiques & Air Qualité Critique", composite_score: 82.9, deliberate_ecosystem_destruction_score: 85.0, toxic_contamination_weaponization_score: 92.0, deforestation_carbon_arson_score: 72.0, biodiversity_collapse_acceleration_score: 82.0, risk_level: "critique", primary_pattern: "contamination_toxique_systematique", key_signals: ["Contamination toxique systémique de Chine/Industrie — déversement délibéré de substances toxiques dans les écosystèmes aquatiques et terrestres par des acteurs industriels en impunité", "Crime environnemental d'État — complicité ou inaction délibérée des autorités face aux destructions massives d'écosystèmes protégés par le droit international", "Point de bascule climatique franchi — la destruction des écosystèmes atteint des seuils irréversibles menaçant l'équilibre climatique régional et mondial"], estimated_ecocide_index: 8.29, last_updated: "2026-06-20" },
    { id: "EC-003", name: "Russie/Sibérie — Feux Incontrôlés & Pergélisol Libéré", country: "Europe de l'Est/Asie", sector: "18M Hectares Brûlés 2021, Méthane Pergélisol Libéré, Forêts Boréales Détruites & Aucun Plan Extinction", composite_score: 80.9, deliberate_ecosystem_destruction_score: 78.0, toxic_contamination_weaponization_score: 82.0, deforestation_carbon_arson_score: 88.0, biodiversity_collapse_acceleration_score: 75.0, risk_level: "critique", primary_pattern: "deforestation_criminelle", key_signals: ["Déforestation criminelle de Russie/Sibérie — exploitation forestière illégale massive avec corruption institutionnelle empêchant toute poursuite judiciaire effective des responsables", "Crime environnemental d'État — complicité ou inaction délibérée des autorités face aux destructions massives d'écosystèmes protégés par le droit international", "Point de bascule climatique franchi — la destruction des écosystèmes atteint des seuils irréversibles menaçant l'équilibre climatique régional et mondial"], estimated_ecocide_index: 8.09, last_updated: "2026-06-20" },
    { id: "EC-004", name: "Indonésie/Bornéo — Huile de Palme & Orang-outans Extinction", country: "Asie du Sud-Est", sector: "90% Forêts Primaires Détruites Kalimantan, Orang-outans -50%, Tourbières Drainées CO2 & Feux Annuels", composite_score: 80.1, deliberate_ecosystem_destruction_score: 80.0, toxic_contamination_weaponization_score: 72.0, deforestation_carbon_arson_score: 82.0, biodiversity_collapse_acceleration_score: 88.0, risk_level: "critique", primary_pattern: "degradation_ecosysteme_active", key_signals: ["Dégradation active d'écosystèmes critiques d'Indonésie/Bornéo — destruction progressive des forêts primaires et zones humides sous pression économique avec complicité des autorités locales", "Crime environnemental d'État — complicité ou inaction délibérée des autorités face aux destructions massives d'écosystèmes protégés par le droit international", "Point de bascule climatique franchi — la destruction des écosystèmes atteint des seuils irréversibles menaçant l'équilibre climatique régional et mondial"], estimated_ecocide_index: 8.01, last_updated: "2026-06-20" },
    { id: "EC-005", name: "Nigéria/Delta Niger — Pollution Shell & Communautés Sacrifiées", country: "Afrique de l'Ouest", sector: "50 Ans Déversements Pétroliers, 40M Habitants Eau Contaminée, Shell Procès Pays-Bas & Espérance Vie -10 Ans", composite_score: 58.9, deliberate_ecosystem_destruction_score: 55.0, toxic_contamination_weaponization_score: 72.0, deforestation_carbon_arson_score: 48.0, biodiversity_collapse_acceleration_score: 62.0, risk_level: "élevé", primary_pattern: "contamination_toxique_systematique", key_signals: ["Pollution industrielle grave de Nigéria/Delta Niger — contamination persistante des écosystèmes côtiers et fluviaux par des acteurs industriels avec impunité partielle des États hôtes", "Communautés sacrifiées — populations locales subissant des impacts sanitaires graves sans accès à la justice ou réparation adéquate des dommages environnementaux", "Responsabilité extraterritoriale — multinationales opérant sous des standards environnementaux inférieurs à ceux de leur pays d'origine, créant une justice environnementale à deux vitesses"], estimated_ecocide_index: 5.89, last_updated: "2026-06-20" },
    { id: "EC-006", name: "Canada/Sables Bitumineux — Alberta Exploitation & Peuples Cris", country: "Amérique du Nord", sector: "142 000 km² Exploités Athabasca, Eau Contaminée Peuples Cris, Émissions CO2 Record & Forêts Boréales Rasées", composite_score: 53.1, deliberate_ecosystem_destruction_score: 52.0, toxic_contamination_weaponization_score: 58.0, deforestation_carbon_arson_score: 48.0, biodiversity_collapse_acceleration_score: 55.0, risk_level: "élevé", primary_pattern: "degradation_ecosysteme_active", key_signals: ["Exploitation extractive irresponsable de Canada/Sables Bitumineux — destruction progressive d'écosystèmes boréaux pour extraction de ressources sans restauration adéquate post-exploitation", "Communautés sacrifiées — populations locales subissant des impacts sanitaires graves sans accès à la justice ou réparation adéquate des dommages environnementaux", "Responsabilité extraterritoriale — multinationales opérant sous des standards environnementaux inférieurs à ceux de leur pays d'origine, créant une justice environnementale à deux vitesses"], estimated_ecocide_index: 5.31, last_updated: "2026-06-20" },
    { id: "EC-007", name: "Australie/Grande Barrière — Blanchissement Coraux & Inaction", country: "Océanie", sector: "50% Coraux Blanchis 2022, Coal Mining Approuvé Proximate, Dugongs -97% Queensland & Plans Climat Insuffisants", composite_score: 29.65, deliberate_ecosystem_destruction_score: 28.0, toxic_contamination_weaponization_score: 25.0, deforestation_carbon_arson_score: 32.0, biodiversity_collapse_acceleration_score: 35.0, risk_level: "modéré", primary_pattern: "degradation_ecosysteme_active", key_signals: ["Inaction environnementale préoccupante d'Australie/Grande Barrière — politique climatique insuffisante conduisant à une dégradation accélérée d'écosystèmes uniques sans mesures correctives adéquates", "Biodiversité endémique menacée — espèces irremplaçables en voie d'extinction rapide sans plan de sauvegarde à la hauteur de la crise en cours", "Responsabilité climatique différée — engagements environnementaux insuffisants compromettant les efforts collectifs pour maintenir les écosystèmes sous le seuil d'irréversibilité"], estimated_ecocide_index: 2.97, last_updated: "2026-06-20" },
    { id: "EC-008", name: "PNUE/Accord Paris — Protection Planétaire & Droit Environnemental", country: "Global", sector: "Accord Paris 196 Parties, PNUE GEO-7, Kunming-Montréal 30x30 & Tribunal Pénal International Écocide Proposition", composite_score: 4.45, deliberate_ecosystem_destruction_score: 5.0, toxic_contamination_weaponization_score: 4.0, deforestation_carbon_arson_score: 3.0, biodiversity_collapse_acceleration_score: 6.0, risk_level: "faible", primary_pattern: "protection_ecosystemique_exemplaire", key_signals: ["PNUE/Accord Paris incarne la protection exemplaire des écosystèmes — respect effectif des engagements climatiques, restauration active des habitats dégradés et biodiversité préservée", "Gouvernance environnementale exemplaire — institutions indépendantes de surveillance, juridictions spécialisées et responsabilité effective des pollueurs industriels", "Modèle de transition écologique — économie circulaire, énergie renouvelable et protection légale des écosystèmes critiques servant de référence internationale"], estimated_ecocide_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { ecocide_delibere_industriel: 1, contamination_toxique_systematique: 2, deforestation_criminelle: 1, degradation_ecosysteme_active: 3, protection_ecosystemique_exemplaire: 1 },
    top_risk_entities: ["Brésil/Amazonie — Déforestation Bolsonaro & Feux Criminels", "Chine/Industrie — Pollution Systémique & Rivières Toxiques", "Russie/Sibérie — Feux Incontrôlés & Pergélisol Libéré"],
    critical_alerts: ["Brésil/Amazonie: écocide délibéré industriel", "Chine/Industrie: contamination toxique systématique", "Russie/Sibérie: déforestation criminelle", "Indonésie/Bornéo: dégradation écosystème active"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "ecocide",
    confidence_score: 0.81,
    data_sources: ["pnue_global_environment_outlook", "global_witness_deforestation_monitor", "iucn_red_list_threatened_species"],
    entities,
    avg_estimated_ecocide_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
