import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[proxy-warfare-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Proxy Warfare Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/proxy-warfare-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Proxy Warfare Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Proxy Warfare Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "PW-001", name: "Russie/Wagner-Africa Corps — Sahel, Libye & Ukraine Mandataires", country: "Afrique/Europe de l'Est", sector: "Wagner/Africa Corps 50+ Pays, Libye HAftar Financé, Mali/Burkina Armés & Ukraine Commandement Hybride PMC", composite_score: 91.5, proxy_network_depth_score: 95.0, deniability_arms_transfer_score: 92.0, proxy_civilian_harm_score: 88.0, sponsor_impunity_score: 90.0, risk_level: "critique", primary_pattern: "reseau_mandataire_global", key_signals: ["Réseau mandataire global de Russie/Wagner-Africa Corps — financement, armement et commandement indirect de forces proxy opérant dans 50+ pays simultanément pour atteindre des objectifs géopolitiques niables", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance devant les instances internationales", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 9.15, last_updated: "2026-06-20" },
    { entity_id: "PW-002", name: "Iran/IRGC — Hezbollah Liban, Hamas Gaza & Houthis Yémen", country: "MENA", sector: "Hezbollah 100 000 Roquettes Financé, Hamas Armement Gaza, Houthis Missiles Yémen & PMF Irak Commandement IRGC", composite_score: 88.9, proxy_network_depth_score: 88.0, deniability_arms_transfer_score: 90.0, proxy_civilian_harm_score: 92.0, sponsor_impunity_score: 85.0, risk_level: "critique", primary_pattern: "mandataire_crimes_civils", key_signals: ["Crimes contre civils par mandataires d'Iran/IRGC — groupes armés soutenus commettant des violations du DIH avec protection diplomatique implicite du commanditaire", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance devant les instances internationales", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 8.89, last_updated: "2026-06-20" },
    { entity_id: "PW-003", name: "USA/CIA — Contras Nicaragua, Mujahidines Afghanistan & Kurdes Syrie", country: "Global", sector: "Opération Cyclone Mujahidines, Contras Millions $, YPG Armes Syrie & Maintien Deniabilité Doctrine Officielle CIA", composite_score: 83.9, proxy_network_depth_score: 85.0, deniability_arms_transfer_score: 88.0, proxy_civilian_harm_score: 80.0, sponsor_impunity_score: 82.0, risk_level: "critique", primary_pattern: "transfert_armes_deniable", key_signals: ["Transferts d'armes à deniabilité plausible d'USA/CIA — acheminement clandestin d'armements vers des groupes armés non étatiques en contournant les embargos et régimes de contrôle des exportations", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance devant les instances internationales", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 8.39, last_updated: "2026-06-20" },
    { entity_id: "PW-004", name: "Arabie Saoudite/EAU — Milices Yémen & Mercenaires Libye/Soudan", country: "MENA/Afrique", sector: "Coalition Yémen Milices Locales, Mercenaires Libye LNA, Soudan RSF Financé & Transferts Armes Cachés Jordanie Transit", composite_score: 83.85, proxy_network_depth_score: 82.0, deniability_arms_transfer_score: 85.0, proxy_civilian_harm_score: 88.0, sponsor_impunity_score: 80.0, risk_level: "critique", primary_pattern: "mandataire_crimes_civils", key_signals: ["Crimes contre civils par mandataires d'Arabie Saoudite/EAU — milices yéménites et mercenaires libyens commettant des violations du DIH avec protection diplomatique implicite", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 8.39, last_updated: "2026-06-20" },
    { entity_id: "PW-005", name: "Turquie/TFSA — Mercenaires Syriens Libye & Azerbaïdjan", country: "MENA/Europe", sector: "TFSA Syriens Libye 18 000, Karabakh Drones+Mercenaires, SADAT Formations & Bases Militaires Libye Permanentes", composite_score: 57.5, proxy_network_depth_score: 55.0, deniability_arms_transfer_score: 58.0, proxy_civilian_harm_score: 62.0, sponsor_impunity_score: 55.0, risk_level: "élevé", primary_pattern: "mandataire_crimes_civils", key_signals: ["Crimes contre civils par mandataires de Turquie/TFSA — mercenaires syriens déployés en Libye et Karabakh avec documentation de violations du DIH et absence de poursuites", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 5.75, last_updated: "2026-06-20" },
    { entity_id: "PW-006", name: "Pakistan/ISI — Taliban Afghanistan & LeT Kashmir", country: "Asie du Sud", sector: "ISI Taliban Support Documenté CIA, Lashkar-e-Taiba Kashmiri, Réseau Haqqani Financement & Double Jeu Alliance Anti-Terror", composite_score: 55.85, proxy_network_depth_score: 52.0, deniability_arms_transfer_score: 55.0, proxy_civilian_harm_score: 58.0, sponsor_impunity_score: 60.0, risk_level: "élevé", primary_pattern: "impunite_commanditaire", key_signals: ["Impunité du commanditaire de Pakistan/ISI — absence de poursuites pour le soutien au réseau Haqqani et Lashkar-e-Taiba auteurs de crimes de guerre au Kashmir et en Afghanistan", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance", "Activer le Groupe d'experts ONU sur les embargos d'armes et saisir la CPI pour complicité de crimes de guerre des commanditaires proxy"], estimated_proxy_warfare_index: 5.59, last_updated: "2026-06-20" },
    { entity_id: "PW-007", name: "Émirats/Chine — Influence Discrète & Financement Proxies Économiques", country: "Global", sector: "EAU Mercenaires Libye Discrets, Chine Acteurs Écon Proxy Djibouti, Influence Élections Via Proxies & Soft Proxy Hybride", composite_score: 28.55, proxy_network_depth_score: 28.0, deniability_arms_transfer_score: 25.0, proxy_civilian_harm_score: 30.0, sponsor_impunity_score: 32.0, risk_level: "modéré", primary_pattern: "reseau_mandataire_global", key_signals: ["Réseau mandataire discret d'Émirats/Chine — influence hybride via proxies économiques et acteurs non-étatiques masqués avec deniabilité maximale et faible intensité cinétique", "Responsabilité du commanditaire niée — doctrine de la 'main invisible' permettant aux États de financer des conflits tout en maintenant une façade de non-belligérance", "Activer le Groupe d'experts ONU sur les embargos d'armes et engager le dialogue diplomatique sur les standards de transparence des transferts d'influence"], estimated_proxy_warfare_index: 2.86, last_updated: "2026-06-20" },
    { entity_id: "PW-008", name: "ONU/Groupe Experts — Embargos Armes & Responsabilité Commanditaires", country: "Global", sector: "Panels Experts ONU Embargos Armes, CIJ Complicité Doctrine, SIPRI Transferts & Traité Commerce Armes ATT 113 Ratifications", composite_score: 4.45, proxy_network_depth_score: 5.0, deniability_arms_transfer_score: 4.0, proxy_civilian_harm_score: 3.0, sponsor_impunity_score: 6.0, risk_level: "faible", primary_pattern: "impunite_commanditaire", key_signals: ["ONU/Groupe Experts incarne la responsabilité exemplaire des commanditaires — embargos respectés, transparence des transferts d'armes et poursuites effectives pour complicité de crimes de guerre", "Traité sur le Commerce des Armes (ATT) — 113 États parties avec obligations de contrôle des exportations empêchant les transferts vers des acteurs commettant des violations graves du DIH", "Partager les méthodologies de suivi des transferts d'armes et renforcer les panels d'experts ONU pour améliorer la responsabilité des commanditaires proxy"], estimated_proxy_warfare_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { reseau_mandataire_global: 2, transfert_armes_deniable: 1, mandataire_crimes_civils: 3, impunite_commanditaire: 2 },
    top_risk_entities: ["Russie/Wagner-Africa Corps — Sahel, Libye & Ukraine Mandataires", "Iran/IRGC — Hezbollah Liban, Hamas Gaza & Houthis Yémen", "USA/CIA — Contras Nicaragua, Mujahidines Afghanistan & Kurdes Syrie"],
    critical_alerts: ["Russie/Wagner-Africa Corps: réseau mandataire global", "Iran/IRGC: mandataire crimes civils", "USA/CIA: transfert armes deniable", "Arabie Saoudite/EAU: mandataire crimes civils"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "proxy_warfare",
    confidence_score: 0.85,
    data_sources: ["sipri_arms_transfers_database", "stanford_mapping_militant_organizations", "acled_proxy_conflict_tracker"],
    entities,
    avg_estimated_proxy_warfare_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
