import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[human-trafficking-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Human Trafficking Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/human-trafficking-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Human Trafficking Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Human Trafficking Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "HT-001", name: "Corée du Nord/RPDC — Travailleurs Forcés Export & Camps Kwanliso", country: "Asie du Nord-Est", sector: "100 000+ Travailleurs Forcés Export Russie/Chine, Kwanliso Travail Forcé Prisonniers, Devises Étrangères État & ONU Sanctions", composite_score: 89.85, sexual_exploitation_network_score: 85.0, forced_labor_system_score: 95.0, state_complicity_impunity_score: 92.0, victim_identification_failure_score: 88.0, risk_level: "critique", primary_pattern: "esclavage_moderne_etatique", key_signals: ["Esclavage moderne étatique de Corée du Nord/RPDC — système de travail forcé institutionnalisé par l'État avec contrôle des travailleurs par la dette, la menace et la privation de liberté", "Victimes vulnérables ciblées — travailleurs nord-coréens exportés comme marchandise humaine par le régime Kim pour générer des devises étrangères", "Saisir le Comité ONU contre l'esclavage et activer les sanctions commerciales via le mécanisme de l'ILO contre le travail forcé étatique"], estimated_human_trafficking_index: 8.99, last_updated: "2026-06-20" },
    { entity_id: "HT-002", name: "Chine/Xinjiang — Transferts Forcés Ouïghours & Travail Coton", country: "Asie", sector: "500 000+ Ouïghours Transferts Usines, Chaînes Approvisionnement Nike/H&M, Coton Xinjiang 20% Mondial & UFLPA Sanctions USA", composite_score: 86.1, sexual_exploitation_network_score: 82.0, forced_labor_system_score: 92.0, state_complicity_impunity_score: 90.0, victim_identification_failure_score: 80.0, risk_level: "critique", primary_pattern: "esclavage_moderne_etatique", key_signals: ["Esclavage moderne étatique de Chine/Xinjiang — transferts forcés massifs d'Ouïghours vers des usines dans d'autres provinces avec contrôle étatique et complicité des chaînes d'approvisionnement mondiales", "Victimes vulnérables ciblées — minorité ethnique ciblée pour travail forcé intégré dans les chaînes de valeur mondiales de l'habillement, l'électronique et l'agriculture", "Saisir le Comité ONU contre l'esclavage et activer les sanctions commerciales via le mécanisme de l'ILO contre le travail forcé étatique"], estimated_human_trafficking_index: 8.61, last_updated: "2026-06-20" },
    { entity_id: "HT-003", name: "Thaïlande/Mekong — Traite Sexuelle Industrielle & Karaokés", country: "Asie du Sud-Est", sector: "300 000+ Victimes Estimées, Réseau GMS Myanmar/Laos/Cambodge, Tier 2 Watch List USA & Corruption Policière Systémique", composite_score: 84.75, sexual_exploitation_network_score: 95.0, forced_labor_system_score: 75.0, state_complicity_impunity_score: 82.0, victim_identification_failure_score: 85.0, risk_level: "critique", primary_pattern: "traite_sexuelle_industrielle", key_signals: ["Traite sexuelle à échelle industrielle de Thaïlande/Mekong — exploitation sexuelle commerciale de masse avec réseaux organisés de recrutement depuis Myanmar, Laos, Cambodge", "Victimes vulnérables ciblées — femmes et enfants des zones rurales appauvries recrutés par la tromperie et maintenus en esclavage sexuel par la dette et la violence", "Activer le Protocole de Palerme et engager Interpol/Europol pour démantèlement des réseaux transnationaux identifiés"], estimated_human_trafficking_index: 8.48, last_updated: "2026-06-20" },
    { entity_id: "HT-004", name: "Libye/Milices — Marchés Esclaves Migrants & Torture Rançons", country: "MENA/Afrique", sector: "CNN Marché Esclaves Documenté 2017, Migrants Sub-Sahariens Vendus, OIM 3000+ Victimes & Milices Impunité Totale", composite_score: 84.0, sexual_exploitation_network_score: 80.0, forced_labor_system_score: 82.0, state_complicity_impunity_score: 90.0, victim_identification_failure_score: 85.0, risk_level: "critique", primary_pattern: "esclavage_moderne_etatique", key_signals: ["Esclavage moderne étatique de Libye/Milices — migrants sub-sahariens vendus aux enchères par des milices opérant avec complicité des autorités libériennes et des garde-côtes financés par l'UE", "Victimes vulnérables ciblées — migrants tentant la traversée méditerranéenne interceptés et réduits en esclavage dans des centres de détention contrôlés par des milices criminelles", "Activer le Protocole de Palerme et engager Interpol/Europol pour démantèlement des réseaux transnationaux identifiés"], estimated_human_trafficking_index: 8.4, last_updated: "2026-06-20" },
    { entity_id: "HT-005", name: "Inde/Bonded Labor — 18M Esclaves Modernes Estimés", country: "Asie du Sud", sector: "18M Bonded Labor ILO Estimé, Briqueteries Rajasthan Enfants, Kamaiya Système Népal & Dalits Ciblés Travail Ancestral Dette", composite_score: 54.1, sexual_exploitation_network_score: 50.0, forced_labor_system_score: 62.0, state_complicity_impunity_score: 48.0, victim_identification_failure_score: 58.0, risk_level: "élevé", primary_pattern: "traite_travail_force", key_signals: ["Traite à des fins de travail forcé d'Inde — 18 millions de travailleurs en servitude pour dettes dans les briqueteries, carrières et agriculture ciblant majoritairement les communautés Dalit", "Victimes vulnérables ciblées — castes inférieures piégées dans des dettes ancestrales transmises de génération en génération sans possibilité légale de quitter l'employeur", "Engager l'ILO pour enquête urgente et activer la Convention 29 sur le travail forcé contre les États et entreprises complices"], estimated_human_trafficking_index: 5.41, last_updated: "2026-06-20" },
    { entity_id: "HT-006", name: "Golfe/Qatar-Émirats — Kafala Travailleurs Migrants & Chantiers", country: "MENA", sector: "Kafala Confiscation Passeports, 6750 Migrants Morts Qatar Stades, 3M Travailleurs Contrats Abusifs & Réformes Insuffisantes", composite_score: 55.1, sexual_exploitation_network_score: 50.0, forced_labor_system_score: 62.0, state_complicity_impunity_score: 52.0, victim_identification_failure_score: 58.0, risk_level: "élevé", primary_pattern: "traite_travail_force", key_signals: ["Traite à des fins de travail forcé du Golfe/Qatar — système Kafala confisquant les passeports et liant les travailleurs migrants à un employeur unique sans possibilité légale de changement", "Victimes vulnérables ciblées — travailleurs d'Asie du Sud et Afrique recrutés par des agents frauduleux et soumis à des conditions d'esclavage dans les chantiers et ménages privés", "Engager l'ILO pour enquête urgente et activer la Convention 29 sur le travail forcé contre les États et entreprises complices"], estimated_human_trafficking_index: 5.51, last_updated: "2026-06-20" },
    { entity_id: "HT-007", name: "Mexique/Cartels — Réseaux Migration Forcée & Exploitation", country: "Amérique du Nord", sector: "Cartels 13B$/An Traite, Zetas Séquestrations Migrants, San Fernando 72 Corps & Femmes Recrutées Faux Emplois", composite_score: 31.4, sexual_exploitation_network_score: 35.0, forced_labor_system_score: 28.0, state_complicity_impunity_score: 30.0, victim_identification_failure_score: 32.0, risk_level: "modéré", primary_pattern: "traite_sexuelle_industrielle", key_signals: ["Traite sexuelle de Mexique/Cartels — réseaux criminels exploitant la route migratoire pour recruter par la tromperie des femmes destinées à l'exploitation sexuelle aux États-Unis", "Victimes vulnérables ciblées — migrants centraméricains pris en otage le long de la route migratoire et contraints à travailler pour les cartels ou vendus à des réseaux d'exploitation", "Activer le Protocole de Palerme et engager Interpol/Europol pour démantèlement des réseaux transnationaux identifiés"], estimated_human_trafficking_index: 3.14, last_updated: "2026-06-20" },
    { entity_id: "HT-008", name: "UNODC/ILO — Protocole Palerme & Convention Travail Forcé", country: "Global", sector: "Protocole Palerme 2000 178 États, ILO Convention 29 Travail Forcé, Blue Heart Campaign & Fonds Victimes UNOCT", composite_score: 4.45, sexual_exploitation_network_score: 5.0, forced_labor_system_score: 4.0, state_complicity_impunity_score: 3.0, victim_identification_failure_score: 6.0, risk_level: "faible", primary_pattern: "protection_victimes_exemplaire", key_signals: ["UNODC/ILO incarne la protection exemplaire des victimes de la traite — Protocole de Palerme, identification proactive et poursuites effectives des trafiquants sans criminalisation des victimes", "Cadre normatif international — Convention 29 ILO, Protocole 2014 et standards IMAS créant des obligations contraignantes pour les États contre le travail forcé", "Partager les modèles de protection et soutenir le Fonds de l'ONU pour les victimes de la traite (UNOCT)"], estimated_human_trafficking_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { traite_sexuelle_industrielle: 2, esclavage_moderne_etatique: 3, trafic_organes_cible: 0, traite_travail_force: 2, protection_victimes_exemplaire: 1 },
    top_risk_entities: ["Corée du Nord/RPDC — Travailleurs Forcés Export & Camps Kwanliso", "Chine/Xinjiang — Transferts Forcés Ouïghours & Travail Coton", "Thaïlande/Mekong — Traite Sexuelle Industrielle & Karaokés"],
    critical_alerts: ["Corée du Nord/RPDC: esclavage moderne étatique", "Chine/Xinjiang: esclavage moderne étatique", "Thaïlande/Mekong: traite sexuelle industrielle", "Libye/Milices: esclavage moderne étatique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "human_trafficking",
    confidence_score: 0.82,
    data_sources: ["unodc_global_report_trafficking_persons", "ilo_global_estimates_modern_slavery", "us_state_department_tip_report"],
    entities,
    avg_estimated_human_trafficking_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
