import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[psychological-warfare-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Psychological Warfare Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/psychological-warfare-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Psychological Warfare Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Psychological Warfare Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "PY-001", name: "Russie/GRU — IRA Ferme Trolls, RT Propagande & Opérations Réflexives Ukraine", country: "Global/Europe de l'Est", sector: "Internet Research Agency 3 000 Employés, RT 100 Pays, Opération Réflexive Doctrine Gerasimov & Deepfakes Zelensky Viraux", composite_score: 90.5, disinformation_scale_sophistication_score: 95.0, civilian_psychological_terror_score: 88.0, social_cohesion_erosion_score: 92.0, psyop_impunity_attribution_score: 85.0, risk_level: "critique", primary_pattern: "desinformation_echelle_industrielle", key_signals: ["Désinformation à l'échelle industrielle de Russie/GRU — Internet Research Agency avec 3 000 employés, RT dans 100 pays et doctrine Gerasimov d'opérations réflexives visant la déstabilisation cognitive des démocraties", "Arme dual-use non régulée — la guerre psychologique exploite l'absence de cadre juridique international contraignant sur les opérations d'influence en temps de paix pour agir sans responsabilité", "Activer les mécanismes OSCE de prévention des conflits et saisir le Rapporteur ONU sur la liberté d'expression pour documenter les opérations d'influence étrangères"], estimated_psychological_warfare_index: 9.05, last_updated: "2026-06-20" },
    { entity_id: "PY-002", name: "Chine/PLA-SSF — Influence Opérations Taiwan, Océanie & Diaspora CCP", country: "Asie/Global", sector: "SSF Psychological Operations Department, Opérations Influence Taiwan 2024, Océanie Réseaux CCP & TikTok Algorithme Ciblé Nations", composite_score: 87.5, disinformation_scale_sophistication_score: 88.0, civilian_psychological_terror_score: 82.0, social_cohesion_erosion_score: 92.0, psyop_impunity_attribution_score: 88.0, risk_level: "critique", primary_pattern: "erosion_cohesion_sociale", key_signals: ["Érosion de la cohésion sociale par Chine/PLA-SSF — opérations d'influence ciblant Taiwan et l'Océanie via TikTok et réseaux CCP pour amplifier les clivages politiques et fragiliser les alliances", "Arme dual-use non régulée — la guerre psychologique exploite l'absence de cadre juridique international contraignant sur les opérations d'influence en temps de paix pour agir sans responsabilité", "Activer les mécanismes OSCE et saisir le Rapporteur ONU sur la liberté d'expression pour documenter les opérations d'influence du SSF chinois"], estimated_psychological_warfare_index: 8.75, last_updated: "2026-06-20" },
    { entity_id: "PY-003", name: "Iran/IRGC — Fake News Moyen-Orient & Hacktivistes Désinformation Israël", country: "MENA/Global", sector: "IRGC Desinformation Réseaux 80+ Sites Faux, Influence US Élections Meta Supprimées, Hack-and-Leak Israël & Farsi Propagande", composite_score: 82.85, disinformation_scale_sophistication_score: 82.0, civilian_psychological_terror_score: 85.0, social_cohesion_erosion_score: 80.0, psyop_impunity_attribution_score: 85.0, risk_level: "critique", primary_pattern: "terreur_psychologique_civils", key_signals: ["Terreur psychologique contre civils de Iran/IRGC — campagnes hack-and-leak ciblant des journalistes israéliens et opérations de désinformation supprimées par Meta lors des élections américaines", "Arme dual-use non régulée — la guerre psychologique exploite l'absence de cadre juridique international contraignant sur les opérations d'influence en temps de paix pour agir sans responsabilité", "Activer les mécanismes OSCE et engager les grandes plateformes dans des protocoles de transparence sur les opérations d'influence étatiques détectées"], estimated_psychological_warfare_index: 8.29, last_updated: "2026-06-20" },
    { entity_id: "PY-004", name: "Daech/ISIS — Dabiq Magazine, Snuff Videos Recrutement & Terreur Médiatique", country: "MENA/Global", sector: "Dabiq/Rumiyah Magazines Multilingues, Vidéos Exécutions Virales 2014-16, Telegram Recrutement 50 000+ & Terreur Médiatique Amplifiée", composite_score: 84.25, disinformation_scale_sophistication_score: 80.0, civilian_psychological_terror_score: 95.0, social_cohesion_erosion_score: 82.0, psyop_impunity_attribution_score: 80.0, risk_level: "critique", primary_pattern: "terreur_psychologique_civils", key_signals: ["Terreur psychologique contre civils de Daech/ISIS — vidéos d'exécutions virales et magazines Dabiq multilingues conçus pour maximiser la peur des populations et le recrutement à l'échelle mondiale", "Arme dual-use non régulée — la guerre psychologique de Daech exploite les plateformes numériques pour amplifier la terreur au-delà de ses capacités militaires réelles", "Activer le GCTF et les mécanismes de contre-narratif du Global Internet Forum to Counter Terrorism pour limiter la propagation du contenu terroriste"], estimated_psychological_warfare_index: 8.43, last_updated: "2026-06-20" },
    { entity_id: "PY-005", name: "USA/CENTCOM — JTRIG, Opérations Influence SOCOM & Psyops Réseaux Sociaux", country: "Global", sector: "JTRIG GCHQ-NSA Influence Ops Révélées Snowden, SOCOM Fake Personas Twitter/Facebook, Contre-Terrorisme PSYOP & Meta Rapports", composite_score: 56.4, disinformation_scale_sophistication_score: 55.0, civilian_psychological_terror_score: 52.0, social_cohesion_erosion_score: 58.0, psyop_impunity_attribution_score: 62.0, risk_level: "élevé", primary_pattern: "impunite_attribution_psyop", key_signals: ["Impunité par attribution difficile d'USA/CENTCOM — JTRIG et opérations SOCOM avec faux profils révélées par Snowden et supprimées par Meta sans responsabilité institutionnelle formelle", "Arme dual-use non régulée — la guerre psychologique exploite l'absence de cadre juridique international contraignant sur les opérations d'influence en temps de paix pour agir sans responsabilité", "Renforcer les mécanismes de supervision parlementaire des opérations d'influence et engager un dialogue multilatéral sur les normes de comportement responsable en ligne"], estimated_psychological_warfare_index: 5.64, last_updated: "2026-06-20" },
    { entity_id: "PY-006", name: "Corée du Nord — Ballons Tracts & Guerre Psychologique DMZ Sud-Coréens", country: "Asie du Nord-Est", sector: "Ballons Tracts Ordures Sud, Radio Psychologique DMZ, Cyber-Désinformation Séoul & Sabotage Symbolique Frontière Continue", composite_score: 54.25, disinformation_scale_sophistication_score: 52.0, civilian_psychological_terror_score: 58.0, social_cohesion_erosion_score: 55.0, psyop_impunity_attribution_score: 52.0, risk_level: "élevé", primary_pattern: "terreur_psychologique_civils", key_signals: ["Terreur psychologique contre civils par Corée du Nord — ballons porteurs de tracts, ordures et déchets envoyés sur le territoire sud-coréen dans une stratégie de harcèlement psychologique continu", "Arme dual-use non régulée — la guerre psychologique exploite l'absence de cadre juridique international contraignant sur les opérations d'influence en temps de paix pour agir sans responsabilité", "Activer les mécanismes OSCE et le dialogue inter-coréen pour désescalade des opérations psychologiques à la frontière DMZ"], estimated_psychological_warfare_index: 5.43, last_updated: "2026-06-20" },
    { entity_id: "PY-007", name: "Acteurs Non-Étatiques — Cartels Narco-Propagande & Milices Médias Sociaux", country: "Global", sector: "Cartels Narco Executions TikTok Recrutement, Hamas Médias Oct 2023, QAnon Amplification Étrangère & Milices Locales Guerres Info", composite_score: 31.35, disinformation_scale_sophistication_score: 30.0, civilian_psychological_terror_score: 35.0, social_cohesion_erosion_score: 32.0, psyop_impunity_attribution_score: 28.0, risk_level: "modéré", primary_pattern: "terreur_psychologique_civils", key_signals: ["Terreur psychologique par acteurs non-étatiques — cartels mexicains publiant des exécutions sur TikTok et milices utilisant les médias sociaux pour la guerre psychologique sans cadre de responsabilité", "Arme dual-use non régulée — la guerre psychologique des acteurs non-étatiques exploite les mêmes plateformes que les États avec une attribution encore plus difficile et une responsabilité quasi-nulle", "Activer les plateformes numériques via le Global Internet Forum et renforcer les capacités nationales de lutte contre les contenus de terreur psychologique"], estimated_psychological_warfare_index: 3.14, last_updated: "2026-06-20" },
    { entity_id: "PY-008", name: "OSCE/EUvsDisinfo — Détection Propagande & Résilience Démocratique", country: "Global", sector: "EUvsDisinfo 17 000 Cas Documentés, OSCE Media Freedom Rapporteur, Atlantic Council DFRLab & Prebunking Recherches Cambridge", composite_score: 4.45, disinformation_scale_sophistication_score: 5.0, civilian_psychological_terror_score: 4.0, social_cohesion_erosion_score: 3.0, psyop_impunity_attribution_score: 6.0, risk_level: "faible", primary_pattern: "impunite_attribution_psyop", key_signals: ["OSCE/EUvsDisinfo incarne la résilience démocratique exemplaire — 17 000 cas de désinformation documentés, prebunking et formation à la littératie médiatique pour immuniser les populations", "Résolution OSCE 2016 sur la liberté des médias — engagement contraignant des États participants à protéger l'espace d'information et à lutter contre la désinformation d'État", "Partager les méthodologies EUvsDisinfo et financer les programmes de prebunking pour renforcer la résilience des sociétés face aux opérations d'influence étrangères"], estimated_psychological_warfare_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { desinformation_echelle_industrielle: 1, terreur_psychologique_civils: 4, erosion_cohesion_sociale: 1, impunite_attribution_psyop: 2 },
    top_risk_entities: ["Russie/GRU — IRA Ferme Trolls, RT Propagande & Opérations Réflexives Ukraine", "Chine/PLA-SSF — Influence Opérations Taiwan, Océanie & Diaspora CCP", "Daech/ISIS — Dabiq Magazine, Snuff Videos Recrutement & Terreur Médiatique"],
    critical_alerts: ["Russie/GRU: désinformation échelle industrielle", "Chine/PLA-SSF: érosion cohésion sociale", "Iran/IRGC: terreur psychologique civils", "Daech/ISIS: terreur psychologique civils"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "psychological_warfare",
    confidence_score: 0.82,
    data_sources: ["euvsdisinfo_disinformation_database", "stanford_internet_observatory_reports", "atlantic_council_dfr_lab_investigations"],
    entities,
    avg_estimated_psychological_warfare_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
