import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[police-brutality-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Police Brutality Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/police-brutality-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Police Brutality Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Police Brutality Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "PB-001", name: "Philippines/Duterte — War on Drugs 6 000+ Morts EJK & Impunité Totale PNP", country: "Asie du Sud-Est", sector: "War on Drugs 6 000+ Morts EJK PNP 2016-22, 12 000+ Morts Estimés Vigilantes, Aucune Poursuite Agents & ICC Enquête Préliminaire Crimes Humanité", composite_score: 89.1, extrajudicial_killing_rate_score: 95.0, racial_ethnic_targeting_score: 82.0, accountability_oversight_failure_score: 90.0, protest_repression_score: 88.0, risk_level: "critique", primary_pattern: "meurtres_extrajudiciaires", key_signals: ["Meurtres extrajudiciaires massifs aux Philippines/Duterte — 6 000+ morts officiels dans la War on Drugs par la PNP avec 12 000+ tués par des vigilantes, aucune poursuite contre des agents malgré l'ouverture d'une enquête ICC", "Crime contre l'humanité — la Commission ICC a conclu en 2021 à des preuves raisonnables de crimes contre l'humanité dans la conduite de la War on Drugs philippine, engageant la responsabilité étatique", "Soutenir la compétence de la CPI pour poursuivre les responsables de la War on Drugs philippine et exiger un mécanisme d'accountability indépendant pour les meurtres extrajudiciaires"], estimated_police_brutality_index: 8.91, last_updated: "2026-06-20" },
    { id: "PB-002", name: "Brésil/PMERJ — 6 000+ Tués Police/An Favelas & Racisme Structurel Documenté", country: "Amérique du Sud", sector: "6 000+ Tués Police Brésil/An PMERJ/PM, Noirs 75% Victimes Police, Favelas Zones Impunité & Opération Maré 2022 80 Morts 1 Jour Condamnée ONU", composite_score: 87.25, extrajudicial_killing_rate_score: 92.0, racial_ethnic_targeting_score: 88.0, accountability_oversight_failure_score: 85.0, protest_repression_score: 82.0, risk_level: "critique", primary_pattern: "meurtres_extrajudiciaires", key_signals: ["Meurtres extrajudiciaires massifs au Brésil/PMERJ — 6 000+ tués par la police chaque année, dont 75% de Noirs, avec des opérations de favelas comme l'Opération Maré 2022 (80 morts en un jour) condamnées par l'ONU", "Racisme structurel documenté — le ciblage des Noirs brésiliens par la police constitue une discrimination raciale systémique violant la Convention Internationale pour l'Élimination de toutes les formes de Discrimination Raciale", "Activer le Comité CERD pour examen urgent de la brutalité policière raciale au Brésil et soutenir le projet de loi national de contrôle de la violence policière en favelas"], estimated_police_brutality_index: 8.73, last_updated: "2026-06-20" },
    { id: "PB-003", name: "USA/BLM — 1 000+ Tués Police/An, Racisme Systémique & George Floyd Moment Mondial", country: "Amérique du Nord", sector: "1 000+ Américains Tués Police/An, Noirs 2.5x Plus Tués Que Blancs, George Floyd Minneapolis 2020 & Rapport ONU Racisme Systémique Police Documenté", composite_score: 85.25, extrajudicial_killing_rate_score: 80.0, racial_ethnic_targeting_score: 95.0, accountability_oversight_failure_score: 82.0, protest_repression_score: 85.0, risk_level: "critique", primary_pattern: "ciblage_racial_ethnique", key_signals: ["Ciblage racial systémique USA/Police — 1 000+ personnes tuées par la police chaque année dont les Noirs américains 2.5 fois plus susceptibles d'être tués que les Blancs, documenté par le Rapport ONU sur le racisme systémique en 2021", "Discrimination raciale institutionnalisée — le ciblage racial par la police américaine viole le 14e Amendement et les obligations des États-Unis sous la Convention CERD, créant une inégalité devant la loi basée sur la race", "Activer le Comité CERD pour examen de la brutalité policière raciale aux États-Unis et soutenir les réformes systémiques d'accountability policière incluant caméras-corps, interdiction des prises d'étranglement et formations anti-biais"], estimated_police_brutality_index: 8.53, last_updated: "2026-06-20" },
    { id: "PB-004", name: "Iran/IRGC — Manifestations Mahsa Amini 500+ Morts & Basij Tirs Basse Altitude", country: "MENA", sector: "Mahsa Amini Mort Garde Morale 2022, 500+ Manifestants Tués IRGC/Basij, Plombs Visage/Yeux Tirs Délibérés & Répression 15 000+ Arrestations Vagues", composite_score: 84.0, extrajudicial_killing_rate_score: 85.0, racial_ethnic_targeting_score: 82.0, accountability_oversight_failure_score: 88.0, protest_repression_score: 80.0, risk_level: "critique", primary_pattern: "repression_protestataires", key_signals: ["Répression violente des protestations en Iran/IRGC — 500+ manifestants tués après la mort de Mahsa Amini avec des tirs délibérés de plombs au niveau des yeux par le Basij, documentés comme violations graves des droits humains", "Répression étatique des droits fondamentaux — la violence contre les manifestants iraniens viole les droits à la vie, à la liberté d'expression et d'assemblée garantis par le PIDCP ratifié par l'Iran", "Activer la Mission internationale d'établissement des faits ONU sur les manifestations iraniennes et poursuivre les responsables des tirs létaux et non-létaux contre les manifestants pacifiques"], estimated_police_brutality_index: 8.4, last_updated: "2026-06-20" },
    { id: "PB-005", name: "Kenya/GSU — Manifestations Juin 2024, 50+ Morts & Tirs Réels Manifestants Pacifiques", country: "Afrique de l'Est", sector: "Kenya Manifestations Génération Z Juin 2024, 50+ Morts GSU Tirs Réels, Parlement Envahi Impunité Policière & IPOA Enquête Indépendante Demandée", composite_score: 53.25, extrajudicial_killing_rate_score: 55.0, racial_ethnic_targeting_score: 52.0, accountability_oversight_failure_score: 55.0, protest_repression_score: 50.0, risk_level: "élevé", primary_pattern: "impunite_policiers_accountability", key_signals: ["Impunité policière au Kenya — 50+ manifestants tués lors des protestations anti-fiscal de juin 2024 avec des tirs réels contre des manifestants pacifiques par la General Service Unit sans accountabilité immédiate", "Violation du droit à la vie — l'usage de tirs réels contre des manifestants pacifiques viole le Principe Directeur ONU sur l'Usage de la Force et les obligations du Kenya sous le PIDCP", "Activer l'IPOA pour enquête indépendante sur les meurtres de manifestants kenyans de juin 2024 et mettre en place des réformes d'accountability policière conformes aux Standards Minimum ONU"], estimated_police_brutality_index: 5.32, last_updated: "2026-06-20" },
    { id: "PB-006", name: "France/LBD — Gilets Jaunes 25+ Yeux Perdus, LBD40 Controversé & IGPN Insuffisante", country: "Europe", sector: "Gilets Jaunes 25+ Manifestants Yeux Perdus LBD40, 5+ Mains Arrachées Grenades, IGPN 0 Poursuites Agents & Comité ONU CAT France Violences Policières 2022", composite_score: 51.05, extrajudicial_killing_rate_score: 48.0, racial_ethnic_targeting_score: 55.0, accountability_oversight_failure_score: 50.0, protest_repression_score: 52.0, risk_level: "élevé", primary_pattern: "repression_protestataires", key_signals: ["Répression violente des protestations en France/LBD — 25+ manifestants gilets jaunes ayant perdu un œil suite aux tirs de LBD40, 5+ mains arrachées par grenades GLI-F4, avec l'IGPN n'ayant conduit à aucune poursuite d'agents", "Violation des standards européens — le Comité ONU contre la Torture a critiqué la France en 2022 pour les violences policières lors des manifestations, soulevant des questions de conformité avec la Convention EDH", "Engager une réforme de l'IGPN vers un contrôle indépendant effectif de la police et suspendre l'usage du LBD40 contre les manifestants conformément aux recommandations du Comité des Droits de l'Homme ONU"], estimated_police_brutality_index: 5.1, last_updated: "2026-06-20" },
    { id: "PB-007", name: "Royaume-Uni/Metropolitan — Affaires Wayne Couzens, Sarah Everard & Misogynie Institutionnelle", country: "Europe", sector: "Wayne Couzens Policier Violeur Meurtrier 2021, Enquête Casey Misogynie Institutionnelle Met Police, 1 000+ Agents Crimes Sexuels Passé & IOPC Réformes Lentes", composite_score: 27.9, extrajudicial_killing_rate_score: 28.0, racial_ethnic_targeting_score: 30.0, accountability_oversight_failure_score: 28.0, protest_repression_score: 25.0, risk_level: "modéré", primary_pattern: "impunite_policiers_accountability", key_signals: ["Impunité policière modérée au Royaume-Uni/Metropolitan — rapport Casey révélant misogynie, racisme et homophobie institutionnels dans la Met avec 1 000+ agents ayant des antécédents de crimes sexuels encore en service", "Défaillance systémique d'accountability — l'affaire Couzens illustre l'échec des mécanismes de contrôle interne à détecter et expulser des policiers aux comportements criminels avant qu'ils ne commettent des crimes graves", "Mettre en œuvre intégralement les recommandations du Rapport Casey sur la Metropolitan Police et renforcer l'IOPC pour qu'il devienne un organe de contrôle véritablement indépendant et efficace"], estimated_police_brutality_index: 2.79, last_updated: "2026-06-20" },
    { id: "PB-008", name: "IPCC/ONU — Principes Fondamentaux Usage Force & Mécanismes Accountability Policière", country: "Global", sector: "Principes Fondamentaux ONU Usage Force Armes Feu 1990, Protocole Minnesota Meurtres, Code Conduite Police ONU & Rapporteur Spécial Exécutions Extrajudiciaires", composite_score: 4.45, extrajudicial_killing_rate_score: 5.0, racial_ethnic_targeting_score: 4.0, accountability_oversight_failure_score: 3.0, protest_repression_score: 6.0, risk_level: "faible", primary_pattern: "impunite_policiers_accountability", key_signals: ["IPCC/ONU incarnent l'accountability policière exemplaire — Principes Fondamentaux ONU sur l'Usage de la Force, Protocole du Minnesota sur les meurtres et Code de Conduite des Nations Unies pour les agents chargés de l'application des lois", "Principes ONU sur l'Usage de la Force (1990) — obligation de nécessité, proportionnalité et précaution dans tout usage de la force par la police, avec responsabilité individuelle et étatique pour les violations", "Universaliser l'application des Principes ONU sur l'Usage de la Force et financer des mécanismes d'accountability policière indépendants dans les pays à haute prévalence de violences policières"], estimated_police_brutality_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { meurtres_extrajudiciaires: 2, ciblage_racial_ethnique: 1, repression_protestataires: 2, impunite_policiers_accountability: 3 },
    top_risk_entities: ["Philippines/Duterte — War on Drugs 6 000+ Morts EJK & Impunité Totale PNP", "Brésil/PMERJ — 6 000+ Tués Police/An Favelas & Racisme Structurel Documenté", "USA/BLM — 1 000+ Tués Police/An, Racisme Systémique & George Floyd Moment Mondial"],
    critical_alerts: ["Philippines/Duterte: meurtres extrajudiciaires", "Brésil/PMERJ: meurtres extrajudiciaires", "USA/BLM: ciblage racial ethnique", "Iran/IRGC: répression protestataires"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "police_brutality",
    confidence_score: 0.82,
    data_sources: ["amnesty_international_police_violence_reports", "hrw_excessive_force_database", "mapping_police_violence_project"],
    entities,
    avg_estimated_police_brutality_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
