import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[ethnic-cleansing-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Ethnic Cleansing Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/ethnic-cleansing-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Ethnic Cleansing Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Ethnic Cleansing Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "EC2-001", name: "Myanmar/Rohingyas — Opération Clearance & 700 000 Expulsés Bangladesh", country: "Asie du Sud-Est", sector: "700 000 Rohingyas Expulsés 2017, Tula Toli Massacre 200+ Civils, Villages Brûlés Satellites Documentés & CPI Enquête 2019", composite_score: 91.6, forced_displacement_scale_score: 95.0, ethnic_massacre_documentation_score: 92.0, demographic_engineering_state_score: 90.0, ethnic_cleansing_impunity_score: 88.0, risk_level: "critique", primary_pattern: "deplacement_force_massif", key_signals: ["Déplacement forcé massif de Myanmar/Rohingyas — expulsion par la terreur de populations ethniques de leurs terres ancestrales créant des réfugiés en violation du DIH", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer le mécanisme R2P au Conseil de Sécurité et déclencher enquête CPI immédiate"], estimated_ethnic_cleansing_index: 9.16, last_updated: "2026-06-20" },
    { entity_id: "EC2-002", name: "Bosnie/Serbes — Srebrenica 8000 Hommes & Épuration Ethnique", country: "Europe", sector: "Srebrenica 8372 Hommes Tués TPIY, 2M Déplacés Guerre 1992-95, Karadžić Condamné 40 Ans & Fosses Communes 570+", composite_score: 88.15, forced_displacement_scale_score: 88.0, ethnic_massacre_documentation_score: 95.0, demographic_engineering_state_score: 88.0, ethnic_cleansing_impunity_score: 80.0, risk_level: "critique", primary_pattern: "massacre_demographique", key_signals: ["Massacre démographique ciblé de Bosnie/Serbes — élimination physique systématique d'une population ethnique avec intention documentée de destruction partielle du groupe", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Saisir la CPI pour génocide et demander déploiement force d'interposition onusienne d'urgence"], estimated_ethnic_cleansing_index: 8.82, last_updated: "2026-06-20" },
    { entity_id: "EC2-003", name: "Russie/Ukraine — Déportation Civils & Russification Territoires Occupés", country: "Europe de l'Est", sector: "CPI Mandat Poutine Enfants Déportés, Marioupol Population Transférée, Territoires Occupés Russifiés & Filtration Camps Civils", composite_score: 84.4, forced_displacement_scale_score: 85.0, ethnic_massacre_documentation_score: 80.0, demographic_engineering_state_score: 90.0, ethnic_cleansing_impunity_score: 82.0, risk_level: "critique", primary_pattern: "epuration_ethnique_totale", key_signals: ["Épuration ethnique totale de Russie/Ukraine — programme étatique délibéré visant à rendre les territoires occupés ethniquement homogènes par la déportation et la russification forcée", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer d'urgence le mécanisme R2P au Conseil de Sécurité et déclencher enquête CPI immédiate"], estimated_ethnic_cleansing_index: 8.44, last_updated: "2026-06-20" },
    { entity_id: "EC2-004", name: "Soudan/Darfour-Masalit — RSF Génocide 2023 & 11M Déplacés", country: "Afrique", sector: "RSF Masalit Massacres El Fasher 2024, 11M Déplacés Plus Grande Crise Monde, Omar Al-Bashir CPI Génocide & Répétition Pattern", composite_score: 86.0, forced_displacement_scale_score: 90.0, ethnic_massacre_documentation_score: 88.0, demographic_engineering_state_score: 80.0, ethnic_cleansing_impunity_score: 85.0, risk_level: "critique", primary_pattern: "deplacement_force_massif", key_signals: ["Déplacement forcé massif de Soudan/Darfour — campagne RSF d'extermination et déportation des Masalit créant la plus grande crise humanitaire mondiale en 2024", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer d'urgence le mécanisme R2P au Conseil de Sécurité et déclencher enquête CPI immédiate"], estimated_ethnic_cleansing_index: 8.6, last_updated: "2026-06-20" },
    { entity_id: "EC2-005", name: "Éthiopie/Tigré-Amhara — Famine Induite & Déplacements Ethniques", country: "Afrique de l'Est", sector: "500 000 Morts Conflit 2020-22, 2M Déplacés Tigré, Famine Induite ONU & Violence Ethnique Amhara-Tigré Réciproque", composite_score: 56.4, forced_displacement_scale_score: 55.0, ethnic_massacre_documentation_score: 58.0, demographic_engineering_state_score: 52.0, ethnic_cleansing_impunity_score: 62.0, risk_level: "élevé", primary_pattern: "segregation_ethnique_institutionnalisee", key_signals: ["Ségrégation ethnique institutionnalisée d'Éthiopie — conflit interethnique entre Tigréens et Amhara avec usage de la famine comme arme et déplacements massifs civils", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer les mécanismes conventionnels CERD et demander mission d'enquête urgente du Comité pour l'élimination des discriminations raciales"], estimated_ethnic_cleansing_index: 5.64, last_updated: "2026-06-20" },
    { entity_id: "EC2-006", name: "Israël/Gaza-Cisjordanie — Colonisation & Déplacements Palestiniens", country: "MENA", sector: "700 000 Colons Cisjordanie Illégaux, Maisons Démolies 55 000+ Depuis 1967, 1.7M Gaza Déplacés 2023-24 & CIJ Ordonnances", composite_score: 56.0, forced_displacement_scale_score: 55.0, ethnic_massacre_documentation_score: 52.0, demographic_engineering_state_score: 58.0, ethnic_cleansing_impunity_score: 60.0, risk_level: "élevé", primary_pattern: "epuration_ethnique_totale", key_signals: ["Épuration ethnique progressive d'Israël/Cisjordanie — colonisation systématique et démolitions d'habitations palestiniennes visant à modifier la composition démographique des territoires occupés", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer d'urgence le mécanisme R2P et appliquer les ordonnances contraignantes de la CIJ"], estimated_ethnic_cleansing_index: 5.6, last_updated: "2026-06-20" },
    { entity_id: "EC2-007", name: "Centrafrique/Anti-Balaka — Violences Intercommunautaires Cycliques", country: "Afrique Centrale", sector: "Musulmans Expulsés Bangui 2013-14, Anti-Balaka Attaques Chrétiennes, MINUSCA Protection Partielle & Impunité Locale Haute", composite_score: 29.65, forced_displacement_scale_score: 28.0, ethnic_massacre_documentation_score: 25.0, demographic_engineering_state_score: 32.0, ethnic_cleansing_impunity_score: 35.0, risk_level: "modéré", primary_pattern: "segregation_ethnique_institutionnalisee", key_signals: ["Tensions interethniques chroniques de Centrafrique — violences communautaires cycliques entre milices chrétiennes et musulmanes sans épuration ethnique étatique formalisée", "Populations ethniques déracinées — communautés expulsées de leurs terres ancestrales avec destruction systématique de leurs villages, archives et marqueurs identitaires", "Activer les mécanismes conventionnels CERD et renforcer le mandat de protection de la MINUSCA"], estimated_ethnic_cleansing_index: 2.97, last_updated: "2026-06-20" },
    { entity_id: "EC2-008", name: "TPIY/TPIR/CPI — Justice Transitionnelle & Prévention Génocide", country: "Global", sector: "TPIY 161 Mis en Examen, TPIR 93 Condamnés, Mécanisme ONU 2010 & Réseau Alerte Précoce Atrocités OSAPG", composite_score: 4.45, forced_displacement_scale_score: 5.0, ethnic_massacre_documentation_score: 4.0, demographic_engineering_state_score: 3.0, ethnic_cleansing_impunity_score: 6.0, risk_level: "faible", primary_pattern: "coexistence_ethnique_exemplaire", key_signals: ["TPIY/TPIR/CPI incarnent la coexistence ethnique exemplaire — justice transitionnelle effective, réconciliation post-conflit active et protections constitutionnelles des minorités", "Justice internationale pour les victimes — tribunaux pénaux internationaux établissant la responsabilité individuelle pour crimes contre l'humanité et génocide", "Partager les bonnes pratiques de réconciliation interethnique et financer les programmes UNESCO de dialogue et coexistence"], estimated_ethnic_cleansing_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { epuration_ethnique_totale: 2, massacre_demographique: 1, deplacement_force_massif: 2, segregation_ethnique_institutionnalisee: 2, coexistence_ethnique_exemplaire: 1 },
    top_risk_entities: ["Myanmar/Rohingyas — Opération Clearance & 700 000 Expulsés Bangladesh", "Bosnie/Serbes — Srebrenica 8000 Hommes & Épuration Ethnique", "Soudan/Darfour-Masalit — RSF Génocide 2023 & 11M Déplacés"],
    critical_alerts: ["Myanmar/Rohingyas: déplacement forcé massif", "Bosnie/Serbes: massacre démographique ciblé", "Russie/Ukraine: épuration ethnique totale", "Soudan/Darfour: déplacement forcé massif"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "ethnic_cleansing",
    confidence_score: 0.87,
    data_sources: ["icty_ictr_icc_case_database", "unhcr_global_displacement_report", "un_osapg_atrocity_prevention_framework"],
    entities,
    avg_estimated_ethnic_cleansing_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
