import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[social-protection-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Social Protection Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/social-protection-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Social Protection Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Social Protection Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "SP-001", name: "Afrique Sub-Saharienne — 85% Travailleurs Secteur Informel Exclus, Pensions 5% & Aléas", country: "Afrique de l'Ouest/Est", sector: "Afrique Sub-Saharienne 85% Emploi Informel OIT, Pensions Formelles <5% Population, Transferts Sociaux 1-2% PIB Insuffisants & 400M Personnes Zéro Protection Sociale", composite_score: 90.00, social_security_coverage_gap_score: 92.0, pension_system_collapse_score: 88.0, child_poverty_welfare_failure_score: 88.0, informal_worker_exclusion_score: 92.0, risk_level: "critique", primary_pattern: "lacune_couverture_securite_sociale", key_signals: ["Défaillance de la protection sociale documentée — Afrique Sub-Saharienne avec score composite 90.00/100 révélant des lacunes systémiques violant l'Article 22 de la DUDH et l'Article 9 du PIDESC sur le droit à la sécurité sociale", "Lacune de couverture sécurité sociale (92.0/100) — l'exclusion de 85% des travailleurs informels de toute protection sociale en Afrique Sub-Saharienne constitue une violation massive de l'Article 9 PIDESC et de la Recommandation OIT 202 sur les socles de protection sociale", "Activer le Rapporteur Spécial ONU sur l'extrême pauvreté et les droits humains et exiger l'application des Recommandations OIT 202 sur les Socles de Protection Sociale pour garantir un minimum de protection à chaque personne"], estimated_social_protection_index: 9.00, last_updated: "2026-06-20" },
    { entity_id: "SP-002", name: "Inde — 93% Informels Non-Couverts, MGNREGA Coupures & Aadhaar Exclusion Numérique", country: "Asie du Sud", sector: "Inde 93% Informels Non-Couverts Sécurité Sociale, MGNREGA Budget Coupé Pandémie, Aadhaar Exclusion Biométrique 200M Bénéficiaires Potentiels & PM Kisan Couverture Lacunaire", composite_score: 87.30, social_security_coverage_gap_score: 88.0, pension_system_collapse_score: 82.0, child_poverty_welfare_failure_score: 88.0, informal_worker_exclusion_score: 92.0, risk_level: "critique", primary_pattern: "exclusion_travailleurs_informels", key_signals: ["Défaillance de la protection sociale documentée — Inde avec score composite 87.30/100 révélant des lacunes systémiques violant l'Article 22 de la DUDH et l'Article 9 du PIDESC sur le droit à la sécurité sociale", "Lacune de couverture sécurité sociale (88.0/100) — l'exclusion de 93% des travailleurs informels de la sécurité sociale et les exclusions numériques par Aadhaar privant 200 millions de bénéficiaires potentiels constituent des violations du PIDESC Art 9", "Activer le Rapporteur Spécial ONU sur l'extrême pauvreté et les droits humains et exiger l'application des Recommandations OIT 202 sur les Socles de Protection Sociale pour garantir un minimum de protection à chaque personne"], estimated_social_protection_index: 8.73, last_updated: "2026-06-20" },
    { entity_id: "SP-003", name: "Haïti/Centrafrique — Zéro Système Sécurité Sociale Fonctionnel, Fonds International Bloqué", country: "Caraïbes/Afrique Centrale", sector: "Haïti Système Sécurité Sociale Effondré Instabilité, Centrafrique 0% Couverture Santé/Retraite, Dons Internationaux Détournés & Population 90%+ Sans Protection Formelle", composite_score: 86.40, social_security_coverage_gap_score: 85.0, pension_system_collapse_score: 88.0, child_poverty_welfare_failure_score: 90.0, informal_worker_exclusion_score: 82.0, risk_level: "critique", primary_pattern: "pauvrete_enfants_defaillance_aide", key_signals: ["Défaillance de la protection sociale documentée — Haïti/Centrafrique avec score composite 86.40/100 révélant des lacunes systémiques violant l'Article 22 de la DUDH et l'Article 9 du PIDESC sur le droit à la sécurité sociale", "Lacune de couverture sécurité sociale (85.0/100) — l'effondrement complet des systèmes de protection sociale en Haïti et l'absence de toute couverture en Centrafrique constituent des violations graves du PIDESC Art 9 exigeant une action internationale urgente", "Activer le Rapporteur Spécial ONU sur l'extrême pauvreté et les droits humains et exiger l'application des Recommandations OIT 202 sur les Socles de Protection Sociale pour garantir un minimum de protection à chaque personne"], estimated_social_protection_index: 8.64, last_updated: "2026-06-20" },
    { entity_id: "SP-004", name: "Brésil/Amérique Latine — Bolsa Familia Coupures Bolsonaro, Inégalités GINI & Informels", country: "Amérique Latine", sector: "Brésil Bolsa Familia Coupures 2021-22 Bolsonaro 3M Exclus, GINI 0.53 Inégalités Extrêmes, 40% Travailleurs Informels Non-Couverts INSS & Reforma Previdência Coupes", composite_score: 83.50, social_security_coverage_gap_score: 82.0, pension_system_collapse_score: 88.0, child_poverty_welfare_failure_score: 82.0, informal_worker_exclusion_score: 82.0, risk_level: "critique", primary_pattern: "effondrement_systeme_pension", key_signals: ["Défaillance de la protection sociale documentée — Brésil/Amérique Latine avec score composite 83.50/100 révélant des lacunes systémiques violant l'Article 22 de la DUDH et l'Article 9 du PIDESC sur le droit à la sécurité sociale", "Lacune de couverture sécurité sociale (82.0/100) — les coupures de Bolsa Familia excluant 3 millions de bénéficiaires sous Bolsonaro et les réformes des retraites réduisant la protection des travailleurs constituent des régressions du droit à la sécurité sociale", "Activer le Rapporteur Spécial ONU sur l'extrême pauvreté et les droits humains et exiger l'application des Recommandations OIT 202 sur les Socles de Protection Sociale pour garantir un minimum de protection à chaque personne"], estimated_social_protection_index: 8.35, last_updated: "2026-06-20" },
    { entity_id: "SP-005", name: "USA — Medicaid Cliffs, Aucun Congé Parental Fédéral & 11% Sans Assurance Maladie", country: "Amérique du Nord", sector: "USA Seul Pays OCDE Sans Congé Parental Fédéral, 11% Population 37M Sans Assurance Maladie 2022, Medicaid Cliff Traps Travailleurs Pauvres & SNAP Benefits Conditionnalité Sévère", composite_score: 54.10, social_security_coverage_gap_score: 52.0, pension_system_collapse_score: 48.0, child_poverty_welfare_failure_score: 62.0, informal_worker_exclusion_score: 55.0, risk_level: "élevé", primary_pattern: "pauvrete_enfants_defaillance_aide", key_signals: ["Défaillance de la protection sociale documentée — USA avec score composite 54.10/100 révélant des lacunes systémiques dans la protection sociale violant les engagements internationaux sous la DUDH Art 22 (le PIDESC n'étant pas ratifié par les USA)", "Lacune de couverture sécurité sociale (52.0/100) — l'absence de congé parental fédéral et les 37 millions de personnes sans assurance maladie placent les USA parmi les pays développés les moins protecteurs en matière de sécurité sociale", "Ratifier le PIDESC et créer un système universel de protection sociale incluant congé parental fédéral, assurance maladie universelle et allocations familiales conformément aux standards OIT pour les pays à revenu élevé"], estimated_social_protection_index: 5.41, last_updated: "2026-06-20" },
    { entity_id: "SP-006", name: "Europe/Austérité — Grèce Retraites -45%, Espagne Chômage 28% 2013 & Precariat", country: "Europe", sector: "Grèce Retraites Coupées -45% Troïka, Espagne Chômage 28% 2013 Jeunes 55%, Austérité UK Universal Credit Dysfonctionnel & Précariat Européen Gig Economy Non-Couvert", composite_score: 52.85, social_security_coverage_gap_score: 52.0, pension_system_collapse_score: 55.0, child_poverty_welfare_failure_score: 50.0, informal_worker_exclusion_score: 55.0, risk_level: "élevé", primary_pattern: "exclusion_travailleurs_informels", key_signals: ["Défaillance de la protection sociale documentée — Europe/Austérité avec score composite 52.85/100 révélant des régressions des droits sociaux liées à l'austérité critiquées par le Comité PIDESC comme violations de l'obligation de non-régression", "Lacune de couverture sécurité sociale (52.0/100) — les coupes de -45% des retraites grecques et l'exclusion des travailleurs de plateforme de la protection sociale constituent des violations de l'obligation de non-régression du PIDESC et de la Charte Sociale Européenne", "Imposer des évaluations d'impact sur les droits sociaux avant toute mesure d'austérité conformément aux recommandations du Comité PIDESC et étendre la protection sociale aux travailleurs de plateforme via la Directive UE sur les conditions de travail des travailleurs de plateforme 2024"], estimated_social_protection_index: 5.29, last_updated: "2026-06-20" },
    { entity_id: "SP-007", name: "Japon/Corée — Working Poor, Kiso Seikatsu Faillite & Non-Regular Workers Exclus", country: "Asie du Nord-Est", sector: "Japon 7M Non-Regular Workers Non-Couverts Pension/Santé, Kiso Seikatsu (Aide Sociale) Stigmate, Corée Working Poor 5M & Personnes Âgées Pauvreté 40% Retraites Insuffisantes", composite_score: 29.40, social_security_coverage_gap_score: 28.0, pension_system_collapse_score: 32.0, child_poverty_welfare_failure_score: 28.0, informal_worker_exclusion_score: 30.0, risk_level: "modéré", primary_pattern: "effondrement_systeme_pension", key_signals: ["Défis de la protection sociale au Japon/Corée — 7 millions de travailleurs non-réguliers au Japon exclus de la pension et de la santé, et 40% de personnes âgées en pauvreté en Corée révèlent des lacunes dans des systèmes économiquement avancés", "Lacune de couverture sécurité sociale (28.0/100) — l'exclusion systémique des travailleurs non-réguliers de la protection sociale au Japon et le taux de pauvreté des retraités en Corée constituent des violations partielles du droit à la sécurité sociale (PIDESC Art 9)", "Réformer les systèmes de protection sociale au Japon et en Corée pour inclure les travailleurs non-réguliers dans les régimes de pension et de santé conformément aux principes universels de la Recommandation OIT 202 sur les socles de protection sociale"], estimated_social_protection_index: 2.94, last_updated: "2026-06-20" },
    { entity_id: "SP-008", name: "OIT/PIDESC — Recommandation 202 Socles Protection Sociale & Plancher Social Mondial", country: "Global", sector: "OIT Recommandation 202 Socles Protection Sociale 2012, PIDESC Article 9 Sécurité Sociale, OIT Rapport Mondial Protection Sociale 2020-22 & Rapport ONU Rapporteur Extrême Pauvreté", composite_score: 4.45, social_security_coverage_gap_score: 5.0, pension_system_collapse_score: 4.0, child_poverty_welfare_failure_score: 3.0, informal_worker_exclusion_score: 6.0, risk_level: "faible", primary_pattern: "exclusion_travailleurs_informels", key_signals: ["OIT/PIDESC incarne le cadre exemplaire de la protection sociale — Recommandation 202 sur les socles de protection sociale et Article 9 PIDESC créant une architecture universelle de droits sociaux minimaux garantis à chaque personne sans discrimination", "Recommandation OIT 202 — définit les socles nationaux de protection sociale comme des ensembles minimaux de garanties de sécurité sociale assurant au moins l'accès aux soins et la sécurité de revenu pour les enfants, travailleurs actifs et personnes âgées", "Universaliser les socles de protection sociale via le Fonds mondial de protection sociale proposé par l'OIT et le G20, et tripler l'aide publique au développement dédiée aux systèmes de protection sociale dans les pays à revenu faible et intermédiaire"], estimated_social_protection_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { lacune_couverture_securite_sociale: 1, effondrement_systeme_pension: 2, pauvrete_enfants_defaillance_aide: 2, exclusion_travailleurs_informels: 3 },
    top_risk_entities: ["Afrique Sub-Saharienne — 85% Travailleurs Secteur Informel Exclus, Pensions 5% & Aléas", "Inde — 93% Informels Non-Couverts, MGNREGA Coupures & Aadhaar Exclusion Numérique", "Haïti/Centrafrique — Zéro Système Sécurité Sociale Fonctionnel, Fonds International Bloqué"],
    critical_alerts: ["Afrique Sub-Saharienne: lacune couverture sécurité sociale", "Inde: exclusion travailleurs informels", "Haïti/Centrafrique: pauvreté enfants défaillance aide", "Brésil: effondrement système pension"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "social_protection",
    confidence_score: 0.81,
    data_sources: ["ilo_world_social_protection_report", "un_special_rapporteur_extreme_poverty_human_rights", "world_bank_aspire_social_protection_database"],
    entities,
    avg_estimated_social_protection_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
