import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[prison-torture-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Prison Torture Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/prison-torture-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Prison Torture Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Prison Torture Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "PT-001", name: "RPDC/Kim Jong-Un — Camps Politiques 150 000 Détenus & Torture Systématique", country: "Asie du Nord-Est", sector: "Camp 14/22 Survivant Shin Dong-Hyuk, 150 000 Prisonniers Politiques OHCHR, Torture Standard Officielle & Privation Sommeil Systématique", composite_score: 93.0, systematic_torture_rate_score: 95.0, detention_condition_severity_score: 92.0, impunity_perpetrators_score: 90.0, medical_care_denial_score: 95.0, risk_level: "critique", primary_pattern: "torture_systematique_detention", key_signals: ["Torture systématique en RPDC — 150 000 détenus dans des camps politiques (kwanliso) subissant torture officielle, travaux forcés, exécutions sommaires et privation de nourriture documentés par la Commission d'Enquête ONU 2014", "Crime contre l'humanité — la torture systématique et généralisée en RPDC constitue un crime contre l'humanité selon le Statut de Rome, engageant la responsabilité personnelle du dirigeant Kim Jong-Un", "Activer le Rapporteur Spécial ONU sur la torture et saisir la CPI pour crimes contre l'humanité incluant torture, meurtres et disparitions forcées dans les camps politiques nord-coréens"], estimated_prison_torture_index: 9.3, last_updated: "2026-06-20" },
    { id: "PT-002", name: "Syrie/Assad — Sednaya 'Abattoir', 13 000 Pendus & César Photos 55 000 Victimes", country: "MENA", sector: "Sednaya Prison Exécutions 2011-24, 13 000 Personnes Pendues, César Photos 55 000 Corps Victimes Torture & Rapport Amnesty 2017 Abattoir Humain", composite_score: 92.7, systematic_torture_rate_score: 92.0, detention_condition_severity_score: 95.0, impunity_perpetrators_score: 95.0, medical_care_denial_score: 88.0, risk_level: "critique", primary_pattern: "torture_systematique_detention", key_signals: ["Torture systématique en Syrie/Assad — prison Sednaya qualifiée d'abattoir humain par Amnesty avec 13 000 pendus et 55 000 photos de corps de victimes de torture (rapport César) documentant les crimes du régime", "Crime contre l'humanité — la torture systématique dans les prisons syriennes constitue un crime contre l'humanité selon le Statut de Rome, avec des preuves directes documentées par les Nations Unies", "Activer la Commission Internationale Indépendante d'Enquête sur la Syrie et saisir le IIIM pour poursuite des responsables de torture dans les prisons syriennes"], estimated_prison_torture_index: 9.27, last_updated: "2026-06-20" },
    { id: "PT-003", name: "Chine/Xinjiang — Camps Rééducation 1M+ Internés & Torture Témoignages Systématiques", country: "Asie", sector: "1M+ Ouïghours Internés Camps Rééducation 2017-24, Tortures Témoignages OHCHR, Privation Sommeil & Tribunal Ouïghour Génocide Londres 2021", composite_score: 87.65, systematic_torture_rate_score: 88.0, detention_condition_severity_score: 85.0, impunity_perpetrators_score: 88.0, medical_care_denial_score: 90.0, risk_level: "critique", primary_pattern: "detention_conditions_inhumaines", key_signals: ["Conditions de détention inhumaines en Chine/Xinjiang — 1 million+ Ouïghours internés dans des camps avec témoignages systématiques de tortures, viols et privation de sommeil documentés par le rapport OHCHR 2022", "Crime contre l'humanité — le Tribunal Ouïghour de Londres 2021 a conclu à des actes de torture, viol et violences sexuelles systématiques équivalant à des crimes contre l'humanité", "Activer le Rapporteur Spécial ONU sur la torture et mettre en œuvre les recommandations OHCHR pour accès indépendant aux camps de détention au Xinjiang"], estimated_prison_torture_index: 8.77, last_updated: "2026-06-20" },
    { id: "PT-004", name: "Égypte/El-Sisi — Prison Scorpion, 60 000 Prisonniers Politiques & Torture Institutionnalisée", country: "MENA", sector: "60 000 Prisonniers Politiques Sisi, Prison Scorpion Isolement Sensoriel, Détention Préventive Illimitée & HRW Torture Institutionnalisée Rapportée 2020-24", composite_score: 83.65, systematic_torture_rate_score: 85.0, detention_condition_severity_score: 82.0, impunity_perpetrators_score: 85.0, medical_care_denial_score: 82.0, risk_level: "critique", primary_pattern: "impunite_tortionnaires", key_signals: ["Impunité des tortionnaires en Égypte/El-Sisi — 60 000 prisonniers politiques avec torture institutionnalisée à la prison Scorpion, aucune poursuite contre les agents de l'État malgré les rapports HRW et Amnesty", "Violation de la Convention contre la Torture — les pratiques de détention égyptiennes violent la CAT ratifiée en 1986, avec mécanisme d'examen périodique révélant une absence totale d'accountability", "Activer le Comité ONU contre la Torture (CAT) pour examen d'urgence de l'Égypte et conditionner l'aide militaire américaine à l'amélioration des conditions de détention"], estimated_prison_torture_index: 8.37, last_updated: "2026-06-20" },
    { id: "PT-005", name: "USA/CIA — Guantanamo, Black Sites & Rapport Sénat 2014 'Enhanced Interrogation'", country: "Amérique du Nord", sector: "Rapport Sénat 2014 Techniques Torture CIA Confirmées, Waterboarding 183 Fois KSM, 780 Détenus Guantanamo Sans Procès & Black Sites Thaïlande/Pologne/Roumanie", composite_score: 54.85, systematic_torture_rate_score: 52.0, detention_condition_severity_score: 55.0, impunity_perpetrators_score: 58.0, medical_care_denial_score: 55.0, risk_level: "élevé", primary_pattern: "impunite_tortionnaires", key_signals: ["Impunité des tortionnaires USA/CIA — rapport du Sénat 2014 documentant tortures (waterboarding, privation de sommeil, alimentation rectale) dans des sites noirs à travers le monde sans aucune poursuite judiciaire", "Violation de la Convention contre la Torture — les techniques d'interrogatoire CIA constituent de la torture selon le droit international, et l'absence de poursuites viole l'obligation de rendre compte de la Convention CAT", "Fermer Guantanamo conformément aux engagements répétés des administrations américaines et poursuivre les responsables de la conception du programme de torture CIA devant la justice"], estimated_prison_torture_index: 5.48, last_updated: "2026-06-20" },
    { id: "PT-006", name: "Turquie/Erdoğan — Post-Coup 150 000 Détenus & CPT Mauvais Traitements Généralisés", country: "Europe/MENA", sector: "Post-Coup 2016 150 000 Détenus Purges, Rapport CPT Mauvais Traitements Généralisés 2017, Kurdes Conditions Isolement & Erdoğan Suspension Garanties CEDH", composite_score: 51.15, systematic_torture_rate_score: 48.0, detention_condition_severity_score: 55.0, impunity_perpetrators_score: 52.0, medical_care_denial_score: 50.0, risk_level: "élevé", primary_pattern: "detention_conditions_inhumaines", key_signals: ["Conditions de détention inhumaines en Turquie/Erdoğan — 150 000 détenus post-coup avec rapport CPT 2017 documentant mauvais traitements généralisés incluant coups, positions de stress et menaces lors des gardes à vue", "Violation des standards européens — les pratiques de détention turques violent la Convention Européenne des Droits de l'Homme dont la Turquie est partie, entraînant de nombreuses condamnations à la Cour EDH", "Activer les mécanismes du Conseil de l'Europe et conditionner les négociations d'adhésion UE à l'amélioration des conditions de détention et à la fin des mauvais traitements documentés"], estimated_prison_torture_index: 5.11, last_updated: "2026-06-20" },
    { id: "PT-007", name: "Brésil/PCC — Prisons Surpeuplées +70%, Massacres Nordeste & Conditions Inhumaines", country: "Amérique du Sud", sector: "900 000 Détenus Brésil +70% Surpopulation, PCC/FDN Violence Inter-Gang, Nordeste Massacres Prisons 2017 & Conditions Sanitaires Inhumaines DEPEN", composite_score: 29.4, systematic_torture_rate_score: 28.0, detention_condition_severity_score: 32.0, impunity_perpetrators_score: 28.0, medical_care_denial_score: 30.0, risk_level: "modéré", primary_pattern: "detention_conditions_inhumaines", key_signals: ["Conditions de détention inhumaines au Brésil/PCC — surpopulation carcérale à +70% avec violences de gangs PCC/FDN ayant causé des massacres au Nordeste en 2017 et conditions sanitaires inhumaines documentées", "Violation des droits humains — les conditions carcérales brésiliennes violent les Règles Nelson Mandela de l'ONU sur le traitement des détenus, et l'État ne garantit pas la sécurité des personnes détenues", "Accélérer les réformes du système pénitentiaire brésilien conformément aux Règles Nelson Mandela et financer la réduction de la surpopulation par des alternatives à l'incarcération"], estimated_prison_torture_index: 2.94, last_updated: "2026-06-20" },
    { id: "PT-008", name: "CPT/CAT-ONU — Prévention Torture, Protocole OPCAT & Rapporteur Spécial", country: "Global", sector: "CAT ONU Convention 173 États, OPCAT Protocole Facultatif MNP Nationaux, CPT Conseil Europe 500+ Visites Pays & Rapporteur Spécial ONU Torture Mandat", composite_score: 4.45, systematic_torture_rate_score: 5.0, detention_condition_severity_score: 4.0, impunity_perpetrators_score: 3.0, medical_care_denial_score: 6.0, risk_level: "faible", primary_pattern: "impunite_tortionnaires", key_signals: ["CPT/CAT-ONU incarnent la prévention exemplaire de la torture — Convention CAT ratifiée par 173 États, Protocole OPCAT créant des mécanismes nationaux de prévention et Rapporteur Spécial ONU avec mandat de visite", "Convention ONU contre la Torture 1984 — obligation erga omnes d'interdire, prévenir, enquêter et poursuivre la torture, avec mécanisme d'examen périodique des États parties au Comité CAT", "Partager les méthodologies CPT de documentation des lieux de détention et renforcer l'OPCAT pour garantir des visites indépendantes dans tous les lieux de privation de liberté"], estimated_prison_torture_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { torture_systematique_detention: 2, detention_conditions_inhumaines: 3, impunite_tortionnaires: 3 },
    top_risk_entities: ["RPDC/Kim Jong-Un — Camps Politiques 150 000 Détenus & Torture Systématique", "Syrie/Assad — Sednaya 'Abattoir', 13 000 Pendus & César Photos 55 000 Victimes", "Chine/Xinjiang — Camps Rééducation 1M+ Internés & Torture Témoignages Systématiques"],
    critical_alerts: ["RPDC/Kim Jong-Un: torture systématique détention", "Syrie/Assad: torture systématique détention", "Chine/Xinjiang: détention conditions inhumaines", "Égypte/El-Sisi: impunité tortionnaires"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "prison_torture",
    confidence_score: 0.86,
    data_sources: ["un_cat_reports_states_parties", "amnesty_international_torture_reports", "hrw_world_report_detention_conditions"],
    entities,
    avg_estimated_prison_torture_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
