import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[environmental-racism-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Environmental Racism Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/environmental-racism-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Environmental Racism Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Environmental Racism Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "ER-001", name: "Nigeria/Delta Niger — Shell Ogoniland, Pétrole Igbo & Pollution 50 Ans Sans Réparation", country: "Afrique de l'Ouest", sector: "Ogoniland Pollution Shell 50 Ans, Ken Saro-Wiwa Exécuté 1995, 11 000 Déversements Documentés & 40B$ Pétrole 1 $ Développement Local", composite_score: 91.5, toxic_exposure_minority_score: 95.0, environmental_sacrifice_zone_score: 92.0, regulatory_discrimination_score: 88.0, environmental_justice_impunity_score: 90.0, risk_level: "critique", primary_pattern: "exposition_toxique_minorites", key_signals: ["Exposition toxique disproportionnée des minorités de Nigeria/Delta Niger — communautés Ogoni et Ijaw concentrées autour des sites pétroliers Shell avec 11 000 déversements et Ken Saro-Wiwa exécuté pour avoir protesté", "Discrimination intersectionnelle — le racisme environnemental combine discrimination raciale et violence écologique, violant simultanément le droit à la santé, à un environnement sain et à l'égalité de traitement", "Activer le Rapporteur Spécial ONU sur les substances dangereuses pour audit des inégalités environnementales et demander la pleine mise en œuvre du plan de nettoyage UNEP Ogoniland"], estimated_environmental_racism_index: 9.15, last_updated: "2026-06-20" },
    { id: "ER-002", name: "USA/Cancer Alley — Louisiane Noire, Plastiques & Inégalités EPA Documentées", country: "Amérique du Nord", sector: "Cancer Alley 100+ Usines Pétrochimiques, Populations Noires 85%+ Zone, Mortalité Cancer +700%, EPA Consentement Décret 2023 Annulé", composite_score: 89.0, toxic_exposure_minority_score: 90.0, environmental_sacrifice_zone_score: 88.0, regulatory_discrimination_score: 92.0, environmental_justice_impunity_score: 85.0, risk_level: "critique", primary_pattern: "discrimination_reglementaire", key_signals: ["Discrimination réglementaire d'USA/Cancer Alley — EPA ayant documenté que les populations noires de Louisiane respirent 54% plus d'air toxique que les blancs avant d'annuler les décrets de protection en 2023", "Discrimination intersectionnelle — le racisme environnemental combine discrimination raciale et violence écologique, violant simultanément le droit à la santé, à un environnement sain et à l'égalité de traitement", "Activer le Rapporteur Spécial ONU sur les substances dangereuses pour audit des inégalités environnementales et renforcer l'application des règles EPA dans les communautés de couleur"], estimated_environmental_racism_index: 8.9, last_updated: "2026-06-20" },
    { id: "ER-003", name: "Amazonie/Yanomami — Mercure Orpaillage, Malnutrition Crise & Morts Garimpeiros", country: "Amérique du Sud", sector: "Orpaillage Illégal 30 000 Garimpeiros Yanomami 2019-23, Mercure Contamination Rivières, Malnutrition Sévère & Morts Déclarées Urgence", composite_score: 87.0, toxic_exposure_minority_score: 88.0, environmental_sacrifice_zone_score: 90.0, regulatory_discrimination_score: 82.0, environmental_justice_impunity_score: 88.0, risk_level: "critique", primary_pattern: "zone_sacrifice_environnemental", key_signals: ["Zone de sacrifice environnemental pour Amazonie/Yanomami — terres autochtones Yanomami systématiquement envahies par 30 000 garimpeiros illégaux avec contamination mercure des rivières déclarée urgence sanitaire en 2023", "Discrimination intersectionnelle — le racisme environnemental combine discrimination raciale et violence écologique, violant simultanément le droit à la santé, à un environnement sain et à l'égalité de traitement", "Activer le Rapporteur Spécial ONU sur les droits des peuples autochtones et exiger l'expulsion immédiate des orpailleurs illégaux des terres Yanomami"], estimated_environmental_racism_index: 8.7, last_updated: "2026-06-20" },
    { id: "ER-004", name: "Inde/Dalits — Castes Basses Usines Déchets & Nettoyeurs Manuels", country: "Asie du Sud", sector: "Dalits 80% Travailleurs Déchets Informels, Nettoyeurs Manuels 58 000 Officiel, Castes Zones Industrielles Polluées & Loi Interdiction Non Appliquée", composite_score: 84.4, toxic_exposure_minority_score: 85.0, environmental_sacrifice_zone_score: 82.0, regulatory_discrimination_score: 88.0, environmental_justice_impunity_score: 82.0, risk_level: "critique", primary_pattern: "discrimination_reglementaire", key_signals: ["Discrimination réglementaire en Inde/Dalits — 80% des travailleurs des déchets sont Dalits et 58 000 nettoyeurs manuels encore actifs malgré l'interdiction légale depuis 1993, faute d'application", "Discrimination intersectionnelle — le racisme environnemental combine discrimination de caste et violence écologique, violant simultanément le droit à la dignité, à la santé et à l'égalité de traitement", "Activer le Rapporteur Spécial ONU sur les formes contemporaines d'esclavage et exiger l'application effective de la loi d'interdiction du nettoyage manuel"], estimated_environmental_racism_index: 8.44, last_updated: "2026-06-20" },
    { id: "ER-005", name: "Kanaky/Nouvelle-Calédonie — Nickel Kanak & Terres Coutumières Sacrifiées", country: "Océanie", sector: "Kanak Terres Coutumières Zones Extraction Nickel, Vaie Nickel Pollution Rivières, Communautés Sans Compensation & Référendum Indépendance Lié", composite_score: 56.6, toxic_exposure_minority_score: 55.0, environmental_sacrifice_zone_score: 62.0, regulatory_discrimination_score: 52.0, environmental_justice_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "zone_sacrifice_environnemental", key_signals: ["Zone de sacrifice environnemental pour Kanaky/Nouvelle-Calédonie — terres coutumières Kanak systématiquement sacrifiées pour l'extraction de nickel avec pollution des rivières et absence de compensation équitable", "Discrimination intersectionnelle — le racisme environnemental colonial combine discrimination ethnique et dépouillement territorial, violant les droits des peuples autochtones à leurs terres et ressources", "Activer le Rapporteur Spécial ONU sur les droits des peuples autochtones et exiger un consentement libre et éclairé pour tout projet minier sur terres coutumières"], estimated_environmental_racism_index: 5.66, last_updated: "2026-06-20" },
    { id: "ER-006", name: "Chine/Guangdong — Recyclage E-Waste Minorités Migrantes & Guiyu Pollution", country: "Asie", sector: "Guiyu Village E-Waste Recycleurs Migrants, Plomb 190x Seuil Enfants, Contamination Sols & Travailleurs Sans Protection Réglementation", composite_score: 54.85, toxic_exposure_minority_score: 52.0, environmental_sacrifice_zone_score: 55.0, regulatory_discrimination_score: 58.0, environmental_justice_impunity_score: 55.0, risk_level: "élevé", primary_pattern: "discrimination_reglementaire", key_signals: ["Discrimination réglementaire en Chine/Guangdong — normes environnementales non appliquées à Guiyu où des travailleurs migrants recyclent des déchets électroniques avec taux de plomb dans le sang des enfants 190 fois le seuil OMS", "Discrimination intersectionnelle — le racisme environnemental combine vulnérabilité des migrants et exposition toxique, violant simultanément le droit à la santé, à l'information et à une protection réglementaire égale", "Activer le Rapporteur Spécial ONU sur les substances dangereuses et exiger l'application des normes de protection dans les zones de recyclage e-waste pour travailleurs migrants"], estimated_environmental_racism_index: 5.49, last_updated: "2026-06-20" },
    { id: "ER-007", name: "Europe/Roms — Décharges Roumanie/Bulgarie & Sites Contaminés Communautés", country: "Europe", sector: "Roms Décharges Proximitée Roumanie/Bulgarie, Sites Contaminés Camps Informels, Plomb Sang Enfants Roms 3x Moyenne & UE Inaction", composite_score: 30.4, toxic_exposure_minority_score: 30.0, environmental_sacrifice_zone_score: 32.0, regulatory_discrimination_score: 28.0, environmental_justice_impunity_score: 32.0, risk_level: "modéré", primary_pattern: "zone_sacrifice_environnemental", key_signals: ["Zone de sacrifice environnemental pour Europe/Roms — camps Roms en Roumanie et Bulgarie systématiquement placés à proximité de décharges avec taux de plomb dans le sang des enfants trois fois la moyenne nationale", "Discrimination intersectionnelle — le racisme environnemental anti-Roms combine discrimination ethnique et abandon territorial en Europe même, dans des États membres de l'Union Européenne", "Activer la Commission Européenne pour enquête sur discrimination environnementale anti-Roms et financer la dépollution des sites contaminés occupés par des communautés Roms"], estimated_environmental_racism_index: 3.04, last_updated: "2026-06-20" },
    { id: "ER-008", name: "PNUE/Enviro-Justice — Droit Environnement Sain & Rapporteur ONU", country: "Global", sector: "ONU Résolution Droit Environnement Sain 2022, PNUE Enviro-Justice Framework, Aarhus Convention & Rapporteur Substances Dangereuses", composite_score: 4.45, toxic_exposure_minority_score: 5.0, environmental_sacrifice_zone_score: 4.0, regulatory_discrimination_score: 3.0, environmental_justice_impunity_score: 6.0, risk_level: "faible", primary_pattern: "impunite_justice_environnementale", key_signals: ["PNUE/Enviro-Justice incarne la justice environnementale exemplaire — Résolution ONU 2022 sur le droit à un environnement sain et mécanismes de Rapporteur Spécial pour les cas de discrimination environnementale", "Résolution ONU A/RES/76/300 de 2022 — reconnaissance universelle du droit à un environnement propre, sain et durable créant une base légale pour combattre le racisme environnemental", "Partager les méthodologies PNUE de cartographie des inégalités environnementales et renforcer la Convention d'Aarhus pour garantir l'accès à la justice en matière environnementale pour les minorités"], estimated_environmental_racism_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { exposition_toxique_minorites: 1, zone_sacrifice_environnemental: 3, discrimination_reglementaire: 3, impunite_justice_environnementale: 1 },
    top_risk_entities: ["Nigeria/Delta Niger — Shell Ogoniland, Pétrole Igbo & Pollution 50 Ans Sans Réparation", "USA/Cancer Alley — Louisiane Noire, Plastiques & Inégalités EPA Documentées", "Amazonie/Yanomami — Mercure Orpaillage, Malnutrition Crise & Morts Garimpeiros"],
    critical_alerts: ["Nigeria/Delta Niger: exposition toxique minorités", "USA/Cancer Alley: discrimination réglementaire", "Amazonie/Yanomami: zone sacrifice environnemental", "Inde/Dalits: discrimination réglementaire"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "environmental_racism",
    confidence_score: 0.79,
    data_sources: ["amnesty_international_pollution_reports", "ejatlas_environmental_justice_database", "unep_environmental_defenders_reports"],
    entities,
    avg_estimated_environmental_racism_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
