import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[debt-trap-economic-coercion-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/debt-trap-economic-coercion-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "DTEC-001", name: "Sri Lanka/Port Hambantota Cédé Chine 99 Ans", country: "Asie du Sud", sector: "Faillite 2022, Port Hambantota Loué Chine 99 Ans, FMI 2.9B$, Coupures Électricité & Pénuries Médicaments Population 22M", sovereign_debt_coercion_loss_autonomy_score: 94.0, conditionality_austerity_social_rights_erosion_score: 90.0, resource_extraction_dispossession_scale_score: 88.0, debt_restructuring_access_justice_deficit_score: 85.0, composite_score: 89.85, risk_level: "critique", primary_pattern: "piege_dette_souverainete_confisquee", key_signals: ["Piège de la dette critique de Sri Lanka/Port Hambantota Cédé Chine 99 Ans — perte de souveraineté économique contraignant les politiques sociales, sanitaires et éducatives, violant le droit des peuples à disposer d'eux-mêmes (PIDCP Art.1)", "Austérité destructrice des droits — les conditionnalités imposées par les créanciers provoquent des coupes dans les systèmes de santé, d'éducation et de protection sociale, violant le PIDESC Art.2", "Spoliation des ressources naturelles — l'accès aux ressources comme garantie de prêt prive les populations autochtones et locales de leurs droits fonciers et de leur droit au développement"], estimated_debt_trap_economic_coercion_rights_index: 8.99, last_updated: "2026-06-21" },
    { id: "DTEC-002", name: "Zambie/Faillite Souveraine 2020 BRI Chine", country: "Afrique Australe", sector: "1er Défaut Afrique Subsaharienne Covid-19, 17B$ Dette Chine, Restructuration 3 Ans Bloquée, Cuivre Ressource Garantie & 18M Personnes Impact", sovereign_debt_coercion_loss_autonomy_score: 88.0, conditionality_austerity_social_rights_erosion_score: 85.0, resource_extraction_dispossession_scale_score: 82.0, debt_restructuring_access_justice_deficit_score: 88.0, composite_score: 86.05, risk_level: "critique", primary_pattern: "deficit_restructuration_acces_justice", key_signals: ["Piège de la dette critique de Zambie/Faillite Souveraine 2020 BRI Chine — perte de souveraineté économique contraignant les politiques sociales, sanitaires et éducatives, violant le droit des peuples à disposer d'eux-mêmes (PIDCP Art.1)", "Austérité destructrice des droits — les conditionnalités imposées par les créanciers provoquent des coupes dans les systèmes de santé, d'éducation et de protection sociale, violant le PIDESC Art.2", "Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 8.61, last_updated: "2026-06-21" },
    { id: "DTEC-003", name: "Grèce/Troïka Austérité 2010-2018 Droits", country: "Europe du Sud", sector: "86B€ Renflouement FMI/BCE/CE, Coupes Retraites 30%, Santé 25%, Chômage 27% Peak, Suicide +30% & 450 000 Émigrants Qualifiés", sovereign_debt_coercion_loss_autonomy_score: 82.0, conditionality_austerity_social_rights_erosion_score: 92.0, resource_extraction_dispossession_scale_score: 68.0, debt_restructuring_access_justice_deficit_score: 75.0, composite_score: 80.35, risk_level: "critique", primary_pattern: "austerite_erosion_droits_sociaux", key_signals: ["Coercition économique de Grèce/Troïka Austérité 2010-2018 Droits — conditions d'emprunt limitant la capacité de l'État à protéger les droits économiques, sociaux et culturels de sa population", "Austérité destructrice des droits — les conditionnalités imposées par les créanciers provoquent des coupes dans les systèmes de santé, d'éducation et de protection sociale, violant le PIDESC Art.2", "Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 8.04, last_updated: "2026-06-21" },
    { id: "DTEC-004", name: "Pakistan/FMI 23ème Programme Conditionnalités", country: "Asie du Sud", sector: "23ème Programme FMI Histoire, 7B$ 2023, Suppression Subventions Énergie & Carburant, Inflation 38%, 40% Population Sous Seuil Pauvreté", sovereign_debt_coercion_loss_autonomy_score: 80.0, conditionality_austerity_social_rights_erosion_score: 88.0, resource_extraction_dispossession_scale_score: 62.0, debt_restructuring_access_justice_deficit_score: 78.0, composite_score: 78.1, risk_level: "critique", primary_pattern: "austerite_erosion_droits_sociaux", key_signals: ["Coercition économique de Pakistan/FMI 23ème Programme Conditionnalités — conditions d'emprunt limitant la capacité de l'État à protéger les droits économiques, sociaux et culturels de sa population", "Austérité destructrice des droits — les conditionnalités imposées par les créanciers provoquent des coupes dans les systèmes de santé, d'éducation et de protection sociale, violant le PIDESC Art.2", "Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 7.81, last_updated: "2026-06-21" },
    { id: "DTEC-005", name: "Éthiopie/BRI Dette Chine Infrastructure 2023", country: "Afrique de l'Est", sector: "13.7B$ Dette Chine Chemins Fer & Énergie, Restructuration 2023 Lente, Conflit Tigré Aggrave, FMI 3.4B$ & Conditionnalités Réforme Fiscale", sovereign_debt_coercion_loss_autonomy_score: 55.0, conditionality_austerity_social_rights_erosion_score: 58.0, resource_extraction_dispossession_scale_score: 62.0, debt_restructuring_access_justice_deficit_score: 60.0, composite_score: 58.45, risk_level: "élevé", primary_pattern: "extraction_ressources_spoliation", key_signals: ["Coercition économique de Éthiopie/BRI Dette Chine Infrastructure 2023 — conditions d'emprunt limitant la capacité de l'État à protéger les droits économiques, sociaux et culturels de sa population", "Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 5.85, last_updated: "2026-06-21" },
    { id: "DTEC-006", name: "Argentine/FMI 44B$ Défaut Cyclique", country: "Amérique du Sud", sector: "44B$ FMI 2018 Plus Grand Programme Histoire, 9ème Défaut 2020, Péronisme vs Conditionnalités, Inflation 130% 2023 & Dollarisation Milei", sovereign_debt_coercion_loss_autonomy_score: 60.0, conditionality_austerity_social_rights_erosion_score: 68.0, resource_extraction_dispossession_scale_score: 48.0, debt_restructuring_access_justice_deficit_score: 52.0, composite_score: 58.4, risk_level: "élevé", primary_pattern: "austerite_erosion_droits_sociaux", key_signals: ["Coercition économique de Argentine/FMI 44B$ Défaut Cyclique — conditions d'emprunt limitant la capacité de l'État à protéger les droits économiques, sociaux et culturels de sa population", "Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 5.84, last_updated: "2026-06-21" },
    { id: "DTEC-007", name: "G20/Cadre Commun Restructuration Dettes", country: "Global", sector: "G20 Cadre Commun 2020, Club de Paris, DSSI Suspension Service Dette, 50+ Pays Éligibles & Délais Restructuration 3-4 Ans Inefficaces", sovereign_debt_coercion_loss_autonomy_score: 22.0, conditionality_austerity_social_rights_erosion_score: 20.0, resource_extraction_dispossession_scale_score: 18.0, debt_restructuring_access_justice_deficit_score: 30.0, composite_score: 22.1, risk_level: "modéré", primary_pattern: "deficit_restructuration_acces_justice", key_signals: ["Impunité des créanciers — l'absence de mécanisme international de restructuration de la dette souveraine laisse les États débiteurs sans recours légal face aux pratiques abusives des créanciers"], estimated_debt_trap_economic_coercion_rights_index: 2.21, last_updated: "2026-06-21" },
    { id: "DTEC-008", name: "Norvège/Fonds Souverain Modèle Transparence", country: "Europe du Nord", sector: "1.5 Trillion$ Fonds Souverain Pétrolier, Zéro Dette Nette, AAA Rating, Gestion Transparente & Droits Sociaux Préservés Politiques Fiscales", sovereign_debt_coercion_loss_autonomy_score: 3.0, conditionality_austerity_social_rights_erosion_score: 2.0, resource_extraction_dispossession_scale_score: 4.0, debt_restructuring_access_justice_deficit_score: 5.0, composite_score: 3.25, risk_level: "faible", primary_pattern: "piege_dette_souverainete_confisquee", key_signals: ["Gestion équitable de la dette de Norvège/Fonds Souverain Modèle Transparence — mécanismes de restructuration accessibles et conditionnalités respectant les droits humains"], estimated_debt_trap_economic_coercion_rights_index: 0.33, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { piege_dette_souverainete_confisquee: 2, austerite_erosion_droits_sociaux: 3, extraction_ressources_spoliation: 1, deficit_restructuration_acces_justice: 2 },
    top_risk_entities: ["Sri Lanka/Port Hambantota Cédé Chine 99 Ans", "Zambie/Faillite Souveraine 2020 BRI Chine", "Grèce/Troïka Austérité 2010-2018 Droits", "Pakistan/FMI 23ème Programme Conditionnalités"],
    critical_alerts: ["Sri Lanka: piege_dette_souverainete_confisquee", "Zambie: deficit_restructuration_acces_justice", "Grèce: austerite_erosion_droits_sociaux", "Pakistan: austerite_erosion_droits_sociaux"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "debt_trap_economic_coercion_rights",
    confidence_score: 0.86,
    data_sources: ["imf_debt_sustainability_framework_2023", "jubilee_debt_campaign_reports", "unctad_debt_vulnerabilities_2023", "world_bank_international_debt_statistics"],
    entities,
    avg_estimated_debt_trap_economic_coercion_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
