import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[sales-coach] SWARM_API_URL non défini — mode dégradé activé");
}

const SWARM_API_URL = process.env.SWARM_API_URL;

const mockReps = [
  {
    rep: {
      rep_id: "rep_001",
      rep_name: "Alexandre Martin",
      manager_id: "mgr_001",
      territory: "Île-de-France",
      open_deals: 12,
      pipeline_value_eur: 480000,
      quota_eur: 300000,
      pipeline_coverage_ratio: 1.6,
      calls_last_30d: 42,
      emails_last_30d: 98,
      meetings_last_30d: 8,
      demos_last_30d: 2,
      win_rate_last_90d: 18,
      win_rate_prev_90d: 24,
      avg_deal_size_eur: 40000,
      avg_sales_cycle_days: 75,
      discovery_score: 55,
      objection_score: 48,
      demo_score: 62,
      pricing_score: 70,
      follow_up_score: 45,
      relationship_score: 72,
      time_mgmt_score: 60,
      deals_won_last_90d: 3,
      deals_lost_last_90d: 9,
      deals_stalled_last_30d: 4,
    },
    coaching_priority: "urgent",
    primary_focus: "qualification",
    coaching_score: 71.5,
    pipeline_health_score: 38.0,
    activity_score: 52.0,
    skill_gap_score: 41.0,
    win_rate_trend_score: 27.0,
    top_recommendations: [
      "Augmenter le volume de prospection — pipeline insuffisant pour atteindre les objectifs",
      "Renforcer la qualification BANT avant d'investir du temps sur un deal",
      "Préparer des réponses structurées aux objections récurrentes (prix, timing, concurrent)",
      "Tester des techniques de closing plus tôt dans le cycle de vente",
    ],
    skill_development: [
      "Approfondir la phase de découverte — poser plus de questions ouvertes sur les enjeux business",
      "Travailler les réponses aux objections prix et concurrentielles avec des role-plays",
      "Mettre en place des séquences de relance multicanal (email + LinkedIn + téléphone)",
    ],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Score BANT moyen des deals qualifiés",
      "Taux de deals disqualifiés en early stage",
    ],
    estimated_quota_attainment_pct: 28.8,
  },
  {
    rep: {
      rep_id: "rep_002",
      rep_name: "Sophie Durand",
      manager_id: "mgr_001",
      territory: "Grand Ouest",
      open_deals: 9,
      pipeline_value_eur: 630000,
      quota_eur: 250000,
      pipeline_coverage_ratio: 2.52,
      calls_last_30d: 68,
      emails_last_30d: 135,
      meetings_last_30d: 14,
      demos_last_30d: 6,
      win_rate_last_90d: 38,
      win_rate_prev_90d: 32,
      avg_deal_size_eur: 70000,
      avg_sales_cycle_days: 60,
      discovery_score: 80,
      objection_score: 75,
      demo_score: 88,
      pricing_score: 72,
      follow_up_score: 78,
      relationship_score: 85,
      time_mgmt_score: 76,
      deals_won_last_90d: 6,
      deals_lost_last_90d: 4,
      deals_stalled_last_30d: 1,
    },
    coaching_priority: "low",
    primary_focus: "retention",
    coaching_score: 22.0,
    pipeline_health_score: 76.0,
    activity_score: 88.0,
    skill_gap_score: 20.0,
    win_rate_trend_score: 80.0,
    top_recommendations: [
      "Activer les opportunités d'upsell sur la base installée existante",
    ],
    skill_development: [],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Taux de renouvellement contrats",
      "Net Revenue Retention (NRR) du portefeuille",
    ],
    estimated_quota_attainment_pct: 95.8,
  },
  {
    rep: {
      rep_id: "rep_003",
      rep_name: "Thomas Leblanc",
      manager_id: "mgr_002",
      territory: "PACA",
      open_deals: 15,
      pipeline_value_eur: 290000,
      quota_eur: 280000,
      pipeline_coverage_ratio: 1.04,
      calls_last_30d: 55,
      emails_last_30d: 110,
      meetings_last_30d: 11,
      demos_last_30d: 4,
      win_rate_last_90d: 22,
      win_rate_prev_90d: 28,
      avg_deal_size_eur: 19333,
      avg_sales_cycle_days: 90,
      discovery_score: 65,
      objection_score: 58,
      demo_score: 70,
      pricing_score: 55,
      follow_up_score: 62,
      relationship_score: 68,
      time_mgmt_score: 72,
      deals_won_last_90d: 4,
      deals_lost_last_90d: 8,
      deals_stalled_last_30d: 5,
    },
    coaching_priority: "high",
    primary_focus: "qualification",
    coaching_score: 58.3,
    pipeline_health_score: 42.0,
    activity_score: 70.0,
    skill_gap_score: 36.0,
    win_rate_trend_score: 38.0,
    top_recommendations: [
      "Augmenter le volume de prospection — pipeline insuffisant pour atteindre les objectifs",
      "Effectuer une revue hebdomadaire du pipeline avec le manager pour débloquer les deals",
      "Renforcer la qualification BANT avant d'investir du temps sur un deal",
    ],
    skill_development: [
      "Travailler les réponses aux objections prix et concurrentielles avec des role-plays",
      "Maîtriser la justification de valeur avant de présenter le prix",
    ],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Score BANT moyen des deals qualifiés",
      "Taux de deals disqualifiés en early stage",
    ],
    estimated_quota_attainment_pct: 38.5,
  },
  {
    rep: {
      rep_id: "rep_004",
      rep_name: "Clara Bernard",
      manager_id: "mgr_002",
      territory: "Rhône-Alpes",
      open_deals: 7,
      pipeline_value_eur: 560000,
      quota_eur: 200000,
      pipeline_coverage_ratio: 2.8,
      calls_last_30d: 72,
      emails_last_30d: 150,
      meetings_last_30d: 18,
      demos_last_30d: 9,
      win_rate_last_90d: 45,
      win_rate_prev_90d: 40,
      avg_deal_size_eur: 80000,
      avg_sales_cycle_days: 55,
      discovery_score: 85,
      objection_score: 82,
      demo_score: 90,
      pricing_score: 78,
      follow_up_score: 88,
      relationship_score: 92,
      time_mgmt_score: 80,
      deals_won_last_90d: 8,
      deals_lost_last_90d: 5,
      deals_stalled_last_30d: 1,
    },
    coaching_priority: "low",
    primary_focus: "retention",
    coaching_score: 15.0,
    pipeline_health_score: 84.0,
    activity_score: 100.0,
    skill_gap_score: 16.0,
    win_rate_trend_score: 87.5,
    top_recommendations: [
      "Activer les opportunités d'upsell sur la base installée existante",
    ],
    skill_development: [],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Taux de renouvellement contrats",
      "Net Revenue Retention (NRR) du portefeuille",
    ],
    estimated_quota_attainment_pct: 126.0,
  },
  {
    rep: {
      rep_id: "rep_005",
      rep_name: "Julien Moreau",
      manager_id: "mgr_001",
      territory: "Grand Est",
      open_deals: 20,
      pipeline_value_eur: 180000,
      quota_eur: 320000,
      pipeline_coverage_ratio: 0.56,
      calls_last_30d: 28,
      emails_last_30d: 45,
      meetings_last_30d: 4,
      demos_last_30d: 1,
      win_rate_last_90d: 12,
      win_rate_prev_90d: 20,
      avg_deal_size_eur: 9000,
      avg_sales_cycle_days: 105,
      discovery_score: 40,
      objection_score: 35,
      demo_score: 45,
      pricing_score: 38,
      follow_up_score: 30,
      relationship_score: 50,
      time_mgmt_score: 42,
      deals_won_last_90d: 2,
      deals_lost_last_90d: 12,
      deals_stalled_last_30d: 9,
    },
    coaching_priority: "urgent",
    primary_focus: "prospecting",
    coaching_score: 86.0,
    pipeline_health_score: 22.0,
    activity_score: 28.0,
    skill_gap_score: 60.0,
    win_rate_trend_score: 3.0,
    top_recommendations: [
      "Augmenter le volume de prospection — pipeline insuffisant pour atteindre les objectifs",
      "Améliorer la discipline de mise à jour CRM pour une meilleure visibilité pipeline",
      "Renforcer la qualification BANT avant d'investir du temps sur un deal",
      "Préparer des réponses structurées aux objections récurrentes (prix, timing, concurrent)",
      "Tester des techniques de closing plus tôt dans le cycle de vente",
      "Effectuer une revue hebdomadaire du pipeline avec le manager pour débloquer les deals",
    ],
    skill_development: [
      "Approfondir la phase de découverte — poser plus de questions ouvertes sur les enjeux business",
      "Travailler les réponses aux objections prix et concurrentielles avec des role-plays",
      "Structurer les démonstrations autour des pain points identifiés, pas des fonctionnalités",
      "Maîtriser la justification de valeur avant de présenter le prix",
      "Mettre en place des séquences de relance multicanal (email + LinkedIn + téléphone)",
      "Prioriser les deals à fort potentiel et déléguer ou abandonner les deals froids",
    ],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Nombre de nouveaux prospects contactés/semaine",
      "Taux de réponse cold outreach",
    ],
    estimated_quota_attainment_pct: 8.3,
  },
  {
    rep: {
      rep_id: "rep_006",
      rep_name: "Marie Petit",
      manager_id: "mgr_003",
      territory: "Normandie",
      open_deals: 8,
      pipeline_value_eur: 380000,
      quota_eur: 220000,
      pipeline_coverage_ratio: 1.73,
      calls_last_30d: 50,
      emails_last_30d: 100,
      meetings_last_30d: 10,
      demos_last_30d: 5,
      win_rate_last_90d: 30,
      win_rate_prev_90d: 30,
      avg_deal_size_eur: 47500,
      avg_sales_cycle_days: 70,
      discovery_score: 70,
      objection_score: 65,
      demo_score: 74,
      pricing_score: 68,
      follow_up_score: 72,
      relationship_score: 75,
      time_mgmt_score: 68,
      deals_won_last_90d: 4,
      deals_lost_last_90d: 6,
      deals_stalled_last_30d: 2,
    },
    coaching_priority: "medium",
    primary_focus: "qualification",
    coaching_score: 44.0,
    pipeline_health_score: 60.0,
    activity_score: 71.0,
    skill_gap_score: 29.0,
    win_rate_trend_score: 50.0,
    top_recommendations: [
      "Renforcer la qualification BANT avant d'investir du temps sur un deal",
    ],
    skill_development: [],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Score BANT moyen des deals qualifiés",
      "Taux de deals disqualifiés en early stage",
    ],
    estimated_quota_attainment_pct: 51.8,
  },
  {
    rep: {
      rep_id: "rep_007",
      rep_name: "Nicolas Fontaine",
      manager_id: "mgr_003",
      territory: "Bretagne",
      open_deals: 11,
      pipeline_value_eur: 820000,
      quota_eur: 350000,
      pipeline_coverage_ratio: 2.34,
      calls_last_30d: 65,
      emails_last_30d: 128,
      meetings_last_30d: 16,
      demos_last_30d: 7,
      win_rate_last_90d: 42,
      win_rate_prev_90d: 35,
      avg_deal_size_eur: 74545,
      avg_sales_cycle_days: 65,
      discovery_score: 78,
      objection_score: 72,
      demo_score: 82,
      pricing_score: 76,
      follow_up_score: 80,
      relationship_score: 88,
      time_mgmt_score: 74,
      deals_won_last_90d: 7,
      deals_lost_last_90d: 4,
      deals_stalled_last_30d: 2,
    },
    coaching_priority: "low",
    primary_focus: "retention",
    coaching_score: 24.5,
    pipeline_health_score: 72.0,
    activity_score: 87.0,
    skill_gap_score: 22.0,
    win_rate_trend_score: 78.0,
    top_recommendations: [
      "Activer les opportunités d'upsell sur la base installée existante",
    ],
    skill_development: [],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Taux de renouvellement contrats",
      "Net Revenue Retention (NRR) du portefeuille",
    ],
    estimated_quota_attainment_pct: 98.3,
  },
  {
    rep: {
      rep_id: "rep_008",
      rep_name: "Camille Rousseau",
      manager_id: "mgr_002",
      territory: "Centre-Val de Loire",
      open_deals: 14,
      pipeline_value_eur: 350000,
      quota_eur: 300000,
      pipeline_coverage_ratio: 1.17,
      calls_last_30d: 38,
      emails_last_30d: 72,
      meetings_last_30d: 7,
      demos_last_30d: 3,
      win_rate_last_90d: 25,
      win_rate_prev_90d: 22,
      avg_deal_size_eur: 25000,
      avg_sales_cycle_days: 80,
      discovery_score: 60,
      objection_score: 55,
      demo_score: 65,
      pricing_score: 58,
      follow_up_score: 62,
      relationship_score: 70,
      time_mgmt_score: 65,
      deals_won_last_90d: 4,
      deals_lost_last_90d: 7,
      deals_stalled_last_30d: 4,
    },
    coaching_priority: "high",
    primary_focus: "qualification",
    coaching_score: 57.5,
    pipeline_health_score: 40.0,
    activity_score: 56.0,
    skill_gap_score: 38.0,
    win_rate_trend_score: 42.5,
    top_recommendations: [
      "Augmenter le volume de prospection — pipeline insuffisant pour atteindre les objectifs",
      "Effectuer une revue hebdomadaire du pipeline avec le manager pour débloquer les deals",
    ],
    skill_development: [
      "Travailler les réponses aux objections prix et concurrentielles avec des role-plays",
      "Maîtriser la justification de valeur avant de présenter le prix",
    ],
    kpis_to_watch: [
      "Taux de conversion pipeline → deal gagné",
      "Durée moyenne du cycle de vente",
      "Score BANT moyen des deals qualifiés",
      "Taux de deals disqualifiés en early stage",
    ],
    estimated_quota_attainment_pct: 29.2,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const priority = searchParams.get("priority");
  const manager = searchParams.get("manager");
  const focus = searchParams.get("focus");

  if (SWARM_API_URL) {
    try {
      const url = new URL(`${SWARM_API_URL}/api/sales-coach`);
      if (priority) url.searchParams.set("priority", priority);
      if (manager) url.searchParams.set("manager", manager);
      if (focus) url.searchParams.set("focus", focus);
      const res = await fetch(url.toString(), { cache: "no-store" });
      if (res.ok) return sealResponse(NextResponse.json(await res.json()));
    } catch {}
  }

  let reps = [...mockReps];
  if (priority) reps = reps.filter((r) => r.coaching_priority === priority);
  if (manager) reps = reps.filter((r) => r.rep.manager_id === manager);
  if (focus) reps = reps.filter((r) => r.primary_focus === focus);

  const total = reps.length;
  const priority_counts = { urgent: 0, high: 0, medium: 0, low: 0 } as Record<string, number>;
  const focus_counts = { prospecting: 0, qualification: 0, presentation: 0, negotiation: 0, closing: 0, retention: 0 } as Record<string, number>;
  for (const r of mockReps) {
    priority_counts[r.coaching_priority] = (priority_counts[r.coaching_priority] || 0) + 1;
    focus_counts[r.primary_focus] = (focus_counts[r.primary_focus] || 0) + 1;
  }
  const avg_coaching_score = mockReps.reduce((s, r) => s + r.coaching_score, 0) / mockReps.length;
  const avg_quota_attainment = mockReps.reduce((s, r) => s + r.estimated_quota_attainment_pct, 0) / mockReps.length;

  return sealResponse(NextResponse.json({
    reps,
    summary: {
      total_reps: mockReps.length,
      priority_counts,
      focus_counts,
      avg_coaching_score: Math.round(avg_coaching_score * 10) / 10,
      avg_quota_attainment_pct: Math.round(avg_quota_attainment * 10) / 10,
      urgent_count: priority_counts.urgent,
    },
  }));
}
