import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[sexual-violence-wartime-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Sexual Violence Wartime Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/sexual-violence-wartime-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Sexual Violence Wartime Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Sexual Violence Wartime Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "SV-001", name: "DRC/Est Congo — 200 000+ Victimes Viol Systématique & Capitale Mondiale Viol Conflit", country: "Afrique Centrale", sector: "200 000+ Victimes Viol Documentées Est Congo 1996-2024, Dr Denis Mukwege Nobel Paix, FARDC/Maï-Maï/M23 Auteurs & Viol Outil Domination Territoriale", composite_score: 91.4, systematic_rape_targeting_score: 95.0, state_actor_perpetration_score: 88.0, survivor_access_justice_score: 90.0, conflict_zone_impunity_score: 92.0, risk_level: "critique", primary_pattern: "viol_arme_guerre_systematique", key_signals: ["Viol comme arme de guerre systématique en DRC/Est Congo — 200 000+ victimes documentées depuis 1996 faisant de l'Est du Congo la 'capitale mondiale du viol' selon l'ONU, avec FARDC, Maï-Maï et M23 comme auteurs identifiés", "Crime de guerre et crime contre l'humanité — le viol systématique en temps de conflit constitue un crime de guerre selon l'Article 8 du Statut de Rome et l'ONU a qualifié les actes en RDC de crime contre l'humanité dès 2010", "Activer la Résolution CS-ONU 1820 sur les violences sexuelles en conflit et renforcer le mandat de la Représentante Spéciale ONU (OSRSG-SVC) pour accès humanitaire d'urgence aux survivantes en RDC"], estimated_sexual_violence_wartime_index: 9.14, last_updated: "2026-06-20" },
    { entity_id: "SV-002", name: "Syrie/Assad — Viol Torture Prisons, 6 000+ Victimes Détention & Impunité Totale", country: "MENA", sector: "6 000+ Victimes Violences Sexuelles Détention Assad Documentées ONU, Sednaya Viol Systématique, Hommes/Femmes/Enfants & Commission Enquête CS-ONU Preuves", composite_score: 91.35, systematic_rape_targeting_score: 92.0, state_actor_perpetration_score: 95.0, survivor_access_justice_score: 88.0, conflict_zone_impunity_score: 90.0, risk_level: "critique", primary_pattern: "ciblage_etatique_violences_sexuelles", key_signals: ["Ciblage étatique des violences sexuelles en Syrie/Assad — 6 000+ victimes documentées de violences sexuelles dans les centres de détention syriens, utilisées comme outil de torture et de terreur par des agents de l'État", "Crime contre l'humanité commis par des agents étatiques — la Commission d'Enquête ONU sur la Syrie a documenté des preuves suffisantes de violences sexuelles systématiques qualifiables de crimes contre l'humanité selon le Statut de Rome", "Activer le mécanisme international IIIM pour préserver les preuves et poursuivre les responsables des violences sexuelles dans les prisons syriennes, en priorité ceux identifiés par la Commission d'Enquête ONU"], estimated_sexual_violence_wartime_index: 9.13, last_updated: "2026-06-20" },
    { entity_id: "SV-003", name: "Bosnie/Serbie — Camps Viol 1992-95, 20 000-50 000 Victimes & TPIY Jurisprudence", country: "Europe de l'Est", sector: "Camps Viol Foča/Prijedor 1992-95, 20 000-50 000 Victimes Estimées, TPIY Première Condamnation Viol Crime Guerre 1998 & Kunarac Précédent Juridique Historique", composite_score: 85.75, systematic_rape_targeting_score: 88.0, state_actor_perpetration_score: 85.0, survivor_access_justice_score: 82.0, conflict_zone_impunity_score: 88.0, risk_level: "critique", primary_pattern: "viol_arme_guerre_systematique", key_signals: ["Viol comme arme de guerre systématique en Bosnie/Serbie — 20 000 à 50 000 victimes dans les camps de viol de Foča et Prijedor entre 1992 et 1995, première qualification de viol comme crime de guerre par le TPIY en 1998 (affaire Kunarac)", "Jurisprudence fondatrice — la condamnation Kunarac par le TPIY en 2001 a établi que le viol peut constituer un crime contre l'humanité quand utilisé de façon systématique comme outil de nettoyage ethnique", "Honorer la jurisprudence TPIY sur les violences sexuelles et soutenir les organisations de survivantes bosniaques qui continuent de demander justice et réparation pour les crimes des années 1990"], estimated_sexual_violence_wartime_index: 8.58, last_updated: "2026-06-20" },
    { entity_id: "SV-004", name: "Myanmar/Rohingya — Viol Systématique 2017 Opération Clearance & CIJ/ICC Procédures", country: "Asie du Sud-Est", sector: "Tatmadaw Viol Systématique Rohingya Femmes 2017, Témoignages 1 000+ Victimes ONU, Villages Brûlés Après Viol & Factfinding Mission 2018 Crimes Contre Humanité", composite_score: 85.65, systematic_rape_targeting_score: 85.0, state_actor_perpetration_score: 90.0, survivor_access_justice_score: 85.0, conflict_zone_impunity_score: 82.0, risk_level: "critique", primary_pattern: "ciblage_etatique_violences_sexuelles", key_signals: ["Ciblage étatique des violences sexuelles au Myanmar/Rohingya — Tatmadaw utilisant le viol systématique comme arme pendant l'opération Clearance de 2017 avec 1 000+ témoignages documentés et villages brûlés après les assauts", "Crime contre l'humanité et élément de génocide — la Mission d'établissement des faits ONU 2018 a conclu que les violences sexuelles de la Tatmadaw constituent des crimes contre l'humanité avec intent génocidaire", "Soutenir les procédures CIJ/CPI contre le Myanmar pour violences sexuelles et assurer l'accès aux soins et à la justice pour les survivantes rohingya réfugiées au Bangladesh"], estimated_sexual_violence_wartime_index: 8.57, last_updated: "2026-06-20" },
    { entity_id: "SV-005", name: "Inde/Manipur — Violences Sexuelles Communautaires 2023, Vidéos Virales & Impunité", country: "Asie du Sud", sector: "Manipur 2023 Violences Sexuelles Communautaires Kuki-Zo/Meitei, Vidéos Défilé Forcé Viralisées, Arrestations Tardives Pression Internationale & Droits Humains Inquiétudes", composite_score: 54.4, systematic_rape_targeting_score: 55.0, state_actor_perpetration_score: 52.0, survivor_access_justice_score: 58.0, conflict_zone_impunity_score: 52.0, risk_level: "élevé", primary_pattern: "impunite_agresseurs_conflit", key_signals: ["Impunité des agresseurs en conflit Inde/Manipur — violences sexuelles communautaires filmées viralisées en 2023 lors des violences inter-ethniques Kuki-Zo/Meitei, avec arrestations des agresseurs seulement après pression internationale", "Lacune dans la protection — les violences sexuelles lors de conflits communautaires en Inde révèlent des défaillances dans la protection des femmes des minorités et l'absence de réponse préventive de l'État", "Accélérer les poursuites judiciaires contre tous les responsables des violences de Manipur et mettre en œuvre les recommandations de la Rapporteure Spéciale ONU sur les violences contre les femmes"], estimated_sexual_violence_wartime_index: 5.44, last_updated: "2026-06-20" },
    { entity_id: "SV-006", name: "Soudan/RSF — Violences Sexuelles Massives Darfour/Khartoum 2023-24 & Campagnes Viol", country: "Afrique de l'Est", sector: "RSF Forces Paramilitaires Viol Systématique Darfour/Khartoum 2023-24, El Fasher Siège Violences Sexuelles, 1 000+ Cas UNFPA & Répétition Crimes Darfour 2003", composite_score: 53.45, systematic_rape_targeting_score: 52.0, state_actor_perpetration_score: 55.0, survivor_access_justice_score: 50.0, conflict_zone_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "impunite_agresseurs_conflit", key_signals: ["Impunité des agresseurs au Soudan/RSF — Forces de Soutien Rapide utilisant le viol systématique au Darfour et à Khartoum depuis 2023, répétant le schéma des crimes documentés de 2003 avec 1 000+ cas UNFPA", "Crime de guerre en cours — les violences sexuelles systématiques des RSF au Darfour et à Khartoum constituent des crimes de guerre documentés par l'ONU, exigeant une réponse juridique internationale urgente", "Activer la Résolution CS-ONU 1820 et saisir la CPI pour les violences sexuelles systématiques des RSF au Soudan, en priorité pour les crimes commis à El Fasher et dans le Darfour"], estimated_sexual_violence_wartime_index: 5.34, last_updated: "2026-06-20" },
    { entity_id: "SV-007", name: "Ouganda/LRA — Ex-Esclaves Sexuelles Réintégration & Justice Transitionnelle Défaillante", country: "Afrique de l'Est", sector: "LRA 10 000+ Femmes Enlevées Esclaves Sexuelles 1987-2006, Joseph Kony CPI Fugitif, Survivantes Stigmatisation Retour & Programmes Réintégration Insuffisants Ouganda", composite_score: 29.3, systematic_rape_targeting_score: 28.0, state_actor_perpetration_score: 30.0, survivor_access_justice_score: 28.0, conflict_zone_impunity_score: 32.0, risk_level: "modéré", primary_pattern: "reintegration_victimes_defaillante", key_signals: ["Réintégration défaillante des victimes en Ouganda/LRA — 10 000+ femmes anciennes esclaves sexuelles du LRA faisant face à stigmatisation sociale et programmes de réintégration insuffisants, pendant que Joseph Kony reste en fuite malgré son mandat CPI depuis 2005", "Justice transitionnelle incomplète — l'absence de capture de Kony et les limites des programmes de réintégration laissent des milliers de survivantes sans accès à la justice et sans réparations adéquates", "Renforcer les programmes de réintégration des survivantes du LRA en Ouganda et intensifier les efforts de coopération internationale pour l'appréhension de Joseph Kony conformément au mandat CPI"], estimated_sexual_violence_wartime_index: 2.93, last_updated: "2026-06-20" },
    { entity_id: "SV-008", name: "OSRSG-SVC/ONU — Résolution 1820 & Criminalisation Violences Sexuelles Conflit", country: "Global", sector: "CS-ONU Résolution 1820 2008 Violences Sexuelles Conflit, OSRSG-SVC Mandat, Équipe Experts PSVI & Protocole International Documentation Violences Sexuelles Conflit", composite_score: 4.45, systematic_rape_targeting_score: 5.0, state_actor_perpetration_score: 4.0, survivor_access_justice_score: 3.0, conflict_zone_impunity_score: 6.0, risk_level: "faible", primary_pattern: "reintegration_victimes_defaillante", key_signals: ["OSRSG-SVC/ONU incarne la protection exemplaire — Résolution 1820 du Conseil de Sécurité qualifiant les violences sexuelles en conflit de menace à la paix et à la sécurité internationales avec mandat de Représentante Spéciale", "Résolution CS-ONU 1820 (2008) — reconnaissance que le viol et autres formes de violence sexuelle constituent des tactiques de guerre et doivent être traités comme des crimes de guerre et crimes contre l'humanité", "Partager le Protocole International de Documentation des Violences Sexuelles en Conflit et renforcer le financement de l'OSRSG-SVC pour documentation, poursuites et soutien aux survivant(e)s"], estimated_sexual_violence_wartime_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { viol_arme_guerre_systematique: 2, ciblage_etatique_violences_sexuelles: 2, impunite_agresseurs_conflit: 2, reintegration_victimes_defaillante: 2 },
    top_risk_entities: ["DRC/Est Congo — 200 000+ Victimes Viol Systématique & Capitale Mondiale Viol Conflit", "Syrie/Assad — Viol Torture Prisons, 6 000+ Victimes Détention & Impunité Totale", "Bosnie/Serbie — Camps Viol 1992-95, 20 000-50 000 Victimes & TPIY Jurisprudence"],
    critical_alerts: ["DRC/Est Congo: viol arme guerre systématique", "Syrie/Assad: ciblage étatique violences sexuelles", "Bosnie/Serbie: viol arme guerre systématique", "Myanmar/Rohingya: ciblage étatique violences sexuelles"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "sexual_violence_wartime",
    confidence_score: 0.83,
    data_sources: ["un_osrsg_svc_annual_reports", "hrw_sexual_violence_conflict_reports", "icrc_women_war_protection_database"],
    entities,
    avg_estimated_sexual_violence_wartime_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
