import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[war-crimes-siege-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "War Crimes Siege Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/war-crimes-siege-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "War Crimes Siege Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "War Crimes Siege Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "WC-001", name: "Russie/Ukraine — Marioupol Siège, Hôpitaux Bombardés & Civils Ciblés", country: "Europe de l'Est", sector: "Marioupol Siège 80 Jours, 100+ Hôpitaux Bombardés OMS, Bucha Exécutions Civils & Mandat CPI Poutine 2023", composite_score: 91.6, deliberate_civilian_targeting_score: 95.0, siege_starvation_tactics_score: 92.0, protected_site_attack_score: 90.0, war_crimes_impunity_score: 88.0, risk_level: "critique", primary_pattern: "boucliers_humains_forces", key_signals: ["Utilisation de boucliers humains de Russie/Ukraine — siège de Marioupol maintenant des civils piégés dans des zones de combat pendant 80 jours avec coupure des corridors humanitaires", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU sur la famine comme arme de guerre et saisir la CPI pour crimes contre l'humanité"], estimated_war_crimes_siege_index: 9.16, last_updated: "2026-06-20" },
    { id: "WC-002", name: "Syrie/Assad — Siège Yarmouk, Armes Chimiques & Hôpitaux Rasés", country: "MENA", sector: "Siège Yarmouk 560 Jours, 50+ Hôpitaux Détruits MSF, Sarin Ghouta 2013 & Double Tap Tactique Documentée", composite_score: 90.75, deliberate_civilian_targeting_score: 90.0, siege_starvation_tactics_score: 95.0, protected_site_attack_score: 92.0, war_crimes_impunity_score: 85.0, risk_level: "critique", primary_pattern: "siege_famine_arme", key_signals: ["Siège et famine comme arme de guerre de Syrie/Assad — blocus du camp de réfugiés de Yarmouk pendant 560 jours privant 18 000 civils de nourriture et de soins médicaux", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU sur la famine comme arme de guerre et saisir la CPI pour crimes contre l'humanité"], estimated_war_crimes_siege_index: 9.08, last_updated: "2026-06-20" },
    { id: "WC-003", name: "Gaza/Israël — Hôpitaux Al-Shifa, Famine Induite & Infrastructure Détruite", country: "MENA", sector: "Al-Shifa Hôpital Assiégé, 2M Déplacés Nord/Sud, 70% Infrastructure Détruite & CIJ Mesures Provisoires Ordonnées 2024", composite_score: 87.9, deliberate_civilian_targeting_score: 88.0, siege_starvation_tactics_score: 90.0, protected_site_attack_score: 88.0, war_crimes_impunity_score: 85.0, risk_level: "critique", primary_pattern: "siege_famine_arme", key_signals: ["Siège et famine comme arme de guerre de Gaza/Israël — blocus de Gaza limitant l'aide humanitaire avec ordonnances contraignantes de la CIJ ordonnant l'accès humanitaire immédiat", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU sur la famine comme arme de guerre et saisir la CPI pour crimes contre l'humanité"], estimated_war_crimes_siege_index: 8.79, last_updated: "2026-06-20" },
    { id: "WC-004", name: "Soudan/RSF — Khartoum Pillages, Civils Massa & Famine 2024", country: "Afrique", sector: "RSF Khartoum Pillages Hôpitaux, Massacre Massa 1000+ Civils, Famine IPC5 Déclarée & 11M Déplacés Urgence Mondiale", composite_score: 86.0, deliberate_civilian_targeting_score: 85.0, siege_starvation_tactics_score: 88.0, protected_site_attack_score: 82.0, war_crimes_impunity_score: 90.0, risk_level: "critique", primary_pattern: "execution_prisonniers_guerre", key_signals: ["Exécutions sommaires de Soudan/RSF — massacre de Massa avec 1000+ civils Masalit tués et pillage systématique des hôpitaux de Khartoum avec impunité totale des commandants RSF", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU et saisir la CPI pour crimes contre l'humanité commis par les RSF"], estimated_war_crimes_siege_index: 8.6, last_updated: "2026-06-20" },
    { id: "WC-005", name: "Éthiopie/Tigré — Siège Alimentaire, Viol Arme & Ambulances Attaquées", country: "Afrique de l'Est", sector: "Siège Alimentaire Tigré 2021, Viols Systémiques Arme Guerre, MSF Ambulances Attaquées & 500 000 Morts Estimés", composite_score: 57.4, deliberate_civilian_targeting_score: 55.0, siege_starvation_tactics_score: 62.0, protected_site_attack_score: 52.0, war_crimes_impunity_score: 62.0, risk_level: "élevé", primary_pattern: "siege_famine_arme", key_signals: ["Siège et famine comme arme de guerre d'Éthiopie/Tigré — blocus alimentaire délibéré du Tigré combiné à des viols systémiques et attaques d'ambulances MSF en violation du DIH", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU sur la famine comme arme de guerre et saisir la CPI pour crimes contre l'humanité"], estimated_war_crimes_siege_index: 5.74, last_updated: "2026-06-20" },
    { id: "WC-006", name: "Yémen/Coalition — Frappes Mariages, Ports Bloqués & Choléra", country: "MENA", sector: "Frappes 140 Mariages/Funérailles, Hodeida Port Bloqué Famine, ONU Panel d'Experts Violations & Choléra 2.5M Cas", composite_score: 57.5, deliberate_civilian_targeting_score: 55.0, siege_starvation_tactics_score: 58.0, protected_site_attack_score: 62.0, war_crimes_impunity_score: 55.0, risk_level: "élevé", primary_pattern: "attaques_hopitaux_protegees", key_signals: ["Attaques systématiques d'hôpitaux et infrastructures protégées au Yémen — frappes sur 140 mariages et funérailles, blocage du port d'Hodeida et destruction du système de santé générant une épidémie de choléra", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Engager le mécanisme de dénonciation ICRC et demander ouverture d'une enquête CPI pour violations graves des Conventions de Genève"], estimated_war_crimes_siege_index: 5.75, last_updated: "2026-06-20" },
    { id: "WC-007", name: "Afghanistan/Taliban — Restrictions Femmes & Aide Humanitaire Bloquée", country: "Asie Centrale", sector: "Femmes Bannies ONG Humanitaires, Aide ONU Bloquée Décret, Éducation Filles Interdite & Famine 15M Personnes", composite_score: 29.8, deliberate_civilian_targeting_score: 28.0, siege_starvation_tactics_score: 38.0, protected_site_attack_score: 22.0, war_crimes_impunity_score: 32.0, risk_level: "modéré", primary_pattern: "siege_famine_arme", key_signals: ["Siège humanitaire de l'Afghanistan/Taliban — interdiction faite aux femmes de travailler pour les ONG créant une famine pour 15 millions de personnes dépendantes de l'aide internationale", "Violations graves des Conventions de Genève — les crimes de guerre documentés créent une responsabilité pénale individuelle pour les commandants selon le principe de responsabilité de commandement", "Activer en urgence la résolution 2417 du CS-ONU sur la famine comme arme de guerre et demander accès humanitaire inconditionnel"], estimated_war_crimes_siege_index: 2.98, last_updated: "2026-06-20" },
    { id: "WC-008", name: "CICR/CPI — Conventions Genève & Justice Humanitaire Internationale", country: "Global", sector: "4 Conventions Genève 196 États, CPI 124 États, Résolution 2417 CS-ONU Famine & ICRC Accès Humanitaire", composite_score: 4.45, deliberate_civilian_targeting_score: 5.0, siege_starvation_tactics_score: 4.0, protected_site_attack_score: 3.0, war_crimes_impunity_score: 6.0, risk_level: "faible", primary_pattern: "droit_humanitaire_respecte", key_signals: ["CICR/CPI incarnent le respect exemplaire du droit international humanitaire — forces armées appliquant les principes de distinction, proportionnalité et précaution avec enquêtes indépendantes", "Conventions de Genève universellement ratifiées — 196 États parties avec obligations contraignantes de protection des civils, des prisonniers de guerre et du personnel médical", "Partager les manuels opérationnels de respect du DIH et former les forces armées partenaires aux obligations des Conventions de Genève"], estimated_war_crimes_siege_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { siege_famine_arme: 3, attaques_hopitaux_protegees: 1, boucliers_humains_forces: 1, execution_prisonniers_guerre: 1, droit_humanitaire_respecte: 1 },
    top_risk_entities: ["Russie/Ukraine — Marioupol Siège, Hôpitaux Bombardés & Civils Ciblés", "Syrie/Assad — Siège Yarmouk, Armes Chimiques & Hôpitaux Rasés", "Gaza/Israël — Hôpitaux Al-Shifa, Famine Induite & Infrastructure Détruite"],
    critical_alerts: ["Russie/Ukraine: utilisation boucliers humains", "Syrie/Assad: siège famine arme de guerre", "Gaza/Israël: siège famine arme de guerre", "Soudan/RSF: exécutions sommaires civils"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "war_crimes_siege",
    confidence_score: 0.88,
    data_sources: ["icc_otp_situation_reports", "un_commission_inquiry_reports", "airwars_civilian_harm_database"],
    entities,
    avg_estimated_war_crimes_siege_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
