import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[child-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Child Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/child-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Child Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Child Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "CH-001", name: "Mali/BF/Niger — Mariage Précoce 52%, FGM 90%+ & Troupes Armées Enfants Sahel", country: "Afrique de l'Ouest", sector: "Mali/Burkina Faso Mariage Précoce 52% Filles Avant 18 Ans, FGM 90%+ Niger, Enfants Soldats Groupes Armés Sahel 2 000+/An & Travail Domestique Garibou/Almodo Non-Protégé", composite_score: 87.40, child_labor_exploitation_score: 85.0, child_soldier_recruitment_score: 90.0, child_marriage_protection_score: 92.0, education_healthcare_denial_score: 82.0, risk_level: "critique", primary_pattern: "child_marriage_protection", key_signals: ["Violation des droits de l'enfant documentée — Mali/BF/Niger avec score composite 87.40/100 révélant des violations massives de la Convention des Nations Unies relative aux droits de l'enfant (CDE 1989) sur le mariage précoce, les mutilations génitales et le recrutement d'enfants soldats", "Mariage précoce/Protection (92.0/100) — le taux de 52% de mariages avant 18 ans et les 90%+ de FGM au Niger constituent des violations graves des Articles 24 et 34 de la CDE et de la Déclaration ONU sur l'élimination de la violence contre les femmes", "Activer le Comité des droits de l'enfant de l'ONU pour examen d'urgence et exiger l'adoption de lois nationales fixant 18 ans comme âge minimum du mariage avec sanction effective, conformément aux Objectifs de Développement Durable 5.3"], estimated_child_rights_index: 8.74, last_updated: "2026-06-20" },
    { entity_id: "CH-002", name: "RDC — 30 000 Enfants Soldats, Mines Coltan & Viol Arme de Guerre Mineurs", country: "Afrique Centrale", sector: "RDC 30 000 Enfants Soldats Groupes Armés Historique, Mines Coltan Kivu Travail Enfants, Viol Arme Guerre Mineurs Documenté ONU & MONUSCO Incapable Protéger Violations CDE", composite_score: 88.10, child_labor_exploitation_score: 90.0, child_soldier_recruitment_score: 92.0, child_marriage_protection_score: 82.0, education_healthcare_denial_score: 88.0, risk_level: "critique", primary_pattern: "child_soldier_recruitment", key_signals: ["Violation des droits de l'enfant documentée — RDC avec score composite 88.10/100 révélant des violations systémiques de la CDE avec 30 000 enfants soldats historiquement recrutés et un usage du viol comme arme de guerre contre les mineurs documenté par la MONUSCO", "Recrutement enfants soldats (92.0/100) — le recrutement de 30 000 enfants dans les groupes armés en RDC constitue une violation grave de l'Article 38 de la CDE et du Protocole facultatif sur l'implication d'enfants dans les conflits armés ratifié par 170 États", "Activer le Comité des droits de l'enfant de l'ONU pour examen d'urgence et exiger la démobilisation et réintégration des enfants soldats via les programmes DDR (Désarmement, Démobilisation et Réintégration) de la MONUSCO conformément aux Principes de Paris 2007"], estimated_child_rights_index: 8.81, last_updated: "2026-06-20" },
    { entity_id: "CH-003", name: "Yémen/Gaza — 4 600 Enfants Tués, Malnutrition 2.2M & Hôpitaux Pédiatriques Détruits", country: "MENA", sector: "Yémen 4 600 Enfants Tués Vérifiés ONU 2015-24, Gaza Malnutrition 800 000 Enfants 2024, Hôpitaux Pédiatriques Bombardés, 2.2M Enfants Malnutris Yémen & 0 Accès Vaccins", composite_score: 86.75, child_labor_exploitation_score: 82.0, child_soldier_recruitment_score: 90.0, child_marriage_protection_score: 85.0, education_healthcare_denial_score: 92.0, risk_level: "critique", primary_pattern: "education_healthcare_denial", key_signals: ["Violation des droits de l'enfant documentée — Yémen/Gaza avec score composite 86.75/100 révélant des violations massives de la CDE dans des contextes de conflit armé avec destruction des systèmes de santé pédiatrique violant les Articles 24 et 38 de la CDE", "Déni santé/Éducation (92.0/100) — les 2.2 millions d'enfants en malnutrition aiguë au Yémen et la destruction des hôpitaux pédiatriques à Gaza constituent des violations du droit à la vie (Article 6 CDE) et du droit à la santé (Article 24 CDE)", "Activer le Comité des droits de l'enfant de l'ONU pour examen d'urgence et garantir l'accès humanitaire immédiat aux enfants malnutris au Yémen et à Gaza conformément aux obligations des parties au conflit sous le droit international humanitaire"], estimated_child_rights_index: 8.68, last_updated: "2026-06-20" },
    { entity_id: "CH-004", name: "Inde/Bangladesh — 10M Enfants Travailleurs, Mariage 27% & Ateliers Clandestins", country: "Asie du Sud", sector: "Inde 10M Enfants Travailleurs ILO, Mariage Précoce 27% Filles, Bangladesh Ateliers Textiles Enfants, Travail Domestique Non-Réglementé & Caste Dalits Enfants Excluant Écoles", composite_score: 86.00, child_labor_exploitation_score: 92.0, child_soldier_recruitment_score: 78.0, child_marriage_protection_score: 90.0, education_healthcare_denial_score: 82.0, risk_level: "critique", primary_pattern: "child_labor_exploitation", key_signals: ["Violation des droits de l'enfant documentée — Inde/Bangladesh avec score composite 86.00/100 révélant 10 millions d'enfants travailleurs et un taux de 27% de mariages précoces violant les Conventions OIT 138/182 et les Articles 24/32 de la CDE", "Travail enfants/Exploitation (92.0/100) — les 10 millions d'enfants travailleurs en Inde et les ateliers textiles utilisant des enfants au Bangladesh constituent des violations directes des Conventions fondamentales OIT 138 (âge minimum) et 182 (pires formes de travail des enfants)", "Activer le Comité des droits de l'enfant de l'ONU pour examen d'urgence et renforcer les mécanismes nationaux d'inspection du travail pour éliminer le travail des enfants conformément à l'ODD 8.7 d'éradication du travail des enfants d'ici 2025"], estimated_child_rights_index: 8.60, last_updated: "2026-06-20" },
    { entity_id: "CH-005", name: "USA — Travail Agricole Enfants Légal, Pauvreté 11M Enfants & Gun Violence Écoles", country: "Amérique du Nord", sector: "USA Travail Agricole Enfants <12 Ans Légal Sans Restriction, 11M Enfants Pauvreté 2023, 45 000 Enfants Blessés/Tués Armes À Feu/An & UNICEF USA Dernier OCDE Ratification CDE", composite_score: 52.25, child_labor_exploitation_score: 60.0, child_soldier_recruitment_score: 45.0, child_marriage_protection_score: 48.0, education_healthcare_denial_score: 55.0, risk_level: "élevé", primary_pattern: "child_labor_exploitation", key_signals: ["Violation des droits de l'enfant documentée — USA avec score composite 52.25/100 révélant des lacunes systémiques incluant le travail agricole légal des enfants de moins de 12 ans et les 45 000 victimes annuelles d'armes à feu, en contradiction avec les standards CDE", "Travail enfants/Exploitation (60.0/100) — l'exception agricole permettant aux enfants de moins de 12 ans de travailler dans les fermes et les 45 000 enfants tués ou blessés annuellement par des armes à feu constituent des violations des Articles 32 et 38 de la CDE", "Ratifier la Convention des Nations Unies relative aux droits de l'enfant (seul État membre ONU non-signataire) et harmoniser la législation sur le travail des enfants avec les standards OIT 138 en supprimant l'exception pour le travail agricole"], estimated_child_rights_index: 5.23, last_updated: "2026-06-20" },
    { entity_id: "CH-006", name: "Brésil — 2.4M Enfants Travailleurs, Mariage 26% & Violência Infantil Favelas", country: "Amérique Latine", sector: "Brésil 2.4M Enfants Travailleurs PNAD 2022, Mariage Précoce 26% Jeunes Femmes, Violência Infantil Favelas, Travail Domestique Non-Protégé & Discrimination Raciale Enfants Noirs", composite_score: 52.50, child_labor_exploitation_score: 50.0, child_soldier_recruitment_score: 48.0, child_marriage_protection_score: 58.0, education_healthcare_denial_score: 55.0, risk_level: "élevé", primary_pattern: "child_marriage_protection", key_signals: ["Violation des droits de l'enfant documentée — Brésil avec score composite 52.50/100 révélant 2.4 millions d'enfants travailleurs et un taux de 26% de mariage précoce chez les jeunes femmes, violant les Conventions OIT 138/182 et la CDE ratifiée par le Brésil", "Mariage précoce/Protection (58.0/100) — le taux de 26% de mariage précoce chez les jeunes femmes brésiliennes et la concentration des violations dans les communautés rurales et les favelas révèlent une application inégale des lois de protection de l'enfance", "Renforcer les programmes de protection sociale de l'enfance brésiliens incluant le programme Criança Feliz et adopter une loi nationale fixant l'âge minimum du mariage à 18 ans sans exception conformément aux recommandations du Comité des droits de l'enfant ONU 2023"], estimated_child_rights_index: 5.25, last_updated: "2026-06-20" },
    { entity_id: "CH-007", name: "Europe — 26 000 Mineurs Isolés Trafiqués, Détention Rétention & Frontex Push-Backs", country: "Europe", sector: "Europe 26 000 Mineurs Non-Accompagnés Trafiqués 2022 Europol, Grèce Détention Mineurs Aux Frontières, Frontex Push-Backs Enfants Refoulement & UK Detention Demandeurs Asile Mineurs", composite_score: 29.75, child_labor_exploitation_score: 35.0, child_soldier_recruitment_score: 25.0, child_marriage_protection_score: 28.0, education_healthcare_denial_score: 30.0, risk_level: "modéré", primary_pattern: "child_labor_exploitation", key_signals: ["Défis des droits de l'enfant en Europe — 26 000 mineurs non-accompagnés trafiqués et les pratiques de détention de mineurs aux frontières révèlent des lacunes dans la protection des enfants migrants violant la CDE et la Charte des Droits Fondamentaux de l'UE", "Travail enfants/Exploitation (35.0/100) — le trafic de 26 000 mineurs non-accompagnés par des réseaux criminels et les pratiques de détention de demandeurs d'asile mineurs en Europe constituent des violations des Articles 11 et 37 de la CDE", "Adopter un système européen de protection des mineurs non-accompagnés garantissant un tuteur légal dans les 72 heures et interdire la détention des mineurs demandeurs d'asile conformément aux lignes directrices UNHCR et aux recommandations du Comité des droits de l'enfant"], estimated_child_rights_index: 2.98, last_updated: "2026-06-20" },
    { entity_id: "CH-008", name: "UNICEF/CDE — Convention 1989, Protocoles Facultatifs & Comité Droits Enfant", country: "Global", sector: "CDE Convention Droits Enfant ONU 1989 196 États Parties, 4 Protocoles Facultatifs, Comité Droits Enfant 18 Experts & UNICEF Rapports Annuels Situation Enfants Monde", composite_score: 4.45, child_labor_exploitation_score: 5.0, child_soldier_recruitment_score: 4.0, child_marriage_protection_score: 3.0, education_healthcare_denial_score: 6.0, risk_level: "faible", primary_pattern: "education_healthcare_denial", key_signals: ["UNICEF/CDE incarne le cadre normatif exemplaire des droits de l'enfant — Convention de 1989 avec 196 États parties créant des obligations contraignantes sur la protection, la participation, la provision et la prévention pour chaque enfant sans discrimination", "CDE Article 3 — impose à tous les États de placer l'intérêt supérieur de l'enfant au cœur de toutes les décisions publiques et législatives, créant une obligation transversale qui s'applique aux politiques sociales, éducatives, sanitaires et migratoires", "Universaliser la ratification des Protocoles facultatifs de la CDE et tripler le budget de l'UNICEF pour accélérer l'élimination du travail des enfants, du mariage précoce et du recrutement d'enfants soldats conformément aux ODD 8.7, 5.3 et 16.2"], estimated_child_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { child_labor_exploitation: 3, child_soldier_recruitment: 1, child_marriage_protection: 2, education_healthcare_denial: 2 },
    top_risk_entities: ["RDC — 30 000 Enfants Soldats, Mines Coltan & Viol Arme de Guerre Mineurs", "Mali/BF/Niger — Mariage Précoce 52%, FGM 90%+ & Troupes Armées Enfants Sahel", "Yémen/Gaza — 4 600 Enfants Tués, Malnutrition 2.2M & Hôpitaux Pédiatriques Détruits"],
    critical_alerts: ["Mali/BF/Niger: mariage précoce protection", "RDC: recrutement enfants soldats", "Yémen/Gaza: déni santé éducation", "Inde/Bangladesh: travail enfants exploitation"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "child_rights",
    confidence_score: 0.86,
    data_sources: ["unicef_state_of_worlds_children_annual_report", "ilo_global_estimates_child_labour_2022", "un_committee_rights_child_concluding_observations_database"],
    entities,
    avg_estimated_child_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
