import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[anti-torture-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Anti-Torture Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/anti-torture-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Anti-Torture Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Anti-Torture Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "AT-001", name: "Chine/Xinjiang — Torture Systématique 1M+ Ouïghours, Témoignages & Denial State", country: "Asie du Nord-Est", sector: "Chine Torture Systématique Camps Xinjiang 1M+ Ouïghours, Électrochocs/Stress Positions Documentés PFEC, Déni État & Aucun Accès CAT Comité Contre la Torture Depuis 2015", composite_score: 91.60, torture_prevalence_severity_score: 95.0, legal_protection_failure_score: 90.0, detention_conditions_inhumane_score: 92.0, impunity_accountability_failure_score: 88.0, risk_level: "critique", primary_pattern: "torture_prevalence_severity", key_signals: ["Violation de l'interdiction de la torture documentée — Chine/Xinjiang avec score composite 91.60/100 révélant une torture systématique dans les camps de 'rééducation' violant l'Article 5 de la DUDH et la Convention contre la Torture (CAT) ratifiée par la Chine en 1988", "Prévalence torture (95.0/100) — les témoignages de 1 million+ de détenus ouïghours décrivant l'utilisation systématique d'électrochocs, privation de sommeil et positions de stress dans les camps constitue une torture systématique au sens de l'Article 1 CAT", "Activer le Comité CAT pour examen d'urgence de la situation en Xinjiang et exiger l'accès du Sous-Comité de prévention de la torture (SPT) aux centres de détention chinois conformément au Protocole facultatif à la CAT (OPCAT)"], estimated_anti_torture_index: 9.16, last_updated: "2026-06-20" },
    { entity_id: "AT-002", name: "Russie — Torture Prisonniers Politiques, Navalny Décès & Guerre Ukraine", country: "Europe de l'Est", sector: "Russie Torture Navalny Documentée Avant Décès 2024, Torture Prisonniers Guerre Ukraine, Bucha Actes Torture Documentés ICC, SIZO Centres Détention Torture Systématique & CEDH 1 000+ Arrêts", composite_score: 88.55, torture_prevalence_severity_score: 88.0, legal_protection_failure_score: 85.0, detention_conditions_inhumane_score: 90.0, impunity_accountability_failure_score: 92.0, risk_level: "critique", primary_pattern: "impunity_accountability_failure", key_signals: ["Violation de l'interdiction de la torture documentée — Russie avec score composite 88.55/100 révélant une torture systématique des prisonniers politiques et de guerre violant la Convention CAT et le Statut de Rome de la CPI pour les crimes commis en Ukraine", "Impunité/Responsabilité (92.0/100) — l'absence totale de poursuites pour la torture de Navalny, les actes documentés à Bucha et la torture dans les centres SIZO révèlent une impunité structurelle violant l'obligation de poursuites pénales de l'Article 7 CAT", "Activer le Comité CAT pour examen d'urgence de la situation russe et coopérer avec la Cour Pénale Internationale pour poursuivre les responsables de torture en Ukraine conformément au mandat du Statut de Rome"], estimated_anti_torture_index: 8.86, last_updated: "2026-06-20" },
    { entity_id: "AT-003", name: "Syrie — Torture Industrielle Assad, 14 000 Détenus Tués & Photos Caesar", country: "MENA", sector: "Syrie Torture Industrielle Prisons Saydnaya/Al-Khatib, Photos Caesar 55 000 Cadavres Torturés Détenus, 14 000 Morts En Détention ONU & CESJ Mécanisme International Impartial Syrie", composite_score: 88.85, torture_prevalence_severity_score: 92.0, legal_protection_failure_score: 85.0, detention_conditions_inhumane_score: 88.0, impunity_accountability_failure_score: 90.0, risk_level: "critique", primary_pattern: "torture_prevalence_severity", key_signals: ["Violation de l'interdiction de la torture documentée — Syrie avec score composite 88.85/100 révélant une torture industrielle de masse dans les prisons d'Assad documentée par 55 000 photos Caesar, constituant des crimes contre l'humanité sous le Statut de Rome", "Prévalence torture (92.0/100) — les 55 000 photos Caesar documentant des cadavres de détenus torturés et les 14 000 décès en détention révèlent une politique de torture étatique systématique et généralisée au sens de l'Article 7 du Statut de Rome de la CPI", "Activer le Mécanisme international, impartial et indépendant (IIIM) Syrie et coopérer avec la Cour Pénale Internationale pour poursuivre les membres du régime Assad responsables de torture en tant que crime contre l'humanité"], estimated_anti_torture_index: 8.89, last_updated: "2026-06-20" },
    { entity_id: "AT-004", name: "Arabie Saoudite — Khashoggi, Torture Prisons & Loi Anti-Terrorisme Couverte", country: "MENA", sector: "Arabie Saoudite Khashoggi Meurtre/Torture Consulat Istanbul 2018, Torture Prisonniers Politiques Femmes Militantes, Cour Terrorisme Jugements Rapides Sans Garanties & CNIA Impunité MBS", composite_score: 87.65, torture_prevalence_severity_score: 85.0, legal_protection_failure_score: 90.0, detention_conditions_inhumane_score: 85.0, impunity_accountability_failure_score: 92.0, risk_level: "critique", primary_pattern: "impunity_accountability_failure", key_signals: ["Violation de l'interdiction de la torture documentée — Arabie Saoudite avec score composite 87.65/100 révélant la torture et l'assassinat de Jamal Khashoggi documentés par la Rapporteure Spéciale ONU et la torture systématique des prisonniers politiques violant la CAT", "Impunité/Responsabilité (92.0/100) — l'impunité totale de Mohamed Ben Salmane pour l'assassinat de Khashoggi et la torture des militantes des droits des femmes dans les prisons saoudiennes révèlent un système d'impunité d'État violant l'Article 7 CAT sur l'obligation de poursuites", "Activer le Comité CAT pour examen d'urgence des pratiques de torture en Arabie Saoudite et exiger la levée du secret sur les enquêtes internes concernant la mort de Khashoggi conformément aux Principes d'Istanbul sur l'efficacité des enquêtes sur la torture"], estimated_anti_torture_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "AT-005", name: "USA — Guantanamo, Black Sites CIA & Waterboarding Torture Mémos Bush", country: "Amérique du Nord", sector: "USA Guantanamo 30+ Prisonniers 20+ Ans Sans Procès, Waterboarding CIA Black Sites Mémos Bush 2002, Rapport Sénate Feinstein 2014 Torture SSCI & Impunité Totale Acteurs CIA", composite_score: 56.10, torture_prevalence_severity_score: 55.0, legal_protection_failure_score: 52.0, detention_conditions_inhumane_score: 60.0, impunity_accountability_failure_score: 58.0, risk_level: "élevé", primary_pattern: "detention_conditions_inhumane", key_signals: ["Violation de l'interdiction de la torture documentée — USA avec score composite 56.10/100 révélant l'utilisation documentée du waterboarding et de techniques améliorées d'interrogatoire par la CIA, qualifiées de torture par le rapport sénatorial Feinstein 2014", "Conditions détention inhumaines (60.0/100) — la détention de 30+ prisonniers à Guantanamo depuis plus de 20 ans sans procès et l'utilisation de privation sensorielle constituent des peines ou traitements cruels, inhumains ou dégradants interdits par l'Article 16 CAT", "Fermer Guantanamo Bay conformément aux engagements présidentiels Obama-Biden et poursuivre les responsables des 'enhanced interrogation techniques' de la CIA conformément à l'obligation de poursuites pénales des Articles 4-7 de la Convention CAT"], estimated_anti_torture_index: 5.61, last_updated: "2026-06-20" },
    { entity_id: "AT-006", name: "Thaïlande/Philippines — Tortured Suspects, Drug War & Disparitions", country: "Asie du Sud-Est", sector: "Thaïlande 2014-20 Coup Torture Détenus Armée, Philippines Drug War Duterte 30 000 Tués, Torture Aveux Policiers Documentés & Impunité Fonctionnaires Sécurité Philippines/Thaïlande", composite_score: 53.35, torture_prevalence_severity_score: 52.0, legal_protection_failure_score: 55.0, detention_conditions_inhumane_score: 52.0, impunity_accountability_failure_score: 55.0, risk_level: "élevé", primary_pattern: "legal_protection_failure", key_signals: ["Violation de l'interdiction de la torture documentée — Thaïlande/Philippines avec score composite 53.35/100 révélant la torture par l'armée thaïlandaise documentée après le coup de 2014 et les 30 000 morts extrajudiciaires de la 'guerre contre la drogue' de Duterte aux Philippines", "Défaillance protection légale (55.0/100) — l'absence de poursuites pour les actes de torture commis par les forces de sécurité en Thaïlande et aux Philippines révèle des lacunes systémiques dans la transposition et l'application des obligations CAT en droit interne", "Activer le Comité CAT pour examen des rapports périodiques de Thaïlande et des Philippines et exiger l'ouverture d'une enquête indépendante sur les morts extrajudiciaires de la guerre anti-drogue conformément aux Principes ONU sur les exécutions extrajudiciaires"], estimated_anti_torture_index: 5.34, last_updated: "2026-06-20" },
    { entity_id: "AT-007", name: "Europe/CEDH — Conditions Prison Inhumaines, Grèce/Bulgarie & Art 3 Violations", country: "Europe", sector: "Grèce/Bulgarie CEDH Art 3 Violations Surpopulation Carcérale, Pologne Détention Secrète CIA Black Site, Malte/Italie Détention Migrants Conditions Inhumaines & CPEDT Rapports Systémiques", composite_score: 28.90, torture_prevalence_severity_score: 28.0, legal_protection_failure_score: 30.0, detention_conditions_inhumane_score: 32.0, impunity_accountability_failure_score: 25.0, risk_level: "modéré", primary_pattern: "detention_conditions_inhumane", key_signals: ["Violations persistantes de l'Article 3 CEDH en Europe — conditions pénitentiaires inhumaines documentées en Grèce et Bulgarie par la CEDH et conditions de détention des migrants révèlent des violations de l'interdiction de la torture dans des États membres du Conseil de l'Europe", "Conditions détention inhumaines (32.0/100) — la surpopulation carcérale chronique en Grèce et Bulgarie condamnée répétitivement par la CEDH au titre de l'Article 3 sur l'interdiction des traitements inhumains ou dégradants", "Renforcer le mécanisme de surveillance du Comité européen pour la prévention de la torture (CPT) et assurer la mise en œuvre des arrêts CEDH condamnant les conditions pénitentiaires inhumaines dans les États membres du Conseil de l'Europe"], estimated_anti_torture_index: 2.89, last_updated: "2026-06-20" },
    { entity_id: "AT-008", name: "CAT-ONU/SPT — Convention 1984, OPCAT & Rapporteur Spécial Torture", country: "Global", sector: "Convention CAT 1984 174 États Parties, OPCAT Protocole Facultatif SPT 2002, Rapporteur Spécial ONU Torture, Comité CAT 10 Experts & Principes Istanbul Enquête Efficace", composite_score: 4.45, torture_prevalence_severity_score: 5.0, legal_protection_failure_score: 4.0, detention_conditions_inhumane_score: 3.0, impunity_accountability_failure_score: 6.0, risk_level: "faible", primary_pattern: "impunity_accountability_failure", key_signals: ["CAT-ONU/SPT incarne le cadre normatif exemplaire de l'interdiction de la torture — Convention de 1984 posant une interdiction absolue non-dérogeable et Protocole facultatif OPCAT créant un système de visites préventives indépendantes des lieux de détention", "Convention CAT Article 1 — définit la torture comme tout acte intentionnel causant douleur ou souffrance aiguë infligé par un agent de l'État ou avec son consentement, créant une interdiction absolue ne souffrant aucune exception ni dérogation", "Universaliser la ratification de l'OPCAT et renforcer le Sous-Comité de prévention de la torture (SPT) pour garantir un accès effectif à tous les lieux de détention dans les 174 États parties à la Convention contre la torture"], estimated_anti_torture_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { torture_prevalence_severity: 2, impunity_accountability_failure: 3, legal_protection_failure: 1, detention_conditions_inhumane: 2 },
    top_risk_entities: ["Chine/Xinjiang — Torture Systématique 1M+ Ouïghours, Témoignages & Denial State", "Syrie — Torture Industrielle Assad, 14 000 Détenus Tués & Photos Caesar", "Russie — Torture Prisonniers Politiques, Navalny Décès & Guerre Ukraine"],
    critical_alerts: ["Chine/Xinjiang: torture prevalence severity", "Russie: impunity accountability failure", "Syrie: torture prevalence severity", "Arabie Saoudite: impunity accountability failure"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "anti_torture",
    confidence_score: 0.86,
    data_sources: ["un_committee_against_torture_concluding_observations_database", "un_special_rapporteur_torture_country_visits_reports", "amnesty_international_global_report_torture_ill_treatment"],
    entities,
    avg_estimated_anti_torture_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
