import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[colonial-reparations-restitution-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = {
  agent: "Colonial Reparations Restitution Rights Engine Agent",
  domain: "colonial_reparations_restitution_rights",
  total_entities: 8,
  avg_composite: 60.94,
  confidence_score: 0.87,
  avg_estimated_colonial_reparations_restitution_rights_index: 6.09,
  risk_distribution: { critique: 4, "élevé": 2, modéré: 1, faible: 1 },
  pattern_distribution: { looted_artifacts_restitution: 3, structural_reparations_denial: 2, indigenous_land_restitution: 2, historical_accountability_gap: 1 },
  top_risk_entities: [
    "Belgique/Congo — Génocide Léopold II, 10M Morts & Refus Réparations Structurelles",
    "Royaume-Uni/CARICOM — 4.8M Esclaves Transatlantiques & Refus Négociation Reparations",
    "France/Haïti — Dette Coloniale 21 Milliards & Remboursement Jusqu'en 1950",
  ],
  critical_alerts: [
    "Belgique/Congo: structural_reparations_denial",
    "Royaume-Uni/CARICOM: structural_reparations_denial",
    "France/Haïti: historical_accountability_gap",
    "Allemagne/Namibie: looted_artifacts_restitution",
  ],
  last_analysis: "2026-06-21",
  engine_version: "1.0.0",
  data_sources: [
    "un_basic_principles_reparations_2005",
    "african_union_reparations_2022",
    "caricom_reparations_commission_2023",
    "ohchr_colonial_legacy_2022",
  ],
  entities: [
    { id: "CR-001", name: "Belgique/Congo — Génocide Léopold II, 10M Morts & Refus Réparations Structurelles", country: "Europe/Afrique Centrale", sector: "État Indépendant Congo Léopold II 10M Morts 1885-1908, Pillage Caoutchouc Ivoire, Mutilations Mains Documentées & Excuses 2020 Sans Réparations Concrètes", composite_score: 89.4, looted_artifacts_restitution_score: 85.0, structural_reparations_denial_score: 95.0, indigenous_land_restitution_score: 88.0, historical_accountability_gap_score: 90.0, risk_level: "critique", primary_pattern: "structural_reparations_denial", key_signals: ["Génocide colonial belge non réparé — régime Léopold II au Congo a causé 10 millions de morts (1885-1908) avec mutilations systématiques, pillage des ressources et travail forcé, crime contre l'humanité sans réparations structurelles malgré excuses du roi Philippe en 2020", "Refus de réparations concrètes — la Belgique a exprimé des 'profonds regrets' mais refuse toute réparation financière ou restitution systématique au Congo, illustrant le fossé entre reconnaissance symbolique et justice réparatrice", "Exiger que la Belgique négocie avec la RDC un traité de réparations incluant restitution artefacts Musée Royal Afrique Centrale, annulation dette coloniale et programme de développement de 50 milliards sur 20 ans"], estimated_colonial_reparations_restitution_rights_index: 8.94, last_updated: "2026-06-21" },
    { id: "CR-002", name: "Royaume-Uni/CARICOM — 4.8M Esclaves Transatlantiques & Refus Négociation Réparations", country: "Europe/Caraïbes", sector: "4.8M Esclaves Transport Britannique Atlantique, CARICOM Réparations 10 Points Plan 2013, Refus UK Négociation Formelle & Compensation 1833 Esclavagistes Seulement", composite_score: 86.2, looted_artifacts_restitution_score: 82.0, structural_reparations_denial_score: 92.0, indigenous_land_restitution_score: 80.0, historical_accountability_gap_score: 90.0, risk_level: "critique", primary_pattern: "structural_reparations_denial", key_signals: ["Paradoxe des réparations britanniques — le Royaume-Uni a versé en 1833 des compensations exclusivement aux propriétaires d'esclaves (pas aux esclaves libérés), et refuse en 2026 toute négociation avec CARICOM sur les réparations aux descendants", "Plan CARICOM en attente — la Commission Réparations CARICOM a présenté en 2013 un plan en 10 points incluant développement, aide psychologique et annulation dette, ignoré par le Royaume-Uni pendant 13 ans", "Exiger que le Royaume-Uni engage des négociations formelles avec CARICOM dans le cadre de l'ONU et établisse un fonds de réparations de 100 milliards en accord avec les Principes Fondamentaux ONU de 2005"], estimated_colonial_reparations_restitution_rights_index: 8.62, last_updated: "2026-06-21" },
    { id: "CR-003", name: "France/Haïti — Dette Coloniale 21 Milliards & Remboursement Jusqu'en 1950", country: "Europe/Caraïbes", sector: "Haïti Payé 21 Milliards Francs 1825-1947 Pour Liberté, Indépendance 1804 Punition Dette Coloniale, Emprunts Bancaires Remboursés 1950 & Appauvrissement Structurel Causé", composite_score: 88.1, looted_artifacts_restitution_score: 80.0, structural_reparations_denial_score: 90.0, indigenous_land_restitution_score: 82.0, historical_accountability_gap_score: 95.0, risk_level: "critique", primary_pattern: "historical_accountability_gap", key_signals: ["Injustice historique unique — Haïti est le seul pays au monde contraint de payer une indemnité aux anciens colonisateurs pour sa propre liberté (150 millions de francs or en 1825, équivalent à 21 milliards actuels), remboursée jusqu'en 1950", "Appauvrissement structurel causé par dette coloniale — les économistes estiment que cette dette coloniale a structurellement appauvri Haïti pendant 125 ans, expliquant en partie son sous-développement chronique et sa vulnérabilité aux catastrophes", "Exiger que la France restitue à Haïti les 21 milliards de francs (actualisés) perçus comme 'rançon de la liberté' et s'engage dans un programme de développement prioritaire en reconnaissance de cette dette historique"], estimated_colonial_reparations_restitution_rights_index: 8.81, last_updated: "2026-06-21" },
    { id: "CR-004", name: "Allemagne/Namibie — Génocide Herero-Nama 1904, Accord 2021 Insuffisant & Artefacts Non Restitués", country: "Europe/Afrique Australe", sector: "Génocide Herero-Nama 65 000-80 000 Morts 1904-1908, Accord 2021 1.1 Milliard Sans Terme 'Réparations', Crânes Humains Volés Non Restitués & Descendants Exclus Négociations", composite_score: 83.7, looted_artifacts_restitution_score: 88.0, structural_reparations_denial_score: 85.0, indigenous_land_restitution_score: 80.0, historical_accountability_gap_score: 82.0, risk_level: "critique", primary_pattern: "looted_artifacts_restitution", key_signals: ["Premier génocide du XXe siècle partiellement reconnu — l'Allemagne a reconnu en 2021 le génocide Herero-Nama (65 000-80 000 morts) mais l'accord de 1.1 milliard sur 30 ans évite le terme 'réparations' et exclut les descendants des négociations", "Crânes humains volés — des centaines de crânes Herero et Nama emportés en Allemagne pour 'recherches raciales' n'ont pas tous été restitués, constituant une violation continue de la dignité des victimes", "Renégocier l'accord Allemagne-Namibie pour inclure le terme 'réparations' légalement contraignant, restituer tous les restes humains et associer directement les communautés Herero-Nama aux décisions d'allocation des fonds"], estimated_colonial_reparations_restitution_rights_index: 8.37, last_updated: "2026-06-21" },
    { id: "CR-005", name: "Musées Européens/Afrique — 90 000+ Artefacts Pillés & Restitution Fragmentée", country: "Europe/Afrique", sector: "90 000 Objets Africains Musées Européens Estimés, Bronzes Bénin British Museum Retour Partiel 2022, France/Sénégal 26 Pièces 2021 & Débat Universalité Musées vs Réparation", composite_score: 53.4, looted_artifacts_restitution_score: 65.0, structural_reparations_denial_score: 50.0, indigenous_land_restitution_score: 45.0, historical_accountability_gap_score: 54.0, risk_level: "élevé", primary_pattern: "looted_artifacts_restitution", key_signals: ["Restitution fragmentée insuffisante — les musées européens détiennent 90 000+ artefacts africains pillés pendant la colonisation, mais les restitutions restent symboliques (26 pièces France/Sénégal, quelques Bronzes Bénin) face à l'ampleur du pillage", "Argument de l'universalité des musées — le British Museum et le Louvre invoquent leur statut de 'musées universels' pour résister aux restitutions massives, argument contesté par les pays d'origine qui réclament leur patrimoine culturel volé", "Adopter une convention internationale contraignante sur la restitution des artefacts coloniaux avec délai de 10 ans pour retourner les objets identifiés comme pillés après 1870 dans les pays d'origine"], estimated_colonial_reparations_restitution_rights_index: 5.34, last_updated: "2026-06-21" },
    { id: "CR-006", name: "Pays-Bas/Indonésie — Violences 1945-49, Excuses 2022 & Programme Réparations Limité", country: "Europe/Asie du Sud-Est", sector: "Violences Extrêmes Guerre Indépendance 1945-49 Reconnues, Excuses Roi Willem-Alexander 2022, Programme 10M€ Victimes Vivantes & Descendants 1.2M Morts Non Couverts", composite_score: 47.8, looted_artifacts_restitution_score: 45.0, structural_reparations_denial_score: 50.0, indigenous_land_restitution_score: 42.0, historical_accountability_gap_score: 55.0, risk_level: "élevé", primary_pattern: "structural_reparations_denial", key_signals: ["Progrès réels mais insuffisants — les Pays-Bas ont reconnu en 2022 les 'violences extrêmes' de 1945-49 en Indonésie et le roi a présenté des excuses officielles, mais le programme de réparations de 10M€ ne couvre que les victimes vivantes directes", "1.2 million de morts non réparés — le programme néerlandais exclut la réparation pour les descendants des 1.2 million de victimes indonésiennes de la guerre d'indépendance, limitant la portée de la justice réparatrice", "Élargir le programme néerlandais de réparations Indonésie pour inclure les descendants des victimes et créer un fonds historique pour l'éducation et la préservation mémoire de la résistance indonésienne"], estimated_colonial_reparations_restitution_rights_index: 4.78, last_updated: "2026-06-21" },
    { id: "CR-007", name: "UA/CARICOM Commission Réparations — Cadre Continental & Solidarité Sud-Sud", country: "Global Sud", composite_score: 25.3, looted_artifacts_restitution_score: 28.0, structural_reparations_denial_score: 22.0, indigenous_land_restitution_score: 28.0, historical_accountability_gap_score: 23.0, risk_level: "modéré", primary_pattern: "structural_reparations_denial", key_signals: ["Coordination Sud-Sud comme levier — l'Union Africaine et CARICOM développent un front uni sur les réparations coloniales, renforçant la légitimité des demandes face aux puissances coloniales européennes réticentes", "Absence de mécanisme contraignant — malgré les Principes Fondamentaux ONU sur Réparations (2005), aucun mécanisme international contraignant n'existe pour forcer les États à négocier les réparations coloniales", "Créer un Tribunal International des Réparations Coloniales sous égide ONU avec compétence contraignante sur les demandes de restitution et réparations issues du colonialisme"], estimated_colonial_reparations_restitution_rights_index: 2.53, last_updated: "2026-06-21" },
    { id: "CR-008", name: "ONU/OHCHR — Principes Fondamentaux Réparations 2005 & Rapporteur Héritage Colonial", country: "Global", composite_score: 4.62, looted_artifacts_restitution_score: 5.0, structural_reparations_denial_score: 4.0, indigenous_land_restitution_score: 5.0, historical_accountability_gap_score: 4.5, risk_level: "faible", primary_pattern: "historical_accountability_gap", key_signals: ["Principes Fondamentaux ONU comme socle normatif — la résolution 60/147 de 2005 établit le droit à réparation (restitution, indemnisation, réhabilitation, satisfaction, garanties de non-répétition) applicable aux violations massives historiques", "Mandat du Rapporteur Spécial sur l'héritage colonial — créé en 2021, ce mandat ONU renforce le cadre normatif mais reste consultatif, sans pouvoir contraignant sur les États refusant de négocier les réparations", "Renforcer le mandat du Rapporteur Spécial sur l'héritage colonial pour inclure des visites de pays et des recommandations contraignantes soumises au Conseil de Sécurité"], estimated_colonial_reparations_restitution_rights_index: 0.46, last_updated: "2026-06-21" },
  ],
};

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/colonial-reparations-restitution-rights-engine`, {
      next: { revalidate: 30 },
    });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}
