import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[transitional-justice-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Transitional Justice Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/transitional-justice-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Transitional Justice Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Transitional Justice Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "TJ-001", name: "Myanmar — Génocide Rohingya, CIJ Arrêt 2023 Non-Exécuté & Junte Impunité", country: "Asie du Sud-Est", sector: "Myanmar Génocide Rohingya CIJ Affaire Gambie 2019, Junte Militaire Crimes Humanité 2021+, Arrêt CIJ Mesures Provisoires Non-Exécutées & Aucune Commission Vérité Perspective", composite_score: 89.75, truth_commission_absence_score: 92.0, reparations_denial_score: 88.0, perpetrator_impunity_score: 95.0, memory_historical_denial_score: 82.0, risk_level: "critique", primary_pattern: "perpetrator_impunity", key_signals: ["Défaillance de justice transitionnelle documentée — Myanmar avec score composite 89.75/100 révélant une impunité totale pour le génocide rohingya et les crimes contre l'humanité de la junte, les mécanismes de justice transitionnelle étant bloqués malgré l'arrêt de la CIJ de 2023", "Impunité des auteurs (95.0/100) — les chefs de la junte militaire poursuivis par la CIJ pour génocide rohingya et responsables de crimes contre l'humanité post-coup 2021 jouissent d'une impunité totale violant l'obligation de punir les crimes internationaux sous le Statut de Rome", "Renforcer la compétence de la Cour Pénale Internationale pour les crimes au Myanmar via un renvoi du Conseil de Sécurité ONU et appliquer les mesures provisoires ordonnées par la CIJ incluant la prévention de nouveaux actes génocidaires contre les Rohingyas"], estimated_transitional_justice_index: 8.98, last_updated: "2026-06-20" },
    { entity_id: "TJ-002", name: "Syrie — IIIM Mécanisme Bloqué, Assad Crimes Contre Humanité & Preuves Perdues", country: "MENA", sector: "Syrie Assad Crimes Contre Humanité Documentés IIIM, Tentatives CPI Bloquées Russie/Chine Veto, Photos Caesar 55 000 Victimes & Pas Processus Justice Transitionnelle 15 Ans Conflit", composite_score: 88.25, truth_commission_absence_score: 90.0, reparations_denial_score: 85.0, perpetrator_impunity_score: 92.0, memory_historical_denial_score: 85.0, risk_level: "critique", primary_pattern: "perpetrator_impunity", key_signals: ["Défaillance de justice transitionnelle documentée — Syrie avec score composite 88.25/100 révélant 15 ans de conflits sans mécanisme de justice effectif pour les crimes d'Assad, les vetos russe et chinois au Conseil de Sécurité bloquant tout renvoi à la CPI", "Impunité des auteurs (92.0/100) — le régime d'Assad responsable de crimes contre l'humanité documentés par le Mécanisme IIIM ONU jouissant d'une impunité totale protégé par les vetos russes et chinois révèle une défaillance structurelle du Conseil de Sécurité de l'ONU", "Utiliser les compétences juridictionnelles nationales pour poursuivre les responsables syriens via le principe de compétence universelle (Allemagne, Suède, Suisse) et renforcer le financement du Mécanisme IIIM pour préserver les preuves pour les poursuites futures"], estimated_transitional_justice_index: 8.83, last_updated: "2026-06-20" },
    { entity_id: "TJ-003", name: "RDC — LRA/M23 Impunité, CPI Limité & 30 Ans Cycles Violence Non-Résolus", country: "Afrique Centrale", sector: "RDC LRA Joseph Kony Toujours En Fuite, M23 Crimes 2023 Non-Poursuivis, CPI 6 Condamnations 30 Ans Cycles Violence & Aucune Commission Vérité Réconciliation Nationale", composite_score: 85.90, truth_commission_absence_score: 88.0, reparations_denial_score: 82.0, perpetrator_impunity_score: 88.0, memory_historical_denial_score: 85.0, risk_level: "critique", primary_pattern: "truth_commission_absence", key_signals: ["Défaillance de justice transitionnelle documentée — RDC avec score composite 85.90/100 révélant 30 ans de cycles de violence sans mécanisme de justice transitionnelle effectif, la CPI n'ayant obtenu que 6 condamnations pour une région productrice de milliers de crimes internationaux", "Absence commission vérité (88.0/100) — l'absence de Commission Vérité et Réconciliation nationale en RDC et l'impunité persistante des groupes armés actifs créent un terreau pour la répétition des cycles de violence violant le droit à la vérité des victimes", "Établir une Commission Vérité et Réconciliation nationale en RDC intégrant les mécanismes traditionnels de justice réparatrice et renforcer la coopération avec la CPI pour l'arrestation des suspects dont les mandats sont en attente d'exécution"], estimated_transitional_justice_index: 8.59, last_updated: "2026-06-20" },
    { entity_id: "TJ-004", name: "Cambodge — ECCC Trop Tardif, 3 Condamnations Khmers Rouges & Réparations Dérisoires", country: "Asie du Sud-Est", sector: "Cambodge ECCC Chambres Extraordinaires 3 Condamnations Seulement Khmers Rouges 50+ Ans Post-Génocide, Réparations Symboliques, Accusés Décédés & Survie Questionnée Par Victimes", composite_score: 84.75, truth_commission_absence_score: 85.0, reparations_denial_score: 88.0, perpetrator_impunity_score: 85.0, memory_historical_denial_score: 80.0, risk_level: "critique", primary_pattern: "reparations_denial", key_signals: ["Défaillance de justice transitionnelle documentée — Cambodge avec score composite 84.75/100 révélant que le tribunal hybride ECCC n'a obtenu que 3 condamnations pour les crimes des Khmers rouges causant 1.7 million de morts, avec des réparations jugées dérisoires par les victimes", "Déni réparations (88.0/100) — les réparations symboliques accordées aux victimes des Khmers rouges par les ECCC ne correspondent pas à l'ampleur des préjudices subis, violant le droit à des réparations adéquates garanti par les Principes Van Boven/Bassiouni", "Assurer la clôture digne des ECCC avec un programme de réparations collectives substantiel pour les victimes des Khmers rouges et capitaliser les leçons apprises pour les mécanismes de justice transitionnelle futurs en Asie du Sud-Est"], estimated_transitional_justice_index: 8.48, last_updated: "2026-06-20" },
    { entity_id: "TJ-005", name: "Afghanistan — Taliban Retour, AIHRC Abolie & 20 Ans Crimes Non-Jugés", country: "Asie Centrale", sector: "Afghanistan Taliban 2021 Abolit AIHRC, 20 Ans Crimes Guerre Toutes Parties Non-Jugés, CPI Enquête Afghanistan Avancement Limité & Victimes USAID Réductions Justice Transitionnelle", composite_score: 56.50, truth_commission_absence_score: 55.0, reparations_denial_score: 58.0, perpetrator_impunity_score: 62.0, memory_historical_denial_score: 50.0, risk_level: "élevé", primary_pattern: "perpetrator_impunity", key_signals: ["Défaillance de justice transitionnelle documentée — Afghanistan avec score composite 56.50/100 révélant que le retour des Taliban en 2021 et l'abolition de la Commission des droits humains AIHRC ont anéanti 20 ans de progrès vers la justice transitionnelle", "Impunité des auteurs (62.0/100) — les crimes commis par toutes les parties au conflit afghan sur 20 ans restent impunis, la CPI ayant une enquête en cours très limitée et les Taliban ayant aboli les mécanismes nationaux de justice transitionnelle", "Maintenir l'enquête de la CPI sur l'Afghanistan et protéger les preuves de crimes de guerre malgré le retrait américain, et soutenir les victimes afghanes devant les juridictions de compétence universelle en Europe pour les crimes documentés"], estimated_transitional_justice_index: 5.65, last_updated: "2026-06-20" },
    { entity_id: "TJ-006", name: "Colombie/FARC — JEP Partiel, Réparations 9M Victimes & Résistances Impunité", country: "Amérique Latine", sector: "Colombie JEP Juridiction Spéciale Paix 9M Victimes Répertoriées, Reconnaissance Crimes FARC/État Partielle, Réparations Individuelles Non-Financées & Macrocriminalité Paramilitaires Non-Soumise", composite_score: 52.70, truth_commission_absence_score: 52.0, reparations_denial_score: 55.0, perpetrator_impunity_score: 55.0, memory_historical_denial_score: 48.0, risk_level: "élevé", primary_pattern: "reparations_denial", key_signals: ["Défaillance partielle de justice transitionnelle documentée — Colombie avec score composite 52.70/100 révélant les avancées mais aussi les limites de la JEP face aux 9 millions de victimes du conflit armé dont les réparations individuelles restent insuffisamment financées", "Déni réparations (55.0/100) — les réparations promises à 9 millions de victimes colombiennes par le processus de paix restent largement non-financées et l'impunité des structures paramilitaires non soumises à la JEP créent une justice transitionnelle incomplète", "Renforcer le financement des réparations aux victimes du conflit colombien conformément aux Principes Joinet/Van Boven et étendre la compétence de la JEP aux structures paramilitaires et aux responsabilités des entreprises complices du conflit armé"], estimated_transitional_justice_index: 5.27, last_updated: "2026-06-20" },
    { entity_id: "TJ-007", name: "Afrique du Sud/Rwanda — TRC/Gacaca Relatifs Succès & Leçons Justice Réparatrice", country: "Afrique", sector: "Afrique du Sud TRC Commission Vérité Réconciliation 1995-2002 Modèle Mondial, Rwanda Gacaca 1.2M Affaires 2002-12, Limites Réparations Faibles SA & Récidive Violence Économique", composite_score: 30.90, truth_commission_absence_score: 28.0, reparations_denial_score: 32.0, perpetrator_impunity_score: 30.0, memory_historical_denial_score: 35.0, risk_level: "modéré", primary_pattern: "memory_historical_denial", key_signals: ["Succès relatifs de justice transitionnelle — Afrique du Sud et Rwanda offrent les modèles les plus cités de justice transitionnelle mondiale avec la TRC de Desmond Tutu et les tribunaux gacaca, mais révèlent aussi les limites des réparations insuffisantes et la persistance des inégalités structurelles", "Déni mémoire historique (35.0/100) — malgré la TRC en Afrique du Sud et les gacaca au Rwanda, les inégalités économiques héritées de l'apartheid et les divisions ethniques persistantes révèlent que la justice transitionnelle sans transformation économique reste incomplète", "Capitaliser les leçons des modèles TRC et gacaca pour élaborer des mécanismes de justice transitionnelle économique intégrant des réparations structurelles transformatrices aux injustices systémiques passées conformément aux recommandations du Rapporteur Spécial ONU sur la vérité et la justice"], estimated_transitional_justice_index: 3.09, last_updated: "2026-06-20" },
    { entity_id: "TJ-008", name: "CPI/ONU-Mécanismes — Statut Rome, Droit à Vérité & Principes Joinet", country: "Global", sector: "CPI Cour Pénale Internationale Statut Rome 1998, Droit à Vérité Résolution ONU 2005, Principes Joinet/Orentlicher Lutte Impunité, ICTJ Institut Justice Transitionnelle & Piliers CSNUT", composite_score: 4.45, truth_commission_absence_score: 5.0, reparations_denial_score: 4.0, perpetrator_impunity_score: 3.0, memory_historical_denial_score: 6.0, risk_level: "faible", primary_pattern: "memory_historical_denial", key_signals: ["CPI/ONU incarne le cadre normatif exemplaire de la justice transitionnelle — Statut de Rome 1998 créant la première juridiction pénale internationale permanente et Principes Joinet définissant les 4 piliers: vérité, justice, réparations et garanties de non-répétition", "Statut de Rome Article 17 — principe de complémentarité obligeant les États à poursuivre les crimes graves avant que la CPI puisse intervenir, créant une obligation d'enquêtes nationales sérieuses pour les crimes de guerre, crimes contre l'humanité et génocide", "Renforcer la CPI avec des contributions financières obligatoires des États membres, améliorer les mécanismes de coopération pour l'exécution des mandats d'arrêt et adopter un traité contraignant sur l'assistance mutuelle judiciaire internationale pour les crimes atroces"], estimated_transitional_justice_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { perpetrator_impunity: 3, truth_commission_absence: 1, reparations_denial: 2, memory_historical_denial: 2 },
    top_risk_entities: ["Myanmar — Génocide Rohingya, CIJ Arrêt 2023 Non-Exécuté & Junte Impunité", "Syrie — IIIM Mécanisme Bloqué, Assad Crimes Contre Humanité & Preuves Perdues", "RDC — LRA/M23 Impunité, CPI Limité & 30 Ans Cycles Violence Non-Résolus"],
    critical_alerts: ["Myanmar: perpetrator impunity", "Syrie: perpetrator impunity", "RDC: truth commission absence", "Cambodge: reparations denial"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "transitional_justice",
    confidence_score: 0.84,
    data_sources: ["ictj_country_programs_transitional_justice_database", "icc_situations_cases_investigations_database", "un_special_rapporteur_truth_justice_reparation_reports"],
    entities,
    avg_estimated_transitional_justice_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
