import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[forced-marriage-child-marriage-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(await sealResponse(MOCK));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/forced-marriage-child-marriage-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(await sealResponse(data));
  } catch {
    return NextResponse.json(await sealResponse(MOCK), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "FMCM-001", name: "Niger/75% Filles Mariées Avant 18 Ans Sahel", country: "Afrique de l'Ouest", sector: "Taux Mondial Le Plus Élevé, 76% Mariées <18 Ans UNICEF 2023, Régions Rurales Zinder & Maradi, Dot Bétail & Pauvreté Extrême", composite_score: 89.1, child_marriage_prevalence_harm_severity_score: 92.0, forced_marriage_coercion_consent_violation_scale_score: 88.0, girl_education_disruption_exclusion_score: 90.0, legal_minimum_age_enforcement_deficit_gap_score: 85.0, risk_level: "critique", primary_pattern: "mariage_enfants_prevalence_systemique", key_signals: ["Mariage des enfants critique de Niger/75% Filles Mariées Avant 18 Ans Sahel — filles mariées de force avant 18 ans, privées d'éducation, exposées aux violences conjugales et aux grossesses précoces mettant leur vie en danger", "Violation systémique du consentement — le mariage forcé constitue une forme d'esclavage moderne reconnue par le Statut de Rome, avec responsabilité des États qui le tolèrent", "Cercle vicieux intergénérationnel — les mères-enfants reproduisent les schémas de pauvreté, leurs filles étant à leur tour exposées au mariage précoce sans accès à l'éducation"], estimated_forced_marriage_child_marriage_rights_index: 8.91, last_updated: "2026-06-21" },
    { id: "FMCM-002", name: "Bangladesh/52% Mariage Enfants Pauvreté", country: "Asie du Sud", sector: "52% Filles Mariées <18 Ans, Ménages Sous Seuil Pauvreté, Cyclones & Déplacements Accélèrent Mariages & Filles Garçons Charge", composite_score: 85.45, child_marriage_prevalence_harm_severity_score: 87.0, forced_marriage_coercion_consent_violation_scale_score: 82.0, girl_education_disruption_exclusion_score: 85.0, legal_minimum_age_enforcement_deficit_gap_score: 88.0, risk_level: "critique", primary_pattern: "mariage_enfants_prevalence_systemique", key_signals: ["Mariage des enfants critique de Bangladesh/52% Mariage Enfants Pauvreté — filles mariées de force avant 18 ans, privées d'éducation, exposées aux violences conjugales et aux grossesses précoces mettant leur vie en danger", "Violation systémique du consentement — le mariage forcé constitue une forme d'esclavage moderne reconnue par le Statut de Rome, avec responsabilité des États qui le tolèrent", "Cercle vicieux intergénérationnel — les mères-enfants reproduisent les schémas de pauvreté, leurs filles étant à leur tour exposées au mariage précoce sans accès à l'éducation"], estimated_forced_marriage_child_marriage_rights_index: 8.55, last_updated: "2026-06-21" },
    { id: "FMCM-003", name: "Éthiopie/Tigré Mariages Forcés Conflit", country: "Afrique de l'Est", sector: "Conflit Tigré 2020-2022, Mariages Survie Famine, Filles 12-15 Ans Mariées Dot Bétail, UNICEF 2M Filles À Risque & Déplacement", composite_score: 84.5, child_marriage_prevalence_harm_severity_score: 85.0, forced_marriage_coercion_consent_violation_scale_score: 90.0, girl_education_disruption_exclusion_score: 82.0, legal_minimum_age_enforcement_deficit_gap_score: 80.0, risk_level: "critique", primary_pattern: "mariage_force_coercition_consentement", key_signals: ["Mariage des enfants critique de Éthiopie/Tigré Mariages Forcés Conflit — filles mariées de force avant 18 ans, privées d'éducation, exposées aux violences conjugales et aux grossesses précoces mettant leur vie en danger", "Violation systémique du consentement — le mariage forcé constitue une forme d'esclavage moderne reconnue par le Statut de Rome, avec responsabilité des États qui le tolèrent", "Cercle vicieux intergénérationnel — les mères-enfants reproduisent les schémas de pauvreté, leurs filles étant à leur tour exposées au mariage précoce sans accès à l'éducation"], estimated_forced_marriage_child_marriage_rights_index: 8.45, last_updated: "2026-06-21" },
    { id: "FMCM-004", name: "Soudan du Sud/Dot Bétail Filles 12 Ans", country: "Afrique de l'Est", sector: "Dot En Bétail Filles 12-15 Ans, Conflit Civil Aggrave Pratiques, 52% Filles Mariées <18 Ans & Impunité Totale Tradition", composite_score: 84.1, child_marriage_prevalence_harm_severity_score: 83.0, forced_marriage_coercion_consent_violation_scale_score: 88.0, girl_education_disruption_exclusion_score: 80.0, legal_minimum_age_enforcement_deficit_gap_score: 86.0, risk_level: "critique", primary_pattern: "mariage_force_coercition_consentement", key_signals: ["Mariage des enfants critique de Soudan du Sud/Dot Bétail Filles 12 Ans — filles mariées de force avant 18 ans, privées d'éducation, exposées aux violences conjugales et aux grossesses précoces mettant leur vie en danger", "Violation systémique du consentement — le mariage forcé constitue une forme d'esclavage moderne reconnue par le Statut de Rome, avec responsabilité des États qui le tolèrent", "Cercle vicieux intergénérationnel — les mères-enfants reproduisent les schémas de pauvreté, leurs filles étant à leur tour exposées au mariage précoce sans accès à l'éducation"], estimated_forced_marriage_child_marriage_rights_index: 8.41, last_updated: "2026-06-21" },
    { id: "FMCM-005", name: "Yemen/32% Filles Avant 15 Ans Guerre", country: "MENA", sector: "Guerre Civile Houthis 2015+, 32% Filles Mariées <15 Ans, Mariages Survie Économique, UNICEF 1.4M Filles À Risque 2023", composite_score: 56.9, child_marriage_prevalence_harm_severity_score: 55.0, forced_marriage_coercion_consent_violation_scale_score: 62.0, girl_education_disruption_exclusion_score: 58.0, legal_minimum_age_enforcement_deficit_gap_score: 52.0, risk_level: "élevé", primary_pattern: "deficit_age_legal_application", key_signals: ["Exploitation matrimoniale de Yemen/32% Filles Avant 15 Ans Guerre — millions de filles mariées avant 18 ans dans un contexte de prévalence élevée sans mécanismes efficaces de protection et d'application légale", "Impunité des pratiques traditionnelles — l'absence de poursuites judiciaires normalise le mariage des enfants comme norme sociale acceptable malgré les interdictions légales", "Exclusion éducative structurelle — le décrochage scolaire lié au mariage précoce perpétue la vulnérabilité économique et la dépendance des femmes vis-à-vis de leurs époux"], estimated_forced_marriage_child_marriage_rights_index: 5.69, last_updated: "2026-06-21" },
    { id: "FMCM-006", name: "Inde/Rajasthan Akha Teej Millions Mariages", country: "Asie du Sud", sector: "Festival Akha Teej Mariages Enfants Massifs, 27% Filles Mariées <18 Ans, Rajasthan Bihar UP Zones Haute Prévalence", composite_score: 50.75, child_marriage_prevalence_harm_severity_score: 48.0, forced_marriage_coercion_consent_violation_scale_score: 52.0, girl_education_disruption_exclusion_score: 55.0, legal_minimum_age_enforcement_deficit_gap_score: 48.0, risk_level: "élevé", primary_pattern: "deficit_age_legal_application", key_signals: ["Exploitation matrimoniale de Inde/Rajasthan Akha Teej Millions Mariages — millions de filles mariées avant 18 ans dans un contexte de prévalence élevée sans mécanismes efficaces de protection et d'application légale", "Impunité des pratiques traditionnelles — l'absence de poursuites judiciaires normalise le mariage des enfants comme norme sociale acceptable malgré les interdictions légales", "Exclusion éducative structurelle — le décrochage scolaire lié au mariage précoce perpétue la vulnérabilité économique et la dépendance des femmes vis-à-vis de leurs époux"], estimated_forced_marriage_child_marriage_rights_index: 5.08, last_updated: "2026-06-21" },
    { id: "FMCM-007", name: "UNICEF/Girls Not Brides Alliance", country: "Global", sector: "Alliance 1500 ONG 100 Pays, Plaidoyer Légal & Communautaire, Programmes Maintien Filles École & Sensibilisation", composite_score: 21.35, child_marriage_prevalence_harm_severity_score: 22.0, forced_marriage_coercion_consent_violation_scale_score: 18.0, girl_education_disruption_exclusion_score: 25.0, legal_minimum_age_enforcement_deficit_gap_score: 20.0, risk_level: "modéré", primary_pattern: "deficit_age_legal_application", key_signals: ["Risque résiduel mariage enfants de UNICEF/Girls Not Brides Alliance — incidents documentés sans institutionnalisation, cadres légaux insuffisamment appliqués ou exceptions judiciaires permettant des mariages précoces", "Vulnérabilités structurelles — pauvreté, normes de genre et systèmes d'état civil défaillants créent des conditions propices au maintien des mariages d'enfants", "Progrès fragiles — les avancées législatives peuvent être inversées par des pressions conservatrices, des conflits armés ou des crises économiques réduisant l'accès à l'éducation"], estimated_forced_marriage_child_marriage_rights_index: 2.14, last_updated: "2026-06-21" },
    { id: "FMCM-008", name: "ONU/CRC Art.16 & CEDAW Mariage Minimum 18 Ans", country: "Global", sector: "CRC 1989 Art.16 Consentement, CEDAW 1979 Art.16 Âge Minimum, Résolution AG 73/148 2018 & Protocoles Droits Filles", composite_score: 5.6, child_marriage_prevalence_harm_severity_score: 5.0, forced_marriage_coercion_consent_violation_scale_score: 4.0, girl_education_disruption_exclusion_score: 6.0, legal_minimum_age_enforcement_deficit_gap_score: 8.0, risk_level: "faible", primary_pattern: "protection_mariage_exemplaire", key_signals: ["ONU/CRC Art.16 & CEDAW Mariage Minimum 18 Ans représente les standards de protection exemplaire contre le mariage des enfants — application stricte de l'âge minimum de 18 ans sans exception judiciaire ou parentale", "Normes CRC et CEDAW respectées — systèmes d'état civil solides, éducation accessible aux filles et programmes de sensibilisation communautaire actifs", "Modèle exportable — financement Girls Not Brides, partage de bonnes pratiques légales et soutien technique aux pays à haute prévalence de mariage des enfants"], estimated_forced_marriage_child_marriage_rights_index: 0.56, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { mariage_enfants_prevalence_systemique: 2, mariage_force_coercition_consentement: 2, exclusion_education_filles: 0, deficit_age_legal_application: 3, protection_mariage_exemplaire: 1 },
    top_risk_entities: ["Niger/75% Filles Mariées Avant 18 Ans Sahel", "Bangladesh/52% Mariage Enfants Pauvreté", "Éthiopie/Tigré Mariages Forcés Conflit", "Soudan du Sud/Dot Bétail Filles 12 Ans"],
    critical_alerts: ["Niger/75% Filles Mariées: mariage enfants prevalence systemique", "Bangladesh/52%: mariage enfants prevalence systemique", "Éthiopie/Tigré: mariage force coercition consentement", "Soudan du Sud: mariage force coercition consentement"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "forced_marriage_child_marriage_rights",
    confidence_score: 0.86,
    data_sources: ["unicef_child_marriage_database_2023", "girls_not_brides_global_tracking", "un_cedaw_committee_periodic_reports", "hrw_child_marriage_investigations"],
    entities,
    avg_estimated_forced_marriage_child_marriage_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
