import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[forced-disappearance-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Forced Disappearance Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/forced-disappearance-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Forced Disappearance Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Forced Disappearance Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "FD-001", name: "RPDC — Kwanliso Camps, Disparitions Politiques & Familles Séparées 70 Ans", country: "Asie du Nord-Est", sector: "Kwanliso Camps Secrets 200 000 Détenus, Familles Séparées Guerres Corée, Rapatriements Forcés Chine & Songbun Système Punition", composite_score: 92.85, state_enforced_disappearance_score: 95.0, secret_detention_network_score: 92.0, family_notification_denial_score: 95.0, disappearance_impunity_score: 88.0, risk_level: "critique", primary_pattern: "disparition_forcee_etatique", key_signals: ["Disparitions forcées étatiques de RPDC — 200 000 détenus dans des camps Kwanliso secrets sans notification aux familles ni accès consulaire depuis des décennies", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Activer le Groupe de travail ONU sur les disparitions forcées pour visites urgentes et saisir le Comité des droits de l'homme pour mesures provisoires"], estimated_forced_disappearance_index: 9.29, last_updated: "2026-06-20" },
    { id: "FD-002", name: "Syrie/Assad — Sites Détention Secrète, 100 000+ Disparus & Torture Caesar", country: "MENA", sector: "Saydnaya Prison Secrète, 100 000+ Détenus Disparus, Photos Caesar 11 000 Corps Torturés & Familles Sans Information 10 Ans", composite_score: 90.85, state_enforced_disappearance_score: 92.0, secret_detention_network_score: 95.0, family_notification_denial_score: 90.0, disappearance_impunity_score: 85.0, risk_level: "critique", primary_pattern: "reseau_detention_secrete", key_signals: ["Réseau de détention secrète de Syrie/Assad — Saydnaya et 27 autres prisons secrètes où 100 000+ détenus ont disparu avec 11 000 morts torturés documentés par les photos Caesar", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Activer le Groupe de travail ONU sur les disparitions forcées et saisir la CPI pour crimes contre l'humanité via le mécanisme IIIM"], estimated_forced_disappearance_index: 9.09, last_updated: "2026-06-20" },
    { id: "FD-003", name: "Chine/Xinjiang — Disparitions Ouïghours, Camps ETIM & Séparations Familiales", country: "Asie", sector: "1M+ Ouïghours Camps Internement, Familles Australie/Europe Sans Contact, Disparitions Activistes Taïwan & Rendan Système", composite_score: 87.75, state_enforced_disappearance_score: 88.0, secret_detention_network_score: 85.0, family_notification_denial_score: 90.0, disappearance_impunity_score: 88.0, risk_level: "critique", primary_pattern: "deni_famille_information", key_signals: ["Déni d'information aux familles par Chine/Xinjiang — 1M+ Ouïghours disparus dans des camps d'internement avec interdiction de contact pour les familles de la diaspora mondiale", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Activer le Groupe de travail ONU sur les disparitions forcées et saisir les mécanismes CERD pour discrimination raciale systémique ciblant les Ouïghours"], estimated_forced_disappearance_index: 8.78, last_updated: "2026-06-20" },
    { id: "FD-004", name: "Argentine/Amérique Latine — Héritage Opération Condor & 30 000 Disparus", country: "Amérique du Sud", sector: "30 000 Disparus Argentine 1976-83, Opération Condor 6 Pays, Abuelas Plaza Mayo & Impunité Partielle Procès Tardifs", composite_score: 84.0, state_enforced_disappearance_score: 85.0, secret_detention_network_score: 82.0, family_notification_denial_score: 88.0, disappearance_impunity_score: 80.0, risk_level: "critique", primary_pattern: "deni_famille_information", key_signals: ["Déni d'information aux familles en Argentine/Amérique Latine — 30 000 disparus de l'Opération Condor avec des décennies de refus étatique avant les procès tardifs et l'action des Abuelas de la Plaza Mayo", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Soutenir les Abuelas de la Plaza Mayo et les commissions vérité régionales pour identification ADN des victimes et poursuite des responsables encore en vie"], estimated_forced_disappearance_index: 8.4, last_updated: "2026-06-20" },
    { id: "FD-005", name: "Mexique/Cartels — 100 000 Disparus & Fosses Communes Jalisco", country: "Amérique du Nord", sector: "100 000+ Disparus Officiels Mexique 2006-2024, Fosses Communes Jalisco 3 000 Corps, Familles Chercheuses & CNDH Impuissance", composite_score: 56.6, state_enforced_disappearance_score: 55.0, secret_detention_network_score: 52.0, family_notification_denial_score: 62.0, disappearance_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "deni_famille_information", key_signals: ["Déni d'information aux familles au Mexique — 100 000+ disparus officiels avec fosses communes découvertes par des collectifs de familles chercheuses face à l'impuissance de la CNDH", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Activer le Groupe de travail ONU sur les disparitions forcées pour visite de pays et soutenir financièrement les collectifs de familles chercheuses"], estimated_forced_disappearance_index: 5.66, last_updated: "2026-06-20" },
    { id: "FD-006", name: "Russie/Tchétchénie — Filtrages, Disparitions Ukraine & Sites Secrets FSB", country: "Europe de l'Est", sector: "Filtrations Tchétchénie 2000-09, Disparitions Ukrainiens 2022 HRW, Pits Mozdok Charniers & FSB Sites Detention Documentés HRW", composite_score: 54.85, state_enforced_disappearance_score: 52.0, secret_detention_network_score: 58.0, family_notification_denial_score: 55.0, disappearance_impunity_score: 55.0, risk_level: "élevé", primary_pattern: "reseau_detention_secrete", key_signals: ["Réseau de détention secrète de Russie/Tchétchénie — sites FSB non déclarés documentés par HRW en Tchétchénie et disparitions d'Ukrainiens dans les territoires occupés depuis 2022", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Activer le Groupe de travail ONU sur les disparitions forcées et saisir la CPI pour crimes contre l'humanité dans les territoires ukrainiens occupés"], estimated_forced_disappearance_index: 5.49, last_updated: "2026-06-20" },
    { id: "FD-007", name: "Sri Lanka/Colombie — Post-Conflit Disparitions & Commission Vérité Partielle", country: "Asie/Amérique du Sud", sector: "Sri Lanka Fin LTTE 2009 Milliers Disparus, Colombie FARC 80 000 Disparus, Commissions Vérité Incomplètes & Familles Attente", composite_score: 29.5, state_enforced_disappearance_score: 28.0, secret_detention_network_score: 32.0, family_notification_denial_score: 30.0, disappearance_impunity_score: 28.0, risk_level: "modéré", primary_pattern: "reseau_detention_secrete", key_signals: ["Réseau de détention secrète post-conflit au Sri Lanka/Colombie — disparitions lors des phases finales de conflits armés avec commissions vérité insuffisantes laissant des milliers de familles sans réponse", "Crime continu jusqu'à l'établissement du sort — la disparition forcée est un crime permanent tant que le sort de la victime reste inconnu, engageant la responsabilité internationale continue de l'État", "Soutenir les commissions vérité nationales et activer les mécanismes ICMP pour identification ADN des restes des victimes"], estimated_forced_disappearance_index: 2.95, last_updated: "2026-06-20" },
    { id: "FD-008", name: "ONU-WGEID/ICMP — Identification Victimes & Convention Disparitions", country: "Global", sector: "WGEID ONU 45+ Ans, Convention 2010 73 États Parties, ICMP ADN Identification Victimes & Bases Données Familles", composite_score: 4.45, state_enforced_disappearance_score: 5.0, secret_detention_network_score: 4.0, family_notification_denial_score: 3.0, disappearance_impunity_score: 6.0, risk_level: "faible", primary_pattern: "impunite_perpetrateurs_disparition", key_signals: ["ONU-WGEID/ICMP incarnent la protection exemplaire contre les disparitions — Convention 2010, identification ADN des victimes et mécanismes d'urgence pour familles des disparus", "Convention internationale 2010 pour protection de toutes les personnes contre les disparitions forcées — 73 États parties avec obligation de criminaliser les disparitions et de reconnaître le droit à la vérité", "Partager les méthodologies d'identification ADN et augmenter les contributions aux bases de données ICMP pour accélérer la résolution des cas de personnes disparues"], estimated_forced_disappearance_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { disparition_forcee_etatique: 1, reseau_detention_secrete: 3, deni_famille_information: 3, impunite_perpetrateurs_disparition: 1 },
    top_risk_entities: ["RPDC — Kwanliso Camps, Disparitions Politiques & Familles Séparées 70 Ans", "Syrie/Assad — Sites Détention Secrète, 100 000+ Disparus & Torture Caesar", "Chine/Xinjiang — Disparitions Ouïghours, Camps ETIM & Séparations Familiales"],
    critical_alerts: ["RPDC: disparition forcée étatique", "Syrie/Assad: réseau détention secrète", "Chine/Xinjiang: déni famille information", "Argentine: déni famille information"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "forced_disappearance",
    confidence_score: 0.84,
    data_sources: ["un_wgeid_annual_report", "amnesty_international_disappearances_database", "icmp_missing_persons_global_statistics"],
    entities,
    avg_estimated_forced_disappearance_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
