import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[disability-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Disability Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/disability-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Disability Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Disability Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "DR-001", name: "Chine — 85M Personnes Handicapées, Institutions Forcées & Eugénisme Légal Stérilisation", country: "Asie du Nord-Est", sector: "Chine 85M Handicapés Loi 1994 Maternité Eugénique Abrogée 2021, Institutions Psychiatriques Forcées, Stérilisation PH Mentale Historique & CRPD Ratifié 2008 Non-Appliqué", composite_score: 88.85, institutionalization_forced_score: 92.0, employment_discrimination_score: 88.0, accessibility_barrier_score: 85.0, legal_capacity_denial_score: 90.0, risk_level: "critique", primary_pattern: "institutionnalisation_forcee", key_signals: ["Violation des droits des personnes handicapées documentée — Chine avec score composite 88.85/100 révélant des discriminations systémiques violant la Convention des Nations Unies relative aux droits des personnes handicapées (CDPH/CRPD 2006)", "Institutionnalisation forcée (92.0/100) — le placement non consenti de personnes handicapées mentales dans des institutions psychiatriques constitue une violation de l'Article 19 CRPD sur le droit à la vie autonome et l'inclusion dans la communauté", "Activer le Comité des droits des personnes handicapées (CRPD Committee) pour examen des rapports périodiques et demander des mesures provisoires en cas d'institutionnalisation massive non consentie"], estimated_disability_rights_index: 8.89, last_updated: "2026-06-20" },
    { entity_id: "DR-002", name: "Russie — 600 000 Internés Psychiatriques, Punipsychiatrie & Article 29 CRPD Violations", country: "Europe de l'Est", sector: "Russie 600 000 Personnes Internées Psychneurological Internaty, Dissident Psychiatrique Héritage URSS, Capacité Juridique Retirée 150 000 Personnes & DI-2022 Réprimer Manifestants Via Psychiatrie", composite_score: 86.55, institutionalization_forced_score: 88.0, employment_discrimination_score: 82.0, accessibility_barrier_score: 85.0, legal_capacity_denial_score: 92.0, risk_level: "critique", primary_pattern: "deni_capacite_juridique", key_signals: ["Violation des droits des personnes handicapées documentée — Russie avec score composite 86.55/100 révélant des discriminations systémiques violant la Convention des Nations Unies relative aux droits des personnes handicapées (CDPH/CRPD 2006)", "Institutionnalisation forcée (88.0/100) — les 600 000 personnes placées dans des établissements psychiatriques russes sans accès à un contrôle judiciaire indépendant constituent une violation massive de l'Article 19 CRPD", "Activer le Comité des droits des personnes handicapées (CRPD Committee) pour examen des rapports périodiques et demander des mesures provisoires en cas d'institutionnalisation massive non consentie"], estimated_disability_rights_index: 8.66, last_updated: "2026-06-20" },
    { entity_id: "DR-003", name: "Inde — 26M Handicapés, Accessibilité 0%, Institutions Coloniales & RPWD 2016 Non-Appliqué", country: "Asie du Sud", sector: "Inde RPWD Act 2016 Non-Appliqué, 26M PH Pauvreté Extrême, 0.3% Emploi Formel, Bâtiments Publics Inaccessibles 95% & Institutions Coloniales Toujours Actives Asiles", composite_score: 86.40, institutionalization_forced_score: 85.0, employment_discrimination_score: 90.0, accessibility_barrier_score: 88.0, legal_capacity_denial_score: 82.0, risk_level: "critique", primary_pattern: "discrimination_emploi_handicap", key_signals: ["Violation des droits des personnes handicapées documentée — Inde avec score composite 86.40/100 révélant des discriminations systémiques violant la Convention des Nations Unies relative aux droits des personnes handicapées (CDPH/CRPD 2006)", "Institutionnalisation forcée (85.0/100) — la persistance d'asiles coloniaux et l'exclusion de 26 millions de personnes handicapées de l'emploi formel (0.3%) constituent des violations de l'Article 27 CRPD sur le droit au travail", "Activer le Comité des droits des personnes handicapées (CRPD Committee) pour examen des rapports périodiques et demander des mesures provisoires en cas d'institutionnalisation massive non consentie"], estimated_disability_rights_index: 8.64, last_updated: "2026-06-20" },
    { entity_id: "DR-004", name: "Afrique Sub-Saharienne — Rituels Ablation Albinos, Violence Sorcellerie & Exclusion Totale", country: "Afrique Sub-Saharienne", sector: "Tanzanie/Mozambique/Malawi Albinos Attaques Rituelles 200+ Meurtres/Mutilations, Exclusion Scolaire PH 80%, Emploi Formel <1% & CRPD Ratifié Sans Mécanisme Application", composite_score: 83.85, institutionalization_forced_score: 82.0, employment_discrimination_score: 85.0, accessibility_barrier_score: 88.0, legal_capacity_denial_score: 80.0, risk_level: "critique", primary_pattern: "barriere_accessibilite_structurelle", key_signals: ["Violation des droits des personnes handicapées documentée — Afrique Sub-Saharienne avec score composite 83.85/100 révélant des discriminations systémiques violant la Convention des Nations Unies relative aux droits des personnes handicapées (CDPH/CRPD 2006)", "Institutionnalisation forcée (82.0/100) — les 200+ meurtres rituels de personnes albinos et l'exclusion de 80% des personnes handicapées de l'éducation en Afrique subsaharienne constituent des violations graves des Articles 10/24 CRPD", "Activer le Comité des droits des personnes handicapées (CRPD Committee) pour examen des rapports périodiques et demander des mesures provisoires en cas d'institutionnalisation massive non consentie"], estimated_disability_rights_index: 8.39, last_updated: "2026-06-20" },
    { entity_id: "DR-005", name: "USA — ADA 1990 Lacunes, 25% Pauvreté PH, Institutions & Guardianship 1.3M", country: "Amérique du Nord", sector: "USA ADA 1990 Progrès Mais 1.3M Sous Guardianship Privation Capacité Juridique, 25% PH Pauvreté, 400 000 Institutions Long-Term Care & Olmstead Decision Non-Compliant États", composite_score: 53.45, institutionalization_forced_score: 52.0, employment_discrimination_score: 55.0, accessibility_barrier_score: 50.0, legal_capacity_denial_score: 58.0, risk_level: "élevé", primary_pattern: "deni_capacite_juridique", key_signals: ["Violation partielle des droits des personnes handicapées aux USA — 1.3 million de personnes sous guardianship total privées de capacité juridique en violation potentielle de l'Article 12 CRPD (non ratifié par les USA)", "Institutionnalisation forcée (52.0/100) — malgré la décision Olmstead de 1999, 400 000 personnes restent en institutions long-term care sans alternatives communautaires suffisantes violant l'esprit de l'ADA 1990", "Ratifier la CRPD et mettre en œuvre le plan de désinstitutionnalisation américain en conformité avec la décision Olmstead et les recommandations du National Council on Disability (NCD)"], estimated_disability_rights_index: 5.35, last_updated: "2026-06-20" },
    { entity_id: "DR-006", name: "Union Européenne — Désinstitutionnalisation Lente, CRPD Art 19 & Fonds Structurels Conditions", country: "Europe", sector: "UE CRPD Ratifiée 2010 Mais 700 000 Personnes Encore Institutionnalisées, Désinstitutionnalisation Lente Bulgarie/Roumanie, Fonds UE Dépensé Institutions & CPRD Comité Critiques 2015/2023", composite_score: 51.55, institutionalization_forced_score: 48.0, employment_discrimination_score: 52.0, accessibility_barrier_score: 55.0, legal_capacity_denial_score: 52.0, risk_level: "élevé", primary_pattern: "barriere_accessibilite_structurelle", key_signals: ["Violation partielle des droits des personnes handicapées dans l'UE — 700 000 personnes encore institutionnalisées malgré la ratification de la CRPD en 2010 et les engagements de désinstitutionnalisation des États membres", "Institutionnalisation forcée (48.0/100) — les fonds structurels européens utilisés pour rénover des institutions plutôt que financer des alternatives communautaires violent les conclusions du Comité CRPD de 2015 et 2023", "Conditionner les fonds structurels UE à la désinstitutionnalisation effective et créer un mécanisme de suivi européen contraignant pour l'application de l'Article 19 CRPD dans tous les États membres"], estimated_disability_rights_index: 5.16, last_updated: "2026-06-20" },
    { entity_id: "DR-007", name: "Royaume-Uni — Austerity Cuts, Benefits Sanctions & Care Act Lacunes", country: "Europe de l'Ouest", sector: "UK Austérité 2010-20 Coupes 30% Benefits PH, PIP Assessment Abusif, DWP Décès Liés Sanctions 111 000 PH & CRPD Comité Rapport Catastrophe Droits 2016/2022", composite_score: 28.90, institutionalization_forced_score: 28.0, employment_discrimination_score: 32.0, accessibility_barrier_score: 30.0, legal_capacity_denial_score: 25.0, risk_level: "modéré", primary_pattern: "discrimination_emploi_handicap", key_signals: ["Violations modérées des droits des personnes handicapées au Royaume-Uni — le Comité CRPD a qualifié en 2016 les coupes d'austérité britanniques de 'violation grave et systématique' des droits des personnes handicapées", "Institutionnalisation forcée (28.0/100) — les 111 000+ décès de personnes handicapées liés aux sanctions de benefits documentés par le DWP constituent une violation de l'Article 28 CRPD sur le droit à un niveau de vie adéquat", "Réviser le système PIP (Personal Independence Payment) britannique et rétablir les niveaux de financement pre-austérité des services aux personnes handicapées conformément aux recommandations CRPD 2022"], estimated_disability_rights_index: 2.89, last_updated: "2026-06-20" },
    { entity_id: "DR-008", name: "CRPD-ONU/DPO — Convention 2006, Comité CRPD & Mouvement Vie Autonome", country: "Global", sector: "CRPD Convention 2006 187 États Parties, Comité CRPD 18 Experts, Mouvement Vie Autonome Independent Living, Rapporteur Spécial ONU Personnes Handicapées & UNPRPD", composite_score: 4.45, institutionalization_forced_score: 5.0, employment_discrimination_score: 4.0, accessibility_barrier_score: 3.0, legal_capacity_denial_score: 6.0, risk_level: "faible", primary_pattern: "deni_capacite_juridique", key_signals: ["CRPD/DPO incarne le cadre exemplaire des droits des personnes handicapées — Convention 2006 ratifiée par 187 États et Comité CRPD créant un mécanisme de contrôle universel et un modèle social du handicap basé sur les droits", "CRPD Article 19 — garantit le droit de toutes les personnes handicapées à vivre dans la communauté avec les mêmes choix que les autres personnes, avec obligation pour les États de prendre des mesures effectives de désinstitutionnalisation", "Universaliser la ratification de la CRPD et de son Protocole facultatif (OP-CRPD) permettant les communications individuelles, et tripler le financement des mécanismes nationaux de protection des droits des personnes handicapées"], estimated_disability_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { institutionnalisation_forcee: 1, discrimination_emploi_handicap: 2, barriere_accessibilite_structurelle: 2, deni_capacite_juridique: 3 },
    top_risk_entities: ["Chine — 85M Personnes Handicapées, Institutions Forcées & Eugénisme Légal Stérilisation", "Russie — 600 000 Internés Psychiatriques, Punipsychiatrie & Article 29 CRPD Violations", "Inde — 26M Handicapés, Accessibilité 0%, Institutions Coloniales & RPWD 2016 Non-Appliqué"],
    critical_alerts: ["Chine: institutionnalisation forcée", "Russie: déni capacité juridique", "Inde: discrimination emploi handicap", "Afrique Sub-Saharienne: barrière accessibilité structurelle"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "disability_rights",
    confidence_score: 0.82,
    data_sources: ["un_crpd_committee_concluding_observations_database", "disability_rights_international_institutional_violence_reports", "world_report_on_disability_who_world_bank"],
    entities,
    avg_estimated_disability_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
