import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[environmental-defenders-persecution-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/environmental-defenders-persecution-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "EDP-001", name: "Honduras/177 Défenseurs Assassinés 2010-2022", country: "Amérique Centrale", sector: "177 Défenseurs Assassinés Depuis Coup 2009, Berta Cáceres COPINH 2016, Barrage Agua Zarca, Desa SA Complice & Impunité 93% Cas Non Résolus", defender_killing_impunity_severity_score: 96.0, criminalization_slapp_lawsuit_scale_score: 88.0, corporate_state_collusion_resource_conflict_score: 92.0, indigenous_land_defender_protection_deficit_score: 90.0, composite_score: 91.9, risk_level: "critique", primary_pattern: "assassinat_defenseur_impunite", key_signals: ["Assassinats de défenseurs critiques de Honduras/177 Défenseurs Assassinés 2010-2022 — meurtres ciblés de militants environnementaux et autochtones dans une totale impunité, violant le droit à la vie (DUDH Art.3) et le Protocole de Mindanao", "Criminalisation massive des défenseurs — poursuites judiciaires abusives (SLAPP) utilisées comme arme d'intimidation pour réduire au silence les militants environnementaux et protéger les intérêts industriels extractifs", "Collusion corpo-étatique — les gouvernements utilisent les forces de sécurité privées et publiques pour protéger les intérêts extractifs au détriment des communautés défendant leur territoire et leurs ressources"], estimated_environmental_defenders_persecution_index: 9.19, last_updated: "2026-06-21" },
    { id: "EDP-002", name: "Brésil/Amazonie 20+ Défenseurs/An Bolsonaro", country: "Amérique du Sud", sector: "270 Défenseurs Tués 2009-2019 Global Witness, Dom Phillips & Bruno Pereira 2022, FUNAI Démantelé, Garimpeiros Légalisés & 20+ Tués/An Sous Bolsonaro", defender_killing_impunity_severity_score: 90.0, criminalization_slapp_lawsuit_scale_score: 82.0, corporate_state_collusion_resource_conflict_score: 88.0, indigenous_land_defender_protection_deficit_score: 86.0, composite_score: 87.2, risk_level: "critique", primary_pattern: "assassinat_defenseur_impunite", key_signals: ["Assassinats de défenseurs critiques de Brésil/Amazonie 20+ Défenseurs/An Bolsonaro — meurtres ciblés de militants environnementaux et autochtones dans une totale impunité, violant le droit à la vie (DUDH Art.3) et le Protocole de Mindanao", "Criminalisation massive des défenseurs — poursuites judiciaires abusives (SLAPP) utilisées comme arme d'intimidation pour réduire au silence les militants environnementaux et protéger les intérêts industriels extractifs", "Collusion corpo-étatique — les gouvernements utilisent les forces de sécurité privées et publiques pour protéger les intérêts extractifs au détriment des communautés défendant leur territoire et leurs ressources"], estimated_environmental_defenders_persecution_index: 8.72, last_updated: "2026-06-21" },
    { id: "EDP-003", name: "Philippines/Duterte Red-Tagging Militants", country: "Asie du Sud-Est", sector: "66 Défenseurs Assassinés 2020-2022, Red-Tagging Militants Anti-Mines, NTF-ELCAC Terrorisme, Chinatown Nickel & Kalikasan People Network", defender_killing_impunity_severity_score: 86.0, criminalization_slapp_lawsuit_scale_score: 90.0, corporate_state_collusion_resource_conflict_score: 84.0, indigenous_land_defender_protection_deficit_score: 82.0, composite_score: 86.05, risk_level: "critique", primary_pattern: "criminalisation_slapp_poursuites", key_signals: ["Assassinats de défenseurs critiques de Philippines/Duterte Red-Tagging Militants — meurtres ciblés de militants environnementaux et autochtones dans une totale impunité, violant le droit à la vie (DUDH Art.3) et le Protocole de Mindanao", "Criminalisation massive des défenseurs — poursuites judiciaires abusives (SLAPP) utilisées comme arme d'intimidation pour réduire au silence les militants environnementaux et protéger les intérêts industriels extractifs", "Collusion corpo-étatique — les gouvernements utilisent les forces de sécurité privées et publiques pour protéger les intérêts extractifs au détriment des communautés défendant leur territoire et leurs ressources"], estimated_environmental_defenders_persecution_index: 8.61, last_updated: "2026-06-21" },
    { id: "EDP-004", name: "Colombie/Accord Paix Défenseurs Non Protégés", country: "Amérique du Sud", sector: "281 Défenseurs Assassinés 2023 Record INDEPAZ, Post-Accord Paix 2016, FARC Dissidents Tuent Défenseurs, Coca Territoires & 33% Autochtones", defender_killing_impunity_severity_score: 85.0, criminalization_slapp_lawsuit_scale_score: 75.0, corporate_state_collusion_resource_conflict_score: 82.0, indigenous_land_defender_protection_deficit_score: 88.0, composite_score: 82.85, risk_level: "critique", primary_pattern: "deficit_protection_defenseurs_autochtones", key_signals: ["Assassinats de défenseurs critiques de Colombie/Accord Paix Défenseurs Non Protégés — meurtres ciblés de militants environnementaux et autochtones dans une totale impunité, violant le droit à la vie (DUDH Art.3) et le Protocole de Mindanao", "Collusion corpo-étatique — les gouvernements utilisent les forces de sécurité privées et publiques pour protéger les intérêts extractifs au détriment des communautés défendant leur territoire et leurs ressources", "Impunité institutionnalisée — l'absence de mécanismes de protection des défenseurs de l'environnement permet la répétition des assassinats et décourage les nouvelles générations de militants"], estimated_environmental_defenders_persecution_index: 8.29, last_updated: "2026-06-21" },
    { id: "EDP-005", name: "Mexique/Cartels Miniers Défenseurs Yaqui", country: "Amérique du Nord", sector: "54 Défenseurs Tués 2022, Cartels Contrôlent Ressources Minières, Peuple Yaqui Eau Sonora, AMLO Retour Militarisation & SLAPP Empresas Extractivas", defender_killing_impunity_severity_score: 48.0, criminalization_slapp_lawsuit_scale_score: 55.0, corporate_state_collusion_resource_conflict_score: 58.0, indigenous_land_defender_protection_deficit_score: 52.0, composite_score: 52.65, risk_level: "élevé", primary_pattern: "collusion_corporate_etatique_ressources", key_signals: ["Violence contre défenseurs de Mexique/Cartels Miniers Défenseurs Yaqui — harcèlement, menaces et violences physiques contre les militants environnementaux sans protection légale effective ni poursuites des auteurs", "Impunité institutionnalisée — l'absence de mécanismes de protection des défenseurs de l'environnement permet la répétition des assassinats et décourage les nouvelles générations de militants"], estimated_environmental_defenders_persecution_index: 5.27, last_updated: "2026-06-21" },
    { id: "EDP-006", name: "Indonésie/Papouasie Forêts Palmier à Huile", country: "Asie du Sud-Est", sector: "Déforestation Papouasie 1.5M Ha, Militants Adat Criminalisés, TNI Militaires Sécurité Plantations, 43 Défenseurs Arrêtés 2022 & Expansion B30 Biofuel", defender_killing_impunity_severity_score: 42.0, criminalization_slapp_lawsuit_scale_score: 50.0, corporate_state_collusion_resource_conflict_score: 55.0, indigenous_land_defender_protection_deficit_score: 48.0, composite_score: 48.35, risk_level: "élevé", primary_pattern: "collusion_corporate_etatique_ressources", key_signals: ["Violence contre défenseurs de Indonésie/Papouasie Forêts Palmier à Huile — harcèlement, menaces et violences physiques contre les militants environnementaux sans protection légale effective ni poursuites des auteurs", "Impunité institutionnalisée — l'absence de mécanismes de protection des défenseurs de l'environnement permet la répétition des assassinats et décourage les nouvelles générations de militants"], estimated_environmental_defenders_persecution_index: 4.84, last_updated: "2026-06-21" },
    { id: "EDP-007", name: "UE/Directive SLAPP Anti-Poursuites Bâillon", country: "Europe", sector: "Directive Anti-SLAPP 2024 UE, SLAPP Tracker 570 Cas Documentés, Journalistes & ONGs Protégés, Coalition Against SLAPPs & RSF Monitoring", defender_killing_impunity_severity_score: 12.0, criminalization_slapp_lawsuit_scale_score: 30.0, corporate_state_collusion_resource_conflict_score: 15.0, indigenous_land_defender_protection_deficit_score: 28.0, composite_score: 20.35, risk_level: "modéré", primary_pattern: "criminalisation_slapp_poursuites", key_signals: ["Protection relative des défenseurs de UE/Directive SLAPP Anti-Poursuites Bâillon — cadres légaux partiels pour protéger les militants environnementaux et fonciers"], estimated_environmental_defenders_persecution_index: 2.04, last_updated: "2026-06-21" },
    { id: "EDP-008", name: "Costa Rica/Modèle Protection Défenseurs Forêts", country: "Amérique Centrale", sector: "Paiements Services Environnementaux, Zéro Déforestation Nette, Défenseurs Protégés Loi SINAC, Forêts 52% Territoire & Récompense Champions Terre 2021", defender_killing_impunity_severity_score: 5.0, criminalization_slapp_lawsuit_scale_score: 4.0, corporate_state_collusion_resource_conflict_score: 6.0, indigenous_land_defender_protection_deficit_score: 8.0, composite_score: 5.65, risk_level: "faible", primary_pattern: "assassinat_defenseur_impunite", key_signals: ["Protection relative des défenseurs de Costa Rica/Modèle Protection Défenseurs Forêts — cadres légaux partiels pour protéger les militants environnementaux et fonciers"], estimated_environmental_defenders_persecution_index: 0.57, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { assassinat_defenseur_impunite: 3, criminalisation_slapp_poursuites: 2, collusion_corporate_etatique_ressources: 2, deficit_protection_defenseurs_autochtones: 1 },
    top_risk_entities: ["Honduras/177 Défenseurs Assassinés 2010-2022", "Brésil/Amazonie 20+ Défenseurs/An Bolsonaro", "Philippines/Duterte Red-Tagging Militants", "Colombie/Accord Paix Défenseurs Non Protégés"],
    critical_alerts: ["Honduras: assassinat_defenseur_impunite", "Brésil/Amazonie: assassinat_defenseur_impunite", "Philippines: criminalisation_slapp_poursuites", "Colombie: deficit_protection_defenseurs_autochtones"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "environmental_defenders_persecution",
    confidence_score: 0.90,
    data_sources: ["global_witness_defenders_report_2023", "front_line_defenders_annual_report_2023", "amnesty_international_land_defenders", "global_environmental_defenders_monitor"],
    entities,
    avg_estimated_environmental_defenders_persecution_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
