import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[caste-discrimination-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Caste Discrimination Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/caste-discrimination-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Caste Discrimination Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Caste Discrimination Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CD-001", name: "Inde/Dalits — 50 000 Atrocités/An Bihar/UP, Intouchabilité Persistante & Viol Outil Oppression", country: "Asie du Sud", sector: "50 000 Atrocités Dalits/An Bihar/UP, Scavenging Manuel 58 000 Encore Actifs, Viol Utilisé Punition Intercaste & Loi Atrocités 1989 Non-Appliquée", composite_score: 91.6, untouchability_practice_rate_score: 95.0, occupational_segregation_score: 92.0, caste_violence_impunity_score: 90.0, intermarriage_prohibition_score: 88.0, risk_level: "critique", primary_pattern: "pratiques_intouchabilite", key_signals: ["Pratiques d'intouchabilité persistantes en Inde/Dalits — 50 000 atrocités documentées annuellement dans les États du Bihar et UP, avec viol utilisé comme outil de punition des Dalits qui défient la hiérarchie de caste", "Discrimination intersectionnelle systémique — la discrimination de caste en Inde combine violence physique, ségrégation spatiale et économique, violant simultanément le droit à l'égalité (Article 17 Constitution), à la dignité et à l'intégrité physique", "Activer le Rapporteur Spécial ONU sur les formes contemporaines de racisme pour audit spécifique sur la discrimination de caste et exiger l'application effective de la Loi de Prévention des Atrocités de 1989"], estimated_caste_discrimination_index: 9.16, last_updated: "2026-06-20" },
    { id: "CD-002", name: "Népal/Dalit — Discrimination Caste 40% Population, Mariages Intercaste Violence & Temple Accès Refusé", country: "Asie du Sud", sector: "Mariages Intercaste Violence 2020-24 Documentée NHRC, Intouchabilité Rurale Dalits 40% Population, Temple/Puits Accès Refusé & Loi Criminalisation 2011 Non-Appliquée", composite_score: 87.15, untouchability_practice_rate_score: 88.0, occupational_segregation_score: 85.0, caste_violence_impunity_score: 90.0, intermarriage_prohibition_score: 85.0, risk_level: "critique", primary_pattern: "pratiques_intouchabilite", key_signals: ["Pratiques d'intouchabilité persistantes au Népal/Dalit — 40% de la population Dalit subissant accès refusé aux temples, puits et lieux publics malgré l'interdiction constitutionnelle de 2007 et la loi de criminalisation de 2011", "Discrimination intersectionnelle systémique — la discrimination de caste au Népal viole l'Article 24 de la Constitution népalaise et les obligations du Comité CERD, avec des violences documentées contre les couples intercaste", "Activer le Comité ONU pour l'Élimination de la Discrimination Raciale (CERD) pour examiner la discrimination de caste au Népal et financer l'application effective des lois anti-discrimination"], estimated_caste_discrimination_index: 8.71, last_updated: "2026-06-20" },
    { id: "CD-003", name: "Yémen/Akhdam — Caste La Plus Basse, Ségrégation Sectorielle & Marginalisation Millénaire", country: "MENA", sector: "Akhdam 'Serviteurs' Caste Inférieure Yemen, Ségrégation Spatiale Bidonvilles, Métiers Dégradants Assignés Générations & Mariage Intercaste Tabou Absolu", composite_score: 83.65, untouchability_practice_rate_score: 85.0, occupational_segregation_score: 82.0, caste_violence_impunity_score: 85.0, intermarriage_prohibition_score: 82.0, risk_level: "critique", primary_pattern: "segregation_professionnelle_caste", key_signals: ["Ségrégation professionnelle de caste au Yémen/Akhdam — communauté Akhdam ('serviteurs') assignée aux métiers les plus dégradants depuis des millénaires, confinée dans des bidonvilles et exclue de l'ascension sociale par des barrières de caste implicites", "Discrimination intersectionnelle — la hiérarchie de caste yéménite combine ségrégation raciale (origine africaine supposée des Akhdam) et discrimination de classe, violant les principes d'égalité de la Charte Arabe des Droits de l'Homme", "Activer le Rapporteur Spécial ONU sur les formes contemporaines de racisme pour documenter la situation des Akhdam et exiger des réformes de lutte contre la discrimination de caste dans le cadre du processus de paix yéménite"], estimated_caste_discrimination_index: 8.37, last_updated: "2026-06-20" },
    { id: "CD-004", name: "Nigéria/Osu — Système Osu Igbo, Intouchabilité Persistante & Mariages Intercaste Tabou", country: "Afrique de l'Ouest", sector: "Osu Igbo Descendants Esclaves Déités, Mariage Libre Non-Osu Tabou Communautaire, Cimetières/Églises Séparés Zones & Discrimination Éducation/Emploi Formelle", composite_score: 81.85, untouchability_practice_rate_score: 82.0, occupational_segregation_score: 80.0, caste_violence_impunity_score: 85.0, intermarriage_prohibition_score: 80.0, risk_level: "critique", primary_pattern: "pratiques_intouchabilite", key_signals: ["Pratiques d'intouchabilité persistantes au Nigéria/Osu — système Osu chez les Igbo maintenant une caste d'intouchables descendants d'esclaves des divinités, exclus des mariages avec les non-Osu et des espaces communautaires", "Discrimination intersectionnelle héréditaire — le système Osu constitue une forme de discrimination héréditaire basée sur le statut ancestral, violant les principes d'égalité de la Constitution nigériane et de la Charte Africaine des Droits de l'Homme", "Activer la Commission Africaine des Droits de l'Homme pour examiner les pratiques de caste Osu et financer des programmes communautaires de sensibilisation contre la discrimination héréditaire au Nigéria"], estimated_caste_discrimination_index: 8.18, last_updated: "2026-06-20" },
    { id: "CD-005", name: "Japon/Burakumin — Discrimination Emploi/Mariage Persistante & Dossiers Cadastraux Caste", country: "Asie du Nord-Est", sector: "Burakumin 3M Personnes Anciens Parias, Dossiers Cadastraux Caste Encore Accessibles, Discrimination Emploi/Mariage Enquêtes & Groupes Suprémacistes Dōwa Incitation", composite_score: 53.1, untouchability_practice_rate_score: 52.0, occupational_segregation_score: 55.0, caste_violence_impunity_score: 55.0, intermarriage_prohibition_score: 50.0, risk_level: "élevé", primary_pattern: "segregation_professionnelle_caste", key_signals: ["Ségrégation professionnelle de caste persistante au Japon/Burakumin — 3 millions de descendants des anciens parias eta/hinin subissant discrimination à l'emploi et au mariage documentée par des enquêtes, malgré l'absence de loi anti-discrimination spécifique", "Lacune juridique — le Japon ne dispose pas de loi interdisant explicitement la discrimination basée sur le statut de Burakumin, permettant la persistance de pratiques discriminatoires dans l'emploi, le mariage et l'accès au logement", "Adopter une loi spécifique interdisant la discrimination Burakumin au Japon et criminaliser l'utilisation des anciens registres cadastraux pour identifier les descendants des quartiers historiques"], estimated_caste_discrimination_index: 5.31, last_updated: "2026-06-20" },
    { id: "CD-006", name: "Pakistan/Dalits Chrétiens — Scavenging Forcé, Conversions Forcées & Discrimination Légale", country: "Asie du Sud", sector: "Dalits Chrétiens Pakistan 2M+ Balayeurs Forcés, Lois Blasphème Instruments Caste, Conversions Forcées Jeunes Femmes & Mariage Forcé Discrimination Légale", composite_score: 52.4, untouchability_practice_rate_score: 55.0, occupational_segregation_score: 52.0, caste_violence_impunity_score: 50.0, intermarriage_prohibition_score: 52.0, risk_level: "élevé", primary_pattern: "pratiques_intouchabilite", key_signals: ["Pratiques d'intouchabilité persistantes au Pakistan/Dalits Chrétiens — 2 millions de Dalits chrétiens assignés au travail de nettoyage et balayage, utilisées comme instrument de discrimination de caste renforcée par les lois sur le blasphème", "Discrimination intersectionnelle — la discrimination de caste au Pakistan se superpose à la discrimination religieuse, créant une double vulnérabilité pour les Dalits chrétiens et hindous soumis à des conversions forcées", "Activer la Rapporteure Spéciale ONU sur la liberté religieuse et le Comité CERD pour examiner la discrimination intersectionnelle de caste et de religion visant les Dalits non-musulmans au Pakistan"], estimated_caste_discrimination_index: 5.24, last_updated: "2026-06-20" },
    { id: "CD-007", name: "Corée/Baekjeong — Caste Historique Abolie 1894 & Stigmate Social Résiduel", country: "Asie du Nord-Est", sector: "Baekjeong Anciens Parias Coréens Abolition 1894 Gabo Reform, Stigmate Social Résiduel Noms/Quartiers, Discrimination Mariage Subtile & Intégration Substantielle Réalisée", composite_score: 28.15, untouchability_practice_rate_score: 28.0, occupational_segregation_score: 30.0, caste_violence_impunity_score: 25.0, intermarriage_prohibition_score: 30.0, risk_level: "modéré", primary_pattern: "interdiction_mariage_intercaste", key_signals: ["Stigmate résiduel de caste en Corée/Baekjeong — discrimination de caste officiellement abolie depuis la réforme Gabo de 1894 mais stigmate social résiduel persistant dans certains mariages et communautés rurales pour les descendants Baekjeong", "Progrès significatifs mais vigilance nécessaire — la Corée a réalisé une intégration sociale substantielle des Baekjeong en un siècle, mais des études documentent encore des préjugés résiduels dans les décisions matrimoniales", "Maintenir les programmes éducatifs coréens sur l'histoire des castes et surveiller les cas résiduels de discrimination pour prévenir toute résurgence dans un contexte de montée du nationalisme identitaire"], estimated_caste_discrimination_index: 2.81, last_updated: "2026-06-20" },
    { id: "CD-008", name: "IDSN/OHCHR — Lutte Discrimination Caste & Principes Directeurs ONU", country: "Global", sector: "IDSN International Dalit Solidarity Network, OHCHR Rapport Discrimination Fondée Ancêtres 2009, Principes Directeurs ONU Caste & CERD Recommandation Générale 29", composite_score: 4.45, untouchability_practice_rate_score: 5.0, occupational_segregation_score: 4.0, caste_violence_impunity_score: 3.0, intermarriage_prohibition_score: 6.0, risk_level: "faible", primary_pattern: "violence_caste_impunite", key_signals: ["IDSN/OHCHR incarnent la protection exemplaire contre la discrimination de caste — Principes Directeurs ONU sur la discrimination fondée sur l'ascendance et Recommandation Générale 29 du CERD créant un cadre de responsabilité", "Recommandation Générale 29 du CERD — interprétation explicite du CERD incluant la discrimination fondée sur l'ascendance (caste) dans le champ de la Convention pour l'Élimination de la Discrimination Raciale", "Partager les méthodologies IDSN de documentation des violences de caste et renforcer la Recommandation Générale 29 du CERD pour contraindre les États à agir contre la discrimination d'ascendance"], estimated_caste_discrimination_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { pratiques_intouchabilite: 4, segregation_professionnelle_caste: 2, violence_caste_impunite: 1, interdiction_mariage_intercaste: 1 },
    top_risk_entities: ["Inde/Dalits — 50 000 Atrocités/An Bihar/UP, Intouchabilité Persistante & Viol Outil Oppression", "Népal/Dalit — Discrimination Caste 40% Population, Mariages Intercaste Violence & Temple Accès Refusé", "Yémen/Akhdam — Caste La Plus Basse, Ségrégation Sectorielle & Marginalisation Millénaire"],
    critical_alerts: ["Inde/Dalits: pratiques intouchabilité", "Népal/Dalit: pratiques intouchabilité", "Yémen/Akhdam: ségrégation professionnelle caste", "Nigéria/Osu: pratiques intouchabilité"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "caste_discrimination",
    confidence_score: 0.81,
    data_sources: ["idsn_caste_based_discrimination_database", "human_rights_watch_caste_reports", "ilo_caste_discrimination_workplace_reports"],
    entities,
    avg_estimated_caste_discrimination_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
