import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[press-freedom-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Press Freedom Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/press-freedom-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Press Freedom Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Press Freedom Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "PF-001", name: "Chine — 100+ Journalistes Emprisonnés, Grand Firewall & Presse État CCTV/Xinhua", country: "Asie du Nord-Est", sector: "Chine 100+ Journalistes Emprisonnés CPJ/RSF 2024, Grand Firewall Internet, Presse Étatique CCTV/Xinhua/People Daily, Correspondants Étrangers Expulsés & RSF Rang 172/180", composite_score: 91.25, journalist_imprisonment_score: 95.0, media_censorship_ownership_score: 95.0, physical_safety_threats_score: 88.0, legal_harassment_lawfare_score: 85.0, risk_level: "critique", primary_pattern: "emprisonnement_journalistes", key_signals: ["Violation de la liberté de la presse documentée — Chine avec score composite 91.25/100 révélant des restrictions systémiques violant l'Article 19 de la DUDH et du PIDCP sur la liberté d'expression et d'information", "Emprisonnement de journalistes (95.0/100) — plus de 100 journalistes emprisonnés en Chine constituent le chiffre absolu le plus élevé au monde, révélant une répression systématique de toute information indépendante", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête urgente et exiger la libération immédiate de tous les journalistes emprisonnés pour leur travail journalistique"], estimated_press_freedom_index: 9.13, last_updated: "2026-06-20" },
    { entity_id: "PF-002", name: "Russie — 36+ Journalistes Emprisonnés, Novaya Gazeta Suspendu & Loi Fausses Infos", country: "Europe de l'Est", sector: "Russie Post-2022 36+ Journalistes Emprisonnés CPJ, Novaya Gazeta Suspendu Muratov Nobel, Étiqueté Agent Étranger, Loi 15 Ans Fausses Infos Armée & Médias Indépendants Exil", composite_score: 88.25, journalist_imprisonment_score: 88.0, media_censorship_ownership_score: 92.0, physical_safety_threats_score: 85.0, legal_harassment_lawfare_score: 88.0, risk_level: "critique", primary_pattern: "censure_concentration_medias", key_signals: ["Violation de la liberté de la presse documentée — Russie avec score composite 88.25/100 révélant des restrictions systémiques violant l'Article 19 de la DUDH et du PIDCP sur la liberté d'expression et d'information", "Emprisonnement de journalistes (88.0/100) — la suspension de Novaya Gazeta, l'étiquetage systématique des médias indépendants comme 'agents étrangers' et l'emprisonnement de 36+ journalistes constituent une liquidation de la presse libre", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête urgente et exiger la libération immédiate de tous les journalistes emprisonnés pour leur travail journalistique"], estimated_press_freedom_index: 8.83, last_updated: "2026-06-20" },
    { entity_id: "PF-003", name: "Iran — 40+ Journalistes Détenus, VPN Bloqués & Instagram/WhatsApp Interdits", country: "MENA", sector: "Iran 40+ Journalistes Emprisonnés 2023 CPJ, Instagram/WhatsApp/Twitter Bloqués, Correspondants BBC/Radio Farda Arrêtés Familles & RSF Journalistes Tués Manifestations 2022", composite_score: 86.55, journalist_imprisonment_score: 88.0, media_censorship_ownership_score: 85.0, physical_safety_threats_score: 90.0, legal_harassment_lawfare_score: 82.0, risk_level: "critique", primary_pattern: "menaces_securite_physique", key_signals: ["Violation de la liberté de la presse documentée — Iran avec score composite 86.55/100 révélant des restrictions systémiques violant l'Article 19 de la DUDH et du PIDCP sur la liberté d'expression et d'information", "Emprisonnement de journalistes (88.0/100) — les 40+ journalistes détenus, le blocage des réseaux sociaux et les menaces contre les familles de journalistes diaspora constituent une répression totale de l'information indépendante en Iran", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête urgente et exiger la libération immédiate de tous les journalistes emprisonnés pour leur travail journalistique"], estimated_press_freedom_index: 8.66, last_updated: "2026-06-20" },
    { entity_id: "PF-004", name: "Myanmar — 60+ Journalistes Arrêtés Post-Coup, Médias Interdits & Licences Révoquées", country: "Asie du Sud-Est", sector: "Myanmar 60+ Journalistes Arrêtés Tatmadaw 2021, Licences Médias Révoquées, CPJ Birmanie Geôlier Presse, Photojournalistes Tués & Journalistes Condamnés 20 Ans", composite_score: 86.25, journalist_imprisonment_score: 90.0, media_censorship_ownership_score: 85.0, physical_safety_threats_score: 88.0, legal_harassment_lawfare_score: 80.0, risk_level: "critique", primary_pattern: "emprisonnement_journalistes", key_signals: ["Violation de la liberté de la presse documentée — Myanmar avec score composite 86.25/100 révélant des restrictions systémiques violant l'Article 19 de la DUDH et du PIDCP sur la liberté d'expression et d'information", "Emprisonnement de journalistes (90.0/100) — les 60+ journalistes arrêtés post-coup 2021, les condamnations à 20 ans et les licences médias révoquées constituent une destruction systématique de la presse libre birmane par le Tatmadaw", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête urgente et exiger la libération immédiate de tous les journalistes emprisonnés pour leur travail journalistique"], estimated_press_freedom_index: 8.63, last_updated: "2026-06-20" },
    { entity_id: "PF-005", name: "Mexique — Journaliste Meurtres Capital Mondial, Cartels & FEADLE Impunité", country: "Amérique Latine", sector: "Mexique 10-15 Journalistes Tués/An RSF, Cartels Ciblage Journalistes Locaux, FEADLE Procureur Spécial Inefficace & CPJ 2024 Mexique 3ème Plus Dangereux Monde", composite_score: 54.25, journalist_imprisonment_score: 52.0, media_censorship_ownership_score: 48.0, physical_safety_threats_score: 65.0, legal_harassment_lawfare_score: 52.0, risk_level: "élevé", primary_pattern: "menaces_securite_physique", key_signals: ["Violation de la liberté de la presse documentée — Mexique avec score composite 54.25/100 révélant des menaces physiques graves pour les journalistes locaux ciblés par les cartels avec impunité quasi-totale de la FEADLE", "Menaces sécurité physique (65.0/100) — le Mexique est le pays le plus meurtrier pour les journalistes en Amérique latine avec 10-15 meurtres par an, majoritairement des journalistes locaux couvrant le crime organisé", "Réformer le mécanisme de protection des journalistes FEADLE et créer un parquet spécialisé avec compétence exclusive sur les crimes contre la presse incluant des ressources d'enquête pour démanteler les cartels visant les journalistes"], estimated_press_freedom_index: 5.43, last_updated: "2026-06-20" },
    { entity_id: "PF-006", name: "Inde — 40+ Journalistes Détenus, UAPA Sédition & Concentration Médias Ambani/Adani", country: "Asie du Sud", sector: "Inde UAPA Anti-Terrorisme Journalistes Cachemire, Sédition Loi Coloniale Abolie 2023, Concentration Médias Reliance/Adani 80%+ Audience & BBC Documentary Modi Interdite", composite_score: 52.40, journalist_imprisonment_score: 48.0, media_censorship_ownership_score: 58.0, physical_safety_threats_score: 50.0, legal_harassment_lawfare_score: 55.0, risk_level: "élevé", primary_pattern: "censure_concentration_medias", key_signals: ["Violation de la liberté de la presse documentée — Inde avec score composite 52.40/100 révélant une concentration médiatique croissante et un harcèlement juridique des journalistes via l'UAPA et la sédition violant l'Article 19 PIDCP", "Emprisonnement de journalistes (48.0/100) — l'utilisation de l'UAPA (loi antiterroriste) contre des journalistes au Cachemire et l'interdiction du documentaire BBC sur Modi illustrent l'instrumentalisation du droit contre la presse", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête urgente et exiger la libération immédiate de tous les journalistes emprisonnés pour leur travail journalistique"], estimated_press_freedom_index: 5.24, last_updated: "2026-06-20" },
    { entity_id: "PF-007", name: "Turquie — 150+ Journalistes Détenus 2016-24, Lois Anti-Presse & Anadolu Agence État", country: "MENA/Europe", sector: "Turquie Post-Coup 150+ Journalistes Détenus 2016-24, 90% Médias Contrôlés Pro-Erdogan, Loi 7418 Désinformation & RSF Rang 158/180 Malgré Libérations Récentes 2024", composite_score: 28.65, journalist_imprisonment_score: 28.0, media_censorship_ownership_score: 32.0, physical_safety_threats_score: 25.0, legal_harassment_lawfare_score: 30.0, risk_level: "modéré", primary_pattern: "censure_concentration_medias", key_signals: ["Restrictions modérées de la liberté de presse en Turquie — malgré des libérations en 2024, la concentration à 90% des médias sous contrôle pro-Erdogan et la loi 7418 sur la désinformation maintiennent des obstacles structurels à la presse libre", "Concentration des médias (32.0/100) — le contrôle de 90% de l'audience médiatique par des groupes proches du gouvernement crée un environnement d'information déséquilibré violant le pluralisme médiatique garanti par l'AMPLE et la jurisprudence CEDH", "Poursuivre les procédures d'infringement CE/UE contre la Turquie pour les violations de la liberté de presse et conditionner l'adhésion UE au respect effectif des standards CEDH sur la liberté d'expression (Article 10)"], estimated_press_freedom_index: 2.87, last_updated: "2026-06-20" },
    { entity_id: "PF-008", name: "RSF/CPJ-ONU — Classement Liberté Presse, Article 19 & Déclaration Windhoek 1991", country: "Global", sector: "RSF Classement Liberté Presse 180 Pays, CPJ Journalistes Emprisonnés Base Données, Rapporteur Spécial ONU Art 19 PIDCP & Déclaration Windhoek 1991 Presse Indépendante Afrique", composite_score: 4.45, journalist_imprisonment_score: 5.0, media_censorship_ownership_score: 4.0, physical_safety_threats_score: 3.0, legal_harassment_lawfare_score: 6.0, risk_level: "faible", primary_pattern: "harcelement_juridique_lawfare", key_signals: ["RSF/CPJ-ONU incarne le cadre exemplaire de protection de la liberté de la presse — classement RSF annuel et base de données CPJ créant une architecture de surveillance mondiale de l'état de la liberté de la presse dans 180 pays", "Article 19 PIDCP — garantit la liberté de rechercher, de recevoir et de répandre des informations, imposant aux États l'obligation de protéger les journalistes et les médias indépendants de toute ingérence étatique", "Universaliser la protection des journalistes via la Résolution CS-ONU 1738 et renforcer le Plan d'action ONU sur la sécurité des journalistes avec mécanismes de responsabilité pour les États laissant impunis les crimes contre la presse"], estimated_press_freedom_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { emprisonnement_journalistes: 2, censure_concentration_medias: 3, menaces_securite_physique: 2, harcelement_juridique_lawfare: 1 },
    top_risk_entities: ["Chine — 100+ Journalistes Emprisonnés, Grand Firewall & Presse État CCTV/Xinhua", "Russie — 36+ Journalistes Emprisonnés, Novaya Gazeta Suspendu & Loi Fausses Infos", "Iran — 40+ Journalistes Détenus, VPN Bloqués & Instagram/WhatsApp Interdits"],
    critical_alerts: ["Chine: emprisonnement journalistes", "Russie: censure concentration médias", "Iran: menaces sécurité physique", "Myanmar: emprisonnement journalistes"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "press_freedom",
    confidence_score: 0.87,
    data_sources: ["rsf_world_press_freedom_index_annual", "cpj_imprisoned_journalists_database", "un_special_rapporteur_freedom_expression_reports"],
    entities,
    avg_estimated_press_freedom_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
