import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[migrant-worker-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Migrant Worker Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/migrant-worker-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Migrant Worker Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Migrant Worker Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "MW-001", name: "Qatar/FIFA — Kafala Système, 6 500+ Morts Travailleurs Migrants & Stades Coupe 2022", country: "MENA", sector: "Qatar 6 500+ Morts Travailleurs Migrants Stades FIFA 2010-22 Estimation Guardian, Kafala Système Captivité, Passeports Confisqués & Réformes 2021 Insuffisantes ILO", composite_score: 90.95, wage_theft_exploitation_score: 92.0, recruitment_fee_debt_score: 88.0, kafala_system_dependency_score: 95.0, labor_rights_access_failure_score: 88.0, risk_level: "critique", primary_pattern: "dependance_systeme_kafala", key_signals: ["Exploitation des travailleurs migrants documentée — Qatar/FIFA avec score composite 90.95/100 révélant des violations des Conventions OIT C97/C143 sur les travailleurs migrants et du Protocole de Palerme", "Système Kafala/Sponsorship (95.0/100) — le système de parrainage crée une dépendance totale de l'employeur empêchant les travailleurs migrants de changer d'emploi ou de quitter le pays", "Activer le Rapporteur Spécial ONU sur les droits des migrants pour enquête sur le système Kafala et exiger la ratification par les États du Golfe des Conventions OIT C87/C98 sur la liberté syndicale"], estimated_migrant_worker_rights_index: 9.1, last_updated: "2026-06-20" },
    { entity_id: "MW-002", name: "Golfe Arabe/Kafala — EAU/KSA/Koweït 25M Travailleurs Captifs Système Parrainage", country: "MENA", sector: "25M Travailleurs Migrants Golfe Système Kafala EAU/KSA/Koweït/Bahreïn, Changement Emploi Interdit, Travailleuses Domestiques Exclues Code Travail & Réformes Cosmétiques", composite_score: 87.65, wage_theft_exploitation_score: 88.0, recruitment_fee_debt_score: 85.0, kafala_system_dependency_score: 92.0, labor_rights_access_failure_score: 85.0, risk_level: "critique", primary_pattern: "dependance_systeme_kafala", key_signals: ["Exploitation des travailleurs migrants documentée — Golfe Arabe/Kafala avec score composite 87.65/100 révélant des violations des Conventions OIT C97/C143 sur les travailleurs migrants et du Protocole de Palerme", "Système Kafala/Sponsorship (92.0/100) — le système de parrainage crée une dépendance totale de l'employeur empêchant les travailleurs migrants de changer d'emploi ou de quitter le pays", "Activer le Rapporteur Spécial ONU sur les droits des migrants pour enquête sur le système Kafala et exiger la ratification par les États du Golfe des Conventions OIT C87/C98 sur la liberté syndicale"], estimated_migrant_worker_rights_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "MW-003", name: "Malaisie/Top Glove — Travailleurs Migrants Captifs, Palm Oil & Gants Pandémie COVID", country: "Asie du Sud-Est", sector: "Top Glove Malaisie Gants Latex 10 000 Travailleurs Migrants Logements Surpeuplés, Frais Recrutement 3 000$, Palm Oil Travailleurs Népalais/Bangladeshis & Sanctions USA 2020", composite_score: 85.65, wage_theft_exploitation_score: 85.0, recruitment_fee_debt_score: 90.0, kafala_system_dependency_score: 85.0, labor_rights_access_failure_score: 82.0, risk_level: "critique", primary_pattern: "dette_frais_recrutement", key_signals: ["Exploitation des travailleurs migrants documentée — Malaisie/Top Glove avec score composite 85.65/100 révélant des violations des Conventions OIT C97/C143 sur les travailleurs migrants et du Protocole de Palerme", "Système Kafala/Sponsorship (85.0/100) — le système de sponsorship malaisien crée une dépendance totale de l'employeur empêchant les travailleurs migrants de changer d'emploi ou de quitter le pays", "Activer le Rapporteur Spécial ONU sur les droits des migrants pour enquête sur le système Kafala et exiger la ratification par les États du Golfe des Conventions OIT C87/C98 sur la liberté syndicale"], estimated_migrant_worker_rights_index: 8.57, last_updated: "2026-06-20" },
    { entity_id: "MW-004", name: "USA/H-2A H-2B — Visa Sponsorship Captivité, Abus Agricoles Documentés & Frais Recrutement", country: "Amérique du Nord", sector: "USA H-2A H-2B Visa Workers 300 000/An, Captivité Sponsor Changement Emploi Difficile, Abus Agricoles Saisonniers EWA & Frais Recrutement Mexique/Guatemala", composite_score: 82.85, wage_theft_exploitation_score: 82.0, recruitment_fee_debt_score: 85.0, kafala_system_dependency_score: 80.0, labor_rights_access_failure_score: 85.0, risk_level: "critique", primary_pattern: "dette_frais_recrutement", key_signals: ["Exploitation des travailleurs migrants documentée — USA/H-2A H-2B avec score composite 82.85/100 révélant des violations des Conventions OIT C97/C143 sur les travailleurs migrants et du Protocole de Palerme", "Système Kafala/Sponsorship (80.0/100) — le système de visa sponsorisé aux États-Unis crée une dépendance totale de l'employeur empêchant les travailleurs migrants de changer d'emploi sans perdre leur statut légal", "Activer le Rapporteur Spécial ONU sur les droits des migrants pour enquête sur le système Kafala et exiger la ratification par les États du Golfe des Conventions OIT C87/C98 sur la liberté syndicale"], estimated_migrant_worker_rights_index: 8.29, last_updated: "2026-06-20" },
    { entity_id: "MW-005", name: "Thaïlande/Pêche Maritime — Esclavage Bateaux Haute Mer, ILO C188 & GFW Rapport", country: "Asie du Sud-Est", sector: "Thaïlande Pêche Maritime Travailleurs Migrants Myanmar/Cambodge Esclavage Bateaux, Pêche Haute Mer Hors Portée Inspection, AP Enquête 2015 & ILO C188 Non-Ratifié", composite_score: 54.0, wage_theft_exploitation_score: 55.0, recruitment_fee_debt_score: 52.0, kafala_system_dependency_score: 58.0, labor_rights_access_failure_score: 50.0, risk_level: "élevé", primary_pattern: "dependance_systeme_kafala", key_signals: ["Exploitation des travailleurs migrants documentée — Thaïlande/Pêche avec score composite 54.0/100 révélant un esclavage maritime de travailleurs migrants en haute mer hors de portée des inspections du travail", "Système Kafala/Sponsorship (58.0/100) — le système de sponsorship des bateaux de pêche thaïlandais crée une captivité de facto des pêcheurs migrants sans accès à l'inspection du travail", "Ratifier la Convention OIT C188 sur les conditions de travail dans la pêche et mettre en place des mécanismes d'inspection maritime pour les bateaux de pêche haute mer incluant les travailleurs migrants"], estimated_migrant_worker_rights_index: 5.4, last_updated: "2026-06-20" },
    { entity_id: "MW-006", name: "Italie/Caporalato — Travailleurs Africains Agriculture, Exploitation & Loi 199/2016", country: "Europe de l'Ouest", sector: "Italie Caporalato Système Intermédiaires Exploitation Travailleurs Migrants Africains Agriculture, Muerte Agriculteurs Sans Eau/Soleil, Loi 199/2016 Anti-Caporalato & Application Lacunaire", composite_score: 52.35, wage_theft_exploitation_score: 52.0, recruitment_fee_debt_score: 48.0, kafala_system_dependency_score: 55.0, labor_rights_access_failure_score: 55.0, risk_level: "élevé", primary_pattern: "dependance_systeme_kafala", key_signals: ["Exploitation des travailleurs migrants documentée — Italie/Caporalato avec score composite 52.35/100 révélant un système d'intermédiaires exploiteurs condamnés par la loi 199/2016 mais persistant dans l'agriculture", "Système Kafala/Sponsorship (55.0/100) — le système Caporalato crée une dépendance des travailleurs migrants africains à des intermédiaires exploiteurs avec frais abusifs et conditions de vie précaires", "Appliquer effectivement la loi 199/2016 anti-Caporalato et financer les inspections du travail agricole en Italie méridionale avec traducteurs et protection des témoins pour les travailleurs migrants"], estimated_migrant_worker_rights_index: 5.24, last_updated: "2026-06-20" },
    { entity_id: "MW-007", name: "Allemagne/Saisonnier — COVID Tönnies Abattoir 2020, Logements Surpeuplés & Travailleurs Roumains", country: "Europe de l'Ouest", sector: "Allemagne Tönnies Abattoir COVID 1 500 Infectés Travailleurs Roumains 2020, Logements Surpeuplés, Travailleurs Saisonniers UE Contrats & AEntG Arbeitnehmer-Entsendegesetz Lacunes", composite_score: 29.6, wage_theft_exploitation_score: 30.0, recruitment_fee_debt_score: 28.0, kafala_system_dependency_score: 32.0, labor_rights_access_failure_score: 28.0, risk_level: "modéré", primary_pattern: "dependance_systeme_kafala", key_signals: ["Exploitation modérée des travailleurs saisonniers en Allemagne — scandale Tönnies 2020 révélant 1 500 travailleurs roumains infectés COVID dans des logements surpeuplés liés à des sous-contrats opaques", "Système Kafala/Sponsorship (32.0/100) — les sous-contrats de travail saisonnier en Allemagne créent une dépendance des travailleurs migrant UE (roumains, bulgares) à des intermédiaires sans protection adéquate", "Renforcer l'AEntG (Loi Détachement Travailleurs) et l'inspection du travail dans les abattoirs et l'agriculture allemands avec mesures spécifiques de protection des travailleurs saisonniers UE"], estimated_migrant_worker_rights_index: 2.96, last_updated: "2026-06-20" },
    { entity_id: "MW-008", name: "OIT/ITUC — Convention 189 Domestiques, C97 Travailleurs Migrants & MOU Bilatéraux Golfe", country: "Global", sector: "OIT Convention 189 Travailleurs Domestiques 2011, C97 Travailleurs Migrants, ITUC Rapports Syndicalisation Migrants & MOU Bilatéraux Philippines/Sri Lanka Golfe", composite_score: 4.45, wage_theft_exploitation_score: 5.0, recruitment_fee_debt_score: 4.0, kafala_system_dependency_score: 3.0, labor_rights_access_failure_score: 6.0, risk_level: "faible", primary_pattern: "exclusion_droits_travail", key_signals: ["OIT/ITUC incarne le cadre exemplaire des droits des travailleurs migrants — Convention 189 sur les travailleurs domestiques et C97 sur les travailleurs migrants créant des obligations de protection et d'égalité de traitement", "Convention OIT C97 (1949) — garantit l'égalité de traitement entre travailleurs migrants et nationaux pour les conditions de travail, les droits syndicaux et la sécurité sociale dans les pays d'emploi", "Universaliser la ratification de la Convention OIT C189 sur les travailleurs domestiques et exiger des États du Golfe l'abandon du système Kafala conformément aux recommandations du Programme Better Work de l'OIT"], estimated_migrant_worker_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { dependance_systeme_kafala: 5, dette_frais_recrutement: 2, exclusion_droits_travail: 1, vol_salaires_exploitation: 0 },
    top_risk_entities: ["Qatar/FIFA — Kafala Système, 6 500+ Morts Travailleurs Migrants & Stades Coupe 2022", "Golfe Arabe/Kafala — EAU/KSA/Koweït 25M Travailleurs Captifs Système Parrainage", "Malaisie/Top Glove — Travailleurs Migrants Captifs, Palm Oil & Gants Pandémie COVID"],
    critical_alerts: ["Qatar/FIFA: dépendance système kafala", "Golfe Arabe: dépendance système kafala", "Malaisie/Top Glove: dette frais recrutement", "USA/H-2A H-2B: dette frais recrutement"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "migrant_worker_rights",
    confidence_score: 0.82,
    data_sources: ["ilo_global_estimates_international_migrant_workers", "migrant_forum_asia_recruitment_fees_database", "business_human_rights_resource_centre_migrant_reports"],
    entities,
    avg_estimated_migrant_worker_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
