import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[digital-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Digital Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/digital-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Digital Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Digital Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "DR-001", name: "Chine/Grand Firewall — 1.4Md Censurés, Surveillance IA Totale & WeChat Monitoring", country: "Asie du Nord-Est", sector: "Grand Firewall Chine 1.4Md Personnes, 300 000+ Sites Bloqués, WeChat Surveillance Messages, Système Crédit Social & IA Reconnaissance Faciale 1Md Visages Base Données Sécurité", composite_score: 92.85, internet_censorship_shutdown_score: 95.0, surveillance_privacy_violation_score: 95.0, digital_expression_suppression_score: 92.0, algorithmic_discrimination_score: 88.0, risk_level: "critique", primary_pattern: "censure_coupure_internet", key_signals: ["Violation des droits numériques documentée — Chine/Grand Firewall avec score composite 92.85/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (95.0/100) — le blocage de 300 000+ sites et la surveillance totale par WeChat constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 9.29, last_updated: "2026-06-20" },
    { id: "DR-002", name: "Corée du Nord — Internet 0.1% Population, Kwangmyong Intranet & Peines Mort Contenu", country: "Asie du Nord-Est", sector: "RPDC 0.1% Population Internet Mondial, Kwangmyong Intranet Contrôlé État, Clé USB Contenu Étranger Peine Mort, Téléphones Inspectés & Complète Isolation Numérique Population", composite_score: 91.15, internet_censorship_shutdown_score: 95.0, surveillance_privacy_violation_score: 90.0, digital_expression_suppression_score: 95.0, algorithmic_discrimination_score: 82.0, risk_level: "critique", primary_pattern: "censure_coupure_internet", key_signals: ["Violation des droits numériques documentée — Corée du Nord avec score composite 91.15/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (95.0/100) — l'isolation numérique totale de 25 millions de Nord-Coréens et les peines de mort pour possession de contenu étranger constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 9.12, last_updated: "2026-06-20" },
    { id: "DR-003", name: "Iran — 50%+ Contenu Bloqué, Pegasus Activistes & Coupe Internet Manifestations 2022", country: "MENA", sector: "Iran 50%+ Internet Bloqué Instagram/WhatsApp, Pegasus Spyware Journalistes/Activistes, Coupure Internet Totale Manifestations Mahsa 2022 & Cyber Police FATA Arrestations Contenus", composite_score: 87.80, internet_censorship_shutdown_score: 88.0, surveillance_privacy_violation_score: 92.0, digital_expression_suppression_score: 88.0, algorithmic_discrimination_score: 82.0, risk_level: "critique", primary_pattern: "surveillance_violation_vie_privee", key_signals: ["Violation des droits numériques documentée — Iran avec score composite 87.8/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (88.0/100) — le blocage de 50%+ du contenu internet et les coupures totales pendant les manifestations Mahsa 2022 constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 8.78, last_updated: "2026-06-20" },
    { id: "DR-004", name: "Russie — RuNet Loi 2019, VPN Bloqués, Telegram Censure & Surveillance SORM-3", country: "Europe de l'Est", sector: "Russie RuNet Souverain Loi 2019, SORM-3 Surveillance Totale Communications, VPN Massifs Bloqués 2022, Telegram Banni Débloqué & 100+ Domaines Médias Bloqués Post-Guerre", composite_score: 86.00, internet_censorship_shutdown_score: 85.0, surveillance_privacy_violation_score: 90.0, digital_expression_suppression_score: 88.0, algorithmic_discrimination_score: 80.0, risk_level: "critique", primary_pattern: "surveillance_violation_vie_privee", key_signals: ["Violation des droits numériques documentée — Russie avec score composite 86.0/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (85.0/100) — la loi RuNet 2019 créant un Internet souverain isolable et le système SORM-3 de surveillance totale des communications constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 8.60, last_updated: "2026-06-20" },
    { id: "DR-005", name: "USA/Big Tech — NSA PRISM, Section 702 FISA & Facial Recognition Minorités Ciblées", country: "Amérique du Nord", sector: "USA NSA PRISM Surveillance 1Md+ Personnes Snowden 2013, Section 702 FISA Renouvellement 2024, Reconnaissance Faciale Faux Positifs Noirs 35×, TikTok Ban & Cloud Act Données", composite_score: 53.90, internet_censorship_shutdown_score: 50.0, surveillance_privacy_violation_score: 58.0, digital_expression_suppression_score: 48.0, algorithmic_discrimination_score: 62.0, risk_level: "élevé", primary_pattern: "discrimination_algorithmique", key_signals: ["Violation des droits numériques documentée — USA/Big Tech avec score composite 53.9/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (50.0/100) — la surveillance NSA PRISM de plus d'un milliard de personnes et la reconnaissance faciale avec 35× plus de faux positifs pour les personnes noires constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 5.39, last_updated: "2026-06-20" },
    { id: "DR-006", name: "Inde — Internet Shutdowns Record 84/An, Cachemire Coupure 552 Jours & Pegasus Opposants", country: "Asie du Sud", sector: "Inde 84 Coupures Internet 2023 Record Mondial SFC, Cachemire 552 Jours Coupure Totale 2019-21, Pegasus Spyware Journalistes/Opposants & IT Act Section 66A Inconstitutionnelle", composite_score: 54.15, internet_censorship_shutdown_score: 58.0, surveillance_privacy_violation_score: 52.0, digital_expression_suppression_score: 55.0, algorithmic_discrimination_score: 50.0, risk_level: "élevé", primary_pattern: "censure_coupure_internet", key_signals: ["Violation des droits numériques documentée — Inde avec score composite 54.15/100 révélant des restrictions systémiques violant l'Article 19 du PIDCP sur la liberté d'expression en ligne et la Résolution ONU A/HRC/32/L.20 sur la promotion des droits humains sur Internet", "Censure/Coupure Internet (58.0/100) — les 84 coupures Internet en 2023 et la coupure totale du Cachemire pendant 552 jours constituent des violations directes de l'Article 19 PIDCP et des standards ONU sur la liberté d'expression en ligne (Résolution CDH 2016)", "Activer le Rapporteur Spécial ONU sur la liberté d'expression pour enquête sur les coupures Internet et exiger l'application de la Résolution CDH 32/13 reconnaissant que les droits hors ligne doivent être protégés en ligne"], estimated_digital_rights_index: 5.42, last_updated: "2026-06-20" },
    { id: "DR-007", name: "UE/RGPD — Cambridge Analytica, DSA Lacunes & Algorithmes Plateformes Non-Régulés", country: "Europe", sector: "UE RGPD 2018 Progrès Mais Cambridge Analytica 87M Profils, Meta 1.2Md Amende RGPD 2023, DSA Digital Services Act Lacunes Application & Algorithmes Recommandation Non-Transparents", composite_score: 30.90, internet_censorship_shutdown_score: 28.0, surveillance_privacy_violation_score: 32.0, digital_expression_suppression_score: 30.0, algorithmic_discrimination_score: 35.0, risk_level: "modéré", primary_pattern: "discrimination_algorithmique", key_signals: ["Défis des droits numériques dans l'UE — malgré le RGPD 2018, les scandales Cambridge Analytica et les lacunes du DSA révèlent des insuffisances dans la régulation des algorithmes et la protection des données personnelles des citoyens européens", "Discrimination algorithmique (35.0/100) — les algorithmes de recommandation non-transparents des plateformes et les biais discriminatoires documentés créent des préjudices pour les utilisateurs malgré le cadre RGPD/DSA européen", "Renforcer l'application du DSA et du RGPD par des autorités de contrôle mieux dotées et adopter un règlement IA contraignant incluant des obligations d'auditabilité algorithmique conformément aux recommandations du Comité européen de la protection des données"], estimated_digital_rights_index: 3.09, last_updated: "2026-06-20" },
    { id: "DR-008", name: "CDH-ONU/EFF — Résolution 32/13 Droits Internet & Principes Nécessité-Proportionnalité", country: "Global", sector: "Résolution CDH-ONU 32/13 Droits Hors Ligne En Ligne, Rapporteur Spécial ONU Expression Art 19, Electronic Frontier Foundation, AccessNow & Principes Nécessité-Proportionnalité Surveillance", composite_score: 4.45, internet_censorship_shutdown_score: 5.0, surveillance_privacy_violation_score: 4.0, digital_expression_suppression_score: 3.0, algorithmic_discrimination_score: 6.0, risk_level: "faible", primary_pattern: "discrimination_algorithmique", key_signals: ["CDH-ONU/EFF incarne le cadre normatif exemplaire des droits numériques — Résolution 32/13 (2016) affirmant que les droits hors ligne doivent être protégés en ligne et Principes Nécessité-Proportionnalité pour la surveillance des communications créant des standards internationaux", "Résolution CDH-ONU 32/13 — affirme que les violations des droits humains en ligne doivent être traitées avec la même urgence que hors ligne, créant une obligation pour les États de protéger la liberté d'expression, la vie privée et l'accès à l'information sur Internet", "Universaliser la ratification de l'Article 19 PIDCP et renforcer le mandat du Rapporteur Spécial ONU sur la liberté d'expression pour inclure une surveillance active des coupures Internet et des violations de droits numériques par les États et entreprises technologiques"], estimated_digital_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { censure_coupure_internet: 3, surveillance_violation_vie_privee: 2, discrimination_algorithmique: 3 },
    top_risk_entities: ["Chine/Grand Firewall — 1.4Md Censurés, Surveillance IA Totale & WeChat Monitoring", "Corée du Nord — Internet 0.1% Population, Kwangmyong Intranet & Peines Mort Contenu", "Iran — 50%+ Contenu Bloqué, Pegasus Activistes & Coupe Internet Manifestations 2022"],
    critical_alerts: ["Chine/Grand Firewall: censure coupure internet", "Corée du Nord: censure coupure internet", "Iran: surveillance violation vie privée", "Russie: surveillance violation vie privée"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "digital_rights",
    confidence_score: 0.85,
    data_sources: ["freedom_house_freedom_on_the_net_annual_report", "accessnow_keepiton_internet_shutdown_tracker", "citizen_lab_targeted_threats_surveillance_research"],
    entities,
    avg_estimated_digital_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
