import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[domestic-violence-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Domestic Violence Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/domestic-violence-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Domestic Violence Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Domestic Violence Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "DV-001", name: "Afrique Sub-Saharienne/RDC — 57% Femmes VCI, Impunité Totale & Pas Convention Istanbul", country: "Afrique Centrale", sector: "RDC 57% Femmes Violence Conjugale ONU, Taux Impunité 95%+, Pas Loi Spécifique VD, Pratiques Culturelles Légitimant Correction & OMS 1/3 Femmes Monde Violence Partenaire", composite_score: 89.60, femicide_intimate_partner_score: 92.0, legal_protection_gap_score: 88.0, impunity_prosecution_failure_score: 92.0, economic_coercion_dependency_score: 85.0, risk_level: "critique", primary_pattern: "feminicide_partenaire_intime", key_signals: ["Violations liées aux violences domestiques documentées — Afrique Sub-Saharienne/RDC avec score composite 89.60/100 révélant des défaillances systémiques violant la Convention d'Istanbul (CAHVIO 2011) et la Déclaration ONU sur l'Élimination de la Violence envers les Femmes (DEVAW 1993)", "Féminicide/Partenaire intime (92.0/100) — avec 57% de femmes victimes de violence conjugale et un taux d'impunité de 95%, la RDC représente une crise systémique de protection des femmes violant les obligations de la Charte Africaine des Droits de l'Homme", "Activer le Rapporteur Spécial ONU sur la violence contre les femmes et la CEDAW pour examen d'urgence et exiger la ratification de la Convention d'Istanbul avec mise en place de tribunaux spécialisés violences conjugales"], estimated_domestic_violence_index: 8.96, last_updated: "2026-06-20" },
    { id: "DV-002", name: "Inde — 30% Femmes VCI, Dot Meurtres 7 000/An & Section 498A Non-Appliquée", country: "Asie du Sud", sector: "Inde 7 000+ Meurtres Dot/An NCRB, 30% Femmes Violences Conjugales OMS, Section 498A IPC Sous-Signalement, Tribunaux Familiaux Lents & UP/Bihar Impunité Culturelle", composite_score: 87.65, femicide_intimate_partner_score: 88.0, legal_protection_gap_score: 85.0, impunity_prosecution_failure_score: 88.0, economic_coercion_dependency_score: 90.0, risk_level: "critique", primary_pattern: "coercition_economique_dependance", key_signals: ["Violations liées aux violences domestiques documentées — Inde avec score composite 87.65/100 révélant des défaillances systémiques violant la Convention d'Istanbul (CAHVIO 2011) et la Déclaration ONU sur l'Élimination de la Violence envers les Femmes (DEVAW 1993)", "Féminicide/Partenaire intime (88.0/100) — les 7 000+ meurtres liés à la dot annuels en Inde et le sous-signalement systémique révèlent l'inefficacité de la protection légale (Section 498A IPC) face à des pratiques culturelles ancrées", "Activer le Rapporteur Spécial ONU sur la violence contre les femmes et la CEDAW pour examen d'urgence et exiger la ratification de la Convention d'Istanbul avec mise en place de tribunaux spécialisés violences conjugales"], estimated_domestic_violence_index: 8.77, last_updated: "2026-06-20" },
    { id: "DV-003", name: "Pakistan — 1 000 Meurtres Honneur/An, Loi PPVAW 2016 Non-Appliquée & Jirgas", country: "Asie du Sud", sector: "Pakistan 1 000+ Meurtres Honneur/An HRW, PPVAW Protection Women Act Punjab 2016 Non-Appliqué, Jirgas Justice Parallèle, Acid Attacks 200+/An & Impunité Culturelle", composite_score: 85.75, femicide_intimate_partner_score: 88.0, legal_protection_gap_score: 82.0, impunity_prosecution_failure_score: 85.0, economic_coercion_dependency_score: 88.0, risk_level: "critique", primary_pattern: "feminicide_partenaire_intime", key_signals: ["Violations liées aux violences domestiques documentées — Pakistan avec score composite 85.75/100 révélant des défaillances systémiques violant la Convention d'Istanbul (CAHVIO 2011) et la Déclaration ONU sur l'Élimination de la Violence envers les Femmes (DEVAW 1993)", "Féminicide/Partenaire intime (88.0/100) — les 1 000+ meurtres d'honneur annuels, les 200+ attaques à l'acide et les Jirgas de justice parallèle rendant des décisions contre les femmes constituent des violations graves de la CEDAW ratifiée par le Pakistan", "Activer le Rapporteur Spécial ONU sur la violence contre les femmes et la CEDAW pour examen d'urgence et exiger la ratification de la Convention d'Istanbul avec mise en place de tribunaux spécialisés violences conjugales"], estimated_domestic_violence_index: 8.58, last_updated: "2026-06-20" },
    { id: "DV-004", name: "Russie — Dépénalisation VD 2017, 10 000+ Décès/An & Pas Centres Refuge Suffisants", country: "Europe de l'Est", sector: "Russie Dépénalisation Violence Domestique 2017 Loi Mizulina, 10 000-14 000 Femmes Tuées Partenaires/An, 15 000 Maisons Refuge Pour 146M Habitants & COVID-19 +30% VD", composite_score: 85.65, femicide_intimate_partner_score: 85.0, legal_protection_gap_score: 90.0, impunity_prosecution_failure_score: 85.0, economic_coercion_dependency_score: 82.0, risk_level: "critique", primary_pattern: "lacune_protection_juridique", key_signals: ["Violations liées aux violences domestiques documentées — Russie avec score composite 85.65/100 révélant des défaillances systémiques violant la Convention d'Istanbul (CAHVIO 2011) et la Déclaration ONU sur l'Élimination de la Violence envers les Femmes (DEVAW 1993)", "Féminicide/Partenaire intime (85.0/100) — la dépénalisation des violences domestiques en 2017 et les 10 000-14 000 femmes tuées annuellement par leur partenaire révèlent une politique délibérée de régression des droits des femmes violant la CEDAW", "Activer le Rapporteur Spécial ONU sur la violence contre les femmes et la CEDAW pour examen d'urgence et exiger la ratification de la Convention d'Istanbul avec mise en place de tribunaux spécialisés violences conjugales"], estimated_domestic_violence_index: 8.57, last_updated: "2026-06-20" },
    { id: "DV-005", name: "Amérique Latine/Féminicide — Mexique 10/Jour, Guatemala & Honduras Taux Élevés", country: "Amérique Latine", sector: "Mexique 10 Féminicides/Jour 2023 INEGI, Guatemala/Honduras Parmi Plus Hauts Taux Monde, Ni Una Menos Mouvement, Impunité 98% Féminicides & MESECVI CEDAW Critiques", composite_score: 54.85, femicide_intimate_partner_score: 52.0, legal_protection_gap_score: 55.0, impunity_prosecution_failure_score: 62.0, economic_coercion_dependency_score: 50.0, risk_level: "élevé", primary_pattern: "impunite_violences_conjugales", key_signals: ["Violations liées aux violences domestiques documentées — Amérique Latine/Féminicide avec score composite 54.85/100 révélant une impunité quasi-totale (98%) pour les féminicides au Mexique violant la Convention de Belém do Pará et les recommandations MESECVI", "Féminicide/Partenaire intime (52.0/100) — les 10 féminicides quotidiens au Mexique et les taux parmi les plus élevés au monde au Guatemala/Honduras révèlent une défaillance systémique de la protection des femmes malgré les lois existantes", "Exiger des États d'Amérique latine l'application effective de la Convention de Belém do Pará et financer les systèmes judiciaires spécialisés féminicide avec protocoles d'enquête conformes aux recommandations MESECVI"], estimated_domestic_violence_index: 5.49, last_updated: "2026-06-20" },
    { id: "DV-006", name: "Moyen-Orient/MENA — Loi Personnelle Status, Mari Autorité & Pas Convention Istanbul", country: "MENA", sector: "MENA Lois Personnelle Status Couvrent VD, Mari Autorité Légale Femme Irak/Liban/Syrie, Qatar/UAE Pas Loi VD Spécifique, Sharia Divorce Difficile & Pas Ratification Istanbul", composite_score: 53.50, femicide_intimate_partner_score: 50.0, legal_protection_gap_score: 58.0, impunity_prosecution_failure_score: 52.0, economic_coercion_dependency_score: 55.0, risk_level: "élevé", primary_pattern: "lacune_protection_juridique", key_signals: ["Violations liées aux violences domestiques documentées — MENA avec score composite 53.50/100 révélant des lacunes juridiques systémiques dans la protection des femmes contre les violences domestiques via les lois de statut personnel", "Féminicide/Partenaire intime (50.0/100) — l'absence de lois spécifiques sur les violences domestiques dans plusieurs États du Golfe et les lois de statut personnel légitimant l'autorité maritale créent une impunité structurelle pour les violences conjugales", "Exiger des États du MENA l'abrogation des dispositions des lois de statut personnel permettant les violences et la ratification de la CEDAW sans réserves à l'Article 16 sur l'égalité dans le mariage"], estimated_domestic_violence_index: 5.35, last_updated: "2026-06-20" },
    { id: "DV-007", name: "Europe/USA — Convention Istanbul, #MeToo & Lacunes Protection Économique", country: "Europe/Amérique du Nord", sector: "USA 1/4 Femmes VPI NCVS, Convention Istanbul Non-Ratifiée USA, France 240 Féminicides/An, UK Coercive Control Loi 2015 & Lacunes Financement Maisons Refuge Austérité", composite_score: 28.55, femicide_intimate_partner_score: 28.0, legal_protection_gap_score: 30.0, impunity_prosecution_failure_score: 25.0, economic_coercion_dependency_score: 32.0, risk_level: "modéré", primary_pattern: "coercition_economique_dependance", key_signals: ["Défis persistants des violences domestiques en Europe et aux USA — malgré des cadres juridiques avancés (Convention Istanbul, VAWA USA), les lacunes de financement et d'application maintiennent 240 féminicides annuels en France et 1/4 de femmes victimes aux USA", "Coercition économique (32.0/100) — les coupes d'austérité dans le financement des maisons refuge et les difficultés économiques de dépendance freinent les sorties de violence domestique même dans les pays développés dotés de lois protectrices", "Renforcer le financement des maisons refuge et des services spécialisés en Europe et aux USA conformément aux standards de la Convention d'Istanbul (1 place refuge pour 10 000 habitants) et universaliser la ratification US de la CEDAW"], estimated_domestic_violence_index: 2.86, last_updated: "2026-06-20" },
    { id: "DV-008", name: "CEDAW/Convention Istanbul — ONU DEVAW 1993 & MESECVI Mécanisme Suivi", country: "Global", sector: "CEDAW Convention Élimination Discriminations Femmes, Convention Istanbul CoE CAHVIO 2011, ONU DEVAW 1993 Déclaration Violence Femmes, MESECVI & Rapporteur Spécial ONU Violence Femmes", composite_score: 4.45, femicide_intimate_partner_score: 5.0, legal_protection_gap_score: 4.0, impunity_prosecution_failure_score: 3.0, economic_coercion_dependency_score: 6.0, risk_level: "faible", primary_pattern: "coercition_economique_dependance", key_signals: ["CEDAW/Convention Istanbul incarne le cadre exemplaire de lutte contre les violences domestiques — GREVIO monitoring Convention Istanbul et Comité CEDAW créant des obligations contraignantes pour les États sur la prévention, protection et poursuite des violences conjugales", "Convention d'Istanbul Article 4 — oblige les États à prendre les mesures législatives nécessaires pour incriminer les violences domestiques physiques, sexuelles, psychologiques et économiques et garantir des enquêtes et poursuites effectives", "Universaliser la ratification de la Convention d'Istanbul et tripler le financement des services spécialisés violences domestiques via les mécanismes de financement de l'ONU-Femmes et du Fonds Fiduciaire ONU pour l'Élimination de la Violence"], estimated_domestic_violence_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { feminicide_partenaire_intime: 2, lacune_protection_juridique: 2, impunite_violences_conjugales: 1, coercition_economique_dependance: 3 },
    top_risk_entities: ["Afrique Sub-Saharienne/RDC — 57% Femmes VCI, Impunité Totale & Pas Convention Istanbul", "Inde — 30% Femmes VCI, Dot Meurtres 7 000/An & Section 498A Non-Appliquée", "Pakistan — 1 000 Meurtres Honneur/An, Loi PPVAW 2016 Non-Appliquée & Jirgas"],
    critical_alerts: ["Afrique Sub-Saharienne/RDC: féminicide partenaire intime", "Inde: coercition économique dépendance", "Pakistan: féminicide partenaire intime", "Russie: lacune protection juridique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "domestic_violence",
    confidence_score: 0.83,
    data_sources: ["who_global_status_report_violence_against_women", "un_women_global_femicide_database", "council_europe_convention_istanbul_monitoring_grevio"],
    entities,
    avg_estimated_domestic_violence_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
