import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[cultural-property-looting-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Cultural Property Looting Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/cultural-property-looting-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Cultural Property Looting Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Cultural Property Looting Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CP-001", name: "Daech/ISIS — Palmyre Destruction, Mossoul Musée & Trafic Financement Territorial", country: "MENA", sector: "Palmyre Colonnes Dynamitées 2015, Musée Mossoul Bulldozer, 100M$ Antiquités Vendues Daesh & Louvre Abu Dhabi Provenance Enquête", composite_score: 89.9, systematic_heritage_destruction_score: 95.0, illicit_antiquities_trafficking_score: 92.0, museum_archive_seizure_score: 88.0, restitution_refusal_impunity_score: 82.0, risk_level: "critique", primary_pattern: "destruction_patrimoine_systematique", key_signals: ["Destruction systématique du patrimoine par Daech/ISIS — Palmyre dynamitée, Musée de Mossoul au bulldozer et 100M$ d'antiquités vendues finançant directement les opérations militaires de Daech", "Crime de guerre et crime culturel — la destruction et le pillage délibérés du patrimoine constituent des crimes de guerre selon le Protocole II de La Haye 1954 et l'Article 8 du Statut de Rome", "Activer l'UNESCO et INTERPOL Works of Art pour listes noires et demandes de restitution urgentes via la Convention UNIDROIT 1995 sur les biens culturels volés"], estimated_cultural_property_looting_index: 8.99, last_updated: "2026-06-20" },
    { id: "CP-002", name: "Russie/Ukraine — Musées Marioupol Pillés, Archives Kherson & Crimée Collections", country: "Europe de l'Est", sector: "Musée Marioupol 2000 Œuvres Volées, Kherson Musée Pillé 2022, Crimée Collections Transférées Moscou & Heritage Mapping UA 50 000 Sites", composite_score: 87.4, systematic_heritage_destruction_score: 88.0, illicit_antiquities_trafficking_score: 80.0, museum_archive_seizure_score: 92.0, restitution_refusal_impunity_score: 90.0, risk_level: "critique", primary_pattern: "saisie_musees_archives", key_signals: ["Saisie de musées et archives par Russie/Ukraine — 2000 œuvres volées au musée de Marioupol et collections de la Crimée transférées à Moscou depuis 2014 sans restitution", "Crime de guerre et crime culturel — la destruction et le pillage délibérés du patrimoine constituent des crimes de guerre selon le Protocole II de La Haye 1954 et l'Article 8 du Statut de Rome", "Activer l'UNESCO et INTERPOL Works of Art pour listes noires et demandes de restitution urgentes via la Convention UNIDROIT 1995 sur les biens culturels volés"], estimated_cultural_property_looting_index: 8.74, last_updated: "2026-06-20" },
    { id: "CP-003", name: "Afghanistan/Taliban — Musée Kaboul, Bouddhas Bamiyan & Sites Préislamiques", country: "Asie Centrale", sector: "Bouddhas Bamiyan Explosés 2001, Musée Kaboul 70% Collection Volée, Sites Bactres/Aï Khanoum Pillés & Taliban Ban Archéologie Étrangère", composite_score: 85.35, systematic_heritage_destruction_score: 92.0, illicit_antiquities_trafficking_score: 85.0, museum_archive_seizure_score: 82.0, restitution_refusal_impunity_score: 80.0, risk_level: "critique", primary_pattern: "destruction_patrimoine_systematique", key_signals: ["Destruction systématique du patrimoine par Afghanistan/Taliban — Bouddhas de Bamiyan explosés en 2001 et 70% de la collection du Musée de Kaboul pillée, effaçant 2500 ans d'histoire pré-islamique", "Crime de guerre et crime culturel — la destruction délibérée du patrimoine constitue un crime de guerre selon le Protocole II de La Haye 1954 et a fait l'objet de la première condamnation CPI en 2016", "Activer l'UNESCO et INTERPOL Works of Art pour listes noires et demander accès aux missions de documentation archéologique urgentes"], estimated_cultural_property_looting_index: 8.54, last_updated: "2026-06-20" },
    { id: "CP-004", name: "Irak/Post-2003 — Musée Baghdad Pillage, Ninive & Sites Sumériens Creusés", country: "MENA", sector: "Musée National Baghdad 15 000 Pièces Pillées 2003, Ninive Sites Lourd, Ur Ziggurat Endommagé Base US & Christie's Provenance Enquêtes", composite_score: 86.0, systematic_heritage_destruction_score: 85.0, illicit_antiquities_trafficking_score: 90.0, museum_archive_seizure_score: 88.0, restitution_refusal_impunity_score: 80.0, risk_level: "critique", primary_pattern: "trafic_antiquites_illicite", key_signals: ["Trafic illicite d'antiquités en Irak/Post-2003 — 15 000 pièces pillées au Musée de Baghdad en 2003 alimentant les marchés d'art de Londres, New York et Genève via des chaînes d'achat volontairement opaques", "Crime de guerre et crime culturel — la destruction et le pillage délibérés du patrimoine constituent des crimes de guerre selon le Protocole II de La Haye 1954 et l'Article 8 du Statut de Rome", "Activer INTERPOL Works of Art et les douanes internationales pour tracer les collections pillées et demander leur restitution via la Convention UNIDROIT 1995"], estimated_cultural_property_looting_index: 8.6, last_updated: "2026-06-20" },
    { id: "CP-005", name: "Royaume-Uni/France — Marbres Elgin, Buste Néfertiti & Restitutions Refusées", country: "Europe", sector: "Marbres Elgin British Museum Refus Grèce, Buste Néfertiti Berlin Refus Égypte, Benin Bronzes Partiellement Restitués & Loi 2002 Inaliénabilité", composite_score: 58.95, systematic_heritage_destruction_score: 52.0, illicit_antiquities_trafficking_score: 55.0, museum_archive_seizure_score: 48.0, restitution_refusal_impunity_score: 88.0, risk_level: "élevé", primary_pattern: "refus_restitution", key_signals: ["Refus de restitution par Royaume-Uni/France — Marbres du Parthénon au British Museum malgré les demandes grecques répétées et Buste de Néfertiti à Berlin refusé à l'Égypte depuis 1924", "Crime de guerre et crime culturel — la rétention de biens culturels pillés constitue une violation continue des obligations de restitution prévues par la Convention UNESCO 1970 sur les biens culturels", "Réformer les lois d'inaliénabilité nationale pour permettre la restitution des biens acquis dans des contextes coloniaux ou de conflit armé selon les standards UNESCO"], estimated_cultural_property_looting_index: 5.9, last_updated: "2026-06-20" },
    { id: "CP-006", name: "Mali/Sahel — Tombouctou Mosquées Détruites & Trafic Via Réseaux Sahara", country: "Afrique de l'Ouest", sector: "Tombouctou Mosquées CPI Condamnation 2016, Manuscrits Sauvés ONG, Trafic Via Niger/Algérie & Sites Dogon Fouilles Clandestines", composite_score: 55.3, systematic_heritage_destruction_score: 58.0, illicit_antiquities_trafficking_score: 62.0, museum_archive_seizure_score: 48.0, restitution_refusal_impunity_score: 52.0, risk_level: "élevé", primary_pattern: "trafic_antiquites_illicite", key_signals: ["Trafic illicite d'antiquités au Mali/Sahel — mosquées de Tombouctou détruites en 2012 (première condamnation CPI pour crimes culturels en 2016) et réseaux de trafic saharien alimentant les marchés européens", "Crime de guerre et crime culturel — la destruction et le pillage délibérés du patrimoine constituent des crimes de guerre selon le Protocole II de La Haye 1954 et l'Article 8 du Statut de Rome", "Renforcer les capacités douanières sahéliennes et activer le programme UNESCO pour la protection d'urgence du patrimoine en zones de conflit"], estimated_cultural_property_looting_index: 5.53, last_updated: "2026-06-20" },
    { id: "CP-007", name: "Chine/Tibet-Xinjiang — Monastères Rasés & Effacement Patrimoine Culturel", country: "Asie", sector: "Monastères Tibétains Détruits Révolution Culturelle, Mosquées Xinjiang Démolies 2017-22, Lhassa Urbanisation Effacement & Littérature Interdite", composite_score: 30.95, systematic_heritage_destruction_score: 32.0, illicit_antiquities_trafficking_score: 28.0, museum_archive_seizure_score: 35.0, restitution_refusal_impunity_score: 28.0, risk_level: "modéré", primary_pattern: "saisie_musees_archives", key_signals: ["Saisie et effacement du patrimoine culturel par Chine/Tibet-Xinjiang — démolition de mosquées ouïghoures et surveillance des monastères tibétains dans le cadre d'une politique d'effacement identitaire documenté", "Crime de guerre et crime culturel — l'effacement systématique des marqueurs culturels d'un groupe peut constituer un élément du crime de génocide culturel selon la jurisprudence internationale", "Activer le Rapporteur Spécial ONU sur les droits culturels et demander accès de l'UNESCO aux sites du Tibet et du Xinjiang pour évaluation indépendante"], estimated_cultural_property_looting_index: 3.1, last_updated: "2026-06-20" },
    { id: "CP-008", name: "UNESCO/INTERPOL — Convention La Haye 1954 & Protection Patrimoine", country: "Global", sector: "Convention La Haye 133 États, INTERPOL Works Art Database, CPI Condamnation Tombouctou 2016 & UNESCO Liste Rouge Urgence", composite_score: 4.45, systematic_heritage_destruction_score: 5.0, illicit_antiquities_trafficking_score: 4.0, museum_archive_seizure_score: 3.0, restitution_refusal_impunity_score: 6.0, risk_level: "faible", primary_pattern: "refus_restitution", key_signals: ["UNESCO/INTERPOL incarnent la protection exemplaire du patrimoine — Convention de La Haye 1954, base INTERPOL des œuvres d'art et première condamnation CPI pour crimes culturels en 2016 à Tombouctou", "Normes internationales — Convention UNESCO 1970, Convention La Haye 1954 et Protocole II créant des obligations contraignantes de protection, restitution et poursuites pour pillage du patrimoine", "Partager les méthodologies INTERPOL de traçage des biens culturels et augmenter le financement de l'UNESCO pour la protection d'urgence du patrimoine dans les zones de conflit"], estimated_cultural_property_looting_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { destruction_patrimoine_systematique: 2, trafic_antiquites_illicite: 2, saisie_musees_archives: 2, refus_restitution: 2 },
    top_risk_entities: ["Daech/ISIS — Palmyre Destruction, Mossoul Musée & Trafic Financement Territorial", "Russie/Ukraine — Musées Marioupol Pillés, Archives Kherson & Crimée Collections", "Irak/Post-2003 — Musée Baghdad Pillage, Ninive & Sites Sumériens Creusés"],
    critical_alerts: ["Daech/ISIS: destruction patrimoine systématique", "Russie/Ukraine: saisie musées archives", "Afghanistan/Taliban: destruction patrimoine systématique", "Irak/Post-2003: trafic antiquités illicite"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "cultural_property_looting",
    confidence_score: 0.80,
    data_sources: ["interpol_works_of_art_database", "unesco_cultural_heritage_protection_reports", "asor_cultural_heritage_initiatives_reports"],
    entities,
    avg_estimated_cultural_property_looting_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
