import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[hate-crime-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Hate Crime Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/hate-crime-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Hate Crime Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Hate Crime Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "HC-001", name: "USA/Supremacy Blanche — 7 700+ Crimes Haine FBI, Islamophobie Post-9/11 & Impunité Structurelle", country: "Amérique du Nord", sector: "7 700+ Crimes Haine FBI 2022 Sous-Reportés, Suprémacisme Blanc Terrorisme Intérieur N°1, Islamophobie 2001-2024 Documentée & Acquittements Fréquents Auteurs", composite_score: 87.25, racial_bias_crime_rate_score: 92.0, religious_motivated_violence_score: 85.0, lgbtq_targeted_violence_score: 88.0, accountability_prosecution_failure_score: 82.0, risk_level: "critique", primary_pattern: "ciblage_racial_xenophobe", key_signals: ["Crimes de haine documentés — USA/Supremacy Blanche avec score composite 87.25/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (82.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 8.73, last_updated: "2026-06-20" },
    { id: "HC-002", name: "Inde/Lynchages Communautaires — Islamophobie BJP, Cow Vigilantes & 200+ Tués Impunis", country: "Asie du Sud", sector: "200+ Lynchages Cow Vigilantes 2014-24 Documentés HRW, Islamophobie Institutionnalisée BJP, Crimes Anti-Dalits & Lois Anti-Conversion Armes Communautaires", composite_score: 88.1, racial_bias_crime_rate_score: 90.0, religious_motivated_violence_score: 92.0, lgbtq_targeted_violence_score: 82.0, accountability_prosecution_failure_score: 88.0, risk_level: "critique", primary_pattern: "violence_religieuse_motivee", key_signals: ["Crimes de haine documentés — Inde/Lynchages Communautaires avec score composite 88.1/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (88.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 8.81, last_updated: "2026-06-20" },
    { id: "HC-003", name: "Russie/Chetchénie — Purges Anti-LGBT Kadyrov, Pogroms Ethniques & Crimes Motivés Haine", country: "Europe de l'Est", sector: "Purges Anti-LGBT Chetchénie 2017-19 Documentées ONU, Attaques Skinheads Minorités Ethniques, Loi Propagande Homosexuelle & Aucune Poursuite Officielle Kadyrov", composite_score: 85.95, racial_bias_crime_rate_score: 82.0, religious_motivated_violence_score: 80.0, lgbtq_targeted_violence_score: 95.0, accountability_prosecution_failure_score: 88.0, risk_level: "critique", primary_pattern: "violence_lgbtq_phobique", key_signals: ["Crimes de haine documentés — Russie/Chetchénie avec score composite 85.95/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (88.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 8.6, last_updated: "2026-06-20" },
    { id: "HC-004", name: "Allemagne/Extrême Droite — 14 000+ Crimes Haine/An, Attentats NSU & Neo-Nazisme", country: "Europe de l'Ouest", sector: "14 000+ Crimes Motivés Haine Allemagne 2022, Cellule Terroriste NSU 10 Meurtres Racistes Non Détectés Années, Attaques Mosquées 2024 & AfD Normalisation Discours Haine", composite_score: 83.0, racial_bias_crime_rate_score: 85.0, religious_motivated_violence_score: 82.0, lgbtq_targeted_violence_score: 80.0, accountability_prosecution_failure_score: 85.0, risk_level: "critique", primary_pattern: "ciblage_racial_xenophobe", key_signals: ["Crimes de haine documentés — Allemagne/Extrême Droite avec score composite 83.0/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (85.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 8.3, last_updated: "2026-06-20" },
    { id: "HC-005", name: "France/Antisémitisme-Islamophobie — 1 200+ Actes/An, BDS & Profanations", country: "Europe de l'Ouest", sector: "1 200+ Actes Antisémites France 2023, 900+ Actes Islamophobes, Profanations Cimetières & Loi Contre Séparatisme Ciblant Communautés Musulmanes", composite_score: 53.9, racial_bias_crime_rate_score: 55.0, religious_motivated_violence_score: 58.0, lgbtq_targeted_violence_score: 50.0, accountability_prosecution_failure_score: 52.0, risk_level: "élevé", primary_pattern: "violence_religieuse_motivee", key_signals: ["Crimes de haine documentés — France/Antisémitisme-Islamophobie avec score composite 53.9/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (52.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 5.39, last_updated: "2026-06-20" },
    { id: "HC-006", name: "Brésil/Violences LGBT+ — 300+ Meurtres/An, Homophobie Religieuse & Impunité", country: "Amérique du Sud", sector: "300+ Meurtres LGBT+ Brésil/An GGB, Taux Assassinats Trans 1er Monde, Bolsonaro Homophobie Institutionnelle 2019-22 & Église Évangélique Crimes Inspirés Haine", composite_score: 54.1, racial_bias_crime_rate_score: 52.0, religious_motivated_violence_score: 48.0, lgbtq_targeted_violence_score: 62.0, accountability_prosecution_failure_score: 55.0, risk_level: "élevé", primary_pattern: "violence_lgbtq_phobique", key_signals: ["Crimes de haine documentés — Brésil/Violences LGBT+ avec score composite 54.1/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (55.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 5.41, last_updated: "2026-06-20" },
    { id: "HC-007", name: "Royaume-Uni/Islamophobie Post-Brexit — 46 000 Incidents Haine/An & Reporting Partiel", country: "Europe de l'Ouest", sector: "46 000 Incidents Crimes Haine UK 2022, Islamophobie Doublée Post-Brexit 2016, Stephen Lawrence Case Institutionalisme & PREVENT Profilage Communautés Musulmanes", composite_score: 31.35, racial_bias_crime_rate_score: 32.0, religious_motivated_violence_score: 35.0, lgbtq_targeted_violence_score: 28.0, accountability_prosecution_failure_score: 30.0, risk_level: "modéré", primary_pattern: "violence_religieuse_motivee", key_signals: ["Crimes de haine documentés — Royaume-Uni/Islamophobie Post-Brexit avec score composite 31.35/100 révélant des violences systémiques motivées par la haine raciale, religieuse ou identitaire nécessitant une réponse juridique urgente", "Impunité structurelle — le niveau d'accountability/poursuites (30.0/100) indique une défaillance systémique dans la réponse judiciaire aux crimes de haine, perpétuant le cycle de violence", "Activer les mécanismes OSCE/ODIHR de reporting des crimes de haine et renforcer les lois nationales sur les crimes de haine avec formation des forces de l'ordre à l'identification et au signalement systématique"], estimated_hate_crime_index: 3.14, last_updated: "2026-06-20" },
    { id: "HC-008", name: "OSCE/ODIHR — Mécanisme Reporting Crimes Haine & Législations Modèles", country: "Global", sector: "ODIHR Système Reporting Crimes Haine 57 États, Recommandations Législatives Anti-Haine, Formation Police & Base Données Incidents Haine OSCE", composite_score: 4.45, racial_bias_crime_rate_score: 5.0, religious_motivated_violence_score: 4.0, lgbtq_targeted_violence_score: 3.0, accountability_prosecution_failure_score: 6.0, risk_level: "faible", primary_pattern: "impunite_auteurs_haine", key_signals: ["OSCE/ODIHR incarne le mécanisme exemplaire de lutte contre les crimes de haine — système de reporting dans 57 États membres et recommandations législatives créant un cadre de référence international", "Cadre juridique ODIHR — définition internationale des crimes de haine incluant les biais raciaux, religieux, homophobes et transphobiques avec obligation de documentation et de reporting des États membres", "Universaliser l'adoption des recommandations ODIHR sur les crimes de haine et financer la formation des forces de l'ordre à l'identification, l'investigation et la poursuite des crimes à caractère haineux"], estimated_hate_crime_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { ciblage_racial_xenophobe: 2, violence_religieuse_motivee: 3, violence_lgbtq_phobique: 2, impunite_auteurs_haine: 1 },
    top_risk_entities: ["Inde/Lynchages Communautaires — Islamophobie BJP, Cow Vigilantes & 200+ Tués Impunis", "USA/Supremacy Blanche — 7 700+ Crimes Haine FBI, Islamophobie Post-9/11 & Impunité Structurelle", "Russie/Chetchénie — Purges Anti-LGBT Kadyrov, Pogroms Ethniques & Crimes Motivés Haine"],
    critical_alerts: ["USA/Supremacy Blanche: ciblage racial xénophobe", "Inde/Lynchages: violence religieuse motivée", "Russie/Chetchénie: violence LGBT+phobique", "Allemagne/Extrême Droite: ciblage racial xénophobe"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "hate_crime",
    confidence_score: 0.80,
    data_sources: ["osce_odihr_hate_crime_reporting_database", "fbi_uniform_crime_reporting_hate_crimes", "ilga_world_homophobia_transphobia_report"],
    entities,
    avg_estimated_hate_crime_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
