import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[cultural-genocide-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Cultural Genocide Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/cultural-genocide-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Cultural Genocide Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Cultural Genocide Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CG-001", name: "Chine/Ouïghours — Xinjiang Camps Rééducation & Langue Bannie", country: "Asie", sector: "1M+ Internés Camps, Langue Ouïghoure Interdite Écoles, Mosquées Détruites & ADN Collecte Systémique", composite_score: 91.6, language_suppression_score: 95.0, cultural_heritage_destruction_score: 92.0, forced_assimilation_score: 90.0, religious_persecution_cultural_score: 88.0, risk_level: "critique", primary_pattern: "genocide_culturel_total", key_signals: ["Génocide culturel critique de Chine/Ouïghours — destruction institutionnelle délibérée d'une langue, d'un patrimoine ou d'une identité culturelle collective par un appareil étatique organisé", "Crime contre l'humanité culturel — la destruction systématique d'une culture constitue une violation grave du droit international humanitaire et des droits culturels fondamentaux", "Mémoire collective effacée — la perte irréversible des langues, traditions et patrimoines culturels représente un appauvrissement de l'humanité et un traumatisme intergénérationnel"], estimated_cultural_genocide_index: 9.16, last_updated: "2026-06-20" },
    { id: "CG-002", name: "Chine/Tibet — Sinicisation Forcée & Bouddhisme Contrôlé", country: "Asie", sector: "Mandarin Imposé Écoles, Moines 'Patriotic Education', Dalaï-Lama Succession Contrôlée & Monastères Demolitions", composite_score: 86.55, language_suppression_score: 88.0, cultural_heritage_destruction_score: 85.0, forced_assimilation_score: 90.0, religious_persecution_cultural_score: 82.0, risk_level: "critique", primary_pattern: "genocide_culturel_total", key_signals: ["Génocide culturel critique de Chine/Tibet — destruction institutionnelle délibérée d'une langue, d'un patrimoine ou d'une identité culturelle collective par un appareil étatique organisé", "Crime contre l'humanité culturel — la destruction systématique d'une culture constitue une violation grave du droit international humanitaire et des droits culturels fondamentaux", "Mémoire collective effacée — la perte irréversible des langues, traditions et patrimoines culturels représente un appauvrissement de l'humanité et un traumatisme intergénérationnel"], estimated_cultural_genocide_index: 8.66, last_updated: "2026-06-20" },
    { id: "CG-003", name: "Russie/Ukraine — Russification Territoires Occupés & Enfants Déportés", country: "Europe de l'Est", sector: "19 000+ Enfants Déportés CPI, Manuels Scolaires Réécrits, Langue Ukrainienne Bannie Écoles Occupées & Archives Détruites", composite_score: 79.75, language_suppression_score: 80.0, cultural_heritage_destruction_score: 85.0, forced_assimilation_score: 78.0, religious_persecution_cultural_score: 75.0, risk_level: "critique", primary_pattern: "destruction_patrimoine_systematique", key_signals: ["Génocide culturel critique de Russie/Ukraine — destruction institutionnelle délibérée d'une langue, d'un patrimoine ou d'une identité culturelle collective par un appareil étatique organisé", "Crime contre l'humanité culturel — la destruction systématique d'une culture constitue une violation grave du droit international humanitaire et des droits culturels fondamentaux", "Mémoire collective effacée — la perte irréversible des langues, traditions et patrimoines culturels représente un appauvrissement de l'humanité et un traumatisme intergénérationnel"], estimated_cultural_genocide_index: 7.98, last_updated: "2026-06-20" },
    { id: "CG-004", name: "Myanmar/Rohingyas — Effacement Identité & Apatridie Institutionnalisée", country: "Asie du Sud-Est", sector: "Apatridie 1982 Citizenship Law, Cimetières Rasés, Villages Brûlés Satellites & Mémoire Collective Détruite", composite_score: 82.6, language_suppression_score: 82.0, cultural_heritage_destruction_score: 80.0, forced_assimilation_score: 88.0, religious_persecution_cultural_score: 80.0, risk_level: "critique", primary_pattern: "assimilation_forcee_etatique", key_signals: ["Génocide culturel critique de Myanmar/Rohingyas — destruction institutionnelle délibérée d'une langue, d'un patrimoine ou d'une identité culturelle collective par un appareil étatique organisé", "Crime contre l'humanité culturel — la destruction systématique d'une culture constitue une violation grave du droit international humanitaire et des droits culturels fondamentaux", "Mémoire collective effacée — la perte irréversible des langues, traditions et patrimoines culturels représente un appauvrissement de l'humanité et un traumatisme intergénérationnel"], estimated_cultural_genocide_index: 8.26, last_updated: "2026-06-20" },
    { id: "CG-005", name: "Turquie/Kurdes — Langue Interdite Histoire & Assimilation Forcée", country: "MENA/Europe", sector: "Kurdophone Interdit Décennies, PKK Criminalisation Culture, Newroz Réprimé & Écoles Kurdes Fermées", composite_score: 56.4, language_suppression_score: 55.0, cultural_heritage_destruction_score: 52.0, forced_assimilation_score: 58.0, religious_persecution_cultural_score: 62.0, risk_level: "élevé", primary_pattern: "persecution_culturelle_active", key_signals: ["Persécution culturelle active de Turquie/Kurdes — restrictions légales systémiques sur les expressions culturelles minoritaires avec risque d'escalade vers la destruction patrimoniale", "Minorités culturelles sous pression — communautés linguistiques et religieuses marginalisées subissant des discriminations institutionnelles affectant leur transmission culturelle", "Défenseurs du patrimoine persécutés — militants des droits culturels, archivistes et linguistes ciblés par les autorités pour leur activisme de préservation"], estimated_cultural_genocide_index: 5.64, last_updated: "2026-06-20" },
    { id: "CG-006", name: "Éthiopie/Tigré — Amhara Expansion & Destruction Patrimoine Tigréen", country: "Afrique de l'Est", sector: "Églises Antiques Détruites Conflit 2020-22, Archives Axoum Pillées, Langues Minoritaires Tigré Supprimées", composite_score: 52.95, language_suppression_score: 52.0, cultural_heritage_destruction_score: 48.0, forced_assimilation_score: 55.0, religious_persecution_cultural_score: 58.0, risk_level: "élevé", primary_pattern: "persecution_culturelle_active", key_signals: ["Persécution culturelle active de Éthiopie/Tigré — restrictions légales systémiques sur les expressions culturelles minoritaires avec risque d'escalade vers la destruction patrimoniale", "Minorités culturelles sous pression — communautés linguistiques et religieuses marginalisées subissant des discriminations institutionnelles affectant leur transmission culturelle", "Défenseurs du patrimoine persécutés — militants des droits culturels, archivistes et linguistes ciblés par les autorités pour leur activisme de préservation"], estimated_cultural_genocide_index: 5.3, last_updated: "2026-06-20" },
    { id: "CG-007", name: "Canada/Autochtones — Pensionnats & Héritage Assimilation Forcée", country: "Amérique du Nord", sector: "150 000 Enfants Pensionnats, 215 Corps Kamloops 2021, Langues Autochtones Quasi-Disparues & Truth Reconciliation", composite_score: 29.65, language_suppression_score: 28.0, cultural_heritage_destruction_score: 25.0, forced_assimilation_score: 32.0, religious_persecution_cultural_score: 35.0, risk_level: "modéré", primary_pattern: "persecution_culturelle_active", key_signals: ["Discrimination culturelle persistante de Canada/Autochtones — politiques d'assimilation partielle affectant les minorités sans destruction systémique des infrastructures culturelles", "Transmission culturelle fragilisée — l'absence de soutien institutionnel aux langues et cultures minoritaires conduit à leur érosion progressive sans intervention délibérée", "Risque de dérive assimilatrice — les pressions économiques et la centralisation politique peuvent transformer une assimilation culturelle douce en politique étatique coercitive"], estimated_cultural_genocide_index: 2.97, last_updated: "2026-06-20" },
    { id: "CG-008", name: "UNESCO/CPPDCE — Diversité Culturelle & Droits Minorités Protégés", country: "Global", sector: "Convention Diversité Culturelle 2005, Patrimoine Immatériel 2003, Droits Linguistiques Minorités & Fonds Urgence", composite_score: 4.45, language_suppression_score: 5.0, cultural_heritage_destruction_score: 4.0, forced_assimilation_score: 3.0, religious_persecution_cultural_score: 6.0, risk_level: "faible", primary_pattern: "preservation_culturelle_exemplaire", key_signals: ["UNESCO/CPPDCE incarne la préservation exemplaire de la diversité culturelle — droits linguistiques des minorités garantis, patrimoine protégé et expression culturelle libre", "Institutions culturelles indépendantes — musées, archives, universités et médias minoritaires opérant librement avec un soutien public transparent", "Modèle de coexistence culturelle — financement UNESCO, ratification des conventions sur la diversité culturelle et coopération internationale pour protéger les patrimoines menacés"], estimated_cultural_genocide_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { genocide_culturel_total: 2, destruction_patrimoine_systematique: 1, assimilation_forcee_etatique: 1, persecution_culturelle_active: 3, preservation_culturelle_exemplaire: 1 },
    top_risk_entities: ["Chine/Ouïghours — Xinjiang Camps Rééducation & Langue Bannie", "Chine/Tibet — Sinicisation Forcée & Bouddhisme Contrôlé", "Myanmar/Rohingyas — Effacement Identité & Apatridie Institutionnalisée"],
    critical_alerts: ["Chine/Ouïghours: génocide culturel total", "Chine/Tibet: génocide culturel total", "Russie/Ukraine: destruction patrimoine systématique", "Myanmar/Rohingyas: assimilation forcée étatique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "cultural_genocide",
    confidence_score: 0.80,
    data_sources: ["cultural_survival_indigenous_rights", "minorities_at_risk_project", "un_cultural_rights_rapporteur_reports"],
    entities,
    avg_estimated_cultural_genocide_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
