import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

const UPSTREAM = process.env.SWARM_API_URL;
if (!UPSTREAM) console.warn("[food-security-rights-engine] SWARM_API_URL not set — running in offline mode");

export async function GET() {
  try {
    if (!UPSTREAM) throw new Error("offline");
    const res = await fetch(`${UPSTREAM}/api/food-security-rights-engine`, {
      next: { revalidate: 30 },
    });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(data));
  } catch {
    return sealResponse(NextResponse.json({
      agent: "FoodSecurityRights Engine Agent",
      domain: "food_security_rights",
      total_entities: 8,
      avg_composite: 61.74,
      confidence_score: 0.85,
      risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
      pattern_distribution: {
        famine_ipc5_aid_blockade: 1,
        deliberate_starvation_warfare: 1,
        humanitarian_blockade_conflict: 1,
        war_induced_food_system_collapse: 1,
        ngo_restriction_acute_malnutrition: 1,
        market_destruction_intercommunal_violence: 1,
        gang_controlled_food_distribution: 1,
        early_warning_response_framework: 1,
      },
      top_risk_entities: [
        "Somalie — IPC Phase 5 Catastrophe",
        "Gaza/Palestine — Famine délibérée IPC 2024",
        "Éthiopie/Tigré — Blocus humanitaire",
      ],
      critical_alerts: [
        "Somalie: famine_ipc5_aid_blockade",
        "Gaza/Palestine: deliberate_starvation_warfare",
        "Éthiopie/Tigré: humanitarian_blockade_conflict",
        "Yémen: war_induced_food_system_collapse",
      ],
      last_analysis: "2026-06-22",
      engine_version: "1.0.0",
      avg_estimated_food_security_rights_index: 6.17,
      data_sources: [
        "fao_global_food_crises_report_2024",
        "wfp_hunger_map_live_data_2024",
        "ipc_global_initiative_acute_food_insecurity",
        "hrw_starvation_as_weapon_war_documentation",
        "oxfam_right_food_global_violations_report",
      ],
      entities: [
        {
          entity_id: "FSR-001",
          name: "Somalie — IPC Phase 5 Catastrophe",
          country: "Somalie",
          famine_severity_score: 96.0,
          food_access_barrier_score: 94.0,
          agricultural_destruction_score: 93.0,
          food_aid_obstruction_score: 95.0,
          composite_score: 94.55,
          risk_level: "critique",
          primary_pattern: "famine_ipc5_aid_blockade",
          estimated_food_security_rights_index: 9.46,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-002",
          name: "Gaza/Palestine — Famine délibérée IPC 2024",
          country: "Palestine",
          famine_severity_score: 93.0,
          food_access_barrier_score: 91.0,
          agricultural_destruction_score: 92.0,
          food_aid_obstruction_score: 90.0,
          composite_score: 91.65,
          risk_level: "critique",
          primary_pattern: "deliberate_starvation_warfare",
          estimated_food_security_rights_index: 9.17,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-003",
          name: "Éthiopie/Tigré — Blocus humanitaire",
          country: "Éthiopie",
          famine_severity_score: 85.0,
          food_access_barrier_score: 84.0,
          agricultural_destruction_score: 82.0,
          food_aid_obstruction_score: 86.0,
          composite_score: 84.2,
          risk_level: "critique",
          primary_pattern: "humanitarian_blockade_conflict",
          estimated_food_security_rights_index: 8.42,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-004",
          name: "Yémen — Guerre & destruction agricole",
          country: "Yémen",
          famine_severity_score: 80.0,
          food_access_barrier_score: 79.0,
          agricultural_destruction_score: 78.0,
          food_aid_obstruction_score: 81.0,
          composite_score: 79.45,
          risk_level: "critique",
          primary_pattern: "war_induced_food_system_collapse",
          estimated_food_security_rights_index: 7.95,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-005",
          name: "Afghanistan — Malnutrition aiguë & restrictions ONGs",
          country: "Afghanistan",
          famine_severity_score: 56.0,
          food_access_barrier_score: 55.0,
          agricultural_destruction_score: 54.0,
          food_aid_obstruction_score: 57.0,
          composite_score: 55.45,
          risk_level: "élevé",
          primary_pattern: "ngo_restriction_acute_malnutrition",
          estimated_food_security_rights_index: 5.55,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-006",
          name: "RCA — Violences intercommunautaires & marchés détruits",
          country: "République Centrafricaine",
          famine_severity_score: 47.0,
          food_access_barrier_score: 46.0,
          agricultural_destruction_score: 48.0,
          food_aid_obstruction_score: 45.0,
          composite_score: 46.6,
          risk_level: "élevé",
          primary_pattern: "market_destruction_intercommunal_violence",
          estimated_food_security_rights_index: 4.66,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-007",
          name: "Haïti — Gangs contrôlant distribution alimentaire",
          country: "Haïti",
          famine_severity_score: 31.0,
          food_access_barrier_score: 30.0,
          agricultural_destruction_score: 29.0,
          food_aid_obstruction_score: 32.0,
          composite_score: 30.45,
          risk_level: "modéré",
          primary_pattern: "gang_controlled_food_distribution",
          estimated_food_security_rights_index: 3.05,
          last_updated: "2026-06-22",
        },
        {
          entity_id: "FSR-008",
          name: "WFP/FAO — Mécanismes alerte précoce FEWS NET",
          country: "International",
          famine_severity_score: 12.0,
          food_access_barrier_score: 11.0,
          agricultural_destruction_score: 13.0,
          food_aid_obstruction_score: 10.0,
          composite_score: 11.6,
          risk_level: "faible",
          primary_pattern: "early_warning_response_framework",
          estimated_food_security_rights_index: 1.16,
          last_updated: "2026-06-22",
        },
      ],
    }, { status: 200 }));
  }
}
