import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[indigenous-land-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    console.warn("[indigenous-land-rights-engine] SWARM_API_URL not set — returning mock");
    return await sealResponse(NextResponse.json({ payload: getMockData() }));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/indigenous-land-rights-engine`, { next: { revalidate: 30 } });
    const data = await res.json();
    return await sealResponse(NextResponse.json({ payload: data }));
  } catch {
    return await sealResponse(NextResponse.json({ error: "upstream_error" }, { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "IL-001", name: "Brésil/Amazonie — 1 000+ Terres Autochtones Menacées, Garimpos Illégaux & Défenseurs Assassinés", country: "Amérique du Sud", sector: "1 000+ Terres Autochtones Démarcation Bloquée Bolsonaro 2019-22, Garimpos Or Illégaux Yanomami 30 000 Contaminés Mercure, 60+ Défenseurs Tués/An Global Witness & FUNAI Démantelée", composite_score: 92.5, territorial_dispossession_score: 95.0, resource_extraction_impact_score: 92.0, legal_recognition_failure_score: 88.0, environmental_destruction_score: 95.0, risk_level: "critique", primary_pattern: "depossession_territoriale", key_signals: ["Dépossession territoriale autochtone — Brésil/Amazonie avec score composite 92.5/100 révélant une violation systémique des droits fonciers ancestraux protégés par la DNUDPA (Article 26) et les conventions OIT 169", "Extraction sans consentement — le score d'impact d'extraction (92.0/100) indique des activités extractives conduites sans Consentement Libre, Préalable et Éclairé (CLPE) des communautés autochtones", "Activer le Mécanisme Expert ONU sur les Droits des Peuples Autochtones pour enquête urgente et exiger le respect du CLPE dans tous les projets d'extraction sur terres ancestrales conformément à la DNUDPA 2007"], estimated_indigenous_land_rights_index: 9.25, last_updated: "2026-06-20" },
    { id: "IL-002", name: "Canada/Premières Nations — Traités Non-Respectés, Pipeline Trans Mountain & RCAANC", country: "Amérique du Nord", sector: "Traités Territoriaux Historiques Canada Non-Respectés, Pipeline Trans Mountain Terres Wet'suwet'en Sans CLPE, 215+ Corps Enfants Kamloops 2021 & RCAANC Consultation Factice", composite_score: 87.65, territorial_dispossession_score: 88.0, resource_extraction_impact_score: 85.0, legal_recognition_failure_score: 92.0, environmental_destruction_score: 85.0, risk_level: "critique", primary_pattern: "non_reconnaissance_juridique", key_signals: ["Dépossession territoriale autochtone — Canada/Premières Nations avec score composite 87.65/100 révélant une violation systémique des droits fonciers ancestraux protégés par la DNUDPA (Article 26) et les conventions OIT 169", "Extraction sans consentement — le score d'impact d'extraction (85.0/100) indique des activités extractives conduites sans Consentement Libre, Préalable et Éclairé (CLPE) des communautés autochtones", "Activer le Mécanisme Expert ONU sur les Droits des Peuples Autochtones pour enquête urgente et exiger le respect du CLPE dans tous les projets d'extraction sur terres ancestrales conformément à la DNUDPA 2007"], estimated_indigenous_land_rights_index: 8.77, last_updated: "2026-06-20" },
    { id: "IL-003", name: "Papouasie/Indonésie — Déforestation Forêts Papouanes, Transmigration & Mines Freeport", country: "Asie du Sud-Est", sector: "Forêts Papouanes Déforestées Mine Freeport-McMoRan Grasberg, Transmigration Javanaise 1M+ Colons Terres Ancestrales, PT Freeport Royalties Insuffisantes & Militarisation Résistance", composite_score: 87.6, territorial_dispossession_score: 85.0, resource_extraction_impact_score: 90.0, legal_recognition_failure_score: 88.0, environmental_destruction_score: 88.0, risk_level: "critique", primary_pattern: "extraction_ressources_illegale", key_signals: ["Dépossession territoriale autochtone — Papouasie/Indonésie avec score composite 87.6/100 révélant une violation systémique des droits fonciers ancestraux protégés par la DNUDPA (Article 26) et les conventions OIT 169", "Extraction sans consentement — le score d'impact d'extraction (90.0/100) indique des activités extractives conduites sans Consentement Libre, Préalable et Éclairé (CLPE) des communautés autochtones", "Activer le Mécanisme Expert ONU sur les Droits des Peuples Autochtones pour enquête urgente et exiger le respect du CLPE dans tous les projets d'extraction sur terres ancestrales conformément à la DNUDPA 2007"], estimated_indigenous_land_rights_index: 8.76, last_updated: "2026-06-20" },
    { id: "IL-004", name: "Philippines/Lumad — IPRA Non-Appliqué, Mines Mindanao & Déplacements Forcés", country: "Asie du Sud-Est", sector: "IPRA 1997 Droits Ancêtres Lumad Non-Appliqué, Mines Nickel/Or Mindanao Terres Ancestrales, 3 000+ Déplacements Forcés Conflits & Militarisation Écoles Autochtones Documentée", composite_score: 83.35, territorial_dispossession_score: 82.0, resource_extraction_impact_score: 85.0, legal_recognition_failure_score: 82.0, environmental_destruction_score: 85.0, risk_level: "critique", primary_pattern: "extraction_ressources_illegale", key_signals: ["Dépossession territoriale autochtone — Philippines/Lumad avec score composite 83.35/100 révélant une violation systémique des droits fonciers ancestraux protégés par la DNUDPA (Article 26) et les conventions OIT 169", "Extraction sans consentement — le score d'impact d'extraction (85.0/100) indique des activités extractives conduites sans Consentement Libre, Préalable et Éclairé (CLPE) des communautés autochtones", "Activer le Mécanisme Expert ONU sur les Droits des Peuples Autochtones pour enquête urgente et exiger le respect du CLPE dans tous les projets d'extraction sur terres ancestrales conformément à la DNUDPA 2007"], estimated_indigenous_land_rights_index: 8.34, last_updated: "2026-06-20" },
    { id: "IL-005", name: "Kenya/Maasaï — Ngorongoro Expulsions, Terres Touristiques & Consentement Absent", country: "Afrique de l'Est", sector: "Maasaï Ngorongoro Conservation Area Expulsions 2022 Sans CLPE, Terres Ancestrales Cédées Tourisme Safari, USAID Financements Réinstallation & Opposition Internationale Ignorée", composite_score: 54.0, territorial_dispossession_score: 55.0, resource_extraction_impact_score: 52.0, legal_recognition_failure_score: 58.0, environmental_destruction_score: 50.0, risk_level: "élevé", primary_pattern: "non_reconnaissance_juridique", key_signals: ["Dépossession territoriale autochtone — Kenya/Maasaï avec score composite 54.0/100 révélant des expulsions forcées des terres ancestrales sans CLPE violant la DNUDPA et les obligations du Kenya sous le Protocole de Maputo", "Extraction sans consentement — le défaut de reconnaissance juridique (58.0/100) prive les Maasaï des recours légaux contre les expulsions pour la conservation et le tourisme", "Exiger du Kenya la conformité avec la jurisprudence CADHP sur les droits fonciers des peuples autochtones et suspendre tout déplacement forcé des Maasaï du Ngorongoro sans CLPE validé"], estimated_indigenous_land_rights_index: 5.4, last_updated: "2026-06-20" },
    { id: "IL-006", name: "Australie/Autochtones — Fracking Northern Territory, Sites Sacrés & Land Rights Act", country: "Océanie", sector: "Aboriginal Land Rights Act 1976 Contourné Fracking NT, Juukan Gorge Sites Sacrés Rio Tinto Détruites 2020, Northern Territory Intervention & Lacunes Native Title Act Veto Minier", composite_score: 52.85, territorial_dispossession_score: 52.0, resource_extraction_impact_score: 55.0, legal_recognition_failure_score: 50.0, environmental_destruction_score: 55.0, risk_level: "élevé", primary_pattern: "extraction_ressources_illegale", key_signals: ["Dépossession territoriale autochtone — Australie/Autochtones avec score composite 52.85/100 révélant des destructions de sites sacrés et des activités d'extraction contournant les protections du Land Rights Act de 1976", "Extraction sans consentement — la destruction de la gorge de Juukan par Rio Tinto en 2020 illustre la faiblesse des mécanismes de CLPE pour les sites du patrimoine autochtone en Australie", "Renforcer le Native Title Act pour garantir un droit de veto effectif des peuples autochtones sur la destruction de sites sacrés et l'extraction de ressources sur terres ancestrales"], estimated_indigenous_land_rights_index: 5.29, last_updated: "2026-06-20" },
    { id: "IL-007", name: "Nouvelle-Zélande/Māori — Waitangi Partiellement Respecté & Progrès He Puapua", country: "Océanie", sector: "Traité Waitangi 1840 Application Partielle 60% Terres Ancestrales Perdues, He Puapua Plan Droits Autochtones 2021, Whanganui River Personnalité Juridique & Co-Gouvernance Progrès", composite_score: 28.15, territorial_dispossession_score: 28.0, resource_extraction_impact_score: 30.0, legal_recognition_failure_score: 25.0, environmental_destruction_score: 30.0, risk_level: "modéré", primary_pattern: "extraction_ressources_illegale", key_signals: ["Progrès significatifs mais insuffisants en Nouvelle-Zélande/Māori — Traité de Waitangi partiellement appliqué avec He Puapua 2021 et personnalité juridique accordée à la rivière Whanganui comme modèle innovant", "Reconnaissance partielle des droits fonciers — 60% des terres ancestrales Māori historiquement perdues restent non-restituées, malgré des avancées institutionnelles notables en co-gouvernance environnementale", "Approfondir la mise en œuvre du Plan He Puapua pour la co-gouvernance Māori des ressources naturelles et accélérer les règlements de revendications territoriales du Tribunal Waitangi"], estimated_indigenous_land_rights_index: 2.82, last_updated: "2026-06-20" },
    { id: "IL-008", name: "UNPFII/UNDRIP — Déclaration ONU 2007 Droits Peuples Autochtones & Mécanisme Expert", country: "Global", sector: "DNUDPA 2007 147 Votes Pour, UNPFII Forum Permanent ONU, Mécanisme Expert Droits Peuples Autochtones & CLPE Standard International Consentement Libre Préalable Éclairé", composite_score: 4.45, territorial_dispossession_score: 5.0, resource_extraction_impact_score: 4.0, legal_recognition_failure_score: 3.0, environmental_destruction_score: 6.0, risk_level: "faible", primary_pattern: "destruction_ecosystemes_sacres", key_signals: ["UNPFII/UNDRIP incarne le cadre exemplaire des droits des peuples autochtones — DNUDPA 2007 adoptée par 147 États et Forum Permanent des Nations Unies créant une plateforme de dialogue et de responsabilité", "DNUDPA Article 26 — droit des peuples autochtones à posséder, utiliser, développer et contrôler les terres, territoires et ressources qu'ils possèdent en vertu de la possession traditionnelle ou de l'occupation", "Universaliser la ratification de la Convention OIT 169 et renforcer le mandat du Mécanisme Expert ONU sur les Droits des Peuples Autochtones pour contraindre les États à appliquer le CLPE"], estimated_indigenous_land_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { depossession_territoriale: 1, extraction_ressources_illegale: 4, non_reconnaissance_juridique: 2, destruction_ecosystemes_sacres: 1 },
    top_risk_entities: ["Brésil/Amazonie — 1 000+ Terres Autochtones Menacées, Garimpos Illégaux & Défenseurs Assassinés", "Canada/Premières Nations — Traités Non-Respectés, Pipeline Trans Mountain & RCAANC", "Papouasie/Indonésie — Déforestation Forêts Papouanes, Transmigration & Mines Freeport"],
    critical_alerts: ["Brésil/Amazonie: dépossession territoriale", "Canada/Premières Nations: non-reconnaissance juridique", "Papouasie/Indonésie: extraction ressources illégale", "Philippines/Lumad: extraction ressources illégale"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "indigenous_land_rights",
    confidence_score: 0.83,
    data_sources: ["forest_peoples_programme_land_rights_database", "un_permanent_forum_indigenous_peoples_reports", "global_witness_land_defenders_killed_database"],
    entities,
    avg_estimated_indigenous_land_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
