import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[colonial-reparations-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Colonial Reparations Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/colonial-reparations-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Colonial Reparations Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Colonial Reparations Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "CR-001", name: "Congo Belge/Léopold II — Génocide 10M Morts, Mains Coupées & Belgique Sans Réparation", country: "Afrique Centrale", sector: "Léopold II Congo 10M Morts Estimés 1885-1908, Système Mains Coupées Documenté Adam Hochschild, Ressources Extractées Sans Réparation & Belgique Reconnaissance Partielle 2002", composite_score: 90.6, historical_atrocity_magnitude_score: 95.0, reparation_refusal_persistence_score: 90.0, ongoing_structural_impact_score: 88.0, accountability_recognition_failure_score: 88.0, risk_level: "critique", primary_pattern: "atrocites_coloniales_masse", key_signals: ["Atrocités coloniales de masse au Congo Belge/Léopold II — 10 millions de morts estimés sous le régime de terreur de Léopold II avec système de mutilations (mains coupées) documenté par les journalistes de l'époque et sans réparations formelles de la Belgique", "Justice historique imprescriptible — les atrocités du Congo Belge constituent selon de nombreux historiens le premier génocide du XXe siècle, créant une obligation morale et juridique de reconnaissance et de réparation de la Belgique", "Exiger de la Belgique des réparations formelles au Congo pour les crimes de Léopold II, au-delà de la reconnaissance partielle de 2002, incluant restitution du patrimoine pillé et fonds de développement"], estimated_colonial_reparations_index: 9.06, last_updated: "2026-06-20" },
    { entity_id: "CR-002", name: "Namibie/Allemagne — Génocide Herero/Nama 1904-08, Reconnaissance 2021 & Réparations Insuffisantes", country: "Afrique Australe", sector: "Génocide Herero/Nama 80 000+ Morts 1904-08, Premier Génocide du XXe Siècle Reconnu, Accord Allemagne-Namibie 2021 1.1Md€ & Victimes Rejettent Offre Insuffisante", composite_score: 87.85, historical_atrocity_magnitude_score: 92.0, reparation_refusal_persistence_score: 88.0, ongoing_structural_impact_score: 85.0, accountability_recognition_failure_score: 85.0, risk_level: "critique", primary_pattern: "genocide_colonial_non_reconnu", key_signals: ["Génocide colonial non entièrement réparé en Namibie/Allemagne — génocide Herero et Nama de 1904-08 reconnu par l'Allemagne en 2021 avec offre de 1.1 milliard d'euros mais rejetée par les représentants des victimes comme insuffisante et excluant les descendants", "Premier génocide du XXe siècle — le génocide Herero/Nama constitue le premier génocide colonial documenté du siècle, créant un précédent de responsabilité d'État pour crimes coloniaux avec des implications pour d'autres nations colonisatrices", "Renégocier l'accord Allemagne-Namibie de 2021 avec une représentation directe des communautés Herero et Nama et accroître substantiellement le montant des réparations pour refléter la magnitude du génocide"], estimated_colonial_reparations_index: 8.79, last_updated: "2026-06-20" },
    { entity_id: "CR-003", name: "Inde/Royaume-Uni — Pillage Colonial 45 Trillards £ Estimé, Famine Bengal & Zero Réparation", country: "Asie du Sud", sector: "Économiste Utsa Patnaik Pillage 45 Trillards £ 1765-1938, Famines Bengal 1943 3M Morts Churchill, Kohinoor/Patrimoine Non-Restitué & Aucune Réparation Britannique", composite_score: 86.55, historical_atrocity_magnitude_score: 88.0, reparation_refusal_persistence_score: 85.0, ongoing_structural_impact_score: 90.0, accountability_recognition_failure_score: 82.0, risk_level: "critique", primary_pattern: "pillage_colonial_systematique", key_signals: ["Pillage colonial systématique Inde/Royaume-Uni — économiste Utsa Patnaik estimant le pillage britannique de l'Inde à 45 trillards de livres sur 173 ans, avec la Famine du Bengale de 1943 causant 3 millions de morts sous la politique de Churchill", "Impact structurel persistant — le pillage colonial explique en partie les inégalités économiques actuelles entre le Royaume-Uni et l'Inde, et la non-restitution du Kohinoor et des archives coloniales perpétue l'injustice historique", "Engager le débat sur les réparations coloniales britanniques à l'Inde incluant la restitution du Kohinoor, des archives coloniales et la création d'un fonds de justice historique reconnaissant les crimes de la colonisation"], estimated_colonial_reparations_index: 8.65, last_updated: "2026-06-20" },
    { entity_id: "CR-004", name: "Algérie/France — 132 Ans Colonisation, Guerre Indépendance 1M Morts & Torture Reconnue", country: "MENA/Europe", sector: "132 Ans Colonisation Française Algérie 1830-1962, Guerre Indépendance 1 000 000 Morts Algériens Estimés, Torture Systematique 1954-62 Reconnue & Macron Reconnaissance Partielle", composite_score: 84.0, historical_atrocity_magnitude_score: 85.0, reparation_refusal_persistence_score: 82.0, ongoing_structural_impact_score: 88.0, accountability_recognition_failure_score: 80.0, risk_level: "critique", primary_pattern: "atrocites_coloniales_masse", key_signals: ["Atrocités coloniales de masse Algérie/France — 132 ans de colonisation avec 1 million de morts algériens estimés pendant la guerre d'indépendance (1954-62) et torture systématique reconnue par Macron en 2018 sans réparations formelles", "Blessure mémorielle persistante — l'absence de reconnaissance complète et de réparations françaises pour les crimes coloniaux en Algérie entretient une fracture mémorielle affectant les relations diplomatiques et les communautés franco-algériennes", "Poursuivre le processus de réconciliation mémorielle franco-algérienne avec reconnaissance formelle des crimes de la colonisation et création d'une commission bilatérale sur la mémoire incluant la question des réparations"], estimated_colonial_reparations_index: 8.4, last_updated: "2026-06-20" },
    { entity_id: "CR-005", name: "CARICOM/Caraïbes — Plan 10 Points Réparations, Esclavage Traite & Dettes Coloniales", country: "Caraïbes", sector: "CARICOM Plan Réparations 10 Points 2014, Esclavage Transatlantique 12.5M Déportés, Haïti Dette Coloniale France 21Md$ Remboursée & Légacies Structurelles Pauvreté", composite_score: 55.15, historical_atrocity_magnitude_score: 55.0, reparation_refusal_persistence_score: 58.0, ongoing_structural_impact_score: 55.0, accountability_recognition_failure_score: 52.0, risk_level: "élevé", primary_pattern: "refus_reparations_persistant", key_signals: ["Refus persistant des réparations aux Caraïbes/CARICOM — Plan en 10 Points de la CARICOM demandant réparations pour l'esclavage transatlantique (12.5 millions déportés) ignoré par les anciennes puissances coloniales et dette haïtienne payée à la France pendant 122 ans", "Injustice économique structurelle — la traite transatlantique et l'esclavage ont créé des inégalités économiques persistantes entre les Caraïbes et les anciennes métropoles coloniales, avec Haïti ayant payé 21 milliards de dollars de 'dette d'indépendance' à la France", "Soutenir le Plan en 10 Points de la CARICOM incluant excuses formelles, programmes de développement et annulation des dettes coloniales résiduelles, en commençant par la restitution de la dette haïtienne à la France"], estimated_colonial_reparations_index: 5.51, last_updated: "2026-06-20" },
    { entity_id: "CR-006", name: "Australie/Générations Volées — Enfants Autochtones Enlevés 1910-70 & Sorry Day 2008", country: "Océanie", sector: "Générations Volées 100 000+ Enfants Autochtones Enlevés Familles 1910-1970, Rapport Bringing Them Home 1997, Sorry Day Rudd 2008 & Réparations Financières Insuffisantes", composite_score: 52.35, historical_atrocity_magnitude_score: 52.0, reparation_refusal_persistence_score: 55.0, ongoing_structural_impact_score: 52.0, accountability_recognition_failure_score: 50.0, risk_level: "élevé", primary_pattern: "genocide_colonial_non_reconnu", key_signals: ["Génocide culturel partiellement reconnu Australie/Générations Volées — 100 000+ enfants autochtones enlevés à leurs familles entre 1910 et 1970 (Générations Volées), avec excuses formelles du Premier Ministre Rudd en 2008 mais réparations financières insuffisantes", "Impact structurel multigénérationnel — les traumatismes intergénérationnels des Générations Volées contribuent aux inégalités persistantes en santé, éducation et espérance de vie entre Autochtones et non-Autochtones en Australie", "Mettre en œuvre les recommandations du rapport Closing the Gap avec financement adéquat et négocier des réparations financières directes aux survivants des Générations Volées et leurs descendants"], estimated_colonial_reparations_index: 5.23, last_updated: "2026-06-20" },
    { entity_id: "CR-007", name: "USA/Esclavage — HR40 Commission Reparations, Wealth Gap Racial & Tulsa Race Massacre", country: "Amérique du Nord", sector: "HR40 Bill Commission Réparations Esclavage Bloqué Congrès, Wealth Gap Racial 8x, Tulsa Race Massacre 1921 Rescapés Sans Réparation & Evanston IL Premier Programme Local", composite_score: 29.5, historical_atrocity_magnitude_score: 28.0, reparation_refusal_persistence_score: 32.0, ongoing_structural_impact_score: 30.0, accountability_recognition_failure_score: 28.0, risk_level: "modéré", primary_pattern: "refus_reparations_persistant", key_signals: ["Refus persistant des réparations aux États-Unis/Esclavage — le projet de loi HR40 créant une commission d'étude des réparations pour l'esclavage bloqué au Congrès depuis 1989, malgré un écart de richesse racial de 8:1 et le Massacre de Tulsa 1921 sans indemnisation des rescapés", "Inégalité structurelle héritée — l'écart de richesse racial de 8:1 entre Noirs et Blancs aux États-Unis est directement lié à l'héritage de l'esclavage et à des politiques post-esclavage discriminatoires comme la ségrégation et le redlining", "Soutenir l'adoption du HR40 au Congrès américain pour créer une commission d'étude des réparations pour l'esclavage et s'inspirer du programme de réparations locales d'Evanston (Illinois) comme modèle municipal"], estimated_colonial_reparations_index: 2.95, last_updated: "2026-06-20" },
    { entity_id: "CR-008", name: "CARICOM/ONU — Cadre Réparations Internationales & Principes Justice Transitionnelle", country: "Global", sector: "Principes ONU Droit Recours Réparation Victimes 2005, Forum Permanent Peuples Autochtones ONU, Déclaration ONU Peuples Autochtones 2007 & CARICOM 10 Points Framework", composite_score: 4.45, historical_atrocity_magnitude_score: 5.0, reparation_refusal_persistence_score: 4.0, ongoing_structural_impact_score: 3.0, accountability_recognition_failure_score: 6.0, risk_level: "faible", primary_pattern: "refus_reparations_persistant", key_signals: ["CARICOM/ONU incarnent le cadre exemplaire des réparations — Principes ONU sur le droit à un recours et à réparation (2005) et Déclaration ONU sur les droits des peuples autochtones (2007) créant une base juridique pour les revendications de réparations coloniales", "Principes ONU sur les Victimes (Résolution 60/147) — droit des victimes de crimes historiques à une restitution, indemnisation, réhabilitation, satisfaction et garanties de non-répétition, applicables aux crimes coloniaux", "Partager les méthodologies CARICOM de quantification des réparations coloniales et renforcer le mandat du Forum Permanent des Nations Unies pour les questions autochtones pour documenter les impacts persistants de la colonisation"], estimated_colonial_reparations_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { atrocites_coloniales_masse: 2, genocide_colonial_non_reconnu: 2, pillage_colonial_systematique: 1, refus_reparations_persistant: 3 },
    top_risk_entities: ["Congo Belge/Léopold II — Génocide 10M Morts, Mains Coupées & Belgique Sans Réparation", "Namibie/Allemagne — Génocide Herero/Nama 1904-08, Reconnaissance 2021 & Réparations Insuffisantes", "Inde/Royaume-Uni — Pillage Colonial 45 Trillards £ Estimé, Famine Bengal & Zero Réparation"],
    critical_alerts: ["Congo Belge/Léopold II: atrocités coloniales masse", "Namibie/Allemagne: génocide colonial non reconnu", "Inde/Royaume-Uni: pillage colonial systématique", "Algérie/France: atrocités coloniales masse"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "colonial_reparations",
    confidence_score: 0.79,
    data_sources: ["caricom_reparations_commission_report", "un_permanent_forum_indigenous_issues", "transitional_justice_database_ictj"],
    entities,
    avg_estimated_colonial_reparations_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
