import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[right-to-education-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Right to Education Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/right-to-education-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Right to Education Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Right to Education Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "RE-001", name: "Afghanistan/Taliban — 4M Filles Interdites École 2021, Université Fermée & Éducation Femmes", country: "Asie du Sud", sector: "Taliban 4M+ Filles Interdites École Afghanistan 2021, Universités Femmes Fermées 2022, Écoles Secrètes Clandestines & UNICEF 6.2M Enfants Hors École 2023", composite_score: 91.25, school_exclusion_rate_score: 95.0, gender_education_barrier_score: 95.0, quality_infrastructure_failure_score: 88.0, conflict_education_destruction_score: 85.0, risk_level: "critique", primary_pattern: "exclusion_scolaire_massive", key_signals: ["Violation du droit à l'éducation documentée — Afghanistan/Taliban avec score composite 91.25/100 révélant une exclusion scolaire massive violant l'Article 26 de la DUDH et l'Article 28 de la Convention des Droits de l'Enfant", "Barrière de genre à l'éducation (95.0/100) — l'exclusion totale des filles de l'éducation par les Taliban constitue la violation la plus grave du droit à l'éducation documentée dans le monde depuis 2021", "Activer l'UNESCO/Rapporteur Spécial ONU sur le Droit à l'Éducation pour enquête urgente et mobiliser le Fonds UNICEF d'Éducation en Situation d'Urgence (ESU) pour rétablir l'accès scolaire"], estimated_right_to_education_index: 9.13, last_updated: "2026-06-20" },
    { id: "RE-002", name: "Yémen/Conflit — 8M Enfants Hors École, 2 400 Écoles Détruites & Enseignants Non-Payés", country: "MENA", sector: "Yemen 8M Enfants Hors École 2023 UNICEF, 2 400+ Écoles Détruites/Endommagées, Enseignants Non-Payés 8 Ans, Houthis Recrutement Écoles & Financement Urgence Insuffisant", composite_score: 88.55, school_exclusion_rate_score: 88.0, gender_education_barrier_score: 85.0, quality_infrastructure_failure_score: 90.0, conflict_education_destruction_score: 92.0, risk_level: "critique", primary_pattern: "destruction_ecoles_conflit", key_signals: ["Violation du droit à l'éducation documentée — Yémen/Conflit avec score composite 88.55/100 révélant une exclusion scolaire massive violant l'Article 26 de la DUDH et l'Article 28 de la Convention des Droits de l'Enfant", "Barrière de genre à l'éducation (85.0/100) — l'interruption de scolarité de 8 millions d'enfants yéménites dont une majorité de filles constitue une violation grave du droit à l'éducation garantie par la CDE", "Activer l'UNESCO/Rapporteur Spécial ONU sur le Droit à l'Éducation pour enquête urgente et mobiliser le Fonds UNICEF d'Éducation en Situation d'Urgence (ESU) pour rétablir l'accès scolaire"], estimated_right_to_education_index: 8.86, last_updated: "2026-06-20" },
    { id: "RE-003", name: "Mali/Burkina Faso — 1M Enfants Hors École, 1 200+ Écoles Fermées & Djihadistes Menaces", country: "Afrique de l'Ouest", sector: "Mali/Burkina Faso 1M+ Enfants Hors École Conflit, 1 200+ Écoles Fermées Menaces Djihadistes, Enseignants Tués/Kidnappés & MINUSMA Retrait Impact Éducation", composite_score: 85.25, school_exclusion_rate_score: 85.0, gender_education_barrier_score: 82.0, quality_infrastructure_failure_score: 85.0, conflict_education_destruction_score: 90.0, risk_level: "critique", primary_pattern: "destruction_ecoles_conflit", key_signals: ["Violation du droit à l'éducation documentée — Mali/Burkina Faso avec score composite 85.25/100 révélant une exclusion scolaire massive violant l'Article 26 de la DUDH et l'Article 28 de la Convention des Droits de l'Enfant", "Barrière de genre à l'éducation (82.0/100) — les fermetures d'écoles dans le Sahel affectent disproportionnellement les filles pour lesquelles la menace djihadiste crée des obstacles additionnels à la scolarisation", "Activer l'UNESCO/Rapporteur Spécial ONU sur le Droit à l'Éducation pour enquête urgente et mobiliser le Fonds UNICEF d'Éducation en Situation d'Urgence (ESU) pour rétablir l'accès scolaire"], estimated_right_to_education_index: 8.53, last_updated: "2026-06-20" },
    { id: "RE-004", name: "Nigeria/Nord — 10.5M Enfants Hors École, Boko Haram Chibok 276 & Pauvreté Structurelle", country: "Afrique de l'Ouest", sector: "Nigeria 10.5M Enfants Hors École Plus Grand Monde, Boko Haram 276 Lycéennes Chibok 2014, ASCE Nord Nigeria & Pauvreté Structurelle Barrières Éducation", composite_score: 82.25, school_exclusion_rate_score: 82.0, gender_education_barrier_score: 80.0, quality_infrastructure_failure_score: 85.0, conflict_education_destruction_score: 82.0, risk_level: "critique", primary_pattern: "defaillance_infrastructure_qualite", key_signals: ["Violation du droit à l'éducation documentée — Nigeria/Nord avec score composite 82.25/100 révélant une exclusion scolaire massive violant l'Article 26 de la DUDH et l'Article 28 de la Convention des Droits de l'Enfant", "Barrière de genre à l'éducation (80.0/100) — l'enlèvement de 276 lycéennes de Chibok par Boko Haram en 2014 symbolise la violence anti-éducation des filles dans le nord du Nigeria", "Activer l'UNESCO/Rapporteur Spécial ONU sur le Droit à l'Éducation pour enquête urgente et mobiliser le Fonds UNICEF d'Éducation en Situation d'Urgence (ESU) pour rétablir l'accès scolaire"], estimated_right_to_education_index: 8.23, last_updated: "2026-06-20" },
    { id: "RE-005", name: "Pakistan/FATA-Baloutchistan — 20M Enfants Hors École, Filles Zones Tribales & Madrasa", country: "Asie du Sud", sector: "Pakistan 20M Enfants Hors École Statistique Mondiale, Filles Zones Tribales FATA/Baloutchistan Accès Limité, Madrasa Éducation Formelle Gap & Malala Yousafzai Cas Emblématique", composite_score: 54.0, school_exclusion_rate_score: 55.0, gender_education_barrier_score: 58.0, quality_infrastructure_failure_score: 52.0, conflict_education_destruction_score: 50.0, risk_level: "élevé", primary_pattern: "barriere_genre_education", key_signals: ["Violation du droit à l'éducation documentée — Pakistan/FATA-Baloutchistan avec score composite 54.0/100 révélant une exclusion scolaire élevée notamment pour les filles dans les zones tribales violant la CDE", "Barrière de genre à l'éducation (58.0/100) — l'attentat contre Malala Yousafzai en 2012 et les restrictions aux filles dans les zones tribales illustrent la violence systémique contre l'éducation des filles au Pakistan", "Augmenter substantiellement le budget éducatif du Pakistan (actuellement <2% PIB) et renforcer la protection des enseignants et des élèves dans les zones tribales FATA/Baloutchistan"], estimated_right_to_education_index: 5.4, last_updated: "2026-06-20" },
    { id: "RE-006", name: "Soudan/Gaza — 1M+ Enfants Déplacés Sans École, RSF Attaques & Khartoum Destructions", country: "Afrique de l'Est/MENA", sector: "Soudan 19M Enfants Hors École Post-Conflit 2023, RSF Attaques Écoles Khartoum, Gaza 600 000 Enfants Sans École 2024 & GCPEA Rapport Attaques Éducation", composite_score: 53.1, school_exclusion_rate_score: 52.0, gender_education_barrier_score: 48.0, quality_infrastructure_failure_score: 58.0, conflict_education_destruction_score: 55.0, risk_level: "élevé", primary_pattern: "defaillance_infrastructure_qualite", key_signals: ["Violation du droit à l'éducation documentée — Soudan/Gaza avec score composite 53.1/100 révélant des destructions d'établissements scolaires par des parties au conflit violant la Déclaration sur la Sécurité dans les Écoles (SSI)", "Barrière de genre à l'éducation (48.0/100) — les destructions d'écoles au Soudan et à Gaza affectent des millions d'enfants déplacés dont une majorité de filles sans accès à l'éducation de remplacement", "Appliquer la Déclaration sur la Sécurité dans les Écoles (SSI) et exiger la protection des établissements éducatifs comme biens protégés par le droit international humanitaire coutumier"], estimated_right_to_education_index: 5.31, last_updated: "2026-06-20" },
    { id: "RE-007", name: "Haïti/Gangs — 700 000 Enfants Hors École, Contrôle Territorial Gangs & Instabilité", country: "Caraïbes", sector: "Haïti 700 000 Enfants Hors École 2024 UNICEF, Gangs Contrôle 80% Port-au-Prince, Écoles Converties Bases & Enseignants Exilés Insécurité", composite_score: 29.0, school_exclusion_rate_score: 30.0, gender_education_barrier_score: 28.0, quality_infrastructure_failure_score: 32.0, conflict_education_destruction_score: 25.0, risk_level: "modéré", primary_pattern: "defaillance_infrastructure_qualite", key_signals: ["Exclusion scolaire significative en Haïti liée à l'insécurité — 700 000 enfants hors école suite au contrôle territorial des gangs sur 80% de Port-au-Prince violant les droits éducatifs garantis par la CDE", "Défaillance d'infrastructure qualité (32.0/100) — la conversion d'écoles en bases de gangs constitue une violation de la Déclaration sur la Sécurité dans les Écoles (SSI) endossée par Haïti", "Prioriser la restauration de l'accès scolaire dans le plan d'intervention humanitaire haïtien et protéger les établissements éducatifs dans les accords de transition politique incluant le Conseil Présidentiel de Transition"], estimated_right_to_education_index: 2.9, last_updated: "2026-06-20" },
    { id: "RE-008", name: "UNESCO/SDG4 — ODD4 Éducation Qualité, CDE Art 28 & Education Cannot Wait Fonds", country: "Global", sector: "UNESCO ODD4 Éducation Qualité Inclusive 2030, CDE Article 28 Droit Éducation, Education Cannot Wait Fonds Urgence & Rapporteur Spécial ONU Droit Éducation", composite_score: 4.45, school_exclusion_rate_score: 5.0, gender_education_barrier_score: 4.0, quality_infrastructure_failure_score: 3.0, conflict_education_destruction_score: 6.0, risk_level: "faible", primary_pattern: "destruction_ecoles_conflit", key_signals: ["UNESCO/SDG4 incarne le cadre exemplaire du droit à l'éducation — ODD4 pour une éducation de qualité inclusive et équitable d'ici 2030 et Fonds Education Cannot Wait créant une architecture de financement d'urgence", "CDE Article 28 — garantit à tout enfant le droit à l'éducation sur la base de l'égalité des chances avec obligation progressive des États de rendre l'enseignement primaire obligatoire et gratuit", "Universaliser la ratification de la Déclaration sur la Sécurité dans les Écoles (SSI) et tripler le financement du Fonds Education Cannot Wait pour atteindre les enfants dans les zones de conflit et les crises prolongées"], estimated_right_to_education_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { exclusion_scolaire_massive: 1, barriere_genre_education: 1, defaillance_infrastructure_qualite: 3, destruction_ecoles_conflit: 3 },
    top_risk_entities: ["Afghanistan/Taliban — 4M Filles Interdites École 2021, Université Fermée & Éducation Femmes", "Yémen/Conflit — 8M Enfants Hors École, 2 400 Écoles Détruites & Enseignants Non-Payés", "Mali/Burkina Faso — 1M Enfants Hors École, 1 200+ Écoles Fermées & Djihadistes Menaces"],
    critical_alerts: ["Afghanistan/Taliban: exclusion scolaire massive", "Yémen/Conflit: destruction écoles conflit", "Mali/Burkina Faso: destruction écoles conflit", "Nigeria/Nord: défaillance infrastructure qualité"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "right_to_education",
    confidence_score: 0.86,
    data_sources: ["unesco_global_education_monitoring_report", "unicef_out_of_school_children_database", "global_coalition_to_protect_education_from_attack_gcpea"],
    entities,
    avg_estimated_right_to_education_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
