import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[religious-law-lgbtq-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(await sealResponse(MOCK));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/religious-law-lgbtq-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(await sealResponse(data));
  } catch {
    return NextResponse.json(await sealResponse(MOCK), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "RLLR-001", name: "Iran/Peine De Mort Homosexualité Droit Islamique", country: "MENA", sector: "Peine Mort Homosexualité Droit Islamique, 4 000 Exécutés Depuis 1979, Khamenei Fatwa Anti-LGBT & Opérations Police Morale 2022 Mahsa", sharia_apostasy_lgbtq_death_penalty_score: 99.0, conversion_therapy_state_sanctioned_scale_score: 95.0, religious_institution_political_power_rights_rollback_score: 98.0, lgbtq_asylum_protection_deficit_score: 96.0, composite_score: 97.05, risk_level: "critique", primary_pattern: "peine_mort_droit_religieux_lgbtq", key_signals: ["Peine de mort pour homosexualité de Iran/Peine De Mort Homosexualité Droit Islamique — les lois fondées sur l'interprétation religieuse condamnent à mort les personnes LGBTQ+, violant les articles 3, 5 et 7 de la DUDH et le Protocole de l'ONU 2014", "Thérapies de conversion étatiques — pratiques condamnées par l'ONU comme torture (A/HRC/44/53) imposées aux personnes LGBTQ+ sous autorité religieuse avec soutien légal de l'État, causant des traumatismes psychologiques graves", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires"], estimated_religious_law_lgbtq_rights_index: 9.71, last_updated: "2026-06-21" },
    { entity_id: "RLLR-002", name: "Arabie Saoudite/Charia LGBT Châtiments Corporels", country: "MENA", sector: "Charia Punition Mort Homosexualité, Fouet & Prison, CPVPV Police Morale, Zéro ONG LGBT Tolérée & Vision 2030 Façade Sans Droits", sharia_apostasy_lgbtq_death_penalty_score: 97.0, conversion_therapy_state_sanctioned_scale_score: 90.0, religious_institution_political_power_rights_rollback_score: 96.0, lgbtq_asylum_protection_deficit_score: 92.0, composite_score: 94.15, risk_level: "critique", primary_pattern: "peine_mort_droit_religieux_lgbtq", key_signals: ["Peine de mort pour homosexualité de Arabie Saoudite/Charia LGBT Châtiments Corporels — les lois fondées sur l'interprétation religieuse condamnent à mort les personnes LGBTQ+, violant les articles 3, 5 et 7 de la DUDH et le Protocole de l'ONU 2014", "Thérapies de conversion étatiques — pratiques condamnées par l'ONU comme torture (A/HRC/44/53) imposées aux personnes LGBTQ+ sous autorité religieuse avec soutien légal de l'État, causant des traumatismes psychologiques graves", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires"], estimated_religious_law_lgbtq_rights_index: 9.42, last_updated: "2026-06-21" },
    { entity_id: "RLLR-003", name: "Afghanistan/Taliban Charia Totale LGBTQ Mort", country: "Asie Centrale", sector: "Taliban 2021 Retour, Charia Intégrale Rétablie, LGBT Exécutions Publiques, Toutes ONGs LGBT Dissoutes & 50+ Arrestations Documentées UNHCR", sharia_apostasy_lgbtq_death_penalty_score: 99.0, conversion_therapy_state_sanctioned_scale_score: 92.0, religious_institution_political_power_rights_rollback_score: 99.0, lgbtq_asylum_protection_deficit_score: 95.0, composite_score: 96.45, risk_level: "critique", primary_pattern: "pouvoir_religieux_retrogression_droits", key_signals: ["Peine de mort pour homosexualité de Afghanistan/Taliban Charia Totale LGBTQ Mort — les lois fondées sur l'interprétation religieuse condamnent à mort les personnes LGBTQ+, violant les articles 3, 5 et 7 de la DUDH et le Protocole de l'ONU 2014", "Thérapies de conversion étatiques — pratiques condamnées par l'ONU comme torture (A/HRC/44/53) imposées aux personnes LGBTQ+ sous autorité religieuse avec soutien légal de l'État, causant des traumatismes psychologiques graves", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires"], estimated_religious_law_lgbtq_rights_index: 9.65, last_updated: "2026-06-21" },
    { entity_id: "RLLR-004", name: "Ouganda/Anti-Homosexuality Act Peine Mort", country: "Afrique de l'Est", sector: "Anti-Homosexuality Act 2023 Peine Mort Aggravée, Museveni Signature, Lobbying Évangéliques USA, 50+ Arrestations & Discrimination Emploi/Logement", sharia_apostasy_lgbtq_death_penalty_score: 92.0, conversion_therapy_state_sanctioned_scale_score: 82.0, religious_institution_political_power_rights_rollback_score: 94.0, lgbtq_asylum_protection_deficit_score: 88.0, composite_score: 89.3, risk_level: "critique", primary_pattern: "pouvoir_religieux_retrogression_droits", key_signals: ["Peine de mort pour homosexualité de Ouganda/Anti-Homosexuality Act Peine Mort — les lois fondées sur l'interprétation religieuse condamnent à mort les personnes LGBTQ+, violant les articles 3, 5 et 7 de la DUDH et le Protocole de l'ONU 2014", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires", "Déficit de protection des réfugiés LGBTQ+ — les personnes fuyant les persécutions religieuses n'ont pas accès aux procédures d'asile adaptées, violant la Convention de 1951 et les Principes de Yogyakarta"], estimated_religious_law_lgbtq_rights_index: 8.93, last_updated: "2026-06-21" },
    { entity_id: "RLLR-005", name: "Russie/Loi Propagande LGBT Église Orthodoxe", country: "Europe de l'Est", sector: "Loi Propagande LGBT 2013 Étendue 2023 Tous Âges, Église Orthodoxe Influence État, Organisations LGBT Interdites & Pride Criminalisée", sharia_apostasy_lgbtq_death_penalty_score: 42.0, conversion_therapy_state_sanctioned_scale_score: 55.0, religious_institution_political_power_rights_rollback_score: 60.0, lgbtq_asylum_protection_deficit_score: 48.0, composite_score: 51.35, risk_level: "élevé", primary_pattern: "pouvoir_religieux_retrogression_droits", key_signals: ["Criminalisation religieuse de Russie/Loi Propagande LGBT Église Orthodoxe — les lois inspirées de l'interprétation religieuse pénalisent l'identité et l'expression LGBTQ+, exposant les personnes à l'emprisonnement et aux violences d'État", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires", "Déficit de protection des réfugiés LGBTQ+ — les personnes fuyant les persécutions religieuses n'ont pas accès aux procédures d'asile adaptées, violant la Convention de 1951 et les Principes de Yogyakarta"], estimated_religious_law_lgbtq_rights_index: 5.14, last_updated: "2026-06-21" },
    { entity_id: "RLLR-006", name: "Pologne/Zones Sans LGBT Église Catholique", country: "Europe Centrale", sector: "100+ Zones Sans LGBT 2019-2022, PiS Idéologie Catholique, Jurisprudence CJUE 2022 Contre Discriminations & Retrait Zones Sous Pression EU 2022", sharia_apostasy_lgbtq_death_penalty_score: 25.0, conversion_therapy_state_sanctioned_scale_score: 40.0, religious_institution_political_power_rights_rollback_score: 62.0, lgbtq_asylum_protection_deficit_score: 35.0, composite_score: 40.25, risk_level: "élevé", primary_pattern: "pouvoir_religieux_retrogression_droits", key_signals: ["Criminalisation religieuse de Pologne/Zones Sans LGBT Église Catholique — les lois inspirées de l'interprétation religieuse pénalisent l'identité et l'expression LGBTQ+, exposant les personnes à l'emprisonnement et aux violences d'État", "Retrogression institutionnelle — les institutions religieuses détenant un pouvoir politique direct bloquent activement les réformes de protection des droits LGBTQ+ et soutiennent les législations discriminatoires"], estimated_religious_law_lgbtq_rights_index: 4.03, last_updated: "2026-06-21" },
    { entity_id: "RLLR-007", name: "USA/Evangelical Anti-LGBT Bills 2023-2024", country: "Amérique du Nord", sector: "580+ Bills Anti-LGBT 2023 États, Thérapies Conversion Légales 20+ États, Drag Ban Tennessee & Idéologie Évangélique SCOTUS Décisions", sharia_apostasy_lgbtq_death_penalty_score: 15.0, conversion_therapy_state_sanctioned_scale_score: 35.0, religious_institution_political_power_rights_rollback_score: 40.0, lgbtq_asylum_protection_deficit_score: 22.0, composite_score: 28.15, risk_level: "modéré", primary_pattern: "pouvoir_religieux_retrogression_droits", key_signals: ["Protection relative des droits LGBTQ+ de USA/Evangelical Anti-LGBT Bills 2023-2024 — séparation effective de l'État et des institutions religieuses sur les droits civils"], estimated_religious_law_lgbtq_rights_index: 2.82, last_updated: "2026-06-21" },
    { entity_id: "RLLR-008", name: "Canada/Mariage Égal & Laïcité Protection LGBTQ", country: "Amérique du Nord", sector: "Mariage Égal 2005, Loi C-4 Thérapies Conversion Interdites 2022, IRPA Protection Réfugiés LGBT & Charte Droits Protection Robuste", sharia_apostasy_lgbtq_death_penalty_score: 3.0, conversion_therapy_state_sanctioned_scale_score: 4.0, religious_institution_political_power_rights_rollback_score: 5.0, lgbtq_asylum_protection_deficit_score: 4.0, composite_score: 3.95, risk_level: "faible", primary_pattern: "peine_mort_droit_religieux_lgbtq", key_signals: ["Protection relative des droits LGBTQ+ de Canada/Mariage Égal & Laïcité Protection LGBTQ — séparation effective de l'État et des institutions religieuses sur les droits civils"], estimated_religious_law_lgbtq_rights_index: 0.4, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { peine_mort_droit_religieux_lgbtq: 3, therapies_conversion_etatiques: 0, pouvoir_religieux_retrogression_droits: 5, deficit_asile_protection_lgbtq: 0 },
    top_risk_entities: ["Iran/Peine De Mort Homosexualité Droit Islamique", "Afghanistan/Taliban Charia Totale LGBTQ Mort", "Arabie Saoudite/Charia LGBT Châtiments Corporels", "Ouganda/Anti-Homosexuality Act Peine Mort"],
    critical_alerts: ["Iran: peine_mort_droit_religieux_lgbtq", "Afghanistan: pouvoir_religieux_retrogression_droits", "Arabie Saoudite: peine_mort_droit_religieux_lgbtq", "Ouganda: pouvoir_religieux_retrogression_droits"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "religious_law_lgbtq_rights",
    confidence_score: 0.88,
    data_sources: ["ilga_world_state_sponsored_homophobia_2023", "rainbow_europe_index_2023", "human_rights_watch_lgbtq_report_2023", "outright_action_international_religion_rights"],
    entities,
    avg_estimated_religious_law_lgbtq_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
