import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[forced-sterilization-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Forced Sterilization Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/forced-sterilization-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Forced Sterilization Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Forced Sterilization Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "FS-001", name: "Chine/Ouïghours — Stérilisations Forcées Xinjiang & DIU Imposés", country: "Asie", sector: "DIU Forcés 80% Femmes Xinjiang, Stérilisations Sans Consentement, Taux Natalité -84% & ONU Investigation 2022", composite_score: 93.6, coercive_reproductive_control_score: 95.0, ethnic_targeted_sterilization_score: 98.0, state_medical_complicity_score: 92.0, sterilization_impunity_score: 88.0, risk_level: "critique", primary_pattern: "sterilisation_genocide_ethnique", key_signals: ["Stérilisation forcée critique de Chine/Ouïghours — programme étatique délibéré de contrôle reproductif ciblant une minorité ethnique dans l'objectif de réduire sa population, constitutif de génocide", "Crime contre l'humanité reproductif — les stérilisations forcées constituent un crime contre l'humanité selon l'Article 7 du Statut de Rome avec responsabilité pénale individuelle", "Violence reproductive institutionnalisée — le personnel médical contraint de participer aux stérilisations forcées sous peine de sanctions crée une complicité médicale systémique"], estimated_forced_sterilization_index: 9.36, last_updated: "2026-06-20" },
    { id: "FS-002", name: "Inde/Campagnes Stérilisation — Quotas Femmes Pauvres & Décès", country: "Asie du Sud", sector: "8M Stérilisées/An Programme National, 16 Décès Chhattisgarh 2014, Quotas Médecins Ruraux & Femmes Dalits Ciblées", composite_score: 84.15, coercive_reproductive_control_score: 88.0, ethnic_targeted_sterilization_score: 82.0, state_medical_complicity_score: 85.0, sterilization_impunity_score: 80.0, risk_level: "critique", primary_pattern: "controle_reproductif_etatique", key_signals: ["Contrôle reproductif étatique critique d'Inde — programme de stérilisation à grande échelle avec coercition documentée ciblant les femmes des castes inférieures et communautés rurales", "Crime contre l'humanité reproductif — les stérilisations forcées constituent un crime contre l'humanité selon l'Article 7 du Statut de Rome avec responsabilité pénale individuelle", "Violence reproductive institutionnalisée — le personnel médical contraint de participer aux stérilisations forcées sous peine de sanctions crée une complicité médicale systémique"], estimated_forced_sterilization_index: 8.42, last_updated: "2026-06-20" },
    { id: "FS-003", name: "USA/ICE — Stérilisations Détenues Immigration Georgie 2020", country: "Amérique du Nord", sector: "Irwin County Hysterectomies Non Consenties, Médecin Reaper Surnommé, DHS Investigation & Femmes Latinas Ciblées", composite_score: 82.5, coercive_reproductive_control_score: 80.0, ethnic_targeted_sterilization_score: 82.0, state_medical_complicity_score: 88.0, sterilization_impunity_score: 80.0, risk_level: "critique", primary_pattern: "complicite_medicale_systematique", key_signals: ["Complicité médicale systémique de USA/ICE — personnel médical en milieu de détention pratiquant des procédures gynécologiques non consenties sur des femmes privées de liberté", "Crime contre l'humanité reproductif — les stérilisations forcées constituent un crime contre l'humanité selon l'Article 7 du Statut de Rome avec responsabilité pénale individuelle", "Violence reproductive institutionnalisée — le personnel médical contraint de participer aux stérilisations forcées sous peine de sanctions crée une complicité médicale systémique"], estimated_forced_sterilization_index: 8.25, last_updated: "2026-06-20" },
    { id: "FS-004", name: "Pérou/Fujimori — Opération Planification Familiale 1996-2000", country: "Amérique du Sud", sector: "272 000 Ligatures Trompes, 22 000 Vasectomies, Quechua/Aymara Ciblés, Fujimori Condamné 2023 & Enquête Pénale", composite_score: 79.85, coercive_reproductive_control_score: 82.0, ethnic_targeted_sterilization_score: 78.0, state_medical_complicity_score: 75.0, sterilization_impunity_score: 85.0, risk_level: "critique", primary_pattern: "sterilisation_forcee_active", key_signals: ["Stérilisation forcée active de Pérou/Fujimori — programme gouvernemental de stérilisations massives ciblant les populations indigènes rurales sous couvert de planification familiale volontaire", "Crime contre l'humanité reproductif — les stérilisations forcées constituent un crime contre l'humanité selon l'Article 7 du Statut de Rome avec responsabilité pénale individuelle", "Violence reproductive institutionnalisée — le personnel médical contraint de participer aux stérilisations forcées sous peine de sanctions crée une complicité médicale systémique"], estimated_forced_sterilization_index: 7.99, last_updated: "2026-06-20" },
    { id: "FS-005", name: "Slovaquie/Roms — Stérilisations Hospitalières Sans Consentement", country: "Europe", sector: "Rapports CEDH Condamnations, Femmes Roms Stérilisées Post-Partum, Formulaires Signés Accouchement & Impunité Médicale", composite_score: 56.0, coercive_reproductive_control_score: 55.0, ethnic_targeted_sterilization_score: 58.0, state_medical_complicity_score: 52.0, sterilization_impunity_score: 60.0, risk_level: "élevé", primary_pattern: "sterilisation_forcee_active", key_signals: ["Stérilisations discriminatoires de Slovaquie/Roms — pratiques hospitalières documentées de stérilisation post-partum sans consentement éclairé ciblant la minorité rom", "Discrimination reproductive — inégalités d'accès aux soins reproductifs et pratiques coercitives visant des communautés marginalisées sans recours judiciaire effectif", "Impunité médicale persistante — absence de sanctions disciplinaires ou pénales pour le personnel médical ayant pratiqué des procédures reproductives non consenties"], estimated_forced_sterilization_index: 5.6, last_updated: "2026-06-20" },
    { id: "FS-006", name: "Namibie/Femmes HIV — Stérilisations Positives Sans Accord", country: "Afrique Australe", sector: "Jugement Cour Suprême 2012, Femmes Séropositives Stérilisées, Hôpitaux Publics Pratiques & Namibia Women's Health Network", composite_score: 51.6, coercive_reproductive_control_score: 50.0, ethnic_targeted_sterilization_score: 52.0, state_medical_complicity_score: 48.0, sterilization_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "complicite_medicale_systematique", key_signals: ["Discrimination reproductive médicale de Namibie — stérilisations coercitives de femmes séropositives fondées sur le statut HIV, constituant une discrimination sanitaire grave", "Discrimination reproductive — inégalités d'accès aux soins reproductifs et pratiques coercitives visant des communautés marginalisées sans recours judiciaire effectif", "Impunité médicale persistante — absence de sanctions disciplinaires ou pénales pour le personnel médical ayant pratiqué des procédures reproductives non consenties"], estimated_forced_sterilization_index: 5.16, last_updated: "2026-06-20" },
    { id: "FS-007", name: "Suède/Historique — Programme Eugénique 1935-1975 & 63 000 Cas", country: "Europe du Nord", sector: "63 000 Stérilisations Programme Eugenique, Loi 1934, Femmes Handicapées/Marginales Ciblées & Réparations 1999", composite_score: 29.65, coercive_reproductive_control_score: 28.0, ethnic_targeted_sterilization_score: 25.0, state_medical_complicity_score: 32.0, sterilization_impunity_score: 35.0, risk_level: "modéré", primary_pattern: "sterilisation_forcee_active", key_signals: ["Héritage eugénique de Suède — programme historique de stérilisations forcées avec reconnaissance officielle et réparations partielles, risque résiduel de dérive discriminatoire en contexte de crise", "Vigilance reproductive requise — sociétés en transition démocratique où des pratiques coercitives isolées persistent malgré un cadre juridique protecteur formellement établi", "Mémoire institutionnelle défaillante — absence d'éducation systématique sur l'histoire des abus reproductifs facilitant le risque de répétition dans des contextes de vulnérabilité sociale"], estimated_forced_sterilization_index: 2.97, last_updated: "2026-06-20" },
    { id: "FS-008", name: "OMS/UNFPA — Droits Reproductifs & Consentement Éclairé", country: "Global", sector: "Directive OMS 2014 Stérilisation Volontaire, UNFPA Droits Reproductifs, CEDAW Article 16 & Standards Consentement", composite_score: 4.45, coercive_reproductive_control_score: 5.0, ethnic_targeted_sterilization_score: 4.0, state_medical_complicity_score: 3.0, sterilization_impunity_score: 6.0, risk_level: "faible", primary_pattern: "droits_reproductifs_exemplaires", key_signals: ["OMS/UNFPA incarne l'exemplarité des droits reproductifs — consentement éclairé garanti, égalité d'accès aux soins reproductifs et protection légale contre toute coercition médicale", "Cadre normatif protecteur — CEDAW, Protocole de Maputo et standards OMS créant des obligations contraignantes pour les États en matière de droits reproductifs", "Modèle de santé reproductive à exporter — formation médicale au consentement, mécanismes de plainte accessibles et sanctions effectives contre les abus reproductifs"], estimated_forced_sterilization_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { sterilisation_genocide_ethnique: 1, controle_reproductif_etatique: 1, complicite_medicale_systematique: 2, sterilisation_forcee_active: 3, droits_reproductifs_exemplaires: 1 },
    top_risk_entities: ["Chine/Ouïghours — Stérilisations Forcées Xinjiang & DIU Imposés", "Inde/Campagnes Stérilisation — Quotas Femmes Pauvres & Décès", "USA/ICE — Stérilisations Détenues Immigration Georgie 2020"],
    critical_alerts: ["Chine/Ouïghours: stérilisation génocide ethnique", "Inde: contrôle reproductif étatique", "USA/ICE: complicité médicale systématique", "Pérou/Fujimori: stérilisation forcée active"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "forced_sterilization",
    confidence_score: 0.82,
    data_sources: ["un_special_rapporteur_reproductive_rights", "hrw_forced_sterilization_reports", "unfpa_state_world_population"],
    entities,
    avg_estimated_forced_sterilization_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
