import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[debt-bondage-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Debt Bondage Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/debt-bondage-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Debt Bondage Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Debt Bondage Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "DB-001", name: "Inde/Briqueteries — Kamaiya/Haliya Bihar/UP, Advance System & 8M Bondés Estimés", country: "Asie du Sud", sector: "8M Personnes Travail Bonded Inde Estimés Walk Free, Briqueteries Bihar/UP Avances Non-Remboursables, Kamaiya Tharu Nepal Frontière & Bonded Labour Abolition Act 1976 Non-Appliqué", composite_score: 88.65, bonded_labor_prevalence_score: 90.0, debt_coercion_mechanism_score: 88.0, legal_protection_failure_score: 85.0, intergenerational_transmission_score: 92.0, risk_level: "critique", primary_pattern: "transmission_intergenerationnelle", key_signals: ["Esclavage par endettement documenté — Inde/Briqueteries avec score composite 88.65/100 révélant des mécanismes de servitude pour dettes violant la Convention sur l'Esclavage de 1926 et le Protocole de Palerme", "Transmission intergénérationnelle (92.0/100) — les dettes héréditaires perpétuent la servitude sur plusieurs générations, constituant une forme d'esclavage intergénérationnel reconnue par les Principes ONU", "Activer le Rapporteur Spécial ONU sur les formes contemporaines d'esclavage pour enquête urgente et appliquer les Principes Directeurs ONU sur les Entreprises et les Droits de l'Homme aux chaînes d'approvisionnement impliquées"], estimated_debt_bondage_index: 8.87, last_updated: "2026-06-20" },
    { id: "DB-002", name: "Pakistan/Briques-Agriculture — Peshgi System 4.5M Bondés Sindh & Punjab", country: "Asie du Sud", sector: "Peshgi Advances System Pakistan Briqueteries/Agriculture 4.5M Bondés Estimés, Sindh Maweshi Bonded Labor, HRCP Rapports & Bonded Labour System Abolition Act 1992 Non-Appliqué", composite_score: 86.85, bonded_labor_prevalence_score: 85.0, debt_coercion_mechanism_score: 90.0, legal_protection_failure_score: 85.0, intergenerational_transmission_score: 88.0, risk_level: "critique", primary_pattern: "mecanisme_coercition_dette", key_signals: ["Esclavage par endettement documenté — Pakistan/Briques-Agriculture avec score composite 86.85/100 révélant des mécanismes de servitude pour dettes violant la Convention sur l'Esclavage de 1926 et le Protocole de Palerme", "Transmission intergénérationnelle (88.0/100) — les dettes héréditaires perpétuent la servitude sur plusieurs générations, constituant une forme d'esclavage intergénérationnel reconnue par les Principes ONU", "Activer le Rapporteur Spécial ONU sur les formes contemporaines d'esclavage pour enquête urgente et appliquer les Principes Directeurs ONU sur les Entreprises et les Droits de l'Homme aux chaînes d'approvisionnement impliquées"], estimated_debt_bondage_index: 8.69, last_updated: "2026-06-20" },
    { id: "DB-003", name: "Népal/Haruwa-Charuwa — 50 000 Libérés 2008 & Réhabilitation Incomplète", country: "Asie du Sud", sector: "Haruwa-Charuwa Madhesh 50 000 Libérés Formellement 2008, Réhabilitation Terrain Insuffisante, Retour Informel Servitude & Kamaiya Liberation 2000 Progrès Mitigés", composite_score: 86.05, bonded_labor_prevalence_score: 88.0, debt_coercion_mechanism_score: 85.0, legal_protection_failure_score: 88.0, intergenerational_transmission_score: 82.0, risk_level: "critique", primary_pattern: "prevalence_travail_bonded", key_signals: ["Esclavage par endettement documenté — Népal/Haruwa-Charuwa avec score composite 86.05/100 révélant des mécanismes de servitude pour dettes violant la Convention sur l'Esclavage de 1926 et le Protocole de Palerme", "Transmission intergénérationnelle (82.0/100) — les dettes héréditaires perpétuent la servitude sur plusieurs générations, constituant une forme d'esclavage intergénérationnel reconnue par les Principes ONU", "Activer le Rapporteur Spécial ONU sur les formes contemporaines d'esclavage pour enquête urgente et appliquer les Principes Directeurs ONU sur les Entreprises et les Droits de l'Homme aux chaînes d'approvisionnement impliquées"], estimated_debt_bondage_index: 8.61, last_updated: "2026-06-20" },
    { id: "DB-004", name: "Bangladesh/Dadon — Pêcheurs Bateaux Endettés, Avances Captivité & Travail Maritime", country: "Asie du Sud", sector: "Dadon System Bangladesh Pêcheurs Bateaux, Avances Armateurs Non-Remboursables, Travail Maritime Bondé & Inspection Maritime Sans Mécanisme Anti-Servitude", composite_score: 82.85, bonded_labor_prevalence_score: 82.0, debt_coercion_mechanism_score: 85.0, legal_protection_failure_score: 80.0, intergenerational_transmission_score: 85.0, risk_level: "critique", primary_pattern: "mecanisme_coercition_dette", key_signals: ["Esclavage par endettement documenté — Bangladesh/Dadon avec score composite 82.85/100 révélant des mécanismes de servitude pour dettes violant la Convention sur l'Esclavage de 1926 et le Protocole de Palerme", "Transmission intergénérationnelle (85.0/100) — les dettes héréditaires perpétuent la servitude sur plusieurs générations, constituant une forme d'esclavage intergénérationnel reconnue par les Principes ONU", "Activer le Rapporteur Spécial ONU sur les formes contemporaines d'esclavage pour enquête urgente et appliquer les Principes Directeurs ONU sur les Entreprises et les Droits de l'Homme aux chaînes d'approvisionnement impliquées"], estimated_debt_bondage_index: 8.29, last_updated: "2026-06-20" },
    { id: "DB-005", name: "Pérou/Amazonie — Habilitación Indigènes Bois, Endettement Extraction & Impunité", country: "Amérique du Sud", sector: "Habilitación System Amazonie Péruvienne Bois/Or, Communautés Indigènes Endettées Intermédiaires, Défenseurs Menacés & MINEM Sans Mécanisme Anti-Bondage", composite_score: 54.0, bonded_labor_prevalence_score: 55.0, debt_coercion_mechanism_score: 52.0, legal_protection_failure_score: 58.0, intergenerational_transmission_score: 50.0, risk_level: "élevé", primary_pattern: "defaillance_protection_juridique", key_signals: ["Esclavage par endettement documenté — Pérou/Amazonie avec score composite 54.0/100 révélant des mécanismes d'endettement captif ciblant les communautés autochtones dans les secteurs extractifs", "Transmission intergénérationnelle (50.0/100) — le système Habilitación crée des cycles d'endettement multigénérationnels pour les communautés autochtones amazonniennes privées de recours juridiques", "Renforcer les mécanismes de protection contre le travail bonded dans la filière bois amazonienne péruvienne et soutenir les organisations autochtones de défense contre l'endettement captif"], estimated_debt_bondage_index: 5.4, last_updated: "2026-06-20" },
    { id: "DB-006", name: "Ghana/Trokosi — Servitude Religieuse Filles, Vestal Virgins & Compensation Dettes Familiales", country: "Afrique de l'Ouest", sector: "Trokosi Pratique Ghana/Bénin/Togo Filles Livrées Temples Compensation Péchés Familiaux, Esclavage Religieux, FIAN International Documentation & Loi Ghana 1998 Application Partielle", composite_score: 52.25, bonded_labor_prevalence_score: 52.0, debt_coercion_mechanism_score: 55.0, legal_protection_failure_score: 50.0, intergenerational_transmission_score: 52.0, risk_level: "élevé", primary_pattern: "mecanisme_coercition_dette", key_signals: ["Esclavage par endettement documenté — Ghana/Trokosi avec score composite 52.25/100 révélant une pratique de servitude religieuse utilisée comme mécanisme de compensation de dettes familiales violant les droits des filles", "Transmission intergénérationnelle (52.0/100) — le système Trokosi impose aux filles de compenser les dettes morales de leurs ancêtres, perpétuant une forme d'esclavage héréditaire par la dette familiale", "Appliquer effectivement la loi criminelle ghanéenne de 1998 contre la pratique Trokosi et financer les programmes de réhabilitation des femmes survivantes en collaboration avec les communautés religieuses traditionnelles"], estimated_debt_bondage_index: 5.23, last_updated: "2026-06-20" },
    { id: "DB-007", name: "Moldavie/Travailleurs Migrants — Dettes Recrutement, Trafic & Remboursements Salaires", country: "Europe de l'Est", sector: "Travailleurs Migrants Moldaves Dettes Agences Recrutement UE, Passeports Confisqués, OIM Documentation & Directive EU Anti-Traite Application Partielle", composite_score: 29.6, bonded_labor_prevalence_score: 30.0, debt_coercion_mechanism_score: 28.0, legal_protection_failure_score: 32.0, intergenerational_transmission_score: 28.0, risk_level: "modéré", primary_pattern: "defaillance_protection_juridique", key_signals: ["Dettes de recrutement documentées en Moldavie — travailleurs migrants endettés par des frais de recrutement abusifs conduisant à des situations proches du travail forcé dans les pays de destination UE", "Lacune juridique de protection — la faiblesse des mécanismes de contrôle des agences de recrutement permet des pratiques d'endettement captif malgré la Directive UE 2011/36 sur la traite des êtres humains", "Renforcer les contrôles sur les agences de recrutement en Moldavie et dans les pays UE de destination et appliquer la Directive UE Anti-Traite pour les cas de travail forcé par endettement"], estimated_debt_bondage_index: 2.96, last_updated: "2026-06-20" },
    { id: "DB-008", name: "OIT/Convention Esclavage — Protocole 2014 C29, SDG 8.7 & Rapporteur ONU Esclavage", country: "Global", sector: "OIT Protocole 2014 Convention Travail Forcé C29, Rapporteur Spécial ONU Formes Contemporaines Esclavage, Walk Free Foundation Index & Convention Esclavage 1926 Cadre Fondateur", composite_score: 4.45, bonded_labor_prevalence_score: 5.0, debt_coercion_mechanism_score: 4.0, legal_protection_failure_score: 3.0, intergenerational_transmission_score: 6.0, risk_level: "faible", primary_pattern: "transmission_intergenerationnelle", key_signals: ["OIT/Convention Esclavage incarne le cadre exemplaire contre le travail bonded — Protocole 2014 sur le Travail Forcé et Convention de 1926 sur l'Esclavage créant des obligations contraignantes", "Protocole OIT de 2014 (P029) — étend la Convention C29 pour couvrir la traite des êtres humains, le travail servile et la servitude pour dettes comme formes contemporaines de travail forcé", "Universaliser la ratification du Protocole OIT de 2014 sur le Travail Forcé et financer le Rapporteur Spécial ONU sur les Formes Contemporaines d'Esclavage pour missions d'enquête dans les pays à haute prévalence"], estimated_debt_bondage_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { prevalence_travail_bonded: 1, mecanisme_coercition_dette: 3, defaillance_protection_juridique: 2, transmission_intergenerationnelle: 2 },
    top_risk_entities: ["Inde/Briqueteries — Kamaiya/Haliya Bihar/UP, Advance System & 8M Bondés Estimés", "Pakistan/Briques-Agriculture — Peshgi System 4.5M Bondés Sindh & Punjab", "Népal/Haruwa-Charuwa — 50 000 Libérés 2008 & Réhabilitation Incomplète"],
    critical_alerts: ["Inde/Briqueteries: transmission intergénérationnelle", "Pakistan/Briques: mécanisme coercition dette", "Népal/Haruwa-Charuwa: prévalence travail bonded", "Bangladesh/Dadon: mécanisme coercition dette"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "debt_bondage",
    confidence_score: 0.82,
    data_sources: ["ilo_global_estimates_modern_slavery_2022", "walk_free_foundation_global_slavery_index", "antislavery_international_bonded_labour_reports"],
    entities,
    avg_estimated_debt_bondage_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
