import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[biometric-surveillance-state-control-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/biometric-surveillance-state-control-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "BSSC-001", name: "Chine/SCS Crédit Social 1.4B Personnes Surveillance Totale", country: "Asie de l'Est", sector: "Système Crédit Social 1.4B Personnes, 700M Caméras CCTV, Reconnaissance Faciale Ubiquitaire, Score Comportemental & Blocage Transport 8M Fois 2019", composite_score: 90.1, mass_biometric_collection_scale_score: 92.0, facial_recognition_misidentification_harm_score: 88.0, biometric_data_misuse_rights_violation_score: 90.0, surveillance_state_chilling_effect_score: 90.0, risk_level: "critique", primary_pattern: "surveillance_biometrique_masse", key_signals: ["Surveillance biométrique de masse critique de Chine/SCS Crédit Social 1.4B Personnes Surveillance Totale — déploiement à grande échelle sans consentement ni cadre légal protecteur, permettant un contrôle étatique total des comportements et associations", "Violation systématique de la vie privée — la collecte biométrique de masse viole l'article 12 de la DUDH et l'article 17 du PIDCP, créant un État de surveillance incompatible avec les droits fondamentaux", "Effet dissuasif massif — la surveillance permanente inhibe l'exercice des libertés d'expression, d'association et de manifestation, réduisant l'espace civique disponible pour la société civile"], estimated_biometric_surveillance_state_control_index: 9.01, last_updated: "2026-06-21" },
    { id: "BSSC-002", name: "Russie/SORM Surveillance Communications Moscow 200K Caméras", country: "Europe de l'Est", sector: "SORM-3 Surveillance Totale Communications, 200.000 Caméras Moscou, Clearview AI Russe NtechLab, Dissidents Identifiés Manifestations & FSB Accès Direct", composite_score: 84.9, mass_biometric_collection_scale_score: 86.0, facial_recognition_misidentification_harm_score: 84.0, biometric_data_misuse_rights_violation_score: 82.0, surveillance_state_chilling_effect_score: 88.0, risk_level: "critique", primary_pattern: "surveillance_biometrique_masse", key_signals: ["Surveillance biométrique de masse critique de Russie/SORM Surveillance Communications Moscow 200K Caméras — déploiement à grande échelle sans consentement ni cadre légal protecteur, permettant un contrôle étatique total des comportements et associations", "Violation systématique de la vie privée — la collecte biométrique de masse viole l'article 12 de la DUDH et l'article 17 du PIDCP, créant un État de surveillance incompatible avec les droits fondamentaux", "Effet dissuasif massif — la surveillance permanente inhibe l'exercice des libertés d'expression, d'association et de manifestation, réduisant l'espace civique disponible pour la société civile"], estimated_biometric_surveillance_state_control_index: 8.49, last_updated: "2026-06-21" },
    { id: "BSSC-003", name: "Éthiopie/Surveillance Opposants Technologie Chinoise", country: "Afrique de l'Est", sector: "Technologie Surveillance Chinoise ZTE/Huawei, Opposants Oromo Identifiés, Journalistes Arrêtés Via Surveillance, Telebirr Données Biométriques & Tigré Surveillance Conflit", composite_score: 82.15, mass_biometric_collection_scale_score: 82.0, facial_recognition_misidentification_harm_score: 78.0, biometric_data_misuse_rights_violation_score: 85.0, surveillance_state_chilling_effect_score: 84.0, risk_level: "critique", primary_pattern: "collecte_donnees_sans_consentement", key_signals: ["Surveillance biométrique de masse critique de Éthiopie/Surveillance Opposants Technologie Chinoise — déploiement à grande échelle sans consentement ni cadre légal protecteur, permettant un contrôle étatique total des comportements et associations", "Violation systématique de la vie privée — la collecte biométrique de masse viole l'article 12 de la DUDH et l'article 17 du PIDCP, créant un État de surveillance incompatible avec les droits fondamentaux", "Effet dissuasif massif — la surveillance permanente inhibe l'exercice des libertés d'expression, d'association et de manifestation, réduisant l'espace civique disponible pour la société civile"], estimated_biometric_surveillance_state_control_index: 8.22, last_updated: "2026-06-21" },
    { id: "BSSC-004", name: "Inde/Aadhaar 1.3B Personnes Plus Grand Système Biométrique", country: "Asie du Sud", sector: "Aadhaar 1.3B Personnes Empreintes+Iris, Fuites UIDAI 2018, Surveillance Protestataires, Linkage Obligatoire Services Essentiels & Système Facial Aadhar 2.0", composite_score: 74.55, mass_biometric_collection_scale_score: 78.0, facial_recognition_misidentification_harm_score: 72.0, biometric_data_misuse_rights_violation_score: 75.0, surveillance_state_chilling_effect_score: 72.0, risk_level: "critique", primary_pattern: "surveillance_biometrique_masse", key_signals: ["Surveillance biométrique de masse critique de Inde/Aadhaar 1.3B Personnes Plus Grand Système Biométrique — déploiement à grande échelle sans consentement ni cadre légal protecteur, permettant un contrôle étatique total des comportements et associations", "Violation systématique de la vie privée — la collecte biométrique de masse viole l'article 12 de la DUDH et l'article 17 du PIDCP, créant un État de surveillance incompatible avec les droits fondamentaux", "Effet dissuasif massif — la surveillance permanente inhibe l'exercice des libertés d'expression, d'association et de manifestation, réduisant l'espace civique disponible pour la société civile"], estimated_biometric_surveillance_state_control_index: 7.46, last_updated: "2026-06-21" },
    { id: "BSSC-005", name: "Royaume-Uni/CCTV Londres 942K Caméras Reconnaissance Faciale", country: "Europe Occidentale", sector: "942.000 Caméras Londres, Police Met RF Controversée, Erreurs Identification 81% Faux Positifs Initial, Manifestants BLM Identifiés & Expansion Airports Biométriques", composite_score: 49.75, mass_biometric_collection_scale_score: 50.0, facial_recognition_misidentification_harm_score: 55.0, biometric_data_misuse_rights_violation_score: 48.0, surveillance_state_chilling_effect_score: 45.0, risk_level: "élevé", primary_pattern: "reconnaissance_faciale_discriminatoire", key_signals: ["Déploiement biométrique extensif de Royaume-Uni/CCTV Londres 942K Caméras Reconnaissance Faciale — systèmes de surveillance à grande échelle avec lacunes significatives de protection, exposant les populations à des risques de discrimination et d'abus", "Reconnaissance faciale discriminatoire — taux d'erreur élevés sur les personnes racisées générant des arrestations arbitraires et des biais algorithmiques documentés par des études indépendantes", "Absence de recours effectif — les victimes de surveillance illégale n'ont pas accès à des mécanismes de plainte indépendants ni à l'information sur les données collectées les concernant"], estimated_biometric_surveillance_state_control_index: 4.98, last_updated: "2026-06-21" },
    { id: "BSSC-006", name: "USA/CBP Frontières Biométrie Aéroports 260M Voyageurs", country: "Amérique du Nord", sector: "CBP Biométrie 97% Voyageurs Aéroports, ICE Accès DMV 32 États, Clearview AI 10B Photos, Pas de Loi Fédérale Biométrie & 26 États sans Réglementation", composite_score: 43.7, mass_biometric_collection_scale_score: 44.0, facial_recognition_misidentification_harm_score: 48.0, biometric_data_misuse_rights_violation_score: 42.0, surveillance_state_chilling_effect_score: 40.0, risk_level: "élevé", primary_pattern: "collecte_donnees_sans_consentement", key_signals: ["Déploiement biométrique extensif de USA/CBP Frontières Biométrie Aéroports 260M Voyageurs — systèmes de surveillance à grande échelle avec lacunes significatives de protection, exposant les populations à des risques de discrimination et d'abus", "Reconnaissance faciale discriminatoire — taux d'erreur élevés sur les personnes racisées générant des arrestations arbitraires et des biais algorithmiques documentés par des études indépendantes", "Absence de recours effectif — les victimes de surveillance illégale n'ont pas accès à des mécanismes de plainte indépendants ni à l'information sur les données collectées les concernant"], estimated_biometric_surveillance_state_control_index: 4.37, last_updated: "2026-06-21" },
    { id: "BSSC-007", name: "Brésil/Reconnaissance Faciale Rio Carnaval Erreurs", country: "Amérique du Sud", sector: "RF Rio Carnaval 2023 Erreurs Identitaires, SESP Système Nacional, 90% Population Android Données Partage, Accord Sécurité Amazon & Absence Loi Biométrie Spécifique", composite_score: 26.55, mass_biometric_collection_scale_score: 28.0, facial_recognition_misidentification_harm_score: 30.0, biometric_data_misuse_rights_violation_score: 25.0, surveillance_state_chilling_effect_score: 22.0, risk_level: "modéré", primary_pattern: "effet_dissuasif_liberte_expression", key_signals: ["Risques biométriques encadrés de Brésil/Reconnaissance Faciale Rio Carnaval Erreurs — protections légales partielles insuffisantes face à l'expansion rapide des technologies de surveillance biométrique dans les espaces publics et privés", "Lacunes réglementaires — les cadres légaux existants ne couvrent pas les nouvelles formes de collecte biométrique, créant des zones grises exploitées par les acteurs étatiques et commerciaux", "Risques d'escalade technologique — la pression sécuritaire et commerciale pousse à l'expansion des systèmes de surveillance sans évaluation d'impact sur les droits humains"], estimated_biometric_surveillance_state_control_index: 2.66, last_updated: "2026-06-21" },
    { id: "BSSC-008", name: "UE/RGPD Données Biométriques Protection Haute", country: "Europe", sector: "RGPD Art.9 Biométrie Catégorie Spéciale, AI Act Reconnaissance Faciale Publique Interdite, CEPD Supervision, Amendes Google 50M€ CNIL & Clearview Interdit EU", composite_score: 9.0, mass_biometric_collection_scale_score: 8.0, facial_recognition_misidentification_harm_score: 10.0, biometric_data_misuse_rights_violation_score: 10.0, surveillance_state_chilling_effect_score: 8.0, risk_level: "faible", primary_pattern: "protection_biometrique_exemplaire", key_signals: ["UE/RGPD Données Biométriques Protection Haute incarne des standards exemplaires de protection contre la surveillance biométrique — cadre légal strict, supervision indépendante et mécanismes de recours effectifs", "RGPD biométrique respecté — consentement explicite requis, droit à l'effacement garanti et interdiction de la reconnaissance faciale dans les espaces publics sans base légale", "Modèle de protection exportable — standards contraignants partagés au niveau international, financement des organisations de protection de la vie privée numérique"], estimated_biometric_surveillance_state_control_index: 0.9, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { surveillance_biometrique_masse: 3, reconnaissance_faciale_discriminatoire: 1, collecte_donnees_sans_consentement: 2, effet_dissuasif_liberte_expression: 1, protection_biometrique_exemplaire: 1 },
    top_risk_entities: ["Chine/SCS Crédit Social 1.4B Personnes Surveillance Totale", "Russie/SORM Surveillance Communications Moscow 200K Caméras", "Éthiopie/Surveillance Opposants Technologie Chinoise", "Inde/Aadhaar 1.3B Personnes Plus Grand Système Biométrique"],
    critical_alerts: ["Chine/SCS: surveillance biometrique masse", "Russie/SORM: surveillance biometrique masse", "Éthiopie: collecte donnees sans consentement", "Inde/Aadhaar: surveillance biometrique masse"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "biometric_surveillance_state_control",
    confidence_score: 0.85,
    data_sources: ["privacy_international_surveillance_reports", "article_19_facial_recognition_database", "ai_now_institute_biometric_surveillance_2023", "surveillance_technology_oversight_project"],
    entities,
    avg_estimated_biometric_surveillance_state_control_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
