import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[indigenous-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Indigenous Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/indigenous-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Indigenous Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Indigenous Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "IR-001", name: "Amazonie/Brésil — Yanomami Génocide Sanitaire, Garimpeiros & Terres Envahies", country: "Amérique Latine", sector: "Brésil Yanomami 28 000 Personnes Contamination Mercure Garimpeiros, Malnutrition Enfants 2023, 900+ Morts Évitables Bolsonaro Ère & FUNAI Démantèlement Protection Terres Autochtones", composite_score: 90.15, land_territory_dispossession_score: 95.0, cultural_linguistic_erasure_score: 88.0, self_determination_denial_score: 85.0, violence_criminalization_score: 92.0, risk_level: "critique", primary_pattern: "land_territory_dispossession", key_signals: ["Violation des droits autochtones documentée — Amazonie/Brésil avec score composite 90.15/100 révélant un génocide sanitaire des Yanomami avec contamination au mercure des garimpeiros, malnutrition infantile et 900+ morts évitables sous Bolsonaro, violant l'UNDRIP Articles 7 et 25", "Dépossession terres/territoire (95.0/100) — l'invasion illégale des terres homologuées yanomami par des milliers de garimpeiros avec tolérance étatique constitue une violation du droit à la terre garanti par l'Article 26 de la Déclaration ONU sur les droits des peuples autochtones (UNDRIP)", "Appliquer immédiatement la décision de la Cour Suprême brésilienne sur la protection des terres yanomami et activer le Mécanisme d'expert ONU sur les droits des peuples autochtones pour enquête urgente sur la situation sanitaire et territoriale des Yanomami"], estimated_indigenous_rights_index: 9.02, last_updated: "2026-06-20" },
    { entity_id: "IR-002", name: "Canada — Pensionnats 215 Enfants Retrouvés, MMIW 1 200 & Eau Potable", country: "Amérique du Nord", sector: "Canada 215 Tombes Enfants Pensionnats Kamloops 2021, MMIW Missing Murdered Indigenous Women 1 200+, 31 Avis Eau Potable Réserves Long Terme & Réconciliation TRC 94 Appels Non-Mis En Oeuvre", composite_score: 87.50, land_territory_dispossession_score: 85.0, cultural_linguistic_erasure_score: 92.0, self_determination_denial_score: 88.0, violence_criminalization_score: 85.0, risk_level: "critique", primary_pattern: "cultural_linguistic_erasure", key_signals: ["Violation des droits autochtones documentée — Canada avec score composite 87.50/100 révélant la découverte de 215 corps d'enfants autochtones dans les pensionnats et 1 200+ femmes et filles autochtones disparues ou assassinées, constituant des violations graves de l'UNDRIP et de la CDE", "Effacement culturel/linguistique (92.0/100) — les pensionnats canadiens ayant arraché des générations d'enfants à leurs familles et cultures constituent un génocide culturel reconnu par la Commission de Vérité et Réconciliation (CVR) violant l'Article 8 UNDRIP sur le droit à la culture", "Mettre en œuvre les 94 appels à l'action de la CVR et les 231 appels à la justice de l'Enquête nationale MMIW en allouant les ressources nécessaires, et ratifier la Déclaration ONU sur les droits des peuples autochtones en droit interne canadien contraignant"], estimated_indigenous_rights_index: 8.75, last_updated: "2026-06-20" },
    { entity_id: "IR-003", name: "Australie — Surincarcération 3% Population 28% Prisons, Deaths In Custody & Terres", country: "Pacifique", sector: "Australie Autochtones 3% Population 28% Détenus, 500+ Décès En Garde À Vue Depuis 1991, Terres Autochtones Contestées Procédures Longues & Écart Espérance Vie 8 Ans Autochtones/Non-Autochtones", composite_score: 86.25, land_territory_dispossession_score: 82.0, cultural_linguistic_erasure_score: 85.0, self_determination_denial_score: 88.0, violence_criminalization_score: 92.0, risk_level: "critique", primary_pattern: "violence_criminalization", key_signals: ["Violation des droits autochtones documentée — Australie avec score composite 86.25/100 révélant une surincarcération massive (28% des détenus pour 3% de la population), 500+ décès en garde à vue depuis 1991 et un écart d'espérance de vie de 8 ans constituant une discrimination systémique violant l'UNDRIP", "Violence/Criminalisation (92.0/100) — le taux de surincarcération des autochtones australiens, 15× supérieur à la population non-autochtone, et les 500+ morts en garde à vue sans condamnation depuis 1991 révèlent une violence institutionnelle systémique violant l'Article 7 UNDRIP", "Mettre en œuvre les recommandations de la Royal Commission into Aboriginal Deaths in Custody (1991) toujours non-appliquées et adopter un traité national avec les peuples autochtones australiens conformément aux obligations UNDRIP sur le consentement libre, préalable et éclairé"], estimated_indigenous_rights_index: 8.63, last_updated: "2026-06-20" },
    { entity_id: "IR-004", name: "Myanmar/Bangladesh — Rohingyas Apatridie, Chin/Kachin Déplacements & UNDRIP", country: "Asie du Sud-Est", sector: "Myanmar Rohingyas Apatrides Loi 1982 Non-Reconnus Peuples Autochtones, Chin/Kachin Terres Confisquées Armée, Bangladesh Adivasi Discrimination & ASEAN Blocage Mécanismes Autochtones", composite_score: 87.00, land_territory_dispossession_score: 88.0, cultural_linguistic_erasure_score: 82.0, self_determination_denial_score: 90.0, violence_criminalization_score: 88.0, risk_level: "critique", primary_pattern: "self_determination_denial", key_signals: ["Violation des droits autochtones documentée — Myanmar/Bangladesh avec score composite 87.00/100 révélant le refus de reconnaissance des droits autochtones des Rohingyas et autres minorités ethniques, l'ASEAN bloquant systématiquement les mécanismes de protection autochtone régionaux", "Déni autodétermination (90.0/100) — le refus du Myanmar de reconnaître les Rohingyas comme peuple autochtone et la confiscation des terres Chin et Kachin par l'armée constituent des violations directes des Articles 3 et 8 UNDRIP sur l'autodétermination et l'intégrité culturelle", "Exiger la reconnaissance des peuples autochtones du Myanmar dans la future constitution post-junte et créer un mécanisme ASEAN contraignant de protection des droits autochtones conforme à l'UNDRIP adoptée par l'Assemblée Générale ONU en 2007"], estimated_indigenous_rights_index: 8.70, last_updated: "2026-06-20" },
    { entity_id: "IR-005", name: "USA — Standing Rock, DAPL & Criminalisation Défenseurs Terres Autochtones", country: "Amérique du Nord", sector: "USA Standing Rock DAPL Construit Malgré Opposition Sioux, Criminalisation 800 Militants Autochtones 2016, Alaska Drilling Terres Sacrées & ICWA Indian Child Welfare Act Menacé SCOTUS", composite_score: 56.60, land_territory_dispossession_score: 55.0, cultural_linguistic_erasure_score: 52.0, self_determination_denial_score: 62.0, violence_criminalization_score: 58.0, risk_level: "élevé", primary_pattern: "self_determination_denial", key_signals: ["Violation des droits autochtones documentée — USA avec score composite 56.60/100 révélant la construction du Dakota Access Pipeline (DAPL) malgré l'opposition des Sioux Standing Rock et la criminalisation de 800 défenseurs autochtones violant le consentement libre, préalable et éclairé (CLPE)", "Déni autodétermination (62.0/100) — la construction du DAPL traversant des terres et eaux sacrées sioux sans consentement éclairé des tribus affectées constitue une violation du droit au CLPE (Article 32 UNDRIP) et des obligations fiduciaires fédérales envers les Nations autochtones", "Ratifier l'UNDRIP (États-Unis ont voté contre en 2007, endossé en 2010 sans force contraignante) et renforcer la consultation des Nations autochtones pour tous projets d'infrastructure conformément aux obligations du Traité de Fort Laramie et du droit fédéral sur les terres tribales"], estimated_indigenous_rights_index: 5.66, last_updated: "2026-06-20" },
    { entity_id: "IR-006", name: "Inde — Adivasi 10M Expulsés Forêts, Loi Forêts 2023 & Naxalisme Criminalisation", country: "Asie du Sud", sector: "Inde Adivasi 10M Expulsés Forêts Loi 2006 Mal Appliquée, Forest Rights Act 2006 Non-Implémenté, Loi Amendement Forêts 2023 Retire Droits & Conflits Naxalites Criminalisation Populations Tribales", composite_score: 51.55, land_territory_dispossession_score: 58.0, cultural_linguistic_erasure_score: 48.0, self_determination_denial_score: 55.0, violence_criminalization_score: 42.0, risk_level: "élevé", primary_pattern: "land_territory_dispossession", key_signals: ["Violation des droits autochtones documentée — Inde avec score composite 51.55/100 révélant l'expulsion de 10 millions d'Adivasi (peuples autochtones) de leurs forêts ancestrales malgré le Forest Rights Act 2006, et les amendements de 2023 réduisant leurs protections légales", "Dépossession terres/territoire (58.0/100) — l'expulsion de 10 millions d'Adivasi des forêts et la non-application du Forest Rights Act 2006 par les États indiens constituent des violations du droit à la terre et au territoire garanti par l'UNDRIP et la Convention OIT 169", "Mettre en œuvre le Forest Rights Act 2006 dans tous les États indiens et abroger les amendements de 2023 restreignant les droits forestiers des Adivasi, conformément aux recommandations du Rapporteur Spécial ONU sur les droits des peuples autochtones après sa visite en Inde"], estimated_indigenous_rights_index: 5.16, last_updated: "2026-06-20" },
    { entity_id: "IR-007", name: "Nouvelle-Zélande/Scandinavie — Traité Waitangi & Sámi Droits Relatifs Progrès", country: "Pacifique/Europe du Nord", sector: "Nouvelle-Zélande Traité Waitangi 1840 Mécanismes Réclamations, Sámi Parlement Norvège/Suède/Finlande, Droits Pêche/Chasse Reconnus & Progrès Relatifs Langue Maori/Sámi Revitalisation", composite_score: 27.05, land_territory_dispossession_score: 28.0, cultural_linguistic_erasure_score: 32.0, self_determination_denial_score: 25.0, violence_criminalization_score: 22.0, risk_level: "modéré", primary_pattern: "cultural_linguistic_erasure", key_signals: ["Progrès relatifs des droits autochtones — Nouvelle-Zélande et pays scandinaves offrent les modèles les plus avancés de reconnaissance des droits autochtones via le Tribunal Waitangi et les Parlements Sámi, mais des lacunes persistent sur la co-gouvernance et les réparations territoriales", "Effacement culturel/linguistique (32.0/100) — malgré des progrès significatifs, la revitalisation des langues maorie et sámi reste fragile et les inégalités socio-économiques entre autochtones et non-autochtones persistent en Nouvelle-Zélande et en Scandinavie", "Capitaliser les modèles néo-zélandais et scandinave pour élaborer des standards internationaux de co-gouvernance avec les peuples autochtones et renforcer la mise en œuvre contraignante de l'UNDRIP dans les systèmes juridiques nationaux"], estimated_indigenous_rights_index: 2.71, last_updated: "2026-06-20" },
    { entity_id: "IR-008", name: "UNDRIP/OIT 169 — Consentement CLPE, Autodétermination & Mécanisme Expert ONU", country: "Global", sector: "UNDRIP Déclaration ONU Droits Peuples Autochtones 2007 146 États, Convention OIT 169 1989 23 Ratifications, Mécanisme Expert ONU MEDPA & Rapporteur Spécial ONU Droits Peuples Autochtones", composite_score: 4.45, land_territory_dispossession_score: 5.0, cultural_linguistic_erasure_score: 4.0, self_determination_denial_score: 3.0, violence_criminalization_score: 6.0, risk_level: "faible", primary_pattern: "self_determination_denial", key_signals: ["UNDRIP/OIT 169 incarne le cadre normatif exemplaire des droits autochtones — UNDRIP 2007 posant 46 articles sur le droit à l'autodétermination, à la terre, à la culture et au consentement libre préalable et éclairé (CLPE) créant des standards internationaux de référence", "UNDRIP Article 3 — reconnaît le droit à l'autodétermination des peuples autochtones, leur droit de déterminer librement leur statut politique et d'assurer leur développement économique, social et culturel, créant une obligation pour les États de respecter leur gouvernance propre", "Renforcer la force contraignante de l'UNDRIP par un protocole additionnel avec mécanisme de plainte individuel et tripler le budget du Mécanisme d'expert ONU sur les droits des peuples autochtones pour assurer un suivi effectif des violations dans les 90 pays comptant des populations autochtones significatives"], estimated_indigenous_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { land_territory_dispossession: 3, cultural_linguistic_erasure: 2, self_determination_denial: 3, violence_criminalization: 1 },
    top_risk_entities: ["Amazonie/Brésil — Yanomami Génocide Sanitaire, Garimpeiros & Terres Envahies", "Canada — Pensionnats 215 Enfants Retrouvés, MMIW 1 200 & Eau Potable", "Myanmar/Bangladesh — Rohingyas Apatridie, Chin/Kachin Déplacements & UNDRIP"],
    critical_alerts: ["Amazonie/Brésil: land territory dispossession", "Canada: cultural linguistic erasure", "Myanmar/Bangladesh: self determination denial", "Australie: violence criminalization"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "indigenous_rights",
    confidence_score: 0.85,
    data_sources: ["un_special_rapporteur_indigenous_peoples_country_reports", "cultural_survival_indigenous_rights_violations_database", "land_is_life_indigenous_land_rights_global_monitor"],
    entities,
    avg_estimated_indigenous_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
