import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[maritime-piracy-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Maritime Piracy Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/maritime-piracy-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Maritime Piracy Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Maritime Piracy Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "MP-001", name: "Golfe de Guinée — Nigeria & Piraterie Violente 200 Miles", country: "Afrique de l'Ouest", sector: "130 Incidents BMI 2020, Prises Otages 6 Mois, 200M Offshore Attaques & Corruption Marine Nigériane", composite_score: 78.6, armed_attack_frequency_score: 92.0, state_sponsored_piracy_score: 65.0, chokepoint_control_score: 75.0, ransomware_maritime_score: 80.0, risk_level: "critique", primary_pattern: "piraterie_violente_organisee", key_signals: ["Piraterie maritime critique de Golfe de Guinée — 130 incidents BMI en 2020 avec prises d'otages jusqu'à 200 miles offshore, finançant des réseaux criminels transnationaux", "Menace au commerce mondial — les attaques perturbent les chaînes d'approvisionnement mondiales, augmentent les coûts d'assurance maritime et forcent le rerouting coûteux", "Impunité structurelle — l'absence de poursuites efficaces crée un effet d'aubaine pour les réseaux pirates et les États sponsors de piraterie proxy"], estimated_maritime_piracy_index: 7.86, last_updated: "2026-06-20" },
    { id: "MP-002", name: "Houthis/Iran — Piraterie Proxy Mer Rouge & Bab el-Mandeb", country: "MENA", sector: "27% Commerce Mondial Menacé, Missiles/Drones Navires Commerciaux, Rerouting Cap Bonne Esp. +14J & Iran Sponsor", composite_score: 86.05, armed_attack_frequency_score: 85.0, state_sponsored_piracy_score: 92.0, chokepoint_control_score: 88.0, ransomware_maritime_score: 72.0, risk_level: "critique", primary_pattern: "piraterie_etatique_proxy", key_signals: ["Piraterie maritime critique de Houthis/Iran — piraterie proxy soutenue par l'Iran attaquant 27% du commerce mondial en mer Rouge avec missiles et drones", "Menace au commerce mondial — les attaques perturbent les chaînes d'approvisionnement mondiales, augmentent les coûts d'assurance maritime et forcent le rerouting coûteux", "Impunité structurelle — l'absence de poursuites efficaces crée un effet d'aubaine pour les réseaux pirates et les États sponsors de piraterie proxy"], estimated_maritime_piracy_index: 8.61, last_updated: "2026-06-20" },
    { id: "MP-003", name: "Chine — Milices Maritimes & Piraterie Légalisée MCS", country: "Asie", sector: "Gardes-Côtes vs Philippines Cannons Eau, Milices 3000 Bateaux Haijing, ZEE Violation Systémique & UNCLOS Rejeté", composite_score: 81.25, armed_attack_frequency_score: 72.0, state_sponsored_piracy_score: 88.0, chokepoint_control_score: 95.0, ransomware_maritime_score: 68.0, risk_level: "critique", primary_pattern: "piraterie_etatique_proxy", key_signals: ["Piraterie maritime critique de Chine — milices maritimes de 3000 bateaux et gardes-côtes armés expulsant illégalement les pêcheurs philippins et vietnamiens de leurs ZEE", "Menace au commerce mondial — les attaques perturbent les chaînes d'approvisionnement mondiales, augmentent les coûts d'assurance maritime et forcent le rerouting coûteux", "Impunité structurelle — l'absence de poursuites efficaces crée un effet d'aubaine pour les réseaux pirates et les États sponsors de piraterie proxy"], estimated_maritime_piracy_index: 8.13, last_updated: "2026-06-20" },
    { id: "MP-004", name: "Somalie & Corne d'Afrique — Piraterie Offshore Renaissante", country: "Afrique de l'Est", sector: "Piraterie Résurgence 2023 Contexte Houthis, Al-Shabaab Maritime Wing, Golfe Aden Attaques & Rançons Crypto", composite_score: 77.6, armed_attack_frequency_score: 80.0, state_sponsored_piracy_score: 72.0, chokepoint_control_score: 82.0, ransomware_maritime_score: 78.0, risk_level: "critique", primary_pattern: "controle_voie_maritime_ilicite", key_signals: ["Piraterie maritime critique de Somalie & Corne d'Afrique — résurgence de la piraterie somalienne en 2023 exploitant la distraction causée par les Houthis en mer Rouge", "Menace au commerce mondial — les attaques perturbent les chaînes d'approvisionnement mondiales, augmentent les coûts d'assurance maritime et forcent le rerouting coûteux", "Impunité structurelle — l'absence de poursuites efficaces crée un effet d'aubaine pour les réseaux pirates et les États sponsors de piraterie proxy"], estimated_maritime_piracy_index: 7.76, last_updated: "2026-06-20" },
    { id: "MP-005", name: "Iran — IRGC Marine & Saisies Navires Hormuz", country: "MENA", sector: "Détroit Hormuz 20% Pétrole Mondial, Saisies IRGC Navires Commerciaux, Mines Navales & Harcelèment", composite_score: 58.3, armed_attack_frequency_score: 55.0, state_sponsored_piracy_score: 52.0, chokepoint_control_score: 65.0, ransomware_maritime_score: 62.0, risk_level: "élevé", primary_pattern: "piraterie_active", key_signals: ["Piraterie maritime active de Iran — l'IRGC saisit des navires commerciaux dans le Détroit d'Hormuz contrôlant 20% du pétrole mondial comme outil de coercition géopolitique", "Économie criminelle maritime — prise d'otages, vols de cargaisons et rackets à l'escale finançant des organisations criminelles déstabilisatrices", "Déficit de capacités navales — l'insuffisance des patrouilles côtières nationales et la corruption créent des zones de non-droit maritime exploitées par les pirates"], estimated_maritime_piracy_index: 5.83, last_updated: "2026-06-20" },
    { id: "MP-006", name: "Venezuela & Caraïbes — Piraterie Narco & Corruption", country: "Amérique du Sud", sector: "Pirates Narco-Liés, Attaques Voiliers Tourisme, Corruption Gardes-Côtes & Transit Drogue Maritime", composite_score: 50.6, armed_attack_frequency_score: 52.0, state_sponsored_piracy_score: 48.0, chokepoint_control_score: 42.0, ransomware_maritime_score: 58.0, risk_level: "élevé", primary_pattern: "piraterie_active", key_signals: ["Piraterie maritime active de Venezuela & Caraïbes — piraterie liée aux réseaux narco ciblant les voiliers de tourisme et les embarcations de pêche avec des gardes-côtes corrompus", "Économie criminelle maritime — prise d'otages, vols de cargaisons et rackets à l'escale finançant des organisations criminelles déstabilisatrices", "Déficit de capacités navales — l'insuffisance des patrouilles côtières nationales et la corruption créent des zones de non-droit maritime exploitées par les pirates"], estimated_maritime_piracy_index: 5.06, last_updated: "2026-06-20" },
    { id: "MP-007", name: "Détroit de Malacca & Asie Sud-Est — Faible Intensité", country: "Asie du Sud-Est", sector: "Petits Vols Bateaux, Indonésie Piraterie Côtière, Capacités Régionales RECAAP Améliorées & Risque Résiduel", composite_score: 29.65, armed_attack_frequency_score: 28.0, state_sponsored_piracy_score: 25.0, chokepoint_control_score: 32.0, ransomware_maritime_score: 35.0, risk_level: "modéré", primary_pattern: "piraterie_active", key_signals: ["Risque piraterie de Détroit de Malacca & Asie Sud-Est — incidents de faible intensité résiduels malgré l'amélioration des capacités régionales RECAAP", "Vulnérabilités côtières — pauvreté des communautés côtières, pêche illégale étrangère et gouvernance maritime défaillante créant des conditions propices", "Risque d'aggravation — la dégradation des conditions économiques et la prolifération des armes légères pourraient intensifier les incidents de piraterie"], estimated_maritime_piracy_index: 2.97, last_updated: "2026-06-20" },
    { id: "MP-008", name: "OMI & EU NAVFOR — Sécurité Maritime Coopérative", country: "Global", sector: "OMI Convention SUA, EU NAVFOR Atalante, RECAAP Asie & Combined Maritime Forces 34 Nations Anti-Piraterie", composite_score: 4.45, armed_attack_frequency_score: 5.0, state_sponsored_piracy_score: 4.0, chokepoint_control_score: 3.0, ransomware_maritime_score: 6.0, risk_level: "faible", primary_pattern: "securite_maritime_cooperative", key_signals: ["OMI & EU NAVFOR incarne la sécurité maritime coopérative — participation aux opérations navales multinationales, respect de l'UNCLOS et partage du renseignement maritime", "Gouvernance maritime exemplaire — garde-côtes efficaces, tribunaux maritimes compétents et coopération régionale contre les réseaux pirates", "Modèle anti-piraterie à diffuser — financement de l'OMI, formation des marines côtières et assistance judiciaire pour poursuivre les pirates capturés"], estimated_maritime_piracy_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { piraterie_etatique_proxy: 2, piraterie_violente_organisee: 1, controle_voie_maritime_ilicite: 1, piraterie_active: 3, securite_maritime_cooperative: 1 },
    top_risk_entities: ["Houthis/Iran — Piraterie Proxy Mer Rouge & Bab el-Mandeb", "Chine — Milices Maritimes & Piraterie Légalisée MCS", "Somalie & Corne d'Afrique — Piraterie Offshore Renaissante"],
    critical_alerts: ["Golfe de Guinée: piraterie violente organisée", "Houthis/Iran: piraterie étatique proxy", "Chine: piraterie étatique proxy", "Somalie & Corne d'Afrique: contrôle voie maritime ilicite"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "maritime_piracy",
    confidence_score: 0.82,
    data_sources: ["icc_imb_piracy_report", "unodc_maritime_crime_monitor", "eu_navfor_atalanta_reports"],
    entities,
    avg_estimated_maritime_piracy_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
