import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[right-to-health-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Right to Health Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/right-to-health-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Right to Health Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Right to Health Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "RH-001", name: "Sierra Leone/Niger — Mortalité Maternelle 443-553/100k, Sages-Femmes & Déserts Médicaux", country: "Afrique de l'Ouest", sector: "Sierra Leone 443/100k Mortalité Maternelle OMS, Niger 553/100k Plus Élevé Monde, 1 Médecin/40 000 Habitants, Accouchements Domicile 70% Sans Soins & CSU OMS Lointaine", composite_score: 87.65, healthcare_access_denial_score: 88.0, medicine_affordability_barrier_score: 82.0, maternal_infant_mortality_score: 95.0, health_system_collapse_score: 85.0, risk_level: "critique", primary_pattern: "mortalite_maternelle_infantile", key_signals: ["Violation du droit à la santé documentée — Sierra Leone/Niger avec score composite 87.65/100 révélant des défaillances systémiques violant l'Article 25 de la DUDH et l'Article 12 du PIDESC sur le droit au meilleur état de santé possible", "Déni d'accès aux soins (88.0/100) — les taux de mortalité maternelle de 443-553 pour 100 000 naissances vivantes constituent des violations graves du droit à la santé reproductive garantie par le PIDESC et la CEDAW", "Activer le Rapporteur Spécial ONU sur le droit à la santé et exiger l'application du Plan d'action OMS pour la couverture santé universelle avec financement international adéquat"], estimated_right_to_health_index: 8.77, last_updated: "2026-06-20" },
    { id: "RH-002", name: "Yemen/Gaza — Hôpitaux Bombardés, 70% Système Santé Détruit & Médecins Arrêtés", country: "MENA", sector: "Yémen 50% Hôpitaux Fermés Conflit, Gaza 70% Infrastructure Santé Détruite 2024, MSF Équipes Tués, Médicaments Bloqués Siège & OMS Alertes Famine/Choléra Simultanés", composite_score: 90.60, healthcare_access_denial_score: 92.0, medicine_affordability_barrier_score: 88.0, maternal_infant_mortality_score: 88.0, health_system_collapse_score: 95.0, risk_level: "critique", primary_pattern: "effondrement_systeme_sante", key_signals: ["Violation du droit à la santé documentée — Yemen/Gaza avec score composite 90.60/100 révélant des défaillances systémiques violant l'Article 25 de la DUDH et l'Article 12 du PIDESC sur le droit au meilleur état de santé possible", "Déni d'accès aux soins (92.0/100) — la destruction de 70% de l'infrastructure de santé à Gaza et la fermeture de 50% des hôpitaux au Yémen constituent des violations graves du droit à la santé et du droit international humanitaire protégeant les établissements médicaux", "Activer le Rapporteur Spécial ONU sur le droit à la santé et exiger l'application du Plan d'action OMS pour la couverture santé universelle avec financement international adéquat"], estimated_right_to_health_index: 9.06, last_updated: "2026-06-20" },
    { id: "RH-003", name: "RDC/Sahel — 3 000+ Centres Santé Attaqués, Ebola Récurrences & Accès MSF Bloqué", country: "Afrique Centrale/Ouest", sector: "RDC 3 000 Centres Santé Attaqués 2018-24, Épidémies Ebola Récurrentes Zones Conflit, Accès MSF/ONG Santé Bloqué Factions & Mortalité Infantile 65/1000 Naissances", composite_score: 86.00, healthcare_access_denial_score: 85.0, medicine_affordability_barrier_score: 82.0, maternal_infant_mortality_score: 88.0, health_system_collapse_score: 90.0, risk_level: "critique", primary_pattern: "effondrement_systeme_sante", key_signals: ["Violation du droit à la santé documentée — RDC/Sahel avec score composite 86.00/100 révélant des défaillances systémiques violant l'Article 25 de la DUDH et l'Article 12 du PIDESC sur le droit au meilleur état de santé possible", "Déni d'accès aux soins (85.0/100) — les 3 000+ attaques contre des centres de santé en RDC et les épidémies Ebola récurrentes dans les zones de conflit constituent des violations du droit à la santé et de l'Article 18 du DIH protégeant le personnel médical", "Activer le Rapporteur Spécial ONU sur le droit à la santé et exiger l'application du Plan d'action OMS pour la couverture santé universelle avec financement international adéquat"], estimated_right_to_health_index: 8.60, last_updated: "2026-06-20" },
    { id: "RH-004", name: "USA/Insulin Crisis — 7.4M Diabétiques Sans Insuline, Faillites Médicales & Pas CSU", country: "Amérique du Nord", sector: "USA 7.4M Diabétiques Insuline Inabordable 300$/Mois, 500 000 Faillites Personnelles/An Dettes Médicales, 30M Sans Assurance & Affaire Rationing Insuline Deaths Congress 2019", composite_score: 84.50, healthcare_access_denial_score: 80.0, medicine_affordability_barrier_score: 92.0, maternal_infant_mortality_score: 82.0, health_system_collapse_score: 85.0, risk_level: "critique", primary_pattern: "barriere_prix_medicaments", key_signals: ["Violation du droit à la santé documentée — USA/Insulin Crisis avec score composite 84.50/100 révélant des défaillances systémiques violant l'Article 25 de la DUDH et l'Article 12 du PIDESC sur le droit au meilleur état de santé possible", "Déni d'accès aux soins (80.0/100) — l'impossibilité pour 7.4 millions de diabétiques américains d'accéder à l'insuline essentielle en raison de son prix et les 500 000 faillites annuelles pour dettes médicales constituent des violations du droit à la santé dans la plus grande économie mondiale", "Activer le Rapporteur Spécial ONU sur le droit à la santé et exiger l'application du Plan d'action OMS pour la couverture santé universelle avec financement international adéquat"], estimated_right_to_health_index: 8.45, last_updated: "2026-06-20" },
    { id: "RH-005", name: "Inde — 60% Dépenses Santé Privées, 3 000$ Catastrophiques Familles & AMR Crise", country: "Asie du Sud", sector: "Inde 60% Dépenses Santé Out-Of-Pocket, 55M Pauvreté/An Dépenses Médicales, Résistance Antimicrobiens AMR 1.35M Décès/An Inde & Couverture CSU 35% Population", composite_score: 55.00, healthcare_access_denial_score: 55.0, medicine_affordability_barrier_score: 58.0, maternal_infant_mortality_score: 52.0, health_system_collapse_score: 55.0, risk_level: "élevé", primary_pattern: "barriere_prix_medicaments", key_signals: ["Violation du droit à la santé documentée — Inde avec score composite 55.00/100 révélant des dépenses de santé catastrophiques pour 55 millions de personnes plongeant dans la pauvreté chaque année, violant le PIDESC Art 12", "Déni d'accès aux soins (55.0/100) — les 60% de dépenses de santé out-of-pocket en Inde et la crise de la résistance antimicrobienne causant 1.35 million de décès annuels révèlent un déficit systémique de financement public de la santé", "Augmenter substantiellement le budget santé public indien (actuellement 1.2% PIB) et accélérer le déploiement de l'Ayushman Bharat vers une couverture santé universelle effective conformément aux ODD3"], estimated_right_to_health_index: 5.50, last_updated: "2026-06-20" },
    { id: "RH-006", name: "Venezuela — Exode Médecins, 95% Manque Médicaments 2019 & Effondrement IVSS", country: "Amérique Latine", sector: "Venezuela 300 000 Médecins Exilés, 95% Pénurie Médicaments 2019 HRW, IVSS Sécurité Sociale Effondrée, Malnutrition Infantile & Mortalité Maternelle Multipliée ×5", composite_score: 53.85, healthcare_access_denial_score: 52.0, medicine_affordability_barrier_score: 55.0, maternal_infant_mortality_score: 58.0, health_system_collapse_score: 50.0, risk_level: "élevé", primary_pattern: "mortalite_maternelle_infantile", key_signals: ["Violation du droit à la santé documentée — Venezuela avec score composite 53.85/100 révélant un effondrement du système de santé avec 95% de pénurie de médicaments et une mortalité maternelle multipliée par 5 violant le PIDESC", "Déni d'accès aux soins (52.0/100) — l'exode de 300 000 médecins et la pénurie de 95% de médicaments essentiels ont réduit l'accès aux soins à des niveaux de crise humanitaire violant les obligations du Venezuela sous le PIDESC", "Lever les sanctions ciblant le système de santé vénézuélien et permettre l'accès de l'aide humanitaire médicale conformément aux recommandations du Rapporteur Spécial ONU sur le droit à la santé"], estimated_right_to_health_index: 5.39, last_updated: "2026-06-20" },
    { id: "RH-007", name: "Europe/Austérité — Grèce 2010-18 Système Santé Coupé 25%, NHS UK Listes Attente", country: "Europe", sector: "Grèce Austérité 2010-18 Budget Santé -25%, NHS Royaume-Uni 7.6M Listes Attente 2024, Médecins Famille Déserts Ruraux France & OCDE Rapports Inégalités Santé Croissantes", composite_score: 28.90, healthcare_access_denial_score: 28.0, medicine_affordability_barrier_score: 32.0, maternal_infant_mortality_score: 30.0, health_system_collapse_score: 25.0, risk_level: "modéré", primary_pattern: "barriere_prix_medicaments", key_signals: ["Défis du droit à la santé en Europe liés à l'austérité — les coupes de 25% du budget santé grec et les 7.6 millions de patients en liste d'attente au NHS britannique révèlent des tensions avec le droit au meilleur état de santé (PIDESC Art 12)", "Déni d'accès aux soins (28.0/100) — les déserts médicaux ruraux en France, les délais d'attente excessifs au NHS et les séquelles des coupes d'austérité grecques créent des inégalités d'accès aux soins au sein de pays développés", "Renforcer les investissements publics dans les systèmes de santé européens conformément aux recommandations de l'OCDE et du Comité PIDESC pour garantir un accès équitable aux soins sans discrimination de localisation géographique ou de revenu"], estimated_right_to_health_index: 2.89, last_updated: "2026-06-20" },
    { id: "RH-008", name: "OMS/PIDESC — Droit Santé Art 12, Couverture Universelle & Accord ADPIC Médicaments", country: "Global", sector: "OMS Couverture Santé Universelle ODD3, PIDESC Article 12 Droit Meilleur État Santé, Accord ADPIC Doha 2001 Médicaments Génériques & Rapporteur Spécial ONU Droit Santé", composite_score: 4.45, healthcare_access_denial_score: 5.0, medicine_affordability_barrier_score: 4.0, maternal_infant_mortality_score: 3.0, health_system_collapse_score: 6.0, risk_level: "faible", primary_pattern: "effondrement_systeme_sante", key_signals: ["OMS/PIDESC incarne le cadre exemplaire du droit à la santé — Article 12 PIDESC et Observation Générale 14 définissant le droit à la santé comme disponible, accessible, acceptable et de qualité (AAAQ) pour toute personne sans discrimination", "PIDESC Article 12 — impose aux États de prendre des mesures progressives pour atteindre le meilleur état de santé possible incluant soins de santé primaires, prévention des épidémies et accès aux médicaments essentiels", "Universaliser l'accès aux médicaments essentiels via le mécanisme ADPIC Doha 2001 et tripler le financement de l'OMS pour déployer la couverture santé universelle dans les pays à revenu faible et intermédiaire d'ici 2030"], estimated_right_to_health_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { deni_acces_soins: 0, barriere_prix_medicaments: 3, mortalite_maternelle_infantile: 2, effondrement_systeme_sante: 3 },
    top_risk_entities: ["Yemen/Gaza — Hôpitaux Bombardés, 70% Système Santé Détruit & Médecins Arrêtés", "Sierra Leone/Niger — Mortalité Maternelle 443-553/100k, Sages-Femmes & Déserts Médicaux", "RDC/Sahel — 3 000+ Centres Santé Attaqués, Ebola Récurrences & Accès MSF Bloqué"],
    critical_alerts: ["Yemen/Gaza: effondrement système santé", "Sierra Leone/Niger: mortalité maternelle infantile", "RDC/Sahel: effondrement système santé", "USA/Insulin Crisis: barrière prix médicaments"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "right_to_health",
    confidence_score: 0.84,
    data_sources: ["who_global_health_observatory_health_financing", "un_special_rapporteur_right_to_health_reports", "msf_access_campaign_medicines_barriers_database"],
    entities,
    avg_estimated_right_to_health_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
