import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[human-rights-defenders-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Human Rights Defenders Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/human-rights-defenders-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Human Rights Defenders Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Human Rights Defenders Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "HRD-001", name: "Mexique/Amérique Centrale — 401 Défenseurs Tués 2023 & Impunité Cartels-État", country: "Amérique Latine", sector: "Mexique 259 Défenseurs Tués 2023 Global Witness Record Mondial, Honduras/Guatemala Défenseurs Terres Autochtones Assassinés, Cartels Complices État & Berta Cáceres Paradigme Impunité", composite_score: 87.35, killings_disappearances_score: 92.0, criminalization_imprisonment_score: 85.0, surveillance_intimidation_score: 82.0, legal_protection_absence_score: 90.0, risk_level: "critique", primary_pattern: "killings_disappearances", key_signals: ["Violation de la protection des défenseurs documentée — Mexique/Amérique Centrale avec score composite 87.35/100 révélant 259 défenseurs des droits tués au Mexique en 2023 selon Global Witness (record mondial), avec une impunité quasi-totale révélant la complicité de l'État avec les auteurs de ces meurtres", "Meurtres/Disparitions (92.0/100) — le Mexique, le Honduras et le Guatemala concentrent 60% des meurtres mondiaux de défenseurs des droits humains, avec une surreprésentation des défenseurs autochtones des terres et de l'environnement, constituant une violation systémique de l'Article 1 de la Déclaration ONU sur les défenseurs (1998)", "Activer le Mécanisme de protection des défenseurs des droits humains et journalistes au Mexique créé en 2012 avec les ressources suffisantes et enquêter sur la complicité des autorités dans les meurtres de défenseurs conformément aux Principes de base ONU sur le recours à la force et à la Déclaration ONU sur les défenseurs de 1998"], estimated_human_rights_defenders_index: 8.74, last_updated: "2026-06-20" },
    { entity_id: "HRD-002", name: "Philippines — Red-Tagging Duterte/Marcos, 900+ Tués & EJE Droits Humains", country: "Asie du Sud-Est", sector: "Philippines Red-Tagging Défenseurs Qualifiés Terroristes, 900+ Activistes Tués Depuis 2016, NTF-ELCAC Listes Rouges, Avocats/Prêtres Assassinés & Karapatan 127 Membres Tués", composite_score: 86.35, killings_disappearances_score: 90.0, criminalization_imprisonment_score: 82.0, surveillance_intimidation_score: 85.0, legal_protection_absence_score: 88.0, risk_level: "critique", primary_pattern: "killings_disappearances", key_signals: ["Violation de la protection des défenseurs documentée — Philippines avec score composite 86.35/100 révélant 900+ défenseurs, avocats, prêtres et journalistes assassinés depuis 2016, la pratique systémique du 'red-tagging' assimilant tout défenseur à un terroriste communiste et l'impunité totale des forces de sécurité", "Meurtres/Disparitions (90.0/100) — le 'red-tagging' systématique par le NTF-ELCAC philippin plaçant des défenseurs sur des listes de suspects terroristes crée un environnement favorisant leur assassinat par des groupes paramilitaires, violant l'Article 12 de la Déclaration ONU sur les défenseurs et le droit à la vie de l'Article 6 PIDCP", "Demander à la CPI de reprendre son enquête préliminaire sur les Philippines pour les exécutions extrajudiciaires et exiger l'abrogation du Terrorism Financing Prevention and Suppression Act utilisé pour réduire au silence les défenseurs, conformément aux recommandations du Rapporteur Spécial ONU sur les défenseurs après sa visite en 2020"], estimated_human_rights_defenders_index: 8.64, last_updated: "2026-06-20" },
    { entity_id: "HRD-003", name: "Russie — Memorial Liquidé, Navalny Tué & Loi Agents Étrangers 2022", country: "Europe de l'Est", sector: "Russie Memorial International Liquidé Décembre 2021, Alexeï Navalny Tué Détention Février 2024, 700+ ONG Agents Étrangers, Loi 2022 ONG Indésirables & Défenseurs 15 Ans Prison", composite_score: 83.0, killings_disappearances_score: 72.0, criminalization_imprisonment_score: 92.0, surveillance_intimidation_score: 88.0, legal_protection_absence_score: 82.0, risk_level: "critique", primary_pattern: "criminalization_imprisonment", key_signals: ["Violation de la protection des défenseurs documentée — Russie avec score composite 83.0/100 révélant la liquidation judiciaire de Memorial International (60 ans d'archive sur la répression soviétique), l'assassinat d'Alexeï Navalny en détention et la criminalisation de 700+ ONG via les lois 'agents étrangers' et 'organisations indésirables'", "Criminalisation/Emprisonnement (92.0/100) — la loi russe sur les agents étrangers et la liste des organisations indésirables ont criminalisé toute société civile indépendante : Memorial, OVD-Info, Human Rights Watch forcées de cesser leurs activités ou exil, violant la liberté d'association (Article 22 PIDCP) et la Déclaration ONU sur les défenseurs", "Imposer des sanctions ciblées contre les fonctionnaires russes responsables de la liquidation de Memorial et de la mort de Navalny et exiger la libération immédiate de tous les défenseurs des droits emprisonnés conformément à l'Article 10 de la Déclaration ONU sur les défenseurs des droits de l'homme"], estimated_human_rights_defenders_index: 8.3, last_updated: "2026-06-20" },
    { entity_id: "HRD-004", name: "Chine — Avocats 709, Femmes Féministes & Défenseurs Xinjiang Disparus", country: "Asie du Nord-Est", sector: "Chine Rafle 709 Juillet 2015 300+ Avocats Droits Humains, Féministes Arrêtées 2015/2019, Défenseurs Ouïghours Disparus Xinjiang, Wang Quanzhang 4 Ans Détention Secrète & HRD Interdits Sortie Territoire", composite_score: 83.1, killings_disappearances_score: 72.0, criminalization_imprisonment_score: 90.0, surveillance_intimidation_score: 92.0, legal_protection_absence_score: 80.0, risk_level: "critique", primary_pattern: "surveillance_intimidation", key_signals: ["Violation de la protection des défenseurs documentée — Chine avec score composite 83.1/100 révélant la rafle de 709 ciblant 300+ avocats des droits humains, les disparitions de défenseurs ouïghours et l'utilisation de la surveillance biométrique et des technologies IA pour identifier et réduire au silence tous les défenseurs", "Surveillance/Intimidation (92.0/100) — la Chine utilise la reconnaissance faciale, le big data et les apps espionnes pour surveiller en temps réel tous les défenseurs des droits, avocats et activistes, créant un effet dissuasif massif qui constitue une violation de la Déclaration ONU sur les défenseurs (Article 12) et du droit à la vie privée (Article 17 PIDCP)", "Invoquer la procédure d'enquête confidentielle du Comité contre la torture pour les disparitions des défenseurs chinois et exiger la libération de tous les avocats emprisonnés lors de la rafle 709, conformément aux constatations du Groupe de travail ONU sur la détention arbitraire sur les cas Wang Quanzhang et Gao Zhisheng"], estimated_human_rights_defenders_index: 8.31, last_updated: "2026-06-20" },
    { entity_id: "HRD-005", name: "USA — Défenseurs Eau/Terres, Standing Rock Criminalisés & SLAPP Corporations", country: "Amérique du Nord", sector: "USA Standing Rock 800 Défenseurs Autochtones Arrêtés 2016, SLAPP Strategic Lawsuits Against Public Participation, Manifestants Climatiques Terrorisme Domestique Charges & Surveillance FBI Activistes", composite_score: 51.4, killings_disappearances_score: 45.0, criminalization_imprisonment_score: 48.0, surveillance_intimidation_score: 62.0, legal_protection_absence_score: 52.0, risk_level: "élevé", primary_pattern: "surveillance_intimidation", key_signals: ["Violation de la protection des défenseurs documentée — USA avec score composite 51.4/100 révélant la criminalisation de 800 défenseurs autochtones de Standing Rock, l'utilisation croissante des SLAPP (poursuites stratégiques bâillon) par les entreprises contre les défenseurs de l'environnement et la surveillance des activistes par le FBI", "Surveillance/Intimidation (62.0/100) — la surveillance par le FBI et les services de renseignement des activistes des droits civiques, des défenseurs de l'environnement et des manifestants Black Lives Matter révèle une criminalisation de la dissidence légitime contraire à l'Article 19 PIDCP et à la Déclaration ONU sur les défenseurs", "Adopter une loi fédérale anti-SLAPP protégeant les défenseurs contre les poursuites bâillon d'entreprises et renforcer les protections constitutionnelles du Premier Amendement pour les défenseurs de l'environnement et des droits autochtones, conformément aux recommandations du Rapporteur Spécial ONU sur les défenseurs après son examen des USA"], estimated_human_rights_defenders_index: 5.14, last_updated: "2026-06-20" },
    { entity_id: "HRD-006", name: "Turquie — 1 500 Avocats Poursuivis, Amnesty Emprisonnée & Agents Étrangers", country: "Europe du Sud-Est", sector: "Turquie 1 500 Avocats Poursuivis Depuis 2016, Taner Kılıç/Directeur Amnesty 6 Ans Procès, Loi Agents Étrangers ONG 2022, Défenseurs Kurdes 30 Ans Prison & HDP 5 000 Membres Arrêtés", composite_score: 51.9, killings_disappearances_score: 45.0, criminalization_imprisonment_score: 62.0, surveillance_intimidation_score: 50.0, legal_protection_absence_score: 52.0, risk_level: "élevé", primary_pattern: "criminalization_imprisonment", key_signals: ["Violation de la protection des défenseurs documentée — Turquie avec score composite 51.9/100 révélant 1 500 avocats poursuivis depuis le coup d'État manqué de 2016, l'emprisonnement du directeur d'Amnesty International Turquie pendant 6 ans et la criminalisation systématique des défenseurs kurdes sous prétexte d'antiterrorisme", "Criminalisation/Emprisonnement (62.0/100) — les poursuites massives contre les avocats des droits humains, journalistes et défenseurs kurdes en Turquie, utilisant les lois antiterroristes pour museler toute dissidence, constituent une violation de la Déclaration ONU sur les défenseurs et des obligations de la Turquie sous la CEDH", "Activer la procédure d'infraction de la CEDH contre la Turquie pour violation systémique des droits des défenseurs et exiger la libération immédiate de tous les avocats et journalistes emprisonnés, conformément aux arrêts de la Grande Chambre CEDH Kavala c. Turquie (2022) et Selahattin Demirtaş c. Turquie"], estimated_human_rights_defenders_index: 5.19, last_updated: "2026-06-20" },
    { entity_id: "HRD-007", name: "UE — Directive Whistleblowers, SLAPP Anti-bâillon & Cadre Protection HRD", country: "Europe", sector: "UE Directive Lanceurs Alerte 2019 Transposition Partielle, Proposition Directive Anti-SLAPP 2022, Fonds UE Défenseurs Droits Humains & Résolution Parlement Européen Protection HRD États Tiers", composite_score: 27.45, killings_disappearances_score: 22.0, criminalization_imprisonment_score: 28.0, surveillance_intimidation_score: 25.0, legal_protection_absence_score: 38.0, risk_level: "modéré", primary_pattern: "legal_protection_absence", key_signals: ["Progrès législatif européen significatif mais insuffisant — la Directive lanceurs d'alerte (2019), la proposition de Directive anti-SLAPP (2022) et le Fonds UE pour les défenseurs représentent des avancées importantes mais la transposition inégale et l'absence de mécanisme contraignant de protection laissent des lacunes", "Absence protection légale (38.0/100) — la transposition incomplète de la Directive lanceurs d'alerte dans plusieurs États membres et les SLAPP transfrontalières révèlent des lacunes dans le cadre européen de protection des défenseurs des droits humains", "Adopter la Directive anti-SLAPP européenne avec un mécanisme de renvoi rapide pour les procédures abusives et créer un mécanisme d'urgence de protection des défenseurs dans les États tiers partenaires de l'UE, conformément aux Lignes directrices de l'UE sur les défenseurs des droits de l'homme (2004, révisées 2008)"], estimated_human_rights_defenders_index: 2.75, last_updated: "2026-06-20" },
    { entity_id: "HRD-008", name: "ONU/Déclaration 1998 — Cadre Normatif, Rapporteur Spécial & Mécanismes Protection", country: "Global", sector: "Déclaration ONU Défenseurs Droits Homme 1998 Résolution A/RES/53/144, Rapporteur Spécial ONU HRD Mary Lawlor Depuis 2020, Mécanismes Régionaux CIDH/UA/OSCE & Fonds Urgence OHCHR", composite_score: 4.45, killings_disappearances_score: 5.0, criminalization_imprisonment_score: 4.0, surveillance_intimidation_score: 3.0, legal_protection_absence_score: 6.0, risk_level: "faible", primary_pattern: "killings_disappearances", key_signals: ["ONU/Déclaration 1998 incarne le cadre normatif de protection des défenseurs des droits — la Déclaration sur les défenseurs des droits de l'homme adoptée par l'Assemblée Générale en 1998 (A/RES/53/144) établissant le droit de défendre les droits humains, protéger les défenseurs contre les représailles et accéder aux organisations internationales", "Rapporteur Spécial ONU sur les HRD — mandat créé en 2000, avec Mary Lawlor depuis 2020, chargé de surveiller la situation des défenseurs dans le monde, répondre aux cas urgents et formuler des recommandations aux États pour améliorer leur protection, recevant 3 000+ communications individuelles par mandat", "Renforcer le mandat du Rapporteur Spécial ONU sur les défenseurs en le rendant universel et créer un fonds d'urgence ONU doté d'au moins 50M$ pour la protection immédiate des défenseurs en danger conformément aux recommandations du Secrétaire général ONU sur la protection des défenseurs"], estimated_human_rights_defenders_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { killings_disappearances: 3, criminalization_imprisonment: 2, surveillance_intimidation: 2, legal_protection_absence: 1 },
    top_risk_entities: ["Mexique/Amérique Centrale — 401 Défenseurs Tués 2023 & Impunité Cartels-État", "Philippines — Red-Tagging Duterte/Marcos, 900+ Tués & EJE Droits Humains", "Chine — Avocats 709, Femmes Féministes & Défenseurs Xinjiang Disparus"],
    critical_alerts: ["Mexique/Amérique Centrale: killings disappearances", "Philippines: killings disappearances", "Russie: criminalization imprisonment", "Chine: surveillance intimidation"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "human_rights_defenders",
    confidence_score: 0.86,
    data_sources: ["front_line_defenders_global_analysis_human_rights_defenders_annual_report", "global_witness_land_environmental_defenders_killed_annual_report", "un_special_rapporteur_human_rights_defenders_country_communications"],
    entities,
    avg_estimated_human_rights_defenders_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
