import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[climate-geopolitics-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Climate Geopolitics Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/climate-geopolitics-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Climate Geopolitics Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Climate Geopolitics Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CG-001", name: "Chine — Monopole Terres Rares & BeiDou Vert Stratégique", country: "Asie", sector: "85% Terres Rares Mondiales, 80% Panneaux Solaires, 70% Batteries & BRI Dépendances Tech Verte", composite_score: 80.15, arctic_resources_militarization_score: 80.0, climate_migration_weaponization_score: 75.0, green_tech_monopoly_score: 92.0, climate_sabotage_score: 72.0, risk_level: "critique", primary_pattern: "monopole_technologie_verte", key_signals: ["Weaponisation climatique de Chine — monopole sur 85% des terres rares et 80% des panneaux solaires mondiaux comme levier de dépendance technologique imposable aux démocraties", "Domination des ressources de la transition — contrôle des terres rares, batteries et énergies renouvelables comme levier de dépendance stratégique imposable aux démocraties", "Escalade géopolitique climatique — la compétition pour les ressources arctiques et les technologies vertes crée des tensions risquant d'éclater en conflits ouverts"], estimated_climate_geopolitics_index: 8.02, last_updated: "2026-06-20" },
    { id: "CG-002", name: "Russie — Militarisation Arctique & Sabotage Énergies Vertes", country: "Europe de l'Est", sector: "14 Bases Arctiques Nouvelles, Sabotage Nord Stream & Désinformation Énergies Vertes Via RT/Sputnik", composite_score: 76.95, arctic_resources_militarization_score: 92.0, climate_migration_weaponization_score: 82.0, green_tech_monopoly_score: 45.0, climate_sabotage_score: 88.0, risk_level: "critique", primary_pattern: "pression_climatique_geopolitique", key_signals: ["Weaponisation climatique de Russie — 14 nouvelles bases militaires arctiques, sabotage des infrastructures énergétiques et désinformation massive contre les énergies renouvelables", "Domination des ressources de la transition — contrôle des terres rares, batteries et énergies renouvelables comme levier de dépendance stratégique imposable aux démocraties", "Escalade géopolitique climatique — la compétition pour les ressources arctiques et les technologies vertes crée des tensions risquant d'éclater en conflits ouverts"], estimated_climate_geopolitics_index: 7.7, last_updated: "2026-06-20" },
    { id: "CG-003", name: "USA — Sanctions Climatiques & Domination Technologique Verte", country: "Amérique du Nord", sector: "IRA 369Md$ Subventions Tech Verte, Minerals Security Partnership & Sanctions Pétrole Adversaires", composite_score: 78.6, arctic_resources_militarization_score: 85.0, climate_migration_weaponization_score: 70.0, green_tech_monopoly_score: 80.0, climate_sabotage_score: 78.0, risk_level: "critique", primary_pattern: "pression_climatique_geopolitique", key_signals: ["Weaponisation climatique de USA — IRA utilisant 369Md$ de subventions vertes comme outil de politique industrielle discriminant les alliés européens", "Domination des ressources de la transition — contrôle des terres rares, batteries et énergies renouvelables comme levier de dépendance stratégique imposable aux démocraties", "Escalade géopolitique climatique — la compétition pour les ressources arctiques et les technologies vertes crée des tensions risquant d'éclater en conflits ouverts"], estimated_climate_geopolitics_index: 7.86, last_updated: "2026-06-20" },
    { id: "CG-004", name: "Turquie & Biélorussie — Weaponisation Migrations Climatiques", country: "MENA/Europe", sector: "Turquie 4M Réfugiés Levier UE, Lukashenka Migrants Irak/Syrie Pologne & Frontex Instrumentalisée", composite_score: 70.95, arctic_resources_militarization_score: 72.0, climate_migration_weaponization_score: 88.0, green_tech_monopoly_score: 55.0, climate_sabotage_score: 68.0, risk_level: "critique", primary_pattern: "weaponisation_migrations_climatiques", key_signals: ["Weaponisation climatique de Turquie & Biélorussie — utilisation des 4 millions de réfugiés climatiques comme levier de négociation contre l'UE et les USA", "Domination des ressources de la transition — contrôle des terres rares, batteries et énergies renouvelables comme levier de dépendance stratégique imposable aux démocraties", "Escalade géopolitique climatique — la compétition pour les ressources arctiques et les technologies vertes crée des tensions risquant d'éclater en conflits ouverts"], estimated_climate_geopolitics_index: 7.1, last_updated: "2026-06-20" },
    { id: "CG-005", name: "Arabie Saoudite & OPEP — Sabotage Transition Énergétique", country: "MENA", sector: "OPEP+ Cuts Stratégiques, Lobbying COP Combustibles Fossiles & Saudi Aramco 2050 Net Zero Fictif", composite_score: 50.15, arctic_resources_militarization_score: 48.0, climate_migration_weaponization_score: 45.0, green_tech_monopoly_score: 38.0, climate_sabotage_score: 75.0, risk_level: "élevé", primary_pattern: "pression_climatique_geopolitique", key_signals: ["Pression climatique géopolitique de Arabie Saoudite & OPEP — coupes OPEP+ stratégiques et lobbying agressif aux COP contre les engagements de sortie des combustibles fossiles", "Compétition pour les ressources de transition — course aux minerais critiques, terres rares et positions arctiques sans règles du jeu claires", "Risque de conflits climatiques — les migrations massives induites par le réchauffement alimentent les tensions politiques internes et les crises humanitaires régionales"], estimated_climate_geopolitics_index: 5.02, last_updated: "2026-06-20" },
    { id: "CG-006", name: "Australie & Canada — Ressources Minérales Critiques", country: "Pacifique/Amérique", sector: "Lithium/Nickel/Cobalt Stratégiques, AUKUS Arctique & Minéraux Critiques vs Chine Alternatives", composite_score: 50.9, arctic_resources_militarization_score: 55.0, climate_migration_weaponization_score: 42.0, green_tech_monopoly_score: 62.0, climate_sabotage_score: 42.0, risk_level: "élevé", primary_pattern: "pression_climatique_geopolitique", key_signals: ["Pression climatique géopolitique de Australie & Canada — positionnement stratégique comme alternatives à la Chine pour les minerais critiques de la transition énergétique", "Compétition pour les ressources de transition — course aux minerais critiques, terres rares et positions arctiques sans règles du jeu claires", "Risque de conflits climatiques — les migrations massives induites par le réchauffement alimentent les tensions politiques internes et les crises humanitaires régionales"], estimated_climate_geopolitics_index: 5.09, last_updated: "2026-06-20" },
    { id: "CG-007", name: "Inde — Émissions & Vulnérabilité Climatique Croissante", country: "Asie du Sud", sector: "3ème Émetteur Mondial, Fonte Glaciers Himalaya 800M, Canicules Mortelles & Stress Hydrique Ganges", composite_score: 30.5, arctic_resources_militarization_score: 30.0, climate_migration_weaponization_score: 28.0, green_tech_monopoly_score: 38.0, climate_sabotage_score: 25.0, risk_level: "modéré", primary_pattern: "pression_climatique_geopolitique", key_signals: ["Transition géopolitique de Inde — 3ème émetteur mondial confronté à des vulnérabilités climatiques extrêmes menaçant 800 millions de personnes dépendant des glaciers himalayens", "Vulnérabilités émergentes — dépendances énergétiques fossiles ou aux technologies vertes étrangères créant des expositions géopolitiques croissantes", "Risque de bascule — l'aggravation du changement climatique pourrait transformer des vulnérabilités actuelles en crises sécuritaires majeures"], estimated_climate_geopolitics_index: 3.05, last_updated: "2026-06-20" },
    { id: "CG-008", name: "UE & Accords Paris — Leadership Climatique Coopératif", country: "Europe", sector: "Pacte Vert 55% Réduction 2030, Fonds Vert 100Md$/An & CBAM Taxe Carbone Frontières Mondiale", composite_score: 4.45, arctic_resources_militarization_score: 5.0, climate_migration_weaponization_score: 4.0, green_tech_monopoly_score: 3.0, climate_sabotage_score: 6.0, risk_level: "faible", primary_pattern: "leadership_climatique_cooperatif", key_signals: ["UE & Accords Paris incarne le leadership climatique coopératif — financement du Fonds Vert, Accords de Paris respectés et diplomatie climatique inclusive exemplaire", "Transition verte exemplaire — déploiement massif des énergies renouvelables domestiques et exportation de technologies vertes sans conditions géopolitiques", "Modèle de coopération climatique — partage des données, transferts technologiques et mécanismes d'adaptation pour les États les plus vulnérables"], estimated_climate_geopolitics_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { militarisation_arctique_strategique: 0, weaponisation_migrations_climatiques: 1, monopole_technologie_verte: 1, pression_climatique_geopolitique: 5, leadership_climatique_cooperatif: 1 },
    top_risk_entities: ["Chine — Monopole Terres Rares & BeiDou Vert Stratégique", "USA — Sanctions Climatiques & Domination Technologique Verte", "Russie — Militarisation Arctique & Sabotage Énergies Vertes"],
    critical_alerts: ["Chine: monopole technologie verte", "USA: pression climatique géopolitique", "Russie: pression climatique géopolitique", "Turquie & Biélorussie: weaponisation migrations climatiques"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "climate_geopolitics",
    confidence_score: 0.76,
    data_sources: ["ipcc_sixth_assessment_report", "arctic_council_monitoring", "iea_critical_minerals_tracker"],
    entities,
    avg_estimated_climate_geopolitics_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
