import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

const SWARM_API_URL = process.env.SWARM_API_URL;

// ── Mock data — mirrors SEORankingEngine._build_mock_sites() ──────────────────

const entities = [
  {
    id: "seo_001",
    name: "Plomberie Leblanc SARL",
    sector: "Artisans & Bâtiment",
    domain: "plomberie-leblanc.fr",
    avg_position: 5,
    organic_traffic_monthly: 18400,
    keyword_count: 312,
    backlink_count: 890,
    domain_authority: 52.0,
    page_speed_mobile: 82.0,
    core_web_vitals_score: 78.0,
    indexation_rate: 94.0,
    local_seo_score: 74.0,
    composite_score: 83.30,
    risk_level: "critique",
  },
  {
    id: "seo_002",
    name: "Restaurant Le Gaulois",
    sector: "Restauration & Hôtellerie",
    domain: "legaulois-restaurant.fr",
    avg_position: 8,
    organic_traffic_monthly: 24700,
    keyword_count: 527,
    backlink_count: 1240,
    domain_authority: 61.0,
    page_speed_mobile: 75.0,
    core_web_vitals_score: 71.0,
    indexation_rate: 98.0,
    local_seo_score: 70.0,
    composite_score: 78.10,
    risk_level: "critique",
  },
  {
    id: "seo_003",
    name: "Cabinet Médical Marchand",
    sector: "Médical & Cabinets de Soin",
    domain: "cabinet-marchand.fr",
    avg_position: 12,
    organic_traffic_monthly: 9800,
    keyword_count: 184,
    backlink_count: 420,
    domain_authority: 44.0,
    page_speed_mobile: 68.0,
    core_web_vitals_score: 74.0,
    indexation_rate: 91.0,
    local_seo_score: 65.0,
    composite_score: 74.90,
    risk_level: "critique",
  },
  {
    id: "seo_004",
    name: "Auto Garage Martin",
    sector: "Garages & Concessionnaires",
    domain: "garage-martin.fr",
    avg_position: 35,
    organic_traffic_monthly: 5200,
    keyword_count: 98,
    backlink_count: 175,
    domain_authority: 31.0,
    page_speed_mobile: 45.0,
    core_web_vitals_score: 42.0,
    indexation_rate: 78.0,
    local_seo_score: 38.0,
    composite_score: 48.85,
    risk_level: "élevé",
  },
  {
    id: "seo_005",
    name: "Immo Provence",
    sector: "Agences Immobilières",
    domain: "immo-provence.fr",
    avg_position: 42,
    organic_traffic_monthly: 7100,
    keyword_count: 143,
    backlink_count: 312,
    domain_authority: 38.0,
    page_speed_mobile: 52.0,
    core_web_vitals_score: 48.0,
    indexation_rate: 85.0,
    local_seo_score: 30.0,
    composite_score: 48.40,
    risk_level: "élevé",
  },
  {
    id: "seo_006",
    name: "École de Langues LinguaMax",
    sector: "Écoles & Formation",
    domain: "linguamax.fr",
    avg_position: 65,
    organic_traffic_monthly: 3400,
    keyword_count: 67,
    backlink_count: 89,
    domain_authority: 22.0,
    page_speed_mobile: 30.0,
    core_web_vitals_score: 25.0,
    indexation_rate: 63.0,
    local_seo_score: 28.0,
    composite_score: 29.85,
    risk_level: "modéré",
  },
  {
    id: "seo_007",
    name: "Boulangerie Du Pain Quotidien",
    sector: "Artisans Boulangers",
    domain: "boulangerie-dupain.fr",
    avg_position: 88,
    organic_traffic_monthly: 820,
    keyword_count: 14,
    backlink_count: 23,
    domain_authority: 9.0,
    page_speed_mobile: 15.0,
    core_web_vitals_score: 10.0,
    indexation_rate: 41.0,
    local_seo_score: 8.0,
    composite_score: 11.45,
    risk_level: "faible",
  },
  {
    id: "seo_008",
    name: "Coiff & Style",
    sector: "Boutiques & Beauté",
    domain: "coiff-style.fr",
    avg_position: 92,
    organic_traffic_monthly: 510,
    keyword_count: 9,
    backlink_count: 11,
    domain_authority: 7.0,
    page_speed_mobile: 12.0,
    core_web_vitals_score: 8.0,
    indexation_rate: 35.0,
    local_seo_score: 5.0,
    composite_score: 8.40,
    risk_level: "faible",
  },
];

const summary = {
  total_sites: 8,
  avg_position: 43.38,
  avg_organic_traffic: 8741.25,
  avg_domain_authority: 33.0,
  sites_critique: 3,
  sites_eleve: 2,
  sites_modere: 1,
  sites_faible: 2,
  top_risk_site: "Plomberie Leblanc SARL",
  top_risk_score: 83.30,
  patterns_detected: [
    "pénalité détectée",
    "contenu dupliqué",
    "vitesse page insuffisante",
    "Core Web Vitals échoué",
    "classement local absent",
  ],
  avg_composite: 47.91,
  avg_estimated_seo_index: 4.79,
};

export async function GET() {
  if (!SWARM_API_URL) {
    return NextResponse.json(sealResponse({ entities, summary } as Record<string, unknown>));
  }
  try {
    const url = new URL(`${SWARM_API_URL}/api/seo-ranking`);
    const res = await fetch(url.toString(), { cache: "no-store" });
    if (res.ok) return NextResponse.json(sealResponse(await res.json() as Record<string, unknown>));
  } catch {}
  return NextResponse.json(sealResponse({ entities: [], summary: {} } as Record<string, unknown>), { status: 502 });
}
