import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[religious-persecution-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Religious Persecution Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/religious-persecution-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Religious Persecution Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Religious Persecution Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "RP-001", name: "RPDC — Bibles Contrebande, Exécutions Culte & Christianisme Interdit", country: "Asie du Nord-Est", sector: "Christianisme Peine de Mort, Bibles Contrebande Exécution, 70 000 Chrétiens Camps & Aucune Religion Autorisée Hors Culte Kim", composite_score: 91.6, state_religious_violence_score: 95.0, blasphemy_apostasy_criminalization_score: 92.0, minority_institutional_exclusion_score: 90.0, religious_persecution_impunity_score: 88.0, risk_level: "critique", primary_pattern: "genocide_confessionnel", key_signals: ["Génocide confessionnel de RPDC — destruction systématique d'une communauté religieuse par l'État incluant massacres, déportations et destruction des lieux de culte", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Saisir la CPI pour crime contre l'humanité à caractère religieux et activer la Convention pour la Prévention du Génocide"], estimated_religious_persecution_index: 9.16, last_updated: "2026-06-20" },
    { id: "RP-002", name: "Pakistan — Loi Blasphème 295-C & Minorités Chrétiennes/Ahmadis", country: "Asie du Sud", sector: "295-C Peine Mort Blasphème, Ahmadis Non-Musulmans Légalement, Asia Bibi Condamnée & 4000+ Accusés Blasphème 1987-2023", composite_score: 86.5, state_religious_violence_score: 85.0, blasphemy_apostasy_criminalization_score: 95.0, minority_institutional_exclusion_score: 85.0, religious_persecution_impunity_score: 80.0, risk_level: "critique", primary_pattern: "blaspheme_peine_mort", key_signals: ["Lois de blasphème à peine de mort de Pakistan — criminalisation de l'apostasie et du blasphème punissable de mort créant une terreur religieuse institutionnalisée", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Engager le Conseil des droits de l'homme de l'ONU pour résolution contraignante abolissant les lois de blasphème létales"], estimated_religious_persecution_index: 8.65, last_updated: "2026-06-20" },
    { id: "RP-003", name: "Myanmar/Rohingyas — Génocide Musulmans & Mosquées Détruites", country: "Asie du Sud-Est", sector: "Rohingyas Apatrides Loi 1982, 750+ Mosquées Détruites, Moines Nationalistes Ma Ba Tha & ONU Génocide Déclaré 2018", composite_score: 86.35, state_religious_violence_score: 92.0, blasphemy_apostasy_criminalization_score: 78.0, minority_institutional_exclusion_score: 85.0, religious_persecution_impunity_score: 90.0, risk_level: "critique", primary_pattern: "genocide_confessionnel", key_signals: ["Génocide confessionnel de Myanmar/Rohingyas — destruction systématique d'une communauté religieuse par l'État incluant massacres, déportations et destruction des lieux de culte", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Saisir la CPI pour crime contre l'humanité à caractère religieux et activer la Convention pour la Prévention du Génocide"], estimated_religious_persecution_index: 8.64, last_updated: "2026-06-20" },
    { id: "RP-004", name: "Chine/Falun Gong-Chrétiens — Église Maison Interdite & Prélèvement Organes", country: "Asie", sector: "10 000 Lieux Culte Démolis 2014-2020, Croix Abattues Zhejiang, Falun Gong Organes & Ouïghours Islam Interdit", composite_score: 83.1, state_religious_violence_score: 82.0, blasphemy_apostasy_criminalization_score: 82.0, minority_institutional_exclusion_score: 88.0, religious_persecution_impunity_score: 80.0, risk_level: "critique", primary_pattern: "discrimination_institutionnelle_religieuse", key_signals: ["Discrimination institutionnelle religieuse de Chine — exclusion systémique des minorités confessionnelles des droits civiques, emplois publics et protections légales", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Activer le Rapporteur Spécial ONU sur la liberté de religion pour mission d'enquête urgente"], estimated_religious_persecution_index: 8.31, last_updated: "2026-06-20" },
    { id: "RP-005", name: "Iran — Baha'is Persécutés, Apostasie Mort & Minorités", country: "MENA", sector: "Baha'is 300+ Exécutés Révolution, Apostasie Peine Mort Fatwas, Chrétiens Convertis Emprisonnés & Dervishes Gonabadi", composite_score: 56.0, state_religious_violence_score: 52.0, blasphemy_apostasy_criminalization_score: 65.0, minority_institutional_exclusion_score: 55.0, religious_persecution_impunity_score: 52.0, risk_level: "élevé", primary_pattern: "blaspheme_peine_mort", key_signals: ["Lois de blasphème à peine de mort d'Iran — fatwas d'apostasie et persécution systémique des Baha'is, chrétiens convertis et soufis par les autorités religieuses étatiques", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Engager le Conseil des droits de l'homme de l'ONU pour résolution contraignante abolissant les lois de blasphème létales"], estimated_religious_persecution_index: 5.6, last_updated: "2026-06-20" },
    { id: "RP-006", name: "Inde/BJP — Lois Anti-Conversion & Violences Anti-Musulmans", country: "Asie du Sud", sector: "Lois Anti-Conversion 12 États, Lynchages Vache Sacrée Impunis, Mosquées Démolies Gujarat & RSS Violences Documentées", composite_score: 56.0, state_religious_violence_score: 55.0, blasphemy_apostasy_criminalization_score: 52.0, minority_institutional_exclusion_score: 58.0, religious_persecution_impunity_score: 60.0, risk_level: "élevé", primary_pattern: "persecution_religieus_active", key_signals: ["Persécution religieuse active d'Inde/BJP — harcèlement, arrestations arbitraires et destruction de lieux de culte de minorités religieuses avec impunité étatique", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Sanctionner les responsables via Global Magnitsky Act et saisir la Commission internationale pour la liberté religieuse"], estimated_religious_persecution_index: 5.6, last_updated: "2026-06-20" },
    { id: "RP-007", name: "Égypte/Coptes — Discrimination Institutionnelle & Attaques Églises", country: "MENA/Afrique", sector: "Coptes 10% Population 0% Gouverneurs, Attentats Église Tanta 2017, Permis Construction Refusés & Quotas Discriminatoires", composite_score: 30.15, state_religious_violence_score: 28.0, blasphemy_apostasy_criminalization_score: 25.0, minority_institutional_exclusion_score: 38.0, religious_persecution_impunity_score: 30.0, risk_level: "modéré", primary_pattern: "discrimination_institutionnelle_religieuse", key_signals: ["Discrimination institutionnelle religieuse d'Égypte — exclusion systémique des Coptes des postes à responsabilité, obstacles à la construction d'églises et impunité partielle pour attentats", "Minorités religieuses ciblées — communautés confessionnelles subissant des violences systémiques, destructions de lieux de culte et exclusion des droits fondamentaux", "Activer le Rapporteur Spécial ONU sur la liberté de religion pour mission d'enquête urgente"], estimated_religious_persecution_index: 3.02, last_updated: "2026-06-20" },
    { id: "RP-008", name: "USCIRF/Rapporteur ONU — Liberté Religieuse & Dialogue Interconfessionnel", country: "Global", sector: "USCIRF Rapport Annuel 180 Pays, Rapporteur ONU Liberté Religion Article 18 & Alliance Civilisations ONU Dialogue", composite_score: 4.45, state_religious_violence_score: 5.0, blasphemy_apostasy_criminalization_score: 4.0, minority_institutional_exclusion_score: 3.0, religious_persecution_impunity_score: 6.0, risk_level: "faible", primary_pattern: "liberte_religieuse_exemplaire", key_signals: ["USCIRF/Rapporteur ONU incarne la liberté religieuse exemplaire — toutes les confessions protégées légalement, lieux de culte respectés et aucune criminalisation de l'apostasie", "Cadre normatif international — Article 18 DUDH, Pacte civil et politique et Déclaration sur l'intolérance religieuse créant des obligations contraignantes pour les États", "Partager les modèles législatifs de protection de la liberté religieuse et financer les mécanismes ONU de surveillance"], estimated_religious_persecution_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { genocide_confessionnel: 2, blaspheme_peine_mort: 2, discrimination_institutionnelle_religieuse: 2, persecution_religieus_active: 1, liberte_religieuse_exemplaire: 1 },
    top_risk_entities: ["RPDC — Bibles Contrebande, Exécutions Culte & Christianisme Interdit", "Pakistan — Loi Blasphème 295-C & Minorités Chrétiennes/Ahmadis", "Myanmar/Rohingyas — Génocide Musulmans & Mosquées Détruites"],
    critical_alerts: ["RPDC: génocide confessionnel", "Pakistan: lois blasphème peine de mort", "Myanmar/Rohingyas: génocide confessionnel", "Chine: discrimination institutionnelle religieuse"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "religious_persecution",
    confidence_score: 0.83,
    data_sources: ["uscirf_annual_report_countries_concern", "open_doors_world_watch_list", "un_special_rapporteur_religion_belief_reports"],
    entities,
    avg_estimated_religious_persecution_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
