import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[colonial-reparations-historical-justice-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/colonial-reparations-historical-justice-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CRHJ-001", name: "Belgique/Congo Free State Léopold II 10-15M Morts", country: "Europe Occidentale", sector: "Léopold II Congo Free State 1885-1908, 10-15M Morts, Mains Coupées Caoutchouc, Pillage Ivoire & Aucune Excuse Formelle à ce Jour", composite_score: 87.25, colonial_extractive_economic_harm_severity_score: 92.0, reparations_acknowledgment_deficit_gap_score: 88.0, historical_memory_denial_suppression_score: 85.0, transitional_justice_mechanism_absence_score: 82.0, risk_level: "critique", primary_pattern: "extractivisme_colonial_grave", key_signals: ["Extractivisme colonial critique de Belgique/Congo Free State Léopold II 10-15M Morts — pillage massif des ressources humaines et naturelles sans reconnaissance ni réparation, perpétuant des inégalités structurelles multigénérationnelles", "Violation continue des droits — le refus de réparations constitue une violation du droit international (Résolution ONU A/RES/60/147) et perpétue les dommages économiques et psychologiques des populations colonisées", "Déni mémoriel institutionnel — l'effacement des crimes coloniaux des récits officiels prive les victimes de reconnaissance et alimente des traumatismes collectifs non résolus"], estimated_colonial_reparations_historical_justice_index: 8.72, last_updated: "2026-06-21" },
    { id: "CRHJ-002", name: "France/Haïti Rançon Coloniale 150M Francs-Or", country: "Europe Occidentale", sector: "Haïti Indemnité 1825-1947, 150M Francs-Or, Dette Odieuse Payée Jusqu'en 1947, PIB Haïti Appauvri 115 Ans & Refus Réparations 2022", composite_score: 85.15, colonial_extractive_economic_harm_severity_score: 88.0, reparations_acknowledgment_deficit_gap_score: 85.0, historical_memory_denial_suppression_score: 82.0, transitional_justice_mechanism_absence_score: 85.0, risk_level: "critique", primary_pattern: "extractivisme_colonial_grave", key_signals: ["Extractivisme colonial critique de France/Haïti Rançon Coloniale 150M Francs-Or — pillage massif des ressources humaines et naturelles sans reconnaissance ni réparation, perpétuant des inégalités structurelles multigénérationnelles", "Violation continue des droits — le refus de réparations constitue une violation du droit international (Résolution ONU A/RES/60/147) et perpétue les dommages économiques et psychologiques des populations colonisées", "Déni mémoriel institutionnel — l'effacement des crimes coloniaux des récits officiels prive les victimes de reconnaissance et alimente des traumatismes collectifs non résolus"], estimated_colonial_reparations_historical_justice_index: 8.52, last_updated: "2026-06-21" },
    { id: "CRHJ-003", name: "Royaume-Uni/Kenya Mau Mau Torture Systématique", country: "Europe Occidentale", sector: "Mau Mau Camps 1952-1960, 1500 Pendaisons, Torture Systématique Documentée, Excuses Partielles 2013 & 19,9M£ Indemnisation Insuffisante", composite_score: 80.1, colonial_extractive_economic_harm_severity_score: 82.0, reparations_acknowledgment_deficit_gap_score: 78.0, historical_memory_denial_suppression_score: 80.0, transitional_justice_mechanism_absence_score: 80.0, risk_level: "critique", primary_pattern: "deficit_reconnaissance_reparations", key_signals: ["Extractivisme colonial critique de Royaume-Uni/Kenya Mau Mau Torture Systématique — pillage massif des ressources humaines et naturelles sans reconnaissance ni réparation, perpétuant des inégalités structurelles multigénérationnelles", "Violation continue des droits — le refus de réparations constitue une violation du droit international (Résolution ONU A/RES/60/147) et perpétue les dommages économiques et psychologiques des populations colonisées", "Déni mémoriel institutionnel — l'effacement des crimes coloniaux des récits officiels prive les victimes de reconnaissance et alimente des traumatismes collectifs non résolus"], estimated_colonial_reparations_historical_justice_index: 8.01, last_updated: "2026-06-21" },
    { id: "CRHJ-004", name: "Allemagne/Namibie Génocide Herero-Nama 1904-1908", country: "Europe Occidentale", sector: "Premier Génocide 20e Siècle, 65-80% Herero Exterminés, Reconnaissance 2021, 1.1B€ Refusé par Communautés & Processus Négociation Bloqué", composite_score: 75.9, colonial_extractive_economic_harm_severity_score: 78.0, reparations_acknowledgment_deficit_gap_score: 74.0, historical_memory_denial_suppression_score: 76.0, transitional_justice_mechanism_absence_score: 75.0, risk_level: "critique", primary_pattern: "deficit_reconnaissance_reparations", key_signals: ["Extractivisme colonial critique de Allemagne/Namibie Génocide Herero-Nama 1904-1908 — pillage massif des ressources humaines et naturelles sans reconnaissance ni réparation, perpétuant des inégalités structurelles multigénérationnelles", "Violation continue des droits — le refus de réparations constitue une violation du droit international (Résolution ONU A/RES/60/147) et perpétue les dommages économiques et psychologiques des populations colonisées", "Déni mémoriel institutionnel — l'effacement des crimes coloniaux des récits officiels prive les victimes de reconnaissance et alimente des traumatismes collectifs non résolus"], estimated_colonial_reparations_historical_justice_index: 7.59, last_updated: "2026-06-21" },
    { id: "CRHJ-005", name: "Pays-Bas/Suriname Esclavage Colonial Reconnu", country: "Europe Occidentale", sector: "600.000 Esclaves Suriname, Excuses Officielles Dec 2022, 200M€ Fonds Commémoratif Insuffisant, Descendants Réclament Réparations Économiques", composite_score: 52.1, colonial_extractive_economic_harm_severity_score: 52.0, reparations_acknowledgment_deficit_gap_score: 58.0, historical_memory_denial_suppression_score: 48.0, transitional_justice_mechanism_absence_score: 50.0, risk_level: "élevé", primary_pattern: "deficit_reconnaissance_reparations", key_signals: ["Déficit majeur de réparations de Pays-Bas/Suriname Esclavage Colonial Reconnu — reconnaissance partielle sans mécanismes concrets de réparation ni processus de justice transitionnelle incluant les communautés affectées", "Archives et biens culturels pillés — des millions d'objets culturels et documents historiques restent détenus dans des institutions des anciens États colonisateurs sans plan de restitution", "Justice transitionnelle insuffisante — les commissions de vérité et les dialogues bilatéraux restent symboliques sans financement ni pouvoir de décision sur les réparations"], estimated_colonial_reparations_historical_justice_index: 5.21, last_updated: "2026-06-21" },
    { id: "CRHJ-006", name: "Espagne/Amériques Conquistadors Génocides Autochtones", country: "Europe Occidentale", sector: "90% Population Autochtone Amérique 1500-1600, 56M Morts, Pillage Or/Argent, Aucune Reconnaissance Formelle & Refus Débat Réparations", composite_score: 46.55, colonial_extractive_economic_harm_severity_score: 48.0, reparations_acknowledgment_deficit_gap_score: 45.0, historical_memory_denial_suppression_score: 50.0, transitional_justice_mechanism_absence_score: 42.0, risk_level: "élevé", primary_pattern: "mecanisme_justice_transitionnelle_absent", key_signals: ["Déficit majeur de réparations de Espagne/Amériques Conquistadors Génocides Autochtones — reconnaissance partielle sans mécanismes concrets de réparation ni processus de justice transitionnelle incluant les communautés affectées", "Archives et biens culturels pillés — des millions d'objets culturels et documents historiques restent détenus dans des institutions des anciens États colonisateurs sans plan de restitution", "Justice transitionnelle insuffisante — les commissions de vérité et les dialogues bilatéraux restent symboliques sans financement ni pouvoir de décision sur les réparations"], estimated_colonial_reparations_historical_justice_index: 4.66, last_updated: "2026-06-21" },
    { id: "CRHJ-007", name: "USA/Jim Crow Esclavage Réparations H.R.40", country: "Amérique du Nord", sector: "246 Ans Esclavage, Jim Crow Ségrégation, H.R.40 Commission Réparations Bloquée, Wealth Gap 8x Blancs/Noirs & Tulsa Race Massacre 1921 Non-Compensé", composite_score: 28.65, colonial_extractive_economic_harm_severity_score: 28.0, reparations_acknowledgment_deficit_gap_score: 32.0, historical_memory_denial_suppression_score: 25.0, transitional_justice_mechanism_absence_score: 30.0, risk_level: "modéré", primary_pattern: "mecanisme_justice_transitionnelle_absent", key_signals: ["Progrès fragiles de USA/Jim Crow Esclavage Réparations H.R.40 — démarches symboliques de reconnaissance historique sans réparations substantielles ni institutionnalisation des processus de mémoire collective", "Risques de régression — les avancées en matière de reconnaissance peuvent être inversées par des gouvernements nationalistes hostiles aux débats sur l'histoire coloniale", "Inégalités persistantes — les écarts de développement entre anciens États colonisateurs et colonisés restent structurellement liés aux dynamiques extractivistes du passé"], estimated_colonial_reparations_historical_justice_index: 2.87, last_updated: "2026-06-21" },
    { id: "CRHJ-008", name: "ONU/Initiatives Réparations Droits Humains", country: "Global", sector: "Résolution A/RES/60/147 2005, Déclaration Durban 2001, Rapporteur Spécial Réparations, Forum Permanente Peuples Autochtones & Fonds Volontaire Limité", composite_score: 9.5, colonial_extractive_economic_harm_severity_score: 8.0, reparations_acknowledgment_deficit_gap_score: 12.0, historical_memory_denial_suppression_score: 10.0, transitional_justice_mechanism_absence_score: 8.0, risk_level: "faible", primary_pattern: "engagement_justice_historique_exemplaire", key_signals: ["ONU/Initiatives Réparations Droits Humains incarne un engagement exemplaire pour la justice historique — processus de réparation concret, institutionnalisé et financé avec participation des communautés affectées", "Standards de réconciliation historique respectés — restitution des archives et biens culturels, programmes éducatifs décoloniaux et fonds de réparation économique opérationnels", "Modèle de justice transitionnelle exportable — partage d'expertise avec d'autres États colonisateurs et soutien aux mécanismes ONU de suivi des réparations historiques"], estimated_colonial_reparations_historical_justice_index: 0.95, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { extractivisme_colonial_grave: 2, deni_memoire_historique: 0, deficit_reconnaissance_reparations: 3, mecanisme_justice_transitionnelle_absent: 2, engagement_justice_historique_exemplaire: 1 },
    top_risk_entities: ["Belgique/Congo Free State Léopold II 10-15M Morts", "France/Haïti Rançon Coloniale 150M Francs-Or", "Royaume-Uni/Kenya Mau Mau Torture Systématique", "Allemagne/Namibie Génocide Herero-Nama 1904-1908"],
    critical_alerts: ["Belgique/Congo: extractivisme colonial grave", "France/Haïti: extractivisme colonial grave", "Royaume-Uni/Kenya: deficit reconnaissance reparations", "Allemagne/Namibie: deficit reconnaissance reparations"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "colonial_reparations_historical_justice",
    confidence_score: 0.85,
    data_sources: ["un_resolution_60_147_reparations_2005", "durban_declaration_programme_action_2001", "historical_archives_colonial_crimes_documentation", "transitional_justice_database_ictj"],
    entities,
    avg_estimated_colonial_reparations_historical_justice_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
