export const competitors = [
  {
    id: "1",
    name: "Salesforce",
    website: "salesforce.com",
    industry: "CRM",
    description: "Leader mondial du CRM cloud, offrant une suite complète d'outils de vente et de service client.",
    threatLevel: "high" as const,
    logo: "SF",
    color: "#00A1E0",
    founded: 1999,
    employees: "70 000+",
    revenue: "31,4 Md$",
    marketShare: 23.8,
    lastUpdated: "2026-06-15",
    pricing: [
      { name: "Starter", price: 25, currency: "€", interval: "mois", features: ["Contact Management", "Email Integration", "Mobile App"] },
      { name: "Professional", price: 80, currency: "€", interval: "mois", features: ["Tout Starter", "Collaboration Tools", "API Access", "Forecasting"] },
      { name: "Enterprise", price: 300, currency: "€", interval: "mois", features: ["Tout Pro", "Advanced Analytics", "Custom Workflows", "AI Features"] },
      { name: "Unlimited", price: 330, currency: "€", interval: "mois", features: ["Tout Enterprise", "Unlimited Customization", "Premier Support"] },
    ],
    features: [
      { name: "Intelligence Artificielle (Einstein)", available: true, quality: "Excellent" },
      { name: "Automatisation des ventes", available: true, quality: "Excellent" },
      { name: "Intégration email", available: true, quality: "Bien" },
      { name: "Rapports avancés", available: true, quality: "Excellent" },
      { name: "Application mobile", available: true, quality: "Bien" },
      { name: "API ouverte", available: true, quality: "Excellent" },
    ],
    news: [
      { date: "2026-06-10", title: "Salesforce lance Einstein Copilot v3", type: "product" },
      { date: "2026-05-20", title: "Augmentation des prix de 12%", type: "pricing" },
      { date: "2026-04-15", title: "Acquisition de DataRobot pour 1,2 Md$", type: "acquisition" },
    ],
    priceHistory: [75, 78, 80, 80, 85, 87, 88, 90, 92, 95, 98, 100],
  },
  {
    id: "2",
    name: "HubSpot",
    website: "hubspot.com",
    industry: "CRM / Marketing",
    description: "Plateforme inbound marketing et CRM populaire auprès des PME, avec des outils marketing et ventes intégrés.",
    threatLevel: "high" as const,
    logo: "HS",
    color: "#FF7A59",
    founded: 2006,
    employees: "7 000+",
    revenue: "2,2 Md$",
    marketShare: 8.4,
    lastUpdated: "2026-06-14",
    pricing: [
      { name: "Gratuit", price: 0, currency: "€", interval: "mois", features: ["CRM de base", "Email limité", "Formulaires"] },
      { name: "Starter", price: 20, currency: "€", interval: "mois", features: ["Tout Gratuit", "Email Marketing", "Live Chat"] },
      { name: "Sales Hub Professional", price: 100, currency: "€", interval: "mois", features: ["Tout Starter", "Automation avancée", "Reporting"] },
      { name: "Enterprise", price: 3600, currency: "€", interval: "mois", features: ["Tout Pro", "Teams", "Custom Objects"] },
    ],
    features: [
      { name: "Intelligence Artificielle", available: true, quality: "Bien" },
      { name: "Automatisation marketing", available: true, quality: "Excellent" },
      { name: "Intégration email", available: true, quality: "Excellent" },
      { name: "Rapports avancés", available: true, quality: "Bien" },
      { name: "Application mobile", available: true, quality: "Bien" },
      { name: "API ouverte", available: true, quality: "Bien" },
    ],
    news: [
      { date: "2026-06-05", title: "HubSpot AI intègre GPT-5", type: "product" },
      { date: "2026-05-12", title: "Nouveau partenariat avec Google Workspace", type: "partnership" },
    ],
    priceHistory: [18, 18, 19, 19, 20, 20, 20, 21, 21, 22, 22, 20],
  },
  {
    id: "3",
    name: "Pipedrive",
    website: "pipedrive.com",
    industry: "CRM Ventes",
    description: "CRM orienté ventes conçu pour les équipes commerciales, avec une interface visuelle de pipeline.",
    threatLevel: "medium" as const,
    logo: "PD",
    color: "#2C3E50",
    founded: 2010,
    employees: "900+",
    revenue: "100 M$",
    marketShare: 3.1,
    lastUpdated: "2026-06-12",
    pricing: [
      { name: "Essential", price: 15, currency: "€", interval: "mois", features: ["Pipeline Management", "Import/Export", "API Access"] },
      { name: "Advanced", price: 29, currency: "€", interval: "mois", features: ["Tout Essential", "Email Sync", "Automations"] },
      { name: "Professional", price: 59, currency: "€", interval: "mois", features: ["Tout Advanced", "Revenue Forecasting", "AI Insights"] },
      { name: "Power", price: 69, currency: "€", interval: "mois", features: ["Tout Pro", "Project Planning", "Phone Support"] },
    ],
    features: [
      { name: "Intelligence Artificielle", available: true, quality: "Moyen" },
      { name: "Automatisation des ventes", available: true, quality: "Bien" },
      { name: "Intégration email", available: true, quality: "Bien" },
      { name: "Rapports avancés", available: false, quality: "-" },
      { name: "Application mobile", available: true, quality: "Excellent" },
      { name: "API ouverte", available: true, quality: "Bien" },
    ],
    news: [
      { date: "2026-05-30", title: "Pipedrive lance AI Sales Assistant", type: "product" },
    ],
    priceHistory: [12, 12, 13, 14, 14, 15, 15, 15, 16, 16, 17, 15],
  },
  {
    id: "4",
    name: "Zoho CRM",
    website: "zoho.com",
    industry: "CRM Suite",
    description: "Suite complète d'applications business avec CRM intégré, solution économique pour les PME.",
    threatLevel: "medium" as const,
    logo: "ZO",
    color: "#E42527",
    founded: 1996,
    employees: "15 000+",
    revenue: "1 Md$",
    marketShare: 4.2,
    lastUpdated: "2026-06-10",
    pricing: [
      { name: "Gratuit", price: 0, currency: "€", interval: "mois", features: ["3 utilisateurs", "Leads", "Contacts"] },
      { name: "Standard", price: 14, currency: "€", interval: "mois", features: ["Scoring", "Workflows", "Campagnes"] },
      { name: "Professional", price: 23, currency: "€", interval: "mois", features: ["Inventory", "Validation Rules", "Portals"] },
      { name: "Enterprise", price: 40, currency: "€", interval: "mois", features: ["AI (Zia)", "Custom Modules", "Multi-currency"] },
    ],
    features: [
      { name: "Intelligence Artificielle (Zia)", available: true, quality: "Bien" },
      { name: "Automatisation des ventes", available: true, quality: "Bien" },
      { name: "Intégration email", available: true, quality: "Moyen" },
      { name: "Rapports avancés", available: true, quality: "Bien" },
      { name: "Application mobile", available: true, quality: "Moyen" },
      { name: "API ouverte", available: true, quality: "Bien" },
    ],
    news: [
      { date: "2026-06-01", title: "Zoho One intègre 55 nouvelles applications", type: "product" },
    ],
    priceHistory: [12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 15, 14],
  },
  {
    id: "5",
    name: "Monday.com",
    website: "monday.com",
    industry: "Gestion de projet / CRM",
    description: "Plateforme de gestion du travail avec capacités CRM, populaire pour la gestion de projets et ventes.",
    threatLevel: "low" as const,
    logo: "MN",
    color: "#F6517C",
    founded: 2012,
    employees: "1 800+",
    revenue: "729 M$",
    marketShare: 2.9,
    lastUpdated: "2026-06-08",
    pricing: [
      { name: "Individuel", price: 0, currency: "€", interval: "mois", features: ["2 sièges", "Tableaux de bord", "200 items"] },
      { name: "Basic", price: 9, currency: "€", interval: "mois", features: ["Items illimités", "5 Go stockage", "Viewers illimités"] },
      { name: "Standard", price: 12, currency: "€", interval: "mois", features: ["Tout Basic", "Timeline", "Intégrations"] },
      { name: "Pro", price: 19, currency: "€", interval: "mois", features: ["Tout Standard", "Automatisations", "Formules"] },
    ],
    features: [
      { name: "Intelligence Artificielle", available: true, quality: "Moyen" },
      { name: "Automatisation des ventes", available: false, quality: "-" },
      { name: "Intégration email", available: true, quality: "Moyen" },
      { name: "Rapports avancés", available: true, quality: "Moyen" },
      { name: "Application mobile", available: true, quality: "Bien" },
      { name: "API ouverte", available: true, quality: "Bien" },
    ],
    news: [
      { date: "2026-05-18", title: "Monday AI automatise la création de tasks", type: "product" },
    ],
    priceHistory: [8, 8, 9, 9, 9, 10, 10, 11, 11, 12, 12, 12],
  },
];

export const alerts = [
  { id: "1", type: "pricing", message: "Salesforce augmente ses prix de 12% sur le plan Enterprise", competitorId: "1", competitorName: "Salesforce", isRead: false, date: "2026-06-15" },
  { id: "2", type: "feature", message: "HubSpot lance une nouvelle fonctionnalité IA intégrée à GPT-5", competitorId: "2", competitorName: "HubSpot", isRead: false, date: "2026-06-10" },
  { id: "3", type: "acquisition", message: "Salesforce acquiert DataRobot pour 1,2 Md$", competitorId: "1", competitorName: "Salesforce", isRead: false, date: "2026-06-08" },
  { id: "4", type: "product", message: "Pipedrive lance AI Sales Assistant en version bêta", competitorId: "3", competitorName: "Pipedrive", isRead: true, date: "2026-06-05" },
  { id: "5", type: "partnership", message: "HubSpot signe un partenariat stratégique avec Google Workspace", competitorId: "2", competitorName: "HubSpot", isRead: true, date: "2026-05-28" },
  { id: "6", type: "acquisition", message: "Salesforce acquiert Spiff pour 419M$ — implications directes sur votre segment CPQ", competitorId: "sf1", competitorName: "Salesforce", date: "2026-06-15", isRead: false },
  { id: "7", type: "partnership", message: "HubSpot annonce un partenariat stratégique avec Microsoft Teams — intégration native Q3 2026", competitorId: "hs1", competitorName: "HubSpot", date: "2026-06-14", isRead: false },
  { id: "8", type: "product", message: "Monday.com déploie Monday AI en disponibilité générale", competitorId: "5", competitorName: "Monday.com", isRead: true, date: "2026-05-10" },
];

export const reports = [
  {
    id: "1",
    title: "Analyse concurrentielle Q2 2026",
    description: "Vue d'ensemble complète du paysage concurrentiel CRM pour le deuxième trimestre 2026.",
    createdAt: "2026-06-01",
    pages: 24,
    status: "ready",
  },
  {
    id: "2",
    title: "Comparaison des prix — Juin 2026",
    description: "Analyse détaillée des stratégies de tarification de tous les concurrents surveillés.",
    createdAt: "2026-05-15",
    pages: 12,
    status: "ready",
  },
  {
    id: "3",
    title: "Rapport de fonctionnalités IA",
    description: "Comparaison des capacités d'intelligence artificielle des principaux CRM du marché.",
    createdAt: "2026-04-30",
    pages: 18,
    status: "ready",
  },
];

export const stats = {
  competitorsTracked: 5,
  activeAlerts: 3,
  reportsGenerated: 3,
  marketScore: 74,
  slaUptime: 99.8,
  avgResponseTime: "< 2h",
};
