import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[food-security-weaponization-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Food Security Weaponization Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/food-security-weaponization-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Food Security Weaponization Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Food Security Weaponization Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "FS-001", name: "Russie — Blocus Mer Noire & Arme Céréalière Ukraine", country: "Europe de l'Est", sector: "Blocus Céréalier 2022 345M Personnes Menacées, Missiles Ports Odessa & Mines Grain Deal ONU Saboté", composite_score: 86.45, grain_export_weaponization_score: 92.0, food_aid_manipulation_score: 85.0, agricultural_sanctions_score: 80.0, famine_induction_score: 88.0, risk_level: "critique", primary_pattern: "famine_induite_politique", key_signals: ["Weaponisation alimentaire de Russie — blocus délibéré des exportations céréalières ukrainiennes menaçant 345 millions de personnes dans 82 pays", "Criminalisation de la faim — blocus alimentaire actif, détournement de l'aide humanitaire et manipulation des marchés céréaliers mondiaux", "Violation du droit humanitaire — l'utilisation de la famine contre des civils constitue un crime de guerre selon le droit international depuis 2018"], estimated_food_security_weaponization_index: 8.65, last_updated: "2026-06-20" },
    { id: "FS-002", name: "Chine — Monopole Réserves & Terres Agricoles Africaines", country: "Asie", sector: "70% Réserves Mondiales Blé/Riz/Maïs, 10M Ha Terres Africaines Achetées & BRI Dépendances Alimentaires", composite_score: 82.65, grain_export_weaponization_score: 88.0, food_aid_manipulation_score: 80.0, agricultural_sanctions_score: 85.0, famine_induction_score: 75.0, risk_level: "critique", primary_pattern: "weaponisation_cereales", key_signals: ["Weaponisation alimentaire de Chine — monopole sur 70% des réserves mondiales de céréales et achat massif de terres agricoles africaines créant des dépendances alimentaires stratégiques", "Criminalisation de la faim — blocus alimentaire actif, détournement de l'aide humanitaire et manipulation des marchés céréaliers mondiaux", "Violation du droit humanitaire — l'utilisation de la famine contre des civils constitue un crime de guerre selon le droit international depuis 2018"], estimated_food_security_weaponization_index: 8.27, last_updated: "2026-06-20" },
    { id: "FS-003", name: "Yémen & Soudan — Blocus Militaire & Famine Induite", country: "MENA/Afrique", sector: "Yémen 21M Personnes Insécurité Alimentaire, Soudan 25M & Blocus Saoudien/RSF Détournement Aide PAM", composite_score: 79.0, grain_export_weaponization_score: 65.0, food_aid_manipulation_score: 90.0, agricultural_sanctions_score: 72.0, famine_induction_score: 95.0, risk_level: "critique", primary_pattern: "manipulation_aide_alimentaire", key_signals: ["Weaponisation alimentaire de Yémen & Soudan — blocus militaires induisant des famines massives touchant 46 millions de civils privés d'aide humanitaire", "Criminalisation de la faim — blocus alimentaire actif, détournement de l'aide humanitaire et manipulation des marchés céréaliers mondiaux", "Violation du droit humanitaire — l'utilisation de la famine contre des civils constitue un crime de guerre selon le droit international depuis 2018"], estimated_food_security_weaponization_index: 7.9, last_updated: "2026-06-20" },
    { id: "FS-004", name: "RPDC — Malnutrition Systémique & Contrôle Distribution", country: "Asie", sector: "42% Population Malnutrie, PDS Distribution Politique-Dépendante & Détournement Aide Alimentaire Internationale", composite_score: 77.5, grain_export_weaponization_score: 80.0, food_aid_manipulation_score: 78.0, agricultural_sanctions_score: 68.0, famine_induction_score: 85.0, risk_level: "critique", primary_pattern: "pression_alimentaire_strategique", key_signals: ["Weaponisation alimentaire de RPDC — 42% de la population en malnutrition chronique utilisée comme outil de contrôle politique via le système PDS", "Criminalisation de la faim — blocus alimentaire actif, détournement de l'aide humanitaire et manipulation des marchés céréaliers mondiaux", "Violation du droit humanitaire — l'utilisation de la famine contre des civils constitue un crime de guerre selon le droit international depuis 2018"], estimated_food_security_weaponization_index: 7.75, last_updated: "2026-06-20" },
    { id: "FS-005", name: "Éthiopie & Tigré — Famine comme Arme de Guerre", country: "Afrique de l'Est", sector: "Siège Tigré 2020-2022 500K Famine, Blocage Convois PAM & Criminalisation Aide Humanitaire Documentée", composite_score: 56.1, grain_export_weaponization_score: 55.0, food_aid_manipulation_score: 60.0, agricultural_sanctions_score: 52.0, famine_induction_score: 58.0, risk_level: "élevé", primary_pattern: "pression_alimentaire_strategique", key_signals: ["Pression alimentaire stratégique de Éthiopie & Tigré — utilisation documentée du blocage de l'aide alimentaire comme arme de guerre dans le conflit du Tigré", "Dépendance alimentaire exploitée — les États importateurs de denrées subissent une vulnérabilité structurelle face aux exportateurs dominants", "Risque de crise alimentaire induite — tout blocage des exportations déclencherait une cascade de pénuries alimentaires dans les pays dépendants"], estimated_food_security_weaponization_index: 5.61, last_updated: "2026-06-20" },
    { id: "FS-006", name: "USA & Occident — Sanctions Agricoles Stratégiques", country: "Amérique du Nord", sector: "Sanctions Cuba/Iran/Russie Volet Agricole, SWIFT Restrictions Achats Alimentaires & Embargo Dual-Use", composite_score: 52.1, grain_export_weaponization_score: 52.0, food_aid_manipulation_score: 48.0, agricultural_sanctions_score: 62.0, famine_induction_score: 45.0, risk_level: "élevé", primary_pattern: "pression_alimentaire_strategique", key_signals: ["Pression alimentaire stratégique de USA & Occident — sanctions économiques incluant des restrictions aux importations alimentaires pouvant impacter la sécurité alimentaire des populations civiles", "Dépendance alimentaire exploitée — les États importateurs de denrées subissent une vulnérabilité structurelle face aux exportateurs dominants", "Risque de crise alimentaire induite — tout blocage des exportations déclencherait une cascade de pénuries alimentaires dans les pays dépendants"], estimated_food_security_weaponization_index: 5.21, last_updated: "2026-06-20" },
    { id: "FS-007", name: "Inde — Interdictions Export Riz/Blé & Chocs Marchés", country: "Asie du Sud", sector: "Ban Export Riz 2023 Choc Prix Mondial, Restrictions Blé & Accaparement Terres Népal/Bangladesh", composite_score: 27.8, grain_export_weaponization_score: 28.0, food_aid_manipulation_score: 25.0, agricultural_sanctions_score: 35.0, famine_induction_score: 22.0, risk_level: "modéré", primary_pattern: "pression_alimentaire_strategique", key_signals: ["Vulnérabilité alimentaire de Inde — interdictions d'exportation de riz et de blé créant des chocs de prix mondiaux affectant les pays à faibles revenus", "Filets de sécurité insuffisants — stocks stratégiques sous-dimensionnés et capacités agricoles locales insuffisantes pour absorber les chocs externes", "Risque de pression alimentaire — la concentration des exportations mondiales de denrées crée des vulnérabilités structurelles exploitables"], estimated_food_security_weaponization_index: 2.78, last_updated: "2026-06-20" },
    { id: "FS-008", name: "PAM & FAO — Sécurité Alimentaire Mondiale Coopérative", country: "Global", sector: "PAM 137M Personnes Assistées, FAO Monitoring Récoltes Mondial & SMIAR Système Alerte Précoce 92 Pays", composite_score: 4.45, grain_export_weaponization_score: 5.0, food_aid_manipulation_score: 4.0, agricultural_sanctions_score: 3.0, famine_induction_score: 6.0, risk_level: "faible", primary_pattern: "securite_alimentaire_cooperative", key_signals: ["PAM & FAO incarne la sécurité alimentaire coopérative — financement du PAM, contribution à la FAO et systèmes d'alerte précoce efficaces", "Distribution alimentaire équitable — mécanismes d'urgence humanitaire indépendants des pressions politiques et accès universel à l'aide alimentaire", "Modèle de résilience alimentaire — stocks stratégiques nationaux, diversification des fournisseurs et aide internationale inconditionnelle"], estimated_food_security_weaponization_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { famine_induite_politique: 1, weaponisation_cereales: 1, manipulation_aide_alimentaire: 1, pression_alimentaire_strategique: 4, securite_alimentaire_cooperative: 1 },
    top_risk_entities: ["Russie — Blocus Mer Noire & Arme Céréalière Ukraine", "Chine — Monopole Réserves & Terres Agricoles Africaines", "Yémen & Soudan — Blocus Militaire & Famine Induite"],
    critical_alerts: ["Russie: famine induite politique", "Chine: weaponisation céréales", "Yémen & Soudan: manipulation aide alimentaire", "RPDC: pression alimentaire stratégique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "food_security_weaponization",
    confidence_score: 0.81,
    data_sources: ["wfp_global_food_crisis_report", "fao_food_security_indicators", "fews_net_famine_early_warning"],
    entities,
    avg_estimated_food_security_weaponization_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
