import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[minority-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Minority Rights Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/minority-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Minority Rights Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Minority Rights Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "MR-001", name: "Chine/Ouïghours — 1M+ Rééducation Xinjiang, Langue/Religion Interdites & Surveillance Totale", country: "Asie du Nord-Est", sector: "1M+ Ouïghours Internés Camps Rééducation Xinjiang, Langue Arabe/Ouïghoure Interdite École, Mosquées Démolies, Surveillance Biométrique Totale & Transferts Forcés Usines", composite_score: 93.0, cultural_linguistic_suppression_score: 95.0, political_exclusion_score: 92.0, economic_marginalization_score: 90.0, physical_security_threat_score: 95.0, risk_level: "critique", primary_pattern: "suppression_culturelle_linguistique", key_signals: ["Violation des droits des minorités documentée — Chine/Ouïghours avec score composite 93.0/100 révélant une suppression systémique violant l'Article 27 du PIDCP et la Déclaration ONU sur les droits des minorités de 1992", "Suppression culturelle-linguistique (95.0/100) — l'effacement de la langue et de la culture ouïghoure constitue une forme de génocide culturel selon la définition élargie de la Convention de 1948", "Activer le Comité consultatif du Conseil des droits de l'homme sur les minorités et exiger l'application effective de la Déclaration ONU 1992 sur les droits des personnes appartenant à des minorités nationales, ethniques, religieuses et linguistiques"], estimated_minority_rights_index: 9.3, last_updated: "2026-06-20" },
    { id: "MR-002", name: "Russie/Tatars Crimée-Minorités — Langues Supprimées, Déportations & Répression Post-2014", country: "Europe de l'Est", sector: "Tatars Crimée Langue/Médias Interdits Post-2014, Medjlis Banni Organisation, Déportations Activistes, Tchétchénie Minorités Linguistiques Supprimées & Minorités Sibériennes Marginalisées", composite_score: 86.5, cultural_linguistic_suppression_score: 88.0, political_exclusion_score: 85.0, economic_marginalization_score: 85.0, physical_security_threat_score: 88.0, risk_level: "critique", primary_pattern: "suppression_culturelle_linguistique", key_signals: ["Violation des droits des minorités documentée — Russie/Tatars Crimée-Minorités avec score composite 86.5/100 révélant une suppression systémique violant l'Article 27 du PIDCP et la Déclaration ONU sur les droits des minorités de 1992", "Suppression culturelle-linguistique (88.0/100) — l'effacement des langues tatare et des minorités sibériennes constitue une forme de génocide culturel selon la définition élargie de la Convention de 1948", "Activer le Comité consultatif du Conseil des droits de l'homme sur les minorités et exiger l'application effective de la Déclaration ONU 1992 sur les droits des personnes appartenant à des minorités nationales, ethniques, religieuses et linguistiques"], estimated_minority_rights_index: 8.65, last_updated: "2026-06-20" },
    { id: "MR-003", name: "Myanmar/Rohingya-Karen — Langues Effacées, Apatridie & Cultures Détruites", country: "Asie du Sud-Est", sector: "Rohingya Langue/Culture Effacées État Rakhine, Karen/Kachin Langues Supprimées Écoles, Apatridie Institutionnalisée & Tatmadaw Attaques Villages Minoritaires Documentées", composite_score: 85.15, cultural_linguistic_suppression_score: 85.0, political_exclusion_score: 88.0, economic_marginalization_score: 85.0, physical_security_threat_score: 82.0, risk_level: "critique", primary_pattern: "exclusion_politique_minorites", key_signals: ["Violation des droits des minorités documentée — Myanmar/Rohingya-Karen avec score composite 85.15/100 révélant une suppression systémique violant l'Article 27 du PIDCP et la Déclaration ONU sur les droits des minorités de 1992", "Suppression culturelle-linguistique (85.0/100) — l'effacement de la langue et de la culture rohingya et karen constitue une forme de génocide culturel selon la définition élargie de la Convention de 1948", "Activer le Comité consultatif du Conseil des droits de l'homme sur les minorités et exiger l'application effective de la Déclaration ONU 1992 sur les droits des personnes appartenant à des minorités nationales, ethniques, religieuses et linguistiques"], estimated_minority_rights_index: 8.52, last_updated: "2026-06-20" },
    { id: "MR-004", name: "Turquie/Kurdes — Langue Kurde Restrictions, HDP/DEM Réprimé & 40 000 Morts Conflit", country: "MENA/Europe", sector: "Langue Kurde Interdite Éducation Publique Partiellement, HDP/DEM Parti Pro-Kurde 12 Ministres Emprisonnés, 40 000 Morts Conflit PKK 1984-2024 & Maires Kurdes Élus Révoqués", composite_score: 82.35, cultural_linguistic_suppression_score: 82.0, political_exclusion_score: 85.0, economic_marginalization_score: 82.0, physical_security_threat_score: 80.0, risk_level: "critique", primary_pattern: "exclusion_politique_minorites", key_signals: ["Violation des droits des minorités documentée — Turquie/Kurdes avec score composite 82.35/100 révélant une suppression systémique violant l'Article 27 du PIDCP et la Déclaration ONU sur les droits des minorités de 1992", "Suppression culturelle-linguistique (82.0/100) — les restrictions à la langue kurde dans l'éducation publique constituent une violation directe de l'Article 27 du PIDCP ratifié par la Turquie", "Activer le Comité consultatif du Conseil des droits de l'homme sur les minorités et exiger l'application effective de la Déclaration ONU 1992 sur les droits des personnes appartenant à des minorités nationales, ethniques, religieuses et linguistiques"], estimated_minority_rights_index: 8.24, last_updated: "2026-06-20" },
    { id: "MR-005", name: "Éthiopie/Tigréens — Langue Tigrigna Marginalisée Post-Conflit, Blocus & Discrimination", country: "Afrique de l'Est", sector: "Tigréens Post-Conflit 2020-22 Langue Tigrigna Marginalisée Administration, Blocus Économique, Accès Services Réduit & Diaspora Tigréenne Poursuite Hors Frontières", composite_score: 54.0, cultural_linguistic_suppression_score: 55.0, political_exclusion_score: 52.0, economic_marginalization_score: 58.0, physical_security_threat_score: 50.0, risk_level: "élevé", primary_pattern: "marginalisation_economique", key_signals: ["Violation des droits des minorités documentée — Éthiopie/Tigréens avec score composite 54.0/100 révélant une marginalisation post-conflit ciblant la minorité tigréenne dans l'accès aux services publics et à l'administration", "Suppression culturelle-linguistique (55.0/100) — la marginalisation de la langue Tigrigna dans l'administration post-conflit constitue une forme de discrimination linguistique violant l'Article 27 du PIDCP", "Exiger de l'Éthiopie la mise en œuvre des accords de Pretoria de 2022 incluant la protection des droits culturels et linguistiques des Tigréens et l'arrêt des discriminations dans l'accès aux services publics"], estimated_minority_rights_index: 5.4, last_updated: "2026-06-20" },
    { id: "MR-006", name: "Espagne/Catalogne — Langue Catalane Tensions, Condamnations Indépendantistes & Amnistie 2024", country: "Europe de l'Ouest", sector: "Langue Catalane Restrictions Certains Contextes, Leaders Indépendantistes Condamnés 9-13 Ans Prison 2017, Llarena Mandat Européen & Amnistie 2024 Débat Constitutionnel", composite_score: 51.45, cultural_linguistic_suppression_score: 52.0, political_exclusion_score: 55.0, economic_marginalization_score: 50.0, physical_security_threat_score: 48.0, risk_level: "élevé", primary_pattern: "exclusion_politique_minorites", key_signals: ["Tensions sur les droits de la minorité catalane en Espagne avec score composite 51.45/100 — condamnations de leaders politiques pour référendum d'autodétermination soulevant des questions de droits politiques des minorités régionales", "Suppression culturelle-linguistique (52.0/100) — malgré la co-officialité du catalan, certaines restrictions dans les contextes institutionnels nationaux créent des tensions avec les droits linguistiques de la minorité", "Poursuivre le dialogue institutionnel sur l'application de la Loi d'Amnistie 2024 et renforcer la protection constitutionnelle des droits linguistiques et culturels des minorités régionales en Espagne"], estimated_minority_rights_index: 5.15, last_updated: "2026-06-20" },
    { id: "MR-007", name: "Kosovo/Serbes — Post-Indépendance Minorités, Protections EULEX & Tensions Nord Mitrovica", country: "Europe de l'Est", sector: "Serbes Kosovo Minorité 5% Post-2008, Protections Constitutionnelles Partielles, Nord Kosovo Tensions KFOR, EULEX Mission & Intégration UE Conditionnée Droits Minorités", composite_score: 28.25, cultural_linguistic_suppression_score: 30.0, political_exclusion_score: 28.0, economic_marginalization_score: 25.0, physical_security_threat_score: 30.0, risk_level: "modéré", primary_pattern: "suppression_culturelle_linguistique", key_signals: ["Droits des minorités partiellement protégés au Kosovo/Serbes — cadre constitutionnel avec sièges réservés et protections EULEX mais tensions persistantes dans le nord de Mitrovica affectant la minorité serbe", "Lacunes dans la protection effective — malgré les garanties constitutionnelles, la minorité serbe du Kosovo fait face à des obstacles pratiques dans l'accès à l'éducation en langue maternelle et aux services publics", "Renforcer les mécanismes de protection des minorités au Kosovo conformément aux obligations de l'Accord de Bruxelles 2013 et accélérer l'intégration de l'Association des Municipalités Serbes"], estimated_minority_rights_index: 2.83, last_updated: "2026-06-20" },
    { id: "MR-008", name: "CCPR/FCNM — Pacte Civil Art 27 Minorités & Convention-Cadre Minorités Nationales CoE", country: "Global", sector: "PIDCP Article 27 Droits Minorités, Convention-Cadre Protection Minorités Nationales CoE, Déclaration ONU 1992 Minorités Nationales & Comité Consultatif ONU Minorités", composite_score: 4.45, cultural_linguistic_suppression_score: 5.0, political_exclusion_score: 4.0, economic_marginalization_score: 3.0, physical_security_threat_score: 6.0, risk_level: "faible", primary_pattern: "menace_securite_physique", key_signals: ["CCPR/FCNM incarne le cadre exemplaire des droits des minorités — Article 27 du PIDCP et Convention-Cadre du Conseil de l'Europe créant des obligations de protection des minorités nationales, ethniques et linguistiques", "Article 27 PIDCP — garantit aux personnes appartenant à des minorités ethniques, religieuses ou linguistiques le droit d'avoir leur propre vie culturelle, de professer et de pratiquer leur propre religion, ou d'employer leur propre langue", "Universaliser la ratification de la Convention-Cadre du Conseil de l'Europe pour la Protection des Minorités Nationales et renforcer les mécanismes de reporting du Comité ONU des droits des minorités"], estimated_minority_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { suppression_culturelle_linguistique: 3, exclusion_politique_minorites: 3, marginalisation_economique: 1, menace_securite_physique: 1 },
    top_risk_entities: ["Chine/Ouïghours — 1M+ Rééducation Xinjiang, Langue/Religion Interdites & Surveillance Totale", "Russie/Tatars Crimée-Minorités — Langues Supprimées, Déportations & Répression Post-2014", "Myanmar/Rohingya-Karen — Langues Effacées, Apatridie & Cultures Détruites"],
    critical_alerts: ["Chine/Ouïghours: suppression culturelle linguistique", "Russie/Tatars Crimée: suppression culturelle linguistique", "Myanmar/Rohingya-Karen: exclusion politique minorités", "Turquie/Kurdes: exclusion politique minorités"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "minority_rights",
    confidence_score: 0.81,
    data_sources: ["minority_rights_group_international_peoples_under_threat", "un_declaration_minority_rights_implementation_reports", "hrw_world_report_minority_discrimination"],
    entities,
    avg_estimated_minority_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
