import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[nuclear-weapons-disarmament-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(await sealResponse(MOCK)));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/nuclear-weapons-disarmament-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(await sealResponse(data)));
  } catch {
    return sealResponse(NextResponse.json(await sealResponse(MOCK), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "NWDR-001", name: "Russie/Doctrine Armes Nucléaires Ukraine Escalade", country: "Europe de l'Est", sector: "Suspension New START 2023, Menaces Nucléaires Explicites Ukraine, Doctrine Emploi Préventif Modifiée & Essais Missiles Sarmat", composite_score: 86.6, nuclear_testing_radiation_civilian_harm_severity_score: 82.0, nuclear_arsenal_modernization_proliferation_scale_score: 88.0, nuclear_deterrence_civilian_threat_score: 92.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 85.0, risk_level: "critique", primary_pattern: "doctrine_nucleaire_escalade_civile", key_signals: ["Menace nucléaire critique de Russie/Doctrine Armes Nucléaires Ukraine Escalade — doctrine d'emploi des armes nucléaires intégrée dans les stratégies militaires actives, avec ciblage potentiel de populations civiles en violation du droit humanitaire international", "Violation existentielle des droits humains — les armes nucléaires constituent par nature une violation du droit à la vie et de l'intégrité physique des populations civiles, interdites par le TPNW 2017", "Escalade asymétrique incontrôlable — les arsenaux nucléaires modernisés avec vecteurs hypersoniques réduisent les délais d'alerte et augmentent le risque de déclenchement accidentel ou délibéré"], estimated_nuclear_weapons_disarmament_rights_index: 8.66, last_updated: "2026-06-21" },
    { id: "NWDR-002", name: "USA/Modernisation 1.7 Trillion & Retrait Traités", country: "Amérique du Nord", sector: "Plan 1.7T$ Modernisation 30 Ans, Retrait INF 2019 & Open Skies 2020, Trident II D5 & B61-12 Bombes Guidées Précision", composite_score: 84.5, nuclear_testing_radiation_civilian_harm_severity_score: 78.0, nuclear_arsenal_modernization_proliferation_scale_score: 92.0, nuclear_deterrence_civilian_threat_score: 82.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 88.0, risk_level: "critique", primary_pattern: "modernisation_arsenal_proliferation", key_signals: ["Menace nucléaire critique de USA/Modernisation 1.7 Trillion & Retrait Traités — doctrine d'emploi des armes nucléaires intégrée dans les stratégies militaires actives, avec ciblage potentiel de populations civiles en violation du droit humanitaire international", "Violation existentielle des droits humains — les armes nucléaires constituent par nature une violation du droit à la vie et de l'intégrité physique des populations civiles, interdites par le TPNW 2017", "Escalade asymétrique incontrôlable — les arsenaux nucléaires modernisés avec vecteurs hypersoniques réduisent les délais d'alerte et augmentent le risque de déclenchement accidentel ou délibéré"], estimated_nuclear_weapons_disarmament_rights_index: 8.45, last_updated: "2026-06-21" },
    { id: "NWDR-003", name: "Corée du Nord/Tests Miniaturisation Missiles Balistiques", country: "Asie du Nord-Est", sector: "6 Tests Nucléaires 2006-2017, Miniaturisation Ogives ICBM, Hwasong-17 Portée USA & Doctrine Emploi Préventif Déclaré", composite_score: 86.15, nuclear_testing_radiation_civilian_harm_severity_score: 88.0, nuclear_arsenal_modernization_proliferation_scale_score: 85.0, nuclear_deterrence_civilian_threat_score: 90.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 80.0, risk_level: "critique", primary_pattern: "doctrine_nucleaire_escalade_civile", key_signals: ["Menace nucléaire critique de Corée du Nord/Tests Miniaturisation Missiles Balistiques — doctrine d'emploi des armes nucléaires intégrée dans les stratégies militaires actives, avec ciblage potentiel de populations civiles en violation du droit humanitaire international", "Violation existentielle des droits humains — les armes nucléaires constituent par nature une violation du droit à la vie et de l'intégrité physique des populations civiles, interdites par le TPNW 2017", "Escalade asymétrique incontrôlable — les arsenaux nucléaires modernisés avec vecteurs hypersoniques réduisent les délais d'alerte et augmentent le risque de déclenchement accidentel ou délibéré"], estimated_nuclear_weapons_disarmament_rights_index: 8.62, last_updated: "2026-06-21" },
    { id: "NWDR-004", name: "Chine/Expansion Arsenal 350→1 000 Ogives 2030", country: "Asie de l'Est", sector: "Arsenal 350 → 1000 Ogives 2030 Pentagon, Silos DF-41 Désert Gobi, Triade Nucléaire Modernisée & Refus Négociations Trilatérales", composite_score: 82.0, nuclear_testing_radiation_civilian_harm_severity_score: 75.0, nuclear_arsenal_modernization_proliferation_scale_score: 90.0, nuclear_deterrence_civilian_threat_score: 80.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 85.0, risk_level: "critique", primary_pattern: "modernisation_arsenal_proliferation", key_signals: ["Menace nucléaire critique de Chine/Expansion Arsenal 350→1 000 Ogives 2030 — doctrine d'emploi des armes nucléaires intégrée dans les stratégies militaires actives, avec ciblage potentiel de populations civiles en violation du droit humanitaire international", "Violation existentielle des droits humains — les armes nucléaires constituent par nature une violation du droit à la vie et de l'intégrité physique des populations civiles, interdites par le TPNW 2017", "Escalade asymétrique incontrôlable — les arsenaux nucléaires modernisés avec vecteurs hypersoniques réduisent les délais d'alerte et augmentent le risque de déclenchement accidentel ou délibéré"], estimated_nuclear_weapons_disarmament_rights_index: 8.2, last_updated: "2026-06-21" },
    { id: "NWDR-005", name: "Pakistan/Inde Kashmir Escalade Nucléaire", country: "Asie du Sud", sector: "160 Vs 160 Ogives, Doctrine Première Frappe Pakistan, Nasr Missiles Tactiques, Kashmir Flashpoint & Pas De Hotline Nucléaire", composite_score: 59.35, nuclear_testing_radiation_civilian_harm_severity_score: 55.0, nuclear_arsenal_modernization_proliferation_scale_score: 60.0, nuclear_deterrence_civilian_threat_score: 65.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 58.0, risk_level: "élevé", primary_pattern: "non_conformite_tpnw_npt", key_signals: ["Prolifération nucléaire active de Pakistan/Inde Kashmir Escalade Nucléaire — développement ou modernisation accéléré des capacités nucléaires militaires en violation de l'esprit du TNP et des normes de désarmement multilatéral", "Risque d'escalade régionale — la possession d'armes nucléaires en contexte de tensions bilatérales crée un risque de calcul erroné pouvant déclencher un conflit nucléaire régional", "Impunité de non-conformité — le refus de ratifier le TPNW et le non-respect de l'Art.VI TNP normalisent la possession permanente d'armes nucléaires comme droit acquis des grandes puissances"], estimated_nuclear_weapons_disarmament_rights_index: 5.94, last_updated: "2026-06-21" },
    { id: "NWDR-006", name: "Iran/Enrichissement 84% AIEA Alerte", country: "MENA", sector: "Enrichissement 84% Proche Niveau Militaire, AIEA Accès Réduit, JCPOA Mort, Missiles Balistiques & Soutien Proxies Régionaux", composite_score: 56.35, nuclear_testing_radiation_civilian_harm_severity_score: 45.0, nuclear_arsenal_modernization_proliferation_scale_score: 62.0, nuclear_deterrence_civilian_threat_score: 55.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 68.0, risk_level: "élevé", primary_pattern: "non_conformite_tpnw_npt", key_signals: ["Prolifération nucléaire active de Iran/Enrichissement 84% AIEA Alerte — développement ou modernisation accéléré des capacités nucléaires militaires en violation de l'esprit du TNP et des normes de désarmement multilatéral", "Risque d'escalade régionale — la possession d'armes nucléaires en contexte de tensions bilatérales crée un risque de calcul erroné pouvant déclencher un conflit nucléaire régional", "Impunité de non-conformité — le refus de ratifier le TPNW et le non-respect de l'Art.VI TNP normalisent la possession permanente d'armes nucléaires comme droit acquis des grandes puissances"], estimated_nuclear_weapons_disarmament_rights_index: 5.64, last_updated: "2026-06-21" },
    { id: "NWDR-007", name: "ICAN/ICRC Campagne Désarmement & TPNW", country: "Global", sector: "Nobel Paix 2017 ICAN, 93 États Ratifié TPNW, ICRC Droit Humanitaire & Plaidoyer Populations Irradiées Pacifique", composite_score: 23.0, nuclear_testing_radiation_civilian_harm_severity_score: 28.0, nuclear_arsenal_modernization_proliferation_scale_score: 18.0, nuclear_deterrence_civilian_threat_score: 18.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 28.0, risk_level: "modéré", primary_pattern: "non_conformite_tpnw_npt", key_signals: ["Non-conformité désarmement de ICAN/ICRC Campagne Désarmement & TPNW — engagement insuffisant dans les mécanismes multilatéraux de contrôle des armements nucléaires malgré les obligations légales découlant du TNP", "Blocage diplomatique — le refus de progresser vers le désarmement nucléaire perpétue un système de sécurité fondé sur la dissuasion mutuellement assurée, menaçant structurellement les droits des populations", "Populations irradiées sans réparation — les victimes des essais nucléaires militaires attendent toujours une indemnisation complète et un accès aux soins médicaux spécialisés"], estimated_nuclear_weapons_disarmament_rights_index: 2.3, last_updated: "2026-06-21" },
    { id: "NWDR-008", name: "ONU/TPNW 2017 & TNP Art.VI Désarmement", country: "Global", sector: "TPNW Entrée Vigueur 2021, TNP 1970 Art.VI Obligation Désarmement, Conférence Désarmement & Mécanismes Vérification", composite_score: 4.85, nuclear_testing_radiation_civilian_harm_severity_score: 5.0, nuclear_arsenal_modernization_proliferation_scale_score: 4.0, nuclear_deterrence_civilian_threat_score: 3.0, tpnw_npt_disarmament_compliance_deficit_gap_score: 8.0, risk_level: "faible", primary_pattern: "desarmement_engagement_exemplaire", key_signals: ["ONU/TPNW 2017 & TNP Art.VI Désarmement incarne l'engagement exemplaire pour le désarmement nucléaire — soutien actif au TPNW, plaidoyer pour les droits des populations affectées par les essais nucléaires et financement des programmes ICAN", "Normes humanitaires défendues — la campagne internationale pour l'abolition des armes nucléaires repose sur le droit humanitaire international et les droits fondamentaux à la vie et à la santé", "Modèle de désarmement exportable — soutien juridique aux victimes d'essais, promotion du TPNW auprès des États non-signataires et dialogue avec les puissances nucléaires"], estimated_nuclear_weapons_disarmament_rights_index: 0.49, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { doctrine_nucleaire_escalade_civile: 2, modernisation_arsenal_proliferation: 2, tests_nucleaires_populations_irradiees: 0, non_conformite_tpnw_npt: 3, desarmement_engagement_exemplaire: 1 },
    top_risk_entities: ["Russie/Doctrine Armes Nucléaires Ukraine Escalade", "USA/Modernisation 1.7 Trillion & Retrait Traités", "Corée du Nord/Tests Miniaturisation Missiles Balistiques", "Chine/Expansion Arsenal 350→1 000 Ogives 2030"],
    critical_alerts: ["Russie/Doctrine Nucléaire: doctrine nucleaire escalade civile", "USA/Modernisation: modernisation arsenal proliferation", "Corée du Nord/Tests: doctrine nucleaire escalade civile", "Chine/Expansion: modernisation arsenal proliferation"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "nuclear_weapons_disarmament_rights",
    confidence_score: 0.88,
    data_sources: ["sipri_nuclear_forces_yearbook_2023", "ican_nuclear_weapons_ban_monitor", "iaea_safeguards_reports", "bulletin_atomic_scientists_nuclear_notebook"],
    entities,
    avg_estimated_nuclear_weapons_disarmament_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
