import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[arms-embargo-violation-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Arms Embargo Violation Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/arms-embargo-violation-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Arms Embargo Violation Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Arms Embargo Violation Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "AE-001", name: "Russie/Corée Nord-Iran — Drones Shaheed/Oreshnik, Munitions RPDC & Embargo Violations", country: "Europe de l'Est/MENA/Asie", sector: "Russie Reçoit Drones Iran Shaheed Embargo Violé, Munitions Corée Nord 1.5M Obus Documentés ONU, Ukraine Cibles Civiles & CS-ONU Résolutions 1718/2231 Ignorées", composite_score: 91.45, embargo_breach_frequency_score: 92.0, state_complicity_level_score: 95.0, civil_war_fueling_score: 90.0, accountability_enforcement_failure_score: 88.0, risk_level: "critique", primary_pattern: "complicite_etatique_armement", key_signals: ["Violation d'embargo sur les armes documentée — Russie/Corée Nord-Iran avec score composite 91.45/100 révélant des transferts d'armes illicites alimentant des conflits et violant les résolutions du Conseil de Sécurité ONU", "Complicité étatique (95.0/100) — les États fournisseurs violent leurs obligations sous le Traité sur le Commerce des Armes (TCA/ATT 2014) et les résolutions CS-ONU établissant des embargos contraignants", "Activer le Panel d'Experts CS-ONU pour enquête sur les violations d'embargo et engager des poursuites devant la CPI pour complicité dans des crimes de guerre via fourniture d'armes sous embargo"], estimated_arms_embargo_violation_index: 9.15, last_updated: "2026-06-20" },
    { entity_id: "AE-002", name: "Émirats/Arabie Saoudite Yémen — Armes Occidentales Embargo ONU Partiel & Civils Tués", country: "MENA", sector: "Armes USA/UK/France Yémen Via EAU/KSA Embargo ONU Partiel Résolution 2216, Cluster Bombs Civils, Panel Experts CS-ONU Violations Documentées & Lobby Défense Pressions", composite_score: 87.65, embargo_breach_frequency_score: 88.0, state_complicity_level_score: 82.0, civil_war_fueling_score: 95.0, accountability_enforcement_failure_score: 85.0, risk_level: "critique", primary_pattern: "alimentation_conflits_armes", key_signals: ["Violation d'embargo sur les armes documentée — Émirats/Arabie Saoudite Yémen avec score composite 87.65/100 révélant des transferts d'armes illicites alimentant des conflits et violant les résolutions du Conseil de Sécurité ONU", "Complicité étatique (82.0/100) — les États fournisseurs violent leurs obligations sous le Traité sur le Commerce des Armes (TCA/ATT 2014) et les résolutions CS-ONU établissant des embargos contraignants", "Activer le Panel d'Experts CS-ONU pour enquête sur les violations d'embargo et engager des poursuites devant la CPI pour complicité dans des crimes de guerre via fourniture d'armes sous embargo"], estimated_arms_embargo_violation_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "AE-003", name: "Chine/Soudan — Darfour Embargo 2005 Violé, Relations Pétrolières CNPC & Impunité", country: "Afrique de l'Est/Asie", sector: "Chine Fournit Armes Soudan Embargo ONU 2005 Résolution 1591, Relations Pétrolières CNPC, Khartoum/RSF Armés & Panel Experts ONU Violations Documentées 2005-2024", composite_score: 85.0, embargo_breach_frequency_score: 85.0, state_complicity_level_score: 82.0, civil_war_fueling_score: 88.0, accountability_enforcement_failure_score: 85.0, risk_level: "critique", primary_pattern: "alimentation_conflits_armes", key_signals: ["Violation d'embargo sur les armes documentée — Chine/Soudan avec score composite 85.0/100 révélant des transferts d'armes illicites alimentant des conflits et violant les résolutions du Conseil de Sécurité ONU", "Complicité étatique (82.0/100) — les États fournisseurs violent leurs obligations sous le Traité sur le Commerce des Armes (TCA/ATT 2014) et les résolutions CS-ONU établissant des embargos contraignants", "Activer le Panel d'Experts CS-ONU pour enquête sur les violations d'embargo et engager des poursuites devant la CPI pour complicité dans des crimes de guerre via fourniture d'armes sous embargo"], estimated_arms_embargo_violation_index: 8.5, last_updated: "2026-06-20" },
    { entity_id: "AE-004", name: "Turquie/Libye — Embargo ONU 2011 Violé, Drones Bayraktar TB2 & Mercenaires Syriens", country: "MENA/Europe", sector: "Turquie Viole Embargo ONU Libye Résolution 1970 2020, Drones TB2 Transferts Sans Notification, Mercenaires Syriens Déployés & Panel Experts ONU Rapport 2020 Violations", composite_score: 82.25, embargo_breach_frequency_score: 82.0, state_complicity_level_score: 80.0, civil_war_fueling_score: 85.0, accountability_enforcement_failure_score: 82.0, risk_level: "critique", primary_pattern: "alimentation_conflits_armes", key_signals: ["Violation d'embargo sur les armes documentée — Turquie/Libye avec score composite 82.25/100 révélant des transferts d'armes illicites alimentant des conflits et violant les résolutions du Conseil de Sécurité ONU", "Complicité étatique (80.0/100) — les États fournisseurs violent leurs obligations sous le Traité sur le Commerce des Armes (TCA/ATT 2014) et les résolutions CS-ONU établissant des embargos contraignants", "Activer le Panel d'Experts CS-ONU pour enquête sur les violations d'embargo et engager des poursuites devant la CPI pour complicité dans des crimes de guerre via fourniture d'armes sous embargo"], estimated_arms_embargo_violation_index: 8.23, last_updated: "2026-06-20" },
    { entity_id: "AE-005", name: "France/Arabie Saoudite — Contrats 1Md€/An Légaux Yémen & Complicité Documentée Civils", country: "MENA/Europe", sector: "France Vente Armes Légales Arabie Saoudite 1Md€/An Dont Yémen, KNDS Caesar Howitzers Yémen, Embargo Partiel Non-Respecté & Rapport Parlement Français Complicité", composite_score: 54.0, embargo_breach_frequency_score: 55.0, state_complicity_level_score: 52.0, civil_war_fueling_score: 58.0, accountability_enforcement_failure_score: 50.0, risk_level: "élevé", primary_pattern: "alimentation_conflits_armes", key_signals: ["Violation partielle d'embargo sur les armes — France/Arabie Saoudite avec score composite 54.0/100 révélant des transferts d'armes légaux mais utilisés contre des civils yéménites en violation de la Position Commune UE 944/2008", "Complicité étatique (52.0/100) — la France continue de vendre des armes à l'Arabie Saoudite malgré les preuves documentées d'utilisation contre des civils au Yémen, violant ses obligations sous le TCA 2014", "Conditionner les exportations d'armes françaises vers l'Arabie Saoudite au respect du droit international humanitaire et activer le mécanisme de contrôle parlementaire pour audit des ventes d'armes à destination du Yémen"], estimated_arms_embargo_violation_index: 5.4, last_updated: "2026-06-20" },
    { entity_id: "AE-006", name: "USA/Israël Gaza — Transferts Armes, LEAHY Act Contourné & Débat Congrès Conditionnalité", country: "MENA/Amérique du Nord", sector: "USA Transferts Armes Israël 14Md$ 2023-24, LEAHY Act Violations Documentées Amnesty, Bombes 2000lb Populations Civiles & Débat Congrès Conditionnalité Armes Non-Appliquée", composite_score: 52.25, embargo_breach_frequency_score: 52.0, state_complicity_level_score: 55.0, civil_war_fueling_score: 50.0, accountability_enforcement_failure_score: 52.0, risk_level: "élevé", primary_pattern: "complicite_etatique_armement", key_signals: ["Violation partielle d'embargo sur les armes — USA/Israël Gaza avec score composite 52.25/100 révélant des transferts d'armes légaux mais utilisés contre des populations civiles en violation potentielle du droit international humanitaire", "Complicité étatique (55.0/100) — l'application non-systématique du LEAHY Act permet des transferts d'armes à des unités militaires impliquées dans des violations documentées des droits humains", "Appliquer strictement le LEAHY Act aux transferts d'armes à Israël et conditionner toute aide militaire future au respect du droit international humanitaire et au libre accès de l'aide humanitaire à Gaza"], estimated_arms_embargo_violation_index: 5.23, last_updated: "2026-06-20" },
    { entity_id: "AE-007", name: "Union Européenne — Position Commune 2008/944, End-User Certificates & Lacunes Application", country: "Europe", sector: "Position Commune UE 2008/944 Critères Export Armes, End-User Certificates Non-Vérifiés Terrain, Divergences États Membres & Rapport PE Manques Application Embargo", composite_score: 27.9, embargo_breach_frequency_score: 28.0, state_complicity_level_score: 30.0, civil_war_fueling_score: 28.0, accountability_enforcement_failure_score: 25.0, risk_level: "modéré", primary_pattern: "complicite_etatique_armement", key_signals: ["Lacunes dans le contrôle des embargos UE — divergences entre États membres dans l'application de la Position Commune 2008/944 créant des failles permettant des exports d'armes vers des zones à risque", "Contrôle insuffisant des End-User Certificates — l'absence de mécanisme UE unifié de vérification post-livraison des armes exportées permet des détournements vers des embargos actifs", "Renforcer la Position Commune UE 2008/944 vers un Règlement contraignant sur les exportations d'armes avec mécanismes de vérification post-livraison et sanctions européennes pour violations"], estimated_arms_embargo_violation_index: 2.79, last_updated: "2026-06-20" },
    { entity_id: "AE-008", name: "SIPRI/TCA-ONU — Traité Commerce Armes 2014 & Panel Experts Sanctions Monitoring", country: "Global", sector: "TCA Arms Trade Treaty 2014 116 États Parties, SIPRI Base Données Transferts Armes, Panel Experts CS-ONU Monitoring Embargos & Registre ONU Armes Conventionnelles", composite_score: 4.45, embargo_breach_frequency_score: 5.0, state_complicity_level_score: 4.0, civil_war_fueling_score: 3.0, accountability_enforcement_failure_score: 6.0, risk_level: "faible", primary_pattern: "impunite_violations_embargo", key_signals: ["SIPRI/TCA incarne le cadre exemplaire de contrôle du commerce des armes — Traité sur le Commerce des Armes 2014 et base de données SIPRI créant transparence et responsabilité dans les transferts internationaux", "TCA 2014 — oblige les États exportateurs à évaluer le risque d'utilisation des armes pour violer le droit international humanitaire avant tout transfert, avec refus obligatoire en cas de risque avéré", "Universaliser la ratification du TCA et renforcer les Panels d'Experts CS-ONU de monitoring des embargos avec mandat d'investigation renforcé et publication systématique des violations identifiées"], estimated_arms_embargo_violation_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { complicite_etatique_armement: 3, alimentation_conflits_armes: 4, impunite_violations_embargo: 1, violation_embargo_systematique: 0 },
    top_risk_entities: ["Russie/Corée Nord-Iran — Drones Shaheed/Oreshnik, Munitions RPDC & Embargo Violations", "Émirats/Arabie Saoudite Yémen — Armes Occidentales Embargo ONU Partiel & Civils Tués", "Chine/Soudan — Darfour Embargo 2005 Violé, Relations Pétrolières CNPC & Impunité"],
    critical_alerts: ["Russie/Corée Nord-Iran: complicité étatique armement", "Émirats/KSA Yémen: alimentation conflits armés", "Chine/Soudan: alimentation conflits armés", "Turquie/Libye: alimentation conflits armés"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "arms_embargo_violation",
    confidence_score: 0.78,
    data_sources: ["sipri_arms_transfers_database", "un_panel_experts_sanctions_monitoring_reports", "arms_control_association_embargo_violations_tracker"],
    entities,
    avg_estimated_arms_embargo_violation_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
