import { NextResponse } from "next/server";

const SWARM_API_URL = process.env.SWARM_API_URL;

const mockAccounts = [
  {
    account: {
      account_id: "acc_001",
      account_name: "TechScale SAS",
      industry: "SaaS B2B",
      contract_type: "annual",
      arr_eur: 96000,
      contract_start_date: "2025-01-15",
      days_until_renewal: 210,
      dau_wau_ratio: 0.52,
      feature_adoption_pct: 82,
      logins_last_30d: 38,
      api_calls_last_30d: 28500,
      features_used: 14,
      total_features: 18,
      integrations_active: 4,
      users_active: 12,
      users_licensed: 15,
      payments_on_time_pct: 100,
      overdue_invoices: 0,
      expansion_revenue_eur: 18000,
      nps_score: 72,
      support_tickets_open: 0,
      support_tickets_30d: 2,
      executive_contacts: 3,
      last_qbr_days: 45,
      csm_sentiment: 92,
      usage_pct_of_limit: 88,
    },
    health_tier: "champion",
    health_score: 88.5,
    engagement_score: 91.2,
    adoption_score: 87.4,
    financial_score: 96.8,
    relationship_score: 88.0,
    churn_risk_pct: 11.5,
    expansion_potential_eur: 38016.0,
    primary_action: "expand",
    health_signals: [
      "Engagement élevé — utilisation active et régulière de la plateforme",
      "Adoption produit forte — plusieurs fonctionnalités clés utilisées",
      "Power users identifiés — excellent signe d'adoption profonde",
      "Opportunité d'upsell identifiée — usage proche des limites",
      "Historique de paiement excellent — client financièrement sain",
      "NPS promoteur — excellent potentiel de recommandation et d'expansion",
      "Relation client solide — contacts multiples, satisfaction élevée",
      "Compte prêt pour l'expansion — signaux d'usage et de croissance positifs",
    ],
    risk_signals: [],
    renewal_forecast: "confident",
  },
  {
    account: {
      account_id: "acc_002",
      account_name: "InnoFinance SA",
      industry: "Fintech",
      contract_type: "multi_year",
      arr_eur: 144000,
      contract_start_date: "2024-07-01",
      days_until_renewal: 380,
      dau_wau_ratio: 0.38,
      feature_adoption_pct: 68,
      logins_last_30d: 22,
      api_calls_last_30d: 9500,
      features_used: 11,
      total_features: 18,
      integrations_active: 3,
      users_active: 18,
      users_licensed: 25,
      payments_on_time_pct: 98,
      overdue_invoices: 0,
      expansion_revenue_eur: 24000,
      nps_score: 35,
      support_tickets_open: 2,
      support_tickets_30d: 5,
      executive_contacts: 2,
      last_qbr_days: 75,
      csm_sentiment: 72,
      usage_pct_of_limit: 64,
    },
    health_tier: "healthy",
    health_score: 72.8,
    engagement_score: 74.5,
    adoption_score: 68.2,
    financial_score: 87.6,
    relationship_score: 65.4,
    churn_risk_pct: 27.2,
    expansion_potential_eur: 31449.6,
    primary_action: "expand",
    health_signals: [
      "Engagement élevé — utilisation active et régulière de la plateforme",
      "Historique de paiement excellent — client financièrement sain",
      "Compte prêt pour l'expansion — signaux d'usage et de croissance positifs",
    ],
    risk_signals: [],
    renewal_forecast: "confident",
  },
  {
    account: {
      account_id: "acc_003",
      account_name: "RetailChain France",
      industry: "Distribution",
      contract_type: "annual",
      arr_eur: 48000,
      contract_start_date: "2025-07-01",
      days_until_renewal: 40,
      dau_wau_ratio: 0.18,
      feature_adoption_pct: 42,
      logins_last_30d: 12,
      api_calls_last_30d: 1200,
      features_used: 7,
      total_features: 18,
      integrations_active: 1,
      users_active: 6,
      users_licensed: 15,
      payments_on_time_pct: 88,
      overdue_invoices: 1,
      expansion_revenue_eur: 0,
      nps_score: -15,
      support_tickets_open: 4,
      support_tickets_30d: 12,
      executive_contacts: 0,
      last_qbr_days: 145,
      csm_sentiment: 38,
      usage_pct_of_limit: 32,
    },
    health_tier: "at_risk",
    health_score: 34.8,
    engagement_score: 38.2,
    adoption_score: 42.1,
    financial_score: 40.8,
    relationship_score: 18.6,
    churn_risk_pct: 75.2,
    expansion_potential_eur: 0,
    primary_action: "save",
    health_signals: [],
    risk_signals: [
      "Faible engagement — risque d'attrition si non adressé rapidement",
      "Support surchargé — trop de tickets ouverts, satisfaction en baisse",
      "Relation client fragile — risque de départ si champion quitte",
      "Renouvellement à risque — contrat expirant avec signaux négatifs",
    ],
    renewal_forecast: "at_risk",
  },
  {
    account: {
      account_id: "acc_004",
      account_name: "ManufactGroup",
      industry: "Industrie",
      contract_type: "multi_year",
      arr_eur: 192000,
      contract_start_date: "2023-03-01",
      days_until_renewal: 250,
      dau_wau_ratio: 0.45,
      feature_adoption_pct: 75,
      logins_last_30d: 45,
      api_calls_last_30d: 52000,
      features_used: 13,
      total_features: 18,
      integrations_active: 5,
      users_active: 28,
      users_licensed: 35,
      payments_on_time_pct: 100,
      overdue_invoices: 0,
      expansion_revenue_eur: 36000,
      nps_score: 58,
      support_tickets_open: 1,
      support_tickets_30d: 3,
      executive_contacts: 4,
      last_qbr_days: 30,
      csm_sentiment: 85,
      usage_pct_of_limit: 76,
    },
    health_tier: "champion",
    health_score: 86.4,
    engagement_score: 89.8,
    adoption_score: 82.6,
    financial_score: 95.4,
    relationship_score: 82.2,
    churn_risk_pct: 13.6,
    expansion_potential_eur: 49766.4,
    primary_action: "expand",
    health_signals: [
      "Engagement élevé — utilisation active et régulière de la plateforme",
      "Adoption produit forte — plusieurs fonctionnalités clés utilisées",
      "Power users identifiés — excellent signe d'adoption profonde",
      "Historique de paiement excellent — client financièrement sain",
      "NPS promoteur — excellent potentiel de recommandation et d'expansion",
      "Relation client solide — contacts multiples, satisfaction élevée",
      "Compte prêt pour l'expansion — signaux d'usage et de croissance positifs",
    ],
    risk_signals: [],
    renewal_forecast: "confident",
  },
  {
    account: {
      account_id: "acc_005",
      account_name: "StartupAI",
      industry: "Intelligence Artificielle",
      contract_type: "monthly",
      arr_eur: 28800,
      contract_start_date: "2025-11-01",
      days_until_renewal: 12,
      dau_wau_ratio: 0.62,
      feature_adoption_pct: 91,
      logins_last_30d: 58,
      api_calls_last_30d: 185000,
      features_used: 16,
      total_features: 18,
      integrations_active: 6,
      users_active: 8,
      users_licensed: 10,
      payments_on_time_pct: 100,
      overdue_invoices: 0,
      expansion_revenue_eur: 9600,
      nps_score: 85,
      support_tickets_open: 0,
      support_tickets_30d: 1,
      executive_contacts: 2,
      last_qbr_days: 25,
      csm_sentiment: 96,
      usage_pct_of_limit: 95,
    },
    health_tier: "champion",
    health_score: 93.8,
    engagement_score: 100.0,
    adoption_score: 96.2,
    financial_score: 98.4,
    relationship_score: 92.6,
    churn_risk_pct: 6.2,
    expansion_potential_eur: 40579.2,
    primary_action: "expand",
    health_signals: [
      "Engagement élevé — utilisation active et régulière de la plateforme",
      "Adoption produit forte — plusieurs fonctionnalités clés utilisées",
      "Power users identifiés — excellent signe d'adoption profonde",
      "Opportunité d'upsell identifiée — usage proche des limites",
      "Historique de paiement excellent — client financièrement sain",
      "NPS promoteur — excellent potentiel de recommandation et d'expansion",
      "Relation client solide — contacts multiples, satisfaction élevée",
      "Compte prêt pour l'expansion — signaux d'usage et de croissance positifs",
    ],
    risk_signals: [],
    renewal_forecast: "confident",
  },
  {
    account: {
      account_id: "acc_006",
      account_name: "ConsultPro",
      industry: "Conseil",
      contract_type: "annual",
      arr_eur: 36000,
      contract_start_date: "2025-09-01",
      days_until_renewal: 75,
      dau_wau_ratio: 0.08,
      feature_adoption_pct: 28,
      logins_last_30d: 8,
      api_calls_last_30d: 120,
      features_used: 4,
      total_features: 18,
      integrations_active: 0,
      users_active: 3,
      users_licensed: 10,
      payments_on_time_pct: 100,
      overdue_invoices: 0,
      expansion_revenue_eur: 0,
      nps_score: -35,
      support_tickets_open: 2,
      support_tickets_30d: 8,
      executive_contacts: 0,
      last_qbr_days: 200,
      csm_sentiment: 25,
      usage_pct_of_limit: 18,
    },
    health_tier: "churning",
    health_score: 22.4,
    engagement_score: 18.8,
    adoption_score: 19.6,
    financial_score: 62.0,
    relationship_score: 8.2,
    churn_risk_pct: 87.6,
    expansion_potential_eur: 0,
    primary_action: "save",
    health_signals: [],
    risk_signals: [
      "Faible engagement — risque d'attrition si non adressé rapidement",
      "Adoption produit insuffisante — ROI perçu probablement faible",
      "NPS détracteur — risque fort de churn et de bouche-à-oreille négatif",
      "Relation client fragile — risque de départ si champion quitte",
      "Renouvellement à risque — contrat expirant avec signaux négatifs",
    ],
    renewal_forecast: "at_risk",
  },
  {
    account: {
      account_id: "acc_007",
      account_name: "LogisticsPro",
      industry: "Logistique",
      contract_type: "annual",
      arr_eur: 60000,
      contract_start_date: "2025-06-01",
      days_until_renewal: 165,
      dau_wau_ratio: 0.28,
      feature_adoption_pct: 55,
      logins_last_30d: 18,
      api_calls_last_30d: 4200,
      features_used: 9,
      total_features: 18,
      integrations_active: 2,
      users_active: 9,
      users_licensed: 12,
      payments_on_time_pct: 95,
      overdue_invoices: 0,
      expansion_revenue_eur: 6000,
      nps_score: 22,
      support_tickets_open: 1,
      support_tickets_30d: 4,
      executive_contacts: 1,
      last_qbr_days: 110,
      csm_sentiment: 60,
      usage_pct_of_limit: 52,
    },
    health_tier: "neutral",
    health_score: 55.6,
    engagement_score: 52.4,
    adoption_score: 57.8,
    financial_score: 72.0,
    relationship_score: 44.2,
    churn_risk_pct: 44.4,
    expansion_potential_eur: 10018.8,
    primary_action: "stabilize",
    health_signals: [
      "Historique de paiement excellent — client financièrement sain",
    ],
    risk_signals: [],
    renewal_forecast: "uncertain",
  },
  {
    account: {
      account_id: "acc_008",
      account_name: "HospitalGroup",
      industry: "Santé",
      contract_type: "multi_year",
      arr_eur: 120000,
      contract_start_date: "2024-01-01",
      days_until_renewal: 195,
      dau_wau_ratio: 0.32,
      feature_adoption_pct: 62,
      logins_last_30d: 20,
      api_calls_last_30d: 7800,
      features_used: 10,
      total_features: 18,
      integrations_active: 3,
      users_active: 22,
      users_licensed: 30,
      payments_on_time_pct: 100,
      overdue_invoices: 0,
      expansion_revenue_eur: 12000,
      nps_score: 28,
      support_tickets_open: 2,
      support_tickets_30d: 6,
      executive_contacts: 2,
      last_qbr_days: 85,
      csm_sentiment: 68,
      usage_pct_of_limit: 58,
    },
    health_tier: "neutral",
    health_score: 62.4,
    engagement_score: 65.8,
    adoption_score: 62.6,
    financial_score: 84.0,
    relationship_score: 52.4,
    churn_risk_pct: 37.6,
    expansion_potential_eur: 22464.0,
    primary_action: "nurture",
    health_signals: [
      "Historique de paiement excellent — client financièrement sain",
    ],
    risk_signals: [],
    renewal_forecast: "uncertain",
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const tier = searchParams.get("tier");
  const action = searchParams.get("action");

  if (SWARM_API_URL) {
    try {
      const url = new URL(`${SWARM_API_URL}/api/account-health`);
      if (tier) url.searchParams.set("tier", tier);
      if (action) url.searchParams.set("action", action);
      const res = await fetch(url.toString(), { cache: "no-store" });
      if (res.ok) return NextResponse.json(await res.json());
    } catch {}
  }

  let accounts = [...mockAccounts];
  if (tier) accounts = accounts.filter((a) => a.health_tier === tier);
  if (action) accounts = accounts.filter((a) => a.primary_action === action);

  const tier_counts: Record<string, number> = { champion: 0, healthy: 0, neutral: 0, at_risk: 0, churning: 0 };
  const action_counts: Record<string, number> = {};
  let total_health = 0, total_churn = 0, total_arr = 0, arr_risk = 0, total_expansion = 0;

  for (const a of mockAccounts) {
    tier_counts[a.health_tier] = (tier_counts[a.health_tier] || 0) + 1;
    action_counts[a.primary_action] = (action_counts[a.primary_action] || 0) + 1;
    total_health += a.health_score;
    total_churn += a.churn_risk_pct;
    total_arr += a.account.arr_eur;
    total_expansion += a.expansion_potential_eur;
    if (["at_risk", "churning"].includes(a.health_tier)) arr_risk += a.account.arr_eur;
  }

  const n = mockAccounts.length;

  return NextResponse.json({
    accounts,
    summary: {
      total: n,
      tier_counts,
      action_counts,
      avg_health_score: Math.round((total_health / n) * 10) / 10,
      avg_churn_risk_pct: Math.round((total_churn / n) * 10) / 10,
      total_arr_eur: total_arr,
      arr_at_risk_eur: arr_risk,
      total_expansion_potential_eur: Math.round(total_expansion),
    },
  });
}
