import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[lgbtq-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "LGBTQ+ Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/lgbtq-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "LGBTQ+ Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "LGBTQ+ Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "LG-001", name: "Iran/IRGC — 75+ Exécutions LGBT 1979-2024, Pendaison Homosexuels & Code Pénal Islamique", country: "MENA", sector: "Code Pénal Islamique Iran Peine Mort Homosexualité Masculine, 75+ Exécutions Documentées ILGA 1979-2024, Femmes Flagellation & Thérapies Conversion Forcée IRGC", composite_score: 91.35, criminalization_severity_score: 92.0, violence_impunity_score: 88.0, legal_recognition_denial_score: 95.0, forced_conversion_repression_score: 90.0, risk_level: "critique", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Violation des droits LGBT+ documentée — Iran/IRGC avec score composite 91.35/100 révélant une criminalisation ou une violence systémique violant les Principes de Jogjakarta et l'Article 2 du PIDCP", "Criminalisation étatique (92.0/100) — la pénalisation de l'orientation sexuelle ou de l'identité de genre constitue une violation directe du droit à la vie privée (Article 17 PIDCP) et à la non-discrimination", "Activer le Rapporteur Spécial ONU sur l'Orientation Sexuelle et l'Identité de Genre (IE SOGI) pour enquête urgente et exiger la dépénalisation conformément aux résolutions du Conseil des Droits de l'Homme ONU"], estimated_lgbtq_rights_index: 9.14, last_updated: "2026-06-20" },
    { entity_id: "LG-002", name: "Ouganda/Anti-Homosexuality Act — Peine Mort 2023, Museveni & Fermeture ONG LGBT", country: "Afrique de l'Est", sector: "Ouganda Anti-Homosexuality Act 2023 Peine Mort Récidive Museveni, 500+ Arrestations, ONG LGBT Fermées & USA Sanctions Partielles Conditionnées", composite_score: 88.25, criminalization_severity_score: 88.0, violence_impunity_score: 85.0, legal_recognition_denial_score: 92.0, forced_conversion_repression_score: 88.0, risk_level: "critique", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Violation des droits LGBT+ documentée — Ouganda/Anti-Homosexuality Act avec score composite 88.25/100 révélant une criminalisation ou une violence systémique violant les Principes de Jogjakarta et l'Article 2 du PIDCP", "Criminalisation étatique (88.0/100) — la pénalisation de l'orientation sexuelle ou de l'identité de genre constitue une violation directe du droit à la vie privée (Article 17 PIDCP) et à la non-discrimination", "Activer le Rapporteur Spécial ONU sur l'Orientation Sexuelle et l'Identité de Genre (IE SOGI) pour enquête urgente et exiger la dépénalisation conformément aux résolutions du Conseil des Droits de l'Homme ONU"], estimated_lgbtq_rights_index: 8.83, last_updated: "2026-06-20" },
    { entity_id: "LG-003", name: "Chéchénie/Russie — Camps Purge Anti-LGBT 2017-19, Kadyrov & Loi Propagande Homosexuelle", country: "Europe de l'Est", sector: "Purges Anti-LGBT Chetchénie 2017-19 Camps Clandestins HRW, Kadyrov Déni Total, Loi Propagande Homosexuelle Russie 2013/2023 Élargie & Criminalisation Trans Proposée", composite_score: 86.4, criminalization_severity_score: 85.0, violence_impunity_score: 90.0, legal_recognition_denial_score: 88.0, forced_conversion_repression_score: 82.0, risk_level: "critique", primary_pattern: "violence_impunite_etatique", key_signals: ["Violation des droits LGBT+ documentée — Chéchénie/Russie avec score composite 86.4/100 révélant une criminalisation ou une violence systémique violant les Principes de Jogjakarta et l'Article 2 du PIDCP", "Criminalisation étatique (85.0/100) — la pénalisation de l'orientation sexuelle ou de l'identité de genre constitue une violation directe du droit à la vie privée (Article 17 PIDCP) et à la non-discrimination", "Activer le Rapporteur Spécial ONU sur l'Orientation Sexuelle et l'Identité de Genre (IE SOGI) pour enquête urgente et exiger la dépénalisation conformément aux résolutions du Conseil des Droits de l'Homme ONU"], estimated_lgbtq_rights_index: 8.64, last_updated: "2026-06-20" },
    { entity_id: "LG-004", name: "Arabie Saoudite — Flagellation/Prison LGBT, Criminalisation Totale Charia & Meurtre Honneur", country: "MENA", sector: "Arabie Saoudite Criminalisation LGBT Totale Charia, Flagellation/Prison Homosexualité, Meurtre Honneur Impuni & Surveillance Digitale Applications Grindr LGBTQ+", composite_score: 83.85, criminalization_severity_score: 82.0, violence_impunity_score: 85.0, legal_recognition_denial_score: 88.0, forced_conversion_repression_score: 80.0, risk_level: "critique", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Violation des droits LGBT+ documentée — Arabie Saoudite avec score composite 83.85/100 révélant une criminalisation ou une violence systémique violant les Principes de Jogjakarta et l'Article 2 du PIDCP", "Criminalisation étatique (82.0/100) — la pénalisation de l'orientation sexuelle ou de l'identité de genre constitue une violation directe du droit à la vie privée (Article 17 PIDCP) et à la non-discrimination", "Activer le Rapporteur Spécial ONU sur l'Orientation Sexuelle et l'Identité de Genre (IE SOGI) pour enquête urgente et exiger la dépénalisation conformément aux résolutions du Conseil des Droits de l'Homme ONU"], estimated_lgbtq_rights_index: 8.39, last_updated: "2026-06-20" },
    { entity_id: "LG-005", name: "Pologne/Zones Libres LGBT — Résolutions Anti-LGBT 2019-21 & Réversion Partielle 2024", country: "Europe de l'Ouest", sector: "100 Zones Libres LGBT Pologne 2019-21 Résolutions Municipales, Droits UE Pression Tusk 2024 Réversion, PiS Propagande Anti-LGBT & Fonds UE Conditionné", composite_score: 54.0, criminalization_severity_score: 55.0, violence_impunity_score: 52.0, legal_recognition_denial_score: 58.0, forced_conversion_repression_score: 50.0, risk_level: "élevé", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Violation des droits LGBT+ documentée — Pologne/Zones Libres LGBT avec score composite 54.0/100 révélant un déni de reconnaissance juridique et des discriminations institutionnalisées violant la Directive UE sur l'égalité de traitement", "Criminalisation étatique (55.0/100) — les résolutions anti-LGBT de 100 municipalités polonaises constituent une forme de discrimination institutionnalisée violant la Charte des Droits Fondamentaux de l'UE", "Activer les mécanismes infringement de la Commission Européenne contre la Pologne pour les violations de la non-discrimination et conditionner les fonds structurels UE au respect effectif des droits LGBT+"], estimated_lgbtq_rights_index: 5.4, last_updated: "2026-06-20" },
    { entity_id: "LG-006", name: "Ghana/Human Sexual Rights Bill — Criminalisation Renforcée 2021 & ONG Fermées", country: "Afrique de l'Ouest", sector: "Ghana Human Sexual Rights and Family Values Bill 2021 Prison 3-10 Ans LGBT, Défenseurs LGBT Arrêtés, ONG Accra LGBT+ Regional Conference Interdite & Pression Religieuse", composite_score: 53.1, criminalization_severity_score: 52.0, violence_impunity_score: 48.0, legal_recognition_denial_score: 58.0, forced_conversion_repression_score: 55.0, risk_level: "élevé", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Violation des droits LGBT+ documentée — Ghana/Human Sexual Rights Bill avec score composite 53.1/100 révélant une aggravation de la criminalisation LGBT violant les obligations du Ghana sous la Charte Africaine des Droits de l'Homme", "Criminalisation étatique (52.0/100) — le projet de loi ghanéen de 2021 renforçant la criminalisation de l'homosexualité constitue une violation de l'Article 2 du PIDCP ratifié par le Ghana", "Exiger du Ghana le retrait du Human Sexual Rights Bill et activer le Comité CCPR pour examen de la conformité de la législation ghanéenne avec les obligations du PIDCP sur la non-discrimination"], estimated_lgbtq_rights_index: 5.31, last_updated: "2026-06-20" },
    { entity_id: "LG-007", name: "Hongrie/Fidesz — Loi Anti-Propagande LGBT 2021 Mineurs, Adoption Interdite & Referendum 2022", country: "Europe de l'Ouest", sector: "Hongrie Loi Anti-Propagande LGBT 2021 Mineurs, Adoption Homosexuels Interdite, Referendum 2022 Anti-LGBT & Commission UE Infringement Procedure 2022", composite_score: 28.9, criminalization_severity_score: 28.0, violence_impunity_score: 30.0, legal_recognition_denial_score: 32.0, forced_conversion_repression_score: 25.0, risk_level: "modéré", primary_pattern: "deni_reconnaissance_juridique", key_signals: ["Restrictions des droits LGBT+ en Hongrie — loi anti-propagande de 2021 interdisant l'enseignement sur l'orientation sexuelle aux mineurs violant la Directive Services Médias Audiovisuels de l'UE", "Déni de reconnaissance juridique (32.0/100) — l'interdiction de l'adoption par les couples de même sexe et les restrictions à l'identité de genre constituent des violations de la Charte des Droits Fondamentaux de l'UE", "Poursuivre les procédures d'infringement de la Commission Européenne contre la Hongrie pour la loi anti-propagande et conditionner les fonds de cohésion UE au respect effectif des droits fondamentaux"], estimated_lgbtq_rights_index: 2.89, last_updated: "2026-06-20" },
    { entity_id: "LG-008", name: "ILGA World/HRC — Rapporteur Spécial ONU SOGI & Principes Jogjakarta 2006/2017", country: "Global", sector: "ILGA World State Sponsored Homophobia Report Annuel, Rapporteur Spécial ONU Orientation Sexuelle Identité Genre IE SOGI, Principes Jogjakarta 2006/2017 & Résolutions CDH-ONU", composite_score: 4.45, criminalization_severity_score: 5.0, violence_impunity_score: 4.0, legal_recognition_denial_score: 3.0, forced_conversion_repression_score: 6.0, risk_level: "faible", primary_pattern: "repression_conversion_forcee", key_signals: ["ILGA World/HRC incarne la protection exemplaire des droits LGBT+ — Principes de Jogjakarta 2006/2017 et Mandat IE SOGI créant un cadre de responsabilité internationale pour les droits à l'orientation sexuelle et l'identité de genre", "Principes de Jogjakarta (2006) — 29 principes d'application du droit international des droits humains à l'orientation sexuelle et l'identité de genre, unanimement reconnus comme référence par les experts ONU", "Universaliser l'application des Principes de Jogjakarta et renforcer le mandat de l'Expert Indépendant ONU SOGI pour investigations dans les pays pratiquant la criminalisation LGBT"], estimated_lgbtq_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { deni_reconnaissance_juridique: 6, violence_impunite_etatique: 1, repression_conversion_forcee: 1, criminalisation_lgbtq_etat: 0 },
    top_risk_entities: ["Iran/IRGC — 75+ Exécutions LGBT 1979-2024, Pendaison Homosexuels & Code Pénal Islamique", "Ouganda/Anti-Homosexuality Act — Peine Mort 2023, Museveni & Fermeture ONG LGBT", "Chéchénie/Russie — Camps Purge Anti-LGBT 2017-19, Kadyrov & Loi Propagande Homosexuelle"],
    critical_alerts: ["Iran/IRGC: déni reconnaissance juridique", "Ouganda: déni reconnaissance juridique", "Chéchénie/Russie: violence impunité étatique", "Arabie Saoudite: déni reconnaissance juridique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "lgbtq_rights",
    confidence_score: 0.83,
    data_sources: ["ilga_world_state_sponsored_homophobia_report", "human_rights_watch_lgbt_rights_database", "un_ie_sogi_reports_sexual_orientation_gender_identity"],
    entities,
    avg_estimated_lgbtq_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
