import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[femicide-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Femicide Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/femicide-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Femicide Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Femicide Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "FM-001", name: "Honduras/El Salvador — Féminicides Maras & Impunité 98%", country: "Amérique Centrale", sector: "Honduras 10.9/100K Taux Record Mondial, Maras Contrôle Corps Femmes, 98% Impunité & Pas Loi Féminicide Spécifique", composite_score: 88.6, feminicide_rate_normalized_score: 95.0, honor_killing_legal_tolerance_score: 75.0, state_institutional_impunity_score: 95.0, survivor_protection_failure_score: 88.0, risk_level: "critique", primary_pattern: "impunite_feminicide_systemique", key_signals: ["Impunité systémique des féminicides de Honduras/El Salvador — taux de condamnation quasi-nuls avec complicité des forces de l'ordre face aux crimes des maras et partenaires intimes", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Engager le CEDAW pour réforme urgente du cadre légal et formation des forces de sécurité à l'identification des féminicides"], estimated_femicide_index: 8.86, last_updated: "2026-06-20" },
    { id: "FM-002", name: "Pakistan/Afghanistan — Crimes Honneur 1000/An & Jirgas", country: "Asie du Sud", sector: "1000+ Crimes Honneur/An Pakistan, Karo-Kari Tradition Sindh, Jirgas Autorisent Meurtres & Article 302 PPC Réduction Peine", composite_score: 86.35, feminicide_rate_normalized_score: 82.0, honor_killing_legal_tolerance_score: 95.0, state_institutional_impunity_score: 88.0, survivor_protection_failure_score: 80.0, risk_level: "critique", primary_pattern: "feminicide_honor_etatique", key_signals: ["Féminicides d'honneur institutionnalisés de Pakistan/Afghanistan — meurtres de femmes tolérés légalement au nom de l'honneur familial avec réduction de peine codifiée dans le droit positif", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Abroger les exemptions légales pour meurtres d'honneur et activer le Rapporteur Spécial ONU sur les violences contre les femmes"], estimated_femicide_index: 8.64, last_updated: "2026-06-20" },
    { id: "FM-003", name: "Mexique/Juárez — Féminicides Cartels & Alertas de Género", country: "Amérique du Nord", sector: "Ciudad Juárez Capitale Mondiale 1990s, 10 Féminicides/Jour Mexique 2023, Alerta Gender Violencia 24 États & Impunité 95%", composite_score: 85.1, feminicide_rate_normalized_score: 90.0, honor_killing_legal_tolerance_score: 72.0, state_institutional_impunity_score: 90.0, survivor_protection_failure_score: 88.0, risk_level: "critique", primary_pattern: "feminicide_conflit_arme", key_signals: ["Féminicides dans les conflits armés de Mexique/Juárez — meurtres de femmes liés aux territoires cartels avec utilisation du corps féminin comme message de terreur entre groupes criminels", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Activer la résolution 1325 du Conseil de Sécurité et saisir la CPI pour féminicides comme crimes contre l'humanité"], estimated_femicide_index: 8.51, last_updated: "2026-06-20" },
    { id: "FM-004", name: "RDC/Congo Est — Féminicides Conflits Armés & Viols Guerre", country: "Afrique Centrale", sector: "Viols Arme Guerre Documentés, Femmes Tuées Après Viol, 200 000+ Victimes HRW & Impunité Presque Totale Commandants", composite_score: 83.65, feminicide_rate_normalized_score: 88.0, honor_killing_legal_tolerance_score: 72.0, state_institutional_impunity_score: 85.0, survivor_protection_failure_score: 90.0, risk_level: "critique", primary_pattern: "violence_conjugale_letale", key_signals: ["Violence conjugale létale systémique de RDC/Congo Est — élimination physique des femmes après violences sexuelles dans le cadre des conflits armés avec tolérance institutionnelle des commandants", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Ratifier la Convention d'Istanbul et activer les mécanismes GREVIO pour audit national des politiques de prévention"], estimated_femicide_index: 8.37, last_updated: "2026-06-20" },
    { id: "FM-005", name: "Turquie — Féminicides +40% 5 Ans & Retrait Convention Istanbul", country: "MENA/Europe", sector: "300+ Féminicides/An, Retrait Convention Istanbul 2021, Bonne Raison Réduction Peine & We Will Stop Femicide Platform", composite_score: 57.5, feminicide_rate_normalized_score: 55.0, honor_killing_legal_tolerance_score: 58.0, state_institutional_impunity_score: 62.0, survivor_protection_failure_score: 55.0, risk_level: "élevé", primary_pattern: "impunite_feminicide_systemique", key_signals: ["Impunité systémique des féminicides de Turquie — retrait de la Convention d'Istanbul et réduction des peines pour 'bonne raison' facilitant les féminicides par partenaires intimes", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Engager le CEDAW pour réforme urgente du cadre légal et réintégrer la Convention d'Istanbul"], estimated_femicide_index: 5.75, last_updated: "2026-06-20" },
    { id: "FM-006", name: "Inde — Féminicides Dot & Avortements Sexo-Sélectifs", country: "Asie du Sud", sector: "7000 Meurtres Dot/An NCRB, Sex-Ratio 912 Filles/1000 Garçons, Dowry Prohibition Act Inefficace & Crimes Non Reportés", composite_score: 55.85, feminicide_rate_normalized_score: 52.0, honor_killing_legal_tolerance_score: 55.0, state_institutional_impunity_score: 58.0, survivor_protection_failure_score: 60.0, risk_level: "élevé", primary_pattern: "violence_conjugale_letale", key_signals: ["Violence conjugale létale systémique d'Inde — 7000 meurtres liés à la dot annuels avec sous-déclaration massive et inefficacité du Dowry Prohibition Act face aux pressions familiales", "Impunité structurelle — les auteurs de féminicides bénéficient de peines réduites, complaisance policière ou exemptions légales renforçant le cycle de la violence létale", "Ratifier la Convention d'Istanbul et activer les mécanismes GREVIO pour audit national des politiques de prévention"], estimated_femicide_index: 5.59, last_updated: "2026-06-20" },
    { id: "FM-007", name: "France/Europe Occidentale — Féminicides Conjugaux & Protection Partielle", country: "Europe", sector: "118 Féminicides France 2023, Bracelet Anti-Rapprochement Insuffisant, Espagne 48 & Grenelle Violences Conjugales Progrès Partiels", composite_score: 25.4, feminicide_rate_normalized_score: 28.0, honor_killing_legal_tolerance_score: 15.0, state_institutional_impunity_score: 25.0, survivor_protection_failure_score: 35.0, risk_level: "modéré", primary_pattern: "violence_conjugale_letale", key_signals: ["Violence conjugale létale persistante de France/Europe — féminicides par partenaires intimes persistants malgré un cadre légal spécifique, révélant des défaillances dans la protection préventive des victimes", "Impunité structurelle résiduelle — délais judiciaires, manque de ressources pour hébergement d'urgence et formation insuffisante des forces de l'ordre aux signaux précurseurs du féminicide", "Ratifier et appliquer pleinement la Convention d'Istanbul et renforcer les ressources des associations de protection des femmes en danger"], estimated_femicide_index: 2.54, last_updated: "2026-06-20" },
    { id: "FM-008", name: "ONU Women/CEDAW — Convention Droits Femmes & Indicateurs", country: "Global", sector: "CEDAW 189 États Parties, ONU Women Données Féminicides, Convention Istanbul 46 Pays & GREVIO Monitoring", composite_score: 4.45, feminicide_rate_normalized_score: 5.0, honor_killing_legal_tolerance_score: 4.0, state_institutional_impunity_score: 3.0, survivor_protection_failure_score: 6.0, risk_level: "faible", primary_pattern: "protection_femmes_exemplaire", key_signals: ["ONU Women/CEDAW incarne la protection exemplaire des femmes — cadre légal spécifique anti-féminicide, poursuites effectives et dispositifs de protection des victimes à risque", "Normes internationales — CEDAW, Convention d'Istanbul et résolution ONU sur féminicides créant des obligations contraignantes pour les États en matière de prévention et sanction", "Partager les modèles législatifs et financer les mécanismes ONU Women pour prévention des féminicides dans les pays à haut risque"], estimated_femicide_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { feminicide_honor_etatique: 1, impunite_feminicide_systemique: 2, feminicide_conflit_arme: 1, violence_conjugale_letale: 3, protection_femmes_exemplaire: 1 },
    top_risk_entities: ["Honduras/El Salvador — Féminicides Maras & Impunité 98%", "Pakistan/Afghanistan — Crimes Honneur 1000/An & Jirgas", "Mexique/Juárez — Féminicides Cartels & Alertas de Género"],
    critical_alerts: ["Honduras/El Salvador: impunité systémique féminicides", "Pakistan/Afghanistan: féminicides d'honneur institutionnalisés", "Mexique/Juárez: féminicides conflits armés", "RDC/Congo Est: violence conjugale létale systémique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "femicide",
    confidence_score: 0.81,
    data_sources: ["unodc_global_study_homicide_gender", "un_women_femicide_watch_database", "small_arms_survey_femicide_data"],
    entities,
    avg_estimated_femicide_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
