import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[freedom-of-assembly-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Freedom of Assembly Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/freedom-of-assembly-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Freedom of Assembly Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Freedom of Assembly Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "FA-001", name: "Chine/Hong Kong — NSL 2020, 10 000+ Arrestations Manifestants & Assemblée Interdite", country: "Asie du Nord-Est", sector: "China National Security Law 2020 HK 10 000+ Arrêtés, 55 Dirigeants Pro-Démocratie Condamnés, Article 23 2024 & Manifestations Place Tiananmen Interdites Continent", composite_score: 92.25, protest_criminalization_score: 95.0, excessive_force_dispersal_score: 88.0, organizer_persecution_score: 95.0, emergency_law_abuse_score: 90.0, risk_level: "critique", primary_pattern: "criminalisation_manifestation", key_signals: ["Violation du droit de réunion documentée — Chine/Hong Kong avec score composite 92.25/100 révélant une restriction systémique violant l'Article 20 de la DUDH et l'Article 21 du PIDCP sur le droit de réunion pacifique", "Criminalisation des manifestations (95.0/100) — la loi NSL 2020 de Hong Kong et l'interdiction permanente de Tiananmen continent constituent des violations directes du droit à la liberté de réunion garanti par le PIDCP", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 9.23, last_updated: "2026-06-20" },
    { entity_id: "FA-002", name: "Biélorussie/Loukachenko — 35 000 Arrestations 2020, Manifestants Torturés & ONG Dissoutes", country: "Europe de l'Est", sector: "Biélorussie 2020 Fraude Électorale 35 000 Manifestants Arrêtés Loukachenko, Torture Documentée HRW, Syndicats/ONG Dissous & Lukashenko Réfugié Moscou", composite_score: 89.60, protest_criminalization_score: 90.0, excessive_force_dispersal_score: 92.0, organizer_persecution_score: 88.0, emergency_law_abuse_score: 88.0, risk_level: "critique", primary_pattern: "force_excessive_dispersion", key_signals: ["Violation du droit de réunion documentée — Biélorussie/Loukachenko avec score composite 89.60/100 révélant une restriction systémique violant l'Article 20 de la DUDH et l'Article 21 du PIDCP sur le droit de réunion pacifique", "Criminalisation des manifestations (90.0/100) — les 35 000 arrestations de manifestants en 2020 et la dissolution systématique des ONG constituent une violation totale du droit à la liberté de réunion en Biélorussie", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 8.96, last_updated: "2026-06-20" },
    { entity_id: "FA-003", name: "Iran/Mahsa Amini — 20 000+ Arrestations 2022, 500+ Tués & Manifestants Pendus", country: "MENA", sector: "Iran Révolution Femme-Vie-Liberté 2022 Mahsa Amini 500+ Morts, 20 000+ Arrestations, Manifestants Exécutés Pendaison & IRGC Tirs Balles Réelles Foules", composite_score: 88.85, protest_criminalization_score: 92.0, excessive_force_dispersal_score: 88.0, organizer_persecution_score: 85.0, emergency_law_abuse_score: 90.0, risk_level: "critique", primary_pattern: "criminalisation_manifestation", key_signals: ["Violation du droit de réunion documentée — Iran/Mahsa Amini avec score composite 88.85/100 révélant une restriction systémique violant l'Article 20 de la DUDH et l'Article 21 du PIDCP sur le droit de réunion pacifique", "Criminalisation des manifestations (92.0/100) — les 500+ manifestants tués, les 20 000 arrestations et les exécutions de manifestants constituent des violations gravissimes du droit à la liberté de réunion pacifique", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 8.89, last_updated: "2026-06-20" },
    { entity_id: "FA-004", name: "Myanmar/Tatmadaw — 5 000+ Tués Manifestants, CRPH & Coup État 2021", country: "Asie du Sud-Est", sector: "Myanmar Coup 2021 Tatmadaw 5 000+ Manifestants Tués, 25 000+ Arrêtés, CRPH Gouvernement Parallèle & Tirs Balles Réelles Rassemblements Pacifiques CDM", composite_score: 87.65, protest_criminalization_score: 88.0, excessive_force_dispersal_score: 95.0, organizer_persecution_score: 82.0, emergency_law_abuse_score: 85.0, risk_level: "critique", primary_pattern: "force_excessive_dispersion", key_signals: ["Violation du droit de réunion documentée — Myanmar/Tatmadaw avec score composite 87.65/100 révélant une restriction systémique violant l'Article 20 de la DUDH et l'Article 21 du PIDCP sur le droit de réunion pacifique", "Criminalisation des manifestations (88.0/100) — les 5 000+ manifestants tués par le Tatmadaw depuis le coup d'État de 2021 constituent une violation gravissime du droit à la liberté de réunion pacifique garantie par le PIDCP", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "FA-005", name: "Russie/Anti-Guerre — 16 000+ Arrestations 2022, Loi Anti-Protestation & OVD-Info", country: "Europe de l'Est", sector: "Russie Anti-Guerre Ukraine 16 000+ Arrestations 2022 OVD-Info, Loi 15 Ans Prison Anti-Armée, Manifestants Condamnés & Espace Public Réprimé Krasnodar/Moscou", composite_score: 56.40, protest_criminalization_score: 55.0, excessive_force_dispersal_score: 52.0, organizer_persecution_score: 58.0, emergency_law_abuse_score: 62.0, risk_level: "élevé", primary_pattern: "abus_lois_urgence", key_signals: ["Violation du droit de réunion documentée — Russie/Anti-Guerre avec score composite 56.40/100 révélant une restriction systémique des manifestations anti-guerre violant l'Article 21 du PIDCP ratifié par la Russie", "Criminalisation des manifestations (55.0/100) — la loi pénalisant toute critique de l'armée russe avec jusqu'à 15 ans de prison constitue une criminalisation directe de la liberté de réunion et d'expression", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 5.64, last_updated: "2026-06-20" },
    { entity_id: "FA-006", name: "Éthiopie/Oromo-Amhara — Manifestants Tués, État Urgence 2021-23 & Restrictions", country: "Afrique de l'Est", sector: "Éthiopie Manifestations Oromo Amhara 2021-23 Centaines Tués, États Urgence Répétés, Internet Coupé & NISS Arrestations Défenseurs Droits Réunion", composite_score: 52.95, protest_criminalization_score: 52.0, excessive_force_dispersal_score: 55.0, organizer_persecution_score: 48.0, emergency_law_abuse_score: 58.0, risk_level: "élevé", primary_pattern: "abus_lois_urgence", key_signals: ["Violation du droit de réunion documentée — Éthiopie/Oromo-Amhara avec score composite 52.95/100 révélant des restrictions graves aux rassemblements pacifiques via états d'urgence répétés violant le PIDCP", "Criminalisation des manifestations (52.0/100) — les états d'urgence répétés en Éthiopie permettant la détention sans jugement et l'interdiction de réunion constituent des restrictions disproportionnées du droit PIDCP Art. 21", "Activer le Rapporteur Spécial ONU sur les droits de réunion pacifique et d'association pour enquête urgente et exiger l'abrogation des lois restrictives incompatibles avec les normes PIDCP"], estimated_freedom_of_assembly_index: 5.30, last_updated: "2026-06-20" },
    { entity_id: "FA-007", name: "France/Gilets Jaunes-Retraites — LBD Mutilés, 11 000+ Gardes à Vue & ACAT Rapport", country: "Europe de l'Ouest", sector: "France Gilets Jaunes 2018-19 + Réforme Retraites 2023, 11 000+ Gardes à Vue, LBD 300+ Blessés Graves Yeux/Mains & Conseil Constitutionnel Critiques", composite_score: 28.65, protest_criminalization_score: 28.0, excessive_force_dispersal_score: 32.0, organizer_persecution_score: 25.0, emergency_law_abuse_score: 30.0, risk_level: "modéré", primary_pattern: "force_excessive_dispersion", key_signals: ["Restrictions modérées du droit de réunion en France — usage contesté des LBD (lanceurs de balles de défense) lors des Gilets Jaunes et de la réforme des retraites ayant causé 300+ blessures graves documentées par l'ACAT", "Force excessive lors des dispersions (32.0/100) — l'usage des LBD 40 ayant provoqué des mutilations graves (perte d'yeux, de mains) lors de manifestations pacifiques soulève des questions de proportionnalité sous l'Article 21 PIDCP", "Renforcer le cadre légal encadrant l'usage des armes de maintien de l'ordre en France conformément aux recommandations du Défenseur des droits et du CNCDH sur la liberté de manifestation"], estimated_freedom_of_assembly_index: 2.87, last_updated: "2026-06-20" },
    { entity_id: "FA-008", name: "OSCE/ODIHR-ONU — Rapporteur Spécial Réunion Pacifique & Guidelines Manifestations", country: "Global", sector: "OSCE ODIHR Guidelines Liberté Réunion Pacifique, Rapporteur Spécial ONU Réunion Clément Nyaletsossi Voule, ICCPR Article 21 & Déclaration ONU Défenseurs Droits 1998", composite_score: 4.45, protest_criminalization_score: 5.0, excessive_force_dispersal_score: 4.0, organizer_persecution_score: 3.0, emergency_law_abuse_score: 6.0, risk_level: "faible", primary_pattern: "abus_lois_urgence", key_signals: ["OSCE/ODIHR-ONU incarne le cadre exemplaire de la liberté de réunion pacifique — Guidelines OSCE et Mandat Rapporteur Spécial ONU créant des standards internationaux pour les États sur les conditions d'encadrement des manifestations", "PIDCP Article 21 — garantit le droit à la liberté de réunion pacifique avec restrictions uniquement si nécessaires dans une société démocratique et proportionnées à l'objectif légitime poursuivi", "Universaliser l'application des Guidelines OSCE/ODIHR sur la liberté de réunion pacifique et renforcer le mandat du Rapporteur Spécial ONU pour enquêtes sur les États restreignant les rassemblements pacifiques"], estimated_freedom_of_assembly_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { criminalisation_manifestation: 2, force_excessive_dispersion: 3, persecution_organisateurs: 0, abus_lois_urgence: 3 },
    top_risk_entities: ["Chine/Hong Kong — NSL 2020, 10 000+ Arrestations Manifestants & Assemblée Interdite", "Biélorussie/Loukachenko — 35 000 Arrestations 2020, Manifestants Torturés & ONG Dissoutes", "Iran/Mahsa Amini — 20 000+ Arrestations 2022, 500+ Tués & Manifestants Pendus"],
    critical_alerts: ["Chine/Hong Kong: criminalisation manifestation", "Biélorussie: force excessive dispersion", "Iran/Mahsa Amini: criminalisation manifestation", "Myanmar/Tatmadaw: force excessive dispersion"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "freedom_of_assembly",
    confidence_score: 0.84,
    data_sources: ["osce_odihr_freedom_of_assembly_reports", "un_special_rapporteur_peaceful_assembly_association", "civicus_monitor_civic_space_ratings"],
    entities,
    avg_estimated_freedom_of_assembly_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
