import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[state-terrorism-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "State Terrorism Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/state-terrorism-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "State Terrorism Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "State Terrorism Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "ST-001", name: "RPDC/Kim Jong-un — Kwanliso, Exécutions Publiques & Terreur Totale", country: "Asie du Nord-Est", sector: "80-120K Détenus Camps Politiques, Exécutions Publiques Masse, ONU Crimes Humanité 2014 & Famines Induites", composite_score: 91.6, extrajudicial_killings_score: 95.0, forced_disappearances_score: 92.0, systematic_torture_score: 90.0, political_mass_imprisonment_score: 88.0, risk_level: "critique", primary_pattern: "terrorisme_etat_systematique", key_signals: ["Terrorisme d'État critique de RPDC/Kim Jong-un — exécutions extrajudiciaires, disparitions forcées et torture utilisées comme instruments délibérés de gouvernance par l'appareil sécuritaire", "Crimes contre l'humanité documentés — les violations systématiques et généralisées des droits fondamentaux constituent des crimes contre l'humanité selon le Statut de Rome", "Culture de l'impunité institutionnalisée — l'absence de responsabilité judiciaire des agents de l'État perpétue les cycles de violence et décourage la dénonciation des victimes"], estimated_state_terrorism_index: 9.16, last_updated: "2026-06-20" },
    { entity_id: "ST-002", name: "Syrie/Assad — Rapport Caesar, Armes Chimiques & Prisons Secrètes", country: "MENA", sector: "55 000 Photos Torture Caesar, 150K+ Disparus, Sarin Ghouta 2013 & Saydnaya Prison Abattoir Documentée", composite_score: 85.8, extrajudicial_killings_score: 83.0, forced_disappearances_score: 90.0, systematic_torture_score: 88.0, political_mass_imprisonment_score: 82.0, risk_level: "critique", primary_pattern: "disparitions_forcees_institutionnalisees", key_signals: ["Terrorisme d'État critique de Syrie/Assad — exécutions extrajudiciaires, disparitions forcées et torture utilisées comme instruments délibérés de gouvernance par l'appareil sécuritaire", "Crimes contre l'humanité documentés — les violations systématiques et généralisées des droits fondamentaux constituent des crimes contre l'humanité selon le Statut de Rome", "Culture de l'impunité institutionnalisée — l'absence de responsabilité judiciaire des agents de l'État perpétue les cycles de violence et décourage la dénonciation des victimes"], estimated_state_terrorism_index: 8.58, last_updated: "2026-06-20" },
    { entity_id: "ST-003", name: "Iran/IRGC — Novichok Dissidents, Evin Prison & Exécutions Masse", country: "MENA", sector: "500+ Exécutés 2023 Record, Assassinats Diaspora Europe, Evin Torture Systémique & Mahsa Amini Répression", composite_score: 82.35, extrajudicial_killings_score: 82.0, forced_disappearances_score: 82.0, systematic_torture_score: 85.0, political_mass_imprisonment_score: 80.0, risk_level: "critique", primary_pattern: "torture_systematique_etat", key_signals: ["Terrorisme d'État critique de Iran/IRGC — exécutions extrajudiciaires, disparitions forcées et torture utilisées comme instruments délibérés de gouvernance par l'appareil sécuritaire", "Crimes contre l'humanité documentés — les violations systématiques et généralisées des droits fondamentaux constituent des crimes contre l'humanité selon le Statut de Rome", "Culture de l'impunité institutionnalisée — l'absence de responsabilité judiciaire des agents de l'État perpétue les cycles de violence et décourage la dénonciation des victimes"], estimated_state_terrorism_index: 8.24, last_updated: "2026-06-20" },
    { entity_id: "ST-004", name: "Chine/DSN — Sécurité Nationale, Ouïghours & Répression Interne", country: "Asie", sector: "Xinjiang Disparitions Forcées, Hong Kong 10000+ Arrêtés, Falung Gong Organes & Minorités Emprisonnements Masse", composite_score: 80.25, extrajudicial_killings_score: 80.0, forced_disappearances_score: 75.0, systematic_torture_score: 78.0, political_mass_imprisonment_score: 90.0, risk_level: "critique", primary_pattern: "repression_politique_massive", key_signals: ["Terrorisme d'État critique de Chine/DSN — exécutions extrajudiciaires, disparitions forcées et torture utilisées comme instruments délibérés de gouvernance par l'appareil sécuritaire", "Crimes contre l'humanité documentés — les violations systématiques et généralisées des droits fondamentaux constituent des crimes contre l'humanité selon le Statut de Rome", "Culture de l'impunité institutionnalisée — l'absence de responsabilité judiciaire des agents de l'État perpétue les cycles de violence et décourage la dénonciation des victimes"], estimated_state_terrorism_index: 8.03, last_updated: "2026-06-20" },
    { entity_id: "ST-005", name: "Russie/FSB — Opposants Empoisonnés, Navalny & Répression Anti-Guerre", country: "Europe de l'Est", sector: "Navalny Assassiné Colonie Pénitentiaire, 19000+ Anti-Guerre Arrêtés, Journalistes Tués & Borschevikova Torture", composite_score: 56.4, extrajudicial_killings_score: 55.0, forced_disappearances_score: 52.0, systematic_torture_score: 58.0, political_mass_imprisonment_score: 62.0, risk_level: "élevé", primary_pattern: "repression_politique_massive", key_signals: ["Répression politique systémique de Russie/FSB — persécution documentée des opposants politiques, journalistes et défenseurs des droits humains par les forces de sécurité étatiques", "Système judiciaire instrumentalisé — tribunaux d'exception, procès politiques inéquitables et emprisonnements arbitraires prolongés servant d'outils de neutralisation des opposants", "Résistance civile réprimée — manifestations dispersées par la force, ONG dissoutes et espaces civiques réduits à néant par la législation sécuritaire abusive"], estimated_state_terrorism_index: 5.64, last_updated: "2026-06-20" },
    { entity_id: "ST-006", name: "Arabie Saoudite/MBS — Khashoggi, MBS Dissidents & Chiites Minorité", country: "MENA", sector: "Khashoggi Assassinat Ambassade 2018, 81 Exécutions Jour 2022, Nimr Al-Nimr & Chiites Répression Est", composite_score: 52.95, extrajudicial_killings_score: 52.0, forced_disappearances_score: 48.0, systematic_torture_score: 55.0, political_mass_imprisonment_score: 58.0, risk_level: "élevé", primary_pattern: "repression_politique_massive", key_signals: ["Répression politique systémique de Arabie Saoudite/MBS — persécution documentée des opposants politiques, journalistes et défenseurs des droits humains par les forces de sécurité étatiques", "Système judiciaire instrumentalisé — tribunaux d'exception, procès politiques inéquitables et emprisonnements arbitraires prolongés servant d'outils de neutralisation des opposants", "Résistance civile réprimée — manifestations dispersées par la force, ONG dissoutes et espaces civiques réduits à néant par la législation sécuritaire abusive"], estimated_state_terrorism_index: 5.3, last_updated: "2026-06-20" },
    { entity_id: "ST-007", name: "Venezuela/Maduro — SEBIN, Colectivos & Opposition Liquidée", country: "Amérique du Sud", sector: "SEBIN Torture Politique, Colectivos Paramilitaires État, Leopoldo López Emprisonné & 800+ Arbitraires 2019", composite_score: 29.65, extrajudicial_killings_score: 28.0, forced_disappearances_score: 25.0, systematic_torture_score: 32.0, political_mass_imprisonment_score: 35.0, risk_level: "modéré", primary_pattern: "repression_politique_massive", key_signals: ["Autoritarisme répressif de Venezuela/Maduro — restrictions documentées des libertés fondamentales avec incidents isolés de violence d'État sans politique systémique de terreur", "Tensions institutions-société civile — confrontations récurrentes entre forces de sécurité et manifestants, sans atteindre le seuil de la répression politique institutionnalisée", "Risque de dérive autoritaire — l'affaiblissement des contre-pouvoirs et l'instrumentalisation des lois antiterroristes créent des conditions propices à l'escalade répressive"], estimated_state_terrorism_index: 2.97, last_updated: "2026-06-20" },
    { entity_id: "ST-008", name: "CPI/CDH ONU — Responsabilité Universelle & État de Droit", country: "Global", sector: "CPI 124 États Parties, CDH Procédures Spéciales 44 Mandataires, Convention Torture Ratifiée 173 États & OPCAT", composite_score: 4.45, extrajudicial_killings_score: 5.0, forced_disappearances_score: 4.0, systematic_torture_score: 3.0, political_mass_imprisonment_score: 6.0, risk_level: "faible", primary_pattern: "etat_de_droit_exemplaire", key_signals: ["CPI/CDH ONU incarne l'état de droit exemplaire — indépendance judiciaire effective, responsabilité des forces de sécurité et garanties constitutionnelles des libertés fondamentales", "Mécanismes de contrôle démocratique — commissions d'enquête indépendantes, tribunaux administratifs actifs et protection des lanceurs d'alerte contre les abus sécuritaires", "Modèle de gouvernance sécuritaire à exporter — coopération judiciaire internationale, formation des forces de sécurité aux droits humains et aide aux États en transition"], estimated_state_terrorism_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { terrorisme_etat_systematique: 1, disparitions_forcees_institutionnalisees: 1, torture_systematique_etat: 1, repression_politique_massive: 4, etat_de_droit_exemplaire: 1 },
    top_risk_entities: ["RPDC/Kim Jong-un — Kwanliso, Exécutions Publiques & Terreur Totale", "Syrie/Assad — Rapport Caesar, Armes Chimiques & Prisons Secrètes", "Iran/IRGC — Novichok Dissidents, Evin Prison & Exécutions Masse"],
    critical_alerts: ["RPDC/Kim Jong-un: terrorisme État systématique", "Syrie/Assad: disparitions forcées institutionnalisées", "Iran/IRGC: torture systématique État", "Chine/DSN: répression politique massive"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "state_terrorism",
    confidence_score: 0.85,
    data_sources: ["amnesty_international_annual_report", "human_rights_watch_world_report", "un_special_rapporteur_torture_reports"],
    entities,
    avg_estimated_state_terrorism_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
