import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[water-weaponization-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Water Weaponization Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/water-weaponization-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Water Weaponization Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Water Weaponization Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "WW-001", name: "Russie/Ukraine — Barrage Kakhovka Destruction & Eau Kherson Coupée", country: "Europe de l'Est", sector: "Barrage Kakhovka Destruction Juin 2023, 700 000 Sans Eau, Marioupol Assiégée Eau Coupée & Kherson Civilian Water Denial ONU", composite_score: 89.25, dam_upstream_coercion_score: 85.0, water_infrastructure_attack_score: 95.0, deliberate_contamination_score: 88.0, access_denial_civilian_score: 90.0, risk_level: "critique", primary_pattern: "attaque_infrastructure_hydrique", key_signals: ["Attaque d'infrastructure hydrique par Russie/Ukraine — destruction du barrage Kakhovka en juin 2023 privant 700 000 personnes d'eau et coupures délibérées à Marioupol et Kherson documentées par l'ONU", "Droit humain fondamental violé — l'accès à l'eau potable est reconnu comme droit humain fondamental par la Résolution ONU 64/292 de 2010, rendant sa négation délibérée constitutive d'une violation grave", "Activer en urgence la Résolution CS-ONU 2417 et le Rapporteur Spécial ONU sur le droit à l'eau pour mesures d'urgence et accès humanitaire immédiat"], estimated_water_weaponization_index: 8.93, last_updated: "2026-06-20" },
    { entity_id: "WW-002", name: "Éthiopie/GERD — Barrage Renaissance Nil & Coercition Égypte/Soudan", country: "Afrique de l'Est", sector: "GERD Remplissage Unilatéral 74M m³, Casus Belli Égypte Eau -2%, Soudan Irrigation Menacée & Nil Bleu Négociations Échouées UA", composite_score: 83.45, dam_upstream_coercion_score: 92.0, water_infrastructure_attack_score: 78.0, deliberate_contamination_score: 75.0, access_denial_civilian_score: 88.0, risk_level: "critique", primary_pattern: "barrage_coercition_amont", key_signals: ["Coercition par barrage amont d'Éthiopie/GERD — remplissage unilatéral du Grand Barrage de la Renaissance menaçant de réduire le débit du Nil de 2% pour l'Égypte, provoquant un casus belli géopolitique", "Droit humain fondamental violé — l'accès à l'eau potable est reconnu comme droit humain fondamental par la Résolution ONU 64/292 de 2010, rendant la manipulation des flux hydriques constitutive d'une violation grave", "Activer en urgence le mécanisme de négociation de l'UA sur le GERD et saisir la CIJ pour arbitrage contraignant sur le partage équitable des eaux du Nil"], estimated_water_weaponization_index: 8.35, last_updated: "2026-06-20" },
    { entity_id: "WW-003", name: "Gaza/Israël — Infrastructure Eau Détruite, Dessalement & Puits Contamination", country: "MENA", sector: "70% Infrastructure Eau Gaza Détruite, 4 Usines Dessalement Hors Service, 2.3M Personnes 3L/Jour Recommandé vs 15L Reçu & OMS Urgence", composite_score: 86.15, dam_upstream_coercion_score: 80.0, water_infrastructure_attack_score: 90.0, deliberate_contamination_score: 85.0, access_denial_civilian_score: 92.0, risk_level: "critique", primary_pattern: "denial_acces_eau_civils", key_signals: ["Déni d'accès à l'eau aux civils de Gaza/Israël — 2.3 millions de civils recevant 3 litres d'eau par jour au lieu des 15 litres minimum OMS, avec 70% de l'infrastructure hydrique détruite", "Droit humain fondamental violé — l'accès à l'eau potable est reconnu comme droit humain fondamental par la Résolution ONU 64/292 de 2010, rendant sa négation délibérée constitutive d'une violation grave", "Activer en urgence la Résolution CS-ONU 2417 et les mesures provisoires de la CIJ ordonnant l'accès humanitaire immédiat à l'eau potable pour la population civile de Gaza"], estimated_water_weaponization_index: 8.62, last_updated: "2026-06-20" },
    { entity_id: "WW-004", name: "Syrie/Assad — Eau Alep Coupée, Euphrate Barrage & Populations Assoiffées", country: "MENA", sector: "Alep Eau Coupée 250 Jours, Barrage Tishreen Contrôle IS, Euphrate Débit Réduit Turquie 40% & UNICEF 12M Sans Eau Sûre Syrie", composite_score: 84.7, dam_upstream_coercion_score: 82.0, water_infrastructure_attack_score: 88.0, deliberate_contamination_score: 82.0, access_denial_civilian_score: 88.0, risk_level: "critique", primary_pattern: "attaque_infrastructure_hydrique", key_signals: ["Attaque d'infrastructure hydrique par Syrie/Assad — eau coupée à Alep pendant 250 jours consécutifs et contrôle du barrage Tishreen utilisé comme arme de guerre contre les populations civiles", "Droit humain fondamental violé — l'accès à l'eau potable est reconnu comme droit humain fondamental par la Résolution ONU 64/292 de 2010, rendant sa négation délibérée constitutive d'une violation grave", "Activer en urgence la Résolution CS-ONU 2417 et saisir la CPI pour crimes contre l'humanité incluant l'utilisation de l'eau comme arme de guerre"], estimated_water_weaponization_index: 8.47, last_updated: "2026-06-20" },
    { entity_id: "WW-005", name: "Chine/Mékong — 11 Barrages Amont, Sécheresses Aval & Pêche Cambodge/Laos", country: "Asie du Sud-Est", sector: "11 Barrages Mékong Chine, Débit Réduit 30% Saison Sèche, Pêche Cambodia -75% & Débit Historique Bas 2019-24 Alerte", composite_score: 55.65, dam_upstream_coercion_score: 65.0, water_infrastructure_attack_score: 55.0, deliberate_contamination_score: 48.0, access_denial_civilian_score: 52.0, risk_level: "élevé", primary_pattern: "barrage_coercition_amont", key_signals: ["Coercition par barrage amont de Chine/Mékong — 11 barrages réduisant le débit du Mékong de 30% en saison sèche, provoquant une chute de 75% des prises de pêche au Cambodge et menaçant la sécurité alimentaire", "Droit humain fondamental violé — la manipulation unilatérale des flux hydriques transfrontaliers viole les droits des populations aval à un accès équitable à l'eau et aux ressources naturelles partagées", "Engager la Commission du Mékong et l'ASEAN pour un accord contraignant de gestion partagée du débit du Mékong incluant des quotas minimaux pour les États aval"], estimated_water_weaponization_index: 5.57, last_updated: "2026-06-20" },
    { entity_id: "WW-006", name: "Yémen/Coalition — Infrastructure Eau Frappes & Choléra 2.5M Cas", country: "MENA", sector: "Frappes Infrastructure Eau Hodeida, Choléra 2.5M Cas Épidémie, UNICEF Pompes Détruites & Population 21M Sans Accès Eau Sûre", composite_score: 56.45, dam_upstream_coercion_score: 52.0, water_infrastructure_attack_score: 62.0, deliberate_contamination_score: 55.0, access_denial_civilian_score: 58.0, risk_level: "élevé", primary_pattern: "attaque_infrastructure_hydrique", key_signals: ["Attaque d'infrastructure hydrique au Yémen/Coalition — frappes sur les systèmes d'eau à Hodeida provoquant une épidémie de choléra avec 2.5 millions de cas, la plus grande épidémie de choléra mondiale en décennies", "Droit humain fondamental violé — l'accès à l'eau potable est reconnu comme droit humain fondamental par la Résolution ONU 64/292 de 2010, rendant la destruction d'infrastructure hydrique constitutive d'un crime de guerre", "Activer en urgence le mécanisme de réponse choléra OMS/UNICEF et saisir le Groupe d'experts ONU sur le Yémen pour documentation des responsabilités"], estimated_water_weaponization_index: 5.65, last_updated: "2026-06-20" },
    { entity_id: "WW-007", name: "Inde/Pakistan — Traité Indus Suspendu & Tensions Eau Kashmir", country: "Asie du Sud", sector: "Traité Indus Waters Suspendu 2023 après Attentat, Chenab Barrage Projets Conflictuels, Pakistanais Agriculture Dépendante & ICJ Arbitrage", composite_score: 28.55, dam_upstream_coercion_score: 28.0, water_infrastructure_attack_score: 25.0, deliberate_contamination_score: 30.0, access_denial_civilian_score: 32.0, risk_level: "modéré", primary_pattern: "denial_acces_eau_civils", key_signals: ["Déni partiel d'accès à l'eau en Inde/Pakistan — suspension unilatérale du Traité des eaux de l'Indus après l'attentat de Pahalgam créant une menace sur l'agriculture pakistanaise tributaire des eaux contrôlées par l'Inde", "Droit humain fondamental et risque de conflit — la manipulation des traités hydriques transfrontaliers peut conduire à une escalade militaire, le Pakistan ayant déclaré toute diversion une 'acte de guerre'", "Réactiver la Banque Mondiale comme médiateur du Traité de l'Indus et engager la CIJ pour arbitrage sur les obligations de l'Inde en matière de partage équitable des eaux"], estimated_water_weaponization_index: 2.86, last_updated: "2026-06-20" },
    { entity_id: "WW-008", name: "ONU-Eau/CICR — Droit à l'Eau & Protection Infrastructures Hydriques", country: "Global", sector: "ONU Résolution 64/292 Droit Eau 2010, CICR Protection Infrastructure Eau DIH, CICID Rapporteur Eau Spécial & Stockholm Water Prize", composite_score: 4.45, dam_upstream_coercion_score: 5.0, water_infrastructure_attack_score: 4.0, deliberate_contamination_score: 3.0, access_denial_civilian_score: 6.0, risk_level: "faible", primary_pattern: "denial_acces_eau_civils", key_signals: ["ONU-Eau/CICR incarne la protection exemplaire du droit à l'eau — Résolution 64/292 reconnaissant l'eau comme droit humain et le DIH protégeant les infrastructures hydriques comme sites protégés en temps de conflit", "Résolution ONU A/RES/64/292 de 2010 — reconnaissance de l'eau potable et de l'assainissement comme droits humains fondamentaux créant des obligations contraignantes de garantie pour tous les États", "Partager les méthodologies CICR de protection des infrastructures hydriques et renforcer la Résolution CS-ONU 2417 sur la famine et l'eau comme armes de guerre"], estimated_water_weaponization_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { barrage_coercition_amont: 2, attaque_infrastructure_hydrique: 3, contamination_deliberee: 0, denial_acces_eau_civils: 3 },
    top_risk_entities: ["Russie/Ukraine — Barrage Kakhovka Destruction & Eau Kherson Coupée", "Gaza/Israël — Infrastructure Eau Détruite, Dessalement & Puits Contamination", "Syrie/Assad — Eau Alep Coupée, Euphrate Barrage & Populations Assoiffées"],
    critical_alerts: ["Russie/Ukraine: attaque infrastructure hydrique", "Éthiopie/GERD: barrage coercition amont", "Gaza/Israël: déni accès eau civils", "Syrie/Assad: attaque infrastructure hydrique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "water_weaponization",
    confidence_score: 0.83,
    data_sources: ["icrc_water_conflict_database", "pacific_institute_water_conflict_chronology", "un_water_global_analysis_assessment"],
    entities,
    avg_estimated_water_weaponization_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
