import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[nps-satisfaction] SWARM_API_URL non défini — mode dégradé activé");
}

const SWARM_API_URL = process.env.SWARM_API_URL;

const entities = [
  {
    id: "CLI-001",
    name: "TechVision SARL",
    sector: "Logiciels & SaaS",
    nps_score: 2.0,
    satisfaction_level: 22.0,
    churn_risk: 85.0,
    response_time_days: 4.0,
    last_contact_date: "2026-05-10",
    total_spent_eur: 48000.0,
    project_count: 3,
    support_tickets: 9,
    recommendation_likelihood: 15.0,
    contract_renewal_months: 2,
    composite_risk_score: 82.25,
    risk_level: "critique",
  },
  {
    id: "CLI-002",
    name: "Groupe Médical Arcen",
    sector: "Santé & Médical",
    nps_score: 3.0,
    satisfaction_level: 28.0,
    churn_risk: 78.0,
    response_time_days: 12.0,
    last_contact_date: "2026-04-28",
    total_spent_eur: 92000.0,
    project_count: 5,
    support_tickets: 8,
    recommendation_likelihood: 20.0,
    contract_renewal_months: 1,
    composite_risk_score: 74.3,
    risk_level: "critique",
  },
  {
    id: "CLI-003",
    name: "Immobilière Bruxelles Est",
    sector: "Immobilier & Promotion",
    nps_score: 4.0,
    satisfaction_level: 30.0,
    churn_risk: 72.0,
    response_time_days: 8.0,
    last_contact_date: "2026-05-20",
    total_spent_eur: 67000.0,
    project_count: 4,
    support_tickets: 10,
    recommendation_likelihood: 28.0,
    contract_renewal_months: 3,
    composite_risk_score: 70.7,
    risk_level: "critique",
  },
  {
    id: "CLI-004",
    name: "Hôtel Le Méridien Bruges",
    sector: "Hôtellerie & Tourisme",
    nps_score: 5.0,
    satisfaction_level: 50.0,
    churn_risk: 55.0,
    response_time_days: 75.0,
    last_contact_date: "2026-04-05",
    total_spent_eur: 115000.0,
    project_count: 6,
    support_tickets: 4,
    recommendation_likelihood: 45.0,
    contract_renewal_months: 5,
    composite_risk_score: 50.75,
    risk_level: "élevé",
  },
  {
    id: "CLI-005",
    name: "Cabinet Juridique Vandermeer",
    sector: "Services Juridiques",
    nps_score: 5.5,
    satisfaction_level: 52.0,
    churn_risk: 50.0,
    response_time_days: 18.0,
    last_contact_date: "2026-05-30",
    total_spent_eur: 78000.0,
    project_count: 4,
    support_tickets: 5,
    recommendation_likelihood: 30.0,
    contract_renewal_months: 6,
    composite_risk_score: 48.0,
    risk_level: "élevé",
  },
  {
    id: "CLI-006",
    name: "Brasserie Artisan Namur",
    sector: "Restauration & Alimentation",
    nps_score: 6.5,
    satisfaction_level: 65.0,
    churn_risk: 30.0,
    response_time_days: 21.0,
    last_contact_date: "2026-06-01",
    total_spent_eur: 34000.0,
    project_count: 2,
    support_tickets: 3,
    recommendation_likelihood: 55.0,
    contract_renewal_months: 9,
    composite_risk_score: 32.75,
    risk_level: "modéré",
  },
  {
    id: "CLI-007",
    name: "FinTech Capitale SA",
    sector: "Finance & Assurance",
    nps_score: 9.0,
    satisfaction_level: 91.0,
    churn_risk: 8.0,
    response_time_days: 2.0,
    last_contact_date: "2026-06-15",
    total_spent_eur: 210000.0,
    project_count: 12,
    support_tickets: 1,
    recommendation_likelihood: 92.0,
    contract_renewal_months: 24,
    composite_risk_score: 9.05,
    risk_level: "faible",
  },
  {
    id: "CLI-008",
    name: "EduTech Benelux ASBL",
    sector: "Éducation & Formation",
    nps_score: 8.5,
    satisfaction_level: 88.0,
    churn_risk: 12.0,
    response_time_days: 3.0,
    last_contact_date: "2026-06-10",
    total_spent_eur: 56000.0,
    project_count: 7,
    support_tickets: 2,
    recommendation_likelihood: 85.0,
    contract_renewal_months: 18,
    composite_risk_score: 13.7,
    risk_level: "faible",
  },
];

const summary = {
  total_clients: 8,
  avg_nps: 5.44,
  avg_satisfaction: 53.25,
  avg_churn_risk: 48.75,
  clients_critique: 3,
  clients_eleve: 2,
  clients_modere: 1,
  clients_faible: 2,
  top_risk_client: "TechVision SARL",
  top_risk_score: 82.25,
  patterns_detected: 5,
  avg_composite: 47.69,
  avg_estimated_satisfaction_index: 4.77,
};

export async function GET() {
  if (!SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse({ entities, summary } as Record<string, unknown>)));
  }
  try {
    const url = new URL(`${SWARM_API_URL}/api/nps-satisfaction`);
    const res = await fetch(url.toString(), { cache: "no-store" });
    if (res.ok) return sealResponse(NextResponse.json(sealResponse(await res.json() as Record<string, unknown>)));
  } catch {}
  return sealResponse(NextResponse.json(sealResponse({ entities: [], summary: {} } as Record<string, unknown>), { status: 502 }));
}
