import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[water-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Water Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/water-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Water Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Water Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "WR-001", name: "Éthiopie/Somalie — 60% Population Sans Eau Potable, Sécheresse & Conflits Points Eau", country: "Afrique de l'Est", sector: "Éthiopie/Somalie 60%+ Sans Eau Potable UNICEF, Sécheresses El Niño 2022-24, Conflits Points Eau Oromia, 90%+ Sans Assainissement Rural & Mortalité Diarrhée Enfants", composite_score: 87.85, safe_water_access_denial_score: 92.0, sanitation_deprivation_score: 88.0, water_privatization_exclusion_score: 85.0, pollution_contamination_score: 85.0, risk_level: "critique", primary_pattern: "deni_acces_eau_potable", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — Éthiopie/Somalie avec score composite 87.85/100 révélant des défaillances systémiques violant la Résolution ONU 64/292 (2010) reconnaissant le droit à l'eau potable et à l'assainissement comme droit humain fondamental", "Déni d'accès à l'eau potable (92.0/100) — les 60%+ de population sans eau potable sécurisée et les conflits autour des points d'eau en Oromia constituent des violations directes du droit à l'eau garanti par la Résolution ONU 64/292", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 8.79, last_updated: "2026-06-20" },
    { entity_id: "WR-002", name: "RDC/Sahel — 74% Défécation Plein Air, Choléra Endémique & Infrastructure Zéro", country: "Afrique Centrale/Ouest", sector: "RDC 74% Défécation Plein Air OMS, Choléra Endémique 300 000 Cas/An, Infrastructure Eau Coloniale Délabrement & Burkina/Mali/Niger Accès Eau <30% Population Rurale", composite_score: 87.50, safe_water_access_denial_score: 88.0, sanitation_deprivation_score: 92.0, water_privatization_exclusion_score: 82.0, pollution_contamination_score: 88.0, risk_level: "critique", primary_pattern: "privation_assainissement", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — RDC/Sahel avec score composite 87.50/100 révélant des défaillances systémiques violant la Résolution ONU 64/292 (2010) reconnaissant le droit à l'eau potable et à l'assainissement comme droit humain fondamental", "Déni d'accès à l'eau potable (88.0/100) — le taux de 74% de défécation à l'air libre en RDC et les 300 000 cas de choléra annuels constituent des violations graves du droit à l'assainissement garanti par la Résolution ONU 70/169", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 8.75, last_updated: "2026-06-20" },
    { entity_id: "WR-003", name: "Inde/Bangladesh — 600M Défécation Plein Air, Arsenic Eau Souterraine & Mangroves", country: "Asie du Sud", sector: "Inde 600M Défécation Plein Air Avant SBA 2014, Bangladesh 25M Arsenic Eau Souterraine WHO, Ganga Pollution Industrielle, Swachh Bharat Progrès & Assainissement Inégal Castes", composite_score: 85.50, safe_water_access_denial_score: 85.0, sanitation_deprivation_score: 88.0, water_privatization_exclusion_score: 80.0, pollution_contamination_score: 90.0, risk_level: "critique", primary_pattern: "contamination_pollution", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — Inde/Bangladesh avec score composite 85.50/100 révélant des défaillances systémiques violant la Résolution ONU 64/292 (2010) reconnaissant le droit à l'eau potable et à l'assainissement comme droit humain fondamental", "Déni d'accès à l'eau potable (85.0/100) — la contamination à l'arsenic affectant 25 millions de Bangladeshis et la pollution industrielle du Gange constituent des violations du droit à une eau salubre garanti par l'Observation Générale 15 du Comité PIDESC", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 8.55, last_updated: "2026-06-20" },
    { entity_id: "WR-004", name: "Flint/USA-Europe — Plomb Eau, PFAS Contamination & Communautés Vulnérables Ciblées", country: "Amérique du Nord/Europe", sector: "Flint Michigan 100 000 Personnes Eau Plomb 2014-19, PFAS Contamination 200M Américains EWG, Hollande/Belgique PFAS Industrie & Communautés Minoritaires Disproportionnément Affectées", composite_score: 83.00, safe_water_access_denial_score: 82.0, sanitation_deprivation_score: 78.0, water_privatization_exclusion_score: 82.0, pollution_contamination_score: 92.0, risk_level: "critique", primary_pattern: "contamination_pollution", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — Flint/USA-Europe avec score composite 83.00/100 révélant des contaminations systémiques ciblant des communautés vulnérables violant le principe de non-discrimination du droit à l'eau", "Déni d'accès à l'eau potable (82.0/100) — la crise de l'eau plombée de Flint ayant affecté 100 000 personnes dont une majorité afro-américaine et la contamination PFAS de 200 millions d'Américains constituent des violations du droit à l'eau potable", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 8.30, last_updated: "2026-06-20" },
    { entity_id: "WR-005", name: "Yémen/Gaza — Eau Arme de Guerre, Infrastructure Détruite & Cholera 2.8M Cas", country: "MENA", sector: "Yémen 2.8M Cas Choléra 2017-24, Infrastructure Eau Bombardée, Gaza Désalinisation Détruite 2024 & OMS Alerte Eau Non-Potable 90% Population Yémen/Gaza Conflits", composite_score: 56.00, safe_water_access_denial_score: 55.0, sanitation_deprivation_score: 58.0, water_privatization_exclusion_score: 48.0, pollution_contamination_score: 65.0, risk_level: "élevé", primary_pattern: "contamination_pollution", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — Yémen/Gaza avec score composite 56.00/100 révélant l'utilisation délibérée de l'eau comme arme de guerre violant le droit international humanitaire (Article 54 Protocole I) et le droit humain à l'eau", "Déni d'accès à l'eau potable (55.0/100) — la destruction de l'infrastructure d'eau à Gaza et au Yémen par des parties au conflit constitue une violation grave du DIH et du droit humain à l'eau garanti par la Résolution ONU 64/292", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 5.60, last_updated: "2026-06-20" },
    { entity_id: "WR-006", name: "Bolivie/Cochabamba — Guerres Eau, Privatisation Bechtel 2000 & Inégalités Rurales", country: "Amérique Latine", sector: "Bolivie Guerre Eau Cochabamba 2000 Privatisation Bechtel, Inégalités Eau Rurales/Urbaines Persistantes, Pérou Minières Contamination Rivières & Équateur Huaorani Pollutions Petroleum", composite_score: 53.90, safe_water_access_denial_score: 50.0, sanitation_deprivation_score: 52.0, water_privatization_exclusion_score: 62.0, pollution_contamination_score: 52.0, risk_level: "élevé", primary_pattern: "exclusion_privatisation_eau", key_signals: ["Violation du droit à l'eau et à l'assainissement documentée — Bolivie/Cochabamba avec score composite 53.90/100 révélant les conséquences de la privatisation de l'eau ayant exclu les populations pauvres de l'accès à l'eau potable", "Déni d'accès à l'eau potable (50.0/100) — la privatisation de l'eau de Cochabamba par Bechtel en 2000 ayant conduit à des augmentations de tarifs de 200% et exclu les populations pauvres illustre le risque du modèle de privatisation pour le droit humain à l'eau", "Activer le Rapporteur Spécial ONU sur le droit à l'eau potable et à l'assainissement et exiger l'application du Plan d'action ONU-Eau pour atteindre l'ODD6 d'accès universel à l'eau potable d'ici 2030"], estimated_water_rights_index: 5.39, last_updated: "2026-06-20" },
    { entity_id: "WR-007", name: "Europe/Sécheresses — Espagne/Italie Restrictions, Nappes Phréatiques & Conflits Agricoles", country: "Europe", sector: "Espagne Sécheresse 2022-24 Restrictions Eau Barcelone, Italie Pô Nappe Record Bas, France SDAGE Révisions & Conflits Agriculteurs Ménages Méga-Bassines Sainte-Soline", composite_score: 28.55, safe_water_access_denial_score: 28.0, sanitation_deprivation_score: 25.0, water_privatization_exclusion_score: 30.0, pollution_contamination_score: 32.0, risk_level: "modéré", primary_pattern: "contamination_pollution", key_signals: ["Tensions émergentes sur le droit à l'eau en Europe — sécheresses récurrentes en Espagne, Italie et France créant des conflits d'usage entre agriculture et ménages soulevant des questions de droit à l'eau dans des pays développés", "Déni d'accès à l'eau potable (28.0/100) — les restrictions d'eau imposées à Barcelone et les conflits autour des méga-bassines en France révèlent des tensions croissantes sur la gouvernance de l'eau dans le contexte du changement climatique", "Renforcer les Schémas Directeurs d'Aménagement et de Gestion des Eaux (SDAGE) en Europe pour garantir le droit prioritaire des ménages à l'eau potable face aux usages agricoles et industriels dans un contexte de rareté climatique"], estimated_water_rights_index: 2.86, last_updated: "2026-06-20" },
    { entity_id: "WR-008", name: "ONU-Eau/PIDESC — Résolution 64/292 Droit Eau, ODD6 & Rapporteur Spécial", country: "Global", sector: "Résolution ONU 64/292 2010 Droit Eau Assainissement, PIDESC Observation Générale 15, ODD6 Eau Propre, Rapporteur Spécial ONU Eau/Assainissement & ONU-Eau Plan Action", composite_score: 4.45, safe_water_access_denial_score: 5.0, sanitation_deprivation_score: 4.0, water_privatization_exclusion_score: 3.0, pollution_contamination_score: 6.0, risk_level: "faible", primary_pattern: "contamination_pollution", key_signals: ["ONU-Eau/PIDESC incarne le cadre exemplaire du droit à l'eau et à l'assainissement — Résolution 64/292 de 2010 et Observation Générale 15 du Comité PIDESC créant des obligations contraignantes d'accessibilité, disponibilité et qualité de l'eau pour tous", "Résolution ONU 64/292 — reconnaît explicitement le droit à l'eau potable et à l'assainissement comme droit humain essentiel à la réalisation de tous les droits humains, imposant aux États des obligations progressives de mise en œuvre universelle", "Universaliser l'accès à l'eau potable via le Fonds ODD6 et renforcer les mécanismes de gouvernance internationale de l'eau douce pour prévenir les conflits hydriques liés au changement climatique et à la surexploitation des nappes phréatiques"], estimated_water_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { deni_acces_eau_potable: 1, privation_assainissement: 1, exclusion_privatisation_eau: 1, contamination_pollution: 5 },
    top_risk_entities: ["Éthiopie/Somalie — 60% Population Sans Eau Potable, Sécheresse & Conflits Points Eau", "RDC/Sahel — 74% Défécation Plein Air, Choléra Endémique & Infrastructure Zéro", "Inde/Bangladesh — 600M Défécation Plein Air, Arsenic Eau Souterraine & Mangroves"],
    critical_alerts: ["Éthiopie/Somalie: déni accès eau potable", "RDC/Sahel: privation assainissement", "Inde/Bangladesh: contamination pollution", "Flint/USA-Europe: contamination pollution"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "water_rights",
    confidence_score: 0.83,
    data_sources: ["who_unicef_joint_monitoring_programme_water_sanitation", "un_special_rapporteur_right_to_safe_water_sanitation_reports", "ewg_tap_water_database_contamination"],
    entities,
    avg_estimated_water_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
