import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[antipersonnel-mines-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Antipersonnel Mines Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/antipersonnel-mines-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Antipersonnel Mines Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Antipersonnel Mines Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "AM-001", name: "Russie/Ukraine — Mines OZM-72 & Sous-Munitions Zones Civiles", country: "Europe de l'Est", sector: "Mines Pétales POM-3 Kherson, MLRS BM-21 Sous-Munitions Villes, 174 000 km² Contaminés HRW & Non Signataire Ottawa", composite_score: 91.0, active_mine_deployment_score: 95.0, civilian_contamination_area_score: 92.0, treaty_noncompliance_production_score: 90.0, victim_clearance_impunity_score: 85.0, risk_level: "critique", primary_pattern: "contamination_massive_civils", key_signals: ["Contamination massive de zones civiles de Russie/Ukraine — déploiement délibéré de mines à sous-munitions et pétales dans des zones agricoles et résidentielles générant des victimes durables", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Activer le mécanisme d'urgence de déminage humanitaire UNMAS et saisir le Comité de mise en œuvre du Traité d'Ottawa"], estimated_antipersonnel_mines_index: 9.1, last_updated: "2026-06-20" },
    { id: "AM-002", name: "Yémen/Houthis — Mines Maritimes & IED Résidentiels", country: "MENA", sector: "Mines Maritimes Détroit Bab-el-Mandeb, IED Routes Civiles Taiz, 100 000+ Zones Contaminées & ONU Liste Noire Persistante", composite_score: 86.15, active_mine_deployment_score: 88.0, civilian_contamination_area_score: 85.0, treaty_noncompliance_production_score: 82.0, victim_clearance_impunity_score: 90.0, risk_level: "critique", primary_pattern: "engins_improvises_massifs", key_signals: ["Engins explosifs improvisés massifs de Yémen/Houthis — déploiement de mines maritimes et IED sur les routes commerciales et civiles avec effets durables sur la mobilité humanitaire", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Renforcer les capacités CIED via OTAN/UNMAS et activer les mécanismes de sanction contre les fournisseurs de matériaux explosifs"], estimated_antipersonnel_mines_index: 8.62, last_updated: "2026-06-20" },
    { id: "AM-003", name: "Myanmar/Tatmadaw — Mines Villages Ethniques & Champs Cultivés", country: "Asie du Sud-Est", sector: "Mines Frontières Karen/Kachin, Villages Ethniques Contaminés, HRW 2020-24 Documentation & Non Signataire Ottawa", composite_score: 84.0, active_mine_deployment_score: 85.0, civilian_contamination_area_score: 88.0, treaty_noncompliance_production_score: 82.0, victim_clearance_impunity_score: 80.0, risk_level: "critique", primary_pattern: "sous_munitions_urbaines", key_signals: ["Armes à sous-munitions en zones civiles de Myanmar/Tatmadaw — mines antipersonnel déployées dans des villages et champs agricoles des minorités ethniques après les offensives militaires", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Saisir le mécanisme de la Convention d'Oslo sur les armes à sous-munitions et demander cessation immédiate des frappes en zones peuplées"], estimated_antipersonnel_mines_index: 8.4, last_updated: "2026-06-20" },
    { id: "AM-004", name: "Syrie/Assad — Barils Explosifs & Sous-Munitions Alep/Idlib", country: "MENA", sector: "Su-25 Sous-Munitions Alep/Idlib, Barils Explosifs Hmeimim, 700+ km² Contaminés & OIAC Documentation", composite_score: 83.45, active_mine_deployment_score: 82.0, civilian_contamination_area_score: 85.0, treaty_noncompliance_production_score: 80.0, victim_clearance_impunity_score: 88.0, risk_level: "critique", primary_pattern: "engins_improvises_massifs", key_signals: ["Engins explosifs improvisés massifs de Syrie/Assad — barils explosifs larghés sur des zones résidentielles et sous-munitions aéroportées en violations graves du droit humanitaire", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Renforcer les capacités CIED via OTAN/UNMAS et activer les mécanismes de sanction contre les fournisseurs de matériaux explosifs"], estimated_antipersonnel_mines_index: 8.35, last_updated: "2026-06-20" },
    { id: "AM-005", name: "Afghanistan/Taliban — Mines Soviétiques Résiduelles & IED", country: "Asie Centrale", sector: "10M Mines Résiduelles Guerre 1979-89, Taliban IED Routes, HALO Trust 2M Mines Neutralisées & 2400 Victimes/An Pic", composite_score: 59.4, active_mine_deployment_score: 55.0, civilian_contamination_area_score: 72.0, treaty_noncompliance_production_score: 50.0, victim_clearance_impunity_score: 62.0, risk_level: "élevé", primary_pattern: "sous_munitions_urbaines", key_signals: ["Contamination historique massive d'Afghanistan — héritage de 10 millions de mines soviétiques cumulé aux IED Taliban créant une pollution explosive multi-décennale", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Activer le mécanisme d'urgence de déminage humanitaire UNMAS et augmenter le financement du HALO Trust"], estimated_antipersonnel_mines_index: 5.94, last_updated: "2026-06-20" },
    { id: "AM-006", name: "Colombie/FARC Résiduels — Mines Zones Rurales & Démineurs Tués", country: "Amérique du Sud", sector: "FARC Mines Plantations Cocaïne, 12 000+ Victimes Mines 1990-2023, Accords 2016 Déminage & ELN Poursuit Déploiement", composite_score: 53.5, active_mine_deployment_score: 50.0, civilian_contamination_area_score: 58.0, treaty_noncompliance_production_score: 52.0, victim_clearance_impunity_score: 55.0, risk_level: "élevé", primary_pattern: "sous_munitions_urbaines", key_signals: ["Contamination rurale persistante de Colombie — 12 000+ victimes de mines sur 30 ans, déploiement résiduel par dissidences FARC et ELN malgré les accords de paix", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Activer le mécanisme d'urgence de déminage humanitaire UNMAS et soutenir les programmes DDR colombiens"], estimated_antipersonnel_mines_index: 5.35, last_updated: "2026-06-20" },
    { id: "AM-007", name: "Angola/Post-Conflit — 15M Mines Héritées Guerre Civile", country: "Afrique Australe", sector: "15M Mines Estimées Guerre 27 Ans, 84 000 Victimes Enregistrées, NPA Déminage Actif & Ottawa Signataire 2002", composite_score: 28.9, active_mine_deployment_score: 28.0, civilian_contamination_area_score: 32.0, treaty_noncompliance_production_score: 22.0, victim_clearance_impunity_score: 35.0, risk_level: "modéré", primary_pattern: "engins_improvises_massifs", key_signals: ["Héritage explosif post-conflit d'Angola — 15 millions de mines héritées de 27 ans de guerre civile avec progrès de déminage significatifs mais pollution résiduelle persistante", "Victimes civiles longue durée — les mines et sous-munitions non explosées continuent de tuer et mutiler des civils des décennies après la fin des conflits", "Renforcer le financement NPA/HALO Trust et activer le Fonds fiduciaire ONU pour l'action antimines Angola"], estimated_antipersonnel_mines_index: 2.89, last_updated: "2026-06-20" },
    { id: "AM-008", name: "UNMAS/HALO Trust — Déminage Humanitaire & Traité Ottawa", country: "Global", sector: "Ottawa Treaty 164 États Parties, UNMAS 40+ Pays, HALO Trust 3M Mines Neutralisées & Landmine Monitor Annuel", composite_score: 4.45, active_mine_deployment_score: 5.0, civilian_contamination_area_score: 4.0, treaty_noncompliance_production_score: 3.0, victim_clearance_impunity_score: 6.0, risk_level: "faible", primary_pattern: "deminage_exemplaire", key_signals: ["UNMAS/HALO Trust incarne le déminage humanitaire exemplaire — Traité d'Ottawa respecté, financement actif du déminage et assistance aux victimes selon les standards IMAS", "Normes internationales appliquées — 164 États parties au Traité d'Ottawa avec obligations de déminage, destruction des stocks et assistance aux victimes dans des délais contraignants", "Partager les méthodologies de déminage et augmenter les contributions au Fonds GICHD pour accélérer la dépollution dans les pays les plus affectés"], estimated_antipersonnel_mines_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { contamination_massive_civils: 1, refus_traite_minage: 0, sous_munitions_urbaines: 3, engins_improvises_massifs: 3, deminage_exemplaire: 1 },
    top_risk_entities: ["Russie/Ukraine — Mines OZM-72 & Sous-Munitions Zones Civiles", "Yémen/Houthis — Mines Maritimes & IED Résidentiels", "Myanmar/Tatmadaw — Mines Villages Ethniques & Champs Cultivés"],
    critical_alerts: ["Russie/Ukraine: contamination massive zones civiles", "Yémen/Houthis: engins improvisés massifs", "Myanmar/Tatmadaw: armes sous-munitions zones civiles", "Syrie/Assad: engins improvisés massifs"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "antipersonnel_mines",
    confidence_score: 0.85,
    data_sources: ["landmine_cluster_munition_monitor_annual", "unmas_annual_report_mine_action", "hrw_explosive_weapons_civilian_harm"],
    entities,
    avg_estimated_antipersonnel_mines_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
