import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[economic-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Economic Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/economic-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Economic Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Economic Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "ER-001", name: "RDC/Cobalt — Mines Artisanales 40 000 Enfants, Cobalt Apple/Tesla & Impunité", country: "Afrique Centrale", sector: "RDC 40 000 Enfants Mines Cobalt Artisanales, Cobalt 70% Mondial Sans Standard Travail, Apple/Tesla Chaîne Approvisionnement, Salaires 2$/Jour & Aucune Protection Sociale Mineurs", composite_score: 88.95, decent_work_denial_score: 92.0, wage_theft_exploitation_score: 90.0, union_suppression_score: 85.0, social_floor_absence_score: 88.0, risk_level: "critique", primary_pattern: "decent_work_denial", key_signals: ["Violation des droits économiques documentée — RDC/Cobalt avec score composite 88.95/100 révélant une exploitation systémique des travailleurs des mines artisanales violant l'Article 7 du PIDESC sur le droit à des conditions de travail justes et favorables", "Déni travail décent (92.0/100) — les 40 000 enfants dans les mines de cobalt artisanales et les salaires de 2$/jour violent simultanément la Convention OIT 138 sur l'âge minimum et l'Article 7 PIDESC sur les conditions de travail équitables", "Activer les mécanismes de diligence raisonnable de l'OCDE sur les chaînes d'approvisionnement et exiger l'application de la Directive UE sur la durabilité des entreprises pour obliger Apple, Tesla et les multinationales utilisant le cobalt à garantir le respect des droits au travail"], estimated_economic_rights_index: 8.90, last_updated: "2026-06-20" },
    { entity_id: "ER-002", name: "Bangladesh/Rana Plaza — 1 134 Morts, 4M Ouvriers Textile & Accord Fire Safety", country: "Asie du Sud", sector: "Bangladesh Rana Plaza 2013 1 134 Morts Effondrement Usine, 4M Ouvriers Textile 95% Femmes, Salaire 95$/Mois, Accord Incendie-Sécurité Insuffisant & H&M/Zara Chaînes Responsabilité", composite_score: 87.15, decent_work_denial_score: 88.0, wage_theft_exploitation_score: 90.0, union_suppression_score: 85.0, social_floor_absence_score: 85.0, risk_level: "critique", primary_pattern: "wage_theft_exploitation", key_signals: ["Violation des droits économiques documentée — Bangladesh/Rana Plaza avec score composite 87.15/100 révélant les conditions de travail mortelles dans l'industrie textile et l'exploitation systémique de 4 millions de travailleurs violant le PIDESC Art 7 et les Conventions OIT 155 et 187 sur la sécurité au travail", "Vol de salaires/Exploitation (90.0/100) — les salaires de 95$/mois et les conditions mortelles de l'industrie textile bangladaise illustrent l'exploitation de chaînes d'approvisionnement mondiales violant les Principes Directeurs ONU sur les entreprises et les droits de l'homme", "Ratifier et appliquer la Convention OIT 190 sur la violence et le harcèlement au travail et étendre l'Accord de Dhaka sur la sécurité incendie à toutes les chaînes d'approvisionnement textiles mondiales avec mécanisme contraignant de responsabilité des donneurs d'ordre"], estimated_economic_rights_index: 8.72, last_updated: "2026-06-20" },
    { entity_id: "ER-003", name: "Pakistan/Briques — 4.5M Travailleurs Liés, Travail Forcé Dettes & Peshgi", country: "Asie du Sud", sector: "Pakistan 4.5M Travailleurs Liés Briqueteries Peshgi Avances-Dettes, Familles Héréditaires Travail Forcé, 0 Syndicat Briqueteries & OIT Rapport Travail Forcé Pakistan Systémique", composite_score: 86.15, decent_work_denial_score: 88.0, wage_theft_exploitation_score: 85.0, union_suppression_score: 82.0, social_floor_absence_score: 90.0, risk_level: "critique", primary_pattern: "social_floor_absence", key_signals: ["Violation des droits économiques documentée — Pakistan/Briques avec score composite 86.15/100 révélant 4.5 millions de travailleurs en situation de servitude pour dettes dans les briqueteries violant la Convention OIT 29 sur le travail forcé et l'Article 8 du PIDCP", "Absence plancher social (90.0/100) — le système Peshgi d'avances-dettes créant une servitude héréditaire pour des familles entières dans les briqueteries constitue une forme de travail forcé interdite par la Convention de l'esclavage de 1926 et la Convention OIT 105", "Activer le mécanisme d'examen de la Convention OIT 29 contre le travail forcé et conditionner les accords commerciaux UE-Pakistan au respect des droits fondamentaux au travail incluant l'interdiction effective du système Peshgi de travail lié"], estimated_economic_rights_index: 8.62, last_updated: "2026-06-20" },
    { entity_id: "ER-004", name: "Asie/Zones Franches — 100M Travailleurs ZES, Syndicats Interdits & Salaire Minimal", country: "Asie du Sud-Est/Chine", sector: "Zones Économiques Spéciales 100M Travailleurs, Syndicats Interdits Bangladesh/Vietnam/Cambodge ZES, Salaire Minimum Non-Appliqué, Licenciements Représailles & Contrats Zéro-Droits", composite_score: 85.75, decent_work_denial_score: 85.0, wage_theft_exploitation_score: 85.0, union_suppression_score: 92.0, social_floor_absence_score: 80.0, risk_level: "critique", primary_pattern: "union_suppression", key_signals: ["Violation des droits économiques documentée — Asie/Zones Franches avec score composite 85.75/100 révélant la suppression systémique des droits syndicaux dans les Zones Économiques Spéciales violant la Convention OIT 87 sur la liberté syndicale et l'Article 8 du PIDESC", "Suppression syndicale (92.0/100) — l'interdiction des syndicats indépendants dans les zones franches de Bangladesh, Vietnam et Cambodge prive 100 millions de travailleurs de leur droit fondamental à l'organisation collective garanti par les Conventions fondamentales de l'OIT", "Exiger des États membres de l'OIT le respect des Conventions fondamentales 87 et 98 sur la liberté syndicale dans les Zones Économiques Spéciales et conditionner l'accès aux marchés des pays de l'OCDE au respect effectif des droits syndicaux"], estimated_economic_rights_index: 8.58, last_updated: "2026-06-20" },
    { entity_id: "ER-005", name: "USA/Gig Economy — 59M Travailleurs Plateformes, 0 Protection & Amazon Surveillance", country: "Amérique du Nord", sector: "USA 59M Travailleurs Gig Economy Sans Protection Sociale, Amazon Algorithmes Surveillance Employés, Walmart Répression Syndicale, Minimum Wage 7.25$/H Depuis 2009 & Prop 22 Californie", composite_score: 53.10, decent_work_denial_score: 52.0, wage_theft_exploitation_score: 58.0, union_suppression_score: 52.0, social_floor_absence_score: 50.0, risk_level: "élevé", primary_pattern: "wage_theft_exploitation", key_signals: ["Violation des droits économiques documentée — USA/Gig Economy avec score composite 53.10/100 révélant l'exclusion délibérée de 59 millions de travailleurs de plateforme de toute protection sociale violant l'Article 7 PIDESC sur des conditions de travail équitables (PIDESC non ratifié par les USA)", "Vol de salaires/Exploitation (58.0/100) — la classification des chauffeurs Uber/Lyft et livreurs DoorDash comme 'entrepreneurs indépendants' pour contourner les protections sociales constitue une violation des Conventions OIT sur le travail décent", "Ratifier le PIDESC et adopter une loi fédérale classifiant les travailleurs de plateforme comme employés avec droits à la protection sociale, syndicale et aux congés payés conformément aux standards de l'OIT sur le travail décent"], estimated_economic_rights_index: 5.31, last_updated: "2026-06-20" },
    { entity_id: "ER-006", name: "Europe/Précariat — Zéro-Heures UK, Faux Auto-Entrepreneurs & Riders Livreurs", country: "Europe", sector: "UK 1M Contrats Zéro-Heures 2023, Faux Autoentrepreneurs France Deliveroo/Uber Eats, Espagne Riders Loi Insuffisante & ETUC Rapports Droits Précaires Non-Protégés Plate-Formes", composite_score: 51.10, decent_work_denial_score: 52.0, wage_theft_exploitation_score: 48.0, union_suppression_score: 50.0, social_floor_absence_score: 55.0, risk_level: "élevé", primary_pattern: "social_floor_absence", key_signals: ["Violation des droits économiques documentée — Europe/Précariat avec score composite 51.10/100 révélant la prolifération des formes d'emploi atypiques contournant les protections sociales en contradiction avec la Charte Sociale Européenne Révisée", "Absence plancher social (55.0/100) — le million de contrats zéro-heures au Royaume-Uni et les faux auto-entrepreneurs dans les plateformes de livraison privent des millions de travailleurs européens de sécurité sociale, congés payés et protection contre le licenciement", "Renforcer la Directive UE sur les travailleurs de plateforme 2024 pour garantir une présomption d'emploi et des droits sociaux complets aux 28 millions de travailleurs de plateforme européens conformément aux recommandations de l'ETUC"], estimated_economic_rights_index: 5.11, last_updated: "2026-06-20" },
    { entity_id: "ER-007", name: "Japon/Karoshi — 2 000 Décès/An Surmenage, Non-Regular Workers & Hôtesses", country: "Asie du Nord-Est", sector: "Japon 2 000+ Décès Karoshi Surmenage/An, 7M Travailleurs Non-Réguliers Salaire -40%, Heures Supplémentaires Non-Payées Mutsuko & Convention OIT Temps Travail Non-Respectée", composite_score: 29.15, decent_work_denial_score: 28.0, wage_theft_exploitation_score: 35.0, union_suppression_score: 28.0, social_floor_absence_score: 25.0, risk_level: "modéré", primary_pattern: "wage_theft_exploitation", key_signals: ["Défis persistants des droits économiques au Japon — le phénomène Karoshi (mort par surmenage) causant 2 000+ décès annuels et l'exclusion de 7 millions de travailleurs non-réguliers des protections complètes révèlent des lacunes dans l'application des droits au travail", "Vol de salaires/Exploitation (35.0/100) — les heures supplémentaires non-payées, les salaires des travailleurs non-réguliers inférieurs de 40% aux réguliers et le Karoshi constituent des violations des limites de temps de travail fixées par la Convention OIT 1 (1919)", "Réformer le droit du travail japonais pour éliminer le dualisme régulier/non-régulier, mettre en œuvre une loi anti-Karoshi contraignante et ratifier les Conventions OIT sur les droits syndicaux conformément aux recommandations du Comité des droits économiques ONU"], estimated_economic_rights_index: 2.92, last_updated: "2026-06-20" },
    { entity_id: "ER-008", name: "OIT/PIDESC — Agenda Travail Décent, Art 7 Conditions Justes & Conventions Fondamentales", country: "Global", sector: "OIT Agenda Travail Décent 2008, PIDESC Article 7 Conditions Travail Équitables, OIT 8 Conventions Fondamentales, Salaire Minimum Vital OIT & Initiative Multi-Parties Partenariat Global", composite_score: 4.45, decent_work_denial_score: 5.0, wage_theft_exploitation_score: 4.0, union_suppression_score: 3.0, social_floor_absence_score: 6.0, risk_level: "faible", primary_pattern: "social_floor_absence", key_signals: ["OIT/PIDESC incarne le cadre normatif exemplaire des droits économiques — Agenda Travail Décent 2008 et Article 7 PIDESC créant des obligations contraignantes de conditions de travail justes, sécurité sociale et liberté syndicale pour tous les travailleurs sans distinction", "Convention OIT 87 sur la liberté syndicale — garantit le droit fondamental de tout travailleur de constituer des syndicats et d'y adhérer, constituant la pierre angulaire des droits économiques reconnus par les 8 Conventions fondamentales de l'OIT ratifiées par 180+ États", "Universaliser la ratification des 8 Conventions fondamentales de l'OIT et tripler le budget de l'OIT pour renforcer les capacités d'inspection du travail dans les pays à revenus faibles et intermédiaires afin d'assurer le travail décent pour tous d'ici 2030"], estimated_economic_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { decent_work_denial: 1, wage_theft_exploitation: 3, union_suppression: 1, social_floor_absence: 3 },
    top_risk_entities: ["RDC/Cobalt — Mines Artisanales 40 000 Enfants, Cobalt Apple/Tesla & Impunité", "Bangladesh/Rana Plaza — 1 134 Morts, 4M Ouvriers Textile & Accord Fire Safety", "Pakistan/Briques — 4.5M Travailleurs Liés, Travail Forcé Dettes & Peshgi"],
    critical_alerts: ["RDC/Cobalt: déni travail décent", "Bangladesh/Rana Plaza: vol salaires exploitation", "Pakistan/Briques: absence plancher social", "Asie/Zones Franches: suppression syndicale"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "economic_rights",
    confidence_score: 0.84,
    data_sources: ["ilo_world_employment_social_outlook_report", "un_special_rapporteur_extreme_poverty_economic_rights_reports", "business_human_rights_resource_centre_labour_violations_database"],
    entities,
    avg_estimated_economic_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
