import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[death-penalty-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Death Penalty Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/death-penalty-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Death Penalty Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Death Penalty Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "DP-001", name: "Chine — 2 000+ Exécutions/An, Secret État & Organes Prisonniers", country: "Asie du Nord-Est", sector: "Chine 2 000+ Exécutions Estimées/An Amnesty Classifié Secret État, Trafic Organes Prisonniers Condamnés Documenté Tribunaux Chine, Crimes Non-Violents Punis Mort & Procès Sans Garanties", composite_score: 93.00, execution_volume_severity_score: 95.0, legal_safeguard_absence_score: 92.0, wrongful_execution_risk_score: 90.0, abolition_resistance_score: 95.0, risk_level: "critique", primary_pattern: "execution_volume_severity", key_signals: ["Violation du droit à la vie documentée — Chine avec score composite 93.00/100 révélant le plus grand nombre d'exécutions au monde (2 000+/an estimés) gardé secret d'État et le prélèvement d'organes sur des prisonniers condamnés, violant l'Article 6 du PIDCP", "Volume exécutions (95.0/100) — la Chine exécute plus de personnes que tous les autres pays réunis selon Amnesty International, avec des condamnations pour crimes non-violents (fraude, trafic de drogue) violant les Garanties de l'ONU pour la protection des personnes passibles de la peine de mort", "Activer le Rapporteur Spécial ONU sur les exécutions extrajudiciaires pour enquête urgente sur les pratiques d'exécution chinoises et exiger la publication des statistiques officielles conformément aux résolutions de l'Assemblée Générale ONU sur le moratoire universel"], estimated_death_penalty_index: 9.30, last_updated: "2026-06-20" },
    { id: "DP-002", name: "Iran — 853 Exécutions 2023, Pendaisons Publiques & Minorités Ethniques", country: "MENA", sector: "Iran 853 Exécutions 2023 Record Décennie Amnesty, Pendaisons Publiques Rues, Kurdes/Baloutches Surreprésentés, Crimes Drogue 50%+ Exécutions & Mineurs Exécutés Malgré Interdiction CDE", composite_score: 90.50, execution_volume_severity_score: 92.0, legal_safeguard_absence_score: 90.0, wrongful_execution_risk_score: 88.0, abolition_resistance_score: 92.0, risk_level: "critique", primary_pattern: "execution_volume_severity", key_signals: ["Violation du droit à la vie documentée — Iran avec score composite 90.50/100 révélant 853 exécutions en 2023 (record de la décennie), dont des pendaisons publiques et des exécutions de membres de minorités ethniques kurdes et baloutches en violation de l'Article 6 PIDCP", "Volume exécutions (92.0/100) — les 853 exécutions iraniennes de 2023, dont 50%+ pour trafic de drogue et des mineurs exécutés contrairement à l'Article 37 de la CDE, révèlent une violation systémique du droit international des droits humains sur la peine de mort", "Activer le Comité des droits de l'homme ONU pour examen d'urgence des pratiques d'exécution iraniennes et exiger un moratoire immédiat sur les exécutions pour crimes de drogue conformément aux résolutions de la Commission des stupéfiants de l'ONU"], estimated_death_penalty_index: 9.05, last_updated: "2026-06-20" },
    { id: "DP-003", name: "Arabie Saoudite/Golfe — 196 Exécutions 2022, Décapitations Publiques & Travailleurs Migrants", country: "MENA", sector: "Arabie Saoudite 196 Exécutions 2022 Record, Décapitations Publiques Vendredi, Travailleurs Migrants 70%+ Condamnés Mort Ressortissants Étrangers, Crimes Sorcellerie/Blasphème & Mineurs", composite_score: 89.50, execution_volume_severity_score: 88.0, legal_safeguard_absence_score: 92.0, wrongful_execution_risk_score: 90.0, abolition_resistance_score: 88.0, risk_level: "critique", primary_pattern: "legal_safeguard_absence", key_signals: ["Violation du droit à la vie documentée — Arabie Saoudite avec score composite 89.50/100 révélant 196 exécutions publiques par décapitation en 2022, dont 70%+ de ressortissants étrangers (travailleurs migrants) sans accès consulaire adéquat, violant la Convention de Vienne", "Absence garanties légales (92.0/100) — les condamnations à mort pour sorcellerie, blasphème et trafic de drogue en Arabie Saoudite sans standards minimaux de procès équitable violent les Garanties minimales ONU pour les personnes passibles de la peine de mort (résolution 1984/50)", "Activer le Rapporteur Spécial ONU sur les exécutions extrajudiciaires pour enquête sur les pratiques saoudiennes et exiger le respect des droits consulaires des travailleurs migrants condamnés à mort conformément à l'arrêt de la CIJ dans l'affaire LaGrand"], estimated_death_penalty_index: 8.95, last_updated: "2026-06-20" },
    { id: "DP-004", name: "USA — 2 700 Condamnés Couloir Mort, Exécutions Innocents & Racial Bias", country: "Amérique du Nord", sector: "USA 2 700 Condamnés Couloir Mort, 190+ Exonérations DNA Couloir Mort Depuis 1973, Biais Racial Documenté Condamnations Noirs, Arkansas/Texas Exécutions Controversées & SCOTUS Limitations", composite_score: 67.10, execution_volume_severity_score: 62.0, legal_safeguard_absence_score: 58.0, wrongful_execution_risk_score: 92.0, abolition_resistance_score: 55.0, risk_level: "critique", primary_pattern: "wrongful_execution_risk", key_signals: ["Violation du droit à la vie documentée — USA avec score composite 67.10/100 révélant 190+ exonérations d'innocents dans les couloirs de la mort depuis 1973 et un biais racial documenté dans les condamnations à mort violant l'Article 6 PIDCP et l'égalité devant la loi", "Risque exécution innocents (92.0/100) — les 190+ exonérations par ADN de condamnés à mort aux USA révèlent un taux d'erreur judiciaire incompatible avec l'irréversibilité de la peine de mort, violant l'obligation de garanties absolues de l'Article 6 PIDCP", "Instaurer un moratoire fédéral sur les exécutions et ratifier le Protocole facultatif au PIDCP visant à l'abolition de la peine de mort (Protocole 2), rejoignant les 90 États abolitionnistes conformément aux résolutions de l'Assemblée Générale ONU A/RES/77/222"], estimated_death_penalty_index: 6.71, last_updated: "2026-06-20" },
    { id: "DP-005", name: "Japon — Condamnés Secret Total, Exécution Sans Préavis & Isolement Cellulaire", country: "Asie du Nord-Est", sector: "Japon Exécutions Sans Préavis Famille/Avocat, Condamnés Couloir Mort 100+ Isolement Complet, Décision Exécution Secrete Ministre Justice & Attente Décennies Incertitude Psychologique Documentée", composite_score: 54.60, execution_volume_severity_score: 52.0, legal_safeguard_absence_score: 62.0, wrongful_execution_risk_score: 50.0, abolition_resistance_score: 55.0, risk_level: "élevé", primary_pattern: "legal_safeguard_absence", key_signals: ["Violation du droit à la vie documentée — Japon avec score composite 54.60/100 révélant des exécutions réalisées sans aucun préavis aux condamnés, familles et avocats, créant une torture psychologique permanente qualifiée de traitement inhumain par le Comité contre la torture de l'ONU", "Absence garanties légales (62.0/100) — la pratique japonaise d'exécution secrète sans préavis et l'isolement cellulaire complet pendant des décennies dans les couloirs de la mort constituent des violations des Articles 7 et 10 PIDCP sur le traitement humain des détenus", "Instaurer un moratoire immédiat au Japon et réformer le système pour garantir notification préalable aux condamnés, familles et avocats conformément aux recommandations du Comité des droits de l'homme ONU dans ses observations finales sur le Japon 2022"], estimated_death_penalty_index: 5.46, last_updated: "2026-06-20" },
    { id: "DP-006", name: "Singapour/Malaisie — Trafic Drogue Peine Mort Obligatoire & Pendaisons 2022-23", country: "Asie du Sud-Est", sector: "Singapour Peine Mort Obligatoire Trafic Drogue Jusqu'En 2012 Puis Partielle, 11 Exécutions 2022 Taux/Capita Record Mondial, Malaisie 1 300 Condamnés Mort Drogue & Réforme Insuffisante", composite_score: 55.00, execution_volume_severity_score: 55.0, legal_safeguard_absence_score: 60.0, wrongful_execution_risk_score: 50.0, abolition_resistance_score: 55.0, risk_level: "élevé", primary_pattern: "legal_safeguard_absence", key_signals: ["Violation du droit à la vie documentée — Singapour/Malaisie avec score composite 55.00/100 révélant l'application de la peine de mort obligatoire pour trafic de drogue, l'un des taux d'exécution per capita les plus élevés au monde, en contradiction avec les standards ONU", "Absence garanties légales (60.0/100) — la peine de mort obligatoire pour trafic de drogue à Singapour, même partiellement réformée, ne permet pas l'individualisation de la peine exigée par les Garanties minimales ONU et le Comité des droits de l'homme pour les infractions à la drogue", "Abolir la peine de mort pour les infractions liées à la drogue à Singapour et en Malaisie conformément aux standards internationaux émergents et aux résolutions de la Commission des stupéfiants de l'ONU reconnaissant l'échec de l'approche pénale pour réduire le trafic"], estimated_death_penalty_index: 5.50, last_updated: "2026-06-20" },
    { id: "DP-007", name: "Europe/CEDH — Protocole 13 Abolition Totale & Pressions Russie/Biélorussie", country: "Europe", sector: "Europe Protocole 13 CEDH Abolition Totale Toutes Circonstances 46 États, Belarus Dernier État Européen Exécutions, Russie Moratoire Pas Abolition & Turquie Pressions Réintroduction Périodiques", composite_score: 27.90, execution_volume_severity_score: 28.0, legal_safeguard_absence_score: 30.0, wrongful_execution_risk_score: 28.0, abolition_resistance_score: 25.0, risk_level: "modéré", primary_pattern: "abolition_resistance", key_signals: ["Progrès significatif d'abolition en Europe — le Protocole 13 à la CEDH abolissant la peine de mort en toutes circonstances ratifié par 46 États membres du Conseil de l'Europe constitue le cadre régional d'abolition le plus avancé au monde, avec Belarus comme seule exception", "Résistance abolition (25.0/100) — la Biélorussie maintenant des exécutions secrètes et les pressions périodiques pour réintroduire la peine de mort en Turquie constituent les derniers obstacles à l'abolition universelle en Europe, région leader du mouvement abolitionniste mondial", "Conditionner toute perspective d'adhésion ou de partenariat avec la Biélorussie à l'abolition de la peine de mort et renforcer les pressions diplomatiques du Conseil de l'Europe pour maintenir le moratoire russe et turc conformément aux engagements OSCE"], estimated_death_penalty_index: 2.79, last_updated: "2026-06-20" },
    { id: "DP-008", name: "ONU/CIDH — Résolution Moratoire, Protocole 2 PIDCP & Mouvement Abolition", country: "Global", sector: "Assemblée Générale ONU Résolution Moratoire Universel 185 Voix 2022, Protocole Facultatif PIDCP 2 Abolition 90 États Parties, CIDH & Amnesty International Campagne Abolition Mondiale", composite_score: 4.40, execution_volume_severity_score: 4.0, legal_safeguard_absence_score: 3.0, wrongful_execution_risk_score: 5.0, abolition_resistance_score: 6.0, risk_level: "faible", primary_pattern: "abolition_resistance", key_signals: ["ONU/CIDH incarne le cadre normatif exemplaire vers l'abolition de la peine de mort — résolutions biennales de l'Assemblée Générale pour un moratoire universel adoptées avec une majorité croissante (185 voix en 2022) et Protocole 2 PIDCP créant une obligation conventionnelle d'abolition pour 90 États", "Protocole 2 PIDCP — oblige les États parties à prendre toutes les mesures nécessaires pour abolir la peine de mort et interdit toute dérogation même en état d'urgence, créant l'obligation internationale la plus contraignante en matière d'abolition de la peine capitale", "Universaliser la ratification du Protocole 2 PIDCP et soutenir les États en transition vers l'abolition via l'assistance technique du HCDH pour réformer leurs systèmes pénaux et mettre en œuvre des alternatives crédibles à la peine de mort conformément aux standards de l'ONU"], estimated_death_penalty_index: 0.44, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { execution_volume_severity: 2, legal_safeguard_absence: 3, wrongful_execution_risk: 1, abolition_resistance: 2 },
    top_risk_entities: ["Chine — 2 000+ Exécutions/An, Secret État & Organes Prisonniers", "Iran — 853 Exécutions 2023, Pendaisons Publiques & Minorités Ethniques", "Arabie Saoudite/Golfe — 196 Exécutions 2022, Décapitations Publiques & Travailleurs Migrants"],
    critical_alerts: ["Chine: execution volume severity", "Iran: execution volume severity", "Arabie Saoudite/Golfe: legal safeguard absence", "USA: wrongful execution risk"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "death_penalty",
    confidence_score: 0.87,
    data_sources: ["amnesty_international_death_sentences_executions_annual_report", "un_special_rapporteur_extrajudicial_executions_country_reports", "cornell_center_death_penalty_worldwide_database"],
    entities,
    avg_estimated_death_penalty_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
