import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[political-assassination-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Political Assassination Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/political-assassination-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Political Assassination Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Political Assassination Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "PA-001", name: "Russie/FSB-GRU — Novichok, Polonium & Éliminations Diaspora", country: "Europe de l'Est", sector: "Skripal Novichok 2018, Litvinenko Polonium 2006, Navalny Assassiné 2024, 14 Morts UK Suspects & GRU Opérations Europe", composite_score: 91.5, state_sponsored_assassination_score: 95.0, cross_border_targeting_score: 92.0, journalist_activist_elimination_score: 88.0, assassination_impunity_score: 90.0, risk_level: "critique", primary_pattern: "assassinat_etatique_transfrontalier", key_signals: ["Assassinat politique étatique critique de Russie/FSB-GRU — programme documenté d'éliminations ciblées d'opposants, journalistes et dissidents par des agents des services secrets d'État", "Crime international grave — les assassinats transfrontaliers commandités par un État violent la souveraineté des nations cibles et constituent des actes de terrorisme d'État au regard du droit international", "Culture de l'impunité létale — l'absence de responsabilité judiciaire des agents étatiques encourage l'escalade et normalise l'assassinat politique comme outil de gouvernance"], estimated_political_assassination_index: 9.15, last_updated: "2026-06-20" },
    { id: "PA-002", name: "Arabie Saoudite/MBS — Khashoggi, Consulat Istanbul & Opérations Tiger Squad", country: "MENA", sector: "Khashoggi Démembré Consulat 2018, Tiger Squad Opérations, 15 Agents Identifiés CIA & MBS Commanditaire ONU", composite_score: 85.75, state_sponsored_assassination_score: 88.0, cross_border_targeting_score: 82.0, journalist_activist_elimination_score: 85.0, assassination_impunity_score: 88.0, risk_level: "critique", primary_pattern: "elimination_journalistes_systematique", key_signals: ["Élimination systématique de journalistes d'Arabie Saoudite/MBS — ciblage délibéré de journalistes critiques du régime à l'intérieur comme à l'extérieur des frontières nationales", "Crime international grave — les assassinats transfrontaliers commandités par un État violent la souveraineté des nations cibles et constituent des actes de terrorisme d'État au regard du droit international", "Culture de l'impunité létale — l'absence de responsabilité judiciaire des agents étatiques encourage l'escalade et normalise l'assassinat politique comme outil de gouvernance"], estimated_political_assassination_index: 8.58, last_updated: "2026-06-20" },
    { id: "PA-003", name: "Iran/IRGC — Opérations Quds Force & Dissidents Europe", country: "MENA", sector: "Soleimani Réponse Planifiée, Dissidents Assassinés Allemagne/France/Danemark, Fatwa Rushdie & Réseau Proxy Assassins", composite_score: 83.6, state_sponsored_assassination_score: 85.0, cross_border_targeting_score: 80.0, journalist_activist_elimination_score: 82.0, assassination_impunity_score: 88.0, risk_level: "critique", primary_pattern: "terreur_diplomatique_assassinat", key_signals: ["Terreur diplomatique par assassinat d'Iran/IRGC — utilisation de proxies et agents dormants sur le territoire de nations étrangères pour éliminer des opposants, journalistes et militantes des droits humains", "Crime international grave — les assassinats transfrontaliers commandités par un État violent la souveraineté des nations cibles et constituent des actes de terrorisme d'État au regard du droit international", "Culture de l'impunité létale — l'absence de responsabilité judiciaire des agents étatiques encourage l'escalade et normalise l'assassinat politique comme outil de gouvernance"], estimated_political_assassination_index: 8.36, last_updated: "2026-06-20" },
    { id: "PA-004", name: "Chine/MSS — Opération Fox Hunt & Dissidents Rapatriés Force", country: "Asie", sector: "Operation Fox Hunt 2014+, 10 000 Fugitifs Ciblés, Stations Police Chinoises Europe & Taiwan Opposants Intimidés", composite_score: 81.9, state_sponsored_assassination_score: 80.0, cross_border_targeting_score: 82.0, journalist_activist_elimination_score: 82.0, assassination_impunity_score: 85.0, risk_level: "critique", primary_pattern: "liquidation_politique_active", key_signals: ["Liquidation politique active de Chine/MSS — programme d'élimination ou rapatriement forcé d'opposants et dissidents à l'étranger via des réseaux consulaires et agents clandestins", "Crime international grave — les assassinats transfrontaliers commandités par un État violent la souveraineté des nations cibles et constituent des actes de terrorisme d'État au regard du droit international", "Culture de l'impunité létale — l'absence de responsabilité judiciaire des agents étatiques encourage l'escalade et normalise l'assassinat politique comme outil de gouvernance"], estimated_political_assassination_index: 8.19, last_updated: "2026-06-20" },
    { id: "PA-005", name: "Turquie/MIT — Opérations Kurdes Europe & Gülenistes Ciblés", country: "MENA/Europe", sector: "MIT Opérations Kosovo/Azerbaïdjan, Journalistes Kurdes Assassinés Paris 2013, Gülenistes Enlevés 6 Pays & Erdoğan Cible Liste", composite_score: 56.0, state_sponsored_assassination_score: 55.0, cross_border_targeting_score: 58.0, journalist_activist_elimination_score: 52.0, assassination_impunity_score: 60.0, risk_level: "élevé", primary_pattern: "liquidation_politique_active", key_signals: ["Opérations d'élimination ciblée de Turquie/MIT — services de renseignement documentés conduisant des assassinats et enlèvements de militants kurdes et opposants gülenistes en Europe", "Répression transnationale documentée — intimidation, surveillance et menaces physiques contre la diaspora politique dans les pays d'accueil sans poursuites effectives des auteurs", "Risque d'escalade létale — la tolérance internationale des assassinats politiques d'État encourage l'extension de ces pratiques à de nouvelles catégories de cibles"], estimated_political_assassination_index: 5.6, last_updated: "2026-06-20" },
    { id: "PA-006", name: "Inde/Connexions — Goldy Brar & Journalistes Sikhs Ciblés", country: "Asie du Sud", sector: "Hardeep Singh Nijjar Assassiné Canada 2023, Gurpatwant Pannun Complot USA, Allégations RAW & Trudeau Accusation Formelle", composite_score: 51.75, state_sponsored_assassination_score: 50.0, cross_border_targeting_score: 45.0, journalist_activist_elimination_score: 55.0, assassination_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "liquidation_politique_active", key_signals: ["Complicité présumée d'État d'Inde — allégations documentées d'implication des services de renseignement dans des assassinats de militants sikhs au Canada et tentative aux États-Unis", "Répression transnationale documentée — intimidation, surveillance et menaces physiques contre la diaspora politique dans les pays d'accueil sans poursuites effectives des auteurs", "Risque d'escalade létale — la tolérance internationale des assassinats politiques d'État encourage l'extension de ces pratiques à de nouvelles catégories de cibles"], estimated_political_assassination_index: 5.18, last_updated: "2026-06-20" },
    { id: "PA-007", name: "Mexique/Cartels-État — Journalistes Assassinés Impunité 90%", country: "Amérique du Nord", sector: "15 Journalistes Tués 2022 Record, 90% Impunité Crimes Presse, Complicité Élus Locaux & CPJ Pays Dangereux Rang 2", composite_score: 29.65, state_sponsored_assassination_score: 28.0, cross_border_targeting_score: 25.0, journalist_activist_elimination_score: 32.0, assassination_impunity_score: 35.0, risk_level: "modéré", primary_pattern: "elimination_journalistes_systematique", key_signals: ["Violence contre les journalistes de Mexique — éliminations de journalistes d'investigation avec complicité partielle des autorités locales sans programme étatique d'assassinat formalisé", "Impunité structurelle — taux d'élucidation des crimes contre la presse inférieurs à 10%, décourageant le journalisme d'investigation et l'expression politique libre", "Zone grise État-criminalité — frontières floues entre criminalité organisée et éléments étatiques corrompus dans l'élimination de voix critiques du pouvoir"], estimated_political_assassination_index: 2.97, last_updated: "2026-06-20" },
    { id: "PA-008", name: "CPJ/RSF — Protection Journalistes & Droit International", country: "Global", sector: "CPJ 1981 Fondé, RSF Classement Liberté Presse 180 Pays, UN Plan Sécurité Journalistes 2012 & Réseau Alerte Urgence", composite_score: 4.45, state_sponsored_assassination_score: 5.0, cross_border_targeting_score: 4.0, journalist_activist_elimination_score: 3.0, assassination_impunity_score: 6.0, risk_level: "faible", primary_pattern: "protection_dissidents_exemplaire", key_signals: ["CPJ/RSF incarne la protection exemplaire des journalistes et dissidents — mécanismes d'alerte précoce, protection physique et plaidoyer juridique international contre les assassinats politiques", "Normes internationales de protection — résolutions ONU sur la sécurité des journalistes, arrêts CrEDH contre les États meurtriers et systèmes de relocalisation d'urgence opérationnels", "Modèle de protection à exporter — formation des États aux standards de protection des journalistes, aide judiciaire aux familles et pression diplomatique contre les gouvernements commanditaires"], estimated_political_assassination_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { assassinat_etatique_transfrontalier: 1, elimination_journalistes_systematique: 2, terreur_diplomatique_assassinat: 1, liquidation_politique_active: 3, protection_dissidents_exemplaire: 1 },
    top_risk_entities: ["Russie/FSB-GRU — Novichok, Polonium & Éliminations Diaspora", "Arabie Saoudite/MBS — Khashoggi, Consulat Istanbul & Opérations Tiger Squad", "Iran/IRGC — Opérations Quds Force & Dissidents Europe"],
    critical_alerts: ["Russie/FSB-GRU: assassinat étatique transfrontalier", "Arabie Saoudite/MBS: élimination journalistes systématique", "Iran/IRGC: terreur diplomatique assassinat", "Chine/MSS: liquidation politique active"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "political_assassination",
    confidence_score: 0.86,
    data_sources: ["committee_protect_journalists_database", "reporters_without_borders_tracker", "bellingcat_assassination_investigations"],
    entities,
    avg_estimated_political_assassination_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
