import { NextResponse } from "next/server";

const SWARM_API_URL = process.env.SWARM_API_URL;

const mockDeals = [
  {
    deal: {
      deal_id: "deal_001",
      deal_name: "Plateforme RevOps — TechScale SAS",
      company: "TechScale SAS",
      contact_name: "Maxime Lefebvre",
      stage: "negotiation",
      deal_value_eur: 95000,
      days_in_stage: 38,
      days_since_last_activity: 18,
      close_date_in_days: -5,
      contacts_count: 1,
      decision_maker_identified: false,
      champion_identified: true,
      executive_sponsor: false,
      last_email_response_days: 16,
      meetings_last_30d: 0,
      prospect_initiated_last_30d: 0,
      has_competitor: true,
      competitor_name: "Salesforce",
      competitor_strength: 72,
      budget_confirmed: false,
      price_objection: true,
      technical_hold: false,
      rep_notes_concern: true,
      next_step_defined: false,
    },
    deal_health: "critical",
    stall_score: 81.4,
    inactivity_risk: 92.0,
    stakeholder_gap: 85.0,
    competitive_risk: 72.0,
    budget_risk: 75.0,
    primary_strategy: "executive_sponsor",
    secondary_strategies: ["competitive_play", "urgency_create"],
    active_blockers: [
      "Aucune activité détectée depuis plus de 14 jours — deal inactif",
      "Aucune prochaine étape planifiée — deal sans momentum",
      "Contact unique dans le compte — risque élevé si le champion quitte",
      "Décideur final non identifié — impossible de progresser sans lui",
      "Budget non confirmé — risque d'abandon en fin de cycle",
      "Concurrent actif identifié dans le deal — risque de perte élevé",
      "Objection prix non résolue — bloquant confirmé",
      "Désalignement au niveau direction — pas de sponsorship exécutif",
    ],
    action_plan: [
      "Impliquer un exécutif côté vendeur pour créer un lien C-level direct",
      "Activer une stratégie de différenciation vs concurrent — ROI comparatif, proof of concept",
      "Créer un événement de clôture — offre limitée, deadline contractuelle, implémentation avant fin trimestre",
    ],
    days_to_act: 0,
    win_probability_adj: 12.5,
    deal_momentum: 5.0,
  },
  {
    deal: {
      deal_id: "deal_002",
      deal_name: "CRM Intelligence — InnoFinance",
      company: "InnoFinance SA",
      contact_name: "Claire Bouchard",
      stage: "proposal",
      deal_value_eur: 62000,
      days_in_stage: 22,
      days_since_last_activity: 8,
      close_date_in_days: 21,
      contacts_count: 3,
      decision_maker_identified: true,
      champion_identified: true,
      executive_sponsor: false,
      last_email_response_days: 6,
      meetings_last_30d: 2,
      prospect_initiated_last_30d: 1,
      has_competitor: true,
      competitor_name: "HubSpot",
      competitor_strength: 45,
      budget_confirmed: true,
      price_objection: false,
      technical_hold: true,
      rep_notes_concern: false,
      next_step_defined: true,
    },
    deal_health: "at_risk",
    stall_score: 41.8,
    inactivity_risk: 42.0,
    stakeholder_gap: 15.0,
    competitive_risk: 45.0,
    budget_risk: 25.0,
    primary_strategy: "competitive_play",
    secondary_strategies: ["value_proof", "champion_build"],
    active_blockers: [
      "Concurrent actif identifié dans le deal — risque de perte élevé",
      "Validation technique en attente — blocage IT/légal/sécurité",
      "Désalignement au niveau direction — pas de sponsorship exécutif",
    ],
    action_plan: [
      "Activer une stratégie de différenciation vs concurrent — ROI comparatif, proof of concept",
      "Présenter un business case chiffré ou une preuve de valeur (étude de cas, POC, ROI calculator)",
      "Identifier et activer un champion interne — trouver la personne qui bénéficie le plus du projet",
    ],
    days_to_act: 1,
    win_probability_adj: 44.0,
    deal_momentum: 62.0,
  },
  {
    deal: {
      deal_id: "deal_003",
      deal_name: "ERP Industriel — ManufactGroup",
      company: "ManufactGroup",
      contact_name: "Thomas Girard",
      stage: "closing",
      deal_value_eur: 148000,
      days_in_stage: 6,
      days_since_last_activity: 1,
      close_date_in_days: 7,
      contacts_count: 4,
      decision_maker_identified: true,
      champion_identified: true,
      executive_sponsor: true,
      last_email_response_days: 1,
      meetings_last_30d: 4,
      prospect_initiated_last_30d: 2,
      has_competitor: false,
      competitor_name: null,
      competitor_strength: 0,
      budget_confirmed: true,
      price_objection: false,
      technical_hold: false,
      rep_notes_concern: false,
      next_step_defined: true,
    },
    deal_health: "active",
    stall_score: 4.5,
    inactivity_risk: 4.0,
    stakeholder_gap: 0.0,
    competitive_risk: 0.0,
    budget_risk: 0.0,
    primary_strategy: "direct_close",
    secondary_strategies: [],
    active_blockers: [],
    action_plan: [
      "Demander directement la commande — trial close, proposition ferme avec deadline",
    ],
    days_to_act: 0,
    win_probability_adj: 87.5,
    deal_momentum: 96.0,
  },
  {
    deal: {
      deal_id: "deal_004",
      deal_name: "Suite Analytics — RetailChain",
      company: "RetailChain France",
      contact_name: "Sophie Roux",
      stage: "demo",
      deal_value_eur: 38000,
      days_in_stage: 35,
      days_since_last_activity: 21,
      close_date_in_days: 45,
      contacts_count: 2,
      decision_maker_identified: true,
      champion_identified: false,
      executive_sponsor: false,
      last_email_response_days: 20,
      meetings_last_30d: 0,
      prospect_initiated_last_30d: 0,
      has_competitor: false,
      competitor_name: null,
      competitor_strength: 0,
      budget_confirmed: false,
      price_objection: false,
      technical_hold: false,
      rep_notes_concern: false,
      next_step_defined: false,
    },
    deal_health: "stalled",
    stall_score: 65.3,
    inactivity_risk: 84.0,
    stakeholder_gap: 55.0,
    competitive_risk: 0.0,
    budget_risk: 40.0,
    primary_strategy: "champion_build",
    secondary_strategies: ["urgency_create", "requalify"],
    active_blockers: [
      "Aucune activité détectée depuis plus de 14 jours — deal inactif",
      "Aucune prochaine étape planifiée — deal sans momentum",
      "Engagement client en baisse — réponses rares, réunions annulées",
      "Cycle de vente anormalement long — signes de désengagement",
      "Aucun champion interne identifié — pas de défenseur du projet côté client",
      "Budget non confirmé — risque d'abandon en fin de cycle",
    ],
    action_plan: [
      "Identifier et activer un champion interne — trouver la personne qui bénéficie le plus du projet",
      "Créer un événement de clôture — offre limitée, deadline contractuelle, implémentation avant fin trimestre",
      "Requalifier le deal — vérifier BANT complet avant de continuer à investir",
    ],
    days_to_act: 0,
    win_probability_adj: 14.0,
    deal_momentum: 10.0,
  },
  {
    deal: {
      deal_id: "deal_005",
      deal_name: "Outreach SaaS — StartupAI",
      company: "StartupAI",
      contact_name: "Pierre Mercier",
      stage: "discovery",
      deal_value_eur: 28000,
      days_in_stage: 10,
      days_since_last_activity: 3,
      close_date_in_days: 60,
      contacts_count: 2,
      decision_maker_identified: true,
      champion_identified: true,
      executive_sponsor: false,
      last_email_response_days: 2,
      meetings_last_30d: 3,
      prospect_initiated_last_30d: 2,
      has_competitor: false,
      competitor_name: null,
      competitor_strength: 0,
      budget_confirmed: false,
      price_objection: false,
      technical_hold: false,
      rep_notes_concern: false,
      next_step_defined: true,
    },
    deal_health: "active",
    stall_score: 14.0,
    inactivity_risk: 12.0,
    stakeholder_gap: 0.0,
    competitive_risk: 0.0,
    budget_risk: 40.0,
    primary_strategy: "value_proof",
    secondary_strategies: ["requalify"],
    active_blockers: [
      "Budget non confirmé — risque d'abandon en fin de cycle",
    ],
    action_plan: [
      "Présenter un business case chiffré ou une preuve de valeur (étude de cas, POC, ROI calculator)",
      "Requalifier le deal — vérifier BANT complet avant de continuer à investir",
    ],
    days_to_act: 0,
    win_probability_adj: 27.5,
    deal_momentum: 88.0,
  },
  {
    deal: {
      deal_id: "deal_006",
      deal_name: "Gestion Pipeline — ConsultPro",
      company: "ConsultPro",
      contact_name: "Amélie Dumont",
      stage: "proposal",
      deal_value_eur: 22000,
      days_in_stage: 28,
      days_since_last_activity: 14,
      close_date_in_days: 10,
      contacts_count: 2,
      decision_maker_identified: false,
      champion_identified: false,
      executive_sponsor: false,
      last_email_response_days: 12,
      meetings_last_30d: 1,
      prospect_initiated_last_30d: 0,
      has_competitor: true,
      competitor_name: "Pipedrive",
      competitor_strength: 55,
      budget_confirmed: true,
      price_objection: true,
      technical_hold: false,
      rep_notes_concern: true,
      next_step_defined: false,
    },
    deal_health: "critical",
    stall_score: 70.25,
    inactivity_risk: 80.0,
    stakeholder_gap: 90.0,
    competitive_risk: 55.0,
    budget_risk: 35.0,
    primary_strategy: "executive_sponsor",
    secondary_strategies: ["champion_build", "competitive_play"],
    active_blockers: [
      "Aucune activité détectée depuis plus de 14 jours — deal inactif",
      "Aucune prochaine étape planifiée — deal sans momentum",
      "Décideur final non identifié — impossible de progresser sans lui",
      "Aucun champion interne identifié — pas de défenseur du projet côté client",
      "Concurrent actif identifié dans le deal — risque de perte élevé",
      "Objection prix non résolue — bloquant confirmé",
    ],
    action_plan: [
      "Impliquer un exécutif côté vendeur pour créer un lien C-level direct",
      "Identifier et activer un champion interne — trouver la personne qui bénéficie le plus du projet",
      "Activer une stratégie de différenciation vs concurrent — ROI comparatif, proof of concept",
    ],
    days_to_act: 0,
    win_probability_adj: 8.0,
    deal_momentum: 20.0,
  },
  {
    deal: {
      deal_id: "deal_007",
      deal_name: "BI Dashboard — LogisticsPro",
      company: "LogisticsPro",
      contact_name: "Nicolas Fabre",
      stage: "negotiation",
      deal_value_eur: 55000,
      days_in_stage: 14,
      days_since_last_activity: 5,
      close_date_in_days: 14,
      contacts_count: 3,
      decision_maker_identified: true,
      champion_identified: true,
      executive_sponsor: true,
      last_email_response_days: 4,
      meetings_last_30d: 2,
      prospect_initiated_last_30d: 1,
      has_competitor: false,
      competitor_name: null,
      competitor_strength: 0,
      budget_confirmed: true,
      price_objection: false,
      technical_hold: false,
      rep_notes_concern: false,
      next_step_defined: true,
    },
    deal_health: "active",
    stall_score: 2.75,
    inactivity_risk: 10.0,
    stakeholder_gap: 0.0,
    competitive_risk: 0.0,
    budget_risk: 0.0,
    primary_strategy: "direct_close",
    secondary_strategies: [],
    active_blockers: [],
    action_plan: [
      "Demander directement la commande — trial close, proposition ferme avec deadline",
    ],
    days_to_act: 0,
    win_probability_adj: 72.0,
    deal_momentum: 78.0,
  },
  {
    deal: {
      deal_id: "deal_008",
      deal_name: "Recrutement IA — HospitalGroup",
      company: "HospitalGroup",
      contact_name: "Isabelle Chevalier",
      stage: "discovery",
      deal_value_eur: 18000,
      days_in_stage: 45,
      days_since_last_activity: 32,
      close_date_in_days: -12,
      contacts_count: 1,
      decision_maker_identified: false,
      champion_identified: false,
      executive_sponsor: false,
      last_email_response_days: 30,
      meetings_last_30d: 0,
      prospect_initiated_last_30d: 0,
      has_competitor: false,
      competitor_name: null,
      competitor_strength: 0,
      budget_confirmed: false,
      price_objection: false,
      technical_hold: true,
      rep_notes_concern: true,
      next_step_defined: false,
    },
    deal_health: "critical",
    stall_score: 84.5,
    inactivity_risk: 100.0,
    stakeholder_gap: 90.0,
    competitive_risk: 0.0,
    budget_risk: 65.0,
    primary_strategy: "requalify",
    secondary_strategies: ["executive_sponsor", "champion_build"],
    active_blockers: [
      "Aucune activité détectée depuis plus de 14 jours — deal inactif",
      "Aucune prochaine étape planifiée — deal sans momentum",
      "Engagement client en baisse — réponses rares, réunions annulées",
      "Cycle de vente anormalement long — signes de désengagement",
      "Contact unique dans le compte — risque élevé si le champion quitte",
      "Décideur final non identifié — impossible de progresser sans lui",
      "Aucun champion interne identifié — pas de défenseur du projet côté client",
      "Budget non confirmé — risque d'abandon en fin de cycle",
      "Validation technique en attente — blocage IT/légal/sécurité",
    ],
    action_plan: [
      "Requalifier le deal — vérifier BANT complet avant de continuer à investir",
      "Impliquer un exécutif côté vendeur pour créer un lien C-level direct",
      "Identifier et activer un champion interne — trouver la personne qui bénéficie le plus du projet",
    ],
    days_to_act: 0,
    win_probability_adj: 1.5,
    deal_momentum: 0.0,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const health = searchParams.get("health");
  const strategy = searchParams.get("strategy");

  if (SWARM_API_URL) {
    try {
      const url = new URL(`${SWARM_API_URL}/api/deal-accelerator`);
      if (health) url.searchParams.set("health", health);
      if (strategy) url.searchParams.set("strategy", strategy);
      const res = await fetch(url.toString(), { cache: "no-store" });
      if (res.ok) return NextResponse.json(await res.json());
    } catch {}
  }

  let deals = [...mockDeals];
  if (health) deals = deals.filter((d) => d.deal_health === health);
  if (strategy) deals = deals.filter((d) => d.primary_strategy === strategy);

  const health_counts: Record<string, number> = { active: 0, at_risk: 0, stalled: 0, critical: 0, lost: 0 };
  const strategy_counts: Record<string, number> = {};
  let total_stall = 0, total_win = 0, pipeline_at_risk = 0;

  for (const d of mockDeals) {
    health_counts[d.deal_health] = (health_counts[d.deal_health] || 0) + 1;
    strategy_counts[d.primary_strategy] = (strategy_counts[d.primary_strategy] || 0) + 1;
    total_stall += d.stall_score;
    total_win += d.win_probability_adj;
    if (["at_risk", "stalled", "critical"].includes(d.deal_health)) {
      pipeline_at_risk += d.deal.deal_value_eur;
    }
  }

  const n = mockDeals.length;

  return NextResponse.json({
    deals,
    summary: {
      total: n,
      health_counts,
      strategy_counts,
      avg_stall_score: Math.round((total_stall / n) * 10) / 10,
      avg_win_probability: Math.round((total_win / n) * 10) / 10,
      pipeline_at_risk_eur: pipeline_at_risk,
      critical_count: health_counts.critical,
    },
  });
}
