import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[corporate-accountability-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Corporate Accountability Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/corporate-accountability-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Corporate Accountability Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Corporate Accountability Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "CA-001", name: "Apple/Samsung — Cobalt DRC, Travail Forcé Ouïghours & Chaînes Opaques", country: "Global/Tech", sector: "Apple Samsung Cobalt 40 000 Enfants Mines RDC Chaîne Approvisionnement, Travail Forcé Ouïghours Fournisseurs Xinjiang Documenté ASPI, Audit Indépendant Refusé & 0 Poursuites Pénales Dirigeants", composite_score: 88.95, supply_chain_abuse_score: 92.0, impunity_legal_gap_score: 90.0, environmental_harm_score: 85.0, greenwash_disclosure_fraud_score: 88.0, risk_level: "critique", primary_pattern: "supply_chain_abuse", key_signals: ["Violation de la responsabilité des entreprises documentée — Apple/Samsung avec score composite 88.95/100 révélant des chaînes d'approvisionnement en cobalt utilisant 40 000 enfants en RDC et du travail forcé ouïghour documenté par l'ASPI, violant les Principes Directeurs ONU sur les entreprises et les droits de l'homme", "Abus chaîne approvisionnement (92.0/100) — l'utilisation de cobalt extrait par des enfants en RDC et de composants produits par du travail forcé ouïghour dans les chaînes d'approvisionnement d'Apple et Samsung révèle la complicité de ces entreprises dans des violations graves des droits humains", "Appliquer la Directive UE sur la durabilité des entreprises (CSDD) et le UK Modern Slavery Act aux chaînes d'approvisionnement technologiques globales pour obliger Apple et Samsung à réaliser une diligence raisonnable contraignante et à réparer les violations documentées"], estimated_corporate_accountability_index: 8.90, last_updated: "2026-06-20" },
    { id: "CA-002", name: "Pétrole/Shell Nigeria — Pollution Delta Niger, Ogoni & Impunité 60 Ans", country: "Afrique/Energie", sector: "Shell Nigeria Delta Niger 60 Ans Pollution Pétrole, Ogoni Ken Saro-Wiwa Exécuté 1995, Déversements 550/An Documentés, Procès La Haye Partiels & Compensation 2023 15M Insuffisante Victimes", composite_score: 89.15, supply_chain_abuse_score: 88.0, impunity_legal_gap_score: 92.0, environmental_harm_score: 95.0, greenwash_disclosure_fraud_score: 80.0, risk_level: "critique", primary_pattern: "environmental_harm", key_signals: ["Violation de la responsabilité des entreprises documentée — Shell/Nigeria avec score composite 89.15/100 révélant 60 ans de pollution pétrolière du Delta du Niger avec 550 déversements/an documentés, l'exécution de Ken Saro-Wiwa et une impunité quasi-totale malgré le procès partiel aux Pays-Bas", "Préjudice environnemental (95.0/100) — la pollution pétrolière du Delta du Niger par Shell pendant 60 ans, causant une catastrophe écologique et sanitaire pour les Ogoni et autres communautés, constitue une violation de l'Article 12 PIDESC sur le droit à la santé et à un environnement sain", "Appliquer le principe de compétence universelle pour les crimes environnementaux d'entreprises opérant à l'étranger et renforcer le Traité contraignant sur les entreprises et droits de l'homme en cours de négociation à Genève depuis 2014 (Groupe de travail intergouvernemental ONU)"], estimated_corporate_accountability_index: 8.92, last_updated: "2026-06-20" },
    { id: "CA-003", name: "Fast Fashion — H&M/Zara Travailleurs Fantômes, Greenwash & Déchets Atacama", country: "Global/Mode", sector: "Fast Fashion H&M/Zara Fournisseurs Bangladesh/Vietnam Salaires Misère, Collections 'Durables' Greenwash Documenté FTC, Déchets Textiles Atacama Chili 40 000T/An & Modern Slavery Act Non-Respecté", composite_score: 86.40, supply_chain_abuse_score: 85.0, impunity_legal_gap_score: 82.0, environmental_harm_score: 88.0, greenwash_disclosure_fraud_score: 92.0, risk_level: "critique", primary_pattern: "greenwash_disclosure_fraud", key_signals: ["Violation de la responsabilité des entreprises documentée — Fast Fashion avec score composite 86.40/100 révélant l'exploitation de travailleurs dans les chaînes d'approvisionnement asiatiques, des pratiques de greenwashing documentées par la FTC et le déversement de 40 000 tonnes de déchets textiles dans le désert d'Atacama", "Greenwash/Fraude divulgation (92.0/100) — les allégations de durabilité d'H&M et Zara qualifiées de trompeuses par les autorités de protection des consommateurs européennes et le désert d'Atacama transformé en décharge textile mondiale constituent une fraude aux consommateurs et une violation des droits environnementaux", "Adopter une directive UE sur l'écoconception textile obligeant la transparence des chaînes d'approvisionnement et interdisant le greenwashing, et renforcer la responsabilité des donneurs d'ordre pour les violations de droits humains dans leurs chaînes de valeur textiles mondiales"], estimated_corporate_accountability_index: 8.64, last_updated: "2026-06-20" },
    { id: "CA-004", name: "Minières/Canada — 1 500 Conflits Communautaires, Guatemala & Impacts Extractifs", country: "Amérique Latine/Minières", sector: "Entreprises Minières Canadiennes 1 500 Conflits Communautaires Documentés MiningWatch, Guatemala Femmes Autochtones Violences Projets Miniers HudBay, Pérou Conflits Sociaux 70% Extractifs & Accord Ambition Net Insuffisant", composite_score: 85.75, supply_chain_abuse_score: 88.0, impunity_legal_gap_score: 85.0, environmental_harm_score: 90.0, greenwash_disclosure_fraud_score: 78.0, risk_level: "critique", primary_pattern: "environmental_harm", key_signals: ["Violation de la responsabilité des entreprises documentée — Minières/Canada avec score composite 85.75/100 révélant 1 500 conflits documentés entre entreprises minières canadiennes et communautés locales, avec des violations graves des droits humains documentées au Guatemala et au Pérou", "Préjudice environnemental (90.0/100) — les impacts environnementaux des projets miniers canadiens en Amérique latine, incluant contamination hydrique, déplacements forcés et violences contre défenseurs de l'environnement, constituent des violations des Principes Directeurs Ruggie sur les entreprises et droits de l'homme", "Adopter une loi canadienne contraignante de diligence raisonnable des entreprises à l'étranger (projet de loi S-211 insuffisant) et créer un mécanisme de recours effectif pour les communautés affectées par les entreprises canadiennes conformément aux Principes Directeurs ONU"], estimated_corporate_accountability_index: 8.58, last_updated: "2026-06-20" },
    { id: "CA-005", name: "Meta/Twitter — Algorithmes Haine Myanmar, Désinformation & Droits Numériques", country: "Global/Tech", sector: "Meta Algorithmes Amplification Haine Anti-Rohingya Myanmar Documenté Frances Haugen, Twitter/X Réduction Modération Contenu Haineux, Cambridge Analytica 87M Profils & RGPD Amendes Insuffisantes", composite_score: 54.25, supply_chain_abuse_score: 55.0, impunity_legal_gap_score: 55.0, environmental_harm_score: 52.0, greenwash_disclosure_fraud_score: 55.0, risk_level: "élevé", primary_pattern: "greenwash_disclosure_fraud", key_signals: ["Violation de la responsabilité des entreprises documentée — Meta avec score composite 54.25/100 révélant que ses algorithmes ont amplifié la haine anti-Rohingya au Myanmar contribuant au génocide documenté par les rapporteurs ONU, et que Cambridge Analytica a utilisé 87 millions de profils sans consentement", "Greenwash/Fraude divulgation (55.0/100) — Meta a dissimulé ses propres recherches internes (Frances Haugen) montrant les dommages de ses algorithmes sur les adolescents et les minorités persécutées, constituant une fraude aux investisseurs et aux régulateurs violant les obligations de transparence des entreprises", "Appliquer le Digital Services Act européen avec des amendes proportionnelles au chiffre d'affaires mondial pour obliger Meta à réaliser des évaluations de risques droits humains de ses algorithmes conformément aux Principes Directeurs ONU et à la jurisprudence de la CEDH sur la responsabilité des intermédiaires"], estimated_corporate_accountability_index: 5.43, last_updated: "2026-06-20" },
    { id: "CA-006", name: "Pharma/Sanofi — Brevets COVID, Accès Médicaments PED & Prix Insuline", country: "Global/Santé", sector: "Brevets COVID Bloqués Par Pfizer/Moderna TRIPS Malgré COVAX, Insuline USA 300$+/Mois Sanofi/Eli Lilly, Médicaments Orphelins Prix Inaccessibles & Lobbying Contre TRIPS Waiver Pays En Développement", composite_score: 52.50, supply_chain_abuse_score: 55.0, impunity_legal_gap_score: 58.0, environmental_harm_score: 42.0, greenwash_disclosure_fraud_score: 55.0, risk_level: "élevé", primary_pattern: "impunity_legal_gap", key_signals: ["Violation de la responsabilité des entreprises documentée — Pharma avec score composite 52.50/100 révélant le blocage des brevets de vaccins COVID par Pfizer/Moderna au détriment des pays en développement et les prix prohibitifs de l'insuline aux USA violant le droit à la santé (PIDESC Art 12)", "Impunité/Lacune légale (58.0/100) — l'absence de mécanisme contraignant permettant la mise sous licence obligatoire des brevets pharmaceutiques en situation d'urgence sanitaire, malgré l'Accord de Doha 2001, révèle une lacune légale systémique au détriment du droit à la santé des pays pauvres", "Adopter un traité international sur la propriété intellectuelle et la santé publique rendant automatique la mise sous licence obligatoire en situation d'urgence sanitaire et créer un mécanisme OMS de financement de la R&D pharmaceutique déconnecté des brevets conformément aux recommandations du CIPIH"], estimated_corporate_accountability_index: 5.25, last_updated: "2026-06-20" },
    { id: "CA-007", name: "UE/Directive CSDD — Diligence Raisonnable Adoptée 2024 & Lacunes Application", country: "Europe", sector: "UE Directive CSDD Adoptée Juin 2024 Diligence Raisonnable Entreprises, Périmètre Réduit PME Exemptées, Délais Transposition 2026-2029 & Sanctions Nationales Variables Non-Harmonisées", composite_score: 32.25, supply_chain_abuse_score: 28.0, impunity_legal_gap_score: 35.0, environmental_harm_score: 30.0, greenwash_disclosure_fraud_score: 38.0, risk_level: "modéré", primary_pattern: "impunity_legal_gap", key_signals: ["Progrès législatif significatif mais insuffisant — la Directive UE CSDD adoptée en juin 2024 impose une diligence raisonnable en matière de droits humains et d'environnement aux grandes entreprises européennes, mais son périmètre réduit et ses délais de transposition laissent des lacunes importantes", "Impunité/Lacune légale (35.0/100) — l'exemption des PME, les délais de transposition jusqu'en 2029 et la variabilité des sanctions nationales créent des inégalités de mise en œuvre réduisant l'effectivité de la CSDD pour protéger les communautés affectées par les chaînes d'approvisionnement européennes", "Renforcer la CSDD lors de sa révision en 2027 pour inclure les PME critiques, harmoniser les sanctions à 5% du chiffre d'affaires mondial et créer un mécanisme de recours civil facilitant l'accès à la justice pour les victimes dans les pays tiers conformément aux Principes Directeurs Ruggie"], estimated_corporate_accountability_index: 3.23, last_updated: "2026-06-20" },
    { id: "CA-008", name: "ONU/Principes Ruggie — PDNU Entreprises & Droits, Traité Contraignant & OCDE", country: "Global", sector: "Principes Directeurs ONU Entreprises Droits Homme 2011 Ruggie, Groupe Travail Intergouvernemental Traité Contraignant Depuis 2014, OCDE Points Contact Nationaux & ISO 26000 RSE Volontaire", composite_score: 4.45, supply_chain_abuse_score: 5.0, impunity_legal_gap_score: 4.0, environmental_harm_score: 3.0, greenwash_disclosure_fraud_score: 6.0, risk_level: "faible", primary_pattern: "impunity_legal_gap", key_signals: ["Principes Directeurs ONU/Ruggie incarne le cadre normatif sur la responsabilité des entreprises — les 31 Principes adoptés en 2011 créant le cadre 'Protéger, Respecter et Réparer' assignant des responsabilités aux États (protection), aux entreprises (respect) et aux deux (réparation)", "Principes Directeurs Ruggie Pilier 2 — reconnaît la responsabilité des entreprises de respecter les droits humains en réalisant une diligence raisonnable, même sans loi nationale contraignante, créant une norme de comportement responsable attendu de toutes les entreprises quel que soit leur lieu d'opération", "Finaliser les négociations du Traité contraignant sur les entreprises et droits de l'homme en cours depuis 2014 au Groupe de travail intergouvernemental ONU et adopter en droit interne des lois de diligence raisonnable inspirées de la CSDD européenne dans tous les pays du G20"], estimated_corporate_accountability_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { supply_chain_abuse: 1, impunity_legal_gap: 3, environmental_harm: 2, greenwash_disclosure_fraud: 2 },
    top_risk_entities: ["Pétrole/Shell Nigeria — Pollution Delta Niger, Ogoni & Impunité 60 Ans", "Apple/Samsung — Cobalt DRC, Travail Forcé Ouïghours & Chaînes Opaques", "Fast Fashion — H&M/Zara Travailleurs Fantômes, Greenwash & Déchets Atacama"],
    critical_alerts: ["Apple/Samsung: supply chain abuse", "Pétrole/Shell Nigeria: environmental harm", "Fast Fashion: greenwash disclosure fraud", "Minières/Canada: environmental harm"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "corporate_accountability",
    confidence_score: 0.84,
    data_sources: ["business_human_rights_resource_centre_corporate_abuse_database", "un_working_group_business_human_rights_country_reports", "corporate_accountability_lab_legal_cases_tracker"],
    entities,
    avg_estimated_corporate_accountability_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
