import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[journalist-murder-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Journalist Murder Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/journalist-murder-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Journalist Murder Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Journalist Murder Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "JM-001", name: "Mexique — 150+ Journalistes Tués 2000-24 & Cartels Impunité 98%", country: "Amérique du Nord", sector: "150+ Journalistes Tués Depuis 2000, Cartels Narco Meurtres, 98% Impunité CPJ & Veracruz/Sinaloa États Plus Dangereux Monde", composite_score: 90.75, journalist_killing_rate_score: 95.0, state_sponsored_targeting_score: 82.0, impunity_conviction_failure_score: 95.0, self_censorship_chilling_effect_score: 90.0, risk_level: "critique", primary_pattern: "assassinat_journalistes_systeme", key_signals: ["Assassinats systémiques de journalistes au Mexique — 150+ journalistes tués depuis 2000, 98% d'impunité selon le CPJ, avec Veracruz et Sinaloa figurant parmi les zones les plus mortelles au monde pour les médias", "Attaque contre la démocratie — tuer des journalistes détruit le rôle de vigie des médias, privant les sociétés de l'information nécessaire pour contrôler le pouvoir et résister à la corruption des cartels", "Activer la Résolution ONU A/RES/68/163 sur la sécurité des journalistes et saisir le Rapporteur Spécial RSF/CPJ pour enquête indépendante et pression diplomatique sur le Mexique"], estimated_journalist_murder_index: 9.08, last_updated: "2026-06-20" },
    { id: "JM-002", name: "Russie/Biélorussie — Anna Politkovskaïa, Novaya Gazeta & Répressions 2022+", country: "Europe de l'Est", sector: "Anna Politkovskaïa 2006, 20+ Journalistes Kremlin-Critiques Morts, Novaya Gazeta Fermée 2022 & Russie 164è RSF Index", composite_score: 89.25, journalist_killing_rate_score: 85.0, state_sponsored_targeting_score: 95.0, impunity_conviction_failure_score: 88.0, self_censorship_chilling_effect_score: 90.0, risk_level: "critique", primary_pattern: "ciblage_etatique_presse", key_signals: ["Ciblage étatique de la presse par Russie/Biélorussie — 20+ journalistes kremlin-critiques morts dans des circonstances suspectes, Novaya Gazeta fermée et Russie au 164e rang RSF malgré un contexte de guerre totale contre la presse indépendante", "Attaque contre la démocratie — l'élimination systématique des journalistes indépendants prive les citoyens russes et biélorusses de l'information nécessaire pour résister aux dérives autoritaires", "Activer la Résolution ONU A/RES/68/163 et saisir le Rapporteur Spécial RSF pour documentation de la répression systémique de la presse en Russie et en Biélorussie"], estimated_journalist_murder_index: 8.93, last_updated: "2026-06-20" },
    { id: "JM-003", name: "Syrie/MENA — 350+ Tués Conflit 2011-24 & Journalistes Otages ISIS", country: "MENA", sector: "350+ Journalistes Tués Syrie 2011-2024, James Foley Otage Décapité, Razan Zaitouneh Disparue & MENA Region Mondiale Plus Mortelle", composite_score: 87.1, journalist_killing_rate_score: 92.0, state_sponsored_targeting_score: 82.0, impunity_conviction_failure_score: 88.0, self_censorship_chilling_effect_score: 85.0, risk_level: "critique", primary_pattern: "assassinat_journalistes_systeme", key_signals: ["Assassinats systémiques de journalistes en Syrie/MENA — 350+ journalistes tués depuis 2011 faisant de la Syrie le pays le plus meurtrier au monde pour les médias, avec James Foley décapité et Razan Zaitouneh disparue", "Attaque contre la démocratie — l'élimination des journalistes en Syrie a permis aux atrocités des différentes factions de rester underdocumentées, facilitant l'impunité pour les crimes de guerre", "Activer la Résolution ONU A/RES/68/163 et renforcer les protections physiques des journalistes de guerre dans les zones de conflit via les protocoles de l'OCHA"], estimated_journalist_murder_index: 8.71, last_updated: "2026-06-20" },
    { id: "JM-004", name: "Philippines/Bangladesh — Maguindanao Massacre & Journalistes Locaux", country: "Asie du Sud-Est", sector: "Maguindanao Massacre 2009 32 Journalistes, Duterte War Media Hostilité, Bangladesh 18 Tués 2020-24 & Impunité Provinciale Totale", composite_score: 83.5, journalist_killing_rate_score: 82.0, state_sponsored_targeting_score: 80.0, impunity_conviction_failure_score: 90.0, self_censorship_chilling_effect_score: 82.0, risk_level: "critique", primary_pattern: "impunite_assassins_journalistes", key_signals: ["Impunité des assassins de journalistes aux Philippines/Bangladesh — Massacre de Maguindanao avec 32 journalistes tués en une seule journée en 2009 et procès de 14 ans illustrant l'impunité provinciale totale", "Attaque contre la démocratie — tuer des journalistes en zone rurale détruit la couverture des abus locaux, permettant aux politiques corrompus et aux seigneurs de guerre locaux d'opérer sans surveillance médiatique", "Activer la Résolution ONU A/RES/68/163 et demander à l'UNESCO de classer les Philippines et le Bangladesh en zone prioritaire de son Plan d'Action sur la Sécurité des Journalistes"], estimated_journalist_murder_index: 8.35, last_updated: "2026-06-20" },
    { id: "JM-005", name: "Afghanistan/Yémen — Taliban Expulsion Presse & Houthis Journalistes Prison", country: "MENA/Asie", sector: "Afghanistan RSF 152è Rang Journalistes Femmes Interdites, Yémen 26 Journalistes Tués, Houthis 5+ Exécutés & RSF Situation Critique", composite_score: 56.0, journalist_killing_rate_score: 55.0, state_sponsored_targeting_score: 58.0, impunity_conviction_failure_score: 52.0, self_censorship_chilling_effect_score: 60.0, risk_level: "élevé", primary_pattern: "autocensure_effet_dissuasif", key_signals: ["Autocensure et effet dissuasif en Afghanistan/Yémen — interdiction Taliban des journalistes femmes et exécutions Houthis de journalistes créant une autocensure quasi-totale dans les médias restants", "Attaque contre la démocratie — l'élimination de la presse indépendante en Afghanistan et au Yémen permet aux violations des droits humains de se dérouler sans témoin médiatique", "Activer la Résolution ONU A/RES/68/163 et saisir le Rapporteur Spécial RSF pour documentation et protection d'urgence des journalistes encore actifs sous les régimes Taliban et Houthis"], estimated_journalist_murder_index: 5.6, last_updated: "2026-06-20" },
    { id: "JM-006", name: "Inde/Brésil — Gauri Lankesh & Brésil Amazon Correspondants Tués", country: "Asie/Amérique du Sud", sector: "Gauri Lankesh Assassinée 2017, Dom Phillips Amazonie 2022, Brésil 9 Journalistes 2020-24 & Inde 161è RSF Modi Hostilité", composite_score: 54.85, journalist_killing_rate_score: 52.0, state_sponsored_targeting_score: 55.0, impunity_conviction_failure_score: 58.0, self_censorship_chilling_effect_score: 55.0, risk_level: "élevé", primary_pattern: "impunite_assassins_journalistes", key_signals: ["Impunité des assassins de journalistes en Inde/Brésil — assassinat de Gauri Lankesh en 2017 et de Dom Phillips en Amazonie en 2022 illustrant l'impunité persistante pour les meurtres de journalistes d'investigation", "Attaque contre la démocratie — les meurtres de journalistes enquêtant sur les crimes environnementaux et la montée de l'extrémisme privent les sociétés d'une couverture critique sur des sujets vitaux", "Activer la Résolution ONU A/RES/68/163 et saisir le Rapporteur Spécial RSF pour enquête indépendante sur l'impunité pour les meurtres de journalistes en Inde et au Brésil"], estimated_journalist_murder_index: 5.49, last_updated: "2026-06-20" },
    { id: "JM-007", name: "Turquie/Hongrie — Journalistes Emprisonnés & Pression Propriétaires Médias", country: "Europe", sector: "Turquie 150+ Journalistes Emprisonnés Record Mondial 2018, Hongrie Médias Oligarchie Orbán & Reporters Sans Frontières UE Alerte", composite_score: 31.65, journalist_killing_rate_score: 30.0, state_sponsored_targeting_score: 35.0, impunity_conviction_failure_score: 30.0, self_censorship_chilling_effect_score: 32.0, risk_level: "modéré", primary_pattern: "ciblage_etatique_presse", key_signals: ["Ciblage étatique de la presse par Turquie/Hongrie — 150+ journalistes emprisonnés en Turquie (record mondial en 2018) et médias hongrois contrôlés par l'oligarchie Orbán créant une presse de fait gouvernementale", "Attaque contre la démocratie — l'emprisonnement de journalistes et le contrôle oligarchique des médias dans des États membres de l'UE fragilisent l'espace démocratique européen et le principe de liberté de la presse", "Activer les mécanismes de l'UE sur l'état de droit et le Media Freedom Act pour protéger l'indépendance de la presse en Turquie et en Hongrie"], estimated_journalist_murder_index: 3.17, last_updated: "2026-06-20" },
    { id: "JM-008", name: "RSF/CPJ — Liberté Presse & Protection Journalistes", country: "Global", sector: "RSF Index 180 Pays Annuel, CPJ Impunity Index, ONU Plan d'Action Sécurité Journalistes & UNESCO Guillermo Cano Prix", composite_score: 4.45, journalist_killing_rate_score: 5.0, state_sponsored_targeting_score: 4.0, impunity_conviction_failure_score: 3.0, self_censorship_chilling_effect_score: 6.0, risk_level: "faible", primary_pattern: "autocensure_effet_dissuasif", key_signals: ["RSF/CPJ incarne la protection exemplaire de la liberté de presse — Index RSF dans 180 pays, base CPJ des journalistes tués et Plan d'Action ONU sur la sécurité des journalistes créant un cadre de responsabilité", "Résolution ONU A/RES/68/163 — condamnation des meurtres de journalistes et appel à mettre fin à l'impunité avec mécanismes de rapport régulier au Secrétaire Général de l'ONU", "Partager les méthodologies RSF/CPJ de documentation des violations et renforcer les programmes de protection physique des journalistes à risque dans les zones de conflit et les États autoritaires"], estimated_journalist_murder_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { assassinat_journalistes_systeme: 2, ciblage_etatique_presse: 2, impunite_assassins_journalistes: 2, autocensure_effet_dissuasif: 2 },
    top_risk_entities: ["Mexique — 150+ Journalistes Tués 2000-24 & Cartels Impunité 98%", "Russie/Biélorussie — Anna Politkovskaïa, Novaya Gazeta & Répressions 2022+", "Syrie/MENA — 350+ Tués Conflit 2011-24 & Journalistes Otages ISIS"],
    critical_alerts: ["Mexique: assassinat journalistes systémique", "Russie/Biélorussie: ciblage étatique presse", "Syrie/MENA: assassinat journalistes systémique", "Philippines/Bangladesh: impunité assassins journalistes"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "journalist_murder",
    confidence_score: 0.88,
    data_sources: ["cpj_journalist_killed_database", "rsf_press_freedom_index", "unesco_journalist_safety_indicators"],
    entities,
    avg_estimated_journalist_murder_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
