import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[drone-warfare-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Drone Warfare Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/drone-warfare-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Drone Warfare Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Drone Warfare Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "DW-001", name: "USA/CENTCOM — Programme Frappes Ciblées JSOC & CIA Drone Wars", country: "Amérique du Nord", sector: "10 000+ Frappes Pakistan/Yémen/Somalie/Syrie, 1700 Civils Tués Bureau of Investigative Journalism, Signature Strikes & Kill Lists NSC", composite_score: 88.15, targeted_killing_program_score: 95.0, autonomous_lethal_systems_score: 88.0, civilian_casualty_rate_score: 85.0, drone_proliferation_export_score: 82.0, risk_level: "critique", primary_pattern: "frappe_ciblee_extrajudiciaire", key_signals: ["Programme de frappes ciblées extrajudiciaires de USA/CENTCOM — assassinats sans procès de suspects hors zones de conflit actif, contournant le droit international humanitaire", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Saisir la CIJ pour demande d'avis consultatif sur les frappes ciblées hors zone de conflit armé"], estimated_drone_warfare_index: 8.82, last_updated: "2026-06-20" },
    { entity_id: "DW-002", name: "Israël/IAI — Harop Kamikaze, Heron & Technologie Frappe Gaza", country: "MENA", sector: "Harop SALA Exporté 20+ Pays, Frappes Gaza 2023-24 Drones Masse, Roof Knocking Doctrine & Industrie Défense N°1 Export Drone", composite_score: 88.9, targeted_killing_program_score: 88.0, autonomous_lethal_systems_score: 92.0, civilian_casualty_rate_score: 90.0, drone_proliferation_export_score: 85.0, risk_level: "critique", primary_pattern: "proliferation_autonome_lettale", key_signals: ["Prolifération de systèmes létaux autonomes d'Israël/IAI — développement et déploiement de drones tueurs sans supervision humaine significative sur la décision de mort", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Engager le CCW-GGE pour traité contraignant sur les systèmes d'armes létales autonomes (SALA)"], estimated_drone_warfare_index: 8.89, last_updated: "2026-06-20" },
    { entity_id: "DW-003", name: "Turquie/Bayraktar — TB2 Prolifération & Conflits Proxy Multiples", country: "MENA/Europe", sector: "TB2 Déployé Ukraine/Libye/Azerbaïdjan/Éthiopie, 30+ Pays Acheteurs, Conflits Civils Intensifiés & Technologie Exportée Sans Contrôle", composite_score: 82.5, targeted_killing_program_score: 82.0, autonomous_lethal_systems_score: 80.0, civilian_casualty_rate_score: 78.0, drone_proliferation_export_score: 92.0, risk_level: "critique", primary_pattern: "guerre_drone_asymetrique", key_signals: ["Guerre asymétrique par drones de Turquie/Bayraktar — acteurs non-étatiques ou États faibles utilisant des essaims de drones bon marché pour contrebalancer la supériorité militaire conventionnelle", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Renforcer les capacités de contre-drones des États cibles via coopération défensive internationale"], estimated_drone_warfare_index: 8.25, last_updated: "2026-06-20" },
    { entity_id: "DW-004", name: "Iran/IRGC — Shahed-136 & Essaims Houthis/Russie Ukraine", country: "MENA", sector: "Shahed-136 Fournis Russie 2000+, Houthis Armés Drones, Yémen Frappes Civiles & Production Industrielle Drones Kamikazes", composite_score: 84.0, targeted_killing_program_score: 85.0, autonomous_lethal_systems_score: 82.0, civilian_casualty_rate_score: 88.0, drone_proliferation_export_score: 80.0, risk_level: "critique", primary_pattern: "drone_suicide_masse", key_signals: ["Déploiement massif de drones kamikazes d'Iran/IRGC — utilisation de munitions rôdeuses autonomes contre des cibles civiles ou dans des zones peuplées sans discrimination", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Activer les mécanismes CCW pour interdire les munitions rôdeuses autonomes létales non discriminantes"], estimated_drone_warfare_index: 8.4, last_updated: "2026-06-20" },
    { entity_id: "DW-005", name: "Chine/CASC — Wing Loong & Exportation Autocrates", country: "Asie", sector: "Wing Loong II Exporté Émirats/Arabie Saoudite/Égypte, CH-4 Irak Civils Tués, Sans Conditions Droits Humains & Copie Predator", composite_score: 59.4, targeted_killing_program_score: 55.0, autonomous_lethal_systems_score: 62.0, civilian_casualty_rate_score: 52.0, drone_proliferation_export_score: 72.0, risk_level: "élevé", primary_pattern: "guerre_drone_asymetrique", key_signals: ["Guerre asymétrique par drones de Chine/CASC — exportation sans conditions de drones militaires à des régimes autoritaires intensifiant les conflits civils régionaux", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Renforcer les capacités de contre-drones des États cibles via coopération défensive internationale"], estimated_drone_warfare_index: 5.94, last_updated: "2026-06-20" },
    { entity_id: "DW-006", name: "Russie/Kronstadt — Orion & Drones Récupérés Iran", country: "Europe de l'Est", sector: "Orion Syrie Frappes Civiles, Shahed-136 Iran Massif Ukraine, Réseaux Civils Ciblés Infrastructure & Drones FPV 1ère Personne Masse", composite_score: 58.0, targeted_killing_program_score: 55.0, autonomous_lethal_systems_score: 58.0, civilian_casualty_rate_score: 68.0, drone_proliferation_export_score: 50.0, risk_level: "élevé", primary_pattern: "drone_suicide_masse", key_signals: ["Déploiement massif de drones kamikazes de Russie — utilisation de munitions rôdeuses iraniennes contre les infrastructures civiles ukrainiennes sans discrimination", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Activer les mécanismes CCW pour interdire les munitions rôdeuses autonomes létales non discriminantes"], estimated_drone_warfare_index: 5.8, last_updated: "2026-06-20" },
    { entity_id: "DW-007", name: "Émirats/UAE — Opérations Libye Yémen & Drones Wing Loong", country: "MENA", sector: "Wing Loong Libye Frappes Embargo Violé, Yémen Coalition Drones, ONU Rapport Violations & Technologie Transférée Sans Supervision", composite_score: 30.25, targeted_killing_program_score: 28.0, autonomous_lethal_systems_score: 25.0, civilian_casualty_rate_score: 32.0, drone_proliferation_export_score: 38.0, risk_level: "modéré", primary_pattern: "guerre_drone_asymetrique", key_signals: ["Utilisation problématique de drones d'Émirats/UAE — frappes en violation d'embargos ONU et transfert de technologie létale sans conditions de droits humains", "Victimes civiles documentées — les frappes de drones causent des pertes collatérales civiles systématiques insuffisamment investigées par des mécanismes de responsabilité indépendants", "Renforcer les capacités de contre-drones des États cibles via coopération défensive internationale"], estimated_drone_warfare_index: 3.03, last_updated: "2026-06-20" },
    { entity_id: "DW-008", name: "CICR/CCW-GGE — Droit Humanitaire & Régulation Drones", country: "Global", sector: "CICR Principes IHL Drones 2021, CCW-GGE SALA Négociations, 70+ États Soutien Traité & Mandat Humain Décision Létale", composite_score: 4.45, targeted_killing_program_score: 5.0, autonomous_lethal_systems_score: 4.0, civilian_casualty_rate_score: 3.0, drone_proliferation_export_score: 6.0, risk_level: "faible", primary_pattern: "transparence_drone_exemplaire", key_signals: ["CICR/CCW-GGE incarne la transparence exemplaire dans l'utilisation des drones militaires — supervision juridique, rapports publics et enquêtes indépendantes sur chaque frappe létale", "Normes IHL appliquées aux drones — principes de distinction, proportionnalité et précaution intégrés aux doctrines opérationnelles avec contrôle parlementaire effectif", "Partager les cadres réglementaires et protocoles de responsabilité comme modèles pour la gouvernance internationale des drones militaires"], estimated_drone_warfare_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { frappe_ciblee_extrajudiciaire: 1, proliferation_autonome_lettale: 1, drone_suicide_masse: 2, guerre_drone_asymetrique: 3, transparence_drone_exemplaire: 1 },
    top_risk_entities: ["Israël/IAI — Harop Kamikaze, Heron & Technologie Frappe Gaza", "USA/CENTCOM — Programme Frappes Ciblées JSOC & CIA Drone Wars", "Iran/IRGC — Shahed-136 & Essaims Houthis/Russie Ukraine"],
    critical_alerts: ["USA/CENTCOM: frappe ciblée extrajudiciaire", "Israël/IAI: prolifération systèmes létaux autonomes", "Iran/IRGC: drones kamikazes masse", "Turquie/Bayraktar: guerre drone asymétrique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "drone_warfare",
    confidence_score: 0.84,
    data_sources: ["bureau_investigative_journalism_drone_strikes", "airwars_civilian_casualty_monitor", "sipri_arms_transfer_database"],
    entities,
    avg_estimated_drone_warfare_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
