import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[arbitrary-detention-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Arbitrary Detention Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/arbitrary-detention-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Arbitrary Detention Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Arbitrary Detention Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "AD-001", name: "Chine/Xinjiang — 1M+ Ouïghours Internés Sans Jugement, VRC & Secret State", country: "Asie du Nord-Est", sector: "1M+ Ouïghours Internés Camps XJ Sans Charges/Jugement, Détention Administrative VRC, Disparitions Forcées Documentées & Accès HCDH Bloqué 2022", composite_score: 92.85, extrajudicial_detention_scale_score: 95.0, incommunicado_torture_score: 92.0, political_prisoner_profile_score: 95.0, due_process_denial_score: 88.0, risk_level: "critique", primary_pattern: "detention_extrajudiciaire_massive", key_signals: ["Détention arbitraire documentée — Chine/Xinjiang avec score composite 92.85/100 révélant des privations de liberté illégales violant l'Article 9 de la DUDH et les Articles 9/14 du PIDCP sur le droit à un procès équitable", "Détention extrajudiciaire (95.0/100) — l'internement de plus d'un million d'Ouïghours dans des camps sans charges ni jugement constitue la violation la plus massive du droit à la liberté et à la sûreté documentée au XXIème siècle", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 9.29, last_updated: "2026-06-20" },
    { id: "AD-002", name: "Arabie Saoudite/MBS — Ritz Carlton 2017, Défenseurs Droits & Loi Antiterrorisme", country: "MENA", sector: "MBS Ritz Carlton 200 Princes 2017, 200+ Défenseurs Droits Femmes/Journalistes Détenus, Loi Antiterrorisme Dissidence & Loujain al-Hathloul 1000 Jours Incommunicado", composite_score: 89.00, extrajudicial_detention_scale_score: 88.0, incommunicado_torture_score: 92.0, political_prisoner_profile_score: 88.0, due_process_denial_score: 88.0, risk_level: "critique", primary_pattern: "torture_incommunicado", key_signals: ["Détention arbitraire documentée — Arabie Saoudite/MBS avec score composite 89.00/100 révélant des privations de liberté illégales violant l'Article 9 de la DUDH et les Articles 9/14 du PIDCP sur le droit à un procès équitable", "Détention extrajudiciaire (88.0/100) — l'internement de centaines de défenseurs des droits humains, journalistes et militants politiques sans base légale conforme au PIDCP constitue une détention arbitraire systémique", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 8.90, last_updated: "2026-06-20" },
    { id: "AD-003", name: "Corée du Nord/Kwanliso — 150 000 Camps Politiques, Familles Entières & Songbun", country: "Asie du Nord-Est", sector: "RPDC 150 000 Prisonniers Politiques Camps Kwanliso, Système Songbun Punition Collective 3 Générations, Torture Systématique & COI ONU 2014 Rapport Crimes Humanité", composite_score: 90.85, extrajudicial_detention_scale_score: 92.0, incommunicado_torture_score: 95.0, political_prisoner_profile_score: 90.0, due_process_denial_score: 85.0, risk_level: "critique", primary_pattern: "torture_incommunicado", key_signals: ["Détention arbitraire documentée — Corée du Nord/Kwanliso avec score composite 90.85/100 révélant des privations de liberté illégales violant l'Article 9 de la DUDH et les Articles 9/14 du PIDCP sur le droit à un procès équitable", "Détention extrajudiciaire (92.0/100) — les 150 000 prisonniers politiques dans les camps Kwanliso avec punition collective des familles sur 3 générations selon le système Songbun constituent des crimes contre l'humanité selon la COI ONU 2014", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 9.09, last_updated: "2026-06-20" },
    { id: "AD-004", name: "Érythrée/Isaias — Détenus Indéfinis Métal Container, Djibhouti & Wall Street", country: "Afrique de l'Est", sector: "Érythrée Service National Indéfini Esclavage État, Prisonniers Politiques Containers Métal Désert, Journalistes G15 Disparus 2001 & Rapporteur Spécial ONU Accès Refusé", composite_score: 86.40, extrajudicial_detention_scale_score: 85.0, incommunicado_torture_score: 90.0, political_prisoner_profile_score: 88.0, due_process_denial_score: 82.0, risk_level: "critique", primary_pattern: "torture_incommunicado", key_signals: ["Détention arbitraire documentée — Érythrée/Isaias avec score composite 86.40/100 révélant des privations de liberté illégales violant l'Article 9 de la DUDH et les Articles 9/14 du PIDCP sur le droit à un procès équitable", "Détention extrajudiciaire (85.0/100) — la détention incommunicado dans des containers métalliques surchauffés dans le désert érythréen constitue une forme de torture et une violation aggravée de la prohibition de la détention arbitraire", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 8.64, last_updated: "2026-06-20" },
    { id: "AD-005", name: "Iran/Prisonniers Double Nationale — Otages Diplomatiques, 2+2 & JCPOA Levier", country: "MENA", sector: "Iran 2+2 Diplomatie Double Nationaux Iraniens-Occidentaux Détenus Otages Négociation, Siamak Namazi 7 Ans, Nazanin Zaghari-Ratcliffe & Evin Prison Conditions", composite_score: 56.90, extrajudicial_detention_scale_score: 55.0, incommunicado_torture_score: 58.0, political_prisoner_profile_score: 62.0, due_process_denial_score: 52.0, risk_level: "élevé", primary_pattern: "prisonnier_politique", key_signals: ["Détention arbitraire documentée — Iran/Double Nationaux avec score composite 56.90/100 révélant des prises d'otages diplomatiques déguisées en poursuites judiciaires violant le PIDCP et les normes sur la protection consulaire", "Détention extrajudiciaire (55.0/100) — la détention systématique de ressortissants biculturels comme monnaie d'échange diplomatique constitue une violation flagrante du PIDCP et du droit à un procès équitable", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 5.69, last_updated: "2026-06-20" },
    { id: "AD-006", name: "Turquie/Post-Coup 2016 — 150 000 Détenus, Journalistes & État Urgence", country: "MENA/Europe", sector: "Turquie Post-Coup 2016 150 000+ Arrestations, 77 000 Mis en Examen, 180+ Journalistes Détenus CPJ & État Urgence 2 Ans Décrets Purge Fonctionnaires", composite_score: 52.35, extrajudicial_detention_scale_score: 52.0, incommunicado_torture_score: 48.0, political_prisoner_profile_score: 55.0, due_process_denial_score: 55.0, risk_level: "élevé", primary_pattern: "prisonnier_politique", key_signals: ["Détention arbitraire documentée — Turquie/Post-Coup avec score composite 52.35/100 révélant des privations de liberté massives post-coup d'État 2016 dépassant les limites permises par la clause de dérogation de l'Article 4 du PIDCP", "Détention extrajudiciaire (52.0/100) — les 150 000+ arrestations et les décrets de purge de l'état d'urgence ayant ciblé des journalistes, juges et fonctionnaires constituent une utilisation abusive des pouvoirs d'urgence", "Saisir le Groupe de Travail ONU sur la Détention Arbitraire pour avis d'urgence et exiger l'accès des mécanismes de monitoring ONU aux lieux de détention conformément à l'OPCAT"], estimated_arbitrary_detention_index: 5.24, last_updated: "2026-06-20" },
    { id: "AD-007", name: "USA/Guantanamo — 780 Détenus Sans Charge, Torture CIA & Procès Militaires", country: "Amérique du Nord", sector: "USA Guantanamo 780 Détenus 2001-2024, 30 Restants Dont 16 Sans Charge, Rapport CIA Torture 2014 & Commissions Militaires Standard Inférieur Procès Équitable", composite_score: 29.40, extrajudicial_detention_scale_score: 28.0, incommunicado_torture_score: 35.0, political_prisoner_profile_score: 25.0, due_process_denial_score: 30.0, risk_level: "modéré", primary_pattern: "torture_incommunicado", key_signals: ["Détention arbitraire documentée — USA/Guantanamo avec score composite 29.40/100 révélant une détention indéfinie sans inculpation violant l'Article 9 du PIDCP et l'interdiction absolue de la torture (Convention ONU CAT)", "Détention extrajudiciaire (28.0/100) — les 16 détenus de Guantanamo restant sans charges après 20+ ans illustrent une violation persistante de l'interdiction de la détention arbitraire reconnue par la Cour Suprême US (Boumediene v. Bush)", "Fermer définitivement Guantanamo Bay conformément aux engagements de l'administration Biden et transférer les détenus restants vers des juridictions garantissant un procès équitable conforme aux standards PIDCP"], estimated_arbitrary_detention_index: 2.94, last_updated: "2026-06-20" },
    { id: "AD-008", name: "GTDA-OPCAT — Groupe Travail ONU Détention Arbitraire & Sous-Comité Prévention", country: "Global", sector: "ONU Groupe Travail Détention Arbitraire GTDA Avis Jurisprudence, OPCAT Sous-Comité Prévention Torture, Règles Nelson Mandela 2015 & PIDCP Article 9 Habeas Corpus", composite_score: 4.45, extrajudicial_detention_scale_score: 5.0, incommunicado_torture_score: 4.0, political_prisoner_profile_score: 3.0, due_process_denial_score: 6.0, risk_level: "faible", primary_pattern: "deni_process_equitable", key_signals: ["GTDA/OPCAT incarne le cadre exemplaire de protection contre la détention arbitraire — Groupe de Travail ONU et Sous-Comité de l'OPCAT créant un mécanisme de surveillance des lieux de détention et de jurisprudence internationale", "PIDCP Article 9 — interdit toute détention arbitraire et garantit le droit à l'habeas corpus (déférement immédiat devant un juge) ainsi que la réparation pour détention illégale", "Universaliser la ratification de l'OPCAT et renforcer les Mécanismes Nationaux de Prévention (MNP) pour inspections indépendantes des lieux de détention avec publication systématique des rapports"], estimated_arbitrary_detention_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { detention_extrajudiciaire_massive: 1, torture_incommunicado: 4, prisonnier_politique: 2, deni_process_equitable: 1 },
    top_risk_entities: ["Chine/Xinjiang — 1M+ Ouïghours Internés Sans Jugement, VRC & Secret State", "Corée du Nord/Kwanliso — 150 000 Camps Politiques, Familles Entières & Songbun", "Arabie Saoudite/MBS — Ritz Carlton 2017, Défenseurs Droits & Loi Antiterrorisme"],
    critical_alerts: ["Chine/Xinjiang: détention extrajudiciaire massive", "Corée du Nord/Kwanliso: torture incommunicado", "Arabie Saoudite/MBS: torture incommunicado", "Érythrée/Isaias: torture incommunicado"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "arbitrary_detention",
    confidence_score: 0.85,
    data_sources: ["un_working_group_arbitrary_detention_opinions", "amnesty_international_political_prisoners_database", "committee_to_protect_journalists_imprisoned_journalists"],
    entities,
    avg_estimated_arbitrary_detention_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
