import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[electoral-rights-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Electoral Rights Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/electoral-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Electoral Rights Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Electoral Rights Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "EL-001", name: "Biélorussie — Élections Volées Loukachenko 2020, 35 000 Arrestations & Tikhanovskaïa", country: "Europe de l'Est", sector: "Biélorussie Élections Présidentielles 2020 Fraudées OSCE, 35 000 Arrestations Post-Élections, Tikhanovskaïa Exilée, Manifestants Torturés & Loukachenko 87% Officiel Vs 20% Réel", composite_score: 92.35, voting_suppression_score: 92.0, election_fraud_manipulation_score: 95.0, opposition_persecution_score: 92.0, democratic_regression_score: 90.0, risk_level: "critique", primary_pattern: "election_fraud_manipulation", key_signals: ["Violation du droit à des élections libres documentée — Biélorussie avec score composite 92.35/100 révélant des élections présidentielles massivement fraudées en 2020 et 35 000 arrestations de manifestants pacifiques, violant l'Article 25 du PIDCP sur le droit de vote", "Fraude électorale (95.0/100) — les élections biélorusses de 2020 reconnues comme fraudées par l'OSCE avec des résultats officiels de 87% pour Loukachenko vs environ 20% réel constituent la violation la plus flagrante du droit à des élections libres en Europe depuis 1990", "Activer la procédure de l'OSCE/ODIHR pour investigation des violations électorales et exiger des élections libres en Biélorussie conformément aux engagements OSCE de 1990 sur la démocratisation et libérer immédiatement tous les prisonniers politiques"], estimated_electoral_rights_index: 9.24, last_updated: "2026-06-20" },
    { entity_id: "EL-002", name: "Russie — Navalny Tué, Opposition Interdite & Élections 87% Poutine 2024", country: "Europe de l'Est", sector: "Russie Élections 2024 Poutine 87% Sans Opposition Réelle, Navalny Assassiné Prison Février 2024, Candidats Opposition Refusés Enregistrement & 16 000+ Arrestations Anti-Guerre", composite_score: 91.35, voting_suppression_score: 90.0, election_fraud_manipulation_score: 92.0, opposition_persecution_score: 95.0, democratic_regression_score: 88.0, risk_level: "critique", primary_pattern: "opposition_persecution", key_signals: ["Violation du droit à des élections libres documentée — Russie avec score composite 91.35/100 révélant l'assassinat d'Alexeï Navalny en détention, l'interdiction de tous les candidats d'opposition sérieux et des élections 2024 donnant 87% à Poutine sans concurrence réelle", "Persécution opposition (95.0/100) — l'assassinat de Navalny, l'emprisonnement de milliers d'opposants et le refus d'enregistrement des candidats d'opposition constituent une élimination systématique de la compétition politique violant les Articles 19 et 25 du PIDCP", "Activer le Conseil des droits de l'homme de l'ONU pour investigation de l'assassinat de Navalny et exiger des élections libres en Russie conformément aux engagements OSCE et à l'Article 25 PIDCP sur le droit à des élections authentiques et périodiques"], estimated_electoral_rights_index: 9.14, last_updated: "2026-06-20" },
    { entity_id: "EL-003", name: "Venezuela — Maduro Fraude Juillet 2024, Machado Interdite & 2 000 Arrestations", country: "Amérique Latine", sector: "Venezuela Élections Juillet 2024 Résultats Falsifiés CNE Maduro, María Corina Machado Candidate Interdite, 2 000+ Arrestations Post-Élections & Carter Center/OSCE Résultats Non-Vérifiables", composite_score: 88.65, voting_suppression_score: 88.0, election_fraud_manipulation_score: 92.0, opposition_persecution_score: 85.0, democratic_regression_score: 90.0, risk_level: "critique", primary_pattern: "election_fraud_manipulation", key_signals: ["Violation du droit à des élections libres documentée — Venezuela avec score composite 88.65/100 révélant des élections présidentielles de juillet 2024 dont les résultats sont non-vérifiables, María Corina Machado interdite de candidature et 2 000+ opposants arrêtés", "Fraude électorale (92.0/100) — l'impossibilité de vérifier les résultats électoraux vénézuéliens de 2024 reconnue par le Carter Center et l'ONU, combinée à l'interdiction des candidats d'opposition, constituent des violations flagrantes de l'Article 25 PIDCP", "Activer l'OEA et la mission d'observation de l'OSCE pour enquête sur les résultats électoraux vénézuéliens et exiger la publication des procès-verbaux complets de bureau de vote conformément aux standards électoraux interaméricains"], estimated_electoral_rights_index: 8.87, last_updated: "2026-06-20" },
    { entity_id: "EL-004", name: "Iran — Conseil Gardiens Filtre 99%, Présidentielle 2024 40% Participation", country: "MENA", sector: "Iran Conseil Gardiens Exclut 99% Candidats Potentiels, Présidentielle 2024 Participation 40% Plus Bas Historique, Prisonniers Politiques Candidats & OSCE/ONU Pas Observateurs", composite_score: 87.00, voting_suppression_score: 85.0, election_fraud_manipulation_score: 88.0, opposition_persecution_score: 90.0, democratic_regression_score: 85.0, risk_level: "critique", primary_pattern: "opposition_persecution", key_signals: ["Violation du droit à des élections libres documentée — Iran avec score composite 87.00/100 révélant un système électoral où le Conseil des Gardiens exclut 99% des candidats potentiels, vidant les élections de tout contenu démocratique réel en violation de l'Article 25 PIDCP", "Persécution opposition (90.0/100) — le filtrage systématique des candidats par le Conseil des Gardiens iranien et l'absence d'observateurs indépendants révèlent un système électoral désigné à reproduire le pouvoir des religieux conservateurs en violation du droit à des élections libres", "Exiger de l'Iran la réforme du système de filtrage des candidatures par le Conseil des Gardiens et permettre l'accès d'observateurs électoraux indépendants de l'OSCE/ONU conformément aux Standards Internationaux pour les Élections"], estimated_electoral_rights_index: 8.70, last_updated: "2026-06-20" },
    { entity_id: "EL-005", name: "Hongrie — Gerrymandering Orbán, Médias Captifs & Démocratie Illibérale", country: "Europe", sector: "Hongrie Gerrymandering Orbán Avantage +15% Sièges Parlement, 80%+ Médias Contrôlés Oligarques Proches Fidesz, UE Article 7 Procédure & OSCE Élections 2022 Non-Pluralisme", composite_score: 56.60, voting_suppression_score: 52.0, election_fraud_manipulation_score: 62.0, opposition_persecution_score: 58.0, democratic_regression_score: 55.0, risk_level: "élevé", primary_pattern: "election_fraud_manipulation", key_signals: ["Violation du droit à des élections libres documentée — Hongrie avec score composite 56.60/100 révélant un gerrymandering donnant à Fidesz un avantage structurel de +15% de sièges et le contrôle de 80% des médias créant des conditions électorales non-pluralistes", "Fraude électorale (62.0/100) — le gerrymandering systématique des circonscriptions hongroises et le contrôle des médias par les proches d'Orbán créent des conditions électorales inégales que l'OSCE a documentées comme 'ne respectant pas les engagements de pluralisme et d'équité'", "Activer la procédure de l'Article 7 TUE contre la Hongrie pour atteintes aux valeurs démocratiques et exiger des réformes électorales conformes aux standards du Conseil de l'Europe sur les élections libres et équitables"], estimated_electoral_rights_index: 5.66, last_updated: "2026-06-20" },
    { entity_id: "EL-006", name: "USA — Voter Suppression Minorités, Gerrymandering & Jan 6 Démocratie", country: "Amérique du Nord", sector: "USA Voter ID Laws Afro-Américains/Latinos Disproportionnément Affectés, Gerrymandering Partisan SCOTUS, Jan 6 Insurrection & Supreme Court Affaiblissement Voting Rights Act 1965", composite_score: 52.30, voting_suppression_score: 58.0, election_fraud_manipulation_score: 50.0, opposition_persecution_score: 48.0, democratic_regression_score: 52.0, risk_level: "élevé", primary_pattern: "voting_suppression", key_signals: ["Violation du droit à des élections libres documentée — USA avec score composite 52.30/100 révélant une suppression du vote disproportionnellement ciblant les minorités raciales et l'affaiblissement judiciaire du Voting Rights Act de 1965 par la Cour Suprême", "Suppression vote (58.0/100) — les lois d'identification électorale impactant disproportionnellement les électeurs afro-américains et latinos et le gerrymandering partisan reconnu par la Cour Suprême révèlent des obstacles structurels au vote contraires à l'Article 25 PIDCP", "Restaurer les dispositions du Voting Rights Act de 1965 invalidées par la Cour Suprême et adopter une législation fédérale interdisant le gerrymandering partisan conformément aux recommandations du Comité des droits humains ONU sur les droits électoraux aux USA"], estimated_electoral_rights_index: 5.23, last_updated: "2026-06-20" },
    { entity_id: "EL-007", name: "Balkans/Serbie-Géorgie — Capture Médias, Élections Contestées & UE Critique", country: "Europe du Sud-Est", sector: "Serbie Médias Capturés Vučić SNS, Géorgie Loi 'Agent Étranger' ONG, Élections Décembre 2023 Serbie Irrégularités OSCE & Géorgie Élections 2024 Résultats Contestés Rues", composite_score: 30.95, voting_suppression_score: 32.0, election_fraud_manipulation_score: 35.0, opposition_persecution_score: 28.0, democratic_regression_score: 28.0, risk_level: "modéré", primary_pattern: "election_fraud_manipulation", key_signals: ["Défis électoraux documentés en Serbie et Géorgie — capture des médias et irrégularités électorales documentées par l'OSCE en Serbie et résultats des élections géorgiennes de 2024 contestés par des semaines de manifestations révèlent un recul démocratique dans les pays candidats à l'UE", "Fraude électorale (35.0/100) — les irrégularités électorales documentées par l'OSCE en Serbie en décembre 2023 et les résultats contestés des élections géorgiennes d'octobre 2024 révèlent des pratiques électorales non-conformes aux standards du Conseil de l'Europe", "Conditionner l'adhésion à l'UE de la Serbie et de la Géorgie au respect des standards électoraux du Conseil de l'Europe et à la liberté des médias, conformément aux critères de Copenhague sur la démocratie et l'État de droit"], estimated_electoral_rights_index: 3.10, last_updated: "2026-06-20" },
    { entity_id: "EL-008", name: "ONU/OSCE/NDI — PIDCP Art 25, Standards Électoraux & Observation Internationale", country: "Global", sector: "PIDCP Article 25 Droit Vote Élections Libres, OSCE Manuel Observation Élections, NDI National Democratic Institute, Carter Center & Standards Internationaux Élections IDEA", composite_score: 4.45, voting_suppression_score: 5.0, election_fraud_manipulation_score: 4.0, opposition_persecution_score: 3.0, democratic_regression_score: 6.0, risk_level: "faible", primary_pattern: "democratic_regression", key_signals: ["ONU/OSCE incarne le cadre normatif exemplaire des droits électoraux — Article 25 PIDCP garantissant le droit de vote dans des élections libres et l'Engagement de Copenhague OSCE 1990 créant des standards de pluralisme, compétition équitable et observation internationale", "PIDCP Article 25 — garantit à chaque citoyen le droit de voter et être élu dans de véritables élections périodiques au suffrage universel et égal, au scrutin secret assurant la libre expression de la volonté des électeurs, créant des obligations contraignantes pour les États parties", "Universaliser l'observation électorale indépendante via l'OSCE/ODIHR, l'OEA et l'UA et renforcer les mécanismes de sanctions ciblées contre les auteurs de fraudes électorales conformément aux résolutions du Conseil des droits de l'homme sur la participation démocratique"], estimated_electoral_rights_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { election_fraud_manipulation: 4, opposition_persecution: 2, voting_suppression: 1, democratic_regression: 1 },
    top_risk_entities: ["Biélorussie — Élections Volées Loukachenko 2020, 35 000 Arrestations & Tikhanovskaïa", "Russie — Navalny Tué, Opposition Interdite & Élections 87% Poutine 2024", "Venezuela — Maduro Fraude Juillet 2024, Machado Interdite & 2 000 Arrestations"],
    critical_alerts: ["Biélorussie: election fraud manipulation", "Russie: opposition persecution", "Venezuela: election fraud manipulation", "Iran: opposition persecution"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "electoral_rights",
    confidence_score: 0.85,
    data_sources: ["osce_odihr_election_observation_mission_reports", "freedom_house_freedom_in_the_world_electoral_democracy_database", "international_idea_global_state_democracy_annual_report"],
    entities,
    avg_estimated_electoral_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
