import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[nuclear-blackmail-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Nuclear Blackmail Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/nuclear-blackmail-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Nuclear Blackmail Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Nuclear Blackmail Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "NB-001", name: "Russie/Poutine — Doctrine Escalade Nucléaire & Menaces Ukraine 2022-24", country: "Europe de l'Est/Global", sector: "Doctrine Escalade Nucléaire Tatique Bielgorod, Menaces OTAN 500+ Déclarations, Exercices Iskander Nucléaires & Retrait New START", composite_score: 90.75, coercive_nuclear_threat_score: 95.0, proliferation_export_risk_score: 85.0, treaty_noncompliance_violation_score: 92.0, deterrence_destabilization_score: 90.0, risk_level: "critique", primary_pattern: "menace_nucleaire_coercitive", key_signals: ["Menaces nucléaires coercitives de Russie/Poutine — 500+ déclarations de menace nucléaire depuis 2022 inhibant la réponse internationale à l'agression ukrainienne via la 'doctrine d'escalade tactique'", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Activer en urgence le Conseil de Sécurité ONU et l'AIEA pour inspection contraignante, avec sanctions ciblées sur les programmes de modernisation nucléaire hors-traités"], estimated_nuclear_blackmail_index: 9.08, last_updated: "2026-06-20" },
    { id: "NB-002", name: "RPDC/Kim — Essais 2022-24, ICBM Hwasong & Réseau Prolifération Iran/Syrie", country: "Asie du Nord-Est", sector: "Hwasong-17 ICBM Testé, 70+ Tests Missiles 2022, Technologie Exportée Iran/Syrie & Constitution Amendée État Nucléaire Permanent", composite_score: 89.55, coercive_nuclear_threat_score: 88.0, proliferation_export_risk_score: 92.0, treaty_noncompliance_violation_score: 95.0, deterrence_destabilization_score: 82.0, risk_level: "critique", primary_pattern: "non_conformite_traites_nucleaires", key_signals: ["Non-conformité aux traités nucléaires de RPDC/Kim — retrait du TNP, 70+ tests missiles en 2022 et exportation de technologie nucléaire vers Iran/Syrie en violation des résolutions CS-ONU", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Activer en urgence le Conseil de Sécurité ONU et l'AIEA pour inspection contraignante, avec sanctions ciblées sur les programmes de modernisation nucléaire hors-traités"], estimated_nuclear_blackmail_index: 8.96, last_updated: "2026-06-20" },
    { id: "NB-003", name: "Pakistan/ISI — Prolifération Réseau AQ Khan & Doctrine First Strike Inde", country: "Asie du Sud", sector: "AQ Khan Réseau Libye/Iran/RPDC Technologie Centrifugeuse, Doctrine First Use Inde, 160+ Têtes & Commandement Civilo-Militaire Opaque", composite_score: 86.35, coercive_nuclear_threat_score: 82.0, proliferation_export_risk_score: 95.0, treaty_noncompliance_violation_score: 88.0, deterrence_destabilization_score: 80.0, risk_level: "critique", primary_pattern: "proliferation_exportation_clandestine", key_signals: ["Prolifération et export clandestins de Pakistan/ISI — réseau AQ Khan livrant la technologie de centrifugation à la Libye, l'Iran et la RPDC, la plus grande fuite de secrets nucléaires de l'histoire", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Activer en urgence le Conseil de Sécurité ONU et l'AIEA pour inspection contraignante, avec sanctions ciblées sur les réseaux de prolifération clandestins"], estimated_nuclear_blackmail_index: 8.64, last_updated: "2026-06-20" },
    { id: "NB-004", name: "Iran/SNSC — Enrichissement 60% & Menace Fermeture Détroit Hormuz", country: "MENA", sector: "Enrichissement 60% U235 Fordow Blindé, JCPOA Abandonné, 2000+ Centrifugeuses IR-6 & Capacité Militaire 12-Semaines Estimée AIEA", composite_score: 84.4, coercive_nuclear_threat_score: 85.0, proliferation_export_risk_score: 82.0, treaty_noncompliance_violation_score: 88.0, deterrence_destabilization_score: 82.0, risk_level: "critique", primary_pattern: "non_conformite_traites_nucleaires", key_signals: ["Non-conformité aux traités nucléaires d'Iran/SNSC — enrichissement à 60% U235 à Fordow blindé, abandon du JCPOA et 2000+ centrifugeuses IR-6 plaçant l'Iran à 12 semaines de la capacité militaire", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Activer en urgence le Conseil de Sécurité ONU et l'AIEA pour inspection contraignante, avec sanctions ciblées sur les programmes d'enrichissement hors-accords"], estimated_nuclear_blackmail_index: 8.44, last_updated: "2026-06-20" },
    { id: "NB-005", name: "Israël/Dimona — Ambiguïté Stratégique & Non-Signature TNP", country: "MENA", sector: "200+ Têtes Estimées Symington/Glenn Act Contournés, Dimona Non-Inspectée AIEA, Non-Signataire TNP & Doctrine Samson Option", composite_score: 57.5, coercive_nuclear_threat_score: 55.0, proliferation_export_risk_score: 58.0, treaty_noncompliance_violation_score: 62.0, deterrence_destabilization_score: 55.0, risk_level: "élevé", primary_pattern: "non_conformite_traites_nucleaires", key_signals: ["Non-conformité aux traités nucléaires d'Israël/Dimona — non-signature du TNP et refus d'inspections AIEA sur le réacteur de Dimona maintenant l'ambiguïté stratégique de la doctrine Samson Option", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Engager le dialogue sur la création d'une zone exempte d'armes nucléaires au Moyen-Orient et inviter Israël à rejoindre les mécanismes de transparence AIEA"], estimated_nuclear_blackmail_index: 5.75, last_updated: "2026-06-20" },
    { id: "NB-006", name: "Chine/PLA — Modernisation 1500 Têtes 2035 & Doctrine No-First-Use Ambiguë", country: "Asie", sector: "1500 Têtes Objectif Pentagon 2035, DF-41 MIRV, Silo Construction 300+ Unités & No-First-Use Doctrine Ambiguïté Stratégique Officielle", composite_score: 54.75, coercive_nuclear_threat_score: 52.0, proliferation_export_risk_score: 55.0, treaty_noncompliance_violation_score: 52.0, deterrence_destabilization_score: 62.0, risk_level: "élevé", primary_pattern: "destabilisation_dissuasion", key_signals: ["Déstabilisation de la dissuasion par Chine/PLA — objectif 1500 têtes nucléaires d'ici 2035 et construction de 300+ silos fragilisant la parité stratégique et rendant obsolètes les accords de limitation existants", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Engager les négociations multilatérales START+ incluant la Chine et activer les mécanismes de transparence des arsenaux nucléaires prévus par l'Article VI du TNP"], estimated_nuclear_blackmail_index: 5.48, last_updated: "2026-06-20" },
    { id: "NB-007", name: "USA/Russie — Expiration New START & Course Modernisation Bilatérale", country: "Global", sector: "New START Expiré 2026 Sans Successeur, B61-12 Déploiement Europe, Russie Retrait Ratification TICE & Modernisation Triades Parallèles", composite_score: 29.5, coercive_nuclear_threat_score: 28.0, proliferation_export_risk_score: 30.0, treaty_noncompliance_violation_score: 32.0, deterrence_destabilization_score: 28.0, risk_level: "modéré", primary_pattern: "non_conformite_traites_nucleaires", key_signals: ["Lacune traités nucléaires USA/Russie — expiration du New START sans successeur créant un vide juridique inédit depuis 1972 dans le contrôle bilatéral des arsenaux nucléaires stratégiques", "Fragilisation du régime TNP — chaque violation sans conséquence érode la crédibilité du Traité de Non-Prolifération et encourage d'autres États à développer leur propre arsenal", "Relancer en urgence les négociations bilatérales USA-Russie sur un successeur au New START et réintégrer le TICE dans les engagements multilatéraux"], estimated_nuclear_blackmail_index: 2.95, last_updated: "2026-06-20" },
    { id: "NB-008", name: "AIEA/TNP — Non-Prolifération & Désarmement Nucléaire Global", country: "Global", sector: "TNP 191 États Parties, AIEA 50+ Pays Inspections, TPNW 93 Signatures & Conférence Révision Désarmement Mécanismes", composite_score: 4.45, coercive_nuclear_threat_score: 5.0, proliferation_export_risk_score: 4.0, treaty_noncompliance_violation_score: 3.0, deterrence_destabilization_score: 6.0, risk_level: "faible", primary_pattern: "menace_nucleaire_coercitive", key_signals: ["AIEA/TNP incarne la non-prolifération exemplaire — 191 États parties respectant les engagements du TNP avec inspections AIEA régulières et engagement crédible vers le désarmement nucléaire", "Article VI du TNP — obligation contraignante pour les États nucléaires de négocier de bonne foi le désarmement général et complet créant un cadre légal pour l'élimination des arsenaux", "Partager les méthodologies de vérification AIEA et augmenter le financement du système de garanties nucléaires pour renforcer la crédibilité du régime de non-prolifération"], estimated_nuclear_blackmail_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { menace_nucleaire_coercitive: 2, proliferation_exportation_clandestine: 1, non_conformite_traites_nucleaires: 4, destabilisation_dissuasion: 1 },
    top_risk_entities: ["Russie/Poutine — Doctrine Escalade Nucléaire & Menaces Ukraine 2022-24", "RPDC/Kim — Essais 2022-24, ICBM Hwasong & Réseau Prolifération Iran/Syrie", "Pakistan/ISI — Prolifération Réseau AQ Khan & Doctrine First Strike Inde"],
    critical_alerts: ["Russie/Poutine: menace nucléaire coercitive", "RPDC/Kim: non conformité traités nucléaires", "Pakistan/ISI: prolifération exportation clandestine", "Iran/SNSC: non conformité traités nucléaires"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "nuclear_blackmail",
    confidence_score: 0.87,
    data_sources: ["sipri_nuclear_forces_yearbook", "iaea_safeguards_implementation_reports", "arms_control_association_nuclear_notebook"],
    entities,
    avg_estimated_nuclear_blackmail_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
