import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[gender-apartheid-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Gender Apartheid Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/gender-apartheid-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Gender Apartheid Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Gender Apartheid Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "GA-001", name: "Afghanistan — Taliban 80+ Interdictions Femmes & Éducation Bannie", country: "Asie", sector: "14M Femmes 80+ Interdictions Formelles, École Interdite 2021, Mahram Obligatoire & CSNU Résolution 2022", composite_score: 95.15, women_mobility_restriction_score: 95.0, women_education_denial_score: 98.0, women_legal_subjugation_score: 95.0, gender_violence_institutionalized_score: 92.0, risk_level: "critique", primary_pattern: "apartheid_genre_total", key_signals: ["Apartheid de genre de Afghanistan — 80+ interdictions formelles imposées aux 14 millions de femmes afghanes, éducation bannie au-delà de la 6ème et mobilité totalement contrôlée", "Crime contre l'humanité potentiel — la CPI enquête sur les traitements infligés aux femmes comme crime contre l'humanité sous le régime de persécution basée sur le genre", "Génération sacrifiée — l'interdiction de l'éducation crée une génération entière de femmes exclues de la vie économique, politique et sociale pour des décennies"], estimated_gender_apartheid_index: 9.52, last_updated: "2026-06-20" },
    { id: "GA-002", name: "Iran — Hijab Obligatoire, Police Mœurs & Révolution Mahsa Amini", country: "MENA", sector: "Gasht-e-Ershad Police Mœurs, Mahsa Amini 2022 Morte, 500+ Manifestants Tués & Discrimination Légale Systémique", composite_score: 84.25, women_mobility_restriction_score: 85.0, women_education_denial_score: 75.0, women_legal_subjugation_score: 82.0, gender_violence_institutionalized_score: 90.0, risk_level: "critique", primary_pattern: "violence_genre_institutionnalisee", key_signals: ["Apartheid de genre de Iran — police des mœurs, hijab obligatoire sous peine d'emprisonnement et 500+ militants tués lors du mouvement Femme Vie Liberté 2022", "Crime contre l'humanité potentiel — la CPI enquête sur les traitements infligés aux femmes comme crime contre l'humanité sous le régime de persécution basée sur le genre", "Génération sacrifiée — l'interdiction de l'éducation crée une génération entière de femmes exclues de la vie économique, politique et sociale pour des décennies"], estimated_gender_apartheid_index: 8.43, last_updated: "2026-06-20" },
    { id: "GA-003", name: "Arabie Saoudite — Réformes MBS & Tutelle Masculine Résiduelle", country: "MENA", sector: "Vision 2030 Réformes Partielles, Tutelle Masculine Persiste, Loujain Al-Hathloul Emprisonnée & Discrimination Légale", composite_score: 80.35, women_mobility_restriction_score: 80.0, women_education_denial_score: 72.0, women_legal_subjugation_score: 88.0, gender_violence_institutionalized_score: 75.0, risk_level: "critique", primary_pattern: "subjugation_legale_systemique", key_signals: ["Apartheid de genre de Arabie Saoudite — malgré les réformes MBS, la tutelle masculine subsiste et les militantes des droits des femmes comme Loujain Al-Hathloul restent emprisonnées", "Crime contre l'humanité potentiel — la CPI enquête sur les traitements infligés aux femmes comme crime contre l'humanité sous le régime de persécution basée sur le genre", "Génération sacrifiée — l'interdiction de l'éducation crée une génération entière de femmes exclues de la vie économique, politique et sociale pour des décennies"], estimated_gender_apartheid_index: 8.04, last_updated: "2026-06-20" },
    { id: "GA-004", name: "Soudan & Somalie — Charia, MGF & Violence Genre Institutionnalisée", country: "Afrique", sector: "MGF 88% Somalie 98% Djibouti, Mariage Enfant Légal 9-15 Ans, Al-Shabaab Contrôle 40% & RSF Viols Guerre", composite_score: 78.55, women_mobility_restriction_score: 78.0, women_education_denial_score: 80.0, women_legal_subjugation_score: 75.0, gender_violence_institutionalized_score: 82.0, risk_level: "critique", primary_pattern: "discrimination_genre_structurelle", key_signals: ["Apartheid de genre de Soudan & Somalie — MGF quasi-universelle, mariage enfant légalisé dès 9 ans et viols de guerre commis par les RSF documentés par l'ONU", "Crime contre l'humanité potentiel — la CPI enquête sur les traitements infligés aux femmes comme crime contre l'humanité sous le régime de persécution basée sur le genre", "Génération sacrifiée — l'interdiction de l'éducation crée une génération entière de femmes exclues de la vie économique, politique et sociale pour des décennies"], estimated_gender_apartheid_index: 7.86, last_updated: "2026-06-20" },
    { id: "GA-005", name: "Pakistan — Lois Blasphème, Mariage Enfant & Zones Tribales FATA", country: "Asie du Sud", sector: "Karo-Kari Assassinats Honneur 1000+/An, FATA Coutumes Anti-Femmes, Mariage Enfant 21% & Blasphème Persecution", composite_score: 56.4, women_mobility_restriction_score: 55.0, women_education_denial_score: 52.0, women_legal_subjugation_score: 58.0, gender_violence_institutionalized_score: 62.0, risk_level: "élevé", primary_pattern: "discrimination_genre_structurelle", key_signals: ["Oppression genrée structurelle de Pakistan — 1000+ assassinats d'honneur annuels, 21% de mariage enfant et zones tribales FATA hors normes constitutionnelles nationales", "Impunité institutionnalisée — les auteurs de violences de genre bénéficient d'une protection de facto via des systèmes juridiques discriminatoires ou défaillants", "Mouvement de résistance réprimé — les militantes des droits des femmes font face à des arrestations, harcèlement et violences d'État pour leur activisme"], estimated_gender_apartheid_index: 5.64, last_updated: "2026-06-20" },
    { id: "GA-006", name: "Nigéria & Sahel — Boko Haram, Chibok & Djihadisme Anti-Genre", country: "Afrique de l'Ouest", sector: "Boko Haram 276 Chibok Girls 2014, GSIM Anti-Éducation Filles, FGM 25% & Mariage Forcé Zones Rurales", composite_score: 52.95, women_mobility_restriction_score: 52.0, women_education_denial_score: 48.0, women_legal_subjugation_score: 55.0, gender_violence_institutionalized_score: 58.0, risk_level: "élevé", primary_pattern: "discrimination_genre_structurelle", key_signals: ["Oppression genrée structurelle de Nigéria & Sahel — Boko Haram a kidnappé 276 lycéennes de Chibok et les groupes djihadistes du Sahel ciblent systématiquement les écoles de filles", "Impunité institutionnalisée — les auteurs de violences de genre bénéficient d'une protection de facto via des systèmes juridiques discriminatoires ou défaillants", "Mouvement de résistance réprimé — les militantes des droits des femmes font face à des arrestations, harcèlement et violences d'État pour leur activisme"], estimated_gender_apartheid_index: 5.3, last_updated: "2026-06-20" },
    { id: "GA-007", name: "Inde — Dowry Deaths, Féminicides & Gaps Genre Persistants", country: "Asie du Sud", sector: "6000 Dowry Deaths/An, Infanticide Féminin, 27% Femmes Actives Économiquement & Écart Salarial 34%", composite_score: 29.65, women_mobility_restriction_score: 28.0, women_education_denial_score: 25.0, women_legal_subjugation_score: 32.0, gender_violence_institutionalized_score: 35.0, risk_level: "modéré", primary_pattern: "discrimination_genre_structurelle", key_signals: ["Inégalité persistante de Inde — 6000 dowry deaths annuelles, taux d'activité féminine parmi les plus bas du monde (27%) et écart salarial de 34%", "Gap d'application — les droits formellement reconnus restent inaccessibles faute de mécanismes d'enforcement et de recours judiciaires effectifs", "Risque de régression — pressions conservatrices ou religieuses pouvant compromettre les acquis de l'égalité de genre dans un contexte politique instable"], estimated_gender_apartheid_index: 2.97, last_updated: "2026-06-20" },
    { id: "GA-008", name: "Islande & Scandinavie — Parité Légale & Égalité Genre Exemplaire", country: "Europe du Nord", sector: "Islande 1ère Égalité Genre 15 Ans Consécutifs, Congé Parental Partagé, 48% Femmes Parlement & Pay Gap <5%", composite_score: 4.45, women_mobility_restriction_score: 5.0, women_education_denial_score: 4.0, women_legal_subjugation_score: 3.0, gender_violence_institutionalized_score: 6.0, risk_level: "faible", primary_pattern: "egalite_genre_exemplaire", key_signals: ["Islande & Scandinavie incarne l'égalité de genre avancée — parité légale effective, représentation politique significative et mécanismes de protection contre les violences", "Justice genrée exemplaire — tribunaux spécialisés sur les violences de genre, protection des lanceurs d'alerte et sanctions effectives contre les discriminateurs", "Modèle d'égalité à exporter — financement d'ONU Femmes, transfert de bonnes pratiques et coopération avec les mouvements féministes dans les États à haute oppression"], estimated_gender_apartheid_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { apartheid_genre_total: 1, violence_genre_institutionnalisee: 1, subjugation_legale_systemique: 1, discrimination_genre_structurelle: 4, egalite_genre_exemplaire: 1 },
    top_risk_entities: ["Afghanistan — Taliban 80+ Interdictions Femmes & Éducation Bannie", "Iran — Hijab Obligatoire, Police Mœurs & Révolution Mahsa Amini", "Arabie Saoudite — Réformes MBS & Tutelle Masculine Résiduelle"],
    critical_alerts: ["Afghanistan: apartheid genre total", "Iran: violence genre institutionnalisée", "Arabie Saoudite: subjugation légale systémique", "Soudan & Somalie: discrimination genre structurelle"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "gender_apartheid",
    confidence_score: 0.84,
    data_sources: ["un_women_progress_report", "freedom_house_gender_discrimination", "human_rights_watch_gender_apartheid"],
    entities,
    avg_estimated_gender_apartheid_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
