import { NextResponse } from "next/server";

const SWARM_API_URL = process.env.SWARM_API_URL;

const mockContacts = [
  {
    contact: {
      contact_id: "cnt_001",
      full_name: "Maxime Lefebvre",
      title: "Directeur Commercial",
      company: "TechScale SAS",
      industry: "SaaS B2B",
      company_size: "51-200",
      linkedin_connections: 1240,
      website_visits_30d: 3,
      emails_opened_30d: 2,
      content_downloads: 1,
      event_attendances: 1,
      has_direct_phone: true,
      has_linkedin: true,
      has_personal_email: false,
      crm_notes_count: 4,
      previous_interactions: 2,
      triggers: ["job_change", "hiring"],
      trigger_recency_days: 3,
      is_decision_maker: true,
      budget_authority: true,
      pain_score: 82,
      icp_score: 91,
      preferred_channel: "linkedin",
      timezone_offset: 1,
    },
    personalization_level: "deep",
    recommended_channel: "linkedin",
    personalization_score: 87.4,
    profile_richness_score: 82.0,
    engagement_score: 72.5,
    timing_score: 91.0,
    channel_fit_score: 100.0,
    primary_angle: "Féliciter pour la prise de poste et proposer un accompagnement adapté aux 90 premiers jours",
    secondary_angles: [
      "Adresser directement le pain point identifié avec une étude de cas similaire",
      "Mentionner un client concurrent ou pair pour créer un effet social proof",
    ],
    opening_hook: "Suite à votre récente prise de poste en tant que Directeur Commercial…",
    call_to_action: "Proposer un appel de 20 min avec agenda personnalisé et étude de cas préparée",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Maxime",
      "Titre: Directeur Commercial",
      "Entreprise: TechScale SAS",
      "Secteur: SaaS B2B",
      "Déclencheur: job change",
      "Pain score: 82/100",
      "Contexte CRM: 4 note(s)",
      "Historique: 2 interaction(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 88.5,
  },
  {
    contact: {
      contact_id: "cnt_002",
      full_name: "Claire Bouchard",
      title: "VP Marketing",
      company: "InnoFinance SA",
      industry: "Fintech",
      company_size: "201-500",
      linkedin_connections: 3200,
      website_visits_30d: 5,
      emails_opened_30d: 0,
      content_downloads: 2,
      event_attendances: 0,
      has_direct_phone: false,
      has_linkedin: true,
      has_personal_email: true,
      crm_notes_count: 2,
      previous_interactions: 0,
      triggers: ["funding", "expansion"],
      trigger_recency_days: 7,
      is_decision_maker: true,
      budget_authority: false,
      pain_score: 65,
      icp_score: 78,
      preferred_channel: "linkedin",
      timezone_offset: 1,
    },
    personalization_level: "strong",
    recommended_channel: "linkedin",
    personalization_score: 70.2,
    profile_richness_score: 61.8,
    engagement_score: 70.0,
    timing_score: 80.0,
    channel_fit_score: 90.0,
    primary_angle: "Capitaliser sur la levée de fonds — aligner la proposition sur les objectifs de croissance accélérée",
    secondary_angles: [
      "Adresser directement le pain point identifié avec une étude de cas similaire",
      "Mentionner un client concurrent ou pair pour créer un effet social proof",
    ],
    opening_hook: "Félicitations pour la levée de votre dernière levée — c'est une étape clé…",
    call_to_action: "Proposer un appel découverte de 15 min avec une question d'ouverture ciblée",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Claire",
      "Titre: VP Marketing",
      "Entreprise: InnoFinance SA",
      "Secteur: Fintech",
      "Déclencheur: funding",
      "Pain score: 65/100",
      "Contexte CRM: 2 note(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 74.8,
  },
  {
    contact: {
      contact_id: "cnt_003",
      full_name: "Thomas Girard",
      title: "DSI",
      company: "ManufactGroup",
      industry: "Industrie",
      company_size: "1000+",
      linkedin_connections: 680,
      website_visits_30d: 2,
      emails_opened_30d: 1,
      content_downloads: 0,
      event_attendances: 2,
      has_direct_phone: true,
      has_linkedin: true,
      has_personal_email: false,
      crm_notes_count: 6,
      previous_interactions: 3,
      triggers: ["event_attended", "content_published"],
      trigger_recency_days: 14,
      is_decision_maker: true,
      budget_authority: true,
      pain_score: 70,
      icp_score: 85,
      preferred_channel: null,
      timezone_offset: 1,
    },
    personalization_level: "strong",
    recommended_channel: "phone",
    personalization_score: 72.8,
    profile_richness_score: 88.5,
    engagement_score: 47.5,
    timing_score: 71.0,
    channel_fit_score: 90.0,
    primary_angle: "Faire référence à l'événement commun pour créer un point de contact chaud",
    secondary_angles: [
      "Adresser directement le pain point identifié avec une étude de cas similaire",
      "Mentionner un client concurrent ou pair pour créer un effet social proof",
    ],
    opening_hook: "On s'est croisés lors de l'événement récent — j'aurais voulu échanger plus longtemps…",
    call_to_action: "Proposer un appel découverte de 15 min avec une question d'ouverture ciblée",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Thomas",
      "Titre: DSI",
      "Entreprise: ManufactGroup",
      "Secteur: Industrie",
      "Déclencheur: event attended",
      "Pain score: 70/100",
      "Contexte CRM: 6 note(s)",
      "Historique: 3 interaction(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 72.5,
  },
  {
    contact: {
      contact_id: "cnt_004",
      full_name: "Amélie Dumont",
      title: "Responsable RH",
      company: "ConsultPro",
      industry: "Conseil",
      company_size: "11-50",
      linkedin_connections: 420,
      website_visits_30d: 0,
      emails_opened_30d: 0,
      content_downloads: 0,
      event_attendances: 0,
      has_direct_phone: false,
      has_linkedin: true,
      has_personal_email: false,
      crm_notes_count: 0,
      previous_interactions: 0,
      triggers: [],
      trigger_recency_days: 90,
      is_decision_maker: false,
      budget_authority: false,
      pain_score: 30,
      icp_score: 45,
      preferred_channel: null,
      timezone_offset: 1,
    },
    personalization_level: "generic",
    recommended_channel: "linkedin",
    personalization_score: 18.0,
    profile_richness_score: 19.5,
    engagement_score: 0.0,
    timing_score: 23.0,
    channel_fit_score: 65.0,
    primary_angle: "Adresser directement le pain point identifié avec une étude de cas similaire",
    secondary_angles: [],
    opening_hook: "Je vous contacte car votre profil correspond exactement à nos clients qui…",
    call_to_action: "Envoyer un email template court avec lien vers ressource générique",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Amélie",
      "Titre: Responsable RH",
      "Entreprise: ConsultPro",
      "Secteur: Conseil",
    ],
    do_not_contact: false,
    outreach_urgency: 18.5,
  },
  {
    contact: {
      contact_id: "cnt_005",
      full_name: "Pierre Mercier",
      title: "CEO",
      company: "StartupAI",
      industry: "Intelligence Artificielle",
      company_size: "11-50",
      linkedin_connections: 5800,
      website_visits_30d: 4,
      emails_opened_30d: 3,
      content_downloads: 2,
      event_attendances: 1,
      has_direct_phone: true,
      has_linkedin: true,
      has_personal_email: true,
      crm_notes_count: 8,
      previous_interactions: 5,
      triggers: ["hiring", "product_launch", "award"],
      trigger_recency_days: 0,
      is_decision_maker: true,
      budget_authority: true,
      pain_score: 88,
      icp_score: 95,
      preferred_channel: "email",
      timezone_offset: 1,
    },
    personalization_level: "deep",
    recommended_channel: "email",
    personalization_score: 94.2,
    profile_richness_score: 100.0,
    engagement_score: 100.0,
    timing_score: 100.0,
    channel_fit_score: 100.0,
    primary_angle: "Aborder le défi de scale commercial lié aux recrutements actifs",
    secondary_angles: [
      "Adresser directement le pain point identifié avec une étude de cas similaire",
      "Mentionner un client concurrent ou pair pour créer un effet social proof",
    ],
    opening_hook: "J'ai vu que StartupAI recrute activement — vous scalez la force commerciale…",
    call_to_action: "Proposer un appel de 20 min avec agenda personnalisé et étude de cas préparée",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Pierre",
      "Titre: CEO",
      "Entreprise: StartupAI",
      "Secteur: Intelligence Artificielle",
      "Déclencheur: hiring",
      "Pain score: 88/100",
      "Contexte CRM: 8 note(s)",
      "Historique: 5 interaction(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 96.8,
  },
  {
    contact: {
      contact_id: "cnt_006",
      full_name: "Sophie Roux",
      title: "DAF",
      company: "RetailChain France",
      industry: "Distribution",
      company_size: "501-1000",
      linkedin_connections: 890,
      website_visits_30d: 1,
      emails_opened_30d: 2,
      content_downloads: 1,
      event_attendances: 0,
      has_direct_phone: true,
      has_linkedin: true,
      has_personal_email: false,
      crm_notes_count: 3,
      previous_interactions: 1,
      triggers: ["email_opened"],
      trigger_recency_days: 2,
      is_decision_maker: true,
      budget_authority: true,
      pain_score: 58,
      icp_score: 72,
      preferred_channel: null,
      timezone_offset: 1,
    },
    personalization_level: "moderate",
    recommended_channel: "phone",
    personalization_score: 60.5,
    profile_richness_score: 68.6,
    engagement_score: 36.0,
    timing_score: 82.0,
    channel_fit_score: 90.0,
    primary_angle: "Relance ciblée — le prospect a ouvert un email précédent sans répondre",
    secondary_angles: [],
    opening_hook: "Je reviens vers vous suite à mon message précédent…",
    call_to_action: "Envoyer un contenu pertinent en pièce jointe et proposer un échange de 15 min",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Sophie",
      "Titre: DAF",
      "Entreprise: RetailChain France",
      "Secteur: Distribution",
      "Déclencheur: email opened",
      "Contexte CRM: 3 note(s)",
      "Historique: 1 interaction(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 62.4,
  },
  {
    contact: {
      contact_id: "cnt_007",
      full_name: "Nicolas Fabre",
      title: "Directeur des Opérations",
      company: "LogisticsPro",
      industry: "Logistique",
      company_size: "201-500",
      linkedin_connections: 340,
      website_visits_30d: 0,
      emails_opened_30d: 0,
      content_downloads: 0,
      event_attendances: 1,
      has_direct_phone: false,
      has_linkedin: true,
      has_personal_email: false,
      crm_notes_count: 1,
      previous_interactions: 1,
      triggers: ["content_published"],
      trigger_recency_days: 21,
      is_decision_maker: false,
      budget_authority: false,
      pain_score: 45,
      icp_score: 60,
      preferred_channel: "email",
      timezone_offset: 1,
    },
    personalization_level: "basic",
    recommended_channel: "email",
    personalization_score: 38.0,
    profile_richness_score: 28.5,
    engagement_score: 7.5,
    timing_score: 62.0,
    channel_fit_score: 70.0,
    primary_angle: "Rebondir sur le contenu publié pour montrer un alignement de vision",
    secondary_angles: [],
    opening_hook: "Votre post sur votre dernier article a vraiment résonné — je partage cette vision…",
    call_to_action: "Proposer une démo ou un lien calendrier direct",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Nicolas",
      "Titre: Directeur des Opérations",
      "Entreprise: LogisticsPro",
      "Secteur: Logistique",
      "Déclencheur: content published",
      "Contexte CRM: 1 note(s)",
      "Historique: 1 interaction(s)",
    ],
    do_not_contact: false,
    outreach_urgency: 37.8,
  },
  {
    contact: {
      contact_id: "cnt_008",
      full_name: "Isabelle Chevalier",
      title: "Responsable Achats",
      company: "HospitalGroup",
      industry: "Santé",
      company_size: "1000+",
      linkedin_connections: 210,
      website_visits_30d: 0,
      emails_opened_30d: 0,
      content_downloads: 0,
      event_attendances: 0,
      has_direct_phone: false,
      has_linkedin: false,
      has_personal_email: false,
      crm_notes_count: 0,
      previous_interactions: 0,
      triggers: [],
      trigger_recency_days: 180,
      is_decision_maker: false,
      budget_authority: false,
      pain_score: 20,
      icp_score: 35,
      preferred_channel: null,
      timezone_offset: 1,
    },
    personalization_level: "generic",
    recommended_channel: "multi",
    personalization_score: 10.5,
    profile_richness_score: 3.5,
    engagement_score: 0.0,
    timing_score: 23.0,
    channel_fit_score: 60.0,
    primary_angle: "Je vous contacte car votre profil correspond exactement à nos clients qui…",
    secondary_angles: [],
    opening_hook: "Je vous contacte car votre profil correspond exactement à nos clients qui…",
    call_to_action: "Envoyer un email template court avec lien vers ressource générique",
    best_send_time: "Mardi 09h00 ou Jeudi 14h00",
    personalization_tokens: [
      "Prénom: Isabelle",
      "Titre: Responsable Achats",
      "Entreprise: HospitalGroup",
      "Secteur: Santé",
    ],
    do_not_contact: false,
    outreach_urgency: 10.5,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const level = searchParams.get("level");
  const channel = searchParams.get("channel");

  if (SWARM_API_URL) {
    try {
      const url = new URL(`${SWARM_API_URL}/api/contact-personalizer`);
      if (level) url.searchParams.set("level", level);
      if (channel) url.searchParams.set("channel", channel);
      const res = await fetch(url.toString(), { cache: "no-store" });
      if (res.ok) return NextResponse.json(await res.json());
    } catch {}
  }

  let contacts = [...mockContacts];
  if (level) contacts = contacts.filter((c) => c.personalization_level === level);
  if (channel) contacts = contacts.filter((c) => c.recommended_channel === channel);

  const level_counts: Record<string, number> = { deep: 0, strong: 0, moderate: 0, basic: 0, generic: 0 };
  const channel_counts: Record<string, number> = { email: 0, linkedin: 0, phone: 0, multi: 0 };
  let total_score = 0, total_urgency = 0, hot_count = 0;

  for (const c of mockContacts) {
    level_counts[c.personalization_level] = (level_counts[c.personalization_level] || 0) + 1;
    channel_counts[c.recommended_channel] = (channel_counts[c.recommended_channel] || 0) + 1;
    total_score += c.personalization_score;
    total_urgency += c.outreach_urgency;
    if (c.outreach_urgency >= 70 && !c.do_not_contact) hot_count++;
  }

  const n = mockContacts.length;

  return NextResponse.json({
    contacts,
    summary: {
      total: n,
      level_counts,
      channel_counts,
      avg_personalization_score: Math.round((total_score / n) * 10) / 10,
      avg_urgency: Math.round((total_urgency / n) * 10) / 10,
      hot_count,
      dnc_count: 0,
    },
  });
}
