import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[refugee-refoulement-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Refugee Refoulement Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/refugee-refoulement-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Refugee Refoulement Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Refugee Refoulement Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "RR-001", name: "Libye/UE — Garde-Côtes Financés Refoulement & Centres Détention", country: "MENA/Europe", sector: "EUNAVFOR Financement Garde-Côtes Libyens, 100 000+ Interceptés/An, Camps Détention Torture Documentée & Accord UE-Libye", composite_score: 90.85, pushback_frequency_violence_score: 92.0, arbitrary_detention_scale_score: 95.0, non_refoulement_violation_score: 90.0, asylum_system_failure_score: 85.0, risk_level: "critique", primary_pattern: "detention_arbitraire_migrants", key_signals: ["Détention arbitraire indéfinie des migrants de Libye/UE — migrants sub-sahariens détenus sans base légale dans des camps de torture financés indirectement par l'Union Européenne", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Activer le Groupe de travail ONU sur la détention arbitraire et demander libération immédiate des détenus sans perspective de renvoi"], estimated_refugee_refoulement_index: 9.09, last_updated: "2026-06-20" },
    { entity_id: "RR-002", name: "Australie/Nauru-Manus — Offshore Detention & Pacific Solution", country: "Océanie", sector: "Offshore Detention Nauru/Manus 2013-2023, Enfants Détention Indéfinie, Médecins Silence MSF & Rajya Loi Anti-Recours", composite_score: 88.25, pushback_frequency_violence_score: 88.0, arbitrary_detention_scale_score: 92.0, non_refoulement_violation_score: 85.0, asylum_system_failure_score: 88.0, risk_level: "critique", primary_pattern: "detention_arbitraire_migrants", key_signals: ["Détention arbitraire indéfinie des migrants d'Australie — Pacific Solution enfermant des demandeurs d'asile pendant des années à Nauru et Manus Island sans procédure légale transparente", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Activer le Groupe de travail ONU sur la détention arbitraire et demander libération immédiate des détenus sans perspective de renvoi"], estimated_refugee_refoulement_index: 8.83, last_updated: "2026-06-20" },
    { entity_id: "RR-003", name: "Grèce/Frontex — Pushbacks Égée & HRW Témoignages Violence", country: "Europe", sector: "Pushbacks Documentés HRW/UNHCR 2020-24, Bateaux Gonflables Abandonnés, Frontex Complicité Enquête & Dénudements Rapportés", composite_score: 85.4, pushback_frequency_violence_score: 90.0, arbitrary_detention_scale_score: 80.0, non_refoulement_violation_score: 88.0, asylum_system_failure_score: 82.0, risk_level: "critique", primary_pattern: "pushback_illegal_violent", key_signals: ["Pushbacks illégaux et violents de Grèce/Frontex — renvoi forcé de demandeurs d'asile en mer Égée avec bateaux gonflables abandonnés et témoignages de violences documentés par HRW et UNHCR", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Saisir en urgence le HCR et engager des poursuites devant la CEDH pour violations de la Convention de Genève 1951"], estimated_refugee_refoulement_index: 8.54, last_updated: "2026-06-20" },
    { entity_id: "RR-004", name: "USA/ICE — Title 42 Expulsions Masse & Familles Séparées", country: "Amérique du Nord", sector: "Title 42 2.5M Expulsions Pandémie, Familles Séparées 5000+ Enfants, Hieleras Détention Froide & Asylum Ban Executive", composite_score: 83.45, pushback_frequency_violence_score: 82.0, arbitrary_detention_scale_score: 85.0, non_refoulement_violation_score: 80.0, asylum_system_failure_score: 88.0, risk_level: "critique", primary_pattern: "refoulement_zones_conflit", key_signals: ["Refoulement vers zones de conflit actif d'USA/ICE — expulsions en masse vers des pays d'Amérique Centrale où les déportés risquent la persécution par les gangs ou les cartels sans examen individuel", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Saisir le HCR et la CrIDH pour mesure d'urgence suspendant les expulsions vers les pays à risque identifiés"], estimated_refugee_refoulement_index: 8.35, last_updated: "2026-06-20" },
    { entity_id: "RR-005", name: "Turquie/Syrie — Déportations Syriens & Pushbacks Frontière Iran", country: "MENA/Europe", sector: "Syriens Déportés De Force 2023, Pushbacks Afghans Frontière Iran, 3.6M Réfugiés Tension Xénophobie & Noyades Frontière", composite_score: 57.5, pushback_frequency_violence_score: 55.0, arbitrary_detention_scale_score: 62.0, non_refoulement_violation_score: 58.0, asylum_system_failure_score: 55.0, risk_level: "élevé", primary_pattern: "detention_arbitraire_migrants", key_signals: ["Détention arbitraire et déportations de Turquie — Syriens déportés de force vers la zone de conflit malgré les risques documentés et pushbacks violents d'Afghans à la frontière iranienne", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Activer le Groupe de travail ONU sur la détention arbitraire et suspendre les accords de coopération frontalière violant le non-refoulement"], estimated_refugee_refoulement_index: 5.75, last_updated: "2026-06-20" },
    { entity_id: "RR-006", name: "Pologne/Belarus — Pushbacks Forêt Białowieża & Personnes Décédées", country: "Europe", sector: "Forêt Białowieża Morts Hypothermie, Zone Exclusion Journalistes, Loi Légalisant Pushbacks 2023 & Instrumentalisation Migrante Loukachenko", composite_score: 56.9, pushback_frequency_violence_score: 58.0, arbitrary_detention_scale_score: 52.0, non_refoulement_violation_score: 62.0, asylum_system_failure_score: 55.0, risk_level: "élevé", primary_pattern: "externalisation_controle_frontalier", key_signals: ["Externalisation répressive de Pologne/Belarus — loi légalisant les pushbacks adoptée en 2023, laissant des personnes mourir d'hypothermie dans la forêt de Białowieża sans accès aux procédures d'asile", "Principe de non-refoulement violé — les États renvoient des personnes vers des pays où elles risquent la persécution en contravention directe de l'Article 33 de la Convention de Genève 1951", "Engager la rapporteure spéciale ONU sur les droits des migrants et suspendre les accords de coopération frontalière violant le non-refoulement"], estimated_refugee_refoulement_index: 5.69, last_updated: "2026-06-20" },
    { entity_id: "RR-007", name: "Canada — Accord Canada-USA Tiers Pays Sûr & Roxham Road", country: "Amérique du Nord", sector: "Accord Tiers Pays Sûr USA Étendu 2023, Roxham Road Fermée, Haïtiens Expulsés & Systèmes Asile Engorgés 12+ Mois", composite_score: 28.4, pushback_frequency_violence_score: 25.0, arbitrary_detention_scale_score: 28.0, non_refoulement_violation_score: 30.0, asylum_system_failure_score: 32.0, risk_level: "modéré", primary_pattern: "externalisation_controle_frontalier", key_signals: ["Externalisation partielle du contrôle frontalier du Canada — accord de tiers pays sûr étendu et fermeture de Roxham Road limitant l'accès à l'asile sans réforme du système congestionné", "Principe de non-refoulement partiellement respecté — engagements formels maintenus mais pratiques administratives créant des obstacles à l'accès aux procédures d'asile pour les demandeurs vulnérables", "Engager la rapporteure spéciale ONU sur les droits des migrants pour évaluation indépendante de l'accord Canada-USA sur les pays tiers sûrs"], estimated_refugee_refoulement_index: 2.84, last_updated: "2026-06-20" },
    { entity_id: "RR-008", name: "HCR/CEDH — Convention Réfugiés 1951 & Non-Refoulement", country: "Global", sector: "Convention 1951 149 États, Protocole 1967, CEDH Arrêts Refoulement & HCR Budget 10B$/An Protection", composite_score: 4.45, pushback_frequency_violence_score: 5.0, arbitrary_detention_scale_score: 4.0, non_refoulement_violation_score: 3.0, asylum_system_failure_score: 6.0, risk_level: "faible", primary_pattern: "protection_refugies_exemplaire", key_signals: ["HCR/CEDH incarnent la protection exemplaire des réfugiés — non-refoulement respecté, procédures d'asile équitables et intégration effective des bénéficiaires de protection internationale", "Convention de Genève 1951 universellement reconnue — 149 États parties avec obligation contraignante de non-refoulement créant un droit subjectif pour les demandeurs d'asile", "Partager les bonnes pratiques d'accueil et augmenter les contributions au budget du HCR pour renforcer la protection mondiale des réfugiés"], estimated_refugee_refoulement_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { pushback_illegal_violent: 1, detention_arbitraire_migrants: 3, externalisation_controle_frontalier: 2, refoulement_zones_conflit: 1, protection_refugies_exemplaire: 1 },
    top_risk_entities: ["Libye/UE — Garde-Côtes Financés Refoulement & Centres Détention", "Australie/Nauru-Manus — Offshore Detention & Pacific Solution", "Grèce/Frontex — Pushbacks Égée & HRW Témoignages Violence"],
    critical_alerts: ["Libye/UE: détention arbitraire indéfinie migrants", "Australie/Nauru-Manus: détention arbitraire indéfinie", "Grèce/Frontex: pushbacks illégaux violents", "USA/ICE: refoulement zones conflit actif"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "refugee_refoulement",
    confidence_score: 0.84,
    data_sources: ["unhcr_global_trends_forced_displacement", "hrw_pushback_documentation_database", "bordermonitoring_eu_incident_reports"],
    entities,
    avg_estimated_refugee_refoulement_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
