import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[right-to-privacy-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Right to Privacy Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/right-to-privacy-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Right to Privacy Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Right to Privacy Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "RP-001", name: "Chine — Bouclier Doré/GFW, Crédit Social & Surveillance Biométrique Totale", country: "Asie du Nord-Est", sector: "Chine Bouclier Doré Great Firewall 1M+ Sites Bloqués, Système Crédit Social Notation Comportementale, Reconnaissance Faciale 600M Caméras Skynet/Sharp Eyes & Ouïghours Xinjiang Surveillance Totale", composite_score: 96.75, mass_surveillance_score: 98.0, data_exploitation_score: 95.0, legal_protection_absence_score: 96.0, digital_surveillance_score: 98.0, risk_level: "critique", primary_pattern: "mass_surveillance", key_signals: ["Violation du droit à la vie privée documentée — Chine avec score composite 96.75/100 révélant le système de surveillance le plus étendu au monde : Great Firewall bloquant 1M+ sites, 600M caméras Skynet/Sharp Eyes, système de crédit social notant les comportements et surveillance totale des Ouïghours en Xinjiang violant l'Article 17 PIDCP", "Surveillance de masse (98.0/100) — le déploiement par la Chine de la reconnaissance faciale obligatoire, du suivi en temps réel via les smartphones et du système de crédit social pénalisant les comportements légaux constitue la violation la plus systématique du droit à la vie privée jamais documentée à l'échelle d'un milliard de personnes", "Adopter une résolution contraignante du Conseil des droits de l'homme ONU contre la surveillance biométrique de masse et exiger la cessation immédiate du système de crédit social chinois contraire à l'Article 17 PIDCP sur la protection de la vie privée et à la Résolution 34/7 du CDH sur la vie privée à l'ère numérique"], estimated_right_to_privacy_index: 9.68, last_updated: "2026-06-20" },
    { id: "RP-002", name: "Russie — SORM-3, RuNet Souverain & FSB Accès Total Communications", country: "Europe de l'Est", sector: "Russie SORM-3 Interception Légale Obligatoire FSB Opérateurs, RuNet Internet Souverain Déconnectable, Messagers Chiffrés Interdits 2022 & Loi Yarovaya Stockage 6 Mois Toutes Communications", composite_score: 88.65, mass_surveillance_score: 90.0, data_exploitation_score: 85.0, legal_protection_absence_score: 88.0, digital_surveillance_score: 92.0, risk_level: "critique", primary_pattern: "mass_surveillance", key_signals: ["Violation du droit à la vie privée documentée — Russie avec score composite 88.65/100 révélant le système SORM-3 obligeant tous les opérateurs à installer des équipements permettant au FSB d'intercepter toutes communications sans mandat judiciaire, violant l'Article 17 PIDCP", "Surveillance numérique (92.0/100) — la loi Yarovaya obligeant le stockage de 6 mois de toutes les communications des citoyens russes et l'obligation de déchiffrement pour le FSB sous peine de blocage révèlent un système de surveillance étatique incompatible avec le droit à la vie privée", "Invoquer la procédure d'enquête du Conseil des droits de l'homme ONU sur la surveillance SORM-3 et exiger la mise en conformité avec les Principes Nécessité et Proportionnalité sur la surveillance des communications élaborés par les rapporteurs spéciaux ONU en 2013"], estimated_right_to_privacy_index: 8.87, last_updated: "2026-06-20" },
    { id: "RP-003", name: "USA — NSA PRISM, Patriot Act & Surveillance Masse Post-9/11 Snowden", country: "Amérique du Nord", sector: "USA NSA PRISM Surveillance 89M Personnes Snowden 2013, Patriot Act Section 215 Métadonnées Téléphoniques, FISA Court Secrète & CLOUD Act Données Étrangers Serveurs USA", composite_score: 80.0, mass_surveillance_score: 72.0, data_exploitation_score: 90.0, legal_protection_absence_score: 78.0, digital_surveillance_score: 82.0, risk_level: "critique", primary_pattern: "data_exploitation", key_signals: ["Violation du droit à la vie privée documentée — USA avec score composite 80.0/100 révélant le programme PRISM de la NSA collectant les données de 89M+ personnes sans mandat individuel, exposé par Edward Snowden en 2013, violant l'Article 17 PIDCP et les engagements de protection des données des alliés", "Exploitation données (90.0/100) — le programme PRISM de la NSA accédant aux serveurs de Google, Facebook, Apple et Microsoft sans mandat individuel et le CLOUD Act permettant l'accès unilatéral aux données stockées par des entreprises américaines à l'étranger constituent des violations extraterritoriales du droit à la vie privée", "Réformer le Foreign Intelligence Surveillance Act (FISA) pour exiger des mandats judiciaires individuels pour toute surveillance de citoyens étrangers et ratifier le Protocole additionnel au PIDCP sur la vie privée à l'ère numérique reconnaissant la portée extraterritoriale de l'Article 17"], estimated_right_to_privacy_index: 8.0, last_updated: "2026-06-20" },
    { id: "RP-004", name: "Iran — Filtrage Internet, Deep Packet Inspection & Répression Manifestants", country: "MENA", sector: "Iran DPI Deep Packet Inspection Toutes Communications, Coupures Internet Manifestations 2019/2022, Telegram/Instagram Bloqués & Identité Numérique Liée Surveillance Politique", composite_score: 79.35, mass_surveillance_score: 72.0, data_exploitation_score: 75.0, legal_protection_absence_score: 92.0, digital_surveillance_score: 80.0, risk_level: "critique", primary_pattern: "legal_protection_absence", key_signals: ["Violation du droit à la vie privée documentée — Iran avec score composite 79.35/100 révélant l'utilisation du Deep Packet Inspection pour surveiller toutes communications numériques, les coupures Internet lors des manifestations de 2019 et 2022 et l'absence totale de protection légale de la vie privée", "Absence protection légale (92.0/100) — l'Iran n'a aucune loi de protection des données, utilise la surveillance numérique comme outil de répression politique (arrestations lors des manifestations Mahsa Amini 2022 basées sur la surveillance) et le DPI constitue une violation systématique de l'Article 17 PIDCP", "Appliquer des sanctions ciblées contre les fournisseurs de technologie de surveillance iraniens et exiger la mise en place d'une loi de protection des données indépendante conforme aux standards du Comité des droits de l'homme ONU dans ses observations sur la vie privée à l'ère numérique (2015)"], estimated_right_to_privacy_index: 7.94, last_updated: "2026-06-20" },
    { id: "RP-005", name: "GAFAM/Big Tech — Capitalisme Surveillance, 87M Cambridge Analytica & Dark Patterns", country: "Global/Tech", sector: "Meta Cambridge Analytica 87M Profils Sans Consentement, Google 4B$ RGPD Amendes, Apple App Tracking Opaque, Amazon Alexa Écoute Permanente & TikTok Transfert Données Chine Documenté", composite_score: 55.4, mass_surveillance_score: 48.0, data_exploitation_score: 68.0, legal_protection_absence_score: 52.0, digital_surveillance_score: 55.0, risk_level: "élevé", primary_pattern: "data_exploitation", key_signals: ["Violation du droit à la vie privée documentée — GAFAM/Big Tech avec score composite 55.4/100 révélant l'exploitation commerciale des données personnelles à grande échelle : Cambridge Analytica (87M profils), amendes RGPD systématiques (Meta 1.2B€, Google 4B$) et opacité des algorithmes de profilage", "Exploitation données (68.0/100) — les modèles économiques de Meta, Google et Amazon reposant sur la collecte et la monétisation de données comportementales sans consentement éclairé réel constituent une forme de capitalisme de surveillance incompatible avec l'Article 17 PIDCP sur la vie privée", "Renforcer le RGPD pour interdire le modèle publicitaire basé sur le profilage comportemental et adopter une loi fédérale américaine de protection des données alignée sur les standards européens, conformément aux recommandations de la Commission nationale informatique et libertés (CNIL) et du Comité de protection des données (EDPB)"], estimated_right_to_privacy_index: 5.54, last_updated: "2026-06-20" },
    { id: "RP-006", name: "Inde — Aadhaar 1,4Md Biométries, Surveillance Politique & PDPB Retardé", country: "Asie du Sud", sector: "Inde Aadhaar 1,4 Milliard Biométries Centralisées, Personal Data Protection Bill 2023 Dilué, Espionnage Pegasus Journalistes/Opposants & Visage Reconnaissance Déployée Police États", composite_score: 52.65, mass_surveillance_score: 56.0, data_exploitation_score: 50.0, legal_protection_absence_score: 55.0, digital_surveillance_score: 48.0, risk_level: "élevé", primary_pattern: "mass_surveillance", key_signals: ["Violation du droit à la vie privée documentée — Inde avec score composite 52.65/100 révélant la base de données biométriques Aadhaar centralisant les données de 1,4 milliard de personnes sans protection adéquate, l'usage du logiciel Pegasus contre des journalistes et le retard de la loi de protection des données", "Surveillance de masse (56.0/100) — l'intégration obligatoire d'Aadhaar à tous les services publics et bancaires, combinée au déploiement de la reconnaissance faciale par plusieurs États sans cadre légal, révèle une infrastructure de surveillance biométrique de masse en violation du droit à la vie privée garanti par l'arrêt Puttaswamy de la Cour Suprême (2017)", "Adopter un Personal Data Protection Act robuste avec une autorité de protection indépendante et limiter l'usage d'Aadhaar aux services essentiels, conformément à l'arrêt Puttaswamy de la Cour Suprême indienne reconnaissant la vie privée comme droit fondamental et aux recommandations du Rapporteur Spécial ONU sur la vie privée"], estimated_right_to_privacy_index: 5.27, last_updated: "2026-06-20" },
    { id: "RP-007", name: "UE/RGPD — Cadre Protection Données Référence Mondial & Lacunes Application", country: "Europe", sector: "UE RGPD 2018 Cadre Référence 27 États, Amendes Max 4% CA Mondial, EDPB Coordination Nationale, Transferts USA Schrems I/II Invalidés CJU & Lacunes Application PME/IA", composite_score: 28.65, mass_surveillance_score: 28.0, data_exploitation_score: 32.0, legal_protection_absence_score: 25.0, digital_surveillance_score: 30.0, risk_level: "modéré", primary_pattern: "data_exploitation", key_signals: ["Progrès législatif significatif mais lacunes — le RGPD européen adopté en 2018 constitue le cadre de protection des données le plus avancé au monde avec des amendes jusqu'à 4% du chiffre d'affaires mondial, mais son application reste inégale entre États membres et les technologies IA créent de nouvelles lacunes", "Exploitation données (32.0/100) — malgré le RGPD, les pratiques de Dark Patterns contournant le consentement éclairé et l'insuffisante application par certaines autorités nationales révèlent des lacunes dans la protection effective des données des citoyens européens", "Renforcer l'application uniforme du RGPD en harmonisant les ressources des autorités nationales de protection des données et étendre son cadre à l'IA générative via l'EU AI Act, pour maintenir le leadership européen dans les standards mondiaux de protection de la vie privée"], estimated_right_to_privacy_index: 2.87, last_updated: "2026-06-20" },
    { id: "RP-008", name: "ONU/PIDCP Art.17 — Droit Vie Privée, Résolution CDH & Principes Surveillance", country: "Global", sector: "PIDCP Article 17 Protection Vie Privée, Résolution CDH 34/7 Vie Privée Ère Numérique 2017, Rapporteur Spécial ONU Vie Privée & Principes Nécessité Proportionnalité Surveillance 2013", composite_score: 4.45, mass_surveillance_score: 5.0, data_exploitation_score: 4.0, legal_protection_absence_score: 3.0, digital_surveillance_score: 6.0, risk_level: "faible", primary_pattern: "digital_surveillance", key_signals: ["ONU/PIDCP Art.17 incarne le cadre normatif exemplaire du droit à la vie privée — l'Article 17 PIDCP garantissant la protection contre les immixtions arbitraires dans la vie privée et la Résolution CDH 34/7 (2017) étendant explicitement ce droit à l'ère numérique créant des obligations contraignantes", "Principes Nécessité et Proportionnalité — les 13 principes élaborés par les rapporteurs spéciaux ONU en 2013 sur la surveillance des communications définissant les conditions dans lesquelles la surveillance étatique peut être légitimement exercée : légalité, nécessité, proportionnalité, notification et recours effectif", "Adopter un Protocole additionnel au PIDCP spécifiquement dédié à la vie privée à l'ère numérique, incluant des obligations pour les entreprises de technologie, et renforcer le mandat du Rapporteur Spécial ONU sur le droit à la vie privée pour couvrir la surveillance algorithmique et les données biométriques"], estimated_right_to_privacy_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { mass_surveillance: 3, data_exploitation: 3, legal_protection_absence: 1, digital_surveillance: 1 },
    top_risk_entities: ["Chine — Bouclier Doré/GFW, Crédit Social & Surveillance Biométrique Totale", "Russie — SORM-3, RuNet Souverain & FSB Accès Total Communications", "USA — NSA PRISM, Patriot Act & Surveillance Masse Post-9/11 Snowden"],
    critical_alerts: ["Chine: mass surveillance", "Russie: mass surveillance", "USA: data exploitation", "Iran: legal protection absence"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "right_to_privacy",
    confidence_score: 0.83,
    data_sources: ["privacy_international_state_of_privacy_country_reports", "freedom_house_freedom_on_the_net_annual_report", "un_special_rapporteur_right_to_privacy_country_reports"],
    entities,
    avg_estimated_right_to_privacy_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
