import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[campaign-roi] SWARM_API_URL non défini — mode dégradé activé");
}

const SWARM_API_URL = process.env.SWARM_API_URL;

const mockCampaigns = [
  {
    campaign: {
      campaign_id: "cmp_001",
      campaign_name: "Cold Outreach Q1 — DSI SaaS",
      channel: "email",
      start_date: "2026-01-06",
      duration_days: 45,
      budget_eur: 8000,
      total_spent_eur: 7800,
      total_contacts: 1200,
      emails_sent: 3600,
      opens: 1188,
      clicks: 252,
      unsubscribes: 18,
      leads_generated: 84,
      mqls: 42,
      sqls: 18,
      opportunities_created: 15,
      deals_won: 4,
      pipeline_value_eur: 280000,
      closed_revenue_eur: 68000,
      avg_deal_size_eur: 17000,
    },
    roi_pct: 772.0,
    roi_score: 82.4,
    reach_efficiency: 76.8,
    conversion_quality: 68.5,
    cost_efficiency: 78.2,
    overall_score: 76.9,
    status: "good",
    cost_per_lead_eur: 92.86,
    cost_per_sql_eur: 433.33,
    cost_per_deal_eur: 1950.0,
    open_rate_pct: 33.0,
    click_rate_pct: 7.0,
    lead_to_opp_rate_pct: 17.9,
    opp_to_won_rate_pct: 26.7,
    key_insights: [
      "ROI exceptionnel — bien au-dessus du benchmark sectoriel",
      "Excellent taux de conversion — ciblage très pertinent",
      "Très bonne portée — campagne scalable",
      "Très bonne efficacité budgétaire",
      "Pipeline significatif généré — bon alignement marketing/ventes",
    ],
    recommendations: [
      "Lancer des A/B tests sur le contenu et les CTA",
      "Lancer une campagne de retargeting sur les contacts engagés",
      "Réutiliser le contenu performant sur d'autres canaux",
    ],
    benchmark_vs_channel: 2.41,
  },
  {
    campaign: {
      campaign_id: "cmp_002",
      campaign_name: "LinkedIn Thought Leadership — DAF PME",
      channel: "linkedin",
      start_date: "2026-02-03",
      duration_days: 30,
      budget_eur: 5000,
      total_spent_eur: 4800,
      total_contacts: 850,
      emails_sent: 850,
      opens: 255,
      clicks: 34,
      unsubscribes: 8,
      leads_generated: 28,
      mqls: 16,
      sqls: 8,
      opportunities_created: 6,
      deals_won: 2,
      pipeline_value_eur: 120000,
      closed_revenue_eur: 42000,
      avg_deal_size_eur: 21000,
    },
    roi_pct: 775.0,
    roi_score: 93.2,
    reach_efficiency: 58.4,
    conversion_quality: 61.2,
    cost_efficiency: 64.8,
    overall_score: 71.5,
    status: "good",
    cost_per_lead_eur: 171.43,
    cost_per_sql_eur: 600.0,
    cost_per_deal_eur: 2400.0,
    open_rate_pct: 30.0,
    click_rate_pct: 4.0,
    lead_to_opp_rate_pct: 21.4,
    opp_to_won_rate_pct: 33.3,
    key_insights: [
      "ROI exceptionnel — bien au-dessus du benchmark sectoriel",
      "Pipeline significatif généré — bon alignement marketing/ventes",
      "Coût par lead élevé — revoir le ciblage ou le message",
    ],
    recommendations: [
      "Lancer des A/B tests sur le contenu et les CTA",
      "Lancer une campagne de retargeting sur les contacts engagés",
      "Affiner le ciblage ICP pour améliorer la conversion",
    ],
    benchmark_vs_channel: 4.31,
  },
  {
    campaign: {
      campaign_id: "cmp_003",
      campaign_name: "Webinaire IA & RevOps — C-Suite",
      channel: "webinar",
      start_date: "2026-03-10",
      duration_days: 14,
      budget_eur: 3500,
      total_spent_eur: 3200,
      total_contacts: 320,
      emails_sent: 2400,
      opens: 840,
      clicks: 192,
      unsubscribes: 12,
      leads_generated: 64,
      mqls: 38,
      sqls: 20,
      opportunities_created: 14,
      deals_won: 5,
      pipeline_value_eur: 195000,
      closed_revenue_eur: 87500,
      avg_deal_size_eur: 17500,
    },
    roi_pct: 2634.0,
    roi_score: 100.0,
    reach_efficiency: 88.6,
    conversion_quality: 82.3,
    cost_efficiency: 92.4,
    overall_score: 90.4,
    status: "excellent",
    cost_per_lead_eur: 50.0,
    cost_per_sql_eur: 160.0,
    cost_per_deal_eur: 640.0,
    open_rate_pct: 35.0,
    click_rate_pct: 8.0,
    lead_to_opp_rate_pct: 21.9,
    opp_to_won_rate_pct: 35.7,
    key_insights: [
      "ROI exceptionnel — bien au-dessus du benchmark sectoriel",
      "Engagement très élevé — contenu très pertinent pour la cible",
      "Excellent taux de conversion — ciblage très pertinent",
      "Très bonne efficacité budgétaire",
      "Pipeline significatif généré — bon alignement marketing/ventes",
    ],
    recommendations: [
      "Augmenter le budget et la fréquence — fort potentiel ROI",
      "Réutiliser le contenu performant sur d'autres canaux",
    ],
    benchmark_vs_channel: 10.53,
  },
  {
    campaign: {
      campaign_id: "cmp_004",
      campaign_name: "SEA Google Ads — Logiciel CRM",
      channel: "paid",
      start_date: "2026-01-15",
      duration_days: 60,
      budget_eur: 15000,
      total_spent_eur: 14200,
      total_contacts: 4500,
      emails_sent: 4500,
      opens: 1350,
      clicks: 540,
      unsubscribes: 45,
      leads_generated: 180,
      mqls: 72,
      sqls: 25,
      opportunities_created: 10,
      deals_won: 2,
      pipeline_value_eur: 95000,
      closed_revenue_eur: 38000,
      avg_deal_size_eur: 19000,
    },
    roi_pct: 167.6,
    roi_score: 55.2,
    reach_efficiency: 82.4,
    conversion_quality: 38.6,
    cost_efficiency: 42.8,
    overall_score: 56.2,
    status: "average",
    cost_per_lead_eur: 78.89,
    cost_per_sql_eur: 568.0,
    cost_per_deal_eur: 7100.0,
    open_rate_pct: 30.0,
    click_rate_pct: 12.0,
    lead_to_opp_rate_pct: 5.6,
    opp_to_won_rate_pct: 20.0,
    key_insights: [
      "ROI sous le benchmark — optimisation nécessaire",
      "Très bonne portée — campagne scalable",
      "Taux de conversion lead → opportunité faible — qualifier le ciblage",
    ],
    recommendations: [
      "Affiner le ciblage ICP pour améliorer la conversion",
      "Optimiser les landing pages pour améliorer la conversion",
      "Ajouter une séquence de nurture pour les leads froids",
      "Renforcer l'alignement marketing-ventes sur le suivi des leads",
    ],
    benchmark_vs_channel: 1.12,
  },
  {
    campaign: {
      campaign_id: "cmp_005",
      campaign_name: "Content Marketing — Blog SEO RH",
      channel: "content",
      start_date: "2025-10-01",
      duration_days: 90,
      budget_eur: 6000,
      total_spent_eur: 5500,
      total_contacts: 2200,
      emails_sent: 2200,
      opens: 440,
      clicks: 88,
      unsubscribes: 22,
      leads_generated: 44,
      mqls: 18,
      sqls: 6,
      opportunities_created: 3,
      deals_won: 0,
      pipeline_value_eur: 45000,
      closed_revenue_eur: 0,
      avg_deal_size_eur: 0,
    },
    roi_pct: -100.0,
    roi_score: 20.0,
    reach_efficiency: 54.6,
    conversion_quality: 22.4,
    cost_efficiency: 28.8,
    overall_score: 31.8,
    status: "poor",
    cost_per_lead_eur: 125.0,
    cost_per_sql_eur: 916.67,
    cost_per_deal_eur: -1.0,
    open_rate_pct: 20.0,
    click_rate_pct: 4.0,
    lead_to_opp_rate_pct: 6.8,
    opp_to_won_rate_pct: 0.0,
    key_insights: [
      "ROI sous le benchmark — optimisation nécessaire",
      "Taux de conversion lead → opportunité faible — qualifier le ciblage",
      "Taux de désabonnement élevé — revoir la pression et pertinence",
    ],
    recommendations: [
      "Affiner le ciblage ICP pour améliorer la conversion",
      "Augmenter la personnalisation des messages",
      "Réduire le budget — ROI insuffisant pour justifier l'investissement",
      "Réduire la fréquence d'envoi pour limiter les désabonnements",
      "Renforcer l'alignement marketing-ventes sur le suivi des leads",
    ],
    benchmark_vs_channel: 0.0,
  },
  {
    campaign: {
      campaign_id: "cmp_006",
      campaign_name: "Cold Outbound — Directeurs IT Industrie",
      channel: "outbound",
      start_date: "2026-04-01",
      duration_days: 30,
      budget_eur: 4000,
      total_spent_eur: 3600,
      total_contacts: 600,
      emails_sent: 1800,
      opens: 612,
      clicks: 126,
      unsubscribes: 9,
      leads_generated: 42,
      mqls: 24,
      sqls: 12,
      opportunities_created: 9,
      deals_won: 3,
      pipeline_value_eur: 162000,
      closed_revenue_eur: 54000,
      avg_deal_size_eur: 18000,
    },
    roi_pct: 1400.0,
    roi_score: 96.8,
    reach_efficiency: 72.3,
    conversion_quality: 75.4,
    cost_efficiency: 85.6,
    overall_score: 82.2,
    status: "excellent",
    cost_per_lead_eur: 85.71,
    cost_per_sql_eur: 300.0,
    cost_per_deal_eur: 1200.0,
    open_rate_pct: 34.0,
    click_rate_pct: 7.0,
    lead_to_opp_rate_pct: 21.4,
    opp_to_won_rate_pct: 33.3,
    key_insights: [
      "ROI exceptionnel — bien au-dessus du benchmark sectoriel",
      "Excellent taux de conversion — ciblage très pertinent",
      "Pipeline significatif généré — bon alignement marketing/ventes",
      "Très bonne efficacité budgétaire",
    ],
    recommendations: [
      "Augmenter le budget et la fréquence — fort potentiel ROI",
      "Réutiliser le contenu performant sur d'autres canaux",
    ],
    benchmark_vs_channel: 7.0,
  },
  {
    campaign: {
      campaign_id: "cmp_007",
      campaign_name: "Salon B2B Tech Paris 2026",
      channel: "event",
      start_date: "2026-05-14",
      duration_days: 3,
      budget_eur: 12000,
      total_spent_eur: 11800,
      total_contacts: 380,
      emails_sent: 380,
      opens: 152,
      clicks: 38,
      unsubscribes: 2,
      leads_generated: 62,
      mqls: 30,
      sqls: 14,
      opportunities_created: 8,
      deals_won: 2,
      pipeline_value_eur: 148000,
      closed_revenue_eur: 44000,
      avg_deal_size_eur: 22000,
    },
    roi_pct: 272.9,
    roi_score: 71.8,
    reach_efficiency: 55.2,
    conversion_quality: 62.4,
    cost_efficiency: 52.6,
    overall_score: 62.8,
    status: "good",
    cost_per_lead_eur: 190.32,
    cost_per_sql_eur: 842.86,
    cost_per_deal_eur: 5900.0,
    open_rate_pct: 40.0,
    click_rate_pct: 10.0,
    lead_to_opp_rate_pct: 12.9,
    opp_to_won_rate_pct: 25.0,
    key_insights: [
      "ROI solide — au-dessus du benchmark sectoriel",
      "Engagement très élevé — contenu très pertinent pour la cible",
      "Coût par lead élevé — revoir le ciblage ou le message",
      "Pipeline significatif généré — bon alignement marketing/ventes",
    ],
    recommendations: [
      "Lancer des A/B tests sur le contenu et les CTA",
      "Lancer une campagne de retargeting sur les contacts engagés",
    ],
    benchmark_vs_channel: 3.41,
  },
  {
    campaign: {
      campaign_id: "cmp_008",
      campaign_name: "Newsletter Mensuelle — Communauté DSI",
      channel: "email",
      start_date: "2026-01-01",
      duration_days: 150,
      budget_eur: 2000,
      total_spent_eur: 1800,
      total_contacts: 5000,
      emails_sent: 15000,
      opens: 3000,
      clicks: 300,
      unsubscribes: 150,
      leads_generated: 30,
      mqls: 10,
      sqls: 3,
      opportunities_created: 1,
      deals_won: 0,
      pipeline_value_eur: 25000,
      closed_revenue_eur: 0,
      avg_deal_size_eur: 0,
    },
    roi_pct: -100.0,
    roi_score: 20.0,
    reach_efficiency: 48.2,
    conversion_quality: 10.4,
    cost_efficiency: 20.2,
    overall_score: 25.8,
    status: "poor",
    cost_per_lead_eur: 60.0,
    cost_per_sql_eur: 600.0,
    cost_per_deal_eur: -1.0,
    open_rate_pct: 20.0,
    click_rate_pct: 2.0,
    lead_to_opp_rate_pct: 3.3,
    opp_to_won_rate_pct: 0.0,
    key_insights: [
      "ROI sous le benchmark — optimisation nécessaire",
      "Taux de désabonnement élevé — revoir la pression et pertinence",
      "Taux de conversion lead → opportunité faible — qualifier le ciblage",
    ],
    recommendations: [
      "Affiner le ciblage ICP pour améliorer la conversion",
      "Augmenter la personnalisation des messages",
      "Réduire le budget — ROI insuffisant pour justifier l'investissement",
      "Réduire la fréquence d'envoi pour limiter les désabonnements",
      "Renforcer l'alignement marketing-ventes sur le suivi des leads",
    ],
    benchmark_vs_channel: 0.0,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const status = searchParams.get("status");
  const channel = searchParams.get("channel");

  if (SWARM_API_URL) {
    try {
      const url = new URL(`${SWARM_API_URL}/api/campaign-roi`);
      if (status) url.searchParams.set("status", status);
      if (channel) url.searchParams.set("channel", channel);
      const res = await fetch(url.toString(), { cache: "no-store" });
      if (res.ok) return sealResponse(NextResponse.json(await res.json()));
    } catch {}
  }

  let campaigns = [...mockCampaigns];
  if (status) campaigns = campaigns.filter((c) => c.status === status);
  if (channel) campaigns = campaigns.filter((c) => c.campaign.channel === channel);

  const status_counts: Record<string, number> = { excellent: 0, good: 0, average: 0, poor: 0, failing: 0 };
  const channel_counts: Record<string, number> = {};
  let total_pipeline = 0, total_revenue = 0, total_spent = 0, total_roi = 0, total_score = 0;

  for (const c of mockCampaigns) {
    status_counts[c.status] = (status_counts[c.status] || 0) + 1;
    channel_counts[c.campaign.channel] = (channel_counts[c.campaign.channel] || 0) + 1;
    total_pipeline += c.campaign.pipeline_value_eur;
    total_revenue += c.campaign.closed_revenue_eur;
    total_spent += c.campaign.total_spent_eur;
    total_roi += c.roi_pct;
    total_score += c.overall_score;
  }

  const n = mockCampaigns.length;

  return sealResponse(NextResponse.json({
    campaigns,
    summary: {
      total: n,
      status_counts,
      channel_counts,
      avg_overall_score: Math.round((total_score / n) * 10) / 10,
      avg_roi_pct: Math.round((total_roi / n) * 10) / 10,
      total_pipeline_eur: total_pipeline,
      total_closed_revenue_eur: total_revenue,
      total_spent_eur: total_spent,
    },
  }));
}
