import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[food-sovereignty-agricultural-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(await sealResponse(MOCK));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/food-sovereignty-agricultural-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(await sealResponse(data));
  } catch {
    return NextResponse.json(await sealResponse(MOCK), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "FSAR-001", name: "Inde/Suicides Agriculteurs Dettes Bt Cotton Monsanto 300K Morts", country: "Asie du Sud", sector: "300.000 Suicides Agriculteurs 1995-2022, Bt Cotton Monsanto Dépendance, Cycles Dette Insurmontables, Maharashtra Epicentre & Loi Semences Propriétaires 2020 Retirée", composite_score: 84.55, land_grabbing_smallholder_displacement_score: 88.0, corporate_seed_monopoly_farmer_dependency_score: 92.0, food_import_dependency_price_shock_vulnerability_score: 75.0, traditional_farming_knowledge_erosion_score: 82.0, risk_level: "critique", primary_pattern: "monopole_semences_dependance_corporative", key_signals: ["Crise agricole critique de Inde/Suicides Agriculteurs Dettes Bt Cotton Monsanto 300K Morts — accaparement des terres et/ou monopole semencier créant des conditions de dépendance et de vulnérabilité alimentaire systémique pour des millions d'agriculteurs", "Violation du droit à l'alimentation — l'article 11 du PIDESC est directement menacé par la concentration corporative des ressources agricoles et l'élimination des systèmes alimentaires paysans traditionnels", "Spirale de la dette agricole — les dépendances aux intrants industriels (semences, pesticides, engrais) génèrent des cycles de dette insurmontables poussant des centaines de milliers d'agriculteurs à la ruine et au suicide"], estimated_food_sovereignty_agricultural_rights_index: 8.46, last_updated: "2026-06-21" },
    { id: "FSAR-002", name: "Éthiopie/Accaparement Terres 3.6M Hectares Investisseurs Étrangers", country: "Afrique de l'Est", sector: "3.6M Ha Cédés 2000-2015, Saudi Arabia/India/China Investisseurs, Villages Oromia Déplacés, Gambella 70.000 Expulsés & Oakland Institute Rapport Violations", composite_score: 76.5, land_grabbing_smallholder_displacement_score: 90.0, corporate_seed_monopoly_farmer_dependency_score: 72.0, food_import_dependency_price_shock_vulnerability_score: 66.0, traditional_farming_knowledge_erosion_score: 75.0, risk_level: "critique", primary_pattern: "accaparement_terres_deplacementpaysans", key_signals: ["Crise agricole critique de Éthiopie/Accaparement Terres 3.6M Hectares Investisseurs Étrangers — accaparement des terres et/ou monopole semencier créant des conditions de dépendance et de vulnérabilité alimentaire systémique pour des millions d'agriculteurs", "Violation du droit à l'alimentation — l'article 11 du PIDESC est directement menacé par la concentration corporative des ressources agricoles et l'élimination des systèmes alimentaires paysans traditionnels", "Spirale de la dette agricole — les dépendances aux intrants industriels (semences, pesticides, engrais) génèrent des cycles de dette insurmontables poussant des centaines de milliers d'agriculteurs à la ruine et au suicide"], estimated_food_sovereignty_agricultural_rights_index: 7.65, last_updated: "2026-06-21" },
    { id: "FSAR-003", name: "Zambie/Monsanto Semences OGM Dépendance Totale Maïs", country: "Afrique Australe", sector: "Monsanto DK Maïs OGM 80% Marché Zambie, Semences Paysannes Illégales, Accord PGS Monsanto, Petits Agriculteurs Endettés & Bayer-Monsanto Fusion Monopole", composite_score: 74.9, land_grabbing_smallholder_displacement_score: 72.0, corporate_seed_monopoly_farmer_dependency_score: 86.0, food_import_dependency_price_shock_vulnerability_score: 68.0, traditional_farming_knowledge_erosion_score: 74.0, risk_level: "critique", primary_pattern: "monopole_semences_dependance_corporative", key_signals: ["Crise agricole critique de Zambie/Monsanto Semences OGM Dépendance Totale Maïs — accaparement des terres et/ou monopole semencier créant des conditions de dépendance et de vulnérabilité alimentaire systémique pour des millions d'agriculteurs", "Violation du droit à l'alimentation — l'article 11 du PIDESC est directement menacé par la concentration corporative des ressources agricoles et l'élimination des systèmes alimentaires paysans traditionnels", "Spirale de la dette agricole — les dépendances aux intrants industriels (semences, pesticides, engrais) génèrent des cycles de dette insurmontables poussant des centaines de milliers d'agriculteurs à la ruine et au suicide"], estimated_food_sovereignty_agricultural_rights_index: 7.49, last_updated: "2026-06-21" },
    { id: "FSAR-004", name: "Brésil/Déforestation Amazonie Soja Agrobusiness Cerrado", country: "Amérique du Sud", sector: "13.000 Km2/An Amazonie Déforestation, Soja Cerrado Expansion, Grilagem Accaparement Terres Autochtones, Quilombolas Expulsés & Bolsonaro FUNAI Démantèlement", composite_score: 67.15, land_grabbing_smallholder_displacement_score: 80.0, corporate_seed_monopoly_farmer_dependency_score: 68.0, food_import_dependency_price_shock_vulnerability_score: 55.0, traditional_farming_knowledge_erosion_score: 62.0, risk_level: "critique", primary_pattern: "accaparement_terres_deplacementpaysans", key_signals: ["Crise agricole critique de Brésil/Déforestation Amazonie Soja Agrobusiness Cerrado — accaparement des terres et/ou monopole semencier créant des conditions de dépendance et de vulnérabilité alimentaire systémique pour des millions d'agriculteurs", "Violation du droit à l'alimentation — l'article 11 du PIDESC est directement menacé par la concentration corporative des ressources agricoles et l'élimination des systèmes alimentaires paysans traditionnels", "Spirale de la dette agricole — les dépendances aux intrants industriels (semences, pesticides, engrais) génèrent des cycles de dette insurmontables poussant des centaines de milliers d'agriculteurs à la ruine et au suicide"], estimated_food_sovereignty_agricultural_rights_index: 6.72, last_updated: "2026-06-21" },
    { id: "FSAR-005", name: "Philippines/Dépendance Agro-industrielle Riz Importé WTO", country: "Asie du Sud-Est", sector: "Accords WTO Libéralisation Riz, Tarifficação 2019, Agriculteurs Locaux Concurrence Importations, CARP Réforme Agraire Inachevée & IRRI Semences Hybrides Dépendance", composite_score: 55.9, land_grabbing_smallholder_displacement_score: 52.0, corporate_seed_monopoly_farmer_dependency_score: 56.0, food_import_dependency_price_shock_vulnerability_score: 62.0, traditional_farming_knowledge_erosion_score: 54.0, risk_level: "élevé", primary_pattern: "dependance_alimentaire_chocs_prix", key_signals: ["Vulnérabilité structurelle agricole de Philippines/Dépendance Agro-industrielle Riz Importé WTO — dépendances économiques profondes vis-à-vis des marchés internationaux et des grandes corporations agro-industrielles réduisant la résilience alimentaire locale", "Érosion de la biodiversité agricole — la standardisation des semences industrielles réduit drastiquement la diversité génétique des cultures, fragilisant les écosystèmes et la capacité d'adaptation aux changements climatiques", "Déplacement des petits agriculteurs — la concurrence des importations subventionnées et des grandes exploitations industrielles expulse des millions de familles paysannes de leurs terres et de leurs moyens de subsistance"], estimated_food_sovereignty_agricultural_rights_index: 5.59, last_updated: "2026-06-21" },
    { id: "FSAR-006", name: "Haïti/Dépendance Importations Alimentaires 60% Post-Tremblement de Terre", country: "Caraïbes", sector: "60% Alimentation Importée, Riz USA Dumping Détruit Agriculture Locale, Tremblements de Terre 2010+2021, Aide Alimentaire Dépendance & Semences Hybrides Don Monsanto Refusé", composite_score: 58.9, land_grabbing_smallholder_displacement_score: 46.0, corporate_seed_monopoly_farmer_dependency_score: 52.0, food_import_dependency_price_shock_vulnerability_score: 82.0, traditional_farming_knowledge_erosion_score: 58.0, risk_level: "élevé", primary_pattern: "dependance_alimentaire_chocs_prix", key_signals: ["Vulnérabilité structurelle agricole de Haïti/Dépendance Importations Alimentaires 60% Post-Tremblement de Terre — dépendances économiques profondes vis-à-vis des marchés internationaux et des grandes corporations agro-industrielles réduisant la résilience alimentaire locale", "Érosion de la biodiversité agricole — la standardisation des semences industrielles réduit drastiquement la diversité génétique des cultures, fragilisant les écosystèmes et la capacité d'adaptation aux changements climatiques", "Déplacement des petits agriculteurs — la concurrence des importations subventionnées et des grandes exploitations industrielles expulse des millions de familles paysannes de leurs terres et de leurs moyens de subsistance"], estimated_food_sovereignty_agricultural_rights_index: 5.89, last_updated: "2026-06-21" },
    { id: "FSAR-007", name: "Mexique/ALENA Maïs Natif Menacé Importations USA", country: "Amérique du Nord", sector: "59 Variétés Maïs Natif Menacées, ALENA Maïs USA Dumping, Milpa Système Traditionnel Déclin, Décret OGM Maïs 2023 Annulé Pression USA & 4M Agriculteurs Déplacés ALENA", composite_score: 37.4, land_grabbing_smallholder_displacement_score: 32.0, corporate_seed_monopoly_farmer_dependency_score: 36.0, food_import_dependency_price_shock_vulnerability_score: 40.0, traditional_farming_knowledge_erosion_score: 44.0, risk_level: "modéré", primary_pattern: "erosion_savoirs_traditionnels", key_signals: ["Pressions agricoles modérées de Mexique/ALENA Maïs Natif Menacé Importations USA — tensions entre modèle agro-industriel et souveraineté alimentaire locale avec solutions partielles insuffisantes pour protéger les droits des agriculteurs", "Risques de monopolisation progressive — la concentration du secteur semencier et de la distribution alimentaire crée des dépendances croissantes sans législation antitrust adaptée", "Savoirs traditionnels menacés — les pratiques agricoles ancestrales et les variétés locales s'érodent sous la pression des modèles d'agriculture intensive sans programme de préservation adéquat"], estimated_food_sovereignty_agricultural_rights_index: 3.74, last_updated: "2026-06-21" },
    { id: "FSAR-008", name: "Via Campesina ONU Traité Ressources Phytogénétiques", country: "Global", sector: "Via Campesina 182 Organisations 81 Pays, Traité FAO Ressources Phytogénétiques 2004, UPOV-CBD Équilibre Semences Paysannes, Agroécologie Transition Soutenue & Rapporteur Spécial Droit Alimentation", composite_score: 9.5, land_grabbing_smallholder_displacement_score: 8.0, corporate_seed_monopoly_farmer_dependency_score: 10.0, food_import_dependency_price_shock_vulnerability_score: 12.0, traditional_farming_knowledge_erosion_score: 8.0, risk_level: "faible", primary_pattern: "souverainete_alimentaire_exemplaire", key_signals: ["Via Campesina ONU Traité Ressources Phytogénétiques incarne la souveraineté alimentaire exemplaire — diversité des systèmes agricoles, protection des semences paysannes et accès sécurisé à la terre pour les petits agriculteurs", "Droits des agriculteurs respectés — traité FAO sur les ressources phytogénétiques appliqué, banques de semences communautaires financées et pratiques agroécologiques soutenues", "Modèle résilient exportable — politiques alimentaires locales protectrices, marchés de proximité développés et programmes de soutien à l'agriculture paysanne durables"], estimated_food_sovereignty_agricultural_rights_index: 0.95, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { accaparement_terres_deplacementpaysans: 2, monopole_semences_dependance_corporative: 2, dependance_alimentaire_chocs_prix: 2, erosion_savoirs_traditionnels: 1, souverainete_alimentaire_exemplaire: 1 },
    top_risk_entities: ["Inde/Suicides Agriculteurs Dettes Bt Cotton Monsanto 300K Morts", "Éthiopie/Accaparement Terres 3.6M Hectares Investisseurs Étrangers", "Zambie/Monsanto Semences OGM Dépendance Totale Maïs", "Brésil/Déforestation Amazonie Soja Agrobusiness Cerrado"],
    critical_alerts: ["Inde/Monsanto: monopole semences dependance corporative", "Éthiopie: accaparement terres deplacement paysans", "Zambie/Monsanto: monopole semences dependance corporative", "Brésil/Amazonie: accaparement terres deplacement paysans"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "food_sovereignty_agricultural_rights",
    confidence_score: 0.85,
    data_sources: ["fao_treaty_plant_genetic_resources_2004", "oakland_institute_land_grab_reports", "grain_org_landgrabbing_database_2023", "via_campesina_food_sovereignty_reports"],
    entities,
    avg_estimated_food_sovereignty_agricultural_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
