import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[racial-justice-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Racial Justice Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/racial-justice-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Racial Justice Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Racial Justice Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "RJ-001", name: "USA/Noir·es — Wealth Gap 8:1, Police Violence 3× & Mass Incarceration 13% Pop 33% Prison", country: "Amérique du Nord", sector: "USA Richesse Médiane Blancs/Noirs 8:1 Fed Reserve, Police Violence Afro-Américains 3× Blancs, Mass Incarceration 13% Population 33% Prisonniers & Redlining Héritage Historique", composite_score: 90.10, systemic_discrimination_score: 92.0, racial_profiling_police_score: 90.0, wealth_education_gap_score: 92.0, hate_speech_ideology_score: 85.0, risk_level: "critique", primary_pattern: "discrimination_systemique", key_signals: ["Injustice raciale systémique documentée — USA/Noir·es — Wealth Gap 8:1, Police Violence 3× & Mass Incarceration 13% Pop 33% Prison avec score composite 90.1/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (92.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 9.01, last_updated: "2026-06-20" },
    { entity_id: "RJ-002", name: "Brésil/Racisme Structurel — 55% Noirs/Métis, Favelas Ciblées & Violência Policial", country: "Amérique Latine", sector: "Brésil 55% Noirs/Métis 75% Victimes Violence, Favelas Ciblées Police BOPE, Racisme Structurel Emploi/Éducation, 80% Tués Police Noirs & Statut Social Apartheid Silencieux", composite_score: 87.65, systemic_discrimination_score: 88.0, racial_profiling_police_score: 92.0, wealth_education_gap_score: 85.0, hate_speech_ideology_score: 85.0, risk_level: "critique", primary_pattern: "profilage_racial_police", key_signals: ["Injustice raciale systémique documentée — Brésil/Racisme Structurel — 55% Noirs/Métis, Favelas Ciblées & Violência Policial avec score composite 87.65/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (88.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "RJ-003", name: "Europe/Roms — 10-12M Apatrides, Discrimination Emploi/Logement & Antigypsyisme Institutionnel", country: "Europe", sector: "10-12M Roms Europe Discrimination Emploi 90%, Logement Ségrégué, Antigypsyisme Institutionnel Reconnu ECRI, Stérilisations Forcées Tchéquie/Slovaquie & Enfants Surreprésentés Écoles Spéciales", composite_score: 85.00, systemic_discrimination_score: 85.0, racial_profiling_police_score: 82.0, wealth_education_gap_score: 88.0, hate_speech_ideology_score: 85.0, risk_level: "critique", primary_pattern: "inegalite_richesse_education", key_signals: ["Injustice raciale systémique documentée — Europe/Roms — 10-12M Apatrides, Discrimination Emploi/Logement & Antigypsyisme Institutionnel avec score composite 85.0/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (85.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 8.50, last_updated: "2026-06-20" },
    { entity_id: "RJ-004", name: "Inde/Castes-Dalits — 200M Dalits, Intouchabilité Pratique & Atrocités 50 000/An", country: "Asie du Sud", sector: "Inde 200M Dalits Discrimination Caste Emploi/Mariage/Temple, Atrocités NCRB 50 000/An, Manuels Égout Éboueurs Force & Caste Système Légalement Aboli Pratiquement Vivant", composite_score: 85.75, systemic_discrimination_score: 88.0, racial_profiling_police_score: 82.0, wealth_education_gap_score: 85.0, hate_speech_ideology_score: 88.0, risk_level: "critique", primary_pattern: "discrimination_systemique", key_signals: ["Injustice raciale systémique documentée — Inde/Castes-Dalits — 200M Dalits, Intouchabilité Pratique & Atrocités 50 000/An avec score composite 85.75/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (88.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 8.58, last_updated: "2026-06-20" },
    { entity_id: "RJ-005", name: "Israel/Arabes Israéliens — Loi Nation-État 2018, Inégalités & Discrimination Budgétaire", country: "MENA", sector: "Israël Loi Nation-État 2018 Citoyens Arabes 20% Citoyens Secondaires, Budgets Municipaux Arabes -40% Juifs, Discrimination Emploi Sécurité & Ou-Bem Rapports Inégalités Systémiques", composite_score: 55.40, systemic_discrimination_score: 55.0, racial_profiling_police_score: 52.0, wealth_education_gap_score: 62.0, hate_speech_ideology_score: 52.0, risk_level: "élevé", primary_pattern: "inegalite_richesse_education", key_signals: ["Injustice raciale systémique documentée — Israel/Arabes Israéliens — Loi Nation-État 2018, Inégalités & Discrimination Budgétaire avec score composite 55.4/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (55.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 5.54, last_updated: "2026-06-20" },
    { entity_id: "RJ-006", name: "France/Discrimination — Profiling Racial Police, Banlieues & CV Anonyme Refus", country: "Europe de l'Ouest", sector: "France Testing Discrimination 3× Moins Rappels CV Arabes/Africains, Contrôles Identité Profiling Racial CNRS, Banlieues IZI Sous-Financement & ECRI Rapport France Profiling 2022", composite_score: 52.50, systemic_discrimination_score: 50.0, racial_profiling_police_score: 58.0, wealth_education_gap_score: 52.0, hate_speech_ideology_score: 50.0, risk_level: "élevé", primary_pattern: "profilage_racial_police", key_signals: ["Injustice raciale systémique documentée — France/Discrimination — Profiling Racial Police, Banlieues & CV Anonyme Refus avec score composite 52.5/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (50.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 5.25, last_updated: "2026-06-20" },
    { entity_id: "RJ-007", name: "Allemagne/Néo-Nazis — NSU Meurtres 10 Victimes, AFD Xénophobie & Rechtsextremismus", country: "Europe de l'Ouest", sector: "Allemagne NSU Meurtres 10 Victimes Turques Grecques, AFD Partis Extrême Droite 20%+, Rechtsextremismus Violence +50% 2021-23 BfV & ECRI Recommandations Non-Appliquées", composite_score: 30.90, systemic_discrimination_score: 28.0, racial_profiling_police_score: 30.0, wealth_education_gap_score: 32.0, hate_speech_ideology_score: 35.0, risk_level: "modéré", primary_pattern: "discours_haine_ideologie", key_signals: ["Injustice raciale systémique documentée — Allemagne/Néo-Nazis — NSU Meurtres 10 Victimes, AFD Xénophobie & Rechtsextremismus avec score composite 30.9/100 révélant des discriminations structurelles violant l'Article 2 de la DUDH, l'Article 26 du PIDCP et la Convention Internationale sur l'Élimination de Toutes les Formes de Discrimination Raciale (CERD 1965)", "Discrimination systémique (28.0/100) — les inégalités raciales institutionnalisées constituent des violations directes de la CERD obligeant les États à prendre des mesures spéciales immédiates pour remédier aux discriminations historiques et actuelles", "Activer le Comité pour l'Élimination de la Discrimination Raciale (CERD) pour examen des rapports périodiques et exiger la mise en œuvre du Programme d'action de Durban III (2021) sur l'élimination du racisme et de la discrimination raciale"], estimated_racial_justice_index: 3.09, last_updated: "2026-06-20" },
    { entity_id: "RJ-008", name: "CERD-ONU/Durban — Convention 1965, Programme Durban III & Rapporteur Spécial Racisme", country: "Global", sector: "CERD Convention 1965 182 États Parties, Programme d'Action Durban III 2021, Rapporteur Spécial ONU Racisme Contemporain & Décennie ONU Personnes Afro-Descendantes 2015-24", composite_score: 4.45, systemic_discrimination_score: 5.0, racial_profiling_police_score: 4.0, wealth_education_gap_score: 3.0, hate_speech_ideology_score: 6.0, risk_level: "faible", primary_pattern: "discours_haine_ideologie", key_signals: ["CERD-ONU/Durban incarne le cadre normatif exemplaire de lutte contre la discrimination raciale — Convention de 1965 et Programme d'Action de Durban créant des obligations contraignantes d'élimination de toutes les formes de discrimination raciale pour les 182 États parties", "Convention CERD Article 2 — impose aux États de prendre des mesures législatives, judiciaires et administratives pour éliminer la discrimination raciale et adopter des mesures spéciales en faveur des groupes raciaux ou ethniques sous-représentés", "Universaliser la ratification de la CERD et renforcer le Programme d'Action de Durban III avec mécanismes de financement dédiés à la lutte contre le racisme systémique et institutionnel dans les systèmes judiciaires, éducatifs et économiques"], estimated_racial_justice_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { discrimination_systemique: 2, profilage_racial_police: 2, inegalite_richesse_education: 2, discours_haine_ideologie: 2 },
    top_risk_entities: ["USA/Noir·es — Wealth Gap 8:1, Police Violence 3× & Mass Incarceration 13% Pop 33% Prison", "Brésil/Racisme Structurel — 55% Noirs/Métis, Favelas Ciblées & Violência Policial", "Inde/Castes-Dalits — 200M Dalits, Intouchabilité Pratique & Atrocités 50 000/An"],
    critical_alerts: ["USA/Noir·es: discrimination systémique", "Brésil/Racisme Structurel: profilage racial police", "Europe/Roms: inégalité richesse éducation", "Inde/Castes-Dalits: discrimination systémique"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "racial_justice",
    confidence_score: 0.83,
    data_sources: ["cerd_committee_concluding_observations_database", "un_special_rapporteur_racism_racial_discrimination_reports", "ecri_country_monitoring_reports_european_racism"],
    entities,
    avg_estimated_racial_justice_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
