import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[statelessness-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Statelessness Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/statelessness-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Statelessness Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Statelessness Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { entity_id: "SL-001", name: "Myanmar/Rohingya — Loi Citoyenneté 1982, 600 000 Apatrides & Génocide Documenté ONU", country: "Asie du Sud-Est", sector: "Loi Citoyenneté Myanmar 1982 Exclusion Rohingya, 600 000 Apatrides Rakhine, Opération Militaire 2017 Épuration & Registre Naissance Refusé Générations", composite_score: 91.6, denationalization_rate_score: 95.0, birth_registration_denial_score: 92.0, stateless_detention_risk_score: 90.0, documentation_access_failure_score: 88.0, risk_level: "critique", primary_pattern: "denationalisation_massive", key_signals: ["Dénationalisation massive au Myanmar/Rohingya — loi de citoyenneté de 1982 excluant délibérément les Rohingya de la nationalité birmane, créant 600 000 apatrides dans l'État Rakhine privés de tout document d'identité", "Droit fondamental violé — la nationalité est un droit humain fondamental selon l'Article 15 de la DUDH, et la dénationalisation ethnique constitue un élément du crime de génocide selon la Convention de 1948", "Activer la Convention de 1954 sur les apatrides et la Convention de 1961 sur la réduction de l'apatridie pour exiger la reconnaissance de la nationalité rohingya par le Myanmar"], estimated_statelessness_index: 9.16, last_updated: "2026-06-20" },
    { entity_id: "SL-002", name: "Golfe Arabe/Bidun — 100 000+ Apatrides 2e Génération Koweït/EAU & Documents Refusés", country: "MENA", sector: "Bidun Kuwait 100 000+ Sans Nationalité, EAU Bidun 10 000 Apatrides, Né au Golfe Mais Refus Documentation & Generations Sans Identité Légale", composite_score: 87.75, denationalization_rate_score: 88.0, birth_registration_denial_score: 85.0, stateless_detention_risk_score: 90.0, documentation_access_failure_score: 88.0, risk_level: "critique", primary_pattern: "echec_documentation_acces", key_signals: ["Échec d'accès aux documents d'identité Golfe/Bidun — 100 000+ Bidun au Koweït et aux EAU nés dans ces pays mais refusant tout accès à la nationalité ou aux documents malgré des générations de résidence", "Droit fondamental violé — l'absence de documents d'identité prive les Bidun de l'accès aux soins, à l'éducation, à l'emploi et à la justice, constituant une violation systémique de la DUDH Article 15", "Activer le Rapporteur Spécial ONU sur les droits des migrants et exiger des États du Golfe la mise en place de voies d'accès à la nationalité pour les Bidun conformément à la Convention de 1954"], estimated_statelessness_index: 8.77, last_updated: "2026-06-20" },
    { entity_id: "SL-003", name: "RPDC/Réfugiés — Diaspora Apatride Chine, Détention Sans Statut & Refoulement Forcé", country: "Asie du Nord-Est", sector: "Réfugiés RPDC Chine 100 000+ Sans Statut Légal, Détention Chine Sans UNHCR Accès, Refoulement Forcé Corée Nord & Persécution Retour Documentée", composite_score: 86.35, denationalization_rate_score: 82.0, birth_registration_denial_score: 95.0, stateless_detention_risk_score: 88.0, documentation_access_failure_score: 80.0, risk_level: "critique", primary_pattern: "detention_apatrides", key_signals: ["Détention d'apatrides de fait en RPDC/Chine — 100 000+ réfugiés nord-coréens en Chine refusés par le système de protection internationale et détenus sans accès au HCR, soumis à refoulement forcé vers la RPDC", "Violation du principe de non-refoulement — la Chine viole la Convention de 1951 sur les réfugiés en refoulant des Nord-Coréens vers un pays où ils font face à torture, emprisonnement et exécution", "Exiger de la Chine l'accès du HCR aux réfugiés nord-coréens et la cessation des refoulements forcés violant le droit international des réfugiés"], estimated_statelessness_index: 8.63, last_updated: "2026-06-20" },
    { entity_id: "SL-004", name: "Côte d'Ivoire/Dioula — Dénationalisation 700 000 & Crise Nationalité Post-Ivoirité", country: "Afrique de l'Ouest", sector: "Ivoirité Politique Exclusion 700 000 Personnes, Dioula/Mandé Sans Documents Nationalité, Crise Post-Electorale 2010-11 Apatridie & Burkina/Mali Frontaliers Indocumentés", composite_score: 83.25, denationalization_rate_score: 85.0, birth_registration_denial_score: 82.0, stateless_detention_risk_score: 85.0, documentation_access_failure_score: 80.0, risk_level: "critique", primary_pattern: "denationalisation_massive", key_signals: ["Dénationalisation massive en Côte d'Ivoire/Dioula — concept d'Ivoirité utilisé pour priver 700 000 personnes d'origine mandé de leur nationalité ivoirienne, créant une apatridie politique documentée par le HCR", "Droit fondamental violé — la dénationalisation politique viole l'Article 15 de la DUDH et la Charte Africaine des Droits de l'Homme, créant une exclusion civique de populations résidant depuis des générations", "Activer la Commission Africaine des Droits de l'Homme pour examiner la politique d'Ivoirité et exiger la mise en place d'un processus de documentation accessible pour toutes les personnes résidant en Côte d'Ivoire"], estimated_statelessness_index: 8.32, last_updated: "2026-06-20" },
    { entity_id: "SL-005", name: "Thaïlande/Peuples des Montagnes — 480 000 Hill Tribes Sans Citoyenneté & Naissance Non-Enregistrée", country: "Asie du Sud-Est", sector: "480 000 Hill Tribes Thaïlande Sans Citoyenneté, Karen/Hmong/Akha Naissance Non-Enregistrée, Accès Soins/Education Refusé & Statut Illégal Permanent", composite_score: 55.0, denationalization_rate_score: 55.0, birth_registration_denial_score: 58.0, stateless_detention_risk_score: 52.0, documentation_access_failure_score: 55.0, risk_level: "élevé", primary_pattern: "deni_enregistrement_naissance", key_signals: ["Déni d'enregistrement des naissances en Thaïlande/Hill Tribes — 480 000 membres des peuples des montagnes (Karen, Hmong, Akha) nés en Thaïlande mais non enregistrés, créant une apatridie héréditaire de facto", "Droit fondamental violé — le droit à l'enregistrement de la naissance et à une nationalité est garanti par l'Article 7 de la Convention des Droits de l'Enfant, dont la Thaïlande est signataire", "Accélérer les programmes de documentation des Hill Tribes en Thaïlande et mettre en œuvre le Plan d'Action Global de l'IBelong-HCR pour l'éradication de l'apatridie d'ici 2024"], estimated_statelessness_index: 5.5, last_updated: "2026-06-20" },
    { entity_id: "SL-006", name: "Kirghizistan/Ethnies — Ex-URSS Apatrides, Dissolution Soviétique & Documents Non-Transférés", country: "Asie Centrale", sector: "Ex-URSS Dissolution Apatridie 100 000+ Personnes Kirghizistan/Tadjikistan, Documents Soviétiques Non-Transférés, Ethnies Minoritaires Indocumentées & HCR Campagne Active", composite_score: 53.45, denationalization_rate_score: 52.0, birth_registration_denial_score: 55.0, stateless_detention_risk_score: 50.0, documentation_access_failure_score: 58.0, risk_level: "élevé", primary_pattern: "deni_enregistrement_naissance", key_signals: ["Déni d'enregistrement en Kirghizistan — héritage de la dissolution soviétique laissant 100 000+ personnes sans documents de nationalité valides, principalement des minorités ethniques dont les naissances n'ont jamais été correctement transférées", "Lacune institutionnelle post-soviétique — l'absence de procédures claires de succession d'État pour les ressortissants des ex-républiques soviétiques a créé une apatridie structurelle violant l'Article 15 de la DUDH", "Soutenir les campagnes HCR d'enregistrement rétroactif en Asie Centrale et exiger des États successeurs de l'URSS des procédures simplifiées de naturalisation pour les personnes apatrides de facto"], estimated_statelessness_index: 5.34, last_updated: "2026-06-20" },
    { entity_id: "SL-007", name: "Lettonie/Estonie — 'Non-Citoyens' Russophones, 200 000 Statut Spécial & Droits Limités", country: "Europe", sector: "Lettonie 200 000 Non-Citoyens Russophones, Estonie Apatrides Soviétiques, Passeport Alien Non-Citoyen & Vote Municipal Refusé UE Discrimination", composite_score: 29.3, denationalization_rate_score: 28.0, birth_registration_denial_score: 30.0, stateless_detention_risk_score: 28.0, documentation_access_failure_score: 32.0, risk_level: "modéré", primary_pattern: "echec_documentation_acces", key_signals: ["Échec partiel d'accès aux droits en Lettonie/Estonie — 200 000 russophones de Lettonie détenant un statut de 'non-citoyen' les privant du droit de vote aux élections législatives et limitant leur mobilité intra-UE", "Discrimination institutionnelle — le statut de non-citoyen crée une catégorie de résidents de longue durée aux droits réduits, soulevant des questions de compatibilité avec les standards européens des droits humains", "Accélérer les procédures de naturalisation simplifiée pour les non-citoyens de Lettonie et d'Estonie et activer les mécanismes du Conseil de l'Europe pour surveiller la conformité avec les standards européens"], estimated_statelessness_index: 2.93, last_updated: "2026-06-20" },
    { entity_id: "SL-008", name: "HCR/IBelong — Campagne Éradication Apatridie 2014-2024 & Conventions Protectrices", country: "Global", sector: "HCR IBelong Campaign 10 Ans 2014-2024, Convention Apatrides 1954 97 États, Convention Réduction Apatridie 1961 & Plan d'Action Global 8 Mesures", composite_score: 4.45, denationalization_rate_score: 5.0, birth_registration_denial_score: 4.0, stateless_detention_risk_score: 3.0, documentation_access_failure_score: 6.0, risk_level: "faible", primary_pattern: "deni_enregistrement_naissance", key_signals: ["HCR/IBelong incarne la protection exemplaire contre l'apatridie — campagne IBelong visant l'éradication de l'apatridie d'ici 2024 avec 8 actions prioritaires et conventions de 1954 et 1961 créant un cadre contraignant", "Convention de 1954 sur le statut des apatrides — définit les droits des apatrides et oblige les États parties à leur garantir documents de voyage, accès au travail et à l'éducation", "Universaliser la ratification des Conventions de 1954 et 1961 sur l'apatridie et financer les campagnes d'enregistrement civil dans les pays à forte prévalence d'apatridie"], estimated_statelessness_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { denationalisation_massive: 2, echec_documentation_acces: 2, detention_apatrides: 1, deni_enregistrement_naissance: 3 },
    top_risk_entities: ["Myanmar/Rohingya — Loi Citoyenneté 1982, 600 000 Apatrides & Génocide Documenté ONU", "Golfe Arabe/Bidun — 100 000+ Apatrides 2e Génération Koweït/EAU & Documents Refusés", "RPDC/Réfugiés — Diaspora Apatride Chine, Détention Sans Statut & Refoulement Forcé"],
    critical_alerts: ["Myanmar/Rohingya: dénationalisation massive", "Golfe Arabe/Bidun: échec documentation accès", "RPDC/Réfugiés: détention apatrides", "Côte d'Ivoire/Dioula: dénationalisation massive"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "statelessness",
    confidence_score: 0.84,
    data_sources: ["unhcr_global_trends_statelessness_report", "institute_statelessness_and_inclusion_database", "ibelong_unhcr_campaign_data"],
    entities,
    avg_estimated_statelessness_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
