import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[child-labor-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(sealResponse(getMockData(), "Child Labor Engine Agent"));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/child-labor-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(sealResponse(data, "Child Labor Engine Agent"));
  } catch {
    return NextResponse.json(sealResponse(getMockData(), "Child Labor Engine Agent"), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "CL-001", name: "Mali/Mines d'Or — 200 000 Enfants Artisanaux, Mercure/Cyanure & Décès Documentés", country: "Afrique de l'Ouest", sector: "200 000 Enfants Mines Artisanales Or Mali, Exposition Mercure/Cyanure Documentée HRW, Décès Et Blessures Carrières & Exportation Or Chaîne Approvisionnement Non-Tracée", composite_score: 88.95, hazardous_child_labor_rate_score: 92.0, forced_labor_recruitment_score: 85.0, school_access_deprivation_score: 90.0, regulatory_enforcement_failure_score: 88.0, risk_level: "critique", primary_pattern: "travail_dangereux_enfants", key_signals: ["Exploitation économique infantile documentée — Mali/Mines d'Or avec score composite 88.95/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (90.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 8.9, last_updated: "2026-06-20" },
    { id: "CL-002", name: "RDC/Cobalt — 40 000 Enfants Mines Kasaï, Tesla/Apple Supply Chain & Zéro Sanction", country: "Afrique Centrale", sector: "40 000 Enfants Mines Cobalt Artisanales Kasaï/Katanga, Blessures Éboulements Documentées Amnesty, Batteries Électriques Tesla/Apple & Due Diligence Marques Insuffisante", composite_score: 88.25, hazardous_child_labor_rate_score: 90.0, forced_labor_recruitment_score: 88.0, school_access_deprivation_score: 85.0, regulatory_enforcement_failure_score: 90.0, risk_level: "critique", primary_pattern: "travail_dangereux_enfants", key_signals: ["Exploitation économique infantile documentée — RDC/Cobalt avec score composite 88.25/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (85.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 8.83, last_updated: "2026-06-20" },
    { id: "CL-003", name: "Bangladesh/Garment — 4.8M Enfants Travailleurs, Rana Plaza & Travail Nocturne", country: "Asie du Sud", sector: "4.8M Enfants Travailleurs Bangladesh, Rana Plaza 2013 1134 Morts Dont Enfants, Garment Secteur Travail Nocturne Illegal & Accord Bangladesh 2013 Progrès Limités", composite_score: 86.65, hazardous_child_labor_rate_score: 88.0, forced_labor_recruitment_score: 85.0, school_access_deprivation_score: 88.0, regulatory_enforcement_failure_score: 85.0, risk_level: "critique", primary_pattern: "travail_dangereux_enfants", key_signals: ["Exploitation économique infantile documentée — Bangladesh/Garment avec score composite 86.65/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (88.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 8.67, last_updated: "2026-06-20" },
    { id: "CL-004", name: "Inde/Travail Bonded — 5.8M Enfants, Briqueteries Bihar & Servitude Héréditaire", country: "Asie du Sud", sector: "5.8M Enfants Travailleurs Inde Officiels, Briqueteries Bihar Travail Bonded Familial, Kamaiya/Haliya Servitude Héréditaire & Child Labour Act 2016 Application Insuffisante", composite_score: 85.5, hazardous_child_labor_rate_score: 85.0, forced_labor_recruitment_score: 90.0, school_access_deprivation_score: 82.0, regulatory_enforcement_failure_score: 85.0, risk_level: "critique", primary_pattern: "recrutement_force_mineur", key_signals: ["Exploitation économique infantile documentée — Inde/Travail Bonded avec score composite 85.5/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (82.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 8.55, last_updated: "2026-06-20" },
    { id: "CL-005", name: "Éthiopie/Plantations — 4M Enfants Agriculture Café/Thé, Travail Saisonnier Caché", country: "Afrique de l'Est", sector: "4M Enfants Travailleurs Éthiopie Agriculture, Plantations Café/Thé Travail Saisonnier, Exportation Café Éthiopien Starbucks/Nespresso & Audit Social Insuffisant", composite_score: 54.0, hazardous_child_labor_rate_score: 55.0, forced_labor_recruitment_score: 52.0, school_access_deprivation_score: 58.0, regulatory_enforcement_failure_score: 50.0, risk_level: "élevé", primary_pattern: "privation_acces_education", key_signals: ["Exploitation économique infantile documentée — Éthiopie/Plantations avec score composite 54.0/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (58.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 5.4, last_updated: "2026-06-20" },
    { id: "CL-006", name: "Brésil/Agrobusiness — Enfants Canne à Sucre/Soja, Travail Rural Informel Familial", country: "Amérique du Sud", sector: "Brésil 1.8M Enfants Travailleurs Rural, Canne à Sucre/Soja Enfants Travail Saisonnier, Travail Familial Légal Brésil <14 Ans & Dérogations Pire Formes", composite_score: 52.35, hazardous_child_labor_rate_score: 52.0, forced_labor_recruitment_score: 48.0, school_access_deprivation_score: 55.0, regulatory_enforcement_failure_score: 55.0, risk_level: "élevé", primary_pattern: "privation_acces_education", key_signals: ["Exploitation économique infantile documentée — Brésil/Agrobusiness avec score composite 52.35/100 révélant des conditions de travail dangereuses violant la Convention OIT 182 sur les pires formes de travail des enfants", "Privation d'éducation structurelle — le score d'accès à l'éducation (55.0/100) indique que le travail infantile prive les enfants de leur droit fondamental à l'éducation (Article 28 CRC)", "Activer les mécanismes OIT/IPEC pour inspection du travail renforcée et soutenir Alliance 8.7 pour élimination pires formes travail enfants d'ici 2025 conformément à l'ODD 8.7"], estimated_child_labor_index: 5.24, last_updated: "2026-06-20" },
    { id: "CL-007", name: "Mexique/Travail Agricole Saisonnier — Légumes/Fraises Exportation & Mineurs Documentés", country: "Amérique du Nord", sector: "Mexique Enfants Champs Agricoles Légaux Via Exception Familiale, Fraises/Tomates Export USA, Enquête NYT 2023 & USMCA Clauses Travail Enfants Insuffisantes", composite_score: 29.6, hazardous_child_labor_rate_score: 30.0, forced_labor_recruitment_score: 28.0, school_access_deprivation_score: 32.0, regulatory_enforcement_failure_score: 28.0, risk_level: "modéré", primary_pattern: "privation_acces_education", key_signals: ["Exploitation économique infantile documentée — Mexique/Travail Agricole avec score composite 29.6/100 révélant des lacunes dans la protection des mineurs travailleurs saisonniers agricoles", "Lacune réglementaire USMCA — les exceptions au travail familial dans l'agriculture mexicaine permettent des pratiques de travail infantile légalement tolérées violant l'esprit de la Convention OIT 138", "Renforcer les clauses travail des enfants dans l'USMCA et exiger du Mexique des inspections du travail agricole incluant la détection systématique du travail infantile saisonnier"], estimated_child_labor_index: 2.96, last_updated: "2026-06-20" },
    { id: "CL-008", name: "OIT/Alliance 8.7 — Convention 182, SDG 8.7 Élimination & IPEC Programme", country: "Global", sector: "OIT Convention 182 Pires Formes Travail Enfants Ratifiée 187 États, Alliance 8.7 ODD Élimination 2025, IPEC Programme International & Rapport Mondial Travail Enfants 2022", composite_score: 4.45, hazardous_child_labor_rate_score: 5.0, forced_labor_recruitment_score: 4.0, school_access_deprivation_score: 3.0, regulatory_enforcement_failure_score: 6.0, risk_level: "faible", primary_pattern: "defaillance_application_loi", key_signals: ["OIT/Alliance 8.7 incarne la protection exemplaire contre le travail des enfants — Convention 182 ratifiée universellement par 187 États et programme IPEC créant un cadre mondial d'élimination", "Convention OIT 182 (1999) — définit les pires formes de travail des enfants (esclavage, prostitution, travail dangereux) avec obligation d'action immédiate et mécanismes de suivi nationaux", "Universaliser l'application de la Convention OIT 138 (âge minimum) et 182 (pires formes) et financer les programmes IPEC d'inspection du travail et de réinsertion scolaire dans les pays à haute prévalence"], estimated_child_labor_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { travail_dangereux_enfants: 3, recrutement_force_mineur: 1, privation_acces_education: 3, defaillance_application_loi: 1 },
    top_risk_entities: ["Mali/Mines d'Or — 200 000 Enfants Artisanaux, Mercure/Cyanure & Décès Documentés", "RDC/Cobalt — 40 000 Enfants Mines Kasaï, Tesla/Apple Supply Chain & Zéro Sanction", "Bangladesh/Garment — 4.8M Enfants Travailleurs, Rana Plaza & Travail Nocturne"],
    critical_alerts: ["Mali/Mines d'Or: travail dangereux enfants", "RDC/Cobalt: travail dangereux enfants", "Bangladesh/Garment: travail dangereux enfants", "Inde/Travail Bonded: recrutement forcé mineur"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "child_labor",
    confidence_score: 0.85,
    data_sources: ["ilo_ipec_child_labour_global_estimates", "unicef_multiple_indicator_cluster_surveys", "us_dol_bureau_international_labor_affairs_reports"],
    entities,
    avg_estimated_child_labor_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
