import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[child-soldiers-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Child Soldiers Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/child-soldiers-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Child Soldiers Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Child Soldiers Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "CS-001", name: "LRA/Ouganda — Lord's Resistance Army & Enfants Otages Kony", country: "Afrique Centrale", sector: "30 000+ Enfants Recrutés Force, Atrocités Imposées, CPI Mandat Kony 2005 & Financement Réseaux Criminels", composite_score: 88.95, forced_child_recruitment_score: 92.0, child_combat_deployment_score: 90.0, state_armed_group_complicity_score: 85.0, child_soldier_impunity_score: 88.0, risk_level: "critique", primary_pattern: "recrutement_force_enfants", key_signals: ["Recrutement d'enfants soldats critique de LRA/Ouganda — enfants enrôlés de force, contraints à combattre ou utilisés comme boucliers humains dans des violations graves du droit international humanitaire", "Crime de guerre documenté — le recrutement d'enfants de moins de 15 ans constitue un crime de guerre selon le Statut de Rome, avec responsabilité pénale individuelle des commandants", "Trauma générationnel irréversible — les enfants soldats subissent des traumatismes psychologiques profonds, des mutilations et une exclusion sociale à vie compromettant leur réintégration"], estimated_child_soldiers_index: 8.9, last_updated: "2026-06-20" },
    { id: "CS-002", name: "Myanmar/Tatmadaw — Armée Birmane & Coup d'État 2021", country: "Asie du Sud-Est", sector: "Listée ONU Recruteurs 2002, 7000+ Enfants Tatmadaw, Coup État 2021 Intensification & Groupes Ethniques Armés", composite_score: 83.9, forced_child_recruitment_score: 83.0, child_combat_deployment_score: 90.0, state_armed_group_complicity_score: 82.0, child_soldier_impunity_score: 80.0, risk_level: "critique", primary_pattern: "enfants_soldats_combattants", key_signals: ["Recrutement d'enfants soldats critique de Myanmar/Tatmadaw — enfants enrôlés de force, contraints à combattre ou utilisés comme boucliers humains dans des violations graves du droit international humanitaire", "Crime de guerre documenté — le recrutement d'enfants de moins de 15 ans constitue un crime de guerre selon le Statut de Rome, avec responsabilité pénale individuelle des commandants", "Trauma générationnel irréversible — les enfants soldats subissent des traumatismes psychologiques profonds, des mutilations et une exclusion sociale à vie compromettant leur réintégration"], estimated_child_soldiers_index: 8.39, last_updated: "2026-06-20" },
    { id: "CS-003", name: "Houthis/Yémen — 3500+ Enfants Soldats & Iran Proxy", country: "MENA", sector: "3500+ Enfants UNICEF 2023, Enfants <10 Ans Guetteurs, Iran Formation & Financement & ONU Liste Noire Persistante", composite_score: 81.65, forced_child_recruitment_score: 80.0, child_combat_deployment_score: 75.0, state_armed_group_complicity_score: 90.0, child_soldier_impunity_score: 82.0, risk_level: "critique", primary_pattern: "militarisation_enfants_proxy", key_signals: ["Recrutement d'enfants soldats critique de Houthis/Yémen — enfants enrôlés de force, contraints à combattre ou utilisés comme boucliers humains dans des violations graves du droit international humanitaire", "Crime de guerre documenté — le recrutement d'enfants de moins de 15 ans constitue un crime de guerre selon le Statut de Rome, avec responsabilité pénale individuelle des commandants", "Trauma générationnel irréversible — les enfants soldats subissent des traumatismes psychologiques profonds, des mutilations et une exclusion sociale à vie compromettant leur réintégration"], estimated_child_soldiers_index: 8.17, last_updated: "2026-06-20" },
    { id: "CS-004", name: "RDC/ADF/M23 — Congo Est & Multiples Groupes Armés", country: "Afrique Centrale", sector: "M23 Recrutement Force, ADF Enfants Boucliers, FARDC Implication Documentée & 15 000 Enfants Libérés 2023", composite_score: 81.5, forced_child_recruitment_score: 78.0, child_combat_deployment_score: 82.0, state_armed_group_complicity_score: 80.0, child_soldier_impunity_score: 88.0, risk_level: "critique", primary_pattern: "exploitation_enfants_guerre", key_signals: ["Recrutement d'enfants soldats critique de RDC/ADF/M23 — enfants enrôlés de force, contraints à combattre ou utilisés comme boucliers humains dans des violations graves du droit international humanitaire", "Crime de guerre documenté — le recrutement d'enfants de moins de 15 ans constitue un crime de guerre selon le Statut de Rome, avec responsabilité pénale individuelle des commandants", "Trauma générationnel irréversible — les enfants soldats subissent des traumatismes psychologiques profonds, des mutilations et une exclusion sociale à vie compromettant leur réintégration"], estimated_child_soldiers_index: 8.15, last_updated: "2026-06-20" },
    { id: "CS-005", name: "Nigéria/Boko Haram — ISWAP & Filles de Chibok Soldates", country: "Afrique de l'Ouest", sector: "Boko Haram Filles Soldates, ISWAP Kamikazes Enfants, Nord-Est 2200+ Enfants & Impunité Locale Élevée", composite_score: 56.4, forced_child_recruitment_score: 55.0, child_combat_deployment_score: 52.0, state_armed_group_complicity_score: 58.0, child_soldier_impunity_score: 62.0, risk_level: "élevé", primary_pattern: "exploitation_enfants_guerre", key_signals: ["Exploitation d'enfants dans les conflits de Nigéria/Boko Haram — utilisation de mineurs dans des rôles de soutien militaire avec risques d'escalade vers des rôles combattants directs", "Impunité des recruteurs — l'absence de poursuites judiciaires crée un effet d'aubaine pour les groupes armés qui continuent à cibler les enfants des communautés vulnérables", "Fragilité post-conflit — les enfants associés aux forces armées rencontrent des obstacles majeurs à la démobilisation, la réhabilitation et la réintégration communautaire"], estimated_child_soldiers_index: 5.64, last_updated: "2026-06-20" },
    { id: "CS-006", name: "Somalie/Al-Shabaab — Recrutement Écoles & Camps Réfugiés", country: "Afrique de l'Est", sector: "Al-Shabaab Recrutement Écoles Madrassas, 7000+ Enfants Documentés, Camps Dadaab Ciblés & Mogadiscio Attaques", composite_score: 52.95, forced_child_recruitment_score: 52.0, child_combat_deployment_score: 48.0, state_armed_group_complicity_score: 55.0, child_soldier_impunity_score: 58.0, risk_level: "élevé", primary_pattern: "exploitation_enfants_guerre", key_signals: ["Exploitation d'enfants dans les conflits de Somalie/Al-Shabaab — utilisation de mineurs dans des rôles de soutien militaire avec risques d'escalade vers des rôles combattants directs", "Impunité des recruteurs — l'absence de poursuites judiciaires crée un effet d'aubaine pour les groupes armés qui continuent à cibler les enfants des communautés vulnérables", "Fragilité post-conflit — les enfants associés aux forces armées rencontrent des obstacles majeurs à la démobilisation, la réhabilitation et la réintégration communautaire"], estimated_child_soldiers_index: 5.3, last_updated: "2026-06-20" },
    { id: "CS-007", name: "Colombie/FARC Résiduels — Dissidences & Mineurs Vulnérables", country: "Amérique du Sud", sector: "FARC Dissidences Post-Accord 2016, ELN Recrutement Communautés Indigènes, 30% Recrues Mineurs Estimés", composite_score: 29.65, forced_child_recruitment_score: 28.0, child_combat_deployment_score: 25.0, state_armed_group_complicity_score: 32.0, child_soldier_impunity_score: 35.0, risk_level: "modéré", primary_pattern: "exploitation_enfants_guerre", key_signals: ["Risque résiduel enfants soldats de Colombie/FARC Résiduels — incidents isolés ou passés sans stratégie active de recrutement institutionnalisée par les forces étatiques ou groupes armés", "Vulnérabilités structurelles — pauvreté, déplacement interne et absence de perspectives économiques rendent les enfants vulnérables au recrutement par des groupes armés", "Progrès fragiles — les acquis de la démobilisation peuvent être inversés par la résurgence de conflits armés ou la prolifération d'armes légères dans la région"], estimated_child_soldiers_index: 2.97, last_updated: "2026-06-20" },
    { id: "CS-008", name: "UNICEF/Principes Paris — Protection Internationale Enfants", country: "Global", sector: "Protocoles Facultatifs CRC 2000, Principes Paris 2007, Mécanismes Surveillance ONU & DDR Programmes 58 Pays", composite_score: 4.45, forced_child_recruitment_score: 5.0, child_combat_deployment_score: 4.0, state_armed_group_complicity_score: 3.0, child_soldier_impunity_score: 6.0, risk_level: "faible", primary_pattern: "protection_enfants_exemplaire", key_signals: ["UNICEF/Principes Paris incarne la protection exemplaire des enfants dans les conflits — respect effectif des Protocoles facultatifs à la CRC et mécanismes de vérification de l'âge dans les forces armées", "Standards de Paris appliqués — programme DDR (désarmement, démobilisation, réintégration) opérationnel avec soutien psychosocial et accès à l'éducation garantis", "Modèle de protection à exporter — financement UNICEF, formation des forces armées aux obligations CRC et coopération avec les mécanismes ONU de surveillance"], estimated_child_soldiers_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { recrutement_force_enfants: 1, enfants_soldats_combattants: 1, militarisation_enfants_proxy: 1, exploitation_enfants_guerre: 4, protection_enfants_exemplaire: 1 },
    top_risk_entities: ["LRA/Ouganda — Lord's Resistance Army & Enfants Otages Kony", "Myanmar/Tatmadaw — Armée Birmane & Coup d'État 2021", "Houthis/Yémen — 3500+ Enfants Soldats & Iran Proxy"],
    critical_alerts: ["LRA/Ouganda: recrutement forcé enfants", "Myanmar/Tatmadaw: enfants soldats combattants", "Houthis/Yémen: militarisation enfants proxy", "RDC/ADF/M23: exploitation enfants guerre"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "child_soldiers",
    confidence_score: 0.83,
    data_sources: ["unicef_children_armed_conflict_report", "un_secretary_general_children_war_annex", "child_soldiers_international_monitor"],
    entities,
    avg_estimated_child_soldiers_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
