import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[transnational-repression-engine] SWARM_API_URL non défini — mode mock activé");
}

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Transnational Repression Engine Agent")));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/transnational-repression-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`Upstream ${res.status}`);
    const data = await res.json();
    return sealResponse(NextResponse.json(sealResponse(data, "Transnational Repression Engine Agent")));
  } catch {
    return sealResponse(NextResponse.json(sealResponse(getMockData(), "Transnational Repression Engine Agent"), { status: 502 }));
  }
}

function getMockData() {
  const entities = [
    { id: "TR-001", name: "Russie/FSB — Novitchok Londres, Dissidents UE & Navalny Empoisonnement", country: "Global/Europe", sector: "Novitchok Skripal Londres, Litvinenko Polonium, Navalny Empoisonné 2020 & 700+ Dissidents Fichés FSB Étranger", composite_score: 89.65, diaspora_targeting_intensity_score: 88.0, extraterritorial_assassination_score: 95.0, digital_transborder_surveillance_score: 90.0, host_country_coercion_score: 85.0, risk_level: "critique", primary_pattern: "assassinat_extraterritorial", key_signals: ["Assassinats extraterritoriaux commandités par Russie/FSB — Novitchok Skripal à Londres, Litvinenko au polonium et empoisonnement Navalny violant la souveraineté des États d'accueil", "Violation de la souveraineté des États d'accueil — la répression transnationale constitue une ingérence directe dans les affaires intérieures des États démocratiques hébergeant des dissidents", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et engager les procédures d'asile d'urgence pour les dissidents ciblés en exil"], estimated_transnational_repression_index: 8.97, last_updated: "2026-06-20" },
    { id: "TR-002", name: "Chine/MSS — Opération Fox Hunt, Stations Police & Ouïghours Exil", country: "Global/Asie", sector: "Operation Fox Hunt 10 000 Retours Forcés, Stations Police CCP 53 Pays, WeChat Surveillance Familles & Interpol Abus Notices", composite_score: 89.9, diaspora_targeting_intensity_score: 95.0, extraterritorial_assassination_score: 88.0, digital_transborder_surveillance_score: 92.0, host_country_coercion_score: 82.0, risk_level: "critique", primary_pattern: "ciblage_diaspora_systematique", key_signals: ["Ciblage systématique de la diaspora par Chine/MSS — 53 stations de police CCP dans des pays tiers, Operation Fox Hunt forçant 10 000 retours et surveillance WeChat des familles restées en Chine", "Violation de la souveraineté des États d'accueil — les stations de police chinoises opérant illégalement sur le territoire d'États souverains constituent une violation directe du droit international", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et exiger la fermeture des stations de police illégales sur le territoire national"], estimated_transnational_repression_index: 8.99, last_updated: "2026-06-20" },
    { id: "TR-003", name: "Arabie Saoudite/GIP — Khashoggi Istanbul & Dissidents Surveillés Pegasus", country: "MENA/Global", sector: "Khashoggi Assassinat Consulat Istanbul, Pegasus Surveillance Proches, 1000+ Dissidents Saoudiens Fichés & Familles Arrêtées", composite_score: 86.0, diaspora_targeting_intensity_score: 85.0, extraterritorial_assassination_score: 90.0, digital_transborder_surveillance_score: 88.0, host_country_coercion_score: 80.0, risk_level: "critique", primary_pattern: "assassinat_extraterritorial", key_signals: ["Assassinats extraterritoriaux commandités par Arabie Saoudite/GIP — meurtre de Khashoggi au consulat d'Istanbul et surveillance Pegasus des proches de dissidents en exil", "Violation de la souveraineté des États d'accueil — l'assassinat dans un consulat saoudien constitue une violation directe de la Convention de Vienne sur les relations consulaires", "Activer le Rapporteur Spécial ONU sur les exécutions extrajudiciaires et engager des poursuites contre les commanditaires identifiés"], estimated_transnational_repression_index: 8.6, last_updated: "2026-06-20" },
    { id: "TR-004", name: "Iran/MOIS — Assassins Envoyés Europe & Dissidents Iraniens Menacés", country: "MENA/Europe", sector: "Complots Assassinat Berlin/Paris/Stockholm, Dual Nationals Otages Diplomatiques, MOIS Surveillance Communautés & 200+ Cibles", composite_score: 83.5, diaspora_targeting_intensity_score: 80.0, extraterritorial_assassination_score: 88.0, digital_transborder_surveillance_score: 82.0, host_country_coercion_score: 85.0, risk_level: "critique", primary_pattern: "assassinat_extraterritorial", key_signals: ["Assassinats extraterritoriaux commandités par Iran/MOIS — complots déjoués à Berlin, Paris et Stockholm ciblant des dissidents iraniens en exil avec utilisation de nationaux doubles comme otages", "Violation de la souveraineté des États d'accueil — la répression transnationale constitue une ingérence directe dans les affaires intérieures des États démocratiques hébergeant des dissidents", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et engager les procédures d'asile d'urgence pour les dissidents ciblés en exil"], estimated_transnational_repression_index: 8.35, last_updated: "2026-06-20" },
    { id: "TR-005", name: "Turquie/MIT — Gülenistes Exil & Journalistes Turcs Europe", country: "Europe/MENA", sector: "Opération Güleniste 80+ Pays Rapatriements, Interpol Notices Abusives 890, Espions MIT Mosquées & Demandes Extradition Pression", composite_score: 56.4, diaspora_targeting_intensity_score: 55.0, extraterritorial_assassination_score: 52.0, digital_transborder_surveillance_score: 58.0, host_country_coercion_score: 62.0, risk_level: "élevé", primary_pattern: "coercition_pays_accueil", key_signals: ["Coercition des pays d'accueil par Turquie/MIT — 890 notices Interpol abusives et pression diplomatique sur les États hébergeant des Gülenistes pour obtenir leur expulsion forcée", "Violation de la souveraineté des États d'accueil — l'instrumentalisation d'Interpol et la surveillance des mosquées constituent une ingérence dans les affaires intérieures des États membres de l'UE", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et demander réforme des mécanismes d'Interpol pour prévenir les abus politiques"], estimated_transnational_repression_index: 5.64, last_updated: "2026-06-20" },
    { id: "TR-006", name: "Azerbaïdjan/Biélorussie — Journalistes Exil & Ryanair Détournement", country: "Europe de l'Est", sector: "Ryanair Détournement Minsk Protassevitch, Journalistes Azerbaïdjanais Exil Surveillés & Hack Phones Dissidents Pays Baltes", composite_score: 53.85, diaspora_targeting_intensity_score: 52.0, extraterritorial_assassination_score: 55.0, digital_transborder_surveillance_score: 58.0, host_country_coercion_score: 50.0, risk_level: "élevé", primary_pattern: "surveillance_numerique_frontiere", key_signals: ["Surveillance numérique transfrontalière d'Azerbaïdjan/Biélorussie — détournement Ryanair pour capturer Protassevitch et piratage des téléphones de dissidents dans les pays baltes", "Violation de la souveraineté des États d'accueil — le détournement d'un vol commercial civil constitue un acte de piraterie aérienne et une violation du droit international de l'aviation", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et engager les procédures d'asile d'urgence pour les dissidents ciblés en exil"], estimated_transnational_repression_index: 5.39, last_updated: "2026-06-20" },
    { id: "TR-007", name: "Éthiopie/Rwanda — Dissidents Réfugiés & Coopération Répressive Régionale", country: "Afrique", sector: "Rwanda Dissident Murders Uganda/Mozambique, Éthiopie Opposition Exil Ciblée, Ugandan Rwandan Coopération & Espions ONG Masqués", composite_score: 28.55, diaspora_targeting_intensity_score: 28.0, extraterritorial_assassination_score: 30.0, digital_transborder_surveillance_score: 25.0, host_country_coercion_score: 32.0, risk_level: "modéré", primary_pattern: "coercition_pays_accueil", key_signals: ["Coercition régionale des pays d'accueil par Éthiopie/Rwanda — coopération répressive bilatérale ciblant les opposants réfugiés en Ouganda et Mozambique avec espions masqués en ONG", "Violation de la souveraineté des États d'accueil — la répression transnationale constitue une ingérence directe dans les affaires intérieures des États hébergeant des réfugiés", "Activer le Rapporteur Spécial ONU sur les défenseurs des droits humains et renforcer la protection des dissidents africains en exil"], estimated_transnational_repression_index: 2.86, last_updated: "2026-06-20" },
    { id: "TR-008", name: "Freedom House/Frontline Defenders — Protection Dissidents & Alertes", country: "Global", sector: "Freedom House Transnational Repression Monitor, Frontline Defenders Urgence, RSF Protection Journalistes Exil & Safe Harbours Coalition", composite_score: 4.45, diaspora_targeting_intensity_score: 5.0, extraterritorial_assassination_score: 4.0, digital_transborder_surveillance_score: 3.0, host_country_coercion_score: 6.0, risk_level: "faible", primary_pattern: "ciblage_diaspora_systematique", key_signals: ["Freedom House/Frontline Defenders incarne la protection exemplaire des dissidents — monitoring en temps réel, alertes d'urgence et Safe Harbours Coalition facilitant la relocation sécurisée", "Normes internationales — Convention des réfugiés 1951 et Déclaration sur les défenseurs des droits humains créant des obligations de protection pour les États d'accueil", "Partager les méthodologies de détection de la répression transnationale et financer les programmes Safe Harbours pour les dissidents les plus ciblés"], estimated_transnational_repression_index: 0.45, last_updated: "2026-06-20" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { ciblage_diaspora_systematique: 2, assassinat_extraterritorial: 3, surveillance_numerique_frontiere: 1, coercition_pays_accueil: 2 },
    top_risk_entities: ["Chine/MSS — Opération Fox Hunt, Stations Police & Ouïghours Exil", "Russie/FSB — Novitchok Londres, Dissidents UE & Navalny Empoisonnement", "Arabie Saoudite/GIP — Khashoggi Istanbul & Dissidents Surveillés Pegasus"],
    critical_alerts: ["Russie/FSB: assassinat extraterritorial", "Chine/MSS: ciblage diaspora systématique", "Arabie Saoudite/GIP: assassinat extraterritorial", "Iran/MOIS: assassinat extraterritorial"],
    last_analysis: "2026-06-20",
    engine_version: "1.0.0",
    domain: "transnational_repression",
    confidence_score: 0.83,
    data_sources: ["freedom_house_transnational_repression_tracker", "frontline_defenders_annual_report", "citizen_lab_pegasus_spyware_investigations"],
    entities,
    avg_estimated_transnational_repression_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
