# Specs waves 985-992 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe (RASR→RDAS), 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 985 — Droit de la famille & procédures judiciaires
    ("grandparent_visitation_rights_engine.py",
     "Droits de visite des grands-parents & refus post-divorce", "Wave 985",
     "Grands-parents privés de leurs droits de visite après divorce ou conflit familial sans recours légal clair.",
     "GVSR", "grandparent_visit"),
    ("alimony_reform_gender_rights_engine.py",
     "Réforme de l'alimony & inégalités de genre post-divorce", "Wave 985",
     "Inégalités dans les pensions alimentaires entre époux selon le genre sans réforme légale équitable.",
     "ARGR", "alimony_reform"),
    ("probate_delay_heir_rights_engine.py",
     "Retards de procédures successorales & droits des héritiers", "Wave 985",
     "Héritiers attendant des années une succession en probate judiciaire sans accès aux actifs du défunt.",
     "PDHR", "probate_delay"),

    # Wave 986 — Santé : coûts & accès spécifiques
    ("bariatric_surgery_insurance_denial_rights_engine.py",
     "Refus d'assurance pour chirurgie bariatrique & discrimination par le poids", "Wave 986",
     "Patients obèses refusés pour la chirurgie bariatrique médicalement nécessaire par les assureurs.",
     "BSID", "bariatric_denial"),
    ("dental_implant_cost_gap_rights_engine.py",
     "Implants dentaires & lacunes de couverture Medicaid/Medicare", "Wave 986",
     "Patients sans couverture pour implants dentaires nécessaires, condamnés à l'extraction ou aux prothèses.",
     "DICG", "dental_implant"),
    ("drug_reimportation_patient_rights_engine.py",
     "Réimportation de médicaments & droits des patients américains", "Wave 986",
     "Patients américains incapables d'importer légalement des médicaments moins coûteux du Canada ou Europe.",
     "DRPR", "drug_reimport"),

    # Wave 987 — Discrimination linguistique & culturelle au travail
    ("aave_dialect_workplace_rights_engine.py",
     "Discrimination AAVE au travail & droits des locuteurs afro-américains", "Wave 987",
     "Travailleurs noirs discriminés ou sanctionnés pour l'utilisation de l'AAVE en milieu professionnel.",
     "ADVR", "aave_workplace"),
    ("ethnic_name_hiring_discrimination_rights_engine.py",
     "Discrimination à l'embauche selon le nom ethnique & biais implicite", "Wave 987",
     "Candidats avec des prénoms à consonance ethnique rejetés systématiquement malgré des qualifications égales.",
     "ENHD", "ethnic_name_hire"),
    ("name_pronunciation_workplace_rights_engine.py",
     "Droits à la prononciation correcte du prénom au travail", "Wave 987",
     "Employés forcés d'adopter un prénom 'américanisé' ou subissant la misprononciation chronique de leur nom.",
     "NPWR", "name_pronunciation"),

    # Wave 988 — Finance & accès aux services bancaires (niches)
    ("credit_invisible_financial_rights_engine.py",
     "Invisibles du crédit & exclusion financière systémique", "Wave 988",
     "Personnes sans historique de crédit exclues du logement, emploi et financement sans recours pour construire un profil.",
     "CIFR", "credit_invisible"),
    ("bank_account_closure_discrimination_rights_engine.py",
     "Fermeture discriminatoire de comptes bancaires & droits des clients", "Wave 988",
     "Banques fermant unilatéralement des comptes de clients minoritaires ou militants sans explication ni recours.",
     "BACD", "bank_closure_discrim"),
    ("debanking_political_rights_engine.py",
     "Débancarisation des militants politiques & liberté d'association", "Wave 988",
     "Activistes, journalistes ou organisations religieuses perdant leurs comptes bancaires pour leurs positions.",
     "DBPR", "debanking_political"),

    # Wave 989 — Services publics & infrastructure communautaire
    ("post_office_rural_closure_rights_engine.py",
     "Fermetures de bureaux de poste ruraux & désenclavement des communautés", "Wave 989",
     "Communautés rurales isolées par la fermeture de bureaux de poste uniques sans service de remplacement.",
     "PORC", "post_office_rural"),
    ("library_budget_cut_rights_engine.py",
     "Coupes budgétaires des bibliothèques publiques & accès à l'information", "Wave 989",
     "Bibliothèques publiques réduisant heures et services en raison de coupes, excluant les populations pauvres.",
     "LBCR", "library_budget_cut"),
    ("public_transit_privatization_rights_engine.py",
     "Privatisation des transports publics & inégalité d'accès", "Wave 989",
     "Systèmes de transport privatisés augmentant tarifs et réduisant couverture des zones pauvres.",
     "PTPR", "transit_privatize"),

    # Wave 990 — Travailleurs de l'économie créative & des loisirs
    ("content_creator_contract_rights_engine.py",
     "Contrats abusifs des plateformes numériques envers les créateurs", "Wave 990",
     "Créateurs de contenu liés par des contrats exclusifs inéquitables sans droits sur leur propre catalogue.",
     "CCCR", "content_creator_contract"),
    ("personal_trainer_misclass_rights_engine.py",
     "Fausse classification des entraîneurs personnels & perte d'avantages sociaux", "Wave 990",
     "Entraîneurs personnels traités comme indépendants sans protections sociales par les salles de sport.",
     "PTMR", "trainer_misclass"),
    ("exotic_dancer_labor_rights_engine.py",
     "Droits du travail des danseuses exotiques & exploitation par les clubs", "Wave 990",
     "Danseuses exotiques mal classifiées comme indépendantes, payant loyer de scène et privées de salaire minimum.",
     "EDLR", "exotic_dancer"),

    # Wave 991 — Sports & spectacles non conventionnels
    ("rodeo_athlete_safety_rights_engine.py",
     "Sécurité des cowboys de rodéo & absence de protections légales", "Wave 991",
     "Cowboys professionnels de rodéo sans compensation accident ni couverture worker's comp après blessures.",
     "RDAS", "rodeo_athlete"),
    ("circus_worker_labor_rights_engine.py",
     "Droits du travail des artistes de cirque itinérants", "Wave 991",
     "Artistes de cirque voyageant sans droits du travail stables, logement précaire et salaires imprévisibles.",
     "CWLR", "circus_worker"),
    ("adult_content_platform_rights_engine.py",
     "Déplatformage des créateurs adultes & absence de recours légal", "Wave 991",
     "Créateurs de contenu adulte légal supprimés sans préavis par des plateformes sans procédure d'appel.",
     "ACPR", "adult_content_platform"),

    # Wave 992 — Actifs numériques & réputation algorithmique
    ("crypto_exchange_collapse_rights_engine.py",
     "Effondrement des plateformes crypto & protection des investisseurs", "Wave 992",
     "Investisseurs perdant leurs économies lors de l'effondrement de plateformes crypto sans protection FDIC.",
     "CECR", "crypto_exchange_collapse"),
    ("nft_rug_pull_fraud_rights_engine.py",
     "Fraudes NFT rug pull & droits des acheteurs non protégés", "Wave 992",
     "Acheteurs de NFT victimes de rug pulls par des créateurs disparaissant sans recours légal ni remboursement.",
     "NRPF", "nft_rug_pull"),
    ("algorithmic_reputation_ban_rights_engine.py",
     "Bannissement algorithmique & réputation numérique injuste", "Wave 992",
     "Particuliers bannis automatiquement des services numériques par des algorithmes erronés sans appel humain.",
     "ARBR", "algo_rep_ban"),
]
