# Specs waves 1337-1344 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Corrections: IPCR pris par incarcerated_parent_child → IMCR
SPECS = [
    # Wave 1337 — Santé: soins post-aigus & facturation (inédits)
    ("skilled_nursing_facility_medicare_coverage_rights_engine.py",
     "Couverture Medicare pour les établissements de soins infirmiers qualifiés & droits des bénéficiaires à jusqu'à 100 jours couverts sans sortie prématurée imposée par l'assureur", "Wave 1337",
     "Patients Medicare transférés de l'hôpital en maison de convalescence se voyant forcer de quitter avant leur rétablissement complet sous pression des assureurs Medicare Advantage.",
     "SNFM", "snf_medicare_cover"),
    ("hospital_itemized_bill_audit_rights_engine.py",
     "Droit à une facture hospitalière détaillée & droits des patients à recevoir un relevé complet de tous les actes et médicaments pour identifier et contester les erreurs de facturation", "Wave 1337",
     "Patients recevant des factures hospitalières forfaitaires sans détail des actes, médicaments et services individuels, incapables d'identifier les erreurs de codage ou de double facturation.",
     "HIBR", "hospital_itemized_bill"),
    ("medical_upcoding_overbilling_patient_rights_engine.py",
     "Sur-codage et surfacturation médicale & droits des patients à une facturation précise des actes réels et à signaler les pratiques de codage gonflées aux organismes de contrôle", "Wave 1337",
     "Patients découvrant que des actes médicaux simples ont été facturés avec des codes de procédures plus complexes et coûteuses, entraînant des copaiements excessifs et des fraudes aux assureurs.",
     "MUOB", "med_upcoding_patient"),

    # Wave 1338 — Travail: congés FMLA & NDAs (inédits)
    ("fmla_intermittent_leave_protection_rights_engine.py",
     "Protection FMLA pour les congés intermittents & droits des employés à des absences médicales épisodiques sans mesures disciplinaires cumulatives pour absences FMLA protégées", "Wave 1338",
     "Employés utilisant des congés FMLA intermittents pour des conditions chroniques se voyant sanctionnés via des politiques d'assiduité qui ne reconnaissent pas les absences protégées.",
     "FLMI", "fmla_intermittent"),
    ("fmla_retaliation_interference_rights_engine.py",
     "Représailles et interférence avec le droit au congé FMLA & droits des employés victimes à un recours légal et à la réintégration après prise de congé médical légitime", "Wave 1338",
     "Employés subissant des rétrogradations, suppressions de postes ou ambiances hostiles après avoir pris un congé FMLA, l'employeur cherchant à décourager les futurs congés.",
     "FLIR", "fmla_retaliation"),
    ("employment_nda_harassment_victims_rights_engine.py",
     "NDAs imposés aux victimes de harcèlement au travail & droits des victimes à refuser ou invalider les accords de confidentialité les forçant au silence sur des comportements illégaux", "Wave 1338",
     "Victimes de harcèlement sexuel ou de discrimination au travail contraintes de signer des NDAs dans les règlements, leur interdisant de partager leur expérience ou de prévenir d'autres victimes.",
     "ENHV", "nda_harass_victims"),

    # Wave 1339 — Finance: fiscalité avancée (inédits)
    ("irs_audit_eitc_disparity_rights_engine.py",
     "Disparité des audits IRS ciblant les déclarants EITC à faibles revenus & droits à un traitement équitable sans ciblage disproportionné comparé aux ménages à revenus élevés", "Wave 1339",
     "Réclamants du crédit EITC à faibles revenus confrontés à des taux d'audit beaucoup plus élevés que les ménages à hauts revenus malgré un risque fiscal objectivement moindre.",
     "IAED", "irs_audit_eitc"),
    ("remote_worker_multistate_tax_rights_engine.py",
     "Imposition multi-États des télétravailleurs & droits des employés à distance à éviter la double imposition sur les mêmes revenus par leur État de résidence et l'État de l'employeur", "Wave 1339",
     "Télétravailleurs basés dans un État différent de leur employeur confrontés à des réclamations fiscales des deux États pour les mêmes revenus sans mécanisme de crédit automatique.",
     "RWMT", "remote_multistate_tax"),
    ("small_farm_estate_tax_relief_rights_engine.py",
     "Allégement fiscal successoral pour les petites fermes familiales & droits des héritiers agricoles à des exemptions ou plans de paiement évitant la vente forcée de terres agricoles", "Wave 1339",
     "Héritiers de fermes familiales confrontés à des droits de succession élevés sur des biens peu liquides mais de grande valeur foncière, contraints de vendre les terres pour payer l'impôt.",
     "SFET", "farm_estate_tax"),

    # Wave 1340 — Logement: baux spéciaux & discrimination (inédits)
    ("commercial_lease_small_business_rights_engine.py",
     "Droits des petits locataires commerciaux & protection contre les non-renouvellements et clauses abusives qui permettent des expulsions soudaines sans délai suffisant pour relocaliser", "Wave 1340",
     "Petites entreprises locataires se voyant signifier des non-renouvellements de bail commercial à court délai, incapables de relocaliser leur activité et clientèle sans fermeture permanente.",
     "CLSB", "commercial_lease_smb"),
    ("housing_voucher_landlord_acceptance_rights_engine.py",
     "Acceptation des bons de logement Section 8 par les propriétaires & droits des locataires à ne pas être refusés uniquement pour leur utilisation d'aides au logement HUD", "Wave 1340",
     "Familles à faibles revenus avec bons de logement Section 8 refusées par des propriétaires qui discriminent explicitement contre les locataires avec aide gouvernementale.",
     "HVLA", "voucher_landlord_accept"),
    ("move_out_inspection_deposit_return_rights_engine.py",
     "Inspection de départ et restitution du dépôt de garantie & droits des locataires à une inspection conjointe et à une liste détaillée justifiant les déductions avec preuves", "Wave 1340",
     "Locataires quittant un logement se voyant retenir tout ou partie de leur dépôt sans inspection conjointe, sans liste détaillée de déductions ni justificatifs des réparations imputées.",
     "MOID", "move_out_deposit"),

    # Wave 1341 — Éducation: services spéciaux (inédits)
    ("early_intervention_part_c_dispute_rights_engine.py",
     "Résolution des litiges IDEA Part C sur les services d'intervention précoce & droits des familles à une médiation et une audience pour les enfants de 0 à 3 ans refusés de services", "Wave 1341",
     "Parents d'enfants de moins de 3 ans identifiés avec des retards de développement se voyant refuser des services d'intervention précoce sans explication ni processus d'appel clair.",
     "EICD", "early_interv_dispute"),
    ("speech_language_therapy_school_iep_rights_engine.py",
     "Thérapie orthophonique dans les IEP scolaires & droits des élèves avec troubles de communication à des séances d'orthophonie suffisantes sans réduction arbitraire des services", "Wave 1341",
     "Élèves avec troubles du langage ou de la parole dont les districts scolaires réduisent les séances d'orthophonie IEP en raison des coûts plutôt que des besoins réels de l'élève.",
     "SLTS", "speech_therapy_iep"),
    ("adoptive_parent_parental_leave_rights_engine.py",
     "Congé parental pour les parents adoptifs & droits des parents qui adoptent à bénéficier des mêmes congés parentaux que les parents biologiques sans discrimination fondée sur le mode de parentalité", "Wave 1341",
     "Parents adoptifs dans des entreprises accordant un congé parental payé aux parents biologiques mais refusant le même avantage aux parents adoptifs ou nourriciers.",
     "APPL", "adoptive_parent_leave"),

    # Wave 1342 — Immigration: droits au travail (inédits)
    ("h1b_employer_visa_dependency_rights_engine.py",
     "Dépendance visa H-1B envers l'employeur & droits des travailleurs qualifiés à la mobilité professionnelle sans perdre leur statut lors d'un changement d'employeur parrainant", "Wave 1342",
     "Travailleurs qualifiés en visa H-1B souhaitant quitter un employeur abusif ne pouvant le faire sans risquer leur statut légal en raison de la dépendance de leur visa au parrainage.",
     "HVDR", "h1b_visa_dependency"),
    ("immigrant_professional_credential_recognition_rights_engine.py",
     "Reconnaissance des diplômes et certifications étrangers & droits des immigrants professionnels formés à l'étranger à une évaluation équitable et accessible de leurs credentials", "Wave 1342",
     "Médecins, ingénieurs et professionnels immigrants ne pouvant exercer leur profession aux États-Unis malgré des diplômes équivalents faute d'un processus de reconnaissance accessible.",
     "IMCR", "immigr_credential_recog"),
    ("undocumented_worker_labor_law_rights_engine.py",
     "Droits du travail des travailleurs sans papiers & protection contre l'exploitation salariale et l'abus indépendamment du statut migratoire sous les lois FLSA et NLRA", "Wave 1342",
     "Travailleurs sans papiers exploités par des employeurs qui refusent de payer le salaire minimum ou les heures supplémentaires, menaçant de dénonciation ICE en cas de plainte.",
     "UDWL", "undocumented_labor"),

    # Wave 1343 — Santé: données & vie privée (inédits)
    ("state_consumer_health_data_privacy_rights_engine.py",
     "Lois étatiques sur la confidentialité des données de santé des consommateurs & droits à contrôler la collecte et la vente de données de santé non couvertes par HIPAA", "Wave 1343",
     "Consommateurs utilisant des apps de santé, trackers de fitness et services de bien-être dont les données sensibles sont vendues à des tiers sans couverture HIPAA ni droit d'opt-out.",
     "SRCA", "state_health_data_priv"),
    ("digital_health_app_data_rights_engine.py",
     "Droits des utilisateurs d'applications de santé numériques & protection contre l'utilisation commerciale des données de santé collectées par des apps non réglementées HIPAA", "Wave 1343",
     "Utilisateurs d'applications de gestion de médicaments, suivi de symptômes et téléthérapie ignorant que leurs données de santé sensibles sont utilisées à des fins publicitaires.",
     "DAPP", "digital_health_app"),
    ("consumer_protection_privacy_opt_out_rights_engine.py",
     "Droits opt-out des données consommateurs & droits des résidents d'États avec lois de confidentialité complètes à supprimer leurs données personnelles des bases des data brokers", "Wave 1343",
     "Consommateurs dans des États avec lois de confidentialité des données cherchant à exercer leurs droits d'accès, de suppression et de portabilité face à des processus d'opt-out délibérément complexes.",
     "CPPR", "consumer_privacy_opt"),

    # Wave 1344 — Droits: accès services & civisme (inédits)
    ("medicaid_adult_dental_coverage_rights_engine.py",
     "Couverture dentaire Medicaid pour adultes & droits des bénéficiaires adultes à des soins dentaires préventifs et curatifs sans être limités aux seules extractions d'urgence", "Wave 1344",
     "Adultes bénéficiaires de Medicaid dans des États n'offrant que des extractions d'urgence incapables d'accéder aux soins préventifs et curatifs qui préserveraient leur santé bucco-dentaire.",
     "MADC", "medicaid_adult_dental"),
    ("essential_worker_hazard_pay_rights_engine.py",
     "Prime de risque pour les travailleurs essentiels en situation de danger & droits des travailleurs en première ligne à une compensation supplémentaire lors des crises sanitaires ou catastrophes", "Wave 1344",
     "Travailleurs essentiels exposés à des risques élevés pendant des crises sanitaires ou catastrophes naturelles sans prime de risque garantie par la loi malgré l'exposition documentée.",
     "EWRP", "essential_hazard_pay"),
    ("caregiver_anti_discrimination_rights_engine.py",
     "Protection contre la discrimination basée sur les responsabilités d'aidant & droits des employés aidants familiaux à ne pas être pénalisés professionnellement pour leurs obligations de soins", "Wave 1344",
     "Parents, aidants d'adultes handicapés ou de parents âgés confrontés à des discriminations à l'embauche et des mises à l'écart professionnelles en raison de leurs responsabilités d'aidant.",
     "CARP", "caregiver_anti_discrim"),
]
