# Specs waves 913-920 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 913 — Déserts médicaux ruraux : maternité & soins généraux
    ("maternal_mortality_rural_rights_engine.py",
     "Mortalité maternelle & déserts obstétricaux ruraux", "Wave 913",
     "Femmes rurales mourant en couches faute de maternité accessible.",
     "MMRU", "maternal_rural"),
    ("obstetric_desert_rural_rights_engine.py",
     "Déserts obstétricaux ruraux & accouchements non assistés", "Wave 913",
     "Comtés ruraux sans obstétricien forçant les femmes à accoucher loin de chez elles.",
     "ODRU", "obstetric_desert"),
    ("telemedicine_rural_gap_rights_engine.py",
     "Télémédecine & fracture numérique rurale", "Wave 913",
     "Patients ruraux sans haut débit incapables d'accéder aux consultations en télémédecine.",
     "TLMG", "telemedicine_rural"),

    # Wave 914 — Haut débit, remboursement & hôpitaux critiques
    ("broadband_rural_health_rights_engine.py",
     "Haut débit rural & accès aux soins numériques", "Wave 914",
     "Absence d'internet haut débit privant les ruraux des services de télésanté.",
     "BRHD", "broadband_rural_health"),
    ("telehealth_reimbursement_gap_rights_engine.py",
     "Remboursement de la télésanté & lacunes d'équité", "Wave 914",
     "Assureurs refusant de rembourser les consultations en télésanté comme les visites physiques.",
     "THRG", "telehealth_reimburse"),
    ("critical_access_hospital_rights_engine.py",
     "Hôpitaux d'accès critique & menace de fermeture", "Wave 914",
     "Seuls hôpitaux ruraux de comtés entiers menacés de fermeture par manque de financement.",
     "CAHP", "critical_access_hosp"),

    # Wave 915 — Urgences rurales & soins primaires
    ("ambulance_rural_delay_rights_engine.py",
     "Délais d'ambulance ruraux & morts évitables", "Wave 915",
     "Patients ruraux attendant des heures une ambulance dans des urgences vitales.",
     "AMRD", "ambulance_rural"),
    ("emergency_room_wait_rural_rights_engine.py",
     "Attente aux urgences rurales & détresse médicale", "Wave 915",
     "Urgences rurales sous-dotées en personnel imposant des attentes dangereuses.",
     "ERWR", "er_rural_wait"),
    ("dental_desert_rural_rights_engine.py",
     "Déserts dentaires ruraux & caries non traitées", "Wave 915",
     "Ruraux sans dentiste à des centaines de kilomètres souffrant de maladies dentaires chroniques.",
     "DDRR", "dental_rural"),

    # Wave 916 — Spécialités & pharmacies rurales
    ("vision_care_rural_rights_engine.py",
     "Soins oculaires ruraux & cécité évitable", "Wave 916",
     "Ruraux sans ophtalmologue perdant la vue par manque de dépistage et de traitement.",
     "VCRR", "vision_rural"),
    ("mental_health_rural_gap_rights_engine.py",
     "Santé mentale & désert psychiatrique rural", "Wave 916",
     "Comtés ruraux entiers sans un seul psychiatre ni thérapeute agréé.",
     "MHRG", "mh_rural"),
    ("pharmacy_desert_rural_rights_engine.py",
     "Déserts pharmaceutiques ruraux & accès aux médicaments", "Wave 916",
     "Ruraux parcourant des dizaines de kilomètres pour remplir une ordonnance vitale.",
     "PDRR", "pharmacy_rural"),

    # Wave 917 — Dialyse, spécialistes & pédiatrie
    ("dialysis_rural_access_rights_engine.py",
     "Dialyse & accès rural aux soins rénaux", "Wave 917",
     "Patients insuffisants rénaux ruraux parcourant des heures trois fois par semaine pour la dialyse.",
     "DLRA", "dialysis_rural"),
    ("specialist_rural_shortage_rights_engine.py",
     "Pénurie de spécialistes ruraux & soins différés", "Wave 917",
     "Spécialistes médicaux absents dans les zones rurales forçant des voyages épuisants.",
     "SSRR", "specialist_rural"),
    ("pediatric_rural_gap_rights_engine.py",
     "Pédiatrie rurale & enfants sans suivi médical", "Wave 917",
     "Enfants ruraux sans pédiatre à proximité, dépendants d'urgences pour les soins courants.",
     "PGRR", "pediatric_rural"),

    # Wave 918 — Soins des aînés & populations tribales
    ("elder_rural_care_rights_engine.py",
     "Soins aux aînés ruraux & isolement médical", "Wave 918",
     "Personnes âgées rurales sans aide à domicile ni maison de retraite accessible.",
     "ECRU", "elder_rural_care"),
    ("tribal_health_underfund_rights_engine.py",
     "Santé des tribus & sous-financement chronique", "Wave 918",
     "Infrastructures de santé tribales chroniquement sous-financées par rapport aux besoins.",
     "TIDH", "tribal_health"),
    ("indian_health_service_gap_rights_engine.py",
     "Indian Health Service & lacunes de couverture", "Wave 918",
     "Autochtones privés de soins essentiels par les insuffisances de l'Indian Health Service.",
     "IHSG", "ihs_gap"),

    # Wave 919 — Santé à la frontière & travailleurs migrants
    ("border_health_desert_rights_engine.py",
     "Déserts de santé frontaliers & populations vulnérables", "Wave 919",
     "Communautés frontalières éloignées des deux systèmes de santé nationaux.",
     "BDHD", "border_health"),
    ("migrant_worker_health_clinic_rights_engine.py",
     "Travailleurs migrants & cliniques de santé itinérantes", "Wave 919",
     "Travailleurs migrants agricoles sans clinique accessible pendant leur déplacement.",
     "MWHC", "migrant_health_clinic"),
    ("occupational_injury_migrant_rights_engine.py",
     "Blessures professionnelles des travailleurs migrants", "Wave 919",
     "Travailleurs migrants blessés au travail sans couverture d'accident ni recours légal.",
     "OIMW", "migrant_injury"),

    # Wave 920 — Santé & conditions des travailleurs agricoles
    ("heat_illness_farmworker_rights_engine.py",
     "Maladie de chaleur & travailleurs agricoles", "Wave 920",
     "Ouvriers agricoles mourant de coup de chaleur sans accès à l'eau ni aux pauses réglementaires.",
     "HIFM", "farmworker_heat"),
    ("farm_worker_housing_camp_rights_engine.py",
     "Camps de logement agricoles & conditions insalubres", "Wave 920",
     "Travailleurs agricoles logés dans des camps sans eau potable ni sanitaires décents.",
     "FWHC", "farm_housing_camp"),
    ("silica_construction_worker_rights_engine.py",
     "Silice dans la construction & ouvriers non protégés", "Wave 920",
     "Ouvriers du bâtiment inhalant la silice sans équipement de protection ni suivi médical.",
     "SCNW", "silica_construction"),
]
