# Specs waves 1361-1368 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Correction: CSAR pris par child_soldiers → CSLR (community solar)
SPECS = [
    # Wave 1361 — Santé: maladies auto-immunes & rares (inédits)
    ("scleroderma_treatment_access_rights_engine.py",
     "Accès au traitement de la sclérodermie systémique & droits des patients atteints de cette maladie auto-immune rare à des thérapies spécialisées et un suivi pluridisciplinaire", "Wave 1361",
     "Patients atteints de sclérodermie systémique confrontés à des délais diagnostiques et à des refus de couverture pour les traitements spécialisés ralentissant la progression de la maladie.",
     "SCLT", "scleroderma_treat"),
    ("sarcoidosis_disability_recognition_rights_engine.py",
     "Reconnaissance de la sarcoïdose comme handicap & droits des patients à des accommodements et prestations face à une maladie inflammatoire multisystémique fluctuante et invisible", "Wave 1361",
     "Personnes atteintes de sarcoïdose avec atteintes pulmonaires et fatigue chronique se voyant refuser la reconnaissance de leur handicap en raison du caractère fluctuant des symptômes.",
     "SARD", "sarcoidosis_disab"),
    ("ehlers_danlos_diagnosis_delay_rights_engine.py",
     "Délais de diagnostic du syndrome d'Ehlers-Danlos & droits des patients à une orientation rapide vers des spécialistes après des années d'errance médicale pour ce trouble du tissu conjonctif", "Wave 1361",
     "Patients atteints du syndrome d'Ehlers-Danlos attendant en moyenne plus d'une décennie un diagnostic correct après de multiples consultations infructueuses et symptômes minimisés.",
     "EDDD", "ehlers_danlos_diag"),

    # Wave 1362 — Santé: neurologie rare & génétique (inédits)
    ("mast_cell_activation_syndrome_rights_engine.py",
     "Reconnaissance du syndrome d'activation mastocytaire & droits des patients à un diagnostic et un traitement face à une affection complexe souvent rejetée comme psychosomatique", "Wave 1362",
     "Patients atteints du syndrome d'activation mastocytaire confrontés à des réactions sévères multisystémiques rejetées par les médecins comme anxiété faute de reconnaissance de l'affection.",
     "MCAS", "mast_cell_activation"),
    ("tardive_dyskinesia_treatment_access_rights_engine.py",
     "Accès au traitement de la dyskinésie tardive & droits des patients ayant développé des mouvements involontaires causés par des médicaments psychiatriques à des thérapies correctrices", "Wave 1362",
     "Patients ayant développé une dyskinésie tardive irréversible suite à des antipsychotiques se voyant refuser l'accès aux nouveaux traitements VMAT2 coûteux par leur assurance.",
     "TDTA", "tardive_dyskinesia"),
    ("genetic_discrimination_life_insurance_rights_engine.py",
     "Discrimination génétique par les assureurs vie & droits des personnes ayant effectué des tests génétiques à ne pas se voir refuser ou surtarifer une assurance vie sur cette base", "Wave 1362",
     "Personnes ayant effectué un test génétique révélant une prédisposition se voyant refuser une assurance vie ou invalidité, la protection GINA ne couvrant pas ces polices.",
     "GDLI", "genetic_life_insur"),

    # Wave 1363 — Logement: énergie & accès (inédits)
    ("community_solar_access_renter_rights_engine.py",
     "Accès au solaire communautaire pour les locataires & droits des personnes ne pouvant installer de panneaux à bénéficier de l'énergie solaire partagée et de ses économies", "Wave 1363",
     "Locataires et copropriétaires incapables d'installer leurs propres panneaux solaires exclus des bénéfices du solaire communautaire faute de programmes accessibles dans leur région.",
     "CSLR", "community_solar_renter"),
    ("electric_vehicle_charging_renter_rights_engine.py",
     "Accès aux bornes de recharge pour les locataires & droits des résidents d'immeubles à demander l'installation de bornes de recharge pour véhicules électriques", "Wave 1363",
     "Locataires possédant un véhicule électrique incapables de le recharger faute de bornes dans leur immeuble et sans droit légal de demander leur installation au propriétaire.",
     "EVCR", "ev_charging_renter"),
    ("weatherization_assistance_renter_rights_engine.py",
     "Aide à l'isolation thermique pour les locataires & droits des occupants de logements énergivores à bénéficier des programmes de calfeutrage sans blocage par le propriétaire", "Wave 1363",
     "Locataires de logements mal isolés subissant des factures énergétiques élevées incapables d'accéder aux programmes d'aide à la rénovation thermique bloqués par les propriétaires.",
     "WXAR", "weatherization_renter"),

    # Wave 1364 — Consommation & protection (inédits)
    ("funeral_preneed_contract_rights_engine.py",
     "Contrats funéraires prépayés & droits des consommateurs à la protection de leurs fonds prépayés et à la transférabilité en cas de faillite du prestataire ou de déménagement", "Wave 1364",
     "Personnes ayant prépayé leurs funérailles découvrant que leurs fonds ne sont pas protégés en cas de faillite du salon funéraire ou non transférables lors d'un déménagement.",
     "FPNC", "funeral_preneed"),
    ("pet_deposit_assistance_animal_rights_engine.py",
     "Dépôts pour animaux et animaux d'assistance & droits des locataires à ne pas payer de dépôts ou frais pour animaux pour leurs animaux d'assistance médicalement nécessaires", "Wave 1364",
     "Locataires avec animaux d'assistance se voyant illégalement facturer des dépôts et frais mensuels pour animaux malgré le statut distinct des animaux d'assistance sous la FHA.",
     "PDAA", "pet_deposit_assist"),
    ("military_lending_act_violation_rights_engine.py",
     "Violations de la loi sur le prêt aux militaires & droits des militaires actifs à un plafond de taux d'intérêt et à des protections contre les prêts prédateurs ciblant les bases", "Wave 1364",
     "Militaires en service actif ciblés par des prêteurs prédateurs contournant le plafond de taux du Military Lending Act via des produits financiers structurés pour échapper à la loi.",
     "MLAV", "military_lending_act"),

    # Wave 1365 — Finance: prédateur & dettes (inédits)
    ("subprime_auto_yo_yo_financing_rights_engine.py",
     "Financement automobile yo-yo subprime & droits des acheteurs à ne pas être rappelés après la vente pour renégocier à des conditions pires sous menace de reprise du véhicule", "Wave 1365",
     "Acheteurs de voitures à crédit subprime rappelés par le concessionnaire jours après l'achat pour signer un nouveau contrat à taux plus élevé sous menace de devoir rendre le véhicule.",
     "SAYY", "subprime_auto_yoyo"),
    ("debt_collector_workplace_contact_rights_engine.py",
     "Contact des recouvreurs de dettes sur le lieu de travail & droits des débiteurs à interdire les appels à leur employeur et à protéger leur emploi des pratiques de recouvrement", "Wave 1365",
     "Débiteurs harcelés par des recouvreurs appelant leur lieu de travail malgré l'interdiction FDCPA, risquant des sanctions disciplinaires voire la perte de leur emploi.",
     "DCWC", "debt_collector_work"),
    ("student_meal_debt_transfer_rights_engine.py",
     "Transfert et recouvrement des dettes de cantine scolaire & droits des familles à ne pas voir ces dettes confiées à des agences de recouvrement ni les enfants stigmatisés", "Wave 1365",
     "Familles avec arriérés de cantine scolaire voyant ces petites dettes transférées à des agences de recouvrement privées avec frais ajoutés et stigmatisation de leurs enfants.",
     "SMDT", "student_meal_debt"),

    # Wave 1366 — Travail: secteurs spécifiques (inédits)
    ("tipped_minor_worker_wage_rights_engine.py",
     "Protection salariale des travailleurs mineurs au pourboire & droits des adolescents employés dans la restauration à un salaire minimum garanti et à une protection contre l'exploitation", "Wave 1366",
     "Adolescents travaillant au pourboire dans la restauration rapide et les services exploités par des employeurs ne garantissant pas le complément de salaire minimum légalement dû.",
     "TMWW", "tipped_minor_worker"),
    ("domestic_worker_live_in_hours_rights_engine.py",
     "Heures de travail des employés de maison résidents & droits des travailleurs domestiques logés à une délimitation claire des heures travaillées et à une rémunération de toutes les heures", "Wave 1366",
     "Employés de maison logés chez leur employeur travaillant de facto en permanence sans délimitation des heures de service ni rémunération des heures de disponibilité nocturne.",
     "DWLH", "domestic_live_in_hours"),
    ("tps_work_authorization_gap_rights_engine.py",
     "Lacunes d'autorisation de travail pour les titulaires de TPS & droits des bénéficiaires du statut de protection temporaire à une continuité d'emploi sans interruption lors des renouvellements", "Wave 1366",
     "Travailleurs titulaires du TPS perdant temporairement leur droit de travailler en raison de retards de traitement des renouvellements de désignation et d'autorisation d'emploi.",
     "TWAG", "tps_work_auth_gap"),

    # Wave 1367 — Justice: réintégration & expression (inédits)
    ("parole_reentry_id_documents_rights_engine.py",
     "Documents d'identité à la sortie de prison & droits des personnes libérées à obtenir rapidement pièces d'identité et documents nécessaires à l'emploi, au logement et aux prestations", "Wave 1367",
     "Personnes sortant de prison sans pièce d'identité valide incapables d'accéder à l'emploi, au logement ou aux services bancaires en raison de processus de réobtention longs et coûteux.",
     "PRID", "parole_reentry_id"),
    ("prison_book_ban_censorship_rights_engine.py",
     "Censure et interdiction de livres en prison & droits des détenus à accéder à la littérature et aux ressources éducatives sans interdictions arbitraires et excessives", "Wave 1367",
     "Détenus se voyant refuser l'accès à des livres éducatifs, juridiques ou littéraires par des politiques de censure carcérale arbitraires bloquant même des ouvrages de référence courants.",
     "PBBC", "prison_book_ban"),
    ("voter_id_disability_access_rights_engine.py",
     "Accès des personnes handicapées aux exigences d'identification électorale & droits des électeurs handicapés à obtenir et présenter une pièce d'identité sans barrières disproportionnées", "Wave 1367",
     "Électeurs handicapés incapables d'obtenir facilement une pièce d'identité conforme aux exigences de vote en raison de barrières d'accès aux bureaux d'émission et de coûts.",
     "VIDA", "voter_id_disability"),

    # Wave 1368 — Droits: expression & vie privée (inédits)
    ("campus_free_speech_zone_rights_engine.py",
     "Zones de libre expression sur les campus universitaires & droits des étudiants à s'exprimer sans confinement à des zones restreintes ni autorisations préalables excessives", "Wave 1368",
     "Étudiants confrontés à des politiques universitaires confinant l'expression à de petites zones désignées avec préavis obligatoire, limitant le débat sur les espaces publics du campus.",
     "CFSZ", "campus_free_speech"),
    ("student_journalist_censorship_rights_engine.py",
     "Censure du journalisme étudiant & droits des élèves journalistes à une liberté de presse protégée contre la censure administrative des publications scolaires et universitaires", "Wave 1368",
     "Élèves journalistes voyant leurs articles censurés par l'administration scolaire pour avoir couvert des sujets sensibles, sans protection légale type loi New Voices dans leur État.",
     "SJCR", "student_journalist"),
    ("smart_speaker_recording_privacy_rights_engine.py",
     "Vie privée et enregistrements des assistants vocaux & droits des utilisateurs à contrôler la collecte, l'écoute humaine et la conservation des enregistrements de leurs enceintes connectées", "Wave 1368",
     "Utilisateurs d'assistants vocaux découvrant que leurs conversations sont enregistrées, conservées et écoutées par des employés sans consentement clair ni contrôle sur la suppression.",
     "SSRP", "smart_speaker_privacy"),
]
