# Specs waves 889-896 — 24 nouveaux moteurs de droits humains
# Vérifications préalables : 0 doublon sémantique, 0 collision de préfixe
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 889 — Documents d'identité & accès civique
    ("birth_certificate_access_rights_engine.py",
     "Acte de naissance & accès aux droits fondamentaux", "Wave 889",
     "Personnes sans acte de naissance exclues de toute démarche civique, sociale ou médicale.",
     "BCAC", "birth_cert_access"),
    ("identity_document_homeless_rights_engine.py",
     "Sans-abri & perte de documents d'identité", "Wave 889",
     "Sans-abri en cercle vicieux : sans adresse, pas de pièce d'identité, sans pièce, pas d'aide.",
     "IDHO", "id_homeless"),
    ("id_poverty_barrier_rights_engine.py",
     "Frais d'identité & barrière à l'accès", "Wave 889",
     "Coût des pièces d'identité excluant les plus pauvres de tout accès aux services.",
     "IDPB", "id_poverty"),

    # Wave 890 — Vote & photo d'identité
    ("voting_photo_id_impossible_rights_engine.py",
     "Photo d'identité & impossibilité de vote", "Wave 890",
     "Électeurs pauvres ou ruraux sans photo d'identité valide empêchés de voter.",
     "VPID", "photo_vote_barrier"),
    ("language_access_court_rights_engine.py",
     "Accès linguistique aux tribunaux", "Wave 890",
     "Justiciables non anglophones privés d'interprètes qualifiés dans les procédures judiciaires.",
     "CACC", "court_language_access"),
    ("court_interpreter_right_rights_engine.py",
     "Droit à un interprète en justice & défaillances", "Wave 890",
     "Audiences conduites sans interprète, privant les justiciables de comprendre leur procès.",
     "CRIP", "court_interpreter"),

    # Wave 891 — Accès linguistique aux services publics
    ("administrative_hearing_language_rights_engine.py",
     "Audiences administratives & barrière linguistique", "Wave 891",
     "Administrations conduisant des auditions déterminantes sans traduction pour les LEP.",
     "ALHL", "admin_language"),
    ("medical_translation_patient_rights_engine.py",
     "Traduction médicale & droit du patient LEP", "Wave 891",
     "Patients à compétence limitée en anglais soignés sans interprète médical qualifié.",
     "MTLP", "medical_translation"),
    ("immigration_translation_detention_rights_engine.py",
     "Traduction en détention migratoire & droits", "Wave 891",
     "Migrants détenus conduisant leur défense sans interprète compétent en droit.",
     "ITDN", "immigration_translation"),

    # Wave 892 — Handicap & pièges économiques
    ("disability_ssi_cliff_rights_engine.py",
     "SSI & falaise d'allocation handicap", "Wave 892",
     "Personnes handicapées perdant toutes leurs aides dès qu'elles gagnent un sou de trop.",
     "DSIC", "disability_ssi_cliff"),
    ("income_disability_trap_rights_engine.py",
     "Revenu & piège de la désincitation handicap", "Wave 892",
     "Incitations perverses du système de prestations empêchant les personnes handicapées de travailler.",
     "IDTL", "income_disability_trap"),
    ("medicaid_asset_limit_rights_engine.py",
     "Plafond de patrimoine Medicaid & pauvreté forcée", "Wave 892",
     "Règles obligeant les personnes handicapées à rester pauvres pour conserver leur couverture santé.",
     "MAAL", "medicaid_asset"),

    # Wave 893 — Fiducies, mariage & Medicaid
    ("special_needs_trust_access_rights_engine.py",
     "Fiducies pour besoins spéciaux & accès inégal", "Wave 893",
     "Personnes handicapées sans avocat incapables d'accéder aux fiducies protégeant leurs prestations.",
     "SNTT", "special_needs_trust"),
    ("medicaid_marriage_penalty_rights_engine.py",
     "Pénalité de mariage Medicaid & couples handicapés", "Wave 893",
     "Couples handicapés forcés de ne pas se marier pour conserver leur couverture Medicaid.",
     "MMPY", "medicaid_marriage"),
    ("disability_divorce_medical_rights_engine.py",
     "Divorce & perte de couverture médicale des personnes handicapées", "Wave 893",
     "Personnes handicapées perdant leur assurance santé après un divorce.",
     "DGMD", "disability_divorce"),

    # Wave 894 — Autonomie & tutelle des personnes handicapées
    ("guardianship_autonomy_disability_rights_engine.py",
     "Tutelle & perte d'autonomie des personnes handicapées", "Wave 894",
     "Tutelles totales supprimant tout pouvoir décisionnel sans restriction proportionnelle.",
     "GDAB", "guardianship_autonomy"),
    ("accessible_playground_design_rights_engine.py",
     "Aires de jeux accessibles & droit des enfants handicapés", "Wave 894",
     "Enfants handicapés exclus des aires de jeux faute de conception universelle.",
     "APLD", "accessible_playground"),
    ("park_access_disability_rights_engine.py",
     "Espaces verts & accessibilité aux personnes handicapées", "Wave 894",
     "Parcs et espaces naturels inaccessibles aux fauteuils roulants et aux personnes à mobilité réduite.",
     "PKAD", "park_disability"),

    # Wave 895 — Loisirs & accessibilité physique
    ("recreational_facility_wheelchair_rights_engine.py",
     "Équipements sportifs & accès aux fauteuils roulants", "Wave 895",
     "Gymnases, piscines et salles de sport inaccessibles aux utilisateurs de fauteuils.",
     "RFWC", "rec_facility_wheel"),
    ("pool_lift_ada_rights_engine.py",
     "Lève-personne piscine & obligations d'accessibilité", "Wave 895",
     "Piscines publiques sans lève-personne conforme excluant les usagers handicapés.",
     "PLFT", "pool_lift"),
    ("deaf_blind_communication_barrier_rights_engine.py",
     "Sourd-cécité & barrières de communication", "Wave 895",
     "Personnes sourdaveugles sans accès à des interprètes tactile ou systèmes augmentatifs.",
     "DBCM", "deaf_blind_comm"),

    # Wave 896 — Infrastructure & mobilité accessible
    ("tactile_paving_obstruction_rights_engine.py",
     "Bandes podotactiles obstruées & piétons aveugles", "Wave 896",
     "Mobilier urbain obstruant les bandes podotactiles privant les aveugles de déplacement autonome.",
     "TPOB", "tactile_paving"),
    ("LEP_language_court_access_rights_engine.py",
     "Compétence linguistique limitée & accès à la justice", "Wave 896",
     "Personnes à compétence limitée en langue officielle naviguant seules dans les systèmes juridiques.",
     "LEPH", "lep_court"),
    ("court_interpreter_oath_quality_rights_engine.py",
     "Qualité des interprètes judiciaires & serment", "Wave 896",
     "Interprètes non certifiés commettant des erreurs graves dans des procédures judiciaires.",
     "CTIO", "court_interp_quality"),
]
