# Specs waves 857-864 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 857 — Dettes structurelles & faillite
    ("student_loan_bankruptcy_ban_rights_engine.py",
     "Prêts étudiants & impossibilité de faillite", "Wave 857",
     "Étudiants endettés à vie, seul groupe légalement exclu du droit à la faillite.",
     "SLBB", "student_bankruptcy"),
    ("medical_bankruptcy_rights_engine.py",
     "Faillite médicale & accès aux soins", "Wave 857",
     "Ménages ruinés par des factures médicales catastrophiques malgré une assurance.",
     "MDBK", "medical_bankruptcy"),
    ("bankruptcy_medical_bill_discharge_rights_engine.py",
     "Dettes médicales & effacement en faillite", "Wave 857",
     "Dettes médicales transformant la faillite en dernier recours indispensable mais insuffisant.",
     "BKMD", "bill_discharge"),

    # Wave 858 — Inégalités de patrimoine & loyers
    ("housing_inequality_tax_rights_engine.py",
     "Imposition du logement & inégalité patrimoniale", "Wave 858",
     "Systèmes fiscaux avantageant les propriétaires riches au détriment des locataires pauvres.",
     "HIXT", "housing_tax_inequality"),
    ("landlord_tax_loophole_rights_engine.py",
     "Propriétaires & niches fiscales abusives", "Wave 858",
     "Failles fiscales permettant aux grands propriétaires d'éviter tout impôt sur les loyers.",
     "LTLH", "landlord_loophole"),
    ("inheritance_wealth_gap_rights_engine.py",
     "Héritage & fossé de richesse intergénérationnel", "Wave 858",
     "Héritages exonérés creusant le fossé entre dynasties patrimoniales et classes populaires.",
     "IWGP", "inheritance_gap"),

    # Wave 859 — Salaires & rémunération
    ("ceo_pay_ratio_disparity_rights_engine.py",
     "Ratio salaires PDG/employés & inégalité salariale", "Wave 859",
     "Ratio de rémunération PDG/salarié médian atteignant des centaines contre un.",
     "CPRD", "ceo_pay_ratio"),
    ("living_wage_ordinance_block_rights_engine.py",
     "Salaire minimum vital & blocage préemptif des États", "Wave 859",
     "États bloquant les ordonnances locales de salaire vital plus élevé.",
     "LWOB", "living_wage_block"),
    ("tip_credit_wage_floor_rights_engine.py",
     "Crédit de pourboire & salaire minimum des serveurs", "Wave 859",
     "Serveurs subissant un sous-salaire légalisé par le crédit de pourboire.",
     "TPCW", "tip_credit_floor"),

    # Wave 860 — Économie de plateforme & évasion fiscale
    ("platform_economy_tax_evasion_rights_engine.py",
     "Économie de plateforme & évasion fiscale systémique", "Wave 860",
     "Géants des plateformes évitant l'impôt via des montages offshore tout en exploitant le marché local.",
     "PETE", "platform_tax"),
    ("gig_tax_gap_worker_rights_engine.py",
     "Travailleurs gig & charge fiscale disproportionnée", "Wave 860",
     "Travailleurs indépendants payant plus d'impôts que les salariés sans protection équivalente.",
     "GTGW", "gig_tax_gap"),
    ("server_minimum_wage_theft_rights_engine.py",
     "Serveurs & vol de salaire minimum", "Wave 860",
     "Restaurateurs ne compensant pas les serveurs quand les pourboires ne couvrent pas le SMIC.",
     "SMNW", "server_wage_theft"),

    # Wave 861 — Droit du travail & syndicats
    ("union_busting_nlrb_violation_rights_engine.py",
     "Casse des syndicats & violations du droit du travail", "Wave 861",
     "Employeurs démantèlant les syndicats via des pratiques illégales impunies.",
     "UBNV", "union_busting"),
    ("strike_injunction_abuse_rights_engine.py",
     "Injonctions anti-grève abusives & droit de grève", "Wave 861",
     "Recours judiciaires d'urgence suspendant les grèves légales sur des prétextes économiques.",
     "SIJT", "strike_injunction"),
    ("mandatory_arbitration_consumer_rights_engine.py",
     "Arbitrage obligatoire & droits des consommateurs", "Wave 861",
     "Clauses d'arbitrage obligatoire privant les consommateurs du droit d'agir en justice.",
     "MARC", "mandatory_arbitration"),

    # Wave 862 — Silence juridique & intimidation
    ("forced_class_action_waiver_rights_engine.py",
     "Renoncement aux actions collectives & droits", "Wave 862",
     "Contrats forçant les consommateurs à renoncer à tout recours collectif en justice.",
     "FCAW", "class_action_waiver"),
    ("nondisclosure_agreement_abuse_rights_engine.py",
     "Accords de confidentialité & abus au travail", "Wave 862",
     "NDA imposés aux victimes de harcèlement les condamnant au silence perpétuel.",
     "NDCA", "nda_abuse"),
    ("metoo_silencing_nda_rights_engine.py",
     "Mouvement MeToo & bâillonnement juridique", "Wave 862",
     "Victimes de harcèlement sexuel sous NDA ignorées par la justice.",
     "MESI", "metoo_silencing"),

    # Wave 863 — Poursuites stratégiques & activisme
    ("SLAPP_suit_journalist_rights_engine.py",
     "Procès-bâillon & journalistes ciblés", "Wave 863",
     "Poursuites stratégiques (SLAPP) ruinant les journalistes et bâillonnant l'investigation.",
     "SLPJ", "slapp_journalist"),
    ("RICO_lawsuit_activist_rights_engine.py",
     "Poursuites RICO contre les militants", "Wave 863",
     "Lois antirackette détournées pour criminaliser les activistes écologiques et sociaux.",
     "RLAC", "rico_activist"),
    ("child_support_enforcement_trap_rights_engine.py",
     "Pension alimentaire & piège de l'endettement", "Wave 863",
     "Pères pauvres emprisonnés pour non-paiement de pensions alimentaires impossibles à honorer.",
     "CSTE", "child_support_trap"),

    # Wave 864 — Finance prédatrice & abus tutélaires
    ("elder_financial_abuse_attorney_rights_engine.py",
     "Abus financiers sur les aînés & mandataires", "Wave 864",
     "Tuteurs légaux ou mandataires dilapidant l'épargne de personnes âgées vulnérables.",
     "EFPA", "elder_attorney_abuse"),
    ("reverse_mortgage_predatory_rights_engine.py",
     "Hypothèques inversées prédatrices & aînés", "Wave 864",
     "Produits d'hypothèque inversée dépouillant les aînés de leur logement.",
     "RMPD", "reverse_mortgage"),
    ("structured_settlement_exploitation_rights_engine.py",
     "Rachats de rentes structurées & victimes", "Wave 864",
     "Victimes de blessures poussées à vendre leurs rentes à des rachats prédateurs.",
     "SSET", "structured_settlement"),
]
