# Specs waves 1201-1208 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1201 — Immigration: effets chilling & bénéfices (inédits)
    ("immigrant_public_charge_chilling_rights_engine.py",
     "Effet chilling de la règle public charge & droits des immigrants légaux à recevoir des aides sans crainte de déportation", "Wave 1201",
     "Immigrants légaux évitant des aides essentielles comme Medicaid par crainte d'être classés public charge lors de leur renouvellement.",
     "PCCE", "public_charge_chill"),
    ("eitc_undocumented_exclusion_rights_engine.py",
     "Exclusion des sans-papiers du crédit d'impôt sur le revenu gagné EITC & impact sur les familles à faibles revenus", "Wave 1201",
     "Travailleurs sans-papiers contribuant au système fiscal américain exclus de l'EITC malgré des années de cotisations.",
     "EITC", "eitc_undoc_exclus"),
    ("immigrant_medicaid_waiting_period_rights_engine.py",
     "Délai de carence Medicaid de 5 ans pour immigrants légaux & droits des nouveaux résidents permanents à la couverture maladie", "Wave 1201",
     "Immigrants légaux en attente de leur 5 ans de résidence permanente sans accès à Medicaid malgré paiement d'impôts.",
     "IMWP", "immigr_medicaid_wait"),

    # Wave 1202 — Finance: audits, impôts & essais cliniques (inédits)
    ("clinical_trial_insurance_coverage_rights_engine.py",
     "Couverture d'assurance pour les soins de routine lors des essais cliniques & refus de prise en charge des coûts corrélés", "Wave 1202",
     "Patients participant à des essais cliniques refusés de couverture pour les soins de routine directement liés à l'essai.",
     "CTCI", "clin_trial_insur"),
    ("tax_audit_frequency_race_rights_engine.py",
     "Disparités raciales dans la fréquence des audits IRS & ciblage disproportionné des contribuables noirs à faibles revenus", "Wave 1202",
     "Contribuables noirs à faibles revenus audités à des taux disproportionnés par rapport aux contribuables blancs de même revenus.",
     "TAFE", "tax_audit_freq_race"),
    ("tax_refund_delay_low_income_rights_engine.py",
     "Délais de remboursement fiscal disproportionnés pour les contribuables à faibles revenus & impact sur la stabilité financière", "Wave 1202",
     "Familles à faibles revenus dépendant de remboursements d'impôts comme coussin financier confrontées à des délais de 6-8 semaines.",
     "TXAR", "tax_refund_delay"),

    # Wave 1203 — Technologie: IA & décisions automatisées (inédits)
    ("ai_facial_recognition_false_arrest_rights_engine.py",
     "Arrestations erronées causées par la reconnaissance faciale IA & absence de recours pour les personnes faussement identifiées", "Wave 1203",
     "Personnes innocentes arrêtées suite à des erreurs de systèmes de reconnaissance faciale IA sans mécanisme de recours clair.",
     "AIRF", "ai_facial_false_arr"),
    ("facial_recognition_wrongful_id_rights_engine.py",
     "Mauvaise identification par reconnaissance faciale dans les enquêtes & droits à la contestation des preuves biométriques", "Wave 1203",
     "Suspects identifiés à tort par des systèmes biométriques dans des enquêtes criminelles sans possibilité de contester la preuve.",
     "FRAR", "facial_wrong_id"),
    ("prosecutor_diversion_access_rights_engine.py",
     "Accès équitable aux programmes de déjudiciarisation par les procureurs & disparités raciales dans l'attribution des alternatives", "Wave 1203",
     "Accusés noirs et latinos moins souvent orientés vers des programmes de déjudiciarisation que leurs homologues blancs pour des crimes similaires.",
     "EPRP", "prosecutor_divers"),

    # Wave 1204 — Famille: droits familiaux complexes (inédits)
    ("child_support_imputed_income_rights_engine.py",
     "Revenus imputés dans les ordonnances de pension alimentaire & injustice envers les parents au chômage involontaire", "Wave 1204",
     "Parents sans emploi contraints de payer des pensions basées sur un revenu fictif imputé alors qu'ils cherchent activement du travail.",
     "CSIM", "child_support_imput"),
    ("legal_father_paternity_fraud_rights_engine.py",
     "Fraude à la paternité légale & droits des pères légaux contraints de payer pour des enfants biologiquement non liés", "Wave 1204",
     "Hommes découvrant qu'ils ne sont pas le père biologique d'un enfant contraints de continuer à payer la pension alimentaire.",
     "LFCR", "legal_father_fraud"),
    ("adult_adoption_legal_right_rights_engine.py",
     "Adoption d'adultes & droits aux procédures simplifiées pour formaliser des liens de famille établis de longue date", "Wave 1204",
     "Adultes souhaitant formaliser légalement des liens parent-enfant établis durant l'enfance confrontés à des procédures complexes.",
     "ADEC", "adult_adoption_right"),

    # Wave 1205 — Santé: tests génétiques & médecine de précision (inédits)
    ("brca_genetic_testing_insurance_rights_engine.py",
     "Couverture d'assurance pour les tests génétiques BRCA & refus de prise en charge pour les femmes à risque héréditaire", "Wave 1205",
     "Femmes avec antécédents familiaux de cancer du sein se voyant refuser la couverture des tests BRCA par leur assureur.",
     "BRCA", "brca_test_insur"),
    ("employer_genetic_discrimination_rights_engine.py",
     "Discrimination génétique par les employeurs & violations insuffisamment poursuivies de la loi GINA sur les informations génétiques", "Wave 1205",
     "Employés dont les informations génétiques sont utilisées illégalement par leur employeur dans des décisions d'embauche ou de promotion.",
     "BRCG", "employer_genetic"),
    ("clinical_trial_access_minority_rights_engine.py",
     "Accès des minorités aux essais cliniques & sous-représentation systématique dans la recherche médicale causant des biais", "Wave 1205",
     "Patients noirs et latinos exclus ou sous-représentés dans les essais cliniques menant à des traitements moins adaptés à leur génétique.",
     "CTIA", "clin_trial_minor"),

    # Wave 1206 — Environnement: transport & pollution (inédits)
    ("school_bus_electric_conversion_rights_engine.py",
     "Conversion des bus scolaires diesel en électrique & droits des enfants défavorisés à ne plus respirer des émissions toxiques", "Wave 1206",
     "Élèves dans des districts scolaires pauvres exposés aux émissions diesel de vieilles flottes non électrifiées sans date de conversion.",
     "WBSC", "school_bus_electric"),
    ("pipeline_safety_fenceline_rights_engine.py",
     "Sécurité des pipelines dans les communautés riveraines & droits des résidents à l'information sur les risques de rupture", "Wave 1206",
     "Communautés vivant à proximité de pipelines vétustes sans information adéquate sur les risques d'explosion ou de fuite.",
     "PCTR", "pipeline_safety_fence"),
    ("oil_industry_community_air_rights_engine.py",
     "Pollution atmosphérique des installations pétrolières & droits des communautés à l'air pur sans cumul d'impacts environnementaux", "Wave 1206",
     "Résidents de quartiers industriels exposés à des émissions multiples de raffineries et d'usines sans évaluation cumulative d'impact.",
     "OICA", "oil_industry_air"),

    # Wave 1207 — Tech & médias: discrimination par algorithme (inédits)
    ("social_media_ad_housing_discrimination_rights_engine.py",
     "Discrimination dans les publicités immobilières sur réseaux sociaux & ciblage algorithmique excluant les minorités", "Wave 1207",
     "Personnes noires et latinos ne voyant pas les annonces immobilières ciblées par algorithmes sur Facebook et Instagram dans leur zone.",
     "FBAM", "social_ad_housing"),
    ("timeshare_exit_fraud_rights_engine.py",
     "Arnaques aux entreprises de sortie de timeshare & droits des propriétaires à résilier sans payer des frais frauduleux", "Wave 1207",
     "Propriétaires de timeshare piégés par des entreprises de sortie frauduleuses qui prennent des milliers sans obtenir la résiliation.",
     "TCAA", "timeshare_exit_fraud"),
    ("restorative_justice_access_rights_engine.py",
     "Accès aux programmes de justice restauratrice & droits des victimes et accusés à choisir des alternatives aux procédures pénales", "Wave 1207",
     "Victimes et accusés intéressés par la justice restauratrice sans accès à ces programmes dans leur juridiction.",
     "RTCP", "restorat_justice_acc"),

    # Wave 1208 — Droits complexes: travailleurs & santé (inédits)
    ("chemical_plant_community_right_know_rights_engine.py",
     "Droit des communautés à savoir sur les produits chimiques des usines voisines & lacunes du Toxic Release Inventory", "Wave 1208",
     "Résidents proches d'usines chimiques ignorant quels produits dangereux sont stockés et émis faute d'information accessible.",
     "PCTM", "chem_plant_comm"),
    ("automatic_clean_slate_expungement_rights_engine.py",
     "Effacement automatique des casiers judiciaires par les lois clean slate & manque d'implémentation dans de nombreux États", "Wave 1208",
     "Personnes éligibles à l'effacement automatique de leur casier dans des États avec loi clean slate qui ne l'implémentent pas en pratique.",
     "ASCA", "auto_clean_slate"),
    ("exchange_student_visa_rights_engine.py",
     "Droits des étudiants en programme d'échange J-1 & exploitation par des employeurs sponsors non régulés", "Wave 1208",
     "Étudiants d'échange J-1 exploités par des sponsors d'emploi leur imposant des conditions illégales sous menace de fin de visa.",
     "EXCH", "exchange_student_visa"),
]
