# Specs waves 825-832 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 825 — Harcèlement médiatique & vie privée des célébrités
    ("paparazzi_harassment_privacy_rights_engine.py",
     "Paparazzi & harcèlement des personnalités publiques", "Wave 825",
     "Photographes intrusifs harcelant personnalités et familles au mépris de leur vie privée.",
     "PPHD", "paparazzi_harassment"),
    ("celebrity_stalker_law_failure_rights_engine.py",
     "Traque de célébrités & défaillance légale", "Wave 825",
     "Lois insuffisantes protégeant personnalités et anonymes contre les harceleurs obsessionnels.",
     "CSLAW", "celebrity_stalker"),
    ("parasocial_exploitation_fan_rights_engine.py",
     "Exploitation des fans & manipulation parasociale", "Wave 825",
     "Créateurs exploitant des liens parasociaux pour extorquer argent et loyauté aux fans.",
     "PSEX", "parasocial_exploit"),

    # Wave 826 — Facturation médicale abusive
    ("funeral_price_gouging_rights_engine.py",
     "Pompes funèbres & surfacturation des familles en deuil", "Wave 826",
     "Familles en deuil exploitées par des prix opaques et abusifs de pompes funèbres.",
     "FPGU", "funeral_gouging"),
    ("hospital_billing_surprise_rights_engine.py",
     "Factures hospitalières surprises & faillite médicale", "Wave 826",
     "Factures médicales imprévues ruinant des patients après des soins urgents.",
     "HBSU", "hospital_surprise_bill"),
    ("ambulance_upcoding_fraud_rights_engine.py",
     "Surfacturation ambulancière & fraude médicale", "Wave 826",
     "Prestataires d'ambulance surfacturant des soins non prodigués aux patients vulnérables.",
     "AMBU", "ambulance_upcoding"),

    # Wave 827 — Fraudes caritatives & détournements
    ("charity_fraud_donation_theft_rights_engine.py",
     "Fraude caritative & vol aux donateurs", "Wave 827",
     "Fausses associations détournant les dons destinés aux victimes de catastrophes.",
     "CFKE", "charity_fraud"),
    ("orphanage_donation_diversion_rights_engine.py",
     "Orphelinats & détournement de dons", "Wave 827",
     "Dons humanitaires détournés au profit des gestionnaires d'orphelinats frauduleux.",
     "ODDI", "orphanage_diversion"),
    ("homecare_elder_fraud_rights_engine.py",
     "Fraude aux soins à domicile & personnes âgées", "Wave 827",
     "Prestataires de soins à domicile facturant des interventions fictives aux aînés.",
     "HCFE", "homecare_elder_fraud"),

    # Wave 828 — Amendes régressives & accès à la justice
    ("court_fine_poverty_trap_rights_engine.py",
     "Amendes judiciaires & piège de la pauvreté", "Wave 828",
     "Amendes et frais de justice emprisonnant les pauvres dans des spirales d'endettement.",
     "CTFI", "court_fine_poverty"),
    ("traffic_fine_regressive_rights_engine.py",
     "Amendes routières régressives & inégalité", "Wave 828",
     "Contraventions forfaitaires pesant infiniment plus sur les bas revenus.",
     "TRFR", "traffic_fine_regressive"),
    ("library_fine_poor_access_rights_engine.py",
     "Amendes bibliothèques & exclusion des pauvres", "Wave 828",
     "Amendes de bibliothèque coupant les enfants pauvres de l'accès aux livres.",
     "LIBF", "library_fine"),

    # Wave 829 — Services essentiels & logement
    ("water_shutoff_low_income_rights_engine.py",
     "Coupures d'eau & ménages à faibles revenus", "Wave 829",
     "Coupures d'eau pour impayés exposant des familles à des risques sanitaires graves.",
     "WSLI", "water_shutoff"),
    ("utility_deposit_barrier_rights_engine.py",
     "Cautions d'énergie & barrière à l'accès", "Wave 829",
     "Cautions exorbitantes pour l'électricité bloquant l'accès aux ménages précaires.",
     "UDBR", "utility_deposit"),
    ("eviction_notice_retaliatory_rights_engine.py",
     "Expulsion locative de représailles", "Wave 829",
     "Propriétaires expulsant des locataires en représailles de plaintes légitimes.",
     "ENRW", "retaliatory_eviction"),

    # Wave 830 — Logement & sans-abrisme
    ("rent_withholding_retaliation_rights_engine.py",
     "Rétention de loyer & représailles", "Wave 830",
     "Locataires poursuivis pour avoir légalement retenu leur loyer en raison d'insalubrité.",
     "RRWR", "rent_withholding"),
    ("security_deposit_theft_tenant_rights_engine.py",
     "Vol de caution locative", "Wave 830",
     "Propriétaires ne restituant pas les cautions sans justification légale.",
     "SDTH", "deposit_theft"),
    ("motel_voucher_homelessness_rights_engine.py",
     "Vouchers de motel & sans-abrisme temporaire", "Wave 830",
     "Sans-abri entassés dans des motels vétustes sans transition vers un logement stable.",
     "MTVH", "motel_homelessness"),

    # Wave 831 — Zonage exclusionnaire & logement social
    ("zoning_exclusionary_housing_rights_engine.py",
     "Zonage exclusionnaire & ségrégation résidentielle", "Wave 831",
     "Règles de zonage barrant l'accès des ménages pauvres aux quartiers prospères.",
     "ZEHO", "exclusionary_zoning"),
    ("accessory_dwelling_permit_barrier_rights_engine.py",
     "Permis de logement accessoire & blocage réglementaire", "Wave 831",
     "Réglementations bloquant la construction de logements abordables sur terrains existants.",
     "ADPU", "accessory_dwelling"),
    ("manufactured_home_community_rights_engine.py",
     "Parcs de maisons mobiles & droits des résidents", "Wave 831",
     "Résidents de parcs de mobil-homes expulsés ou exploités par des propriétaires de parcs.",
     "MHCO", "manufactured_home"),

    # Wave 832 — Nuisances environnementales & voisinage
    ("noise_pollution_sleep_deprivation_rights_engine.py",
     "Pollution sonore & privation de sommeil", "Wave 832",
     "Nuisances sonores chroniques détruisant la santé et la qualité de vie des riverains.",
     "NOPS", "noise_sleep"),
    ("social_housing_waitlist_rights_engine.py",
     "Listes d'attente HLM & droit au logement", "Wave 832",
     "Familles attendant des années un logement social sans priorité ni recours.",
     "SHWL", "social_housing_wait"),
    ("cancer_charity_scam_rights_engine.py",
     "Escroqueries caritatives aux malades du cancer", "Wave 832",
     "Faux organismes récoltant des fonds pour les cancéreux sans reversement aux malades.",
     "CCSC", "cancer_charity_scam"),
]
