# Specs waves 1041-1048 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# Remplacement : sickle_cell_adult(trop proche)→lupus_nephritis (SCAR→LNAC)
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1041 — Santé & maladies spécifiques (inédits)
    ("lupus_nephritis_access_rights_engine.py",
     "Lupus rénal & accès inégal aux biothérapies coûteuses", "Wave 1041",
     "Patients atteints de néphrite lupique sans accès aux biothérapies innovantes faute de couverture assurance.",
     "LNAC", "lupus_nephritis"),
    ("endometriosis_diagnosis_delay_rights_engine.py",
     "Retard de diagnostic de l'endométriose & souffrance prolongée des femmes", "Wave 1041",
     "Femmes attendant 7 à 10 ans un diagnostic d'endométriose en raison du manque de formation médicale.",
     "EDDR", "endometriosis_delay"),
    ("celiac_disease_military_rights_engine.py",
     "Maladie cœliaque dans l'armée & accès au régime sans gluten en garnison", "Wave 1041",
     "Soldats atteints de maladie cœliaque refusés ou incapables de maintenir un régime sans gluten en déploiement.",
     "CGDM", "celiac_military"),

    # Wave 1042 — Logement & discrimination financière (inédits)
    ("condo_association_selective_rights_engine.py",
     "Application sélective des règles de copropriété & discrimination raciale", "Wave 1042",
     "Copropriétés appliquant leurs règlements de manière discriminatoire contre les résidents de couleur.",
     "CASR", "condo_discrim"),
    ("homeowner_insurance_redlining_rights_engine.py",
     "Redlining d'assurance habitation & discrimination algorithmique raciale", "Wave 1042",
     "Propriétaires dans des quartiers à majorité noire refusés ou surfacturés par les assureurs habitation.",
     "HIRN", "homeown_insur_redline"),
    ("natural_disaster_insurance_denial_rights_engine.py",
     "Refus d'indemnisation après catastrophe naturelle & droits des sinistrés", "Wave 1042",
     "Propriétaires refusés ou sous-indemnisés après un ouragan ou une inondation par les assureurs.",
     "NDID", "disaster_insur_deny"),

    # Wave 1043 — Immigration & intégration professionnelle (inédits)
    ("green_card_medical_exam_barrier_rights_engine.py",
     "Examens médicaux pour carte verte & coûts prohibitifs pour les demandeurs", "Wave 1043",
     "Demandeurs de carte verte contraints à des examens médicaux coûteux non couverts sans aide disponible.",
     "GCME", "green_card_medical"),
    ("daca_professional_license_rights_engine.py",
     "DACA & barrières aux licences professionnelles pour les Dreamers", "Wave 1043",
     "Bénéficiaires DACA qualifiés refusés pour des licences professionnelles d'État malgré des diplômes valides.",
     "DPLR", "daca_prof_license"),
    ("asylee_employment_auth_rights_engine.py",
     "Autorisation d'emploi des réfugiés & délais excessifs de traitement", "Wave 1043",
     "Demandeurs d'asile incapables de travailler légalement pendant des mois d'attente administrative.",
     "AEAU", "asylee_work_auth"),

    # Wave 1044 — Droits des travailleurs : congés & protections (inédits)
    ("bereavement_leave_rights_engine.py",
     "Congé de deuil & absence de protection légale fédérale standard", "Wave 1044",
     "Travailleurs forcés de reprendre immédiatement le travail après un décès familial sans congé légal garanti.",
     "BLST", "bereavement_leave"),
    ("jury_duty_retaliation_rights_engine.py",
     "Représailles après service comme juré & droits des travailleurs", "Wave 1044",
     "Employés sanctionnés ou licenciés pour avoir accompli leur devoir de juré malgré les protections légales.",
     "JDRY", "jury_duty_retalia"),
    ("military_leave_employer_retaliation_rights_engine.py",
     "Représailles patronales contre les réservistes appelés en service actif", "Wave 1044",
     "Réservistes militaires licenciés ou discriminés à leur retour de service en violation de l'USERRA.",
     "MLRE", "military_leave_retalia"),

    # Wave 1045 — Eau, sol & agriculture (inédits)
    ("soil_contamination_urban_farm_rights_engine.py",
     "Contamination des sols des jardins urbains & sécurité alimentaire locale", "Wave 1045",
     "Jardins urbains installés sur des terrains contaminés sans test obligatoire exposant les mangeurs.",
     "SCUF", "soil_urban_farm"),
    ("aquifer_depletion_rights_engine.py",
     "Épuisement des aquifères & droits des communautés rurales à l'eau souterraine", "Wave 1045",
     "Agriculteurs et communautés rurales perdant leur eau souterraine face aux grandes exploitations agro-industrielles.",
     "AQDR", "aquifer_depletion"),
    ("drought_water_rationing_rights_engine.py",
     "Rationnement de l'eau en période de sécheresse & droits des petits usagers", "Wave 1045",
     "Petits agriculteurs et ménages défavorisés subissant des restrictions d'eau plus sévères que les grandes entreprises.",
     "DWRN", "drought_ration"),

    # Wave 1046 — Cybersécurité & droits des victimes numériques (inédits)
    ("ransomware_victim_government_rights_engine.py",
     "Victimes de ransomware ciblant des services publics & responsabilité gouvernementale", "Wave 1046",
     "Citoyens sans accès aux services essentiels après des cyberattaques paralysant les systèmes gouvernementaux.",
     "RVGR", "ransomware_gov_victim"),
    ("data_breach_notification_delay_rights_engine.py",
     "Délais de notification des violations de données & droits des victimes", "Wave 1046",
     "Victimes de violations de données notifiées des mois après l'incident, empêchant une protection rapide.",
     "DBNL", "data_breach_notify"),
    ("identity_theft_recovery_rights_engine.py",
     "Processus de récupération après vol d'identité & obstacles bureaucratiques", "Wave 1046",
     "Victimes de vol d'identité passant des années à corriger des dossiers de crédit et des poursuites injustes.",
     "ITRB", "identity_theft_recover"),

    # Wave 1047 — Communautés géographiquement isolées (inédits)
    ("colonias_water_access_rights_engine.py",
     "Accès à l'eau potable dans les colonias de la frontière américano-mexicaine", "Wave 1047",
     "Résidents des colonias vivant sans eau courante ni égouts dans des zones non incorporées frontalières.",
     "CLWA", "colonias_water"),
    ("tribal_internet_access_rights_engine.py",
     "Accès internet dans les réserves tribales & fracture numérique autochtone", "Wave 1047",
     "Nations tribales sans connexion internet fiable excluant leurs membres des services en ligne et de l'éducation.",
     "TRIA", "tribal_internet"),
    ("puerto_rico_hurricane_aid_rights_engine.py",
     "Aide humanitaire après Maria à Porto Rico & discrimination fédérale", "Wave 1047",
     "Résidents de Porto Rico recevant une aide fédérale de catastrophe inférieure à celle accordée aux États continentaux.",
     "PRHA", "pr_hurricane_aid"),

    # Wave 1048 — Sport & santé des athlètes (inédits)
    ("female_athlete_triad_rights_engine.py",
     "Triade de l'athlète féminine & pression institutionnelle sur les sportives", "Wave 1048",
     "Athlètes féminines souffrant de la triade (os/énergie/cycle) sous pression des entraîneurs pour perdre du poids.",
     "FATR", "female_athlete_triad"),
    ("youth_sport_specialization_injury_rights_engine.py",
     "Spécialisation sportive précoce chez les jeunes & blessures chroniques", "Wave 1048",
     "Enfants poussés à se spécialiser dans un sport unique dès 8 ans, développant des blessures de surmenage chroniques.",
     "SSIY", "sport_spec_injury"),
    ("adaptive_sport_access_rights_engine.py",
     "Accès aux sports adaptés pour les personnes handicapées & équité de financement", "Wave 1048",
     "Athlètes handicapés avec accès insuffisant aux programmes sportifs adaptés faute de financement équitable.",
     "ASAP", "adaptive_sport"),
]
