# Specs waves 1001-1008 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# Remplacements : night_shift_cancer (existe) → shift_work_sleep ; naloxone (existe) → suboxone_tapering
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1001 — Propriété intellectuelle & droits des artistes
    ("folk_art_copyright_rights_engine.py",
     "Droits d'auteur des artistes folk & protection de l'art traditionnel", "Wave 1001",
     "Artistes folk et artisans traditionnels dont les œuvres sont copiées sans attribution ni rémunération.",
     "FACR", "folk_art_copyright"),
    ("ai_generated_art_copyright_rights_engine.py",
     "Droits d'auteur de l'art généré par IA & droits des artistes originaux", "Wave 1001",
     "Artistes humains dont le style et œuvres sont reproduits sans consentement par des modèles d'IA génératifs.",
     "AIGC", "ai_art_copyright"),
    ("musician_work_for_hire_rights_engine.py",
     "Contrats work-for-hire des musiciens & perte des droits sur leur musique", "Wave 1001",
     "Musiciens cédant les droits permanents sur leurs créations via des clauses work-for-hire abusives.",
     "MWFH", "musician_work_hire"),

    # Wave 1002 — Espaces publics & marginalisation des sans-abri
    ("park_curfew_youth_rights_engine.py",
     "Couvre-feux dans les parcs publics & discrimination envers les jeunes", "Wave 1002",
     "Jeunes et minorités ciblés par des couvre-feux municipaux dans les parcs sans fondement légal clair.",
     "PCYR", "park_curfew_youth"),
    ("public_bench_removal_rights_engine.py",
     "Suppression de bancs publics & criminalisation de la pauvreté urbaine", "Wave 1002",
     "Villes retirant bancs et abris publics pour décourager les sans-abri sans solutions alternatives.",
     "PBRH", "public_bench_remove"),
    ("community_garden_eviction_rights_engine.py",
     "Expulsion des jardins communautaires & droits des résidents urbains", "Wave 1002",
     "Jardins communautaires en milieu urbain détruits pour des projets immobiliers sans compensation ni relogement.",
     "CGER", "community_garden_evict"),

    # Wave 1003 — Travailleurs saisonniers spécifiques
    ("ski_resort_seasonal_worker_rights_engine.py",
     "Droits des travailleurs saisonniers de stations de ski", "Wave 1003",
     "Travailleurs saisonniers des stations de ski logés par l'employeur sans droits stables ni recours en cas d'abus.",
     "SRWR", "ski_seasonal_worker"),
    ("camp_counselor_misclass_rights_engine.py",
     "Mauvaise classification des moniteurs de camps & violation FLSA", "Wave 1003",
     "Moniteurs de camps d'été traités comme bénévoles ou mal rémunérés en violation des règles FLSA.",
     "CCMR", "camp_counselor"),
    ("summer_intern_nonprofit_rights_engine.py",
     "Stagiaires non rémunérés des ONG & exploitation légalisée", "Wave 1003",
     "Organisations à but non lucratif exploitant des stagiaires non payés qui accomplissent le travail de salariés.",
     "SINP", "summer_intern_nonprofit"),

    # Wave 1004 — Accessibilité numérique & personnes handicapées
    ("web_accessibility_lawsuit_rights_engine.py",
     "Procès en accessibilité web & droits ADA des utilisateurs handicapés", "Wave 1004",
     "Sites web refusant de se conformer aux normes WCAG, bloquant l'accès aux personnes handicapées.",
     "WARR", "web_access_lawsuit"),
    ("blind_ebook_drm_rights_engine.py",
     "DRM des e-books & exclusion des lecteurs aveugles", "Wave 1004",
     "Protections DRM des livres numériques incompatibles avec les lecteurs d'écran pour aveugles.",
     "BEDR", "blind_ebook_drm"),
    ("deaf_podcast_captioning_rights_engine.py",
     "Absence de sous-titrage des podcasts & exclusion des sourds", "Wave 1004",
     "Podcasts et contenus audio sans transcription ni sous-titres, inaccessibles aux personnes sourdes ou malentendantes.",
     "DPCS", "deaf_podcast_caption"),

    # Wave 1005 — Logement étudiant & droits sur le campus
    ("on_campus_housing_retaliation_rights_engine.py",
     "Représailles sur le logement campus & droits des étudiants activistes", "Wave 1005",
     "Étudiants activistes ou plaignants perdant leur logement campus comme forme de représailles institutionnelles.",
     "OHRE", "campus_housing_retaliate"),
    ("off_campus_lease_trap_rights_engine.py",
     "Baux pièges hors campus & exploitation des étudiants locataires", "Wave 1005",
     "Étudiants piégés dans des baux annuels non résiliables proches des campus avec clauses abusives.",
     "OLTR", "off_campus_lease"),
    ("student_food_insecurity_campus_rights_engine.py",
     "Insécurité alimentaire des étudiants sur les campus universitaires", "Wave 1005",
     "Étudiants incapables de se nourrir correctement sur les campus sans accès aux programmes d'aide alimentaire.",
     "SFIC", "student_food_campus"),

    # Wave 1006 — Traitement des dépendances & accès aux soins
    ("addiction_treatment_waitlist_rights_engine.py",
     "Listes d'attente pour traitement des addictions & droits à la vie", "Wave 1006",
     "Personnes dépendantes mourant pendant des mois d'attente pour accéder à des programmes de traitement.",
     "ATWL", "addiction_waitlist"),
    ("suboxone_tapering_access_rights_engine.py",
     "Accès à la buprénorphine pour sevrage & restrictions médicales abusives", "Wave 1006",
     "Patients en sevrage aux opioïdes refusés ou interrompus dans leur traitement à la buprénorphine.",
     "SXBR", "suboxone_access"),
    ("methadone_clinic_nimby_rights_engine.py",
     "Opposition NIMBY aux cliniques méthadone & accès aux soins", "Wave 1006",
     "Cliniques méthadone refusées par des municipalités cédant à la pression des riverains contre les patients.",
     "MNMB", "methadone_nimby"),

    # Wave 1007 — Transport actif & mobilité urbaine
    ("bike_lane_removal_rights_engine.py",
     "Suppression de pistes cyclables & droits des cyclistes", "Wave 1007",
     "Villes supprimant des pistes cyclables sous pression automobile sans recours pour les usagers vélos.",
     "BKRL", "bike_lane_remove"),
    ("pedestrian_crosswalk_safety_rights_engine.py",
     "Sécurité des passages piétons & responsabilité des municipalités", "Wave 1007",
     "Piétons tués ou blessés aux passages dangereux malgré des demandes répétées d'amélioration ignorées.",
     "PCSW", "pedestrian_crosswalk"),
    ("wheelchair_paratransit_wait_rights_engine.py",
     "Temps d'attente paratransit & droits à la mobilité des personnes handicapées", "Wave 1007",
     "Utilisateurs de fauteuils roulants attendant des heures le paratransit en raison de sous-financement chronique.",
     "WPTR", "wheelchair_paratransit"),

    # Wave 1008 — Santé des travailleurs de nuit & horaires décalés
    ("shift_work_sleep_disorder_rights_engine.py",
     "Troubles du sommeil des travailleurs postés & droits aux accommodations", "Wave 1008",
     "Travailleurs en horaires décalés souffrant de troubles du sommeil chroniques sans droit à aménagement.",
     "SHWS", "shift_work_sleep"),
    ("graveyard_shift_childcare_rights_engine.py",
     "Garde d'enfants pour travailleurs de nuit & désert de services", "Wave 1008",
     "Parents travaillant la nuit sans accès à une garde d'enfants adaptée aux horaires nocturnes.",
     "GVSC", "graveyard_childcare"),
    ("overnight_worker_safety_rights_engine.py",
     "Sécurité des travailleurs seuls de nuit & isolement professionnel", "Wave 1008",
     "Travailleurs isolés la nuit sans protocole de sécurité ni moyen de communication en cas d'urgence.",
     "ONWS", "overnight_worker"),
]
