# Specs waves 1297-1304 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1297 — Santé infectieuse & discrimination (inédits)
    ("hiv_employment_discrimination_rights_engine.py",
     "Discrimination à l'emploi liée au VIH & protection ADA des personnes séropositives contre les licenciements fondés sur le statut VIH", "Wave 1297",
     "Personnes séropositives traitées et indétectables se voyant licenciées ou refuser un emploi après divulgation de leur statut sérologique.",
     "HIVE", "hiv_employ_discrim"),
    ("hepatitis_c_treatment_access_rights_engine.py",
     "Accès aux traitements antiviraux curatifs de l'hépatite C & refus d'assurance limitant les DAA aux stades avancés de la maladie", "Wave 1297",
     "Personnes atteintes d'hépatite C chronique se voyant refuser les antiviraux curatifs pan-génotypiques en raison de restrictions d'assurance basées sur la fibrose.",
     "HDAC", "hep_c_treatment"),
    ("hiv_prep_insurance_coverage_rights_engine.py",
     "Couverture d'assurance pour la PrEP contre le VIH & droits des personnes à haut risque à une prophylaxie pré-exposition sans copaiements", "Wave 1297",
     "Personnes à haut risque de VIH éligibles à la PrEP se heurtant à des copaiements élevés ou des exigences d'autorisation préalable limitant l'accès.",
     "PREP", "hiv_prep_cover"),

    # Wave 1298 — Logement: urgences & transitions (inédits)
    ("transitional_housing_reentry_barriers_rights_engine.py",
     "Obstacles au logement de transition pour les sortants de prison & droits à un accès non discriminatoire malgré le casier judiciaire", "Wave 1298",
     "Personnes sortant de prison incapables de trouver un logement de transition en raison de politiques de refus automatique basées sur le casier judiciaire.",
     "THRB", "transit_housing_barrier"),
    ("domestic_violence_lease_termination_rights_engine.py",
     "Résiliation de bail pour les survivants de violence domestique & droits à rompre un bail sans pénalité pour fuir un domicile dangereux", "Wave 1298",
     "Victimes de violence domestique cherchant à fuir leur domicile confrontées à des pénalités de résiliation de bail dans des États sans protection légale spécifique.",
     "DLET", "dv_lease_terminat"),
    ("habitability_indoor_air_quality_rights_engine.py",
     "Habitabilité et qualité de l'air intérieur dans les logements locatifs & droits des locataires contre les polluants comme la moisissure et les COV", "Wave 1298",
     "Locataires vivant dans des logements avec une qualité d'air intérieur dégradée par des moisissures, revêtements de sol ou peintures toxiques sans recours légal efficace.",
     "HABM", "habitab_indoor_air"),

    # Wave 1299 — Justice: droits post-condamnation (inédits)
    ("sex_offender_registry_tier_challenge_rights_engine.py",
     "Contestation du niveau de classification dans le registre des délinquants sexuels & droits à une révision individuelle basée sur le risque réel", "Wave 1299",
     "Personnes classées au niveau le plus élevé du registre des délinquants sexuels sans évaluation individuelle du risque et sans voie de reclassification.",
     "SXRR", "sex_offender_tier"),
    ("life_sentence_parole_eligibility_rights_engine.py",
     "Éligibilité à la libération conditionnelle pour les condamnés à perpétuité & droits des détenus condamnés avant 18 ans à un réexamen de sentence", "Wave 1299",
     "Personnes condamnées à perpétuité pour des crimes commis mineures n'ayant pas accès à une audience de libération conditionnelle malgré les arrêts de la Cour Suprême.",
     "LSPE", "life_sentence_parole"),
    ("good_time_credit_calculation_rights_engine.py",
     "Calcul des crédits de bonne conduite pour les détenus & droits à un calcul correct et à un recours en cas d'application erronée des remises de peine", "Wave 1299",
     "Détenus se voyant incorrectement calculer leurs crédits de remise de peine pour bonne conduite, prolongeant leur détention au-delà de la date légale de libération.",
     "SGTC", "good_time_credit"),

    # Wave 1300 — Santé: maladies neurologiques graves (inédits)
    ("huntington_disease_genetic_privacy_rights_engine.py",
     "Confidentialité des tests génétiques pour la maladie de Huntington & droits des personnes à risque contre la discrimination fondée sur les résultats", "Wave 1300",
     "Personnes issues de familles avec Huntington choisissant de ne pas se faire tester par crainte de discrimination à l'assurance ou à l'emploi malgré la GINA.",
     "HNGT", "huntington_genetic"),
    ("als_patient_care_rights_engine.py",
     "Droits des patients SLA à des soins continus & accès aux équipements de communication alternative et aux soins palliatifs intensifs à domicile", "Wave 1300",
     "Patients atteints de SLA se heurtant à des refus d'assurance pour des dispositifs de communication alternative ou de ventilation à domicile indispensables à leur autonomie.",
     "ALSR", "als_patient_care"),
    ("muscular_dystrophy_equipment_rights_engine.py",
     "Couverture des équipements médicaux pour la dystrophie musculaire & droits des patients à un accès aux dispositifs d'assistance respiratoire et de mobilité", "Wave 1300",
     "Patients atteints de dystrophie musculaire se voyant refuser des équipements de ventilation, fauteuils motorisés et dispositifs de toux assistée vitaux.",
     "MDQR", "muscular_dystrophy_eq"),

    # Wave 1301 — Finance: hypothèques (inédits)
    ("dual_tracking_mortgage_rights_engine.py",
     "Double suivi dans les modifications de prêt hypothécaire & droits des propriétaires contre la poursuite simultanée d'une modification et d'une saisie", "Wave 1301",
     "Propriétaires en cours de demande de modification de prêt découvrant que leur prestataire avance simultanément la procédure de saisie en violation de la loi.",
     "DTMR", "dual_tracking_mortgage"),
    ("force_placed_insurance_mortgage_rights_engine.py",
     "Assurance imposée par les prêteurs hypothécaires & droits des emprunteurs contre des polices surévaluées placées sans notification ni comparaison", "Wave 1301",
     "Propriétaires se voyant imposer une assurance habitation à tarif excessif par leur prestataire hypothécaire sans notification et sans pouvoir fournir leur propre police.",
     "FPIM", "force_placed_insur"),
    ("escrow_account_dispute_rights_engine.py",
     "Litiges sur les comptes de dépôt fiduciaire hypothécaire & droits des emprunteurs à contester les surprovisions et les augmentations de versement", "Wave 1301",
     "Propriétaires constatant des surprovisions dans leur compte escrow hypothécaire entraînant des hausses de versement mensuel sans explication ni remboursement.",
     "ESCM", "escrow_mortgage"),

    # Wave 1302 — Travail: droits spéciaux (inédits)
    ("paid_sick_leave_small_employer_gap_rights_engine.py",
     "Lacunes du congé maladie payé pour les petits employeurs & droits des travailleurs d'entreprises de moins de 15 employés sans couverture étatique", "Wave 1302",
     "Travailleurs dans de petites entreprises exemptées des lois de congé maladie payé contraints de choisir entre santé et salaire lors de maladie.",
     "PSLS", "sick_leave_small_emp"),
    ("tipped_worker_wage_theft_rights_engine.py",
     "Vol de salaire pour les travailleurs au pourboire & droits des serveurs contre les détournements de pourboires par les employeurs et les managers", "Wave 1302",
     "Serveurs dont les pourboires sont illégalement confisqués ou partagés avec des managers non éligibles, sous-évalués ou déduits des erreurs de caisse.",
     "TWTH", "tipped_wage_theft"),
    ("j1_visa_exchange_worker_rights_engine.py",
     "Droits des travailleurs en échange culturel J-1 & protection contre l'exploitation et l'abus des parrains du programme de visa J-1", "Wave 1302",
     "Travailleurs en programme J-1 exploités par des employeurs abusant du contrôle du visa pour imposer des conditions de travail abusives sans recours légal.",
     "JVEX", "j1_exchange_work"),

    # Wave 1303 — Immigration: communautés spécifiques (inédits)
    ("venezuelan_tps_protection_rights_engine.py",
     "Statut de protection temporaire pour les ressortissants vénézuéliens & droits à la désignation TPS face à la crise politique et économique", "Wave 1303",
     "Ressortissants vénézuéliens aux États-Unis face à l'instabilité du statut TPS lors de changements d'administration affectant leur capacité à travailler légalement.",
     "VNTF", "venezuelan_tps"),
    ("refugee_employment_authorization_rights_engine.py",
     "Autorisation de travail pour les réfugiés réinstallés & droits à l'emploi légal immédiat dès l'admission officielle sans délai d'approbation USCIS", "Wave 1303",
     "Réfugiés réinstallés incapables de travailler en attendant leur document d'autorisation d'emploi malgré leur admission légale aux États-Unis.",
     "REHE", "refugee_employ_auth"),
    ("withholding_only_asylum_appeal_rights_engine.py",
     "Appels des cas de withholding of removal uniquement & droits des personnes dont la demande d'asile a été refusée à plaider le retrait différé", "Wave 1303",
     "Demandeurs d'asile déboutés non expulsables vers leur pays d'origine en raison de risques de torture mais sans statut légal permanent ni voie d'appel.",
     "GNIN", "withholding_appeal"),

    # Wave 1304 — Droits: protection génétique & diversité (inédits)
    ("gina_genetic_insurance_discrimination_rights_engine.py",
     "Protection GINA contre la discrimination génétique par les assureurs & droits des titulaires de tests génétiques à une couverture non affectée", "Wave 1304",
     "Personnes ayant effectué des tests génétiques découvrant que leur assureur maladie ou vie utilise leurs résultats génétiques pour leur refuser une couverture.",
     "GNDI", "gina_genetic_insur"),
    ("private_school_disability_rights_engine.py",
     "Droits des élèves handicapés dans les écoles privées & obligations légales Section 504 des établissements recevant des fonds fédéraux indirects", "Wave 1304",
     "Élèves handicapés dans des écoles privées recevant indirectement des fonds fédéraux se voyant refuser des accommodements Section 504 supposément applicables.",
     "PSDC", "private_school_disab"),
    ("problem_gambling_workplace_rights_engine.py",
     "Jeu pathologique comme handicap au travail & droits des personnes avec trouble du jeu à demander un accommodement pour traitement plutôt qu'être licenciées", "Wave 1304",
     "Employés développant un trouble du jeu lié à l'expansion des paris sportifs légaux ne bénéficiant pas de protections ADA similaires aux autres addictions.",
     "SBAD", "problem_gambling_work"),
]
