# Specs waves 1305-1312 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1305 — Santé: prévention & dépistage (inédits)
    ("cervical_cancer_hpv_screening_rights_engine.py",
     "Dépistage du cancer du col par test HPV & droits des femmes à un co-test ou test HPV primaire sans copaiement sous les recommandations USPSTF", "Wave 1305",
     "Femmes se voyant facturer un copaiement pour leur test HPV de dépistage cervical malgré les exigences ACA de couverture préventive sans frais partagés.",
     "HVSC", "hpv_cervical_screen"),
    ("skin_cancer_dermatology_access_rights_engine.py",
     "Accès au dépistage du cancer de la peau par dermatologue & droits des personnes à haut risque à des examens annuels remboursés par l'assurance", "Wave 1305",
     "Personnes à haut risque de mélanome attendant 6 à 12 mois pour voir un dermatologue en raison de pénuries de spécialistes dans leur zone géographique.",
     "SKCD", "skin_cancer_derm"),
    ("genetic_counseling_brca_access_rights_engine.py",
     "Accès au conseil génétique BRCA pour le cancer héréditaire & droits des personnes avec antécédents familiaux à des tests et conseils remboursés", "Wave 1305",
     "Personnes avec antécédents familiaux de cancer du sein ou des ovaires ne pouvant accéder à un conseil génétique BRCA en raison de limitations d'assurance.",
     "GBRA", "brca_genetic_counsel"),

    # Wave 1306 — Logement: sécurité & maintenance (inédits)
    ("elevator_maintenance_high_rise_rights_engine.py",
     "Maintenance des ascenseurs dans les immeubles d'appartements & droits des locataires handicapés à un logement habitable lors des pannes prolongées", "Wave 1306",
     "Résidents handicapés d'immeubles de grande hauteur confinés à leur appartement pendant des semaines en raison de pannes d'ascenseur non réparées rapidement.",
     "ELMR", "elevator_maint_rights"),
    ("building_code_violation_tenant_rights_engine.py",
     "Droits des locataires lors de violations des codes de construction & protection contre les expulsions de représailles après signalement d'infractions", "Wave 1306",
     "Locataires signalant des violations du code de construction à leur propriétaire ou aux autorités faisant ensuite l'objet d'actions d'expulsion de représailles.",
     "BCVT", "building_code_tenant"),
    ("pest_infestation_landlord_remediation_rights_engine.py",
     "Obligations du propriétaire lors d'infestations de nuisibles & droits des locataires à une extermination professionnelle sans frais et à une réduction de loyer", "Wave 1306",
     "Locataires vivant avec des infestations de cafards, rongeurs ou punaises de lit que le propriétaire refuse de traiter malgré les plaintes répétées.",
     "PEIL", "pest_infestation_land"),

    # Wave 1307 — Finance: investissement & épargne (inédits)
    ("robo_advisor_fiduciary_duty_rights_engine.py",
     "Obligation fiduciaire des conseillers financiers robotisés & droits des investisseurs à des recommandations dans leur meilleur intérêt sans conflits d'intérêts", "Wave 1307",
     "Investisseurs utilisant des robo-conseillers recevant des recommandations de portefeuille biaisées par les conflits d'intérêts des plateformes parentes.",
     "RBFI", "robo_advisor_fiduciary"),
    ("education_savings_529_restrictions_rights_engine.py",
     "Restrictions des plans d'épargne éducation 529 & droits des familles à des définitions flexibles des dépenses éducatives éligibles", "Wave 1307",
     "Familles ayant épargné dans des plans 529 se voyant refuser le remboursement pour des dépenses éducatives légitimes non reconnues comme éligibles par le plan.",
     "EDSR", "529_education_restrict"),
    ("employee_stock_option_vesting_rights_engine.py",
     "Acquisition des options d'achat d'actions des employés & droits des travailleurs lors de licenciements qui les privent de options non encore acquises", "Wave 1307",
     "Employés licenciés juste avant l'acquisition de leurs options d'achat d'actions dans des circonstances suggérant un calendrier délibéré pour éviter le versement.",
     "ESVO", "employee_stock_vest"),

    # Wave 1308 — Immigration: protection familiale (inédits)
    ("mixed_status_family_fear_rights_engine.py",
     "Familles de statut mixte et effet dissuasif de la peur de l'immigration & droits des membres citoyens à accéder aux services sans risque pour les proches", "Wave 1308",
     "Familles mixtes citoyens-non documentés évitant les soins médicaux, l'aide alimentaire et l'éducation par peur des contrôles d'immigration dans les services.",
     "MSFR", "mixed_status_fear"),
    ("ice_enforcement_sensitive_locations_rights_engine.py",
     "Application des lois d'immigration aux lieux sensibles & droits des communautés à des politiques protégeant les écoles, hôpitaux et lieux de culte", "Wave 1308",
     "Immigrants dans des communautés où les agents ICE opèrent près des écoles et hôpitaux sans politiques de lieux sensibles clairement établies et appliquées.",
     "ICES", "ice_sensitive_loc"),
    ("immigrant_parent_deportation_custody_rights_engine.py",
     "Garde des enfants lors de la déportation d'un parent immigrant & droits à maintenir le lien parental et à éviter le placement en famille d'accueil", "Wave 1308",
     "Parents immigrants déportés dont les enfants citoyens américains sont placés en famille d'accueil car aucun plan de garde alternatif n'a été établi à l'avance.",
     "IPDC", "immigr_parent_custody"),

    # Wave 1309 — Éducation: équité avancée (inédits)
    ("racial_equity_curriculum_access_rights_engine.py",
     "Accès au curriculum d'équité raciale dans les écoles publiques & droits des élèves à une éducation historique complète non censurée par la législation", "Wave 1309",
     "Élèves dans des États ayant adopté des lois limitant l'enseignement de l'histoire raciale confrontés à une éducation incomplète sur le racisme systémique.",
     "RECU", "racial_equity_curr"),
    ("in_school_suspension_education_rights_engine.py",
     "Éducation pendant les suspensions scolaires internes & droits des élèves à continuer à recevoir un enseignement même pendant les périodes d'isolement disciplinaire", "Wave 1309",
     "Élèves placés en suspension interne sans accès à l'enseignement pendant des jours, accumulant un retard académique important pour des infractions mineures.",
     "ISSP", "in_school_suspend"),
    ("college_admissions_transparency_rights_engine.py",
     "Transparence dans les admissions universitaires & droits des candidats à comprendre les critères de décision et à contester les refus inexpliqués", "Wave 1309",
     "Candidats universitaires refusés sans explication claire ni feedback, incapables de comprendre pourquoi leurs dossiers solides n'ont pas été retenus.",
     "CATR", "college_admit_transp"),

    # Wave 1310 — Santé: conditions féminines (inédits)
    ("endometriosis_surgical_treatment_rights_engine.py",
     "Accès au traitement chirurgical de l'endométriose & droits des patientes à une excision laparoscopique sans être limitées aux traitements hormonaux", "Wave 1310",
     "Patientes atteintes d'endométriose sévère contraintes par leur assurance d'essayer des traitements hormonaux répétés avant d'accéder à une chirurgie curative.",
     "EOSA", "endo_surgical_treat"),
    ("pcos_fertility_insurance_rights_engine.py",
     "Couverture d'assurance des traitements de fertilité liés au SOPK & droits des femmes à l'induction d'ovulation sans exclure les complications hormonales du SOPK", "Wave 1310",
     "Femmes atteintes du syndrome des ovaires polykystiques cherchant à concevoir confrontées à des refus d'assurance pour les traitements de fertilité spécifiques au SOPK.",
     "PCFI", "pcos_fertility_ins"),
    ("menopause_hormone_therapy_rights_engine.py",
     "Thérapie hormonale substitutive pour la ménopause & droits des femmes à un accès aux traitements sans restrictions excessives fondées sur des risques surestimés", "Wave 1310",
     "Femmes ménopausées cherchant une thérapie hormonale substitutive confrontées à des refus de prescription ou de couverture d'assurance basés sur des données obsolètes.",
     "MHRT", "menopause_hrt"),

    # Wave 1311 — Travail: droits spécifiques (inédits)
    ("just_in_time_scheduling_rights_engine.py",
     "Planification de dernière minute dans la restauration & droits des travailleurs à un préavis de planning minimal et à une compensation pour les modifications tardives", "Wave 1311",
     "Travailleurs de la restauration et du commerce recevant leurs horaires moins de 24 heures à l'avance, rendant impossible la planification des soins et transports.",
     "JITS", "just_in_time_sched"),
    ("meal_rest_break_violation_rights_engine.py",
     "Violations des droits aux pauses repas et repos & droits des travailleurs à des pauses légalement garanties et à une compensation pour les pauses non accordées", "Wave 1311",
     "Travailleurs dans des secteurs à rythme soutenu contraints de travailler sans pauses repas ou repos légalement requises sans compensation pour cette privation.",
     "MRBE", "meal_rest_break"),
    ("religious_accommodation_job_rights_engine.py",
     "Accommodements religieux au travail & droits des employés à des modifications d'horaire, de tenue et de tâches pour respecter leurs pratiques religieuses", "Wave 1311",
     "Employés se voyant refuser des accommodements pour les pratiques et observances religieuses par des employeurs invoquant une gêne minimale non démontrée.",
     "RELW", "religious_job_accomm"),

    # Wave 1312 — Droits: accès & protection (inédits)
    ("notary_public_access_underserved_rights_engine.py",
     "Accès aux services notariaux dans les communautés mal desservies & droits des résidents ruraux et à faibles revenus à des services de notariat abordables", "Wave 1312",
     "Résidents ruraux et à faibles revenus incapables d'accéder facilement à des notaires pour des documents légaux essentiels comme les testaments et procurations.",
     "NOPB", "notary_access"),
    ("small_claims_court_fee_waiver_rights_engine.py",
     "Dispenses de frais pour les tribunaux de petites créances & droits des justiciables à faibles revenus à accéder à la justice sans obstacles financiers", "Wave 1312",
     "Justiciables à faibles revenus cherchant à déposer des demandes de petites créances confrontés à des frais de dépôt qui représentent une proportion de leur créance.",
     "SCFW", "small_claims_fee_waiv"),
    ("legal_document_translation_rights_engine.py",
     "Traduction des documents juridiques pour les non-anglophones & droits des parties à recevoir des contrats, jugements et avis dans une langue compréhensible", "Wave 1312",
     "Personnes à maîtrise limitée de l'anglais signant des contrats, baux ou documents judiciaires sans traduction adéquate et sans compréhension réelle du contenu.",
     "LDTR", "legal_doc_translat"),
]
