# Specs waves 921-928 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 921 — Discipline scolaire & racisme systémique
    ("school_discipline_racial_gap_rights_engine.py",
     "Discipline scolaire & écart racial d'exclusion", "Wave 921",
     "Élèves noirs et latinos suspendus et expulsés à des taux racialement disproportionnés.",
     "SDRG", "school_race_discipline"),
    ("suspension_school_poverty_rights_engine.py",
     "Suspension scolaire & trappe de pauvreté", "Wave 921",
     "Suspensions scolaires répétées aggravant le décrochage et la précarité des élèves pauvres.",
     "SUSP", "school_suspension"),
    ("expulsion_special_education_rights_engine.py",
     "Expulsion des élèves en éducation spécialisée", "Wave 921",
     "Élèves handicapés expulsés en violation de leurs droits à l'éducation adaptée.",
     "EXSE", "expulsion_sped"),

    # Wave 922 — Pipeline scolaire vers la prison
    ("alternative_school_pipeline_rights_engine.py",
     "Écoles alternatives & pipeline vers la prison", "Wave 922",
     "Écoles alternatives servant de sas vers le système pénal plutôt que vers l'éducation.",
     "ASPL", "alt_school_pipeline"),
    ("dress_code_racial_bias_rights_engine.py",
     "Codes vestimentaires & biais racial", "Wave 922",
     "Codes vestimentaires scolaires ciblant disproportionnellement les cultures minoritaires.",
     "DCRB", "dress_code_racial"),
    ("hair_discrimination_school_rights_engine.py",
     "Discrimination capillaire à l'école & identité culturelle", "Wave 922",
     "Élèves punis ou exclus pour des coiffures naturelles liées à leur identité culturelle.",
     "HDSC", "hair_school_discrim"),

    # Wave 923 — Cheveux, maternelle & programmes avancés
    ("natural_hair_school_ban_rights_engine.py",
     "Interdiction des cheveux naturels à l'école", "Wave 923",
     "Règlements scolaires interdisant locks, tresses et afros imposant des standards blancs.",
     "NHSB", "natural_hair_ban"),
    ("race_based_discipline_preschool_rights_engine.py",
     "Discipline raciale en maternelle & suspension", "Wave 923",
     "Enfants noirs suspendus dès la maternelle à des taux largement supérieurs à ceux des blancs.",
     "RBDP", "preschool_race_disc"),
    ("gifted_program_exclusion_rights_engine.py",
     "Programmes pour surdoués & exclusion des minorités", "Wave 923",
     "Enfants de couleur sous-représentés dans les programmes pour surdoués sans évaluation équitable.",
     "GPEX", "gifted_exclusion"),

    # Wave 924 — Ségrégation éducative & frais
    ("advanced_class_segregation_rights_engine.py",
     "Classes avancées & ségrégation scolaire de facto", "Wave 924",
     "Classes avancées ségrégant de facto les lycées par race et classe sociale.",
     "ACSG", "advanced_segregation"),
    ("school_boundary_segregation_rights_engine.py",
     "Frontières scolaires & ségrégation résidentielle", "Wave 924",
     "Carte scolaire perpétuant la ségrégation résidentielle dans les districts publics.",
     "SBSG", "boundary_segregation"),
    ("magnet_school_lottery_rights_engine.py",
     "Loteries des écoles magnets & inégalité d'accès", "Wave 924",
     "Loteries d'accès aux meilleures écoles magnets désavantagent systématiquement les pauvres.",
     "MSLT", "magnet_lottery"),

    # Wave 925 — Frais scolaires & ressources
    ("school_fee_barrier_rights_engine.py",
     "Frais scolaires obligatoires & barrière à l'accès", "Wave 925",
     "Familles pauvres incapables de payer les frais scolaires « obligatoires » illégaux.",
     "SFBR", "school_fee_barrier"),
    ("extracurricular_pay_barrier_rights_engine.py",
     "Activités parascolaires payantes & exclusion des pauvres", "Wave 925",
     "Élèves pauvres exclus d'activités formant les futures élites faute de pouvoir les payer.",
     "EPBR", "extracurricular_pay"),
    ("marching_band_fee_poor_rights_engine.py",
     "Frais de fanfare & exclusion des élèves pauvres", "Wave 925",
     "Élèves pauvres exclus des programmes musicaux parascolaires par les frais d'instruments.",
     "MBFP", "band_fee"),

    # Wave 926 — Police scolaire & fouilles
    ("school_resource_officer_harm_rights_engine.py",
     "Agents de sécurité scolaires & harm disproportionné", "Wave 926",
     "Officiers de sécurité scolaires criminalisant des comportements juvéniles normaux.",
     "SROH", "sro_harm"),
    ("counselor_to_cop_ratio_rights_engine.py",
     "Ratio conseillers/policiers & santé mentale des élèves", "Wave 926",
     "Lycées avec plus d'agents de sécurité que de conseillers d'orientation.",
     "CCRA", "counselor_cop_ratio"),
    ("school_police_search_student_rights_engine.py",
     "Fouilles policières des élèves & droits constitutionnels", "Wave 926",
     "Élèves fouillés sans mandat ni raison valable par des agents de sécurité.",
     "SPSS", "school_search"),

    # Wave 927 — Surveillance numérique des élèves
    ("student_cell_phone_search_rights_engine.py",
     "Fouille de téléphone d'élève & vie privée numérique", "Wave 927",
     "Élèves contraints de déverrouiller leurs téléphones lors de fouilles scolaires.",
     "SCPS", "student_phone_search"),
    ("classroom_surveillance_camera_rights_engine.py",
     "Caméras en classe & surveillance des élèves", "Wave 927",
     "Caméras dans les salles de classe filmant les élèves sans procédure de transparence.",
     "CSCA", "classroom_camera"),
    ("student_behavioral_data_algorithm_rights_engine.py",
     "Données comportementales des élèves & algorithmes disciplinaires", "Wave 927",
     "Algorithmes compilant les comportements d'élèves et influençant leurs sanctions.",
     "SBDA", "student_data_algo"),

    # Wave 928 — Parents & éducation spécialisée
    ("parent_language_barrier_school_rights_engine.py",
     "Barrière linguistique parentale & participation scolaire", "Wave 928",
     "Parents non anglophones exclus des réunions et décisions scolaires concernant leurs enfants.",
     "PLBS", "parent_language"),
    ("iep_parent_exclusion_rights_engine.py",
     "IEP & exclusion des parents des décisions d'éducation spécialisée", "Wave 928",
     "Parents exclus ou ignorés lors des réunions IEP déterminant le plan éducatif de leur enfant.",
     "IPEX", "iep_parent"),
    ("special_ed_restraint_rights_engine.py",
     "Contention en éducation spécialisée & droits des élèves", "Wave 928",
     "Élèves en éducation spécialisée soumis à des contentions et isolements abusifs.",
     "SEDR", "sped_restraint"),
]
