# Specs waves 897-904 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 897 — Énergie & logement insalubre
    ("low_income_energy_bill_assistance_rights_engine.py",
     "Aides à la facture énergétique & ménages précaires", "Wave 897",
     "Ménages à faibles revenus incapables de payer leurs factures d'énergie malgré les aides.",
     "LIEA", "low_income_energy"),
    ("weatherization_poor_housing_rights_engine.py",
     "Isolation thermique & logements pauvres", "Wave 897",
     "Logements des ménages pauvres non isolés, froids l'hiver et brûlants l'été.",
     "WZPH", "weatherization"),
    ("indoor_air_quality_low_income_rights_engine.py",
     "Qualité de l'air intérieur & logements précaires", "Wave 897",
     "Ménages précaires respirant un air intérieur toxique faute de ventilation et de rénovation.",
     "IAQL", "indoor_air_low"),

    # Wave 898 — Allergènes & polluants du logement
    ("lead_paint_asthma_trigger_rights_engine.py",
     "Peinture au plomb & asthme des enfants locataires", "Wave 898",
     "Enfants de locataires exposés à la peinture au plomb et aux allergènes déclenchant l'asthme.",
     "LPAS", "lead_asthma"),
    ("mold_rental_health_rights_engine.py",
     "Moisissures locatives & santé des occupants", "Wave 898",
     "Locataires vivant dans des logements infestés de moisissures sans recours effectif.",
     "MLRH", "mold_rental"),
    ("carpet_glue_formaldehyde_rights_engine.py",
     "Colles de moquette, formaldéhyde & exposition domestique", "Wave 898",
     "Résidents exposés au formaldéhyde des moquettes et revêtements dans des logements neufs.",
     "CGFO", "carpet_formaldehyde"),

    # Wave 899 — Insalubrité & pesticides
    ("cockroach_allergen_housing_rights_engine.py",
     "Allergènes de cafards & asthme en logement social", "Wave 899",
     "Enfants de logements sociaux souffrant d'asthme sévère dû aux allergènes de cafards.",
     "COAL", "cockroach_allergen"),
    ("housing_pesticide_exposure_rights_engine.py",
     "Pesticides dans les logements & santé des résidents", "Wave 899",
     "Résidents exposés à des pesticides pulvérisés sans préavis ni protection.",
     "HPEX", "housing_pesticide"),
    ("second_hand_smoke_tenant_rights_engine.py",
     "Tabagisme passif & droits des locataires", "Wave 899",
     "Locataires non-fumeurs exposés à la fumée de voisins dans des immeubles sans politique.",
     "SHST", "second_smoke_tenant"),

    # Wave 900 — Fumée & logement sans tabac
    ("third_hand_smoke_child_rights_engine.py",
     "Fumée tertiaire & enfants exposés", "Wave 900",
     "Enfants exposés aux résidus de fumée de tabac sur surfaces et vêtements.",
     "THSC", "third_smoke_child"),
    ("smoke_free_housing_gap_rights_engine.py",
     "Logements sans tabac & lacunes de mise en œuvre", "Wave 900",
     "Politiques de logements sans tabac non appliquées exposant les non-fumeurs.",
     "SFHG", "smoke_free_gap"),
    ("community_land_trust_rights_engine.py",
     "Fiducies foncières communautaires & accès abordable", "Wave 900",
     "Fiducies foncières communautaires bloquées par des réglementations hostiles.",
     "CLTR", "community_land_trust"),

    # Wave 901 — Gentrification & retour au logement
    ("eviction_moratorium_gap_rights_engine.py",
     "Moratoire d'expulsion & lacunes de protection", "Wave 901",
     "Locataires tombant entre les mailles des moratoires d'expulsion temporaires.",
     "EMGP", "eviction_moratorium"),
    ("right_to_return_gentrification_rights_engine.py",
     "Droit au retour & gentrification des quartiers", "Wave 901",
     "Résidents expulsés par la gentrification sans droit légal de retour aux prix abordables.",
     "RTRG", "right_to_return"),
    ("inclusionary_zoning_weak_rights_engine.py",
     "Zonage inclusionnaire insuffisant & logement abordable", "Wave 901",
     "Exigences de zonage inclusionnaire trop faibles pour contrebalancer la gentrification.",
     "IZWK", "inclusionary_zoning"),

    # Wave 902 — Logement abordable & récupération
    ("affordable_unit_clawback_rights_engine.py",
     "Unités abordables & récupération par les promoteurs", "Wave 902",
     "Unités abordables converties en marché libre à l'expiration des obligations.",
     "AUCB", "affordable_clawback"),
    ("condo_conversion_tenant_rights_engine.py",
     "Conversion en copropriété & droits des locataires", "Wave 902",
     "Locataires expulsés lorsque des immeubles sont convertis en copropriétés.",
     "CCTB", "condo_conversion"),
    ("adu_tenant_protection_rights_engine.py",
     "Logements accessoires & protection des locataires", "Wave 902",
     "Locataires de logements accessoires sans protection légale face aux propriétaires.",
     "ADUT", "adu_tenant"),

    # Wave 903 — Parcs mobiles & bons de logement
    ("manufactured_home_park_sale_rights_engine.py",
     "Vente de parcs de maisons mobiles & expulsion des résidents", "Wave 903",
     "Résidents de parcs mobiles expulsés lorsque le propriétaire vend le terrain.",
     "MHPS", "mobile_park_sale"),
    ("housing_voucher_landlord_refusal_rights_engine.py",
     "Bons de logement & refus des propriétaires", "Wave 903",
     "Détenteurs de bons de logement refusés par des propriétaires discriminants.",
     "HVLR", "voucher_refusal"),
    ("section8_stigma_discrimination_rights_engine.py",
     "Section 8 & stigmatisation des bénéficiaires", "Wave 903",
     "Bénéficiaires de la Section 8 discriminés et stigmatisés sur le marché locatif.",
     "SSCD", "section8_stigma"),

    # Wave 904 — Logement public & HUD
    ("public_housing_waitlist_rights_engine.py",
     "Listes d'attente HLM & droit au logement public", "Wave 904",
     "Familles attendant des années un logement public sans recours ni transparence.",
     "PHWL", "public_housing_wait"),
    ("hud_inspection_failure_rights_engine.py",
     "Inspections HUD défaillantes & logements insalubres", "Wave 904",
     "Logements subventionnés ne passant pas les inspections HUD mais restant occupés.",
     "HUDF", "hud_inspection"),
    ("public_housing_mold_rights_engine.py",
     "Moisissures en logement public & négligence institutionnelle", "Wave 904",
     "Logements publics infestés de moisissures sans rénovation malgré les plaintes répétées.",
     "PHMR", "public_housing_mold"),
]
