# Specs waves 1233-1240 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1233 — Santé: maladies chroniques & femmes (inédits)
    ("cancer_survivor_employment_rights_engine.py",
     "Discrimination à l'emploi des survivants de cancer & droits sous l'ADA à des accommodements post-traitement", "Wave 1233",
     "Survivants de cancer confrontés à des discriminations à l'embauche ou à des licenciements liés à leur historique médical.",
     "CSLB", "cancer_survivor_employ"),
    ("uterine_fibroid_treatment_rights_engine.py",
     "Accès aux traitements minimalement invasifs pour fibromes utérins & refus d'assurance pour alternatives à l'hystérectomie", "Wave 1233",
     "Femmes avec fibromes utérins sévères se voyant refuser une couverture pour des traitements moins invasifs que l'hystérectomie.",
     "FBRB", "fibroid_treatment"),
    ("continuous_glucose_monitor_coverage_rights_engine.py",
     "Couverture des moniteurs de glucose en continu CGM & refus d'assurance pour les diabétiques de type 2 sous insuline", "Wave 1233",
     "Diabétiques de type 2 sous insuline refusés pour la couverture CGM bien que ces dispositifs améliorent le contrôle glycémique.",
     "CPHP", "cgm_coverage"),

    # Wave 1234 — Immigration: permis & statuts niches (inédits)
    ("undocumented_immigrant_driver_license_rights_engine.py",
     "Permis de conduire pour immigrants sans papiers & refus dans des États sans loi reconnaissant leur besoin de mobilité", "Wave 1234",
     "Immigrants sans papiers dans des États sans loi de permis conduire pour tous vivant sans mobilité légale pour le travail.",
     "DLIC", "undoc_driver_license"),
    ("license_exam_language_barrier_rights_engine.py",
     "Barrières linguistiques dans les examens de licences professionnelles & droits des immigrants qualifiés à des tests traduits", "Wave 1234",
     "Professionnels immigrés qualifiés incapables de passer les examens de licence dans leur langue malgré une maîtrise technique.",
     "MLTR", "license_exam_lang"),
    ("veteran_rural_healthcare_access_rights_engine.py",
     "Accès aux soins de santé VA pour vétérans ruraux & droits aux soins communautaires quand les distances sont prohibitives", "Wave 1234",
     "Vétérans ruraux parcourant des heures pour accéder aux cliniques VA sans remboursement de transport ni soins communautaires.",
     "VTMH", "vet_rural_health"),

    # Wave 1235 — Justice: amendes & fines (inédits)
    ("street_vendor_permit_enforcement_rights_engine.py",
     "Application des règles de permis aux vendeurs de rue & violations des droits des vendeurs informels par des saisies arbitraires", "Wave 1235",
     "Vendeurs de rue à faibles revenus dont la marchandise est confisquée et les carts saisis sans procédure légale équitable.",
     "STVE", "street_vendor_permit"),
    ("ability_to_pay_court_fine_rights_engine.py",
     "Évaluation de la capacité de paiement des amendes judiciaires & droits des pauvres à ne pas être emprisonnés pour dettes", "Wave 1235",
     "Personnes à faibles revenus emprisonnées pour des amendes impayées sans évaluation judiciaire de leur réelle capacité de paiement.",
     "ILDL", "ability_pay_fine"),
    ("court_legal_representation_civil_rights_engine.py",
     "Droit à la représentation légale dans les procédures civiles & absence de droit constitutionnel à un avocat en matière civile", "Wave 1235",
     "Plaideurs non représentés dans des affaires d'expulsion, garde d'enfant ou protection sociale sans accès à un avocat.",
     "CSFR", "civil_legal_repr"),

    # Wave 1236 — Éducation: équité & accès (inédits)
    ("gifted_education_underfunding_rights_engine.py",
     "Sous-financement des programmes d'éducation pour surdoués & inégalités dans l'accès aux ressources pour les élèves avancés", "Wave 1236",
     "Districts scolaires sans programmes d'éducation pour surdoués laissant les élèves avancés sans défi ni stimulation adéquats.",
     "OGMD", "gifted_underfund"),
    ("dual_enrollment_access_equity_rights_engine.py",
     "Accès équitable aux cours de double inscription lycée-université & barrières financières et géographiques pour élèves défavorisés", "Wave 1236",
     "Lycéens dans des districts pauvres sans accès aux cours de double inscription disponibles dans des districts plus riches.",
     "DMLE", "dual_enroll_equity"),
    ("school_meal_debt_shaming_rights_engine.py",
     "Honte liée aux dettes de repas scolaires & pratiques humiliantes envers les enfants dont les familles ne peuvent payer", "Wave 1236",
     "Enfants dont les repas scolaires sont confisqués ou remplacés par des alternatives moins nourrissantes en raison de dettes impayées.",
     "CSML", "school_meal_debt"),

    # Wave 1237 — Travail: travailleurs spécialisés (inédits)
    ("unpaid_internship_wage_rights_engine.py",
     "Stages non rémunérés et droits des stagiaires & classification illégale de travailleurs comme stagiaires pour éviter le salaire", "Wave 1237",
     "Étudiants effectuant des travaux réels de valeur commerciale classifiés comme stagiaires non payables pour éviter le salaire minimum.",
     "GAPP", "unpaid_intern_wage"),
    ("piece_rate_worker_minimum_wage_rights_engine.py",
     "Salaire minimum pour les travailleurs à la pièce & calcul des heures pour garantir le revenu horaire plancher légal", "Wave 1237",
     "Ouvriers agricoles et manufacturiers payés à la pièce ne gagnant pas l'équivalent du salaire minimum horaire en période creuse.",
     "PPLT", "piece_rate_minwage"),
    ("nonprofit_worker_wage_parity_rights_engine.py",
     "Parité salariale dans les organisations à but non lucratif & compensation insuffisante justifiée par la mission plutôt que l'équité", "Wave 1237",
     "Travailleurs de OBNL payés significativement moins que leurs homologues du secteur public pour des rôles identiques.",
     "UREC", "nonprofit_wage_parity"),

    # Wave 1238 — Technologie: vie privée & IA (inédits)
    ("employer_social_media_demand_rights_engine.py",
     "Exigence des employeurs d'accès aux réseaux sociaux privés & droits des candidats à la vie privée numérique pendant le recrutement", "Wave 1238",
     "Candidats à l'emploi contraints de fournir mots de passe ou accès à leurs profils sociaux privés lors des entretiens.",
     "CNBS", "employer_social_demand"),
    ("ai_hiring_algorithm_bias_rights_engine.py",
     "Biais des algorithmes de recrutement IA & droits des candidats à une évaluation équitable sans discrimination automatisée", "Wave 1238",
     "Candidats qualifiés éliminés par des systèmes de présélection IA reproduisant des biais de genre, race ou âge sans révision humaine.",
     "EDSP", "ai_hiring_bias"),
    ("predictive_analytics_employee_exit_rights_engine.py",
     "Analyse prédictive pour identifier les employés susceptibles de quitter & utilisation des données personnelles sans consentement", "Wave 1238",
     "Employés dont les données comportementales sont analysées par des algorithmes pour prédire leur départ et les discipliner proactivement.",
     "PKDR", "predict_employee_exit"),

    # Wave 1239 — Santé: besoins spéciaux & accès (inédits)
    ("autism_adult_service_gap_rights_engine.py",
     "Lacune de services pour adultes autistes après 21 ans & chute de falaise de services entre l'école et la vie adulte", "Wave 1239",
     "Jeunes adultes autistes perdant tous leurs services éducatifs à 21 ans sans transition vers des services adultes adaptés.",
     "SBNR", "autism_adult_gap"),
    ("pediatric_palliative_care_access_rights_engine.py",
     "Accès aux soins palliatifs pédiatriques & droits des enfants gravement malades à des soins de confort dès le diagnostic", "Wave 1239",
     "Enfants atteints de maladies graves sans accès à des équipes de soins palliatifs pédiatriques en dehors des grands centres.",
     "ABGE", "pediatric_palliat"),
    ("adult_adhd_diagnosis_treatment_rights_engine.py",
     "Diagnostic et traitement du TDAH adulte & refus d'assurance pour médicaments de stimulants chez les adultes diagnostiqués tard", "Wave 1239",
     "Adultes diagnostiqués avec TDAH refusés pour la couverture de médicaments stimulants avec des restrictions d'âge arbitraires.",
     "PTVR", "adult_adhd_treat"),

    # Wave 1240 — Droits divers: accès & équité (inédits)
    ("disability_placard_abuse_rights_engine.py",
     "Abus des plaques de stationnement handicapé & droits des personnes handicapées à un stationnement réservé fonctionnel", "Wave 1240",
     "Personnes handicapées incapables de trouver des places de stationnement réservées en raison de l'abus généralisé des placards.",
     "CPLT", "disab_placard_abuse"),
    ("public_restroom_access_rights_engine.py",
     "Accès aux toilettes publiques & droits des personnes handicapées, enceintes et avec conditions médicales à des facilités adéquates", "Wave 1240",
     "Personnes avec conditions médicales urgentes incapables d'accéder à des toilettes publiques dans les zones commerciales et de transport.",
     "CNER", "public_restroom_acc"),
    ("digital_accessibility_website_rights_engine.py",
     "Accessibilité numérique des sites web aux personnes handicapées & non-conformité ADA des services gouvernementaux en ligne", "Wave 1240",
     "Personnes handicapées incapables d'accéder aux services gouvernementaux en ligne en raison de sites web non conformes aux normes WCAG.",
     "DGTM", "digital_accessibility"),
]
