# Specs waves 1289-1296 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1289 — Sports & loisirs (inédits)
    ("amateur_athlete_injury_insurance_rights_engine.py",
     "Assurance blessures pour les athlètes amateurs & droits à une couverture médicale lors des compétitions organisées par des fédérations sportives", "Wave 1289",
     "Athlètes amateurs blessés lors de compétitions organisées par des fédérations sans couverture d'assurance médicale obligatoire pour les participants.",
     "AAIS", "amateur_athlete_insur"),
    ("youth_sport_safety_equipment_rights_engine.py",
     "Équipements de sécurité obligatoires dans les sports de jeunes & droits des enfants à des protections physiques standardisées dans les ligues organisées", "Wave 1289",
     "Enfants dans des ligues sportives de jeunesse sans réglementation sur les équipements de sécurité comme les casques de protection conformes aux normes.",
     "YSSE", "youth_sport_equip"),
    ("recreational_league_waiver_rights_engine.py",
     "Applicabilité des exonérations de responsabilité dans les ligues récréatives & droits des participants adultes blessés par négligence organisationnelle", "Wave 1289",
     "Adultes blessés dans des ligues récréatives confrontés à des exonérations de responsabilité excluant même les cas de négligence grossière de l'organisateur.",
     "RLWE", "rec_league_waiver"),

    # Wave 1290 — Logement: types spéciaux (inédits)
    ("tiny_home_zoning_rights_engine.py",
     "Zonage pour les mini-maisons & droits des résidents à construire ou installer des tiny homes sur des terrains en zone résidentielle classique", "Wave 1290",
     "Personnes souhaitant habiter dans des mini-maisons confrontées à des codes de zonage exigeant des superficies minimales incompatibles avec les tiny homes.",
     "THZN", "tiny_home_zoning"),
    ("retirement_community_entry_fee_rights_engine.py",
     "Contrats de frais d'entrée dans les communautés de retraite & droits des résidents à la transparence et au remboursement partiel en cas de départ", "Wave 1290",
     "Résidents de communautés de retraite ayant versé des frais d'entrée importants ne pouvant pas les récupérer partiellement lors d'un départ anticipé ou décès.",
     "RCEF", "retire_entry_fee"),
    ("condo_reserve_fund_adequacy_rights_engine.py",
     "Adéquation des fonds de réserve de copropriété & droits des acheteurs à des divulgations complètes sur l'état financier de l'association avant l'achat", "Wave 1290",
     "Acheteurs de condominiums découvrant après l'achat que le fonds de réserve est gravement insuffisant pour les réparations majeures imminentes.",
     "CRFR", "condo_reserve_fund"),

    # Wave 1291 — Finance: crédit & dettes (inédits)
    ("medical_debt_statute_limitation_rights_engine.py",
     "Prescription des dettes médicales & droits des patients contre la collecte de dettes médicales prescrites hors délai légal par des tiers collecteurs", "Wave 1291",
     "Patients contactés par des collecteurs tentant de recouvrer des dettes médicales prescrites depuis des années bien au-delà du délai légal de recouvrement.",
     "MDSL", "medical_debt_statute"),
    ("debt_validation_letter_rights_engine.py",
     "Lettre de validation de dette FDCPA & droits des consommateurs à une vérification écrite de la légitimité et du montant d'une dette avant paiement", "Wave 1291",
     "Consommateurs recevant des demandes de paiement de collecteurs sans pouvoir obtenir une validation écrite de l'identité du créancier original et du solde exact.",
     "DVLT", "debt_validation_lett"),
    ("free_credit_freeze_rights_engine.py",
     "Gel de crédit gratuit pour tous les consommateurs & droits à un gel et dégel de crédit sans frais auprès de chaque bureau de crédit majeur", "Wave 1291",
     "Consommateurs souhaitant geler leur crédit pour prévenir la fraude ignorant que des gelées gratuites sont légalement disponibles ou incapables de les activer.",
     "FCFZ", "free_credit_freeze"),

    # Wave 1292 — Santé: spécialités médicales (inédits)
    ("clinical_trial_informed_consent_rights_engine.py",
     "Consentement éclairé dans les essais cliniques & droits des participants à comprendre les risques avant l'inscription à une étude de recherche médicale", "Wave 1292",
     "Participants à des essais cliniques confrontés à des formulaires de consentement complexes sans explication claire des risques réels et des alternatives disponibles.",
     "CTCS", "clinical_trial_consent"),
    ("rare_disease_diagnosis_delay_rights_engine.py",
     "Délais de diagnostic des maladies rares & droits des patients à être référés à des centres d'expertise après des années d'errance diagnostique", "Wave 1292",
     "Patients atteints de maladies rares attendant en moyenne 5 à 7 ans un diagnostic correct après avoir consulté de nombreux spécialistes sans résultat.",
     "RDDL", "rare_disease_diag_del"),
    ("second_opinion_insurance_coverage_rights_engine.py",
     "Couverture d'assurance pour les secondes opinions médicales & droits des patients à consulter un autre spécialiste sans refus d'assurance pré-chirurgical", "Wave 1292",
     "Patients souhaitant obtenir un second avis avant une chirurgie majeure se voyant refuser le remboursement de cette consultation jugée non nécessaire par l'assureur.",
     "SOII", "second_opinion_insur"),

    # Wave 1293 — Travail: freelance & nouvelles formes (inédits)
    ("freelancer_payment_timeline_rights_engine.py",
     "Délais de paiement des freelances & droits des travailleurs indépendants à recevoir paiement dans les délais contractuels sous peine de pénalités", "Wave 1293",
     "Travailleurs indépendants attendant 90 à 180 jours le paiement de leurs factures d'entreprises clientes sans recours légal accessible à faible coût.",
     "FLTL", "freelancer_pay_time"),
    ("gig_worker_unemployment_insurance_rights_engine.py",
     "Assurance chômage pour les travailleurs de plateformes & droits d'accès aux prestations UI lors de déactivations injustifiées de compte", "Wave 1293",
     "Travailleurs Uber, DoorDash et Instacart désactivés de leurs plateformes sans compensation chômage dans des États sans couverture UI pour les gig workers.",
     "GWUI", "gig_work_unemploy"),
    ("contractor_noncompete_professional_rights_engine.py",
     "Clauses de non-concurrence pour professionnels libéraux & restrictions abusives imposées aux médecins et avocats indépendants après fin de contrat", "Wave 1293",
     "Médecins et professionnels de santé quittant une pratique contraints par des non-concurrences géographiques empêchant de soigner leurs patients habituels.",
     "CNTB", "contractor_noncompete"),

    # Wave 1294 — Éducation: spécialisée (inédits)
    ("for_profit_school_state_licensing_rights_engine.py",
     "Licences étatiques pour les écoles à but lucratif & droits des étudiants à vérifier la légitimité et l'accréditation avant de s'inscrire", "Wave 1294",
     "Étudiants s'inscrivant dans des écoles à but lucratif non correctement agréées par l'État, ignorant que leur diplôme ne sera pas reconnu par les employeurs.",
     "FPSL", "for_profit_school_lic"),
    ("campus_housing_disability_rights_engine.py",
     "Accommodements de handicap dans les logements universitaires & droits des étudiants à des modifications raisonnables des résidences campus", "Wave 1294",
     "Étudiants handicapés demandant des accommodements dans les résidences universitaires confrontés à des processus longs ou des refus non justifiés.",
     "CHDM", "campus_housing_disab"),
    ("student_transcript_withholding_rights_engine.py",
     "Rétention des relevés de notes pour dettes étudiantes & droits des diplômés à recevoir leur transcrit malgré des soldes impayés avec l'établissement", "Wave 1294",
     "Étudiants diplômés incapables d'obtenir leur relevé de notes officiel car l'université retient les transcriptions pour des dettes d'amendes ou de stationnement.",
     "STWH", "student_transcript"),

    # Wave 1295 — Droits: âge & statut (inédits)
    ("older_worker_retraining_access_rights_engine.py",
     "Accès aux programmes de reconversion pour travailleurs âgés & droits des 50+ aux formations financées par l'État lors des restructurations industrielles", "Wave 1295",
     "Travailleurs de plus de 50 ans déplacés par l'automatisation se heurtant à des critères d'admissibilité restrictifs pour les programmes de reconversion financés.",
     "OWRT", "older_worker_retrain"),
    ("minor_emancipation_legal_procedure_rights_engine.py",
     "Procédure d'émancipation légale des mineurs & droits des adolescents à l'autonomie juridique et financière sans attendre la majorité civile", "Wave 1295",
     "Adolescents cherchant à s'émanciper légalement confrontés à des procédures judiciaires complexes et coûteuses sans représentation légale accessible.",
     "MNER", "minor_emancipation"),
    ("adea_small_employer_coverage_rights_engine.py",
     "Protection ADEA contre la discrimination par âge pour les petits employeurs & lacune de la loi fédérale qui exclut les employeurs de moins de 20 salariés", "Wave 1295",
     "Travailleurs de 40 ans et plus discriminés par des employeurs de moins de 20 salariés non couverts par l'ADEA et sans protection étatique équivalente.",
     "ASMC", "adea_small_employer"),

    # Wave 1296 — Santé publique & environnement (inédits)
    ("lead_service_line_replacement_rights_engine.py",
     "Remplacement des canalisations de plomb & droits des résidents à l'accès à l'eau potable sans plomb et au remplacement financé des lignes de service", "Wave 1296",
     "Résidents recevant leur eau par des canalisations de plomb vieillissantes sans programme de remplacement accessible ou financé par les services publics.",
     "LSRL", "lead_service_line"),
    ("residential_pesticide_drift_rights_engine.py",
     "Dérive de pesticides vers les zones résidentielles & droits des riverains de zones agricoles à une notification préalable et à une protection de la santé", "Wave 1296",
     "Résidents vivant près de champs agricoles exposés à des dérives de pesticides sans notification préalable ni zone tampon de protection légalement requise.",
     "PDRT", "resid_pesticide_drift"),
    ("ambient_air_quality_monitoring_rights_engine.py",
     "Surveillance de la qualité de l'air ambiant & droits des communautés à des données de pollution en temps réel pour protéger les populations vulnérables", "Wave 1296",
     "Communautés proches d'industries polluantes sans surveillance adéquate de la qualité de l'air en temps réel ni données accessibles au public sur les pics de pollution.",
     "AQMR", "ambient_air_monitor"),
]
