# Specs waves 1209-1216 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1209 — Travail: surveillance & conditions (inédits)
    ("military_spouse_employment_rights_engine.py",
     "Droits professionnels des conjoints de militaires & obstacles à l'emploi liés aux déménagements PCS répétés", "Wave 1209",
     "Conjoints de militaires recommençant leur recherche d'emploi à chaque mutation PCS, perdant années d'ancienneté et réseaux professionnels.",
     "MSWP", "military_spouse_employ"),
    ("employer_gps_tracking_worker_rights_engine.py",
     "Surveillance GPS des travailleurs par les employeurs & droits à la vie privée des employés en dehors des heures de travail", "Wave 1209",
     "Employés dont les employeurs utilisent des appareils GPS pour surveiller leurs déplacements même pendant leurs heures personnelles.",
     "EDCA", "employer_gps_track"),
    ("retail_worker_predictive_scheduling_rights_engine.py",
     "Droit à une planification prédictible pour les travailleurs du commerce & changements d'horaire de dernière minute sans préavis", "Wave 1209",
     "Caissiers et employés de commerce dont les horaires changent de semaine en semaine sans préavis suffisant pour organiser leur vie.",
     "RTSP", "retail_predict_sched"),

    # Wave 1210 — Justice: bases de données & surveillance (inédits)
    ("gang_database_wrongful_entry_rights_engine.py",
     "Inscription erronée dans les bases de données de gangs & droits des personnes à contester une désignation de gang", "Wave 1210",
     "Jeunes hommes noirs et latinos inscrits dans des bases de données de gangs policières sans avoir commis de crime ou appartenu à un gang.",
     "GANG", "gang_db_wrong"),
    ("biometric_workplace_bipa_rights_engine.py",
     "Collecte de données biométriques des employés sans consentement & violations de la loi BIPA de l'Illinois et lois similaires", "Wave 1210",
     "Employés d'entrepôts et d'usines contraints d'utiliser des lecteurs d'empreintes pour pointer sans informations sur l'utilisation des données.",
     "BITP", "biometric_bipa"),
    ("dna_database_familial_search_rights_engine.py",
     "Recherches familiales dans les bases de données ADN forensiques & droits des relatives non accusées à ne pas être profilées", "Wave 1210",
     "Proches de personnes ayant soumis leur ADN à des banques de données pouvant identifier des suspects via des concordances familiales sans mandat.",
     "DMEL", "dna_familial_search"),

    # Wave 1211 — Santé: Medicare & personnes âgées (inédits)
    ("medicare_advantage_prior_auth_rights_engine.py",
     "Autorisations préalables abusives des Medicare Advantage & refus de soins couverts dans la Medicare traditionnelle", "Wave 1211",
     "Bénéficiaires Medicare Advantage dont les soins nécessaires sont refusés par leur plan privé via des autorisations préalables excessives.",
     "MAVE", "medicare_advan_auth"),
    ("home_care_aide_wage_rights_engine.py",
     "Salaires insuffisants des aides à domicile & exemptions législatives excluant les soins à domicile du minimum vital", "Wave 1211",
     "Aides à domicile gagnant moins que le salaire minimum en raison d'exemptions pour travailleurs domestiques dans certains États.",
     "HCAW", "home_care_wage"),
    ("prescription_drug_cost_cap_rights_engine.py",
     "Plafonnement des coûts de médicaments sur ordonnance pour seniors & droits des bénéficiaires Medicare à des prix abordables", "Wave 1211",
     "Seniors sous Medicare Part D dépensant des milliers par mois pour des médicaments vitaux sans plafond mensuel réel sur leur charge.",
     "PCFE", "prescr_cost_cap"),

    # Wave 1212 — Finance: protection des consommateurs (inédits)
    ("pay_to_day_pay_advance_rights_engine.py",
     "Avances sur salaire par des applications fintech & frais cachés équivalant à des taux d'intérêt usuraires non réglementés", "Wave 1212",
     "Travailleurs utilisant des apps d'avances sur salaire payant des frais présentés comme des pourboires équivalant à 300% APR.",
     "PAYD", "pay_advance_trap"),
    ("fintech_prepaid_card_hidden_fee_rights_engine.py",
     "Frais cachés des cartes prépayées fintech & droits des consommateurs à des informations complètes sur les coûts réels", "Wave 1212",
     "Consommateurs peu bancarisés utilisant des cartes prépayées perdant une fraction de leurs fonds en frais mensuels et de transaction.",
     "FCPE", "fintech_prepaid_fee"),
    ("mortgage_junk_fee_rights_engine.py",
     "Frais parasites dans les prêts hypothécaires & droits des emprunteurs à des frais de clôture transparents et justifiés", "Wave 1212",
     "Acheteurs immobiliers découvrant des milliers de frais de clôture non divulgués lors du closing qu'ils ne peuvent refuser.",
     "MLSP", "mortgage_junk_fee"),

    # Wave 1213 — Éducation: accès & équité (inédits)
    ("gifted_program_racial_equity_rights_engine.py",
     "Inégalités raciales dans les programmes pour enfants surdoués & sous-référencement des élèves noirs et latinos", "Wave 1213",
     "Enfants noirs et latinos sous-représentés dans les programmes d'enseignement pour surdoués malgré des scores comparables à leurs pairs.",
     "GCAD", "gifted_racial_equity"),
    ("college_campus_sexual_assault_ix_rights_engine.py",
     "Protections Title IX dans les cas de violence sexuelle sur campus & délais de procédure et partialité dans les audiences", "Wave 1213",
     "Survivantes d'agression sexuelle sur campus confrontées à des procédures Title IX biaisées ou à des délais de traitement excessifs.",
     "CSMR", "campus_ix_assault"),
    ("grade_retention_racial_gap_rights_engine.py",
     "Disparités raciales dans le redoublement scolaire & droits des élèves à un soutien pédagogique alternatif à la rétention", "Wave 1213",
     "Élèves noirs et latinos retenus une année scolaire à des taux plus élevés que leurs pairs blancs pour des performances similaires.",
     "GAPR", "grade_retain_race"),

    # Wave 1214 — Environnement: eau & conditions climatiques (inédits)
    ("water_affordability_shutoff_rights_engine.py",
     "Coupures d'eau pour non-paiement & droits des ménages pauvres à un service d'eau essentiel abordable sans interruption", "Wave 1214",
     "Ménages à faibles revenus confrontés à des coupures d'eau pour des factures impayées sans programme d'aide accessible.",
     "WPTP", "water_afford_shutoff"),
    ("extreme_drought_small_farm_rights_engine.py",
     "Impacts des sécheresses extrêmes sur les petits agriculteurs & droits aux indemnités d'assurance récolte et à l'aide fédérale", "Wave 1214",
     "Petits fermiers perdant des récoltes lors de sécheresses extrêmes refusés pour les indemnités USDA ou mal couverts par les polices.",
     "ESDH", "drought_small_farm"),
    ("mold_habitability_legal_right_rights_engine.py",
     "Présence de moisissures et habitabilité des logements locatifs & droits légaux des locataires à une remediation obligatoire", "Wave 1214",
     "Locataires avec moisissures toxiques dans leur logement confrontés à des propriétaires refusant d'agir sans obligation légale claire.",
     "MMLR", "mold_habitability"),

    # Wave 1215 — Santé mentale: accès & discrimination (inédits)
    ("mental_health_er_boarding_rights_engine.py",
     "Attente en urgences pour patients psychiatriques en crise & droits à un placement rapide dans des unités spécialisées", "Wave 1215",
     "Patients en crise psychiatrique attendant des jours aux urgences générales faute de lits psychiatriques disponibles dans leur région.",
     "HCAE", "mental_er_boarding"),
    ("psychiatric_medication_formulary_rights_engine.py",
     "Restrictions formulaires pour médicaments psychiatriques & step therapy forçant des changements non médicaux de traitement", "Wave 1215",
     "Patients psychiatriques stabilisés contraints par leur assurance de recommencer des traitements moins efficaces pour raisons de coût.",
     "PTCA", "psych_med_formulary"),
    ("involuntary_mental_health_hold_appeal_rights_engine.py",
     "Droits d'appel des personnes en hospitalisation psychiatrique involontaire & accès insuffisant à la représentation juridique", "Wave 1215",
     "Personnes placées en hospitalisation psychiatrique involontaire sans avocat disponible pour les aider à contester leur détention.",
     "IBPD", "involunt_hold_appeal"),

    # Wave 1216 — Droits divers: communautés & individus (inédits)
    ("malpractice_expert_witness_requirement_rights_engine.py",
     "Exigences d'expert dans les actions en faute médicale & coûts prohibitifs pour les victimes de négligence à faibles revenus", "Wave 1216",
     "Victimes de faute médicale incapables d'engager les experts requis pour déposer leur action en justice malgré une négligence évidente.",
     "MCAR", "malpract_expert"),
    ("mortgage_assumption_right_rights_engine.py",
     "Droit à la reprise de prêt hypothécaire assumable & obstacles des prêteurs à l'exercice du droit légal d'assumption", "Wave 1216",
     "Acheteurs et héritiers se voyant refuser l'assomption d'un prêt hypothécaire assumable malgré le droit légal explicite.",
     "MBAF", "mortgage_assumpt"),
    ("homecare_caregiver_family_leave_rights_engine.py",
     "Congé payé pour aidants familiaux de proches malades & droits insuffisants des travailleurs à des congés de soin rémunérés", "Wave 1216",
     "Travailleurs contraints de quitter leur emploi pour soigner un parent âgé ou malade sans congé payé accessible hors FMLA.",
     "HCFL", "homecare_family_leave"),
]
