# Specs waves 905-912 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision, 0 doublon interne (SLBN→ROTP corrigé)
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 905 — Déserts alimentaires & SNAP
    ("food_desert_transportation_rights_engine.py",
     "Déserts alimentaires & mobilité des résidents pauvres", "Wave 905",
     "Résidents de déserts alimentaires sans transport vers les épiceries les plus proches.",
     "FDTR", "food_desert_transport"),
    ("grocery_chain_redlining_rights_engine.py",
     "Chaînes d'épicerie & redlining alimentaire", "Wave 905",
     "Épiceries refusant d'ouvrir dans des quartiers pauvres ou minoritaires.",
     "GRCL", "grocery_redlining"),
    ("snap_benefit_cliff_rights_engine.py",
     "Falaise SNAP & perte d'aide alimentaire", "Wave 905",
     "Ménages perdant toutes leurs aides SNAP pour un dollar de revenu supplémentaire.",
     "SNBC", "snap_cliff"),

    # Wave 906 — Conditions SNAP & accès EBT
    ("snap_work_requirement_rights_engine.py",
     "Exigences de travail SNAP & exclusion des plus vulnérables", "Wave 906",
     "Conditions de travail SNAP éliminant des bénéficiaires incapables de les satisfaire.",
     "SNWR", "snap_work_req"),
    ("ebt_fee_atm_rights_engine.py",
     "Frais ATM sur les cartes EBT & ponction sur l'aide alimentaire", "Wave 906",
     "Frais bancaires sur les retraits EBT réduisant effectivement le montant de l'aide.",
     "EBTF", "ebt_atm_fee"),
    ("snap_online_purchase_access_rights_engine.py",
     "Achats en ligne SNAP & accès numérique des bénéficiaires", "Wave 906",
     "Bénéficiaires SNAP sans accès internet incapables d'utiliser les options en ligne.",
     "SNOP", "snap_online"),

    # Wave 907 — Dettes de cantine & nutrition scolaire
    ("school_meal_debt_rights_engine.py",
     "Dettes de cantine scolaire & honte alimentaire", "Wave 907",
     "Enfants poursuivis pour des dettes de cantine ou privés de repas chauds.",
     "SMDB", "school_meal_debt"),
    ("lunch_shaming_student_rights_engine.py",
     "Honte à la cantine & stigmatisation des élèves pauvres", "Wave 907",
     "Élèves humiliés publiquement pour dettes de repas devant leurs camarades.",
     "LSSH", "lunch_shaming"),
    ("wic_program_gap_rights_engine.py",
     "Programme WIC & lacunes de couverture nutritionnelle", "Wave 907",
     "Femmes enceintes et nourrissons non couverts par le WIC faute de financement.",
     "WICG", "wic_gap"),

    # Wave 908 — Petit-déjeuner & aide alimentaire
    ("school_breakfast_access_rights_engine.py",
     "Petit-déjeuner scolaire universel & accès inégal", "Wave 908",
     "Élèves affamés le matin dans des établissements sans programme de petit-déjeuner.",
     "SBRA", "school_breakfast"),
    ("food_bank_stigma_rights_engine.py",
     "Banques alimentaires & stigmatisation des usagers", "Wave 908",
     "Personnes évitant les banques alimentaires par honte, aggravant leur insécurité.",
     "FBSK", "food_bank_stigma"),
    ("community_fridge_zoning_rights_engine.py",
     "Frigos communautaires & obstacles réglementaires", "Wave 908",
     "Frigos solidaires interdits par des ordonnances de zonage défavorisant la solidarité.",
     "CFZN", "community_fridge"),

    # Wave 909 — Glanage & partage alimentaire
    ("gleaning_law_block_rights_engine.py",
     "Lois de glanage & blocage du partage alimentaire", "Wave 909",
     "Législations bloquant le glanage des surplus agricoles destinés à être détruits.",
     "GLNB", "gleaning_block"),
    ("dumpster_diving_criminalize_rights_engine.py",
     "Fouille de poubelles criminalisée & gaspillage alimentaire", "Wave 909",
     "Criminalisation de la récupération alimentaire dans les déchets des commerces.",
     "DDCR", "dumpster_criminalized"),
    ("food_waste_donation_barrier_rights_engine.py",
     "Dons alimentaires & barrières légales au partage", "Wave 909",
     "Commerces évitant les dons par peur de poursuites malgré les lois de protection.",
     "FWDB", "food_waste_donation"),

    # Wave 910 — Agriculture urbaine & semences
    ("urban_farm_zoning_rights_engine.py",
     "Agriculture urbaine & zonage restrictif", "Wave 910",
     "Zones urbaines interdisant l'agriculture qui pourrait nourrir des quartiers pauvres.",
     "UFZN", "urban_farm_zoning"),
    ("rooftop_garden_permit_rights_engine.py",
     "Jardins sur toits & obstacles administratifs", "Wave 910",
     "Permis introuvables empêchant les jardins sur toits de lutte contre les déserts alimentaires.",
     "ROTP", "rooftop_garden"),
    ("food_labeling_allergen_rights_engine.py",
     "Étiquetage alimentaire des allergènes & droits des consommateurs", "Wave 910",
     "Étiquetage trompeur ou incomplet exposant les allergiques à des risques mortels.",
     "FLAB", "food_allergen_label"),

    # Wave 911 — Alimentation, publicité & santé
    ("food_desert_hospital_admission_rights_engine.py",
     "Déserts alimentaires & hospitalisations évitables", "Wave 911",
     "Taux d'hospitalisation pour diabète et maladies cardiaques explosant dans les déserts alimentaires.",
     "FDHA", "food_desert_hospital"),
    ("junk_food_advertising_child_rights_engine.py",
     "Publicité alimentaire & enfants ciblés", "Wave 911",
     "Marketing de la malbouffe ciblant les enfants et aggravant l'obésité infantile.",
     "JFAC", "junk_food_ads"),
    ("nutrition_label_confusion_rights_engine.py",
     "Confusion des étiquettes nutritionnelles & désinformation", "Wave 911",
     "Étiquetage nutritionnel volontairement complexe trompant les consommateurs peu éduqués.",
     "NLBC", "nutrition_label"),

    # Wave 912 — Certification, résidus & coûts
    ("organic_certification_cost_rights_engine.py",
     "Certification bio & coût inaccessible aux petits producteurs", "Wave 912",
     "Coûts de certification bio exclusant les petits agriculteurs des marchés premium.",
     "OCCF", "organic_cert_cost"),
    ("pesticide_residue_produce_rights_engine.py",
     "Résidus de pesticides sur les fruits & légumes", "Wave 912",
     "Consommateurs exposés à des résidus de pesticides excédant les normes sans information.",
     "PRPC", "pesticide_produce"),
    ("seed_library_ban_rights_engine.py",
     "Bibliothèques de semences & interdictions législatives", "Wave 912",
     "Bibliothèques de semences fermées par des lois favorisant les brevets semenciers.",
     "SLBR", "seed_library"),
]
