# Specs waves 945-952 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 945 — Droits reproductifs post-Dobbs
    ("abortion_access_travel_rights_engine.py",
     "Droit à l'avortement & voyages interétatiques post-Dobbs", "Wave 945",
     "Femmes contraintes de voyager dans d'autres États pour accéder à l'avortement après Dobbs.",
     "AAVT", "abortion_travel"),
    ("medication_abortion_access_rights_engine.py",
     "Accès à l'avortement médicamenteux & poursuites étatiques", "Wave 945",
     "États criminalisant l'expédition par courrier de médicaments abortifs légaux fédéralement.",
     "MAAB", "medication_abortion"),
    ("parental_consent_abortion_rights_engine.py",
     "Consentement parental pour avortement & droits des mineures", "Wave 945",
     "Mineures contraintes d'obtenir le consentement parental ou une dispense judiciaire pour avorter.",
     "PCAB", "parental_consent_abort"),

    # Wave 946 — FIV, fausses couches & couverture contraceptive
    ("ivf_access_rights_engine.py",
     "Accès à la FIV & droits à la parentalité assistée", "Wave 946",
     "Couples infertiles privés de FIV par des lois reconnaissant la personnalité juridique des embryons.",
     "IVFA", "ivf_access"),
    ("miscarriage_criminal_prosecution_rights_engine.py",
     "Poursuites criminelles pour fausses couches & droits reproductifs", "Wave 946",
     "Femmes poursuivies pénalement après une fausse couche dans des États aux lois anti-avortement.",
     "MCPR", "miscarriage_crim"),
    ("employer_contraception_coverage_rights_engine.py",
     "Couverture contraceptive par l'employeur & refus religieux", "Wave 946",
     "Employeurs invoquant des exemptions religieuses pour refuser la couverture contraceptive.",
     "ECCR", "employer_contraception"),

    # Wave 947 — Handicap : emploi & discrimination
    ("ada_workplace_accommodation_rights_engine.py",
     "ADA & refus d'aménagements raisonnables au travail", "Wave 947",
     "Employeurs refusant des aménagements raisonnables aux travailleurs handicapés malgré l'ADA.",
     "ADAW", "ada_workplace"),
    ("disability_hiring_discrimination_rights_engine.py",
     "Discrimination à l'embauche contre les personnes handicapées", "Wave 947",
     "Candidats handicapés qualifiés systématiquement écartés lors des processus de recrutement.",
     "DHDM", "disability_hiring"),
    ("ada_public_accommodation_rights_engine.py",
     "ADA & accessibilité des lieux publics pour personnes handicapées", "Wave 947",
     "Commerces et lieux publics refusant ou ignorant les obligations d'accessibilité de l'ADA.",
     "ADPA", "ada_public_accomm"),

    # Wave 948 — Santé mentale : parité d'assurance & alternatives judiciaires
    ("mental_health_parity_insurance_rights_engine.py",
     "Parité d'assurance santé mentale & inégalité de couverture", "Wave 948",
     "Assureurs couvrant moins bien la santé mentale que les soins physiques en violation de la loi.",
     "MHPI", "mental_parity"),
    ("mental_health_court_rights_engine.py",
     "Tribunaux de santé mentale & alternatives à l'incarcération", "Wave 948",
     "Accès inégal aux tribunaux de santé mentale qui permettent d'éviter l'incarcération.",
     "MHCR", "mental_health_court"),
    ("psychiatric_advance_directive_rights_engine.py",
     "Directives anticipées psychiatriques & autonomie des patients", "Wave 948",
     "Patients psychiatriques dont les directives anticipées sont ignorées lors des crises.",
     "PADR", "psych_advance_dir"),

    # Wave 949 — Immigration : procédures judiciaires & droits
    ("asylum_seeker_deportation_rights_engine.py",
     "Demandeurs d'asile déportés sans audience équitable", "Wave 949",
     "Demandeurs d'asile expulsés avant que leur dossier soit entendu par un tribunal d'immigration.",
     "ASDR", "asylum_deportation"),
    ("immigration_bond_unaffordable_rights_engine.py",
     "Cautions d'immigration inaccessibles & détention prolongée", "Wave 949",
     "Détenus immigrants incapables de payer des cautions d'immigration astronomiques, détenus des mois.",
     "IBUA", "immigration_bond"),
    ("immigration_court_interpreter_rights_engine.py",
     "Droit à l'interprète dans les procédures d'immigration", "Wave 949",
     "Détenus immigrants compris lors d'audiences judiciaires sans interprète qualifié.",
     "IIPR", "immigration_interp"),

    # Wave 950 — Énergie propre & droits des communautés
    ("solar_permit_barrier_rights_engine.py",
     "Obstacles administratifs aux permis d'énergie solaire", "Wave 950",
     "Propriétaires bloqués par des délais et frais bureaucratiques pour installer du solaire.",
     "SPBR", "solar_permit"),
    ("fossil_fuel_displaced_worker_rights_engine.py",
     "Travailleurs des combustibles fossiles déplacés & reconversion", "Wave 950",
     "Mineurs et travailleurs pétroliers sans programme de reconversion lors de la fermeture des sites.",
     "CEDW", "fossil_displaced"),
    ("clean_energy_community_benefit_rights_engine.py",
     "Bénéfices de l'énergie propre & exclusion des communautés locales", "Wave 950",
     "Communautés rurales accueillant des projets d'énergie propre sans partage des bénéfices.",
     "CECB", "clean_energy_community"),

    # Wave 951 — Droits des travailleurs freelance & indépendants
    ("freelancer_unpaid_invoice_rights_engine.py",
     "Facturation impayée des freelances & accès à la justice", "Wave 951",
     "Freelances incapables de récupérer les honoraires impayés par des clients sans recours abordable.",
     "FUIR", "freelancer_unpaid"),
    ("independent_contractor_benefit_exclusion_rights_engine.py",
     "Exclusion des avantages sociaux pour les contractuels indépendants", "Wave 951",
     "Travailleurs indépendants privés d'assurance maladie, retraite et congés payés des salariés.",
     "ICBE", "contractor_benefit"),
    ("gig_worker_social_security_rights_engine.py",
     "Cotisations sécurité sociale des travailleurs de plateformes", "Wave 951",
     "Travailleurs de plateformes payant la double cotisation SS sans les protections des employés.",
     "GWSS", "gig_social_sec"),

    # Wave 952 — Environnement urbain & santé des communautés
    ("thermal_water_pollution_rights_engine.py",
     "Pollution thermique de l'eau & impacts sur les écosystèmes aquatiques", "Wave 952",
     "Centrales électriques déversant de l'eau chaude dans les rivières détruisant les écosystèmes.",
     "TWPR", "thermal_water"),
    ("urban_green_space_equity_rights_engine.py",
     "Espaces verts urbains & inégalité d'accès pour les communautés pauvres", "Wave 952",
     "Quartiers pauvres et minoritaires avec moins de parcs et d'espaces verts par habitant.",
     "UGSE", "urban_green_equity"),
    ("fossil_fuel_community_health_rights_engine.py",
     "Santé des communautés proches des industries polluantes aux combustibles fossiles", "Wave 952",
     "Résidents vivant près de raffineries et centrales subissant des taux de cancer et maladies chroniques.",
     "RFCH", "fossil_community_health"),
]
