# Specs waves 809-816 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 809 — Violences d'État & exécutions
    ("drug_war_civilian_killing_rights_engine.py",
     "Guerre contre la drogue & meurtres de civils", "Wave 809",
     "Civils tués dans des opérations antidrogue sans procédure ni justice.",
     "DWCK", "drug_war_civilian"),
    ("extrajudicial_execution_state_rights_engine.py",
     "Exécutions extrajudiciaires par l'État", "Wave 809",
     "Meurtres commis par les forces de l'ordre hors de tout cadre légal.",
     "EXJE", "extrajudicial_execution"),
    ("protest_crowd_control_injury_rights_engine.py",
     "Maintien de l'ordre & blessés lors de manifestations", "Wave 809",
     "Manifestants blessés ou tués par des techniques de dispersion prohibées.",
     "PCCR", "protest_crowd_control"),

    # Wave 810 — Surveillance politique & dissidence
    ("teargas_civilian_residential_rights_engine.py",
     "Gaz lacrymogènes dans les zones résidentielles", "Wave 810",
     "Usage de gaz lacrymogènes en zones habitées intoxiquant enfants et malades.",
     "TGCI", "teargas_civilian"),
    ("surveillance_activist_targeting_rights_engine.py",
     "Surveillance ciblée des militants", "Wave 810",
     "Activistes suivis, fichés et intimidés via des outils de surveillance numérique.",
     "SACT", "activist_surveillance"),
    ("red_list_dissident_disappearance_rights_engine.py",
     "Listes rouges & disparitions de dissidents", "Wave 810",
     "Dissidents inscrits sur des listes secrètes exposés aux enlèvements et aux disparitions.",
     "RDDI", "redlist_dissident"),

    # Wave 811 — Liberté de la presse & sources
    ("journalist_source_protection_rights_engine.py",
     "Protection des sources journalistiques", "Wave 811",
     "Sources journalistiques identifiées et poursuivies faute de protection légale effective.",
     "JSOP", "journalist_source"),
    ("media_capture_oligarch_rights_engine.py",
     "Capture des médias par les oligarques", "Wave 811",
     "Concentration médiatique aux mains d'oligarques détruisant l'indépendance éditoriale.",
     "MCOL", "media_oligarch"),
    ("newsroom_safety_physical_threats_rights_engine.py",
     "Sécurité des rédactions & menaces physiques", "Wave 811",
     "Journalistes agressés, menacés de mort ou harcelés dans leurs rédactions.",
     "NWSF", "newsroom_safety"),

    # Wave 812 — Désinformation & espace numérique
    ("disinformation_state_actor_rights_engine.py",
     "Désinformation d'État & droits civiques", "Wave 812",
     "Campagnes de désinformation pilotées par des États sabotant le débat public.",
     "DISA", "state_disinformation"),
    ("internet_shutdown_protest_rights_engine.py",
     "Coupures d'Internet lors de manifestations", "Wave 812",
     "Coupures d'Internet étouffant les mobilisations citoyennes et l'information.",
     "ISPR", "internet_shutdown"),
    ("stop_frisk_racial_rights_engine.py",
     "Contrôles au faciès & stop-and-frisk", "Wave 812",
     "Interpellations préventives ciblant systématiquement les minorités raciales.",
     "SFRI", "stop_frisk"),

    # Wave 813 — Demande d'asile & frontières judiciaires
    ("asylum_evidence_standard_rights_engine.py",
     "Normes de preuve pour l'asile & fardeau injuste", "Wave 813",
     "Demandeurs d'asile déboutés faute de preuves impossibles à réunir seuls.",
     "ASED", "asylum_evidence"),
    ("refugee_family_separation_border_rights_engine.py",
     "Séparation des familles à la frontière", "Wave 813",
     "Enfants séparés de leurs parents à la frontière, traumatisés et sans représentation.",
     "RFSE", "refugee_family_sep"),
    ("stateless_birth_registration_rights_engine.py",
     "Apatridie & enregistrement des naissances", "Wave 813",
     "Enfants non déclarés à la naissance, invisibles pour l'État et privés de droits.",
     "SNBR", "stateless_birth"),

    # Wave 814 — Stérilisation & violence reproductive d'État
    ("forced_sterilization_minority_rights_engine.py",
     "Stérilisation forcée des minorités", "Wave 814",
     "Stérilisations imposées à des femmes de groupes minoritaires sans consentement.",
     "FSMI", "forced_sterilization"),
    ("prison_rape_reporting_rights_engine.py",
     "Viol en détention & impunité", "Wave 814",
     "Violences sexuelles en prison sous-déclarées et ignorées par les autorités.",
     "PRPE", "prison_rape"),
    ("reproductive_coercion_partner_rights_engine.py",
     "Coercition reproductive par le partenaire", "Wave 814",
     "Sabotage de contraception et grossesses imposées par des partenaires violents.",
     "RPCO", "reproductive_coercion"),

    # Wave 815 — Violences basées sur le genre & survivantes
    ("domestic_homicide_femicide_rights_engine.py",
     "Féminicide & homicide domestique", "Wave 815",
     "Femmes tuées par leur partenaire intime dans un contexte d'impunité systémique.",
     "DHFE", "femicide"),
    ("acid_attack_survivor_rights_engine.py",
     "Attaques à l'acide & survivantes", "Wave 815",
     "Survivantes d'attaques à l'acide sans soins, sans justice ni réhabilitation.",
     "AATS", "acid_attack"),
    ("fgm_survivor_healthcare_rights_engine.py",
     "Survivantes de MGF & accès aux soins", "Wave 815",
     "Survivantes de mutilations génitales féminines sans prise en charge médicale adaptée.",
     "FGMS", "fgm_survivor"),

    # Wave 816 — Pratiques traditionnelles néfastes
    ("breast_ironing_practice_rights_engine.py",
     "Repassage des seins & pratique néfaste", "Wave 816",
     "Jeunes filles victimes du repassage des seins, pratique masquée et douloureuse.",
     "BRIR", "breast_ironing"),
    ("widowhood_ritual_violence_rights_engine.py",
     "Rituels de veuvage & violences imposées", "Wave 816",
     "Veuves soumises à des rituels humiliants ou dangereux imposés par la communauté.",
     "WIDR", "widowhood_ritual"),
    ("police_surveillance_minority_rights_engine.py",
     "Surveillance policière des communautés minoritaires", "Wave 816",
     "Quartiers minoritaires sous surveillance policière disproportionnée et intrusives.",
     "PSUR", "police_surveillance"),
]
