# Specs waves 1017-1024 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : FLAB→FLBD (food_labeling_allergen pris) ; 0 collision après correction, 0 doublon interne
# Remplacements : seed_patent→crop_insurance ; elder_guardianship→elder_poa_fraud
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1017 — Sports & droits des athlètes spécifiques
    ("marathon_heat_safety_rights_engine.py",
     "Sécurité thermique des marathons & responsabilité des organisateurs", "Wave 1017",
     "Coureurs de marathon mourant ou subissant des coups de chaleur sans protocoles de sécurité adéquats.",
     "MRHS", "marathon_heat_safety"),
    ("nfl_cheerleader_labor_rights_engine.py",
     "Droits du travail des majorettes NFL & classement injuste", "Wave 1017",
     "Majorettes NFL traitées comme contractuelles indépendantes, payées sous le salaire minimum sans avantages.",
     "CNFL", "nfl_cheerleader"),
    ("esports_minor_exploitation_rights_engine.py",
     "Mineurs esportifs & exploitation par les organisations sans protection légale", "Wave 1017",
     "Joueurs esports mineurs sous contrats abusifs sans scolarité garantie ni protection de revenus.",
     "EMEX", "esports_minor"),

    # Wave 1018 — Immigration & travail (nouveaux angles)
    ("h2b_seasonal_worker_rights_engine.py",
     "Travailleurs saisonniers H-2B non agricoles & vulnérabilité à l'exploitation", "Wave 1018",
     "Travailleurs H-2B dans l'hôtellerie et le paysagisme liés à leur employeur sans mobilité légale.",
     "H2BV", "h2b_seasonal"),
    ("undocumented_work_injury_rights_engine.py",
     "Travailleurs sans-papiers blessés au travail & absence de recours légal", "Wave 1018",
     "Travailleurs immigrés sans titre de séjour blessés sur le tas refusés par les assurances accident.",
     "UWIR", "undoc_work_injury"),
    ("e2_entrepreneur_visa_barrier_rights_engine.py",
     "Visa E-2/EB-5 & barrières pour entrepreneurs immigrants à faibles revenus", "Wave 1018",
     "Entrepreneurs immigrants exclus du visa investisseur par des seuils d'investissement inaccessibles.",
     "E2VB", "e2_visa_barrier"),

    # Wave 1019 — Logement & constructions neuves
    ("new_construction_defect_rights_engine.py",
     "Défauts de construction dans les logements neufs & recours des propriétaires", "Wave 1019",
     "Propriétaires de maisons neuves défectueuses bloqués par des clauses d'arbitrage imposées par les promoteurs.",
     "NCDR", "construction_defect"),
    ("construction_subcontractor_wage_theft_rights_engine.py",
     "Vol de salaire des sous-traitants de construction & responsabilité des donneurs d'ordre", "Wave 1019",
     "Ouvriers de construction sous-traités non payés sans recours contre les contractants généraux.",
     "CWTS", "construct_sub_wages"),
    ("manufactured_home_warranty_rights_engine.py",
     "Garanties des maisons préfabriquées & droits des propriétaires lésés", "Wave 1019",
     "Propriétaires de maisons manufactures refusés dans leurs garanties par des fabricants peu transparents.",
     "MHWG", "manuf_home_warranty"),

    # Wave 1020 — Santé reproductive avancée & PMA
    ("egg_donor_long_term_health_rights_engine.py",
     "Donneuses d'ovocytes & absence de suivi médical à long terme", "Wave 1020",
     "Jeunes femmes ayant donné des ovocytes sans information sur les risques à long terme ni suivi médical.",
     "EDOH", "egg_donor_health"),
    ("sperm_donor_identity_rights_engine.py",
     "Droit des enfants donneurs de sperme à connaître leur identité génétique", "Wave 1020",
     "Enfants conçus par don de sperme anonyme privés de leur droit à connaître l'identité de leur donneur.",
     "SPDI", "sperm_donor_id"),
    ("surrogacy_contract_enforcement_rights_engine.py",
     "Mères porteuses & inexécutabilité des contrats dans les États non réglementés", "Wave 1020",
     "Mères porteuses ou parents d'intention sans recours légal dans des États n'ayant pas légiféré sur la GPA.",
     "SCCF", "surrogacy_enforce"),

    # Wave 1021 — Justice pour victimes & procédures pénales
    ("crime_victim_restitution_collection_rights_engine.py",
     "Restitution aux victimes de crimes & absence de mécanisme de recouvrement", "Wave 1021",
     "Victimes obtenant des ordonnances de restitution judiciaires impossibles à recouvrer auprès des condamnés.",
     "CVRC", "victim_restitution"),
    ("false_confession_coercion_rights_engine.py",
     "Fausses confessions coercitives & droits des suspects interrogés", "Wave 1021",
     "Suspects, notamment des mineurs, obtenant de fausses confessions sous pression policière intense.",
     "FCCR", "false_confession"),
    ("wrongful_termination_burden_rights_engine.py",
     "Licenciement injustifié & fardeau de preuve prohibitif pour les victimes", "Wave 1021",
     "Employés licenciés pour discrimination sans capacité à prouver l'intention discriminatoire de l'employeur.",
     "WTPB", "wrongful_term_proof"),

    # Wave 1022 — Seniors : finances & protection (inédits)
    ("elder_power_attorney_fraud_rights_engine.py",
     "Fraude à la procuration financière & exploitation des personnes âgées", "Wave 1022",
     "Personnes âgées dépossédées de leurs biens par des proches abusant de procurations financières.",
     "EPNF", "elder_poa_fraud"),
    ("pension_fund_mismanagement_rights_engine.py",
     "Mauvaise gestion des fonds de retraite & pertes pour les pensionnaires", "Wave 1022",
     "Retraités perdant leurs pensions à cause de mauvaises gestions de fonds sans garanties suffisantes PBGC.",
     "PFMN", "pension_mismanage"),
    ("long_term_care_insurance_denial_rights_engine.py",
     "Refus d'assurance dépendance & abandon des seniors aux soins coûteux", "Wave 1022",
     "Aînés se voyant refuser ou annuler leur assurance soins longue durée au moment de leur plus grand besoin.",
     "LTCD", "ltc_insur_deny"),

    # Wave 1023 — Consommateurs & protection contre les abus commerciaux
    ("auto_warranty_dealer_fraud_rights_engine.py",
     "Fraude aux garanties automobiles par les concessionnaires & droits acheteurs", "Wave 1023",
     "Acheteurs de véhicules trompés sur la nature des garanties ou vendant des couvertures inutiles.",
     "AWFD", "auto_warranty_fraud"),
    ("subscription_dark_pattern_rights_engine.py",
     "Dark patterns d'abonnement & obstacles à l'annulation des services", "Wave 1023",
     "Consommateurs piégés dans des abonnements payants impossibles à annuler par conception délibérée.",
     "SCDB", "subscription_dark"),
    ("ticket_resale_fee_rights_engine.py",
     "Frais cachés des revendeurs de billets & droits des consommateurs", "Wave 1023",
     "Consommateurs choqués par des frais de service de 30 à 50% ajoutés en fin de transaction sur les billets.",
     "TSFR", "ticket_resale_fee"),

    # Wave 1024 — Agriculture & alimentation (inédits)
    ("small_farmer_usda_bias_rights_engine.py",
     "Biais des programmes USDA contre les petits agriculteurs & équité", "Wave 1024",
     "Petits agriculteurs et agriculteurs de couleur structurellement exclus des aides USDA favorisant les grandes fermes.",
     "SFUB", "small_farmer_usda"),
    ("crop_insurance_small_farmer_rights_engine.py",
     "Assurance récolte & exclusion des petits exploitants agricoles", "Wave 1024",
     "Petits agriculteurs incapables d'accéder aux programmes d'assurance récolte fédéraux bénéficiant aux géants.",
     "CFIS", "crop_insur_small"),
    ("food_label_deception_rights_engine.py",
     "Étiquetage alimentaire trompeur & droits des consommateurs contre les allégations mensongères", "Wave 1024",
     "Consommateurs trompés par des allégations marketing comme 'naturel' ou 'sain' sans définition légale.",
     "FLBD", "food_label_deceive"),
]
