# Specs waves 873-880 — 24 nouveaux moteurs de droits humains (batch final)
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 873 — Familles non conventionnelles & droits
    ("polyamory_legal_recognition_rights_engine.py",
     "Polyamour & reconnaissance légale des familles", "Wave 873",
     "Familles polyamoureuses sans protection légale pour les partenaires et les enfants.",
     "PLRY", "polyamory_legal"),
    ("cohabitation_property_right_rights_engine.py",
     "Cohabitation & droits patrimoniaux des conjoints de fait", "Wave 873",
     "Conjoints de fait sans droits patrimoniaux en cas de séparation ou de décès.",
     "CHPR", "cohabitation_property"),
    ("common_law_marriage_gap_rights_engine.py",
     "Mariage coutumier & vide juridique de protection", "Wave 873",
     "Unions de droit coutumier sans équivalence légale laissant les partenaires sans recours.",
     "CLMG", "common_law_gap"),

    # Wave 874 — Statuts familiaux & exclusions
    ("domestic_partnership_exclusion_rights_engine.py",
     "Partenariats domestiques & exclusions sectorielles", "Wave 874",
     "Partenariats civils non reconnus par des employeurs ou systèmes de retraite.",
     "DPEX", "domestic_partner"),
    ("consensual_nonmonogamy_discrimination_rights_engine.py",
     "Non-monogamie consentie & discrimination", "Wave 874",
     "Personnes en relations plurielles discriminées dans l'emploi, la garde d'enfants et le logement.",
     "CNDM", "nonmonogamy_discrim"),
    ("sex_offender_registry_reform_rights_engine.py",
     "Registre des délinquants sexuels & réforme", "Wave 874",
     "Registres des délinquants sexuels perpétuant la stigmatisation sans réduire la récidive.",
     "SORR", "sex_registry_reform"),

    # Wave 875 — Registres pénaux & résidences
    ("juvenile_sex_offense_registry_rights_engine.py",
     "Mineurs & inscription à vie sur les registres sexuels", "Wave 875",
     "Mineurs auteurs d'infractions sexuelles inscrits à vie sur des registres publics.",
     "JSOR", "juvenile_registry"),
    ("homeless_sex_offender_housing_rights_engine.py",
     "Sans-abri inscrits sur registre & logement impossible", "Wave 875",
     "Délinquants sexuels sans logement possible à cause des restrictions de résidence.",
     "HSOR", "homeless_sex_reg"),
    ("residency_restriction_sex_registry_rights_engine.py",
     "Restrictions de résidence & registre des délinquants", "Wave 875",
     "Zones d'exclusion résidentielle rendant impossible la réinsertion des inscrits.",
     "RSRH", "residency_sex_restrict"),

    # Wave 876 — Sans-abrisme & criminalisation de la pauvreté
    ("panhandling_ban_rights_engine.py",
     "Interdiction de mendicité & criminalisation de la pauvreté", "Wave 876",
     "Lois anti-mendicité ciblant les sans-abri plutôt que les causes de la pauvreté.",
     "PHBN", "panhandling_ban"),
    ("sitting_lying_ban_public_rights_engine.py",
     "Interdiction de s'asseoir ou se coucher en public", "Wave 876",
     "Ordonnances anti-campement pénalisant les comportements inévitables des sans-abri.",
     "SLBN", "sitting_lying"),
    ("urban_camping_ban_rights_engine.py",
     "Interdiction de camper en ville & droits des sans-abri", "Wave 876",
     "Interdictions de campement urbain sans offre alternative de logement ou d'hébergement.",
     "UCBN", "urban_camping"),

    # Wave 877 — Destructions de camps & transition
    ("sweeps_homeless_property_rights_engine.py",
     "Expulsions de campements & destruction de biens", "Wave 877",
     "Opérations de nettoyage de campements détruisant les effets personnels des sans-abri.",
     "SHPR", "homeless_sweeps_property"),
    ("sweeps_camp_destruction_rights_engine.py",
     "Destruction de campements & droits fondamentaux", "Wave 877",
     "Démantèlement forcé de campements sans relogement préalable ni respect de la dignité.",
     "SCDP", "camp_destruction"),
    ("transitional_housing_waitlist_rights_engine.py",
     "Listes d'attente pour logements de transition", "Wave 877",
     "Sans-abri attendant des années un logement de transition inexistant en quantité suffisante.",
     "THWI", "transition_wait"),

    # Wave 878 — Réduction des risques & drogues
    ("substance_use_syringe_service_rights_engine.py",
     "Programmes d'échange de seringues & droits des usagers", "Wave 878",
     "Programmes d'échange de seringues criminalisés, aggravant les épidémies de VIH et hépatite.",
     "SYRV", "syringe_service"),
    ("harm_reduction_criminalization_rights_engine.py",
     "Réduction des risques & criminalisation", "Wave 878",
     "Politiques criminalisant les services de réduction des risques, tuant plus qu'elles ne protègent.",
     "HRDC", "harm_reduction_crim"),
    ("naloxone_access_barrier_rights_engine.py",
     "Accès à la naloxone & barrières réglementaires", "Wave 878",
     "Prescriptions et restrictions limitant l'accès à la naloxone et les décès évitables par overdose.",
     "NALB", "naloxone_access"),

    # Wave 879 — Rétablissement & réinsertion
    ("addiction_recovery_discrimination_rights_engine.py",
     "Rétablissement de l'addiction & discrimination à l'emploi", "Wave 879",
     "Personnes en rétablissement refusées à l'emploi, au logement et aux soins.",
     "ADRD", "recovery_discrimination"),
    ("sober_living_zoning_exclusion_rights_engine.py",
     "Résidences de sobriété & exclusion par le zonage", "Wave 879",
     "Maisons de rétablissement bloquées par des réglementations de zonage discriminatoires.",
     "SLZN", "sober_zoning"),
    ("opioid_crisis_rural_access_rights_engine.py",
     "Crise des opioïdes & désert rural de traitement", "Wave 879",
     "Communautés rurales ravagées par les opioïdes sans cliniques de traitement accessibles.",
     "OCRU", "opioid_rural"),

    # Wave 880 — Contamination & urgence de santé publique
    ("fentanyl_contamination_harm_rights_engine.py",
     "Contamination au fentanyl & risque de masse", "Wave 880",
     "Fentanyl contaminant des drogues illicites tuant des usagers sans avertissement.",
     "FCOH", "fentanyl_harm"),
    ("neighbor_registry_notification_rights_engine.py",
     "Notification de voisinage & registre des délinquants", "Wave 880",
     "Notifications publiques forçant les délinquants enregistrés à subir harcèlement communautaire.",
     "NRSH", "neighbor_notify"),
    ("criminalized_homelessness_cycle_rights_engine.py",
     "Sans-abrisme criminalisé & cycle de récidive", "Wave 880",
     "Infractions liées au sans-abrisme créant des casiers judiciaires bloquant toute réinsertion.",
     "CRHM", "criminalized_homeless"),
]
