# Specs waves 1353-1360 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1353 — Santé: maladies rares & chroniques (inédits)
    ("gastroparesis_disability_accommodation_rights_engine.py",
     "Gastroparésie comme handicap & droits des patients à des accommodements professionnels et une reconnaissance médicale d'une affection digestive sévère souvent invisible et minimisée", "Wave 1353",
     "Personnes atteintes de gastroparésie sévère confrontées à des refus d'accommodements et à une reconnaissance médicale insuffisante de leur affection digestive invalidante.",
     "GPDA", "gastroparesis_disab"),
    ("lupus_nephritis_treatment_access_rights_engine.py",
     "Accès au traitement de la néphrite lupique & droits des patients atteints de lupus avec atteinte rénale à des thérapies immunosuppressives avancées sans restrictions d'assurance", "Wave 1353",
     "Patients atteints de néphrite lupique risquant une insuffisance rénale se voyant refuser des traitements immunosuppresseurs avancés au profit de protocoles moins efficaces.",
     "LNTA", "lupus_nephritis_treat"),
    ("myasthenia_gravis_treatment_access_rights_engine.py",
     "Accès aux traitements de la myasthénie grave & droits des patients à des thérapies ciblées et immunoglobulines sans être limités aux traitements de première ligne inefficaces", "Wave 1353",
     "Patients atteints de myasthénie grave réfractaire se voyant refuser l'accès aux nouvelles thérapies ciblées coûteuses par leur assureur malgré l'échec des traitements standard.",
     "MGTA", "myasthenia_gravis_treat"),

    # Wave 1354 — Santé & environnement (inédits)
    ("pku_metabolic_diet_coverage_rights_engine.py",
     "Couverture des aliments médicaux pour la phénylcétonurie & droits des patients atteints de troubles métaboliques à une prise en charge des formules et aliments médicaux vitaux", "Wave 1354",
     "Personnes atteintes de phénylcétonurie ou autres troubles métaboliques devant payer de leur poche des aliments médicaux coûteux non couverts par leur assurance maladie.",
     "PKMD", "pku_metabolic_diet"),
    ("nitrate_drinking_water_rural_rights_engine.py",
     "Contamination de l'eau potable par les nitrates en zone rurale & droits des résidents à une eau sûre face aux ruissellements agricoles polluant les puits et réseaux locaux", "Wave 1354",
     "Familles rurales consommant une eau de puits contaminée par des nitrates issus de l'agriculture intensive sans accès à des tests gratuits ni à des solutions de traitement financées.",
     "NDWR", "nitrate_water_rural"),
    ("septic_system_failure_low_income_rights_engine.py",
     "Défaillance des fosses septiques chez les ménages à faibles revenus & droits des propriétaires défavorisés à une aide pour les réparations sanitaires essentielles à la salubrité", "Wave 1354",
     "Propriétaires à faibles revenus en zone rurale confrontés à des fosses septiques défaillantes créant des risques sanitaires sans accès à des programmes d'aide à la réparation.",
     "SSFL", "septic_failure_low_inc"),

    # Wave 1355 — Logement: locataires vulnérables (inédits)
    ("mobile_home_lot_rent_increase_rights_engine.py",
     "Augmentations de loyer des emplacements de maisons mobiles & droits des propriétaires de mobil-homes à une protection contre les hausses abusives de loyer du terrain qu'ils ne possèdent pas", "Wave 1355",
     "Propriétaires de maisons mobiles possédant leur logement mais louant le terrain confrontés à des hausses de loyer foncier les forçant à abandonner un bien impossible à déplacer.",
     "MHLR", "mobile_home_lot_rent"),
    ("squatter_occupant_eviction_process_rights_engine.py",
     "Procédure régulière d'expulsion des occupants sans titre & droits à une procédure judiciaire équitable distinguant les occupants de bonne foi des intrus sans recours à l'auto-justice", "Wave 1355",
     "Occupants de logements sans bail formel confrontés à des expulsions illégales par auto-justice du propriétaire sans procédure judiciaire ni distinction de leur situation réelle.",
     "SOEP", "squatter_occupant_evict"),
    ("rent_reporting_credit_building_rights_engine.py",
     "Déclaration des loyers pour bâtir un historique de crédit & droits des locataires à faire compter leurs paiements de loyer ponctuels dans leur dossier de crédit sans frais cachés", "Wave 1355",
     "Locataires payant leur loyer ponctuellement pendant des années sans bénéfice pour leur score de crédit, désavantagés par rapport aux propriétaires dont les paiements hypothécaires comptent.",
     "RRCB", "rent_reporting_credit"),

    # Wave 1356 — Finance: prédateur & accès (inédits)
    ("earned_wage_access_fee_rights_engine.py",
     "Frais des avances sur salaire gagné & droits des travailleurs à accéder à leur salaire déjà gagné sans frais d'avance équivalant à des taux d'intérêt usuraires déguisés", "Wave 1356",
     "Travailleurs à faibles revenus utilisant des applications d'avance sur salaire payant des frais et pourboires répétés équivalant à des taux annuels effectifs de plusieurs centaines de pour cent.",
     "EWAF", "earned_wage_access_fee"),
    ("overdraft_opt_in_abuse_rights_engine.py",
     "Abus du consentement aux découverts bancaires & droits des consommateurs à ne pas être inscrits par défaut à des programmes de découvert coûteux sans consentement éclairé", "Wave 1356",
     "Consommateurs facturés de frais de découvert élevés sur de petites transactions par carte de débit en raison d'inscriptions à des programmes de couverture sans consentement clair.",
     "OOIA", "overdraft_opt_in"),
    ("medical_credit_card_predatory_rights_engine.py",
     "Cartes de crédit médicales prédatrices & droits des patients à comprendre les taux d'intérêt différés avant de financer des soins via des cartes promues dans les cabinets médicaux", "Wave 1356",
     "Patients incités à financer des soins dentaires ou médicaux via des cartes de crédit médicales à intérêt différé subissant des taux rétroactifs punitifs en cas de retard de paiement.",
     "MCCP", "medical_credit_card"),

    # Wave 1357 — Travail: secteurs spécifiques (inédits)
    ("warehouse_productivity_quota_injury_rights_engine.py",
     "Quotas de productivité dangereux en entrepôt & droits des travailleurs à des cadences de travail ne compromettant pas leur sécurité physique ni leur droit aux pauses légales", "Wave 1357",
     "Travailleurs d'entrepôts logistiques soumis à des quotas algorithmiques imposant des cadences provoquant des blessures musculo-squelettiques et privant des pauses nécessaires.",
     "WPQI", "warehouse_quota_injury"),
    ("commercial_driver_detention_time_pay_rights_engine.py",
     "Rémunération du temps d'attente des chauffeurs routiers & droits des conducteurs à être payés pour les heures d'attente lors des chargements et déchargements aux quais", "Wave 1357",
     "Chauffeurs de poids lourds attendant des heures non rémunérées aux quais de chargement, perdant un revenu significatif et dépassant leurs limites légales de service sans compensation.",
     "CDDT", "driver_detention_time"),
    ("healthcare_worker_workplace_violence_rights_engine.py",
     "Violence au travail contre les soignants & droits des professionnels de santé à une protection contre les agressions de patients et à des protocoles de sécurité obligatoires", "Wave 1357",
     "Infirmiers et soignants subissant des agressions physiques et verbales fréquentes de la part de patients sans protocoles de sécurité adéquats ni protection légale renforcée.",
     "HWWV", "healthcare_worker_viol"),

    # Wave 1358 — Immigration: détention & procédure (inédits)
    ("ice_detention_solitary_confinement_rights_engine.py",
     "Isolement cellulaire dans les centres de rétention immigration & droits des détenus civils à ne pas subir d'isolement prolongé utilisé comme punition sans procédure régulière", "Wave 1358",
     "Détenus en rétention immigration placés en isolement cellulaire prolongé comme mesure punitive ou pour leur vulnérabilité sans justification médicale ni examen indépendant.",
     "IDSC", "ice_detention_solitary"),
    ("border_asylum_metering_turnback_rights_engine.py",
     "Limitation du nombre de demandes d'asile aux frontières & droits des demandeurs à présenter leur demande aux points d'entrée sans refoulement ni listes d'attente illégales", "Wave 1358",
     "Demandeurs d'asile refoulés aux points d'entrée officiels par des pratiques de limitation quotidienne les contraignant à attendre dans des conditions dangereuses côté mexicain.",
     "BAMT", "border_asylum_metering"),
    ("immigration_bond_hearing_access_rights_engine.py",
     "Accès aux audiences de cautionnement en immigration & droits des détenus à une audience rapide sur leur libération sous caution avec examen individualisé de leur dangerosité", "Wave 1358",
     "Détenus immigration maintenus en rétention prolongée sans audience de cautionnement rapide ni examen individualisé de leur risque de fuite ou de danger pour la communauté.",
     "IBHA", "immigr_bond_hearing"),

    # Wave 1359 — Éducation & justice civile (inédits)
    ("dyslexia_early_screening_school_rights_engine.py",
     "Dépistage précoce de la dyslexie à l'école & droits des élèves à une identification systématique des troubles d'apprentissage dès les premières années pour une intervention efficace", "Wave 1359",
     "Élèves dyslexiques non identifiés en l'absence de dépistage systématique précoce accumulant des années de retard de lecture avant un diagnostic tardif et coûteux.",
     "DESS", "dyslexia_screening"),
    ("gifted_education_access_equity_rights_engine.py",
     "Équité d'accès aux programmes d'éducation pour surdoués & droits des élèves talentueux de milieux défavorisés à une identification et un accès non discriminatoires aux programmes avancés", "Wave 1359",
     "Élèves doués issus de minorités et de familles à faibles revenus sous-représentés dans les programmes pour surdoués en raison de critères d'identification biaisés et de barrières d'accès.",
     "GEAE", "gifted_education_equity"),
    ("felony_jury_service_exclusion_rights_engine.py",
     "Exclusion à vie du service de juré pour les anciens condamnés & droits des personnes ayant purgé leur peine à participer au devoir civique de juré après réhabilitation", "Wave 1359",
     "Personnes ayant purgé leur peine pour un crime exclues à vie du service de juré dans de nombreux États, perdant un droit civique fondamental même après réhabilitation complète.",
     "FJSE", "felony_jury_exclusion"),

    # Wave 1360 — Droits: numérique & protection (inédits)
    ("protective_order_firearm_surrender_rights_engine.py",
     "Remise des armes à feu lors d'ordonnances de protection & droits des victimes de violence à une application effective du désarmement des agresseurs sous ordonnance restrictive", "Wave 1360",
     "Victimes de violence domestique protégées par une ordonnance restrictive demeurant en danger car l'agresseur conserve ses armes faute de mécanisme de remise et de vérification effectif.",
     "POFS", "protective_order_firearm"),
    ("doxxing_personal_information_protection_rights_engine.py",
     "Protection contre le doxxing et la divulgation d'informations personnelles & droits des victimes à obtenir la suppression rapide de leurs données exposées malicieusement en ligne", "Wave 1360",
     "Personnes victimes de doxxing voyant leur adresse, téléphone et lieu de travail publiés en ligne pour les harceler sans mécanisme légal efficace de suppression rapide et de poursuite.",
     "DPIP", "doxxing_info_protect"),
    ("swatting_false_report_victim_rights_engine.py",
     "Victimes de swatting par faux signalements d'urgence & droits des personnes ciblées à une protection, des recours et une responsabilisation des auteurs de fausses alertes dangereuses", "Wave 1360",
     "Personnes victimes de swatting subissant des interventions policières armées déclenchées par de faux signalements malveillants, risquant blessures et traumatismes sans recours adéquat.",
     "SWFV", "swatting_false_report"),
]
