# Specs waves 1265-1272 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1265 — Réintégration & emploi (inédits)
    ("formerly_incarcerated_occupational_license_rights_engine.py",
     "Licences professionnelles pour personnes anciennement incarcérées & interdictions automatiques liées au casier sans lien avec la profession", "Wave 1265",
     "Ex-détenus se voyant refuser des licences professionnelles pour coiffure, plomberie ou soins sans évaluation individuelle de leur casier.",
     "FIOL", "formerly_incarc_license"),
    ("workers_comp_claim_denial_appeal_rights_engine.py",
     "Appel des refus de demandes d'indemnisation accidents du travail & droits des travailleurs à une révision équitable des décisions de l'assureur", "Wave 1265",
     "Travailleurs blessés dont les demandes d'indemnisation sont refusées par des assureurs sans processus d'appel accessible et transparent.",
     "WCDA", "workers_comp_deny_appeal"),
    ("ssdi_reconsideration_step_rights_engine.py",
     "Étape de réexamen des demandes SSDI refusées & droits des demandeurs à une nouvelle évaluation complète avant l'audience d'ALJ", "Wave 1265",
     "Demandeurs SSDI rejetés à l'étape initiale naviguant le processus de réexamen sans aide légale avec un taux d'approbation inférieur à 15%.",
     "SSRC", "ssdi_reconsider_step"),

    # Wave 1266 — Traitement des dépendances (inédits)
    ("buprenorphine_prescribing_barrier_rights_engine.py",
     "Obstacles à la prescription de buprénorphine pour le trouble d'usage aux opioïdes & droits des patients à un accès équitable aux soins", "Wave 1266",
     "Patients avec trouble d'usage aux opioïdes incapables d'accéder à la buprénorphine en raison de pénuries de prescripteurs certifiés DATA-2000.",
     "BPHB", "buprenorphine_prescr"),
    ("supervised_consumption_site_legal_rights_engine.py",
     "Sites de consommation supervisée pour réduction des risques & statut légal des programmes qui ont sauvé des milliers de vies", "Wave 1266",
     "Organisations de santé publique cherchant à ouvrir des sites de consommation supervisée confrontées à des poursuites fédérales malgré leur efficacité.",
     "SCSL", "supervised_consump_site"),
    ("opioid_treatment_prison_continuity_rights_engine.py",
     "Continuité du traitement aux opioïdes en prison & droits des détenus avec TUO à recevoir une TAMO en détention sans interruption forcée", "Wave 1266",
     "Détenus sous traitement de maintien aux opioïdes contraints d'arrêter leur médication à l'incarcération dans des prisons refusant la TAMO.",
     "OPTC", "opioid_treat_prison"),

    # Wave 1267 — Santé: soins primaires & assurance (inédits)
    ("vision_care_senior_medicaid_rights_engine.py",
     "Soins de vision pour seniors sous Medicaid & couverture insuffisante des lunettes et examens oculaires dans de nombreux États", "Wave 1267",
     "Seniors à faibles revenus sous Medicaid incapables d'accéder aux examens de vue et lunettes correctrices dans des États avec couverture minimale.",
     "VSMD", "vision_care_senior_md"),
    ("preventive_care_cost_sharing_aca_rights_engine.py",
     "Partage des coûts pour les soins préventifs sous l'ACA & droits des assurés à une prévention sans franchises ni copaiements", "Wave 1267",
     "Assurés se voyant facturer des copaiements pour des services préventifs supposément gratuits sous l'ACA par des assureurs confondant les codes de facturation.",
     "PCCS", "prev_care_cost_aca"),
    ("step_therapy_urgent_override_rights_engine.py",
     "Dérogation urgente à la thérapie par étapes & droits des patients à un accès immédiat aux traitements prescrits en cas d'urgence médicale", "Wave 1267",
     "Patients dans des situations médicales urgentes bloqués par des exigences de thérapie par étapes qui retardent les traitements critiques prescrits par leur médecin.",
     "STOU", "step_therapy_urgent"),

    # Wave 1268 — Éducation: besoins spéciaux (inédits)
    ("extended_school_year_iep_rights_engine.py",
     "Services scolaires d'été étendus ESY dans les PEI & droits des élèves handicapés à la continuité des services en été pour éviter la régression", "Wave 1268",
     "Élèves handicapés éligibles aux services ESY d'été se voyant refuser ces services par des districts essayant de réduire leurs coûts d'éducation spéciale.",
     "ESYI", "extended_school_yr"),
    ("early_intervention_eligibility_rights_engine.py",
     "Éligibilité aux services d'intervention précoce 0-3 ans & droits des nourrissons et tout-petits avec retards de développement à des services IDEA Part C", "Wave 1268",
     "Nourrissons avec retards développementaux refusés pour les services d'intervention précoce en raison de critères d'éligibilité trop restrictifs par État.",
     "EIEG", "early_interv_elig"),
    ("section_504_plan_implementation_gap_rights_engine.py",
     "Lacunes dans la mise en œuvre des plans 504 & droits des élèves handicapés à des accommodements réellement appliqués en classe", "Wave 1268",
     "Élèves avec des plans 504 approuvés dont les accommodements ne sont pas systématiquement mis en œuvre par les enseignants sans mécanisme de suivi.",
     "PGAP", "504_plan_impl_gap"),

    # Wave 1269 — Travail: équité & discrimination (inédits)
    ("salary_history_ban_employer_rights_engine.py",
     "Interdictions d'interroger sur l'historique salarial & droits des candidats à ne pas perpétuer les inégalités salariales historiques lors de l'embauche", "Wave 1269",
     "Candidats à l'emploi dont les employeurs interrogent encore sur le salaire actuel ou passé dans des États ayant adopté des lois interdisant cette pratique.",
     "SHBN", "salary_hist_ban"),
    ("family_status_hiring_discrimination_rights_engine.py",
     "Discrimination à l'embauche fondée sur le statut familial & droits des parents et aidants contre les préjugés liés aux responsabilités familiales", "Wave 1269",
     "Candidats parents de jeunes enfants ou aidants de proches éliminés du processus d'embauche en raison de suppositions sur leur disponibilité.",
     "CDHR", "family_status_hire"),
    ("formulary_exception_drug_access_rights_engine.py",
     "Exceptions au formulaire d'assurance pour les médicaments non couverts & droits des patients à l'accès médical nécessaire non standard", "Wave 1269",
     "Patients nécessitant des médicaments hors formulaire d'assurance confrontés à des processus d'exception opaques et chronophages qui retardent le traitement.",
     "FSDC", "formulary_exception"),

    # Wave 1270 — Finance: fraudes & prêts abusifs (inédits)
    ("home_equity_predatory_loan_rights_engine.py",
     "Prêts sur valeur nette immobilière prédateurs & droits des propriétaires contre les conditions abusives des HELOC et prêts secondaires", "Wave 1270",
     "Propriétaires à revenus modestes ciblés par des prêts sur valeur nette à taux excessifs et conditions cachées menaçant leur logement.",
     "HEPL", "home_equity_predatory"),
    ("senior_investment_fraud_protection_rights_engine.py",
     "Fraude à l'investissement ciblant les seniors & droits des victimes âgées à des recours contre les conseillers financiers véreux", "Wave 1270",
     "Seniors victimes de fraudes à l'investissement comme les Ponzi schemes ou produits d'assurance complexes vendus sans divulgation des risques.",
     "SIVF", "senior_invest_fraud"),
    ("predatory_lending_minority_community_rights_engine.py",
     "Prêts prédateurs dans les communautés de couleur & droits à une protection égale contre le ciblage discriminatoire par les prêteurs sous-prime", "Wave 1270",
     "Communautés racisées ciblées de façon disproportionnée par des prêteurs sous-prime proposant des conditions défavorables à des emprunteurs qualifiés pour mieux.",
     "PLMC", "predatory_lend_minority"),

    # Wave 1271 — Environnement & habitat (inédits)
    ("airport_noise_residential_rights_engine.py",
     "Nuisance sonore des aéroports pour les résidents & droits à l'insonorisation financée et à des restrictions de trajectoires de vol nocturnes", "Wave 1271",
     "Résidents vivant sous les couloirs de vol aéroportuaires souffrant de niveaux sonores dépassant les limites de santé publique sans compensation ni remède.",
     "ANRS", "airport_noise_resid"),
    ("natural_gas_appliance_safety_rights_engine.py",
     "Sécurité des appareils à gaz naturel dans les logements & droits des locataires à des détecteurs de fuite et à la réparation rapide", "Wave 1271",
     "Locataires vivant avec des appareils à gaz défectueux ou des conduites non entretenues sans obligation légale de détection des fuites dans leur État.",
     "NGAL", "gas_appliance_safety"),
    ("industrial_noise_workplace_hearing_rights_engine.py",
     "Protection auditive des travailleurs en milieux industriels bruyants & droits OSHA à une surveillance audiométrique et EPI adéquats", "Wave 1271",
     "Travailleurs dans des environnements industriels dépassant les limites OSHA de bruit ne recevant pas de protection auditive ni surveillance médicale adéquates.",
     "INOW", "industrial_noise_work"),

    # Wave 1272 — Droits divers: accès & protection (inédits)
    ("language_access_healthcare_rights_engine.py",
     "Accès linguistique aux soins de santé & droits des patients limités en anglais à des interprètes médicaux qualifiés sans frais", "Wave 1272",
     "Patients à maîtrise limitée de l'anglais recevant des soins médicaux sans interprète qualifié, risquant des erreurs diagnostiques et thérapeutiques graves.",
     "LAHC", "language_access_hlth"),
    ("religious_land_use_zoning_rights_engine.py",
     "Usage religieux des terres et droits de zonage RLUIPA & protection des congrégations contre les restrictions discriminatoires d'utilisation des sols", "Wave 1272",
     "Congrégations religieuses, notamment minoritaires, confrontées à des obstacles de zonage disproportionnés pour construire ou agrandir leurs lieux de culte.",
     "RLUZ", "religious_land_zone"),
    ("funeral_home_pricing_regulation_rights_engine.py",
     "Réglementation des prix des pompes funèbres & droits des familles endeuillées à une tarification transparente sous la règle FTC des funérailles", "Wave 1272",
     "Familles endeuillées payant des milliers de dollars de frais funéraires non divulgués à l'avance en violation des exigences de divulgation de prix FTC.",
     "FHPR", "funeral_home_pricing"),
]
