# Specs waves 881-888 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 881 — Isolement carcéral & santé mentale
    ("solitary_confinement_mental_health_rights_engine.py",
     "Isolement cellulaire & dégradation de la santé mentale", "Wave 881",
     "Détenus en isolement développant des psychoses et des traumatismes durables.",
     "SCMH", "solitary_mental"),
    ("supermax_isolation_rights_engine.py",
     "Prisons supermax & torture par l'isolement", "Wave 881",
     "Détenus en supermax soumis à un isolement total assimilable à la torture.",
     "SMAX", "supermax_isolation"),
    ("cell_extraction_restraint_chair_rights_engine.py",
     "Extractions de cellule & chaises de contention", "Wave 881",
     "Utilisation de chaises de contention lors d'extractions de cellules sans protocole médical.",
     "CERC", "cell_restraint"),

    # Wave 882 — Traitements forcés en détention
    ("forced_medication_prison_rights_engine.py",
     "Médication forcée en prison & consentement", "Wave 882",
     "Détenus sous médication forcée sans procédure de consentement ni surveillance médicale.",
     "FMPR", "forced_prison_med"),
    ("restraint_seclusion_psychiatric_rights_engine.py",
     "Contention & isolement en psychiatrie", "Wave 882",
     "Patients psychiatriques soumis à la contention physique comme punition ou facilité.",
     "RSPS", "restraint_psychiatric"),
    ("involuntary_hospitalization_abuse_rights_engine.py",
     "Hospitalisation sous contrainte & abus", "Wave 882",
     "Personnes hospitalisées sous contrainte abusivement pour museler des comportements normaux.",
     "IHAB", "involuntary_hosp"),

    # Wave 883 — Consentement & capacité médicale
    ("ect_consent_patient_rights_engine.py",
     "Électrochocs & consentement du patient", "Wave 883",
     "Thérapies par électrochocs administrées sans consentement éclairé ou contre la volonté.",
     "ECTP", "ect_consent"),
    ("guardian_medical_override_rights_engine.py",
     "Tuteur légal & décisions médicales imposées", "Wave 883",
     "Tuteurs imposant des traitements médicaux contre la volonté exprimée de la personne.",
     "GMOV", "guardian_override"),
    ("capacity_assessment_disability_rights_engine.py",
     "Évaluation de la capacité & personnes handicapées", "Wave 883",
     "Personnes handicapées jugées incapables sans évaluation individualisée rigoureuse.",
     "CADB", "capacity_disability"),

    # Wave 884 — Autonomie & tutelle
    ("supported_decision_making_rights_engine.py",
     "Prise de décision accompagnée & alternatives à la tutelle", "Wave 884",
     "Personnes sous tutelle privées d'alternatives de décision accompagnée moins restrictives.",
     "SDMK", "supported_decisions"),
    ("outpatient_commitment_abuse_rights_engine.py",
     "Soins psychiatriques ambulatoires forcés & abus", "Wave 884",
     "Ordonnances de soins ambulatoires imposant des traitements à des personnes en liberté.",
     "OCAM", "outpatient_commit"),
    ("wage_assignment_unfair_rights_engine.py",
     "Cession de salaire & coercition patronale", "Wave 884",
     "Employeurs contraignant des salariés à céder une partie de leur salaire à des tiers.",
     "WAGU", "wage_assignment"),

    # Wave 885 — Dettes & saisies
    ("repo_vehicle_debt_rights_engine.py",
     "Saisie de véhicule & dette & perte d'emploi", "Wave 885",
     "Saisies de véhicules pour petites dettes créant une spirale chômage-pauvreté.",
     "RVDI", "vehicle_repo"),
    ("title_loan_vehicle_trap_rights_engine.py",
     "Prêts sur titres de véhicules & piège financier", "Wave 885",
     "Prêts à taux exorbitants sur titres de véhicules dépouillant les emprunteurs précaires.",
     "TLVH", "title_loan"),
    ("eviction_credit_report_rights_engine.py",
     "Expulsion & inscription au crédit à vie", "Wave 885",
     "Expulsions locatives apparaissant sur les dossiers de crédit bloquant le relogement.",
     "ECRT", "eviction_credit"),

    # Wave 886 — Listes noires & casier judiciaire
    ("tenant_blacklist_rights_engine.py",
     "Listes noires de locataires & accès au logement", "Wave 886",
     "Bases de données privées inscrivant des locataires sur des listes bloquant tout relogement.",
     "TEBK", "tenant_blacklist"),
    ("criminal_record_employment_housing_rights_engine.py",
     "Casier judiciaire & double peine professionnelle et résidentielle", "Wave 886",
     "Casiers judiciaires perpétuant l'exclusion du marché du travail et du logement.",
     "CPPD", "criminal_double_bar"),
    ("ban_the_box_gap_rights_engine.py",
     "Ban the Box & lacunes de mise en œuvre", "Wave 886",
     "Politiques Ban the Box mal appliquées continuant à discriminer les ex-détenus.",
     "BXGP", "ban_box_gap"),

    # Wave 887 — Amendes, frais & suspension de permis
    ("fines_fees_court_debt_cycle_rights_engine.py",
     "Amendes judiciaires & spirale d'endettement cumulatif", "Wave 887",
     "Amendes et frais de justice s'accumulant avec intérêts enfermant les pauvres dans la dette.",
     "FFCD", "fines_fees_debt"),
    ("fines_suspension_license_poverty_rights_engine.py",
     "Suspension de permis pour amendes impayées & pauvreté", "Wave 887",
     "Permis suspendus pour amendes impayées, supprimant le moyen de transport vers l'emploi.",
     "FSLP", "fines_license_poor"),
    ("restitution_supervision_fee_rights_engine.py",
     "Frais de supervision post-peine & réinsertion bloquée", "Wave 887",
     "Frais de probation et de surveillance s'accumulant et rejetant les sortants de prison.",
     "RSTC", "restitution_fee"),

    # Wave 888 — Soins en milieu correctionnel
    ("shelter_carceral_health_rights_engine.py",
     "Santé en prison & soins refusés", "Wave 888",
     "Soins médicaux chroniquement refusés aux détenus en violation des standards internationaux.",
     "SHCM", "prison_health"),
    ("prenatal_care_incarcerated_rights_engine.py",
     "Soins prénataux & femmes incarcérées", "Wave 888",
     "Détenues enceintes sans suivi prénatal adéquat ni accès à des soins obstétricaux.",
     "PHCP", "prenatal_prison"),
    ("mental_health_crisis_jail_diversion_rights_engine.py",
     "Crise psychiatrique & détention au lieu du soin", "Wave 888",
     "Personnes en crise mentale emprisonnées faute de structures de soins alternatives.",
     "MHJD", "mh_jail_diversion"),
]
