# Specs waves 1321-1328 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Corrections: CPRD pris par ceo_pay_ratio → CLRD; MANA pris par maternal_anaemia → MVNA
SPECS = [
    # Wave 1321 — Famille: droit familial avancé (inédits)
    ("child_custody_relocation_dispute_rights_engine.py",
     "Litiges de déménagement dans les gardes partagées & droits du parent non gardien à s'opposer à une relocalisation substantielle affectant l'accès aux enfants", "Wave 1321",
     "Parents non gardiens apprenant que l'autre parent souhaite déménager loin avec les enfants sans procédure judiciaire d'approbation préalable.",
     "CLRD", "custody_reloc_dispute"),
    ("parental_alienation_court_documentation_rights_engine.py",
     "Documentation de l'aliénation parentale dans les procédures judiciaires & droits du parent affecté à faire admettre les preuves et obtenir des interventions correctrices", "Wave 1321",
     "Parents victimes d'aliénation parentale systématique cherchant à documenter les comportements et obtenir des interventions judiciaires sans être écartés comme partie biaisée.",
     "PACD", "parental_alien_doc"),
    ("joint_custody_educational_decision_rights_engine.py",
     "Prises de décisions éducatives dans la garde juridique conjointe & droits des deux parents à participer aux choix scolaires, thérapies et activités parascolaires", "Wave 1321",
     "Parents en garde juridique conjointe dont l'un prend des décisions éducatives majeures (changement d'école, thérapies) sans consulter l'autre comme l'exige l'accord.",
     "JCED", "joint_custody_educ"),

    # Wave 1322 — Finance: prêts étudiants IDR (inédits)
    ("income_driven_repayment_recertification_rights_engine.py",
     "Recertification annuelle des plans IDR de prêts étudiants & droits des emprunteurs à maintenir leur éligibilité sans perdre leur progression vers la remise de dette", "Wave 1322",
     "Emprunteurs de prêts étudiants fédéraux perdant leur plan IDR et leur progression vers la remise PSLF suite à des erreurs de recertification annuelle.",
     "IDRR", "idr_recertification"),
    ("parent_plus_loan_repayment_options_rights_engine.py",
     "Options de remboursement des prêts PLUS parentaux & droits des parents emprunteurs à accéder aux plans IDR et à la remise de service public via la double consolidation", "Wave 1322",
     "Parents ayant contracté des prêts PLUS fédéraux pour financer les études de leurs enfants confrontés à des options de remboursement très limitées comparées aux prêts directs.",
     "PPLR", "parent_plus_repay"),
    ("private_student_loan_cosigner_release_rights_engine.py",
     "Libération du cosignataire des prêts étudiants privés & droits des cosignataires à être libérés après un historique de paiement satisfaisant sans obstacles cachés", "Wave 1322",
     "Cosignataires de prêts étudiants privés incapables d'être libérés malgré des années de paiements ponctuels, leur responsabilité financière empêchant leurs propres emprunts.",
     "SLCR", "student_loan_cosign"),

    # Wave 1323 — Santé: Medicare avancé (inédits)
    ("medicare_part_d_donut_hole_rights_engine.py",
     "Lacune de couverture Medicare Partie D & droits des bénéficiaires à comprendre et naviguer la période de franchise des médicaments sans arrêter leur traitement", "Wave 1323",
     "Bénéficiaires Medicare entrant dans la lacune de couverture Part D se voyant facturer des montants bien supérieurs aux coûts normaux pour leurs médicaments essentiels.",
     "MPDH", "medicare_d_donut"),
    ("medicare_coverage_denial_appeal_rights_engine.py",
     "Appels des refus de couverture Medicare & droits des bénéficiaires à des niveaux d'appel structurés avec délais réglementés pour les services médicaux nécessaires", "Wave 1323",
     "Bénéficiaires Medicare dont les services ou équipements médicaux sont refusés ne connaissant pas les niveaux d'appel ni les délais légaux de réponse des administrateurs.",
     "MCDA", "medicare_coverage_appeal"),
    ("medicare_advantage_network_adequacy_rights_engine.py",
     "Adéquation du réseau Medicare Advantage & droits des assurés à des spécialistes accessibles sans frais hors réseau excessifs ni délais d'attente déraisonnables", "Wave 1323",
     "Assurés Medicare Advantage confrontés à des réseaux de prestataires insuffisants dans leur zone, contraints de payer hors réseau pour accéder aux spécialistes nécessaires.",
     "MVNA", "medicare_adv_network"),

    # Wave 1324 — Transport: droits véhicules (inédits)
    ("vehicle_repossession_notice_rights_engine.py",
     "Notification et droit de rachat avant saisie d'un véhicule & droits des emprunteurs à un préavis minimum et à une période de grâce pour éviter la reprise", "Wave 1324",
     "Emprunteurs dont le véhicule est saisi sans notification préalable suffisante ni possibilité de remédier au défaut avant que leur outil de travail principal soit repris.",
     "VRNR", "vehicle_repo_notice"),
    ("parking_enforcement_due_process_rights_engine.py",
     "Procédure de contestation des amendes de stationnement & droits des conducteurs à une audience équitable avant escalade vers la mise en fourrière ou suspension du permis", "Wave 1324",
     "Conducteurs contestant des amendes de stationnement incorrectes confrontés à des systèmes d'appel municipaux inaccessibles avec délais irréalistes et défenses limitées.",
     "PKDP", "parking_due_process"),
    ("auto_insurance_credit_score_pricing_rights_engine.py",
     "Tarification de l'assurance automobile basée sur le score de crédit & droits des conducteurs à ne pas être pénalisés pour leur situation financière plutôt que leur conduite", "Wave 1324",
     "Conducteurs à faibles revenus ou historique de crédit limité payant des primes d'assurance automobile significativement plus élevées basées sur le crédit plutôt que les accidents.",
     "AICP", "auto_insur_credit"),

    # Wave 1325 — Santé: neurodéveloppement (inédits)
    ("autism_aba_therapy_insurance_coverage_rights_engine.py",
     "Couverture d'assurance pour la thérapie ABA & droits des enfants autistes à des thérapies comportementales intensives sans limites arbitraires de séances ou d'âge", "Wave 1325",
     "Enfants autistes dont la thérapie ABA est limitée à un nombre insuffisant de séances par semaine par l'assurance, entravant leur développement pendant les années critiques.",
     "AABA", "autism_aba_cover"),
    ("adhd_stimulant_medication_shortage_rights_engine.py",
     "Pénuries de médicaments stimulants pour le TDAH & droits des patients à des options alternatives et à la continuité des soins pendant les ruptures de stock prolongées", "Wave 1325",
     "Personnes atteintes de TDAH incapables de trouver leurs médicaments stimulants prescrits dans les pharmacies en raison de pénuries prolongées sans orientation vers alternatives.",
     "ADMS", "adhd_med_shortage"),
    ("learning_disability_college_accommodation_rights_engine.py",
     "Accommodements pour troubles d'apprentissage dans l'enseignement supérieur & droits des étudiants dyslexiques et dyscalculiques à des ajustements prouvés sans documentation excessive", "Wave 1325",
     "Étudiants universitaires avec diagnostics de dyslexie ou TDAH confrontés à des procédures d'accommodements longues ou des refus malgré des diagnostics documentés.",
     "LDCA", "learning_disab_college"),

    # Wave 1326 — Travail: surveillance & vie privée (inédits)
    ("employee_electronic_monitoring_notification_rights_engine.py",
     "Notification de la surveillance électronique des employés & droits des travailleurs à être informés des types de monitoring et données collectées par l'employeur", "Wave 1326",
     "Employés dont les communications, déplacements et productivité sont surveillés électroniquement sans notification préalable ni divulgation de l'étendue du monitoring.",
     "EEMN", "employee_elec_monitor"),
    ("remote_work_performance_tracking_rights_engine.py",
     "Suivi de performance des télétravailleurs & droits des employés à distance à des méthodes de mesure de productivité raisonnables sans surveillance intrusive des appareils personnels", "Wave 1326",
     "Télétravailleurs soumis à des logiciels de surveillance prenant des captures d'écran fréquentes, enregistrant les frappes clavier et accédant à leur caméra sans consentement explicite.",
     "RWPT", "remote_perf_track"),
    ("genetic_information_employment_protection_rights_engine.py",
     "Protection GINA étendue contre l'utilisation des informations génétiques dans l'emploi & droits des travailleurs à ne pas subir de discrimination basée sur les résultats de tests", "Wave 1326",
     "Employés dont les résultats de tests génétiques personnels sont accédés ou pris en compte dans des décisions d'emploi sans protection adéquate au-delà des lacunes GINA actuelles.",
     "GIER", "genetic_employ_prot"),

    # Wave 1327 — Logement: assurance & risque climatique (inédits)
    ("homeowner_insurance_nonrenewal_climate_rights_engine.py",
     "Non-renouvellement d'assurance habitation pour risque climatique & droits des propriétaires à une notification préalable et à des alternatives de couverture de dernier recours", "Wave 1327",
     "Propriétaires dans des zones à risque d'incendie, d'inondation ou d'ouragan recevant des avis de non-renouvellement sans accès à des assurances alternatives abordables.",
     "HINR", "homeinsur_nonrenew"),
    ("flood_insurance_claim_dispute_rights_engine.py",
     "Litiges de réclamations d'assurance inondation NFIP & droits des assurés à un processus de contestation équitable pour les indemnisations insuffisantes après sinistre", "Wave 1327",
     "Propriétaires inondés recevant des offres d'indemnisation du NFIP largement insuffisantes pour couvrir les réparations sans processus d'appel accessible ni expertise indépendante.",
     "FICD", "flood_insur_dispute"),
    ("asbestos_rental_property_disclosure_rights_engine.py",
     "Divulgation de l'amiante dans les logements locatifs & droits des locataires à être informés de la présence d'amiante et à des mesures de protection ou réparation adéquates", "Wave 1327",
     "Locataires vivant dans des logements anciens contenant de l'amiante sans divulgation du propriétaire ni plan de gestion ou de décontamination sécurisée.",
     "ASTD", "asbestos_rental_dis"),

    # Wave 1328 — Éducation: transition & licences (inédits)
    ("iep_transition_services_age_21_rights_engine.py",
     "Services de transition IEP jusqu'à l'âge de 21 ans & droits des élèves handicapés à une planification concrète de l'emploi et de la vie indépendante dès 16 ans", "Wave 1328",
     "Élèves handicapés approchant de l'âge de 21 ans sans plan de transition IEP substantiel vers l'emploi, l'enseignement supérieur ou la vie communautaire indépendante.",
     "IPTS", "iep_transition_21"),
    ("special_education_extended_eligibility_rights_engine.py",
     "Éligibilité étendue aux services d'éducation spécialisée après 18 ans & droits des jeunes adultes à continuer leurs services IDEA jusqu'à l'obtention du diplôme ou 22 ans", "Wave 1328",
     "Jeunes adultes handicapés dont les districts scolaires refusent les services d'éducation spécialisée au-delà de 18 ans avant l'obtention du diplôme réel.",
     "SEEE", "sped_extended_eligib"),
    ("occupational_license_military_spouse_rights_engine.py",
     "Portabilité des licences professionnelles pour les conjoints militaires & droits à une reconnaissance rapide ou temporaire lors des mutations sans refaire l'intégralité du processus", "Wave 1328",
     "Conjoints de militaires déménageant vers un nouvel État perdant leur licence professionnelle active et devant reprendre l'intégralité du processus de certification.",
     "OLMS", "occ_lic_mil_spouse"),
]
