# Specs waves 1193-1200 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1193 — Finance: recouvrement de créances (inédits)
    ("unemployment_overpayment_clawback_rights_engine.py",
     "Récupération abusive des trop-perçus d'allocations chômage & droits des bénéficiaires contre les saisies automatisées", "Wave 1193",
     "Chômeurs réclamant des allocations obtenues légitimement contraints de rembourser des trop-perçus causés par des erreurs gouvernementales.",
     "UOPR", "unemploy_overpay"),
    ("debt_collector_social_media_rights_engine.py",
     "Contact des collecteurs de dettes via réseaux sociaux & droits des débiteurs contre les pratiques numériques abusives FDCPA", "Wave 1193",
     "Débiteurs contactés par des collecteurs via Facebook, LinkedIn ou DMs Instagram en violation des protections FDCPA modernes.",
     "DCSM", "debt_collect_social"),
    ("medical_debt_ban_credit_report_rights_engine.py",
     "Interdiction des dettes médicales dans les rapports de crédit & droits des patients à ne pas voir leur score pénalisé", "Wave 1193",
     "Patients dont les dettes médicales impactent leur score de crédit et leur accès aux logements, emplois et prêts malgré les réformes.",
     "MBCR", "med_debt_ban_credit"),

    # Wave 1194 — Transport: permis & mobilité (inédits)
    ("driver_license_suspension_debt_rights_engine.py",
     "Suspension du permis de conduire pour dettes non liées à la conduite & impact disproportionné sur les travailleurs pauvres", "Wave 1194",
     "Travailleurs pauvres perdant leur permis pour des amendes impayées non liées à la conduite, perdant ainsi leur emploi.",
     "DLSD", "driver_lic_debt"),
    ("transit_wheelchair_boarding_denial_rights_engine.py",
     "Refus d'embarquement des fauteuils roulants dans les transports publics & droits ADA des passagers handicapés à l'accessibilité", "Wave 1194",
     "Utilisateurs de fauteuils roulants refusés ou ignorés aux arrêts de bus et de métro par des opérateurs ne déployant pas les rampes.",
     "TWTB", "transit_wheelchair_board"),
    ("public_transit_affordable_fare_rights_engine.py",
     "Tarification des transports publics abordables & impact des augmentations tarifaires sur l'accès des travailleurs à faibles revenus", "Wave 1194",
     "Travailleurs à faibles revenus contraints d'abandonner les transports en commun suite à des augmentations tarifaires sans programme d'aide.",
     "PTWA", "transit_afford_fare"),

    # Wave 1195 — Logement: politiques HUD & logement public (inédits)
    ("public_housing_one_strike_policy_rights_engine.py",
     "Politique one-strike des HLM & expulsion pour activité criminelle d'un membre du ménage à l'insu du locataire principal", "Wave 1195",
     "Locataires de logements publics expulsés pour les crimes commis par un membre de la famille sans qu'ils soient impliqués.",
     "PHST", "public_hous_one_strike"),
    ("section8_voucher_denial_criminal_rights_engine.py",
     "Refus des vouchers Section 8 pour casier judiciaire & barrières à l'aide au logement pour personnes en réinsertion", "Wave 1195",
     "Personnes en réinsertion avec casier judiciaire ancienrejetées des listes d'attente Section 8 sans évaluation individuelle.",
     "SCVD", "section8_criminal"),
    ("hud_equal_opportunity_complaint_rights_engine.py",
     "Plaintes HUD pour violations d'équité d'opportunité & délais excessifs dans le traitement des griefs de discrimination", "Wave 1195",
     "Victimes de discrimination au logement attendant des années le traitement de leurs plaintes HUD sans résolution effective.",
     "HEQR", "hud_equal_opport"),

    # Wave 1196 — Identité & droits civiques (inédits)
    ("nonbinary_id_state_barrier_rights_engine.py",
     "Obstacles étatiques à l'identification non binaire & droits des personnes non binaires à une documentation légale conforme", "Wave 1196",
     "Personnes non binaires vivant dans des États refusant les marqueurs de genre X sur les permis de conduire et documents officiels.",
     "NBID", "nonbinary_id_barrier"),
    ("cosmetology_license_hour_barrier_rights_engine.py",
     "Barrières des heures requises pour licence esthétique & exigences disproportionnées comparées aux formations médicales", "Wave 1196",
     "Candidats aux licences de cosmétologie et d'esthétique contraints à plus de 1500 heures de formation pour des services basiques.",
     "COSM", "cosmetol_hour_barr"),
    ("name_change_court_cost_barrier_rights_engine.py",
     "Coût des procédures judiciaires de changement de nom & barrières financières pour les personnes à faibles revenus", "Wave 1196",
     "Personnes souhaitant changer légalement de nom incapables de payer les frais judiciaires, obstacles à leur identité légale.",
     "NCBL", "name_change_cost"),

    # Wave 1197 — Emploi: licences professionnelles & conditions (inédits)
    ("occupational_license_cost_entry_rights_engine.py",
     "Coûts d'entrée prohibitifs des licences professionnelles & barrières financières aux carrières réglementées", "Wave 1197",
     "Candidats à des professions réglementées incapables de payer frais d'examen, formation et licence d'entrée de plusieurs milliers.",
     "OLCB", "occup_licens_cost"),
    ("professional_license_interstate_rights_engine.py",
     "Reconnaissance des licences professionnelles entre États & obligations de re-certification coûteuses lors de déménagements", "Wave 1197",
     "Infirmières, enseignants et thérapeutes déménageant entre États contraints de recommencer des processus de licence longs et coûteux.",
     "PLIR", "prof_licens_interst"),
    ("cosmetology_school_debt_trap_rights_engine.py",
     "Endettement des étudiants des écoles d'esthétique & promesses salariales trompeuses ne couvrant pas le coût de formation", "Wave 1197",
     "Diplômés d'écoles de cosmétologie endettés pour des formations dont le retour salarial ne permet pas le remboursement prévu.",
     "CSMH", "cosmet_school_debt"),

    # Wave 1198 — Environnement: sols & eau industrielle (inédits)
    ("pesticide_farm_worker_exposure_rights_engine.py",
     "Exposition aux pesticides des travailleurs agricoles & protections EPA insuffisantes pour les familles vivant près des cultures", "Wave 1198",
     "Familles d'ouvriers agricoles exposées à des dérives de pesticides près de leurs maisons sans notification préalable d'épandage.",
     "PFSE", "pestic_farm_worker"),
    ("agricultural_runoff_downstream_rights_engine.py",
     "Pollution agricole affectant les communautés en aval & droits des riverains à l'eau potable sans contamination nitratée", "Wave 1198",
     "Résidents ruraux dont les puits et cours d'eau sont contaminés par les nitrates d'élevage intensif sans recours légal effectif.",
     "AGRT", "agric_runoff_downstr"),
    ("school_bus_exhaust_rights_engine.py",
     "Pollution des bus scolaires diesel & exposition des enfants aux émissions toxiques dans les quartiers défavorisés", "Wave 1198",
     "Enfants dans des districts scolaires pauvres exposés aux émissions diesel de flottes de bus vétustes non électrifiées.",
     "SCBA", "school_bus_exhaust"),

    # Wave 1199 — Santé: accès pédiatrique & chronique (inédits)
    ("child_vision_screening_access_rights_engine.py",
     "Accès au dépistage visuel des enfants & diagnostics manqués dans les écoles sans programme de dépistage structuré", "Wave 1199",
     "Enfants avec déficiences visuelles non diagnostiquées en raison de l'absence de programmes de dépistage systématiques dans leur école.",
     "CVSD", "child_vision_screen"),
    ("ssdi_overpayment_clawback_rights_engine.py",
     "Récupération des trop-perçus d'invalidité SSDI & saisies automatiques ruinant les bénéficiaires pour des erreurs SSA", "Wave 1199",
     "Bénéficiaires SSDI contraints de rembourser des trop-perçus causés par des erreurs SSA via des saisies sur leurs maigres prestations.",
     "SSIA", "ssdi_overpay_claw"),
    ("therapy_visit_cap_rehab_rights_engine.py",
     "Plafonds de visites pour thérapies de rééducation & droits des patients à une couverture suffisante pour la récupération complète", "Wave 1199",
     "Patients post-opératoires ou post-AVC dont les séances de kinésithérapie nécessaires sont plafonnées arbitrairement par l'assurance.",
     "HWRR", "therapy_visit_cap"),

    # Wave 1200 — Droits divers: accès à la justice & identité (inédits)
    ("fibromyalgia_disability_recognition_rights_engine.py",
     "Reconnaissance de la fibromyalgie comme invalidité & refus SSDI pour maladie difficile à objectiver médicalement", "Wave 1200",
     "Patients atteints de fibromyalgie sévère refusés pour l'invalidité SSDI car la condition n'est pas mesurable par tests objectifs.",
     "FIBR", "fibromyalg_disab"),
    ("indigent_burial_access_rights_engine.py",
     "Accès aux services funéraires pour personnes indigentes & droits des familles à la dignité dans la mort malgré la pauvreté", "Wave 1200",
     "Familles sans ressources incapables de payer les frais funéraires voyant leurs proches enterrés dans des fosses communes sans cérémonie.",
     "IBER", "indigent_burial"),
    ("notary_service_access_rights_engine.py",
     "Accès aux services notariaux pour personnes à mobilité réduite & droits des seniors et handicapés à la notarisation à domicile", "Wave 1200",
     "Seniors confinés à domicile incapables d'accéder à des notaires pour signer des documents légaux essentiels comme les testaments.",
     "NOTR", "notary_access"),
]
