# Specs waves 1281-1288 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1281 — Bénéfices sociaux & nutrition (inédits)
    ("snap_application_barriers_rights_engine.py",
     "Obstacles aux demandes SNAP & droits des ménages éligibles à un accès simplifié sans barrières de documentation excessives", "Wave 1281",
     "Ménages éligibles aux bons alimentaires SNAP incapables de compléter leur demande en raison d'exigences de preuves documentaires disproportionnées.",
     "SNPB", "snap_applic_barrier"),
    ("tanf_time_limit_hardship_rights_engine.py",
     "Limites temporelles TANF & droits des familles en difficulté durable à des extensions de hardship au-delà des 60 mois fédéraux", "Wave 1281",
     "Familles ayant atteint leurs 60 mois fédéraux de TANF sans alternative d'emploi viable ni extension pour circonstances exceptionnelles approuvée.",
     "TNFT", "tanf_time_limit"),
    ("chip_children_health_coverage_rights_engine.py",
     "Couverture CHIP pour enfants de familles à revenus modestes & droits à une inscription continue sans lacunes de couverture lors des renouvellements", "Wave 1281",
     "Enfants perdant leur couverture CHIP lors des renouvellements annuels en raison de délais ou erreurs de documentation malgré une éligibilité maintenue.",
     "CHIP", "chip_health_cover"),

    # Wave 1282 — Énergie & services publics (inédits)
    ("net_metering_solar_rights_engine.py",
     "Net metering pour les panneaux solaires résidentiels & droits des producteurs solaires à une compensation équitable du surplus d'énergie injectée", "Wave 1282",
     "Propriétaires avec panneaux solaires se voyant imposer des réductions unilatérales du taux de compensation net metering par les services publics.",
     "NTSM", "net_metering_solar"),
    ("liheap_energy_assistance_rights_engine.py",
     "Aide LIHEAP pour les factures d'énergie des ménages à faibles revenus & droits d'accès aux fonds d'urgence avant la coupure de service", "Wave 1282",
     "Ménages à faibles revenus face à des coupures d'énergie incapables d'accéder aux fonds LIHEAP avant expiration des délais d'urgence.",
     "LIHE", "liheap_energy"),
    ("affordable_connectivity_broadband_rights_engine.py",
     "Programme de connectivité abordable pour internet & droits des ménages à faibles revenus à un accès internet haut débit sans discrimination de zone", "Wave 1282",
     "Ménages éligibles au programme ACP d'internet abordable dans des zones sans fournisseur participant ou avec des vitesses insuffisantes malgré la subvention.",
     "ABCP", "affordable_connect"),

    # Wave 1283 — Protection enfants & familles (inédits)
    ("foster_care_sibling_placement_rights_engine.py",
     "Placement des frères et sœurs ensemble en famille d'accueil & droits légaux à maintenir les liens fraternels lors des placements de protection", "Wave 1283",
     "Fratries séparées lors de placements en famille d'accueil faute de foyers disponibles pour les groupes de frères et sœurs malgré les exigences légales.",
     "FSFC", "foster_sibling_place"),
    ("relative_caregiver_licensing_rights_engine.py",
     "Exigences de licence pour les soignants de parenté & droits des grands-parents et proches à être approuvés sans standards de maisons d'accueil non pertinents", "Wave 1283",
     "Grands-parents voulant accueillir leurs petits-enfants en protection confrontés à des exigences de licence de famille d'accueil inadaptées à leur situation.",
     "RCGR", "relative_caregiv_lic"),
    ("child_summer_meal_program_rights_engine.py",
     "Programme de repas estivaux pour enfants & droits des enfants des quartiers défavorisés à accéder aux sites du programme USDA d'été", "Wave 1283",
     "Enfants dans des zones rurales ou urbaines défavorisées sans accès à des sites de repas estivaux USDA pendant les vacances scolaires malgré leur éligibilité.",
     "CSMA", "child_summer_meal"),

    # Wave 1284 — Santé: gestion maladies chroniques (inédits)
    ("hypertension_prevention_coverage_rights_engine.py",
     "Couverture préventive de l'hypertension & droits des patients à un dépistage, une surveillance et un traitement précoce sans barrières financières", "Wave 1284",
     "Personnes à risque d'hypertension incapables d'accéder à un monitoring régulier et des médicaments préventifs en raison de copaiements ou restrictions d'assurance.",
     "HPTC", "hypertension_prev_cov"),
    ("chronic_kidney_disease_early_detection_rights_engine.py",
     "Dépistage précoce de la maladie rénale chronique & droits des patients diabétiques et hypertendus à des tests annuels remboursés de fonction rénale", "Wave 1284",
     "Patients diabétiques et hypertendus à haut risque de MRC se voyant refuser ou facturer les tests annuels de créatinine et microalbuminurie nécessaires.",
     "CKDE", "ckd_early_detect"),
    ("asthma_action_plan_school_rights_engine.py",
     "Plans d'action contre l'asthme à l'école & droits des élèves asthmatiques à avoir un plan médicamentaire et un accès immédiat aux inhalateurs", "Wave 1284",
     "Élèves asthmatiques dans des écoles sans politiques claires de gestion d'asthme confrontés à des retards dans l'accès à leur inhalateur lors des crises.",
     "ASPS", "asthma_school_plan"),

    # Wave 1285 — Discrimination: contextes spéciaux (inédits)
    ("disability_accommodation_remote_work_rights_engine.py",
     "Accommodements de handicap pour le télétravail & droits des travailleurs handicapés à des ajustements raisonnables pour travailler à domicile", "Wave 1285",
     "Travailleurs handicapés se voyant refuser le télétravail comme accommodement raisonnable malgré son efficacité prouvée pour leur condition médicale.",
     "DRWA", "disab_remote_accomm"),
    ("chronic_illness_absenteeism_discipline_rights_engine.py",
     "Discipline liée aux absences pour maladie chronique & droits des employés à des politiques de présence qui tiennent compte des conditions médicales documentées", "Wave 1285",
     "Employés avec maladies chroniques documentées recevant des avertissements ou licenciements pour des absences médicalement nécessaires sans accommodement ADA.",
     "CIAD", "chronic_ill_absence"),
    ("national_origin_accent_customer_service_rights_engine.py",
     "Discrimination d'accent dans le service client & droits des travailleurs à ne pas être refusés de postes clients en raison de leur accent étranger", "Wave 1285",
     "Travailleurs immigrants qualifiés exclus des postes en contact avec la clientèle en raison de leur accent étranger malgré une communication intelligible.",
     "NAOC", "national_accent_cs"),

    # Wave 1286 — Justice & accès (inédits)
    ("juvenile_record_expungement_rights_engine.py",
     "Effacement des casiers judiciaires juvéniles & droits des jeunes adultes à une ardoise propre distincte de la procédure d'annulation des condamnations", "Wave 1286",
     "Jeunes adultes portant des casiers pour des délits juvéniles qui entravent leur accès à l'éducation, l'emploi et le logement malgré l'éligibilité à l'effacement.",
     "EXJV", "juvenile_record_expunge"),
    ("civil_legal_aid_rural_access_rights_engine.py",
     "Accès à l'aide juridique civile en zones rurales & droits des résidents éloignés à une représentation légale pour les affaires de logement et famille", "Wave 1286",
     "Résidents ruraux faisant face à des expulsions, divorces ou garde d'enfant sans accès à un bureau d'aide juridique à moins de 2 heures de route.",
     "CLAR", "civil_aid_rural"),
    ("mandatory_employment_arbitration_rights_engine.py",
     "Arbitrage obligatoire dans les contrats d'emploi & droits des travailleurs à rejeter des clauses qui privent de l'accès aux tribunaux", "Wave 1286",
     "Travailleurs contraints de signer des clauses d'arbitrage obligatoire comme condition d'emploi les empêchant de former des recours collectifs contre l'employeur.",
     "EMAC", "mandatory_employ_arbit"),

    # Wave 1287 — Santé mentale: crises & accès (inédits)
    ("mental_health_crisis_988_rights_engine.py",
     "Ligne de crise 988 pour la santé mentale & droits des appelants à une réponse de santé mentale sans intervention policière automatique", "Wave 1287",
     "Personnes en crise de santé mentale appelant le 988 dans des comtés sans équipes mobiles de crise, entraînant une réponse policière non appropriée.",
     "MHCL", "mental_health_988"),
    ("telehealth_mental_health_parity_rights_engine.py",
     "Parité de remboursement pour la télésanté mentale & droits des patients à un remboursement équitable des séances de thérapie virtuelle", "Wave 1287",
     "Patients en thérapie virtuelle se voyant rembourser moins pour les séances de télésanté mentale que pour les séances en présentiel malgré la loi de parité.",
     "TMHW", "telehlth_mental_par"),
    ("inpatient_psychiatric_discharge_rights_engine.py",
     "Droits de sortie des patients psychiatriques hospitalisés & protection contre les sorties prématurées motivées par les pressions de débit des assureurs", "Wave 1287",
     "Patients hospitalisés en psychiatrie sortis prématurément sous pression des assureurs avant stabilisation, augmentant les risques de rechute et réhospitalisation.",
     "IPPD", "inpatient_psych_disch"),

    # Wave 1288 — Droits émergents: travail & numérique (inédits)
    ("disability_remote_work_accommodation_appeal_rights_engine.py",
     "Appel des refus d'accommodements de télétravail pour handicap & droits des travailleurs à un processus de reconsidération avec documentation médicale", "Wave 1288",
     "Travailleurs handicapés dont les demandes d'accommodements de télétravail ont été refusées sans processus d'appel interne ou médiation accessible.",
     "DARW", "disab_remote_appeal"),
    ("on_call_pay_schedule_rights_engine.py",
     "Rémunération des heures d'astreinte et des plannings imprévisibles & droits des travailleurs au paiement minimal pour les heures réservées non utilisées", "Wave 1288",
     "Travailleurs en astreinte sans rémunération garantie pour les heures réservées, incapables de planifier leur temps personnel ou de prendre un second emploi.",
     "OCPR", "on_call_pay_sched"),
    ("smart_city_surveillance_rights_engine.py",
     "Surveillance par les villes intelligentes & droits des citoyens à limiter la collecte de données biométriques et comportementales dans l'espace public", "Wave 1288",
     "Citoyens vivant dans des villes déployant des réseaux de caméras intelligentes avec reconnaissance faciale sans politique de gouvernance de données publique.",
     "SCSV", "smart_city_surveill"),
]
