# Specs waves 1009-1016 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# Remplacements : felon_voting→probation_voting ; cancer_alley→refinery_fence_line ; incarcerated_parent→prison_nursery
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1009 — Liberté religieuse & pratiques spécifiques
    ("jewish_cemetery_protection_rights_engine.py",
     "Protection des cimetières juifs contre les promoteurs immobiliers", "Wave 1009",
     "Cimetières juifs historiques détruits ou menacés par des projets immobiliers sans protection légale adéquate.",
     "JCPR", "jewish_cemetery"),
    ("muslim_student_prayer_rights_engine.py",
     "Prière des élèves musulmans à l'école & accommodations institutionnelles", "Wave 1009",
     "Élèves musulmans refusés dans leur droit à prier pendant les pauses scolaires par des règlements trop restrictifs.",
     "MSPA", "muslim_student_prayer"),
    ("jw_minor_blood_transfusion_rights_engine.py",
     "Mineurs Témoins de Jéhovah & transfusions sanguines refusées", "Wave 1009",
     "Conflits juridiques entre le droit médical de l'enfant aux soins vitaux et les croyances religieuses parentales.",
     "JWBT", "jw_minor_blood"),

    # Wave 1010 — Prison & réhabilitation (inédits)
    ("prison_education_program_rights_engine.py",
     "Accès à l'éducation en prison & droits des détenus à la réhabilitation", "Wave 1010",
     "Détenus sans accès à des programmes éducatifs ou de formation professionnelle malgré les preuves d'efficacité.",
     "PEPR", "prison_education"),
    ("probation_voting_rights_engine.py",
     "Droit de vote des personnes en liberté conditionnelle & citoyenneté civique", "Wave 1010",
     "Personnes en probation ou libération conditionnelle privées du droit de vote dans les États non réformés.",
     "PVRS", "probation_voting"),
    ("prison_nursery_rights_engine.py",
     "Nurseries carcérales & droits des mères incarcérées à garder leur bébé", "Wave 1010",
     "Mères incarcérées séparées de leurs nouveau-nés en l'absence de programmes nurseries dans la plupart des États.",
     "INPR", "prison_nursery"),

    # Wave 1011 — Santé mentale des enfants & jeunes
    ("school_counselor_ratio_rights_engine.py",
     "Ratio élèves/conseiller scolaire & crise de santé mentale juvénile", "Wave 1011",
     "Écoles avec des conseillers gérant 500 élèves chacun, incapables de détecter les crises de santé mentale.",
     "SCRA", "school_counselor_ratio"),
    ("pediatric_mental_health_hospitalization_rights_engine.py",
     "Pénurie de lits pédiatriques psychiatriques & attentes en urgence", "Wave 1011",
     "Enfants en crise psychiatrique attendant des jours aux urgences faute de lits pédiatriques psychiatriques.",
     "PMHH", "pediatric_psych_beds"),
    ("school_mental_health_telehealth_rights_engine.py",
     "Télésanté mentale à l'école & accès inégal selon le district", "Wave 1011",
     "Districts scolaires riches offrant la télésanté mentale pendant que les districts pauvres n'ont rien.",
     "SMTB", "school_mental_telehealth"),

    # Wave 1012 — Travailleurs spécifiques sous-représentés
    ("garment_piece_rate_rights_engine.py",
     "Salaire à la pièce dans l'industrie textile & vol de salaire systémique", "Wave 1012",
     "Couturières payées à la pièce en dessous du salaire minimum sans recours légal accessible.",
     "GPWR", "garment_piece_rate"),
    ("domestic_worker_scheduling_rights_engine.py",
     "Planification instable des travailleurs domestiques & droits à la prévisibilité", "Wave 1012",
     "Aides à domicile et femmes de ménage assignées sans préavis, bloquant leur droit à un deuxième emploi.",
     "DWSR", "domestic_schedule"),
    ("dockworker_health_safety_rights_engine.py",
     "Santé et sécurité des dockers & exposition aux émissions diesel", "Wave 1012",
     "Travailleurs portuaires exposés aux émissions diesel des navires et grues sans protection respiratoire adéquate.",
     "DKHS", "dockworker_safety"),

    # Wave 1013 — Logement & droits des locataires (inédits)
    ("landlord_retaliation_complaint_rights_engine.py",
     "Représailles des propriétaires après plaintes des locataires", "Wave 1013",
     "Locataires évincés ou harcelés après avoir signalé des violations d'habitabilité aux autorités locales.",
     "LRCR", "landlord_retaliate"),
    ("public_housing_lead_paint_rights_engine.py",
     "Peinture au plomb dans les logements publics & droits des familles", "Wave 1013",
     "Familles dans des logements HUD exposées à la peinture au plomb sans plan de remédiation malgré les lois.",
     "PHLR", "public_housing_lead"),
    ("section8_geographic_mobility_rights_engine.py",
     "Bons Section 8 & restrictions géographiques excluant les quartiers riches", "Wave 1013",
     "Bénéficiaires de Vouchers incapables de déménager dans des quartiers avec de meilleures écoles et emplois.",
     "SVGR", "section8_mobility"),

    # Wave 1014 — Environnement & communautés (inédits)
    ("superfund_cleanup_delay_rights_engine.py",
     "Retards de nettoyage des sites Superfund & santé des riverains", "Wave 1014",
     "Communautés vivant autour de sites Superfund contaminés attendant des décennies un nettoyage EPA.",
     "SFCD", "superfund_cleanup"),
    ("truck_route_diesel_community_rights_engine.py",
     "Routes de camions diesel & pollution dans les communautés défavorisées", "Wave 1014",
     "Quartiers pauvres traversés par des couloirs de transport lourd exposant les résidents aux PM2.5 diesel.",
     "TRDC", "truck_diesel_community"),
    ("refinery_fence_line_community_rights_engine.py",
     "Communautés à la clôture des raffineries & droits à la santé", "Wave 1014",
     "Résidents vivant directement contre les clôtures des raffineries subissant des pics de benzène sans protection.",
     "RFLN", "refinery_fence_line"),

    # Wave 1015 — Santé & accès aux soins (inédits)
    ("chronic_pain_discrimination_rights_engine.py",
     "Discrimination des patients douloureux chroniques & accès aux soins", "Wave 1015",
     "Patients souffrant de douleur chronique non cancéreuse traités comme des drogués et privés de traitement.",
     "CPMD", "chronic_pain_discrim"),
    ("lupus_racial_treatment_gap_rights_engine.py",
     "Lupus & disparité de traitement raciale pour les femmes noires", "Wave 1015",
     "Femmes noires atteintes de lupus diagnostiquées tardivement et moins bien traitées que les patientes blanches.",
     "LTRD", "lupus_racial_gap"),
    ("rare_disease_clinical_trial_rights_engine.py",
     "Maladies rares & accès aux essais cliniques pour les non-assurés", "Wave 1015",
     "Patients atteints de maladies rares sans accès aux essais cliniques faute d'assurance ou de transport.",
     "RDCT", "rare_disease_trial"),

    # Wave 1016 — Droits numériques & vie privée domestique
    ("smart_meter_opt_out_rights_engine.py",
     "Droit de retrait des compteurs intelligents & vie privée énergétique", "Wave 1016",
     "Résidents incapables de refuser les compteurs intelligents transmettant des données de consommation détaillées.",
     "SMTR", "smart_meter_optout"),
    ("home_security_camera_neighbor_rights_engine.py",
     "Caméras de surveillance domiciliaires & droits des voisins à la vie privée", "Wave 1016",
     "Voisins filmés en continu par des caméras de sécurité résidentielles sans recours légal ni réglementation.",
     "HSCN", "home_camera_neighbor"),
    ("facial_recognition_retail_rights_engine.py",
     "Reconnaissance faciale dans les commerces & droits des consommateurs", "Wave 1016",
     "Consommateurs identifiés et suivis par reconnaissance faciale dans les commerces sans consentement ni divulgation.",
     "FARR", "facial_recog_retail"),
]
