# Specs waves 977-984 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 977 — Athlètes & droits sportifs
    ("college_athlete_nil_rights_engine.py",
     "NIL & droits à la rémunération des athlètes universitaires", "Wave 977",
     "Athlètes universitaires privés de leur droit à monétiser leur nom, image et ressemblance.",
     "CANR", "college_nil"),
    ("athlete_concussion_cte_rights_engine.py",
     "CTE & traumatismes crâniens des athlètes professionnels", "Wave 977",
     "Joueurs professionnels souffrant de CTE après des traumatismes répétés dissimulés par les ligues.",
     "ACTC", "athlete_cte"),
    ("youth_sport_abuse_parent_rights_engine.py",
     "Abus dans le sport juvénile & droits des jeunes athlètes", "Wave 977",
     "Jeunes athlètes subissant des abus psychologiques et physiques d'entraîneurs sans supervision.",
     "YSAP", "youth_sport_abuse"),

    # Wave 978 — Animaux de service & soutien émotionnel
    ("emotional_support_animal_airline_rights_engine.py",
     "Animaux de soutien émotionnel & refus des compagnies aériennes", "Wave 978",
     "Passagers avec des troubles psychiques refusés avec leurs ESA après les nouvelles règles DOT.",
     "ESAA", "esa_airline"),
    ("dv_shelter_pet_policy_rights_engine.py",
     "Animaux domestiques & refus des refuges pour victimes DV", "Wave 978",
     "Victimes de violences domestiques refusant d'entrer dans des refuges n'acceptant pas leurs animaux.",
     "DVPP", "dv_pet_shelter"),
    ("false_service_animal_rights_engine.py",
     "Faux animaux de service & impact sur les utilisateurs légitimes", "Wave 978",
     "Propriétaires d'animaux frauduleux nuisant aux droits ADA des vrais utilisateurs de chiens guides.",
     "FSAV", "false_service_animal"),

    # Wave 979 — Soins infirmiers & professionnels de santé
    ("nurse_mandatory_overtime_rights_engine.py",
     "Heures supplémentaires obligatoires des infirmières & sécurité patients", "Wave 979",
     "Infirmières contraintes d'effectuer des heures supplémentaires au risque d'erreurs médicales.",
     "NMOR", "nurse_overtime"),
    ("nurse_staffing_ratio_rights_engine.py",
     "Ratio infirmières/patients & qualité des soins hospitaliers", "Wave 979",
     "Hôpitaux opérant avec des ratios insuffisants d'infirmières mettant des vies en danger.",
     "NSRP", "nurse_staffing"),
    ("healthcare_worker_violence_rights_engine.py",
     "Violence contre les professionnels de santé & protection légale insuffisante", "Wave 979",
     "Médecins et infirmières agressés dans les hôpitaux sans protection légale adéquate.",
     "HWVR", "healthcare_violence"),

    # Wave 980 — Travail des jeunes & planification imprévisible
    ("child_labor_us_manufacturing_rights_engine.py",
     "Travail des enfants dans l'industrie américaine & violations FLSA", "Wave 980",
     "Enfants travaillant dans des usines de transformation américaines en violation des lois fédérales.",
     "CLMF", "child_labor_manuf"),
    ("teen_work_hour_violation_rights_engine.py",
     "Violations des heures de travail des adolescents & FLSA", "Wave 980",
     "Adolescents travaillant de nuit ou des heures excessives en violation des protections FLSA.",
     "TWHV", "teen_work_hours"),
    ("unpredictable_work_schedule_rights_engine.py",
     "Planification imprévisible du travail & droits des travailleurs", "Wave 980",
     "Travailleurs assignés en dernière minute sans préavis, perturbant soins, études et revenus.",
     "UWSR", "unpred_schedule"),

    # Wave 981 — Logement & contaminants environnementaux
    ("asbestos_housing_poor_rights_engine.py",
     "Amiante dans les logements précaires & droits des locataires", "Wave 981",
     "Locataires pauvres exposés à l'amiante dans des bâtiments anciens sans rénovation ni relogement.",
     "ASHP", "asbestos_housing"),
    ("carbon_monoxide_detector_rental_rights_engine.py",
     "Détecteur CO dans les logements locatifs & obligations légales", "Wave 981",
     "Locataires sans détecteur de monoxyde de carbone fonctionnel, exposés à des risques mortels.",
     "CMDR", "co_detector"),
    ("meth_contaminated_home_rights_engine.py",
     "Logements contaminés par la méthamphétamine & droits des locataires", "Wave 981",
     "Locataires emménageant dans d'anciens laboratoires de meth sans test ni décontamination obligatoire.",
     "MCHM", "meth_home"),

    # Wave 982 — Aide sociale & systèmes administratifs
    ("medicaid_work_requirement_rights_engine.py",
     "Exigences de travail Medicaid & exclusion des personnes malades", "Wave 982",
     "Malades chroniques perdant leur Medicaid pour ne pas avoir satisfait des exigences de travail.",
     "MWRR", "medicaid_work_req"),
    ("snap_error_overpayment_rights_engine.py",
     "Remboursements SNAP pour erreurs & pression sur les bénéficiaires", "Wave 982",
     "Bénéficiaires SNAP contraints de rembourser des trop-perçus causés par des erreurs administratives.",
     "SEOP", "snap_overpayment"),
    ("social_security_backlog_disability_rights_engine.py",
     "Arriéré des demandes d'invalidité SS & attentes mortelles", "Wave 982",
     "Demandeurs d'invalidité SS attendant des années une décision, souvent mourant avant d'être approuvés.",
     "SSBR", "ss_disability_backlog"),

    # Wave 983 — Santé reproductive & maternité
    ("maternity_leave_unpaid_rights_engine.py",
     "Congé maternité non payé & disparités économiques entre femmes", "Wave 983",
     "Mères forcées de retourner au travail prématurément faute de congé maternité payé aux USA.",
     "MLUR", "maternity_unpaid"),
    ("midwife_scope_practice_rights_engine.py",
     "Pratique des sages-femmes & restrictions législatives étatiques", "Wave 983",
     "Sages-femmes qualifiées bloquées dans des États interdisant leur pratique indépendante.",
     "MSPR", "midwife_practice"),
    ("birth_center_closure_rights_engine.py",
     "Fermetures de maisons de naissance & accès à la maternité", "Wave 983",
     "Maisons de naissance fermées par des réglementations excessive limitant les options d'accouchement.",
     "BCCL", "birth_center"),

    # Wave 984 — Surveillance & droits numériques (nouvelles frontières)
    ("predictive_text_surveillance_rights_engine.py",
     "Prédiction de frappe & surveillance des communications privées", "Wave 984",
     "Autorités utilisant des outils d'analyse prédictive de texte pour surveiller les communications.",
     "PTSR", "predictive_text"),
    ("police_social_media_monitoring_rights_engine.py",
     "Surveillance policière des réseaux sociaux & droits civils", "Wave 984",
     "Police utilisant des outils d'analyse des réseaux sociaux pour surveiller les activistes.",
     "PSSM", "police_social_monitor"),
    ("surveillance_reform_fourth_amendment_rights_engine.py",
     "Réforme de la surveillance & 4e amendement à l'ère numérique", "Wave 984",
     "Protections du 4e amendement inadaptées aux nouvelles formes de surveillance numérique.",
     "SRFA", "surveillance_4th_amend"),
]
