# Specs waves 1225-1232 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1225 — Logement: droits locataires avancés (inédits)
    ("illegal_landlord_lockout_rights_engine.py",
     "Changement de serrures illégal par les propriétaires & droits des locataires à une réintégration immédiate et à des dommages", "Wave 1225",
     "Locataires retrouvant leur logement verrouillé par le propriétaire sans procédure judiciaire légale d'expulsion complétée.",
     "ILEV", "illegal_lockout"),
    ("emergency_rental_assistance_delay_rights_engine.py",
     "Délais excessifs des programmes d'aide d'urgence au loyer & droits des locataires en crise à un traitement accéléré", "Wave 1225",
     "Locataires en défaut de paiement attendant des mois le versement d'une aide d'urgence au loyer approuvée pendant qu'une expulsion avance.",
     "EADB", "emerg_rent_assist"),
    ("self_help_eviction_utility_shutoff_rights_engine.py",
     "Coupure illégale des services par les propriétaires pour forcer le départ & droits des locataires à des services essentiels", "Wave 1225",
     "Locataires victimes de propriétaires coupant eau, électricité ou chauffage pour les forcer à partir sans procédure judiciaire.",
     "SLHV", "self_help_utility"),

    # Wave 1226 — Santé: médicaments & équipements (inédits)
    ("pharmacist_conscience_refusal_rights_engine.py",
     "Refus de délivrer des médicaments pour raisons de conscience & droits des patients à accéder aux prescriptions légales", "Wave 1226",
     "Patients se voyant refuser contraception, médicaments abortifs ou autre traitement prescrit légalement par un pharmacien par conviction.",
     "PCRF", "pharm_conscience"),
    ("wheelchair_repair_insurance_delay_rights_engine.py",
     "Délais d'approbation d'assurance pour réparations de fauteuils roulants & droits des utilisateurs à un équipement fonctionnel", "Wave 1226",
     "Utilisateurs de fauteuils roulants motorisés cloués à domicile pendant des semaines en attente d'une approbation d'assurance pour réparation.",
     "WCRP", "wheelchair_repair"),
    ("contact_lens_prescription_portability_rights_engine.py",
     "Portabilité des ordonnances de lentilles de contact & droit des patients à obtenir leur prescription pour acheter ailleurs", "Wave 1226",
     "Patients se voyant refuser leur ordonnance de lentilles de contact par des optométristes voulant garder leur activité commerciale.",
     "DRCS", "contact_lens_presc"),

    # Wave 1227 — Finance: dettes & crédit consommateurs (inédits)
    ("credit_card_minimum_payment_trap_rights_engine.py",
     "Piège des paiements minimaux de cartes de crédit & droits des consommateurs à des avertissements clairs sur le remboursement total", "Wave 1227",
     "Titulaires de cartes ne payant que le minimum mensuel ignorant qu'il faudra 20 ans pour rembourser leur solde au taux actuel.",
     "CCPM", "credit_min_pay"),
    ("credit_card_late_fee_regulation_rights_engine.py",
     "Réglementation des frais de retard de cartes de crédit & droits des consommateurs contre les frais punitifs disproportionnés", "Wave 1227",
     "Titulaires de cartes payant 30 à 40 dollars de frais de retard pour avoir manqué d'un jour le délai de paiement.",
     "ILDV", "credit_late_fee"),
    ("child_minor_credit_freeze_rights_engine.py",
     "Gel du crédit pour les mineurs & droits des parents à protéger l'identité financière de leurs enfants avant qu'elle soit volée", "Wave 1227",
     "Enfants dont l'identité est utilisée frauduleusement pour ouvrir des comptes de crédit sans que leurs parents puissent le prévenir.",
     "ILMR", "child_credit_freeze"),

    # Wave 1228 — Immigration: autorisations de travail (inédits)
    ("ead_work_permit_processing_delay_rights_engine.py",
     "Délais de traitement des autorisations de travail EAD & droits des demandeurs à travailler légalement pendant les retards", "Wave 1228",
     "Demandeurs d'asile et immigrants légaux attendant plus d'un an leur EAD pour travailler légalement pendant que l'USCIS traite.",
     "CPMC", "ead_processing_delay"),
    ("medicaid_hcbs_waiver_wait_list_rights_engine.py",
     "Listes d'attente des aides Medicaid à domicile HCBS & droits des personnes handicapées à la désinstitutionnalisation", "Wave 1228",
     "Personnes handicapées attendant des années sur des listes d'attente pour des services Medicaid HCBS leur permettant de vivre chez elles.",
     "HCBS", "hcbs_wait_list"),
    ("community_integration_olmstead_rights_engine.py",
     "Application de l'arrêt Olmstead sur l'intégration communautaire & persistance de la sur-institutionnalisation des personnes handicapées", "Wave 1228",
     "Personnes handicapées maintenues dans des institutions coûteuses au lieu de recevoir des services communautaires conformément à Olmstead.",
     "NVMB", "olmstead_integrat"),

    # Wave 1229 — Droits: succession numérique & civiques (inédits)
    ("digital_estate_asset_access_rights_engine.py",
     "Accès aux actifs numériques après le décès & droits des héritiers à gérer comptes, cryptos et contenus numériques hérités", "Wave 1229",
     "Familles incapables d'accéder aux comptes, cryptomonnaies et actifs numériques d'un proche décédé sans loi uniforme d'accès.",
     "DGEQ", "digital_estate"),
    ("incarcerated_person_voting_rights_engine.py",
     "Droits de vote des personnes incarcérées pour délits mineurs & privation du droit civique pendant une détention provisoire", "Wave 1229",
     "Personnes en détention provisoire non condamnées ou condamnées pour délits mineurs privées du droit de vote dans de nombreux États.",
     "OMSP", "incarcerat_vote"),
    ("felon_voting_restoration_rights_engine.py",
     "Restauration du droit de vote pour les ex-détenus & processus de restauration complexes décourageant la réintégration civique", "Wave 1229",
     "Ex-détenus éligibles à la restauration de leurs droits civiques ne pouvant naviguer les procédures bureaucratiques sans aide légale.",
     "QIBR", "felon_vote_restore"),

    # Wave 1230 — Professions de santé: licences & pratique (inédits)
    ("nursing_license_discipline_rights_engine.py",
     "Procédures disciplinaires des conseils infirmiers & droits des infirmières à une procédure équitable avant suspension de licence", "Wave 1230",
     "Infirmières faisant l'objet de plaintes disciplinaires sans représentation légale adéquate et confrontées à des suspensions injustes.",
     "FLVD", "nursing_license_disc"),
    ("healthcare_license_interstate_compact_rights_engine.py",
     "Compacts intérétatiques de licences médicales & droits des praticiens à une reconnaissance rapide dans les États de destination", "Wave 1230",
     "Médecins, infirmières et thérapeutes déménageant entre États devant recommencer un processus de licence long malgré les compacts.",
     "HPOR", "health_license_compact"),
    ("earned_wage_employer_advance_rights_engine.py",
     "Programmes d'avances sur salaire offerts par les employeurs & droits des travailleurs à des termes équitables et non punitifs", "Wave 1230",
     "Travailleurs utilisant des programmes d'avances sur salaire parrainés par leur employeur avec des déductions automatiques et des frais cachés.",
     "GRPS", "earned_wage_employer"),

    # Wave 1231 — Justice: droits en prison & après (inédits)
    ("prison_mail_censorship_rights_engine.py",
     "Censure du courrier des détenus & droits constitutionnels à la correspondance non justiciée avec la famille et les avocats", "Wave 1231",
     "Détenus dont le courrier familial ou légal est censuré ou retenu sans motif de sécurité légitime par les administrations pénitentiaires.",
     "PHRR", "prison_mail_censor"),
    ("prison_strip_search_dignity_rights_engine.py",
     "Fouilles à nu des détenus sans motif probable & droits constitutionnels à la dignité dans les prisons et centres de détention", "Wave 1231",
     "Détenus soumis à des fouilles à nu répétées et humiliantes sans justification sécuritaire individuelle valable.",
     "PHRE", "prison_strip_search"),
    ("disaster_emergency_rental_aid_gap_rights_engine.py",
     "Lacunes dans l'aide au loyer d'urgence après catastrophe & droits des locataires à une protection pendant la reconstruction", "Wave 1231",
     "Locataires déplacés par des catastrophes naturelles sans couverture d'aide au loyer adaptée aux délais réels de reconstruction.",
     "FCWP", "disaster_rent_gap"),

    # Wave 1232 — Santé: portée de pratique & spécialités (inédits)
    ("pharmacist_scope_practice_extension_rights_engine.py",
     "Extension du champ de pratique des pharmaciens & droits des patients ruraux à un accès aux soins courants sans médecin", "Wave 1232",
     "Patients ruraux sans médecin local incapables d'obtenir des ordonnances simples auprès de pharmaciens formés mais non autorisés.",
     "SPCA", "pharm_scope_extend"),
    ("optometry_therapeutic_scope_rights_engine.py",
     "Champ de pratique thérapeutique des optométristes & restrictions des États limitant les soins oculaires accessibles", "Wave 1232",
     "Patients ayant besoin de traitements oculaires courants que leur optométriste est formé à fournir mais légalement interdit de traiter.",
     "ASVP", "optom_therap_scope"),
    ("sleep_specialist_shortage_rights_engine.py",
     "Pénurie de spécialistes du sommeil & droits des patients avec apnée grave à un diagnostic et traitement sans attente excessive", "Wave 1232",
     "Patients avec apnée sévère attendant 6 à 12 mois pour voir un spécialiste du sommeil en raison de pénuries critiques de médecins.",
     "SGAP", "sleep_specialist"),
]
