# Specs waves 1257-1264 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1257 — Handicap: accès & mobilité (inédits)
    ("spinal_cord_injury_vocational_rehab_rights_engine.py",
     "Réadaptation professionnelle pour blessés médullaires & droits d'accès aux services VR financés sans listes d'attente excessives", "Wave 1257",
     "Personnes avec lésions médullaires cherchant une réadaptation professionnelle confrontées à des listes d'attente de 2 à 3 ans pour des services VR financés.",
     "SCIV", "sci_vocational_rehab"),
    ("amputee_driver_license_adaptive_rights_engine.py",
     "Permis de conduire adapté pour amputés & droits à une évaluation équitable et à des adaptations véhiculaires financées", "Wave 1257",
     "Personnes amputées cherchant à conduire avec des véhicules adaptés confrontées à des évaluateurs insuffisamment formés aux capacités des amputés.",
     "ADRV", "amputee_adaptive_drive"),
    ("blind_assistive_technology_access_rights_engine.py",
     "Accès aux technologies d'assistance pour aveugles & droits à un financement suffisant pour les lecteurs d'écran et équipements Braille", "Wave 1257",
     "Personnes aveugles ou malvoyantes incapables d'obtenir le financement pour des technologies d'assistance essentielles à l'emploi et l'éducation.",
     "BATA", "blind_assistive_tech"),

    # Wave 1258 — Santé: conditions spécialisées (inédits)
    ("organ_donor_registry_family_override_rights_engine.py",
     "Droit de la famille à annuler le don d'organes enregistré & protection des volontés des donneurs inscrits au registre officiel", "Wave 1258",
     "Familles de donneurs décédés refusant le prélèvement d'organes malgré la volonté explicitement enregistrée du défunt de son vivant.",
     "ODRF", "organ_donor_override"),
    ("sjogrens_syndrome_diagnosis_rights_engine.py",
     "Syndrome de Sjögren: diagnostic tardif & droits des patients à être référés rapidement aux rhumatologues et ophtalmologues", "Wave 1258",
     "Patients atteints du syndrome de Sjögren attendant en moyenne 4 à 7 ans un diagnostic correct malgré des symptômes invalidants présents depuis longtemps.",
     "SJOG", "sjogrens_diagnosis"),
    ("chronic_fatigue_syndrome_recognition_rights_engine.py",
     "Reconnaissance médicale du syndrome de fatigue chronique ME/CFS & droits des patients contre le rejet diagnostique et la sous-prise en charge", "Wave 1258",
     "Patients atteints de ME/CFS se voyant dire que leur maladie est psychosomatique et refusés pour des traitements symptomatiques et des aménagements de handicap.",
     "FMPT", "cfs_me_recognition"),

    # Wave 1259 — Famille: droits avancés (inédits)
    ("foster_youth_education_stability_rights_engine.py",
     "Stabilité scolaire des jeunes en famille d'accueil & droits à rester dans leur école d'origine lors des changements de placement", "Wave 1259",
     "Enfants en famille d'accueil contraints de changer d'école à chaque changement de placement perdant la continuité éducative garantie par la loi McKinney-Vento.",
     "FYSE", "foster_youth_educ"),
    ("stepparent_adoption_consent_rights_engine.py",
     "Adoption par un beau-parent & droits procéduraux des parents biologiques absents pour contester ou consentir à l'adoption légale", "Wave 1259",
     "Parents biologiques non gardiens découvrant que leurs droits parentaux peuvent être supprimés via une adoption par un beau-parent sans leur consentement éclairé.",
     "SADC", "stepparent_adoption"),
    ("unmarried_father_paternity_rights_engine.py",
     "Droits des pères non mariés à établir la paternité légale & accès à la garde et visitation refusé sans procédure judiciaire coûteuse", "Wave 1259",
     "Pères non mariés voulant être présents dans la vie de leurs enfants confrontés à des procédures légales coûteuses pour établir leurs droits parentaux.",
     "UPRT", "unmarried_father_pat"),

    # Wave 1260 — Justice: droits diversifiés (inédits)
    ("eyewitness_misidentification_criminal_rights_engine.py",
     "Erreurs d'identification par témoins oculaires & droits des accusés à contester les procédures d'identification non fiables utilisées contre eux", "Wave 1260",
     "Accusés condamnés sur la base d'identifications oculaires erronées conduites sans procédures de double-aveugle protégeant contre les suggestions.",
     "EMIS", "eyewitness_misidentif"),
    ("civil_forfeiture_currency_seizure_rights_engine.py",
     "Saisie de liquidités par forfeiture civile & droits des porteurs de cash à récupérer leurs fonds sans être accusés d'un crime", "Wave 1260",
     "Voyageurs et citoyens se faisant confisquer leurs liquidités par la police sous prétexte de suspicion sans inculpation ni condamnation.",
     "CFCR", "civil_forfeiture_cash"),
    ("jury_selection_discrimination_rights_engine.py",
     "Discrimination dans la sélection des jurés & droits des accusés à contester les récusations péremptoires fondées sur la race ou le genre", "Wave 1260",
     "Accusés de minorités ethniques confrontés à des jurys dont les membres de leur groupe ont été systématiquement éliminés par des récusations péremptoires.",
     "JYSD", "jury_select_discrim"),

    # Wave 1261 — Logement: discrimination avancée (inédits)
    ("criminal_history_housing_fair_chance_rights_engine.py",
     "Logement équitable pour personnes avec casier judiciaire & droits des ex-détenus à ne pas être automatiquement refusés par les propriétaires", "Wave 1261",
     "Ex-détenus cherchant un logement refusés automatiquement en raison de leur casier judiciaire sans évaluation individuelle de leur situation.",
     "CFHC", "criminal_hist_housing"),
    ("hoa_disability_accommodation_denial_rights_engine.py",
     "Refus d'accommodements de handicap par les associations HOA & droits FHA des résidents handicapés à des modifications raisonnables", "Wave 1261",
     "Résidents handicapés dans des communautés HOA se voyant refuser des modifications raisonnables comme des rampes ou places de parking adaptées.",
     "HDAD", "hoa_disab_accommod"),
    ("security_deposit_deduction_dispute_rights_engine.py",
     "Contestation des déductions sur dépôts de garantie & droits des locataires à des retenues justifiées documentées et à une restitution rapide", "Wave 1261",
     "Locataires quittant leur logement se voyant retenir tout ou partie de leur dépôt pour des dommages préexistants ou des frais non justifiés.",
     "SEDP", "security_dep_deduct"),

    # Wave 1262 — Technologie: IA & décisions (inédits)
    ("ai_medical_diagnosis_error_rights_engine.py",
     "Erreurs des systèmes d'IA de diagnostic médical & droits des patients à une vérification humaine des diagnostics algorithmiques", "Wave 1262",
     "Patients dont les diagnostics ou résultats d'imagerie sont interprétés exclusivement par des algorithmes d'IA sans révision humaine obligatoire.",
     "AMDE", "ai_medical_diagn"),
    ("ai_bail_risk_assessment_rights_engine.py",
     "Outils d'évaluation des risques par IA pour la libération sous caution & droits des accusés à contester les scores algorithmiques opaques", "Wave 1262",
     "Accusés dont la détention provisoire est influencée par des scores de risque algorithmiques biaisés et non transparents sans possibilité de contestation.",
     "ABRK", "ai_bail_risk"),
    ("algorithmic_landlord_screening_rights_engine.py",
     "Sélection algorithmique des locataires par les propriétaires & droits des candidats à contester les refus fondés sur des scores opaques", "Wave 1262",
     "Candidats locataires refusés par des systèmes de scoring algorithmiques intégrant des données de crédit et comportementales sans transparence.",
     "ALSH", "algo_landlord_screen"),

    # Wave 1263 — Immigration: protection spécifique (inédits)
    ("u_visa_crime_victim_immigration_rights_engine.py",
     "Visa U pour victimes de crimes graves & droits à la certification policière et protection contre la déportation pendant la procédure", "Wave 1263",
     "Victimes de crimes graves non documentées éligibles au visa U incapables d'obtenir la certification des forces de l'ordre nécessaire à leur dossier.",
     "UVCV", "u_visa_crime_victim"),
    ("immigrant_witness_protection_rights_engine.py",
     "Protection des témoins immigrants contre les représailles & droits à une protection légale quand ils coopèrent avec les autorités", "Wave 1263",
     "Immigrants témoins de crimes ou victimes de traite coopérant avec les autorités sans protection efficace contre les représailles des trafiquants.",
     "IWPR", "immigrant_witness_prot"),
    ("consular_nonimmigrant_visa_denial_rights_engine.py",
     "Refus de visa non-immigrant au consulat & droits des demandeurs à une explication et à contester les refus de visas touristiques ou étudiants", "Wave 1263",
     "Demandeurs de visas non-immigrants légitimes se voyant refuser sans explication de fond sous la présomption d'intention d'immigration.",
     "CVND", "consular_visa_denial"),

    # Wave 1264 — Santé: maternité & reproduction (inédits)
    ("fertility_preservation_cancer_rights_engine.py",
     "Préservation de la fertilité pour patients atteints de cancer & droits à la couverture d'assurance avant traitements stérilisants", "Wave 1264",
     "Patients atteints de cancer en âge de procréer ne pouvant pas accéder à la congélation d'ovocytes ou de sperme avant chimiothérapie faute de couverture.",
     "FPCA", "fertility_preserv_cancer"),
    ("gestational_surrogacy_legal_rights_engine.py",
     "Droits légaux dans la gestation pour autrui & protection juridique des parents d'intention et des mères porteuses dans les États sans loi", "Wave 1264",
     "Parents d'intention et mères porteuses dans des États sans loi sur la GPA confrontés à une insécurité juridique sur la parentalité légale de l'enfant.",
     "GSRG", "gestational_surrog"),
    ("perinatal_mental_health_insurance_rights_engine.py",
     "Couverture d'assurance pour la santé mentale périnatale & droits des femmes enceintes et post-partum à une prise en charge remboursée", "Wave 1264",
     "Femmes enceintes ou ayant accouché récemment souffrant d'anxiété ou dépression périnatale incapables d'accéder à des soins remboursés par leur assurance.",
     "PMHI", "perinatal_mental_hlth"),
]
