# Specs waves 1273-1280 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1273 — Santé: cancer & dépistage (inédits)
    ("colorectal_cancer_screening_access_rights_engine.py",
     "Accès au dépistage du cancer colorectal & droits des assurés à une coloscopie de suivi sans frais après un résultat anormal au test de selles", "Wave 1273",
     "Assurés payant des milliers de dollars pour une coloscopie de diagnostic après un test de selles anormal supposément couvert sans frais par l'ACA.",
     "CCSA", "colorectal_screen"),
    ("lung_cancer_low_dose_ct_rights_engine.py",
     "Dépistage du cancer du poumon par scanner faible dose & droits des fumeurs actuels et anciens à une couverture complète sans copaiement", "Wave 1273",
     "Fumeurs éligibles au dépistage annuel LDCT selon les directives USPSTF se voyant facturer des frais par des assureurs ignorant la règle préventive.",
     "LCCT", "lung_cancer_ldct"),
    ("prostate_cancer_psa_coverage_rights_engine.py",
     "Couverture du test PSA pour le dépistage du cancer de la prostate & droits des hommes à une prise de décision éclairée sur le dépistage", "Wave 1273",
     "Hommes à haut risque de cancer de la prostate confrontés à des assureurs refusant le remboursement du PSA ou exigeant des copaiements injustifiés.",
     "PPSA", "prostate_psa_cover"),

    # Wave 1274 — Logement: financement & aides (inédits)
    ("manufactured_home_financing_rights_engine.py",
     "Financement des maisons manufacturées & droits des acheteurs à des prêts immobiliers abordables sans être limités aux prêts personnels à taux élevé", "Wave 1274",
     "Acheteurs de maisons manufacturées contraints d'accepter des prêts personnels chattel à 15% d'intérêt car leur maison n'est pas considérée comme un bien immobilier.",
     "MHFL", "manufactured_home_fin"),
    ("fha_loan_condo_approval_rights_engine.py",
     "Approbation FHA pour copropriétés & droits des acheteurs à faibles revenus à accéder au financement FHA dans des complexes non approuvés", "Wave 1274",
     "Acheteurs voulant utiliser des prêts FHA confrontés à des complexes de copropriété non approuvés par la FHA rendant leur achat impossible.",
     "FCAC", "fha_condo_approval"),
    ("hud_housing_counseling_access_rights_engine.py",
     "Accès au conseil en logement HUD & droits des acheteurs et locataires à un service gratuit de conseil avant une décision immobilière majeure", "Wave 1274",
     "Ménages à revenus modestes cherchant à accéder à des conseillers HUD agréés confrontés à des listes d'attente ou l'absence de services dans leur zone.",
     "HDHC", "hud_housing_counsel"),

    # Wave 1275 — Transport & mobilité (inédits)
    ("ride_share_wheelchair_accessible_rights_engine.py",
     "Accessibilité en fauteuil roulant des services de covoiturage & droits ADA des personnes handicapées à une attente équitable sans surtarification", "Wave 1275",
     "Utilisateurs de fauteuils roulants attendant 30 à 60 minutes pour un véhicule Uber ou Lyft accessible alors que les autres attendent 5 minutes.",
     "RWCA", "rideshare_wheelchair"),
    ("special_ed_transportation_rights_engine.py",
     "Transport scolaire pour élèves de l'éducation spéciale & droits à un transport IDEA adapté sans retards ou distances excessives", "Wave 1275",
     "Élèves avec IEP attendant des heures dans des bus inadaptés ou se voyant refuser le transport vers leur école de placement appropriée.",
     "STSD", "sped_transportation"),
    ("intercity_bus_ada_compliance_rights_engine.py",
     "Conformité ADA des services d'autobus interurbains & droits des passagers handicapés à un accès équitable aux voyages longue distance", "Wave 1275",
     "Personnes handicapées incapables d'utiliser les services d'autobus interurbains comme Greyhound en raison de véhicules ou arrêts non conformes à l'ADA.",
     "LBAD", "intercity_bus_ada"),

    # Wave 1276 — Droits civiques: vote & participation (inédits)
    ("voter_id_student_id_rights_engine.py",
     "Identifiant étudiant pour le vote & droits des étudiants à utiliser leur carte d'étudiant comme pièce d'identité aux urnes", "Wave 1276",
     "Étudiants dans des États refusant les cartes d'identité universitaires comme preuve d'identité valide pour voter contraints d'obtenir une pièce d'identité supplémentaire.",
     "VISC", "voter_student_id"),
    ("absentee_ballot_rejection_rights_engine.py",
     "Rejet des bulletins de vote par correspondance & droits des électeurs à être notifiés et à corriger les erreurs procédurales avant la date limite", "Wave 1276",
     "Électeurs se faisant rejeter leur bulletin de vote par correspondance pour des erreurs mineures comme une signature manquante sans notification en temps voulu.",
     "ABRJ", "absentee_ballot_rej"),
    ("provisional_ballot_rights_engine.py",
     "Droit aux bulletins provisoires & garanties pour les électeurs dont l'inscription est contestée le jour du scrutin de pouvoir participer", "Wave 1276",
     "Électeurs dont le nom n'apparaît pas sur les listes le jour de l'élection se voyant refuser un bulletin provisoire ou dont le bulletin est rejeté sans examen.",
     "PVBL", "provisional_ballot"),

    # Wave 1277 — Consommateurs: produits & garanties (inédits)
    ("lemon_law_vehicle_rights_engine.py",
     "Loi citron pour les véhicules défectueux & droits des acheteurs à un remplacement ou remboursement pour les voitures neuves avec défauts récurrents", "Wave 1277",
     "Acheteurs de véhicules neufs présentant des défauts récurrents se voyant opposer des définitions restrictives de la loi citron par les constructeurs.",
     "LEMN", "lemon_law_vehicle"),
    ("used_car_as_is_warranty_rights_engine.py",
     "Garantie des voitures d'occasion vendues en l'état & droits des acheteurs contre les vices cachés non divulgués dans les ventes de gré à gré", "Wave 1277",
     "Acheteurs de voitures d'occasion vendues en l'état découvrant des problèmes mécaniques graves non divulgués par le vendeur et sans recours légal.",
     "UCWT", "used_car_warranty"),
    ("extended_warranty_appliance_rights_engine.py",
     "Garanties prolongées pour appareils ménagers & droits des consommateurs à des produits de garantie qui couvrent vraiment les pannes prévisibles", "Wave 1277",
     "Consommateurs ayant acheté des garanties prolongées se voyant refuser les réparations pour des exclusions obscures non divulguées clairement à l'achat.",
     "AWRP", "extended_warranty_app"),

    # Wave 1278 — Emploi: sécurité & santé (inédits)
    ("musculoskeletal_disorder_ergonomic_rights_engine.py",
     "Prévention des troubles musculo-squelettiques au travail & droits des travailleurs à des ajustements ergonomiques obligatoires dans les environnements répétitifs", "Wave 1278",
     "Travailleurs d'entrepôts, usines et bureaux développant des TMS évitables faute de programmes ergonomiques obligatoires dans leur État ou secteur.",
     "ERGO", "msd_ergonomic_prev"),
    ("indoor_heat_illness_worker_rights_engine.py",
     "Protection contre les maladies liées à la chaleur pour les travailleurs intérieurs & droits dans les entrepôts et cuisines sans climatisation adéquate", "Wave 1278",
     "Travailleurs dans des entrepôts non climatisés, cuisines et fonderies exposés à des températures dangereuses sans standard OSHA de chaleur intérieure.",
     "HIPR", "indoor_heat_worker"),
    ("osha_retaliation_complaint_rights_engine.py",
     "Représailles pour plaintes OSHA & droits des travailleurs à dénoncer des conditions dangereuses sans craindre le licenciement ou des mesures défavorables", "Wave 1278",
     "Travailleurs signalant des violations de sécurité à l'OSHA subissant des représailles patronales sans voie rapide d'appel ou de réintégration provisoire.",
     "ROSH", "osha_retaliation"),

    # Wave 1279 — Assurance: droits & procédures (inédits)
    ("insurance_claim_appraisal_rights_engine.py",
     "Clause d'arbitrage d'expertise dans les polices d'assurance habitation & droits des assurés à une évaluation indépendante des sinistres contestés", "Wave 1279",
     "Propriétaires dont les réclamations d'assurance sont sous-évaluées par l'assureur confrontés à un processus d'appel par expertise inaccessible et coûteux.",
     "ICAP", "insur_claim_apprais"),
    ("independent_medical_exam_insurance_rights_engine.py",
     "Examens médicaux indépendants dans les litiges d'assurance & droits des assurés à contester des IME défavorables commandés par l'assureur", "Wave 1279",
     "Demandeurs d'assurance soumis à des examens médicaux indépendants commandités par l'assureur dont les conclusions biaisées servent à refuser les prestations.",
     "IMEP", "indep_medical_exam"),
    ("coordination_of_benefits_insurance_rights_engine.py",
     "Coordination des prestations entre polices d'assurance multiples & droits des assurés à éviter les paiements doubles et les lacunes de couverture", "Wave 1279",
     "Personnes avec plusieurs polices d'assurance confrontées à des disputes de coordination entre assureurs qui refusent chacun d'être le payeur principal.",
     "CBID", "coord_benefits_ins"),

    # Wave 1280 — Finance: retraite & épargne (inédits)
    ("pension_lump_sum_election_rights_engine.py",
     "Choix entre rente et capital forfaitaire pour les pensions & droits des retraités à une information complète avant une décision irrévocable", "Wave 1280",
     "Retraités choisissant entre une rente viagère et un capital forfaitaire sans conseil fiduciaire indépendant sur les implications fiscales et successorales.",
     "PNLS", "pension_lump_sum"),
    ("retirement_hardship_withdrawal_rights_engine.py",
     "Retraits pour difficultés financières des comptes de retraite & droits des travailleurs à accéder à leur épargne en cas d'urgence sans pénalités excessives", "Wave 1280",
     "Travailleurs en difficulté financière confrontés à des procédures complexes et des pénalités dissuasives pour accéder à leurs propres épargnes de retraite.",
     "RETH", "retire_hardship_with"),
    ("403b_teacher_retirement_rights_engine.py",
     "Plans de retraite 403(b) pour enseignants & droits des éducateurs à des options d'investissement à faibles frais sans produits d'assurance coûteux", "Wave 1280",
     "Enseignants piégés dans des plans 403(b) avec des fonds à frais élevés ou des rentes variables opaque vendus par des agents non fiduciaires.",
     "ETBC", "403b_teacher_ret"),
]
