# Specs waves 1033-1040 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : PADR→PALD, FWHC→FWDR (farmworker_housing→dental) ; 0 collision après corrections, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1033 — Droit de la famille & protection (inédits)
    ("parental_alienation_detection_rights_engine.py",
     "Aliénation parentale & droits des parents victimes dans les procédures de garde", "Wave 1033",
     "Parents séparés dont l'enfant est systématiquement retourné contre eux sans outils légaux de détection fiables.",
     "PALD", "parental_alienation"),
    ("grandparent_custody_rights_engine.py",
     "Garde des enfants par les grands-parents & conflits avec les droits parentaux", "Wave 1033",
     "Grands-parents élevant leurs petits-enfants sans statut légal clair, vulnérables face aux décisions des parents.",
     "GRCP", "grandparent_custody"),
    ("domestic_adoption_disruption_rights_engine.py",
     "Perturbation d'adoption domestique & droits des enfants abandonnés", "Wave 1033",
     "Adoptions nationales interrompues par les familles adoptives sans recours ni filet de sécurité pour l'enfant.",
     "DADR", "adoption_disruption"),

    # Wave 1034 — Travailleurs agricoles & migrants (inédits)
    ("farmworker_dental_health_rights_engine.py",
     "Santé dentaire des travailleurs agricoles & absence de couverture assurance", "Wave 1034",
     "Travailleurs agricoles souffrant de caries sévères sans aucune couverture dentaire ni clinique mobile accessible.",
     "FWDR", "farmworker_dental"),
    ("labor_trafficking_agriculture_rights_engine.py",
     "Trafic de main-d'œuvre agricole & impunité des recruteurs frauduleux", "Wave 1034",
     "Travailleurs agricoles victimes de trafic contraints à travailler sous menace sans poursuites des recruteurs.",
     "LTAG", "labor_traffic_agri"),
    ("migrant_worker_bank_access_rights_engine.py",
     "Accès bancaire des travailleurs migrants & exclusion financière", "Wave 1034",
     "Travailleurs migrants refusés par les banques sans pièces d'identité standardisées ou numéro de sécurité sociale.",
     "MWBK", "migrant_bank_access"),

    # Wave 1035 — Sécurité publique & accidents (inédits)
    ("firework_injury_liability_rights_engine.py",
     "Blessures par feux d'artifice & responsabilité des organisateurs d'événements", "Wave 1035",
     "Spectateurs blessés lors de spectacles pyrotechniques sans recours contre les organisateurs non assurés.",
     "FIRJ", "firework_injury"),
    ("swimming_pool_inspection_rights_engine.py",
     "Inspection des piscines publiques & responsabilité municipale en cas d'accident", "Wave 1035",
     "Noyades évitables dans des piscines publiques dont les inspections de sécurité étaient en retard ou bâclées.",
     "SWPI", "pool_inspection"),
    ("amusement_park_safety_rights_engine.py",
     "Sécurité des parcs d'attractions & absence de régulation fédérale", "Wave 1035",
     "Accidents graves dans des parcs d'attractions réglementés par les seuls États sans standard fédéral unifié.",
     "AMPR", "amusement_park_safe"),

    # Wave 1036 — Infrastructure & responsabilité publique
    ("pothole_vehicle_damage_rights_engine.py",
     "Dommages véhicule causés par les nids-de-poule & responsabilité municipale", "Wave 1036",
     "Conducteurs dont les véhicules sont endommagés par des nids-de-poule signalés mais non réparés sans recours clair.",
     "PVDL", "pothole_damage"),
    ("railroad_crossing_safety_rights_engine.py",
     "Sécurité des passages à niveau & responsabilité des compagnies ferroviaires", "Wave 1036",
     "Accidents mortels aux passages à niveau défectueux sans signalisation adéquate ni entretien par les opérateurs.",
     "RRCS", "railroad_crossing"),
    ("bridge_inspection_neglect_rights_engine.py",
     "Ponts défectueux & droits des usagers à des infrastructures sûres", "Wave 1036",
     "Ponts classés structurellement déficients utilisés quotidiennement sans calendrier de rénovation fixé.",
     "BINR", "bridge_inspection"),

    # Wave 1037 — Santé bucco-dentaire & visuelle spécifique
    ("orthodontic_medicaid_access_rights_engine.py",
     "Accès à l'orthodontie pour enfants Medicaid & développement dentaire", "Wave 1037",
     "Enfants Medicaid refusés pour un traitement orthodontique nécessaire faute de couverture ou de praticiens.",
     "ORDM", "orthodontic_medicaid"),
    ("dental_emergency_gap_rights_engine.py",
     "Urgences dentaires & lacunes de couverture pour les patients sans assurance", "Wave 1037",
     "Patients souffrant d'urgences dentaires sévères contraints aux urgences hospitalières sans couverture dentaire.",
     "DEGC", "dental_emergency_gap"),
    ("vision_therapy_coverage_rights_engine.py",
     "Thérapie visuelle & exclusion des assurances pour les enfants avec troubles", "Wave 1037",
     "Enfants souffrant de troubles visuels fonctionnels refusés pour la thérapie visuelle non couverte par les assureurs.",
     "VTCV", "vision_therapy"),

    # Wave 1038 — Logement & location (inédits)
    ("airbnb_host_eviction_rights_engine.py",
     "Hôtes Airbnb évincés par des guests & absence de protection légale", "Wave 1038",
     "Propriétaires Airbnb victimes de guests refusant de partir, transformés en locataires avec droits de protection.",
     "AHEV", "airbnb_host_evict"),
    ("vacation_rental_scam_rights_engine.py",
     "Arnaques de locations de vacances & droits des victimes sur les plateformes", "Wave 1038",
     "Vacanciers escroqués par de fausses annonces de location payées à l'avance sans propriété existante.",
     "VRSC", "vacation_rental_scam"),
    ("tenant_sublease_prohibition_rights_engine.py",
     "Interdiction de sous-location & droits des locataires à la flexibilité", "Wave 1038",
     "Locataires à revenus modestes interdits de sous-louer en cas d'absence prolongée, forçant des doubles paiements.",
     "SLPR", "sublease_prohibit"),

    # Wave 1039 — Presse & accès à l'information
    ("local_news_desert_rights_engine.py",
     "Déserts médiatiques locaux & droit des citoyens à l'information publique", "Wave 1039",
     "Communautés rurales et urbaines pauvres sans journalisme local pour surveiller les élus et les entreprises.",
     "LNDR", "local_news_desert"),
    ("shield_law_journalist_rights_engine.py",
     "Lois boucliers pour journalistes & protection des sources confidentielles", "Wave 1039",
     "Journalistes dans des États sans loi bouclier contraints de révéler leurs sources sous peine de prison.",
     "SLJP", "shield_law_journalist"),
    ("foia_delay_barrier_rights_engine.py",
     "Délais excessifs des demandes FOIA & droit d'accès aux informations publiques", "Wave 1039",
     "Demandes FOIA ignorées des mois ou années, privant citoyens et journalistes de documents publics essentiels.",
     "FDRB", "foia_delay"),

    # Wave 1040 — Justice civile & accès aux droits (inédits)
    ("wrongful_death_civil_rights_engine.py",
     "Décès injustifié par la police & obstacles aux recours civils des familles", "Wave 1040",
     "Familles de victimes de violence policière incapables de poursuivre civilement en raison de l'immunité qualifiée.",
     "WDCR", "wrongful_death_police"),
    ("civil_forfeiture_reform_rights_engine.py",
     "Réforme de la confiscation civile & résistance des services de police", "Wave 1040",
     "Saisies d'actifs sans condamnation maintenues par les législatures sous pression des services de police.",
     "CFRB", "civil_forfeit_reform"),
    ("expungement_low_income_barrier_rights_engine.py",
     "Barrières à l'effacement des casiers judiciaires pour les personnes à faibles revenus", "Wave 1040",
     "Personnes éligibles à l'effacement de casier incapables de financer la procédure judiciaire complexe et coûteuse.",
     "EILR", "expunge_low_income"),
]
