# Specs waves 1377-1384 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Corrections: TRFR pris → TRFP; court_interpreter (CIQR) doublon sémantique → self_represented_litigant (SRLA)
SPECS = [
    # Wave 1377 — Santé: maladies & traitements (inédits)
    ("gout_treatment_access_rights_engine.py",
     "Accès au traitement de la goutte chronique & droits des patients à des thérapies hypo-uricémiantes et anti-inflammatoires sans être limités à la gestion des crises aiguës uniquement", "Wave 1377",
     "Patients atteints de goutte chronique subissant des crises répétées invalidantes faute d'accès à un traitement de fond hypo-uricémiant adéquat et à un suivi rhumatologique.",
     "GTAC", "gout_treatment"),
    ("bell_palsy_recovery_treatment_rights_engine.py",
     "Traitement et rééducation de la paralysie de Bell & droits des patients à un accès rapide aux corticoïdes, antiviraux et rééducation faciale dès l'apparition des symptômes", "Wave 1377",
     "Patients atteints de paralysie faciale de Bell ne recevant pas de traitement rapide ni de rééducation faciale remboursée, entraînant des séquelles permanentes évitables.",
     "BPRT", "bell_palsy_recovery"),
    ("chronic_migraine_preventive_access_rights_engine.py",
     "Accès aux traitements préventifs de la migraine chronique & droits des patients à des anticorps anti-CGRP et injections sans devoir échouer des traitements multiples au préalable", "Wave 1377",
     "Patients souffrant de migraine chronique invalidante contraints d'essayer et d'échouer plusieurs traitements préventifs anciens avant d'accéder aux thérapies anti-CGRP modernes.",
     "CMPA", "chronic_migraine_prev"),

    # Wave 1378 — Santé: traitements spécialisés & chirurgie (inédits)
    ("cystic_fibrosis_modulator_access_rights_engine.py",
     "Accès aux modulateurs CFTR pour la mucoviscidose & droits des patients à ces thérapies transformatrices sans restrictions d'âge, de mutation ou de coût imposées par l'assurance", "Wave 1378",
     "Patients atteints de mucoviscidose se voyant refuser l'accès aux modulateurs CFTR transformateurs en raison de restrictions d'assurance fondées sur l'âge ou le type de mutation.",
     "CFMA", "cf_modulator_access"),
    ("psoriasis_systemic_treatment_access_rights_engine.py",
     "Accès aux traitements systémiques du psoriasis sévère & droits des patients à des biothérapies sans être limités aux traitements topiques inefficaces pour les formes étendues", "Wave 1378",
     "Patients atteints de psoriasis sévère couvrant une grande surface corporelle contraints d'utiliser des crèmes topiques inefficaces avant d'accéder aux biothérapies par leur assurance.",
     "PSTA", "psoriasis_systemic"),
    ("bariatric_surgery_coverage_rights_engine.py",
     "Couverture de la chirurgie bariatrique médicalement nécessaire & droits des patients à une prise en charge sans exigences préalables excessives ni exclusions catégorielles arbitraires", "Wave 1378",
     "Patients atteints d'obésité morbide avec comorbidités graves se voyant refuser la couverture d'une chirurgie bariatrique médicalement nécessaire par des exclusions de police arbitraires.",
     "BSCA", "bariatric_surgery"),

    # Wave 1379 — Santé: chirurgie, dispositifs & épargne (inédits)
    ("spinal_stenosis_surgery_access_rights_engine.py",
     "Accès à la chirurgie de la sténose spinale & droits des patients souffrant de compression nerveuse invalidante à une intervention chirurgicale sans délais d'autorisation prolongés", "Wave 1379",
     "Patients atteints de sténose spinale sévère avec douleur et perte de mobilité confrontés à des refus ou délais d'autorisation préalable pour une chirurgie décompressive nécessaire.",
     "SSSA", "spinal_stenosis_surg"),
    ("varicose_vein_medical_necessity_rights_engine.py",
     "Nécessité médicale du traitement des varices & droits des patients avec insuffisance veineuse symptomatique à un traitement remboursé sans être classés à tort comme demandes esthétiques", "Wave 1379",
     "Patients souffrant d'insuffisance veineuse chronique avec ulcères et douleurs se voyant refuser le traitement classé à tort comme esthétique malgré sa nécessité médicale documentée.",
     "VVMN", "varicose_vein_medical"),
    ("health_savings_account_access_rights_engine.py",
     "Accès équitable aux comptes d'épargne santé HSA & droits des travailleurs à faibles revenus à bénéficier des avantages fiscaux santé sans être désavantagés par leur incapacité d'épargner", "Wave 1379",
     "Travailleurs à faibles revenus avec plans à franchise élevée incapables de profiter des avantages fiscaux des HSA faute de revenu disponible à épargner, contrairement aux hauts revenus.",
     "HSAA", "hsa_access_equity"),

    # Wave 1380 — Logement: accès & propriété (inédits)
    ("shared_equity_homeownership_rights_engine.py",
     "Accession à la propriété en équité partagée & droits des acheteurs de programmes d'équité partagée à des conditions transparentes de revente et de partage de plus-value équitables", "Wave 1380",
     "Acheteurs accédant à la propriété via des programmes d'équité partagée ou de fiducies foncières communautaires confrontés à des clauses de revente complexes limitant leur plus-value.",
     "SEHO", "shared_equity_home"),
    ("tenant_right_first_refusal_rights_engine.py",
     "Droit de préemption des locataires & droits des occupants à une priorité d'achat de leur logement lors de la mise en vente de l'immeuble avant la vente à un tiers", "Wave 1380",
     "Locataires d'immeubles mis en vente perdant leur logement faute de droit de préemption leur permettant d'acheter collectivement ou individuellement avant un investisseur extérieur.",
     "TRFP", "tenant_first_refusal"),
    ("property_tax_circuit_breaker_rights_engine.py",
     "Dispositifs de plafonnement de l'impôt foncier selon le revenu & droits des propriétaires âgés et à faibles revenus à un allégement fiscal pour éviter la perte de leur logement", "Wave 1380",
     "Propriétaires âgés à revenu fixe confrontés à des hausses d'impôt foncier menaçant leur logement sans connaître les dispositifs de circuit breaker plafonnant l'impôt selon le revenu.",
     "PTCB", "property_tax_circuit"),

    # Wave 1381 — Logement: vulnérables & financement (inédits)
    ("seasonal_agricultural_housing_rights_engine.py",
     "Logement des travailleurs agricoles saisonniers & droits des ouvriers migrants à un hébergement sûr, salubre et conforme aux normes fourni par les employeurs durant la saison", "Wave 1381",
     "Travailleurs agricoles saisonniers logés dans des baraquements surpeuplés, insalubres et non conformes aux normes de sécurité par des employeurs échappant aux inspections.",
     "SAHO", "seasonal_ag_housing"),
    ("manufactured_home_lender_steering_rights_engine.py",
     "Orientation prédatrice des acheteurs de maisons préfabriquées vers des prêts coûteux & droits des acquéreurs à un financement équitable sans être dirigés vers du crédit captif onéreux", "Wave 1381",
     "Acheteurs de maisons préfabriquées orientés par les vendeurs vers des prêts personnels à taux élevé au lieu d'hypothèques conventionnelles moins chères auxquelles ils sont éligibles.",
     "MHLS", "mfg_home_lender_steer"),
    ("rent_to_own_furniture_trap_rights_engine.py",
     "Pièges des contrats de location-vente de meubles et électroménagers & droits des consommateurs à connaître le coût total réel exorbitant avant de s'engager dans ces accords", "Wave 1381",
     "Consommateurs à faibles revenus louant meubles et appareils en location-vente payant au final plusieurs fois le prix de détail sans comprendre le coût total des contrats.",
     "RTOF", "rent_to_own_furniture"),

    # Wave 1382 — Immigration: procédure & statut (inédits)
    ("visa_revocation_notice_rights_engine.py",
     "Notification lors de la révocation de visa & droits des titulaires à être informés des motifs et à contester une révocation avant de subir des conséquences sur leur statut légal", "Wave 1382",
     "Titulaires de visas révoqués sans notification préalable ni explication découvrant leur statut compromis lors d'un voyage ou contrôle, sans voie de contestation claire.",
     "VRNT", "visa_revocation_notice"),
    ("green_card_renewal_delay_rights_engine.py",
     "Délais de renouvellement de la carte verte & droits des résidents permanents à une preuve de statut valide et au droit de travailler et voyager pendant le traitement du renouvellement", "Wave 1382",
     "Résidents permanents légaux dont la carte verte expire avant le renouvellement confrontés à des difficultés d'emploi, de voyage et de preuve de statut malgré leur statut maintenu.",
     "GCRD", "green_card_renewal"),
    ("immigration_court_continuance_rights_engine.py",
     "Reports d'audience devant les tribunaux d'immigration & droits des justiciables à un délai raisonnable pour préparer leur défense et obtenir un avocat sans rejet expéditif de leur cas", "Wave 1382",
     "Justiciables en procédure d'immigration se voyant refuser des reports d'audience nécessaires pour trouver un avocat ou rassembler des preuves, conduisant à des décisions précipitées.",
     "ICCN", "immigr_court_continue"),

    # Wave 1383 — Éducation & réadaptation (inédits)
    ("english_learner_reclassification_rights_engine.py",
     "Reclassification des élèves apprenants d'anglais & droits des élèves à une évaluation équitable pour sortir du statut EL sans y être maintenus indûment ni en sortir prématurément", "Wave 1383",
     "Élèves apprenants d'anglais maintenus des années dans des programmes EL malgré leur maîtrise, ou reclassés prématurément sans soutien, en raison de critères incohérents.",
     "ELRC", "el_reclassification"),
    ("vocational_rehab_transition_rights_engine.py",
     "Services de réadaptation professionnelle à la transition & droits des jeunes handicapés et adultes à un accompagnement vers l'emploi sans listes d'attente ni ordres de priorité excluants", "Wave 1383",
     "Personnes handicapées cherchant un emploi via les agences de réadaptation professionnelle bloquées par des listes d'attente et des ordres de priorité excluant les handicaps moins sévères.",
     "VRTR", "voc_rehab_transition"),
    ("edtech_student_data_privacy_rights_engine.py",
     "Vie privée des données scolaires collectées par les technologies éducatives & droits des élèves et parents à contrôler la collecte commerciale des données par les plateformes EdTech", "Wave 1383",
     "Élèves utilisant des plateformes EdTech dont les données d'apprentissage, comportementales et personnelles sont collectées et potentiellement monétisées sans consentement parental éclairé.",
     "ETSD", "edtech_student_data"),

    # Wave 1384 — Justice: accès & équité (inédits)
    ("self_represented_litigant_assistance_rights_engine.py",
     "Assistance aux justiciables sans avocat & droits des parties se représentant elles-mêmes à des ressources, formulaires simplifiés et aide procédurale pour accéder réellement à la justice", "Wave 1384",
     "Justiciables sans moyens d'engager un avocat confrontés à des procédures judiciaires complexes sans assistance, formulaires accessibles ni guichets d'aide à l'auto-représentation.",
     "SRLA", "self_rep_litigant"),
    ("civil_contempt_jail_debt_rights_engine.py",
     "Emprisonnement pour outrage civil lié aux dettes & droits des débiteurs à ne pas être incarcérés pour incapacité de payer sans audience sur leur capacité réelle de paiement", "Wave 1384",
     "Personnes incarcérées pour outrage civil pour non-paiement de pensions, amendes ou dettes sans audience déterminant leur capacité réelle de payer, recréant de fait la prison pour dettes.",
     "CCJD", "civil_contempt_debt"),
    ("ankle_monitor_fee_rights_engine.py",
     "Frais des bracelets électroniques de surveillance & droits des personnes sous surveillance électronique à ne pas payer des frais quotidiens créant une détention conditionnée à la richesse", "Wave 1384",
     "Personnes placées sous surveillance par bracelet électronique contraintes de payer des frais quotidiens élevés, transformant une alternative à la détention en piège de dette pour les pauvres.",
     "AMFE", "ankle_monitor_fee"),
]
