# Specs waves 961-968 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 961 — Surveillance numérique des employés
    ("employee_email_surveillance_rights_engine.py",
     "Surveillance des emails d'employés & vie privée au travail", "Wave 961",
     "Employeurs lisant les emails professionnels et personnels sans politique de confidentialité transparente.",
     "EESR", "employee_email_surv"),
    ("location_tracking_employee_rights_engine.py",
     "Suivi GPS des employés & droit à la vie privée", "Wave 961",
     "Travailleurs suivis en temps réel par GPS sans consentement ni politique claire.",
     "LTER", "location_employee"),
    ("biometric_timeclock_employee_rights_engine.py",
     "Horloge biométrique au travail & droits BIPA des employés", "Wave 961",
     "Employeurs collectant empreintes digitales ou scans rétiniens sans consentement BIPA.",
     "BTCE", "biometric_timeclock"),

    # Wave 962 — Technologies de surveillance policière
    ("license_plate_reader_rights_engine.py",
     "Lecteurs de plaques automatisés & suivi des déplacements civils", "Wave 962",
     "Bases de données ALPR permettant de reconstituer les déplacements des citoyens sans mandat.",
     "LPRR", "alpr_surveillance"),
    ("cell_site_simulator_rights_engine.py",
     "Simulateurs de tours cellulaires & surveillance sans mandat", "Wave 962",
     "Police utilisant des IMSI catchers ciblant les téléphones sans mandat judiciaire.",
     "CSSR", "cell_simulator"),
    ("social_media_screening_employer_rights_engine.py",
     "Vérification des réseaux sociaux par les employeurs & discrimination", "Wave 962",
     "Employeurs refusant des candidats basés sur leurs opinions politiques ou activités en ligne.",
     "SMSE", "social_screen_employ"),

    # Wave 963 — IA & discrimination financière et médicale
    ("ai_credit_scoring_discrimination_rights_engine.py",
     "Scores de crédit IA & discrimination algorithmique raciale", "Wave 963",
     "Modèles IA de crédit reproduisant et amplifiant des biais raciaux historiques.",
     "ACSD", "ai_credit_discrim"),
    ("ai_insurance_pricing_algorithm_rights_engine.py",
     "Tarification IA des assurances & discrimination cachée", "Wave 963",
     "Algorithmes d'assurance utilisant des proxies raciaux pour fixer des primes discriminatoires.",
     "AISP", "ai_insurance_price"),
    ("health_app_data_sharing_rights_engine.py",
     "Applications santé & partage non consenti de données médicales", "Wave 963",
     "Applications santé vendant des données personnelles médicales à des tiers sans consentement clair.",
     "HADR", "health_app_data"),

    # Wave 964 — Santé numérique & vie privée médicale
    ("telemedicine_data_privacy_rights_engine.py",
     "Télémédecine & confidentialité des données de consultation", "Wave 964",
     "Plateformes de télémédecine partageant des données de consultation avec des partenaires publicitaires.",
     "TMDP", "telemed_privacy"),
    ("patient_portal_data_breach_rights_engine.py",
     "Brèches de données des portails patients & droits HIPAA", "Wave 964",
     "Violations de données de portails patients exposant les dossiers médicaux sans notification rapide.",
     "PPDB", "patient_portal_breach"),
    ("hospital_data_sale_patient_rights_engine.py",
     "Vente de données hospitalières & droits des patients", "Wave 964",
     "Hôpitaux vendant des données dé-identifiées de patients à des tiers sans leur consentement.",
     "HDSP", "hospital_data_sale"),

    # Wave 965 — Santé & droits au travail (maternité & conditions)
    ("disability_disclosure_work_rights_engine.py",
     "Divulgation de handicap au travail & représailles patronales", "Wave 965",
     "Travailleurs sanctionnés après avoir divulgué un handicap à leur employeur en cherchant un aménagement.",
     "DDWR", "disability_disclose"),
    ("chronic_illness_workplace_rights_engine.py",
     "Maladies chroniques & droits aux aménagements raisonnables", "Wave 965",
     "Employés souffrant de maladies chroniques refusés d'aménagements légaux et menacés de licenciement.",
     "CIWR", "chronic_illness_work"),
    ("lactation_break_work_rights_engine.py",
     "Pauses d'allaitement au travail & refus patronaux", "Wave 965",
     "Mères allaitantes privées de pauses ou d'espace approprié pour tirer leur lait au travail.",
     "LBWR", "lactation_break"),

    # Wave 966 — Travailleurs agricoles saisonniers & H-2A
    ("agricultural_h2a_visa_rights_engine.py",
     "Visa H-2A & exploitation des travailleurs agricoles saisonniers", "Wave 966",
     "Travailleurs H-2A liés à un seul employeur, exposés à l'exploitation sans recours légal effectif.",
     "AVHA", "h2a_visa"),
    ("farm_labor_contractor_abuse_rights_engine.py",
     "Sous-traitants de main-d'œuvre agricole & abus systémiques", "Wave 966",
     "Sous-traitants agricoles pratiquant le vol de salaire, loyers abusifs et intimidation sans responsabilité.",
     "FLCA", "farm_labor_contractor"),
    ("us_farm_child_labor_exemption_rights_engine.py",
     "Exemptions agricoles FLSA & travail des enfants dans les fermes", "Wave 966",
     "Loi FLSA permettant aux enfants de travailler dans des conditions dangereuses dans l'agriculture.",
     "AGCE", "farm_child_exempt"),

    # Wave 967 — Travailleurs d'entrepôts & centres de distribution
    ("warehouse_worker_quota_rights_engine.py",
     "Quotas de travail en entrepôts & épuisement des travailleurs", "Wave 967",
     "Travailleurs d'entrepôts imposés des quotas inhumains conduisant à des blessures et épuisement.",
     "WWQR", "warehouse_quota"),
    ("fulfillment_center_injury_rights_engine.py",
     "Blessures dans les centres de distribution & sous-déclaration", "Wave 967",
     "Taux de blessures élevés dans les centres de fulfillment masqués par la pression contre le signalement.",
     "FCIR", "fulfillment_injury"),
    ("warehouse_heat_rights_engine.py",
     "Chaleur extrême dans les entrepôts & absence de protection légale", "Wave 967",
     "Travailleurs d'entrepôts sans climatisation exposés à des températures mortelles en l'absence de loi fédérale.",
     "WHRR", "warehouse_heat"),

    # Wave 968 — Santé dentaire, vision & soins préventifs
    ("dental_access_low_income_adult_rights_engine.py",
     "Accès dentaire adultes à faibles revenus & lacunes Medicaid", "Wave 968",
     "Adultes à faibles revenus sans couverture dentaire Medicaid souffrant de maladies buccales chroniques.",
     "DALA", "dental_adult_low"),
    ("vision_care_insurance_gap_rights_engine.py",
     "Couverture d'assurance vision & lacunes de soins oculaires", "Wave 968",
     "Patients perdant la vue faute de couverture d'assurance pour les examens et lunettes préventifs.",
     "VCIG", "vision_insur_gap"),
    ("preventive_care_insurance_rights_engine.py",
     "Soins préventifs obligatoires & résistance des assureurs", "Wave 968",
     "Assureurs refusant de couvrir les soins préventifs recommandés malgré les obligations légales ACA.",
     "PCIR", "preventive_care"),
]
