# Specs waves 801-808 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 801 — Maladies tropicales négligées II
    ("trachoma_blindness_prevention_rights_engine.py",
     "Trachome & cécité évitable", "Wave 801",
     "Trachome bactérien rendant aveugle faute d'hygiène et d'antibiotiques accessibles.",
     "TRCH", "trachoma"),
    ("river_blindness_onchocerciasis_rights_engine.py",
     "Cécité des rivières & onchocercose", "Wave 801",
     "Onchocercose rendant aveugle les communautés riveraines des fleuves africains.",
     "RVBL", "river_blindness"),
    ("guinea_worm_eradication_rights_engine.py",
     "Ver de Guinée & éradication incomplète", "Wave 801",
     "Populations encore atteintes du ver de Guinée, maladie en voie d'éradication mais persistante.",
     "GUWM", "guinea_worm"),

    # Wave 802 — Maladies infectieuses & prévention
    ("sleeping_sickness_tsetse_rights_engine.py",
     "Maladie du sommeil & trypanosomiase", "Wave 802",
     "Trypanosomiase africaine mortelle frappant les zones rurales sans diagnostic ni traitement.",
     "SLEP", "sleeping_sickness"),
    ("rabies_prevention_access_rights_engine.py",
     "Rage & accès à la prophylaxie post-exposition", "Wave 802",
     "Victimes de morsures mourantes faute d'accès aux vaccins antirabiques.",
     "RABV", "rabies_prevention"),
    ("kala_azar_visceral_leishmaniasis_rights_engine.py",
     "Kala-azar & leishmaniose viscérale", "Wave 802",
     "Leishmaniose viscérale fatale dans les zones pauvres ignorées des politiques de santé.",
     "KALA", "kala_azar"),

    # Wave 803 — Carences & dépistage néonatal
    ("hookworm_soil_transmitted_rights_engine.py",
     "Ankylostome & helminthes transmis par le sol", "Wave 803",
     "Parasites intestinaux anémiant les enfants et bloquant développement cognitif et physique.",
     "HOOK", "hookworm"),
    ("maternal_anaemia_nutrition_rights_engine.py",
     "Anémie maternelle & malnutrition", "Wave 803",
     "Anémie pendant la grossesse tuant mères et nouveau-nés faute de fer et de suivi.",
     "MANA", "maternal_anaemia"),
    ("sickle_cell_screening_treatment_rights_engine.py",
     "Drépanocytose & dépistage néonatal", "Wave 803",
     "Nouveau-nés drépanocytaires mourant faute de dépistage néonatal et de traitement.",
     "SICK", "sickle_cell"),

    # Wave 804 — Santé mentale communautaire
    ("mental_health_gap_rural_rights_engine.py",
     "Désert psychiatrique rural", "Wave 804",
     "Populations rurales sans psychiatre ni psychologue, livrées à l'isolement.",
     "MHGR", "mh_rural_gap"),
    ("psychosis_street_homeless_rights_engine.py",
     "Psychose & sans-abrisme", "Wave 804",
     "Personnes psychotiques sans abri cyclant entre rue, urgences et prison sans soins.",
     "PSST", "psychosis_street"),
    ("youth_suicide_indigenous_rights_engine.py",
     "Suicide des jeunes autochtones", "Wave 804",
     "Taux de suicide catastrophiques chez les jeunes autochtones privés de perspectives.",
     "YSIN", "youth_indigenous_suicide"),

    # Wave 805 — Identité, orientation & corps
    ("conversion_therapy_ban_rights_engine.py",
     "Thérapies de conversion & interdiction", "Wave 805",
     "Pratiques visant à changer l'orientation ou l'identité de genre, sources de trauma.",
     "CTHB", "conversion_therapy"),
    ("intersex_surgery_consent_rights_engine.py",
     "Chirurgie intersexe sans consentement", "Wave 805",
     "Nourrissons intersexes opérés sans urgence médicale ni consentement éclairé.",
     "IXSU", "intersex_surgery"),
    ("elder_suicide_isolation_rights_engine.py",
     "Suicide des personnes âgées & isolement", "Wave 805",
     "Personnes âgées isolées en proie à la dépression et au suicide invisible.",
     "ESIN", "elder_isolation_suicide"),

    # Wave 806 — Menstruation, stigmate & exclusion
    ("menstruation_stigma_exclusion_rights_engine.py",
     "Tabou menstruel & exclusion sociale", "Wave 806",
     "Femmes et filles exclues de la vie sociale et religieuse pendant leurs règles.",
     "MENS", "menstruation_stigma"),
    ("period_poverty_school_dropout_rights_engine.py",
     "Précarité menstruelle & décrochage scolaire", "Wave 806",
     "Filles abandonnant l'école faute d'accès à des protections hygiéniques.",
     "PPSC", "period_poverty"),
    ("witch_accusation_community_violence_rights_engine.py",
     "Accusations de sorcellerie & violences communautaires", "Wave 806",
     "Personnes lynchées ou exilées sur accusation de sorcellerie sans recours judiciaire.",
     "WACT", "witch_accusation"),

    # Wave 807 — Corps stigmatisés & minorités visibles
    ("albinism_attack_body_parts_rights_engine.py",
     "Albinisme & mutilations rituelles", "Wave 807",
     "Personnes albinos attaquées pour leurs membres utilisés dans des rituels.",
     "ALAT", "albinism_attack"),
    ("bone_harvesting_body_trafficking_rights_engine.py",
     "Trafic d'organes osseux & prélèvement non consenti", "Wave 807",
     "Prélèvements osseux non consentis sur des cadavres pour le commerce médical.",
     "BOHA", "bone_harvesting"),
    ("vitiligo_stigma_employment_rights_engine.py",
     "Vitiligo & discrimination à l'emploi", "Wave 807",
     "Personnes atteintes de vitiligo discriminées à l'embauche et dans la vie sociale.",
     "VTST", "vitiligo_stigma"),

    # Wave 808 — Handicap physique & accès aux droits
    ("dwarfism_discrimination_employment_rights_engine.py",
     "Nanisme & discrimination à l'emploi", "Wave 808",
     "Personnes de petite taille confrontées au rejet professionnel et aux moqueries systémiques.",
     "DWDI", "dwarfism_discrimination"),
    ("newborn_screening_rare_disease_rights_engine.py",
     "Dépistage néonatal & maladies rares", "Wave 808",
     "Nouveau-nés non dépistés pour des maladies rares traitables dès la naissance.",
     "NBSC", "newborn_rare_screening"),
    ("burn_survivor_scar_rehabilitation_rights_engine.py",
     "Brûlés & réhabilitation des cicatrices", "Wave 808",
     "Survivants de brûlures graves sans accès à la chirurgie reconstructrice ni au soutien psychologique.",
     "BSSR", "burn_survivor"),
]
