# Specs waves 1241-1248 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1241 — Finance: assurance & prêts (inédits)
    ("ssdi_disability_hearing_wait_rights_engine.py",
     "Délais d'attente pour les audiences d'invalidité SSDI & droits des demandeurs à une décision rapide de l'ALJ", "Wave 1241",
     "Demandeurs d'invalidité SSDI attendant 18 à 24 mois pour une audience d'ALJ sans revenus pendant que leur appel est en attente.",
     "SSDA", "ssdi_hearing_wait"),
    ("mortgage_loan_modification_rights_engine.py",
     "Droits à la modification de prêt hypothécaire & obstacles des prestataires refusant de modifier des prêts en souffrance", "Wave 1241",
     "Propriétaires en défaut cherchant une modification de prêt confrontés à des prestataires perdant des documents et ignorant les demandes.",
     "MLRM", "mortgage_loan_mod"),
    ("college_athlete_transfer_portal_rights_engine.py",
     "Droits des athlètes universitaires dans le portail de transfert & restrictions NCAA sur l'éligibilité immédiate", "Wave 1241",
     "Athlètes universitaires transférant vers de nouveaux établissements confrontés à des restrictions d'éligibilité de la NCAA malgré les réformes.",
     "CATF", "athlete_transfer_port"),

    # Wave 1242 — Logement: animaux & associations (inédits)
    ("emotional_support_animal_housing_rights_engine.py",
     "Animaux de soutien émotionnel dans les logements avec no-pets policy & droits FHA à un logement adapté sans frais supplémentaires", "Wave 1242",
     "Personnes avec troubles mentaux se voyant refuser un ESA ou facturer des frais pour animaux dans des logements avec politique no-pets.",
     "ESAH", "esa_housing_rights"),
    ("hoa_board_election_dispute_rights_engine.py",
     "Litiges lors d'élections de conseils HOA & droits des membres à des processus électoraux transparents et contestables", "Wave 1242",
     "Propriétaires contestant des élections de conseil HOA entachées d'irrégularités sans mécanisme d'appel indépendant accessible.",
     "HOAD", "hoa_board_election"),
    ("hoa_fine_dispute_rights_engine.py",
     "Droits de contestation des amendes HOA & absence de procédure d'appel équitable dans de nombreuses associations", "Wave 1242",
     "Propriétaires recevant des amendes HOA pour des infractions mineures sans audience équitable ni possibilité de présenter leur défense.",
     "NLIL", "hoa_fine_dispute"),

    # Wave 1243 — Justice: audiences & recours (inédits)
    ("mortgage_foreclosure_mediation_rights_engine.py",
     "Programmes de médiation pour les saisies immobilières & droits des propriétaires à une médiation obligatoire avant saisie", "Wave 1243",
     "Propriétaires en défaut dans des États sans médiation obligatoire perdant leur maison sans possibilité de négocier une alternative.",
     "MOCF", "foreclos_mediation"),
    ("government_benefit_appeal_hearing_rights_engine.py",
     "Droits d'appel des décisions de prestations gouvernementales & retards dans les auditions de sécurité sociale et Medicaid", "Wave 1243",
     "Bénéficiaires de programmes gouvernementaux ayant des prestations refusées ou supprimées sans audience d'appel dans un délai raisonnable.",
     "GDWB", "gov_benefit_appeal"),
    ("immigration_court_backlog_rights_engine.py",
     "Arriéré des tribunaux d'immigration & droits des demandeurs à une décision dans un délai raisonnable après des années d'attente", "Wave 1243",
     "Demandeurs d'asile attendant 5 à 7 ans pour une audience devant un juge d'immigration en raison d'arriérés records.",
     "BPRC", "immigr_court_backlog"),

    # Wave 1244 — Santé: maladies neurales & mentales (inédits)
    ("multiple_sclerosis_treatment_access_rights_engine.py",
     "Accès aux thérapies modificatrices de la sclérose en plaques & refus d'assurance pour les traitements de haute efficacité", "Wave 1244",
     "Patients atteints de SEP se voyant refuser des thérapies de haute efficacité approuvées en faveur d'options moins efficaces moins coûteuses.",
     "MOFR", "ms_treatment_access"),
    ("veteran_brain_injury_disability_rights_engine.py",
     "Droits à la compensation pour traumatismes crâniens de vétérans & classification insuffisante des TBI par le département VA", "Wave 1244",
     "Vétérans avec traumatismes crâniens liés au service militaire se voyant refuser ou sous-évaluer leur compensation VA.",
     "VHSP", "vet_brain_injury"),
    ("adult_onset_hearing_loss_rights_engine.py",
     "Perte auditive à l'âge adulte & accès aux aides auditives couvertes sans exigences excessives et listes d'attente", "Wave 1244",
     "Adultes avec perte auditive sévère incapables d'accéder à des aides auditives couvertes en raison de critères d'assurance restrictifs.",
     "SMRT", "adult_hearing_loss"),

    # Wave 1245 — Emploi: droits & protections (inédits)
    ("at_will_employment_exception_rights_engine.py",
     "Exceptions légales à l'emploi at-will & droits des employés contre les licenciements violant l'ordre public", "Wave 1245",
     "Employés licenciés en représailles d'une action protégée dans des États at-will sans accès aux protections légales fédérales.",
     "ADGA", "at_will_exception"),
    ("non_compete_agreement_low_wage_rights_engine.py",
     "Accords de non-concurrence imposés aux travailleurs à faibles revenus & restrictions abusives à la mobilité professionnelle", "Wave 1245",
     "Travailleurs à faibles salaires dans la restauration ou le commerce liés par des accords de non-concurrence les empêchant de changer d'emploi.",
     "BFRS", "noncompete_lowwage"),
    ("coworker_harassment_employer_liability_rights_engine.py",
     "Responsabilité patronale pour le harcèlement entre collègues & droits des victimes quand l'employeur connaissait le comportement", "Wave 1245",
     "Victimes de harcèlement par des collègues dont les employeurs connaissant les faits n'ont pas agi, engageant leur responsabilité légale.",
     "LACP", "coworker_harass"),

    # Wave 1246 — Technologie: manipulation & plateformes (inédits)
    ("algorithmic_content_moderation_appeal_rights_engine.py",
     "Droits d'appel contre la modération de contenu algorithmique & suppressions automatisées injustifiées de comptes légaux", "Wave 1246",
     "Utilisateurs de plateformes dont les comptes ou contenus légaux sont supprimés par algorithmes sans notification ni recours effectif.",
     "NTPR", "algo_content_appeal"),
    ("dark_pattern_consent_manipulation_rights_engine.py",
     "Manipulation du consentement par les dark patterns numériques & droits des utilisateurs à une décision de privacy non truquée", "Wave 1246",
     "Consommateurs trompés par des interfaces délibérément confusantes qui rendent le refus du partage de données plus difficile que l'acceptation.",
     "CTNB", "dark_pattern_consent"),
    ("subscription_trap_auto_renewal_rights_engine.py",
     "Pièges des abonnements avec renouvellement automatique opaque & droits à la résiliation simple et remboursement partiel", "Wave 1246",
     "Consommateurs piégés dans des abonnements automatiquement renouvelés dont le processus de résiliation est délibérément complexifié.",
     "APGA", "subscript_trap"),

    # Wave 1247 — Santé: accès & équité (inédits)
    ("doula_medicaid_coverage_rights_engine.py",
     "Couverture Medicaid pour les services de doula & droits des femmes enceintes défavorisées à un soutien continu à la naissance", "Wave 1247",
     "Femmes enceintes à faibles revenus dans des États sans couverture Medicaid pour les doulas accouchant sans soutien de naissance.",
     "DRME", "doula_medicaid"),
    ("peer_support_specialist_insurance_rights_engine.py",
     "Remboursement des spécialistes en soutien par les pairs & droits des patients en rétablissement à ce service de santé mentale", "Wave 1247",
     "Personnes en rétablissement cherchant des services de soutien par les pairs non couverts par leur assurance malgré leur efficacité prouvée.",
     "PSRR", "peer_support_insur"),
    ("community_health_worker_coverage_rights_engine.py",
     "Couverture des agents de santé communautaires & droits des communautés sous-desservies à ce pont de santé publique financé", "Wave 1247",
     "Patients des communautés défavorisées privés d'accès aux agents de santé communautaires dans des États sans financement Medicaid.",
     "PCWR", "community_health_work"),

    # Wave 1248 — Droits divers: accès & protection (inédits)
    ("disability_parking_placard_theft_rights_engine.py",
     "Vol et usage abusif des plaques de stationnement handicapé & droits des personnes handicapées à un remplacement facile", "Wave 1248",
     "Personnes handicapées victimes de vol ou de perte de leur plaque de stationnement confrontées à un long processus de remplacement.",
     "DPRD", "disab_placard_theft"),
    ("naturalization_oath_disability_rights_engine.py",
     "Adaptations pour la cérémonie de naturalisation pour personnes handicapées & droits à la procédure même avec capacité cognitive réduite", "Wave 1248",
     "Immigrants avec handicap cognitif ou physique cherchant à être naturalisés confrontés à des barrières dans les procédures standard.",
     "NLTR", "natural_disab_oath"),
    ("gig_worker_safety_injury_rights_engine.py",
     "Sécurité et blessures au travail des travailleurs de plateforme & absence de couverture accidents du travail pour les gig workers", "Wave 1248",
     "Livreurs et chauffeurs de plateforme blessés en service sans couverture workers compensation en tant que travailleurs indépendants.",
     "GCRS", "gig_worker_injury"),
]
