# Specs waves 1345-1352 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Correction: CCDF pris par credit_card_deceptive_fee → CSDF (condo structural defect)
SPECS = [
    # Wave 1345 — Santé: dispositifs médicaux & fournitures (inédits)
    ("ostomy_supply_insurance_coverage_rights_engine.py",
     "Couverture d'assurance des fournitures de stomie & droits des patients stomisés à des quantités adéquates de poches et accessoires sans plafonds arbitraires compromettant l'hygiène", "Wave 1345",
     "Patients porteurs d'une stomie se voyant rationner leurs poches et barrières cutanées par leur assurance en deçà du nombre médicalement nécessaire pour des soins hygiéniques.",
     "OSTC", "ostomy_supply_cover"),
    ("power_wheelchair_prior_authorization_rights_engine.py",
     "Autorisation préalable des fauteuils roulants électriques & droits des personnes à mobilité réduite à un équipement adapté sans délais d'approbation excessifs ni refus injustifiés", "Wave 1345",
     "Personnes à mobilité sévèrement réduite attendant des mois l'autorisation préalable d'un fauteuil roulant électrique médicalement nécessaire à leur autonomie quotidienne.",
     "PWPA", "power_wheelchair_auth"),
    ("home_oxygen_therapy_coverage_rights_engine.py",
     "Couverture de l'oxygénothérapie à domicile & droits des patients atteints de maladies respiratoires chroniques à un approvisionnement continu sans interruptions liées aux exigences de requalification", "Wave 1345",
     "Patients dépendants d'oxygène à domicile subissant des interruptions d'approvisionnement en raison d'exigences de requalification répétées et de changements de fournisseurs imposés.",
     "HOTC", "home_oxygen_therapy"),

    # Wave 1346 — Logement: copropriété & infrastructure (inédits)
    ("condo_construction_defect_rights_engine.py",
     "Vices de construction dans les copropriétés neuves & droits des copropriétaires à des réparations par le promoteur et à des recours collectifs pour défauts structurels cachés", "Wave 1346",
     "Copropriétaires de condominiums neufs découvrant des défauts structurels majeurs après expiration des garanties, le promoteur refusant toute responsabilité pour les réparations coûteuses.",
     "CSDF", "condo_construct_defect"),
    ("cooperative_housing_share_loan_rights_engine.py",
     "Prêts sur parts de coopératives d'habitation & droits des résidents coopérateurs à un financement équitable et à une protection contre les saisies de parts sans procédure régulière", "Wave 1346",
     "Résidents de coopératives d'habitation incapables d'obtenir un financement abordable pour leurs parts ou menacés de perte de logement lors de difficultés de paiement sans protection adéquate.",
     "CHSL", "coop_housing_share"),
    ("hoa_architectural_review_abuse_rights_engine.py",
     "Abus des comités de revue architecturale des HOA & droits des propriétaires à des décisions cohérentes, transparentes et non arbitraires sur les modifications de leur propriété", "Wave 1346",
     "Propriétaires dans des associations HOA confrontés à des refus arbitraires et incohérents de leurs demandes de modification par des comités architecturaux sans critères clairs ni recours.",
     "HARA", "hoa_architect_review"),

    # Wave 1347 — Finance: assurance-vie & rentes (inédits)
    ("life_insurance_claim_denial_rights_engine.py",
     "Refus de réclamations d'assurance-vie & droits des bénéficiaires à recevoir les capitaux décès sans refus abusifs fondés sur des erreurs techniques ou des contestations tardives", "Wave 1347",
     "Bénéficiaires d'assurance-vie se voyant refuser le versement du capital décès en raison d'omissions mineures dans la demande originale ou de contestations de la cause du décès.",
     "LICD", "life_insur_claim_deny"),
    ("annuity_surrender_charge_rights_engine.py",
     "Frais de rachat des rentes différées & droits des souscripteurs âgés à comprendre les pénalités de retrait anticipé avant de souscrire des produits à frais de sortie élevés", "Wave 1347",
     "Personnes âgées ayant investi dans des rentes différées découvrant des frais de rachat punitifs les empêchant d'accéder à leur propre épargne en cas d'urgence médicale.",
     "ANSC", "annuity_surrender"),
    ("unclaimed_property_recovery_rights_engine.py",
     "Récupération des biens non réclamés détenus par les États & droits des citoyens à retrouver et récupérer leurs fonds dormants sans frais de localisation prédateurs", "Wave 1347",
     "Personnes ignorant que des comptes bancaires dormants, chèques non encaissés ou dépôts oubliés leur appartenant sont détenus par l'État, ciblées par des localisateurs facturant des commissions excessives.",
     "UCPR", "unclaimed_property"),

    # Wave 1348 — Travail: classification & avantages (inédits)
    ("salaried_overtime_misclassification_rights_engine.py",
     "Mauvaise classification des salariés exemptés d'heures supplémentaires & droits des travailleurs incorrectement classés comme exemptés à percevoir les heures supplémentaires dues", "Wave 1348",
     "Travailleurs classés à tort comme cadres exemptés d'heures supplémentaires effectuant un travail non qualifiant, privés de la rémunération majorée à laquelle ils ont légalement droit.",
     "SOMC", "salaried_ot_misclass"),
    ("unpaid_volunteer_labor_nonprofit_rights_engine.py",
     "Travail bénévole non rémunéré dans les organisations & droits des bénévoles à ne pas remplacer des postes salariés et à être rémunérés quand ils effectuent un travail d'employé", "Wave 1348",
     "Personnes recrutées comme bénévoles par des organisations à but lucratif déguisées ou effectuant un travail qui devrait être rémunéré selon les critères FLSA du volontariat légitime.",
     "UVLN", "unpaid_volunteer_labor"),
    ("employee_stock_purchase_plan_rights_engine.py",
     "Plans d'achat d'actions des employés ESPP & droits des travailleurs à une information claire sur les périodes d'achat, décotes et implications fiscales sans pièges contractuels cachés", "Wave 1348",
     "Employés participant à des plans ESPP perdant des avantages en raison d'une mauvaise compréhension des périodes de détention, des retenues sur salaire et des conséquences fiscales non divulguées.",
     "ESPP", "employee_stock_purchase"),

    # Wave 1349 — Immigration: humanitaire spécialisé (inédits)
    ("vawa_self_petition_abuse_rights_engine.py",
     "Auto-pétition VAWA pour les victimes de violences conjugales & droits des conjoints, enfants et parents maltraités à demander un statut légal indépendamment de l'agresseur citoyen", "Wave 1349",
     "Conjoints non documentés victimes de violences de la part de leur partenaire citoyen américain ignorant leur droit à une auto-pétition VAWA pour obtenir un statut légal indépendant.",
     "VWSP", "vawa_self_petition"),
    ("asylum_one_year_filing_deadline_rights_engine.py",
     "Délai d'un an pour le dépôt des demandes d'asile & droits des demandeurs à invoquer des exceptions pour circonstances exceptionnelles ou changées ayant retardé leur demande", "Wave 1349",
     "Demandeurs d'asile dont la demande est refusée pour avoir manqué le délai d'un an malgré des circonstances comme un traumatisme, une maladie ou un changement de conditions dans leur pays.",
     "AOYD", "asylum_one_year"),
    ("asylum_work_permit_waiting_clock_rights_engine.py",
     "Horloge d'attente du permis de travail pour demandeurs d'asile & droits des requérants à obtenir une autorisation d'emploi dans des délais raisonnables pendant l'examen de leur demande", "Wave 1349",
     "Demandeurs d'asile incapables de travailler légalement pendant des mois en raison des règles d'horloge d'attente et des retards de traitement de leur autorisation d'emploi initiale.",
     "AWPC", "asylum_work_clock"),

    # Wave 1350 — Éducation: financement & dette (inédits)
    ("pell_grant_eligibility_restoration_rights_engine.py",
     "Rétablissement de l'éligibilité aux bourses Pell & droits des étudiants à faibles revenus à récupérer leur aide financière après une interruption ou une perte temporaire d'éligibilité", "Wave 1350",
     "Étudiants à faibles revenus perdant leur bourse Pell pour des raisons administratives ou de progression académique sans connaître les voies de rétablissement de leur éligibilité.",
     "PGER", "pell_grant_restore"),
    ("title_iv_funds_return_withdrawal_rights_engine.py",
     "Retour des fonds Title IV lors d'un abandon d'études & droits des étudiants à un calcul équitable des fonds dus et à une protection contre les dettes injustifiées après retrait", "Wave 1350",
     "Étudiants abandonnant leurs études en cours de semestre confrontés à des factures soudaines de remboursement de fonds Title IV mal calculées par leur établissement.",
     "TIVR", "title_iv_return"),
    ("ap_exam_fee_waiver_low_income_rights_engine.py",
     "Dispenses de frais d'examens AP pour les élèves à faibles revenus & droits des lycéens défavorisés à passer les examens d'éducation avancée sans barrière financière", "Wave 1350",
     "Élèves de familles à faibles revenus inscrits à des cours Advanced Placement incapables de payer les frais d'examen, perdant la chance d'obtenir des crédits universitaires.",
     "APFW", "ap_exam_fee_waiver"),

    # Wave 1351 — Santé mentale: enfants & jeunes (inédits)
    ("youth_residential_treatment_oversight_rights_engine.py",
     "Surveillance des établissements de traitement résidentiel pour jeunes & droits des mineurs placés à une protection contre les abus, contentions excessives et placements injustifiés", "Wave 1351",
     "Jeunes placés dans des établissements de traitement résidentiel comportementaux subissant des contentions abusives, isolements et négligences sans surveillance externe adéquate.",
     "YRTO", "youth_residential_treat"),
    ("school_based_mental_health_access_rights_engine.py",
     "Accès aux services de santé mentale en milieu scolaire & droits des élèves à des conseillers, psychologues et soutien psychologique disponibles sans ratios élèves-professionnels excessifs", "Wave 1351",
     "Élèves en détresse psychologique dans des écoles sans conseillers en nombre suffisant, avec des ratios de centaines d'élèves par psychologue scolaire empêchant un soutien réel.",
     "SBMH", "school_mental_health"),
    ("pediatric_psychiatric_boarding_rights_engine.py",
     "Hébergement prolongé en urgences des enfants en crise psychiatrique & droits des mineurs à un placement rapide en soins adaptés sans attente de plusieurs jours aux urgences", "Wave 1351",
     "Enfants en crise psychiatrique restant bloqués des jours voire des semaines dans des services d'urgence faute de lits psychiatriques pédiatriques disponibles dans leur région.",
     "PPBR", "pediatric_psych_board"),

    # Wave 1352 — Droits: technologie & accès numérique (inédits)
    ("algorithmic_benefit_denial_appeal_rights_engine.py",
     "Appel des refus de prestations décidés par algorithme & droits des bénéficiaires à une explication humaine et à un recours quand un système automatisé réduit ou supprime leurs aides", "Wave 1352",
     "Bénéficiaires d'aides sociales voyant leurs prestations réduites ou supprimées par des systèmes algorithmiques opaques sans explication compréhensible ni voie de recours humaine réelle.",
     "ABDA", "algo_benefit_appeal"),
    ("digital_government_id_exclusion_rights_engine.py",
     "Exclusion par les identifiants numériques gouvernementaux & droits des personnes sans smartphone ou compétences numériques à accéder aux services publics par des voies alternatives", "Wave 1352",
     "Personnes âgées, à faibles revenus ou sans accès numérique exclues des services gouvernementaux exigeant une identité numérique, un smartphone ou une vérification en ligne obligatoire.",
     "DGIE", "digital_id_exclusion"),
    ("captcha_accessibility_disability_rights_engine.py",
     "Accessibilité des CAPTCHA pour les personnes handicapées & droits des utilisateurs aveugles, malvoyants ou avec troubles cognitifs à accéder aux services en ligne sans barrières de vérification", "Wave 1352",
     "Personnes aveugles, malvoyantes ou avec handicaps cognitifs incapables de compléter des CAPTCHA visuels ou auditifs, bloquées de l'accès à des services en ligne essentiels.",
     "CADR", "captcha_accessibility"),
]
