# Specs waves 929-936 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 929 — LGBTQ+ élèves & discrimination scolaire
    ("trans_student_bathroom_rights_engine.py",
     "Élèves trans & accès aux toilettes scolaires", "Wave 929",
     "Élèves transgenres forcés d'utiliser des toilettes contraires à leur identité de genre.",
     "TSBR", "trans_school_bath"),
    ("gay_straight_alliance_club_rights_engine.py",
     "Clubs GSA & interdictions scolaires", "Wave 929",
     "Clubs Gay-Straight Alliance interdits ou sabotés dans des établissements secondaires.",
     "GSAC", "gsa_club"),
    ("lgbtq_school_counselor_rights_engine.py",
     "Conseillers scolaires LGBTQ+ & refus d'affirmation", "Wave 929",
     "Conseillers scolaires refusant d'affirmer l'identité LGBTQ+ des élèves en crise.",
     "LQSC", "lgbtq_counselor"),

    # Wave 930 — Harcèlement scolaire & Title IX
    ("school_bullying_victim_rights_engine.py",
     "Harcèlement scolaire & droits des victimes", "Wave 930",
     "Élèves harcelés sans intervention efficace de l'école malgré des signalements répétés.",
     "SBVR", "school_bully_victim"),
    ("peer_sexual_harassment_school_rights_engine.py",
     "Harcèlement sexuel entre pairs à l'école", "Wave 930",
     "Élèves victimes de harcèlement sexuel de camarades sans protection scolaire adéquate.",
     "PSHS", "peer_sexual_harass"),
    ("title_ix_school_response_rights_engine.py",
     "Title IX & défaillance scolaire face au harcèlement", "Wave 930",
     "Écoles violant le Title IX en ignorant les plaintes de harcèlement sexuel des élèves.",
     "TIXR", "title_ix_response"),

    # Wave 931 — Enfants non documentés & droits éducatifs
    ("undocumented_child_school_rights_engine.py",
     "Enfants non documentés & droit à l'éducation publique", "Wave 931",
     "Enfants sans papiers exclus ou intimidés lors de l'inscription scolaire malgré Plyler v. Doe.",
     "UDCS", "undoc_child_school"),
    ("daca_student_higher_ed_rights_engine.py",
     "Étudiants DACA & accès aux universités publiques", "Wave 931",
     "Étudiants DACA refusés dans les universités publiques ou privés de frais de résidence.",
     "DACS", "daca_higher_ed"),
    ("immigrant_youth_ell_rights_engine.py",
     "Jeunes immigrants & services linguistiques scolaires insuffisants", "Wave 931",
     "Élèves immigrants sans services ELL adéquats perdant du terrain académique par manque de soutien.",
     "IELL", "immigrant_ell"),

    # Wave 932 — Handicap, technologie d'assistance & inclusion
    ("assistive_technology_iep_rights_engine.py",
     "Technologies d'assistance & plans IEP refusés", "Wave 932",
     "Élèves handicapés privés de technologies d'assistance essentielles malgré leur droit légal.",
     "ATIP", "assistive_tech_iep"),
    ("deaf_interpreter_school_rights_engine.py",
     "Interprètes pour élèves sourds & droits scolaires", "Wave 932",
     "Élèves sourds sans interprète qualifié en classe, violant leurs droits IDEA et ADA.",
     "DISR", "deaf_interpreter"),
    ("blind_student_material_rights_engine.py",
     "Élèves aveugles & matériels adaptés scolaires refusés", "Wave 932",
     "Élèves malvoyants privés de matériels en braille ou en grands caractères par manque de ressources.",
     "BSMR", "blind_materials"),

    # Wave 933 — Bibliothèques scolaires & censure curriculaire
    ("school_library_book_ban_rights_engine.py",
     "Bibliothèques scolaires & interdiction de livres", "Wave 933",
     "Livres retirés des bibliothèques scolaires pour leur contenu LGBTQ+, racial ou politique.",
     "SCBB", "school_book_ban"),
    ("critical_race_theory_curriculum_rights_engine.py",
     "Théorie critique de la race & censure curriculaire", "Wave 933",
     "Enseignants sanctionnés pour avoir abordé l'histoire raciale sous pression de lois anti-CRT.",
     "CRTC", "crt_curriculum"),
    ("sex_education_censorship_rights_engine.py",
     "Éducation sexuelle & censure dans les écoles publiques", "Wave 933",
     "Programmes d'éducation sexuelle complets supprimés au profit de curricula abstinence-only.",
     "SEXC", "sex_ed_censor"),

    # Wave 934 — Élèves sans domicile & enfants placés
    ("homeless_student_school_rights_engine.py",
     "Élèves sans domicile & droit à la continuité scolaire", "Wave 934",
     "Élèves sans domicile fixe forcés de changer d'école, violant le McKinney-Vento Homeless Act.",
     "HSSR", "homeless_student"),
    ("foster_care_school_transfer_rights_engine.py",
     "Enfants placés & transferts scolaires répétés", "Wave 934",
     "Enfants en famille d'accueil changeant d'école à chaque placement, sans continuité éducative.",
     "FCST", "foster_school"),
    ("runaway_youth_education_rights_engine.py",
     "Jeunes fugueurs & accès à l'éducation formelle", "Wave 934",
     "Jeunes fugueurs sans tuteur légal incapables de s'inscrire à l'école sans consentement parental.",
     "RYSE", "runaway_youth_ed"),

    # Wave 935 — Religion, créationnisme & école publique
    ("school_prayer_coercion_rights_engine.py",
     "Prière à l'école publique & coercition religieuse", "Wave 935",
     "Élèves non religieux contraints à des prières ou pratiques religieuses dans les écoles publiques.",
     "SPRC", "school_prayer"),
    ("creationism_public_school_rights_engine.py",
     "Créationnisme dans les écoles publiques & laïcité", "Wave 935",
     "Enseignement du créationnisme comme alternative à l'évolution dans les écoles publiques.",
     "CPSM", "creationism_school"),
    ("religious_vaccine_exemption_school_rights_engine.py",
     "Exemptions vaccinales religieuses & santé scolaire", "Wave 935",
     "Exemptions religieuses vaccinales créant des risques sanitaires dans les communautés scolaires.",
     "REVS", "religious_vacc"),

    # Wave 936 — Données scolaires, domicile & droits parentaux
    ("school_record_ferpa_rights_engine.py",
     "Dossiers scolaires & confidentialité FERPA", "Wave 936",
     "Dossiers scolaires d'élèves partagés avec des tiers sans consentement parental requis par FERPA.",
     "SRPR", "school_ferpa"),
    ("homeschool_regulation_abuse_rights_engine.py",
     "Éducation à domicile & absence de contrôle des abus", "Wave 936",
     "Enfants éduqués à domicile exposés à des abus sans supervision ni signalement obligatoire.",
     "HSCR", "homeschool_abuse"),
    ("parent_school_notification_rights_engine.py",
     "Notification parentale & droits des familles à l'école", "Wave 936",
     "Parents non informés des incidents, sanctions disciplinaires ou changements scolaires affectant leur enfant.",
     "PNTR", "parent_notify"),
]
