# Specs waves 993-1000 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : PCDR→PTCD, LBDB→GLBD (0 collision après correction), 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 993 — Gouvernance locale & transparence démocratique
    ("local_election_recall_rights_engine.py",
     "Droit au recall des élus locaux & démocratie directe", "Wave 993",
     "Citoyens incapables de destituer des élus locaux corrompus faute de mécanismes de recall accessibles.",
     "LERR", "local_election_recall"),
    ("municipal_budget_transparency_rights_engine.py",
     "Transparence budgétaire municipale & droits des contribuables", "Wave 993",
     "Municipalités refusant de publier des budgets lisibles, privant les citoyens de tout contrôle démocratique.",
     "MBTR", "municipal_budget_transp"),
    ("zoning_board_corruption_rights_engine.py",
     "Corruption dans les commissions d'urbanisme & droits des résidents", "Wave 993",
     "Commissions de zonage locales accordant des variances à des promoteurs sans processus transparent.",
     "ZBCR", "zoning_board_corrupt"),

    # Wave 994 — Animaux de compagnie & droits familiaux
    ("pet_lease_predatory_rights_engine.py",
     "Location prédatrice d'animaux de compagnie & contrats abusifs", "Wave 994",
     "Acheteurs d'animaux piégés dans des contrats de location masqués comme ventes avec paiements exorbitants.",
     "PLPR", "pet_lease_predatory"),
    ("pet_custody_divorce_rights_engine.py",
     "Garde d'animaux lors de divorce & vide juridique", "Wave 994",
     "Animaux de compagnie traités comme biens meubles lors de divorces sans considération de leur bien-être.",
     "PTCD", "pet_custody_divorce"),
    ("veterinary_price_transparency_rights_engine.py",
     "Opacité tarifaire vétérinaire & droits des propriétaires d'animaux", "Wave 994",
     "Propriétaires d'animaux facturés des tarifs exorbitants sans devis préalable ni comparaison possible.",
     "VPTR", "vet_price_transp"),

    # Wave 995 — Droits LGBTQ+ spécifiques (inédits)
    ("lgbtq_elder_nursing_home_rights_engine.py",
     "Personnes LGBTQ+ âgées & discrimination en maisons de retraite", "Wave 995",
     "Résidents LGBTQ+ des maisons de retraite subissant harcèlement et refus de respect de leur identité.",
     "LGNR", "lgbtq_elder_nursing"),
    ("conversion_therapy_adult_ban_rights_engine.py",
     "Thérapies de conversion pour adultes & coercition familiale", "Wave 995",
     "Adultes LGBTQ+ contraints à des thérapies de conversion par pression familiale dans les États non protégés.",
     "CTAB", "conversion_therapy_adult"),
    ("lgbtq_blood_donation_rights_engine.py",
     "Restrictions de don de sang pour hommes ayant des rapports avec des hommes", "Wave 995",
     "Hommes gay encore soumis à des restrictions discriminatoires pour le don de sang malgré les tests modernes.",
     "GLBD", "lgbtq_blood_donate"),

    # Wave 996 — Travailleurs spécifiques sous-représentés
    ("car_wash_worker_exploitation_rights_engine.py",
     "Exploitation des travailleurs de lavage automobile & vol de salaire", "Wave 996",
     "Travailleurs de car washes payés en dessous du salaire minimum ou victimes de vol de salaire systématique.",
     "CWER", "car_wash_worker"),
    ("salon_worker_wage_theft_rights_engine.py",
     "Vol de salaire dans les salons de beauté & droits des travailleurs", "Wave 996",
     "Travailleurs de salons dépouillés de pourboires et payés en dessous du minimum légal par des propriétaires.",
     "SWVT", "salon_wage_theft"),
    ("hair_braider_licensing_rights_engine.py",
     "Licences excessives pour coiffeuses afro & barrières racistes", "Wave 996",
     "Tresseuses africaines et afro-américaines obligées de suivre 1500 heures de formation non pertinente.",
     "HBLR", "hair_braider_license"),

    # Wave 997 — Parentalité & protection de l'enfance (niches)
    ("paternity_leave_stigma_rights_engine.py",
     "Stigmatisation des pères prenant un congé parental & inégalité", "Wave 997",
     "Pères sanctionnés ou découragés de prendre leur congé parental par la culture d'entreprise et les managers.",
     "PLSR", "paternity_leave_stigma"),
    ("foster_parent_training_barrier_rights_engine.py",
     "Barrières administratives pour les parents d'accueil candidats", "Wave 997",
     "Candidats parents d'accueil abandonnant devant les exigences bureaucratiques excessives réduisant l'offre.",
     "FPBR", "foster_parent_barrier"),
    ("teen_parent_housing_rights_engine.py",
     "Logement des adolescentes mères & lacunes du système de protection", "Wave 997",
     "Mères adolescentes sans logement stable après la naissance, exclues des foyers étudiants et refuges.",
     "TCPR", "teen_parent_housing"),

    # Wave 998 — Eau & contaminants spécifiques (inédits)
    ("nitrate_agricultural_water_rights_engine.py",
     "Contamination nitrate par l'agriculture & eau potable rurale", "Wave 998",
     "Communautés rurales buvant une eau chargée en nitrates agricoles sans filtration ni compensation.",
     "NAWR", "nitrate_agri_water"),
    ("algae_bloom_drinking_water_rights_engine.py",
     "Cyanobactéries & algues toxiques dans l'eau potable municipale", "Wave 998",
     "Villes touchées par des proliférations d'algues toxiques dans les réservoirs sans alerte précoce.",
     "ALBW", "algae_bloom_water"),
    ("perchlorate_water_contamination_rights_engine.py",
     "Contamination perchlorate eau souterraine & sites militaires", "Wave 998",
     "Communautés proches de bases militaires buvant de l'eau contaminée au perchlorate sans réponse fédérale.",
     "PCWC", "perchlorate_water"),

    # Wave 999 — IA & décisions sociales critiques (inédits)
    ("ai_sentencing_recommendation_rights_engine.py",
     "Biais IA dans les recommandations de peine pénale", "Wave 999",
     "Juges s'appuyant sur des scores IA biaisés racialement pour des recommandations de peine non transparentes.",
     "ASRB", "ai_sentencing_bias"),
    ("ai_unemployment_fraud_detection_rights_engine.py",
     "Faux positifs IA dans la détection de fraude chômage & injustice", "Wave 999",
     "Bénéficiaires du chômage accusés à tort de fraude par des algorithmes défaillants sans recours humain.",
     "AUFD", "ai_unemployment_fraud"),
    ("ai_healthcare_rationing_rights_engine.py",
     "Rationnement des soins de santé par IA & discrimination cachée", "Wave 999",
     "Algorithmes hospitaliers refusant ou retardant des soins intensifs sur des critères opaques et biaisés.",
     "AHCR", "ai_health_ration"),

    # Wave 1000 — Justice historique & réparations (inédites)
    ("japanese_internment_property_rights_engine.py",
     "Propriétés perdues lors de l'internement japonais & restitution", "Wave 1000",
     "Familles japonaises-américaines n'ayant jamais récupéré leurs propriétés saisies lors de l'internement 1942.",
     "JIPR", "japanese_internment_prop"),
    ("tulsa_race_massacre_descendants_rights_engine.py",
     "Descendants du massacre de Tulsa 1921 & droits aux réparations", "Wave 1000",
     "Descendants de victimes du massacre de Greenwood/Tulsa sans réparations malgré des décennies de plaidoyer.",
     "TRMD", "tulsa_massacre_desc"),
    ("indigenous_allotment_land_loss_rights_engine.py",
     "Terres tribales perdues via le Dawes Act & restitution", "Wave 1000",
     "Nations indigènes ayant perdu des millions d'hectares via l'allotissement Dawes sans restitution légale.",
     "ILAL", "indigenous_allotment"),
]
