# Specs waves 953-960 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 953 — Droits financiers : crédit & dette foncière
    ("credit_report_error_rights_engine.py",
     "Erreurs dans les rapports de crédit & droits FCRA", "Wave 953",
     "Consommateurs victimes d'erreurs dans leurs rapports de crédit sans recours efficace sous la FCRA.",
     "CRER", "credit_report_error"),
    ("auto_loan_predatory_rights_engine.py",
     "Prêts automobiles abusifs & ciblage des minorités", "Wave 953",
     "Concessionnaires et prêteurs pratiquant des taux abusifs ciblant les minorités raciales.",
     "ALPR", "auto_loan_predatory"),
    ("tax_lien_home_seizure_rights_engine.py",
     "Saisie de domicile pour dettes fiscales & droits des propriétaires", "Wave 953",
     "Propriétaires perdant leur maison pour de petites dettes fiscales via des ventes de privilège fiscal.",
     "TLHS", "tax_lien_home"),

    # Wave 954 — Prêts étudiants & assurance santé
    ("student_loan_forgiveness_rights_engine.py",
     "Remise des prêts étudiants & obstacles bureaucratiques", "Wave 954",
     "Emprunteurs éligibles bloqués par des obstacles administratifs dans les programmes de remise.",
     "SLFR", "student_loan_forgive"),
    ("public_service_loan_forgiveness_rights_engine.py",
     "PSLF & refus de remise de prêt pour les agents publics", "Wave 954",
     "Agents publics et enseignants ayant cotisé 10 ans mais refusés au programme PSLF pour erreurs.",
     "PSFL", "pslf_denial"),
    ("insurance_claim_denial_rights_engine.py",
     "Refus d'indemnisation d'assurance & mauvaise foi des assureurs", "Wave 954",
     "Assureurs refusant systématiquement des sinistres légitimes pour préserver leurs bénéfices.",
     "ICDR", "insurance_claim_denial"),

    # Wave 955 — Fintech & droits des consommateurs numériques
    ("credit_card_deceptive_fee_rights_engine.py",
     "Frais de carte de crédit trompeurs & pratiques abusives", "Wave 955",
     "Émetteurs de cartes de crédit cachant des frais en petits caractères piégeant les consommateurs.",
     "CCDF", "credit_card_fee"),
    ("crypto_fraud_investor_rights_engine.py",
     "Fraudes crypto & droits des investisseurs non protégés", "Wave 955",
     "Investisseurs en cryptomonnaies victimes de fraudes sans protection réglementaire adéquate.",
     "CFIR", "crypto_fraud"),
    ("buy_here_pay_here_auto_rights_engine.py",
     "Concessionnaires BHPH & exploitation des acheteurs à crédit limité", "Wave 955",
     "Acheteurs à revenus modestes piégés dans des contrats BHPH à taux exorbitants avec GPS furtifs.",
     "BHPH", "bhph_auto"),

    # Wave 956 — Logement : frais cachés & services essentiels
    ("lease_hidden_fee_rights_engine.py",
     "Frais cachés dans les baux locatifs & droits des locataires", "Wave 956",
     "Locataires découvrant des frais obligatoires cachés ajoutés aux loyers annoncés.",
     "LHFR", "lease_hidden_fee"),
    ("utility_billing_error_rights_engine.py",
     "Erreurs de facturation des services publics & recours des consommateurs", "Wave 956",
     "Consommateurs surfacturés par des erreurs de compteurs ou de facturation sans recours simple.",
     "UBER", "utility_bill_error"),
    ("electric_gas_shutoff_rights_engine.py",
     "Coupures d'électricité et de gaz & protection des ménages vulnérables", "Wave 956",
     "Familles pauvres ou malades dont l'électricité ou le gaz est coupé en hiver ou été extrême.",
     "EGSR", "electric_gas_shutoff"),

    # Wave 957 — Logement : discrimination & accès au crédit
    ("source_of_income_discrimination_rights_engine.py",
     "Discrimination selon la source de revenu & logement abordable", "Wave 957",
     "Locataires refusés par des propriétaires discriminant contre les bénéficiaires d'aides au logement.",
     "SIDR", "income_source_discrim"),
    ("criminal_record_housing_rights_engine.py",
     "Casier judiciaire & discrimination au logement", "Wave 957",
     "Ex-détenus refusés systématiquement pour des logements sur la base de casiers judiciaires anciens.",
     "CRHR", "criminal_housing"),
    ("credit_check_housing_discrimination_rights_engine.py",
     "Vérification de crédit & exclusion des locataires pauvres", "Wave 957",
     "Critères de crédit excessivement stricts excluant les locataires pauvres du marché locatif.",
     "CCHD", "credit_housing_discrim"),

    # Wave 958 — Droit de vote : intégrité & accès
    ("voting_machine_paper_audit_rights_engine.py",
     "Machines à voter sans piste papier & intégrité électorale", "Wave 958",
     "États utilisant des machines à voter sans trace papier vérifiable, exposant aux litiges post-élection.",
     "VMAP", "voting_machine_audit"),
    ("early_voting_restriction_rights_engine.py",
     "Restrictions du vote anticipé & suppression électorale", "Wave 958",
     "Réductions des heures et jours de vote anticipé ciblant disproportionnellement les électeurs noirs.",
     "EVRR", "early_vote_restrict"),
    ("voter_registration_purge_rights_engine.py",
     "Radiation des listes électorales & opt-out automatique abusif", "Wave 958",
     "Électeurs radiés des listes électorales sans notification adéquate avant les élections.",
     "VRAO", "voter_reg_purge"),

    # Wave 959 — Justice juvénile & transition vers l'âge adulte
    ("juvenile_record_sealing_rights_engine.py",
     "Scellement des casiers juvéniles & transition vers l'âge adulte", "Wave 959",
     "Jeunes adultes bloqués par des casiers juvéniles non scellés empêchant emploi et logement.",
     "JRSR", "juvenile_record_seal"),
    ("aging_out_foster_care_rights_engine.py",
     "Jeunes quittant le placement à 18 ans sans filet de sécurité", "Wave 959",
     "Jeunes adultes sortant du système de placement sans logement, emploi ni soutien institutionnel.",
     "YAOF", "aging_foster_out"),
    ("youth_court_diversion_rights_engine.py",
     "Diversion judiciaire juvénile & accès inégal aux programmes", "Wave 959",
     "Jeunes délinquants primaires sans accès aux programmes de diversion selon leur code postal.",
     "YCDR", "youth_diversion"),

    # Wave 960 — Accès à la justice & arbitrage forcé
    ("court_filing_fee_barrier_rights_engine.py",
     "Frais de dossier judiciaire & barrière à la justice civile", "Wave 960",
     "Plaignants pauvres incapables de payer les frais de dossier pour accéder aux tribunaux civils.",
     "CFFB", "court_fee_barrier"),
    ("civil_legal_aid_gap_rights_engine.py",
     "Aide juridictionnelle civile & écart de financement", "Wave 960",
     "Millions de personnes pauvres sans avocat dans des affaires civiles déterminant leur logement et garde.",
     "CLGP", "civil_legal_aid"),
    ("nursing_home_arbitration_clause_rights_engine.py",
     "Clauses d'arbitrage dans les maisons de retraite & droits des résidents", "Wave 960",
     "Résidents contraints de signer des clauses d'arbitrage lors de l'admission privant de recours judiciaire.",
     "NURB", "nursing_arbit"),
]
