# Specs waves 937-944 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 937 — Droits électoraux & culturels autochtones
    ("tribal_voting_suppression_rights_engine.py",
     "Suppression du vote autochtone & obstacles électoraux", "Wave 937",
     "Communautés autochtones confrontées à des obstacles structurels à l'inscription et au vote.",
     "TVSN", "tribal_vote_suppress"),
    ("native_voter_id_rights_engine.py",
     "Identité électorale autochtone & difficultés d'inscription", "Wave 937",
     "Autochtones sans adresse fixe ou pièces d'identité étatiques exclus des bureaux de vote.",
     "NVID", "native_voter_id"),
    ("indigenous_mascot_school_rights_engine.py",
     "Mascotes autochtones & dignité culturelle dans les écoles", "Wave 937",
     "Équipes sportives utilisant des caricatures autochtones blessant la dignité des communautés.",
     "IMSK", "indigenous_mascot"),

    # Wave 938 — Droits des traités & souveraineté tribale
    ("treaty_fishing_rights_engine.py",
     "Droits de pêche issus des traités & violations fédérales", "Wave 938",
     "Nations autochtones dont les droits de pêche garantis par traité sont ignorés ou réduits.",
     "TFRG", "treaty_fishing"),
    ("treaty_hunting_rights_engine.py",
     "Droits de chasse issus des traités & restrictions gouvernementales", "Wave 938",
     "Peuples autochtones poursuivis pour exercer des droits de chasse garantis par traités historiques.",
     "THRN", "treaty_hunting"),
    ("tribal_gaming_sovereignty_rights_engine.py",
     "Jeux tribaux & atteintes à la souveraineté autochtone", "Wave 938",
     "États bloquant les activités de jeu tribales en violation des droits souverains reconnus.",
     "TGSV", "tribal_gaming"),

    # Wave 939 — Enfants autochtones & décrochage scolaire
    ("icwa_violation_native_child_rights_engine.py",
     "ICWA & violation des droits des enfants autochtones en placement", "Wave 939",
     "Enfants autochtones placés dans des familles non autochtones en violation de l'ICWA fédérale.",
     "ICWV", "icwa_violation"),
    ("native_child_foster_placement_rights_engine.py",
     "Placements d'enfants autochtones & éloignement familial", "Wave 939",
     "Enfants autochtones surreprésentés dans le système de placement hors de leurs communautés.",
     "NCFP", "native_foster"),
    ("native_student_dropout_rights_engine.py",
     "Décrochage scolaire des élèves autochtones & abandon institutionnel", "Wave 939",
     "Élèves autochtones décrochant à des taux deux fois supérieurs faute de soutien culturel à l'école.",
     "NSDR", "native_dropout"),

    # Wave 940 — Extractivisme & droits autochtones
    ("oil_pipeline_indigenous_rights_engine.py",
     "Pipelines pétroliers & violations des droits autochtones", "Wave 940",
     "Pipelines traversant des terres ancestrales autochtones sans consentement préalable éclairé.",
     "OPIR", "pipeline_indigenous"),
    ("extractivism_indigenous_community_rights_engine.py",
     "Extractivisme & destruction des communautés autochtones", "Wave 940",
     "Industries extractives détruisant les moyens de subsistance autochtones sans compensation.",
     "EXIC", "extractivism_indigenous"),
    ("indigenous_environmental_justice_rights_engine.py",
     "Justice environnementale autochtone & double fardeau", "Wave 940",
     "Communautés autochtones portant un fardeau environnemental disproportionné des industries polluantes.",
     "IEJR", "indigenous_enviro"),

    # Wave 941 — Droits trans & identité légale
    ("trans_gender_marker_id_rights_engine.py",
     "Marqueur de genre sur les documents d'identité & droits trans", "Wave 941",
     "Personnes trans incapables de corriger leur marqueur de genre sur passeports et permis de conduire.",
     "TGMR", "trans_gender_marker"),
    ("trans_insurance_coverage_rights_engine.py",
     "Couverture d'assurance & discrimination médicale transgenre", "Wave 941",
     "Assureurs refusant de couvrir les soins d'affirmation de genre pour les personnes trans.",
     "TICR", "trans_insurance"),
    ("trans_elder_care_rights_engine.py",
     "Soins aux aîné·es transgenres & discrimination institutionnelle", "Wave 941",
     "Personnes trans âgées maltraitées dans les maisons de retraite qui ignorent leur identité.",
     "TECR", "trans_elder"),

    # Wave 942 — Protection des données des jeunes & santé numérique
    ("youth_data_collection_rights_engine.py",
     "Collecte de données des mineurs en ligne & violations COPPA", "Wave 942",
     "Plateformes collectant les données personnelles de mineurs sans consentement parental requis.",
     "YDCR", "youth_data"),
    ("social_media_algorithm_teen_rights_engine.py",
     "Algorithmes des réseaux sociaux & dommages aux adolescents", "Wave 942",
     "Algorithmes amplifiant contenus nuisibles auprès des adolescents vulnérables sans régulation.",
     "SMAT", "social_algo_teen"),
    ("social_media_eating_disorder_rights_engine.py",
     "Réseaux sociaux, image corporelle & troubles alimentaires des jeunes", "Wave 942",
     "Contenus algorithmiques promouvant l'idéal de minceur extrême déclenchant des troubles alimentaires.",
     "SMED", "social_eating_disorder"),

    # Wave 943 — Prisonniers & liens familiaux
    ("prison_visitation_ban_rights_engine.py",
     "Interdiction de visites en prison & destruction des liens familiaux", "Wave 943",
     "Prisons supprimant les visites physiques au profit d'appels vidéo payants imposés aux familles.",
     "PVBN", "prison_visit_ban"),
    ("incarcerated_parent_child_rights_engine.py",
     "Parents incarcérés & droits des enfants à maintenir le contact", "Wave 943",
     "Enfants séparés de leurs parents incarcérés sans programme de contact ou de réunification.",
     "IPCR", "incarcerated_parent"),
    ("prison_mail_surveillance_rights_engine.py",
     "Surveillance du courrier en prison & vie privée des détenus", "Wave 943",
     "Courrier des détenus lu systématiquement, incluant correspondances juridiques confidentielles.",
     "PMSR", "prison_mail"),

    # Wave 944 — Sécurité au travail & indemnisation
    ("workers_compensation_denial_rights_engine.py",
     "Refus d'indemnisation des travailleurs blessés au travail", "Wave 944",
     "Travailleurs blessés privés d'indemnisation par des employeurs contestant systématiquement les claims.",
     "WCDR", "workers_comp_denial"),
    ("osha_retaliation_worker_rights_engine.py",
     "Représailles contre les travailleurs signalant des dangers à l'OSHA", "Wave 944",
     "Travailleurs licenciés ou sanctionnés après avoir signalé des violations de sécurité à l'OSHA.",
     "OSHR", "osha_retaliation"),
    ("workplace_heat_illness_rights_engine.py",
     "Maladie de chaleur au travail & absence de protection OSHA", "Wave 944",
     "Travailleurs en intérieur sans climatisation exposés à des températures dangereuses sans protection.",
     "WPHI", "workplace_heat"),
]
