# Specs waves 1313-1320 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1313 — Santé: conditions chroniques spécifiques (inédits)
    ("inflammatory_bowel_disease_workplace_rights_engine.py",
     "Droits des travailleurs atteints de MICI au travail & accommodements ADA pour la maladie de Crohn et la rectocolite dans les environnements de bureau", "Wave 1313",
     "Employés atteints de Crohn ou rectocolite hémorragique demandant des accommodements comme des pauses fréquentes aux toilettes se voyant refuser ce droit minimal.",
     "IBDW", "ibd_workplace_rights"),
    ("interstitial_cystitis_disability_rights_engine.py",
     "Cystite interstitielle comme handicap protégé & droits des patients à des accommodements raisonnables au travail et une couverture d'assurance adéquate", "Wave 1313",
     "Personnes atteintes de cystite interstitielle chronique sévère se heurtant à des refus d'accommodements professionnels et de reconnaissance comme handicap valide.",
     "ICBS", "interstitial_cyst_dis"),
    ("chronic_pain_treatment_access_rights_engine.py",
     "Accès aux soins pour la douleur chronique non oncologique & droits des patients à des plans de traitement multimodaux sans être limités aux seuls opioïdes ou au sevrage", "Wave 1313",
     "Personnes souffrant de douleur chronique sévère se voyant refuser l'accès à des spécialistes de la douleur et des thérapies complémentaires par leur assurance.",
     "CPTA", "chronic_pain_treat"),

    # Wave 1314 — Logement: conditions & types (inédits)
    ("no_pets_exception_service_emotional_rights_engine.py",
     "Exceptions aux politiques no-pets pour les animaux d'assistance et de soutien & droits cumulatifs différents des simples accommodements ESA", "Wave 1314",
     "Propriétaires refusant les exceptions aux politiques no-pets pour les animaux d'assistance certifiés malgré les obligations FHA distinctes des simples animaux de compagnie.",
     "NPEX", "no_pets_exception"),
    ("storage_unit_auction_lien_rights_engine.py",
     "Lien et vente aux enchères des unités de stockage pour arriérés & droits des locataires à une notification adéquate avant que leurs biens personnels soient vendus", "Wave 1314",
     "Locataires d'unités de stockage perdant des objets de valeur inestimable lors d'enchères après avoir manqué de peu la date limite sans notification suffisante.",
     "SUAL", "storage_unit_lien"),
    ("hotel_extended_stay_tenant_rights_engine.py",
     "Droits des résidents à long terme dans les hôtels & protection locative pour ceux qui utilisent les hôtels à prix quotidien comme logement permanent faute d'alternative", "Wave 1314",
     "Personnes vivant depuis des mois dans des hôtels extended stay comme seul logement abordable sans droits de locataire ni protection contre l'expulsion soudaine.",
     "HEST", "hotel_extended_stay"),

    # Wave 1315 — Finance: banque & accès (inédits)
    ("unbanked_alternative_financial_rights_engine.py",
     "Services financiers alternatifs pour les ménages sans banque & droits à des services de dépôt abordables sans exigences de solde minimum prohibitives", "Wave 1315",
     "Ménages sans compte bancaire payant des frais excessifs pour encaisser des chèques et envoyer des mandats faute d'accès à des comptes bancaires standards.",
     "UBAF", "unbanked_alt_finance"),
    ("bank_account_wage_garnishment_rights_engine.py",
     "Protection des fonds de subsistance lors de saisies de comptes bancaires & droits des débiteurs à conserver les aides sociales et revenus minimaux", "Wave 1315",
     "Personnes dont les comptes bancaires sont saisis pour dettes perdant leurs allocations de chômage, prestations sociales et salaires nécessaires à leur survie.",
     "BAGS", "bank_garnishment"),
    ("payroll_card_fee_regulation_rights_engine.py",
     "Réglementation des frais des cartes de paie & droits des travailleurs payés par carte à une option de retrait gratuit et à des frais transparents", "Wave 1315",
     "Travailleurs recevant leur salaire sur des cartes de paie perdant une partie de leurs revenus en frais de retrait et de maintenance non divulgués à l'embauche.",
     "PCFD", "payroll_card_fees"),

    # Wave 1316 — Immigration: procédures avancées (inédits)
    ("affirmative_defensive_asylum_rights_engine.py",
     "Processus d'asile affirmatif vs défensif & droits des demandeurs à comprendre la voie procédurale et à éviter les défauts de comparution", "Wave 1316",
     "Demandeurs d'asile ignorant la différence entre les procédures d'asile affirmatives et défensives prenant des décisions procédurales qui nuisent à leur dossier.",
     "AADS", "affirm_defensive_asylum"),
    ("immigration_detention_mental_health_rights_engine.py",
     "Santé mentale dans les centres de rétention immigration & droits des détenus à des évaluations psychiatriques et des soins adaptés en rétention", "Wave 1316",
     "Détenus en centres de rétention immigration développant ou aggravant des troubles mentaux sans accès à des soins psychiatriques adéquats pendant la détention.",
     "IDMH", "immigr_det_mental"),
    ("military_parole_in_place_rights_engine.py",
     "Liberté conditionnelle sur place pour les familles militaires & droits des conjoints et parents non documentés de membres actifs à un statut légal provisoire", "Wave 1316",
     "Conjoints et parents non documentés de membres actifs des forces armées américaines cherchant à régulariser leur statut via le programme Military PIP.",
     "MIPL", "military_parole_place"),

    # Wave 1317 — Éducation: sports & activités scolaires (inédits)
    ("concussion_return_play_protocol_rights_engine.py",
     "Protocoles de retour au jeu après commotion cérébrale & droits des athlètes scolaires à un processus de récupération médicalement supervisé étape par étape", "Wave 1317",
     "Athlètes lycéens subissant des pressions de la part d'entraîneurs pour retourner au jeu trop tôt après une commotion cérébrale sans autorisation médicale.",
     "SCRT", "concussion_return_play"),
    ("extracurricular_activity_access_rights_engine.py",
     "Accès aux activités parascolaires pour tous les élèves & droits des élèves à faibles revenus et handicapés à participer sans barrières financières ou physiques", "Wave 1317",
     "Élèves de familles à faibles revenus exclus des activités parascolaires en raison de frais de participation, d'équipement ou de transport non couverts par les districts.",
     "EXCA", "extracurric_access"),
    ("school_uniform_low_income_rights_engine.py",
     "Exigences d'uniformes scolaires et aide financière & droits des familles défavorisées à ne pas être pénalisées pour incapacité à acheter les uniformes requis", "Wave 1317",
     "Familles à faibles revenus confrontées à des politiques d'uniformes scolaires sans programme d'aide financière adéquat pour les achats requis.",
     "SLIR", "school_uniform_low"),

    # Wave 1318 — Travail: droits spécifiques avancés (inédits)
    ("background_check_criminal_private_employer_rights_engine.py",
     "Vérifications des antécédents criminels par les employeurs privés & droits des candidats à contester les erreurs dans les rapports et à la divulgation du refus", "Wave 1318",
     "Candidats à l'emploi refusés sur la base de casiers erronés ou périmés dans des rapports de vérification des antécédents sans notification adéquate du motif.",
     "BGCP", "background_check_priv"),
    ("workplace_drug_testing_rights_engine.py",
     "Tests de dépistage de drogues au travail & droits des employés à contester des tests défaillants et à une procédure équitable avant sanctions disciplinaires", "Wave 1318",
     "Employés confrontés à des sanctions basées sur des tests de dépistage aux résultats faussement positifs sans procédure d'appel indépendante ni second test confirmatory.",
     "DTEW", "workplace_drug_test"),
    ("employee_personal_social_media_rights_engine.py",
     "Vie privée des réseaux sociaux personnels des employés & droits à une présence en ligne personnelle sans craindre les représailles de l'employeur", "Wave 1318",
     "Employés disciplinés ou licenciés pour des publications sur leurs réseaux sociaux personnels non liées à leur travail et publiées en dehors des heures de travail.",
     "SMPE", "employee_social_media"),

    # Wave 1319 — Santé: médicaments & technologies (inédits)
    ("mat_faith_based_treatment_rights_engine.py",
     "Traitement assisté par médicaments dans les structures basées sur la foi & droits des personnes avec TUO à accéder à la buprénorphine sans obstacle religieux", "Wave 1319",
     "Personnes avec trouble d'usage aux opioïdes accédant à des programmes de traitement religieux qui refusent ou découragent la TAMO malgré son efficacité prouvée.",
     "MAFT", "mat_faith_treatment"),
    ("remote_patient_monitoring_insurance_rights_engine.py",
     "Remboursement de la surveillance à distance des patients & droits des malades chroniques à une couverture d'assurance pour les dispositifs de monitoring continu", "Wave 1319",
     "Patients avec conditions chroniques utilisant des appareils de surveillance à distance refusant d'être remboursés par des assureurs ne reconnaissant pas ces codes CPT.",
     "RPMC", "remote_patient_monit"),
    ("telehealth_prescription_rights_engine.py",
     "Prescription médicale par télémédecine & droits des patients à recevoir des ordonnances valides lors de consultations virtuelles sans exigences de présence physique", "Wave 1319",
     "Patients dans des zones rurales ou à mobilité réduite incapables d'obtenir des renouvellements d'ordonnances lors de consultations de télémédecine en raison de restrictions étatiques.",
     "TLHP", "telehealth_prescribe"),

    # Wave 1320 — Droits divers: protection & civisme (inédits)
    ("credit_report_dispute_process_rights_engine.py",
     "Processus de contestation des rapports de crédit & droits des consommateurs à une enquête réelle sur les erreurs plutôt qu'une confirmation automatique des créanciers", "Wave 1320",
     "Consommateurs contestant des erreurs dans leurs rapports de crédit voyant les bureaux confirmer automatiquement les informations incorrectes sans enquête réelle.",
     "CRDP", "credit_report_dispute"),
    ("online_defamation_false_obituary_rights_engine.py",
     "Diffamation en ligne par faux avis de décès & droits des vivants dont la mort est faussement annoncée à obtenir une suppression rapide et des dommages", "Wave 1320",
     "Personnes découvrant de faux avis de décès publiés à leur sujet en ligne, causant des préjudices professionnels et personnels sans mécanisme de suppression rapide.",
     "OBDE", "false_obituary_defam"),
    ("voter_registration_purge_rights_engine.py",
     "Radiation irrégulière des listes électorales & droits des électeurs à une notification, vérification et réinscription avant de perdre leur droit de vote", "Wave 1320",
     "Électeurs inscrits découvrant le jour du scrutin qu'ils ont été radiés des listes sans notification préalable en raison de procédures de nettoyage non conformes.",
     "VRPG", "voter_reg_purge"),
]
