# Specs waves 833-840 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 833 — Réfugiés climatiques & adaptation
    ("climate_refugee_legal_gap_rights_engine.py",
     "Réfugiés climatiques & vide juridique", "Wave 833",
     "Personnes déplacées par le climat sans statut légal ni protection internationale.",
     "CLRG", "climate_refugee"),
    ("typhoon_evacuation_island_rights_engine.py",
     "Typhons & évacuation des îles vulnérables", "Wave 833",
     "Insulaires sans moyens d'évacuation face aux typhons de plus en plus violents.",
     "TYEV", "typhoon_island"),
    ("drought_farmer_suicide_rights_engine.py",
     "Sécheresse & vague de suicides de paysans", "Wave 833",
     "Agriculteurs ruinés par la sécheresse se suicidant sans filets de sécurité.",
     "DFSU", "drought_farmer_suicide"),

    # Wave 834 — Catastrophes naturelles amplifiées
    ("glacier_flash_flood_mountain_rights_engine.py",
     "Crues glaciaires soudaines & villages de montagne", "Wave 834",
     "Villages de montagne emportés par des crues glaciaires sans alerte précoce.",
     "GFFL", "glacier_flood"),
    ("permafrost_village_relocation_rights_engine.py",
     "Dégel du pergélisol & relogement des villages", "Wave 834",
     "Villages arctiques s'effondrant dans le pergélisol fondu sans ressources de relocalisation.",
     "PVRL", "permafrost_relocation"),
    ("wildfire_air_quality_chronic_rights_engine.py",
     "Incendies & qualité de l'air chronique", "Wave 834",
     "Communautés respirant des fumées de feux de forêt pendant des semaines sans protection.",
     "WFAQ", "wildfire_air"),

    # Wave 835 — Chaleur extrême & alimentation
    ("heat_island_urban_poor_rights_engine.py",
     "Îlots de chaleur & pauvreté urbaine", "Wave 835",
     "Quartiers pauvres densifiés sans verdure, piégés dans des îlots de chaleur mortels.",
     "HIUP", "heat_island"),
    ("flash_drought_crop_failure_rights_engine.py",
     "Sécheresse éclair & effondrement des récoltes", "Wave 835",
     "Sécheresses ultra-rapides anéantissant les récoltes sans temps d'adaptation.",
     "FDCF", "flash_drought"),
    ("indigenous_fire_knowledge_suppression_rights_engine.py",
     "Savoirs autochtones du feu & suppression", "Wave 835",
     "Pratiques de brûlage traditionnel interdites malgré leur efficacité prouvée.",
     "IFKN", "indigenous_fire"),

    # Wave 836 — Arctique & océans
    ("arctic_ice_loss_hunter_rights_engine.py",
     "Fonte de la banquise & chasseurs arctiques", "Wave 836",
     "Chasseurs et pêcheurs arctiques privés de glace stable et de ressources traditionnelles.",
     "AITH", "arctic_hunter"),
    ("microplastic_food_contamination_rights_engine.py",
     "Microplastiques & contamination alimentaire", "Wave 836",
     "Microplastiques envahissant la chaîne alimentaire sans réglementation ni étiquetage.",
     "MPFC", "microplastic_food"),
    ("nanoplastic_blood_health_rights_engine.py",
     "Nanoplastiques dans le sang & santé", "Wave 836",
     "Nanoplastiques détectés dans le sang humain sans étude sanitaire systématique.",
     "NPLB", "nanoplastic_blood"),

    # Wave 837 — Polluants chimiques persistants
    ("flame_retardant_toxin_rights_engine.py",
     "Retardateurs de flamme toxiques & exposition", "Wave 837",
     "Retardateurs de flamme dans les meubles et textiles s'accumulant dans l'organisme.",
     "TFLR", "flame_retardant"),
    ("pfoa_contamination_health_rights_engine.py",
     "PFOA & contamination des populations riveraines", "Wave 837",
     "PFOA rejeté par des usines accumulé dans l'eau et le sang des riverains.",
     "PFOA", "pfoa_contamination"),
    ("endocrine_disruptor_pesticide_rights_engine.py",
     "Perturbateurs endocriniens & pesticides", "Wave 837",
     "Pesticides perturbateurs endocriniens affectant fertilité et développement hormonal.",
     "EDPS", "endocrine_pesticide"),

    # Wave 838 — Chaîne alimentaire contaminée
    ("toxic_metal_tuna_rights_engine.py",
     "Métaux lourds dans le thon & consommateurs", "Wave 838",
     "Thons contaminés aux métaux lourds consommés sans information suffisante.",
     "TMTU", "toxic_metal_tuna"),
    ("mercury_fish_consumption_rights_engine.py",
     "Mercure dans les poissons & santé des femmes enceintes", "Wave 838",
     "Consommation de poissons contaminés au mercure exposant les nourrissons in utero.",
     "MFCO", "mercury_fish"),
    ("phthalate_child_toy_rights_engine.py",
     "Phtalates dans les jouets & perturbation hormonale", "Wave 838",
     "Jouets plastiques à base de phtalates perturbant le système hormonal des enfants.",
     "PHTC", "phthalate_toy"),

    # Wave 839 — Contamination industrielle du quotidien
    ("PCB_breast_milk_contamination_rights_engine.py",
     "PCB dans le lait maternel & contamination intergénérationnelle", "Wave 839",
     "PCB persistants passant de la mère à l'enfant via le lait maternel.",
     "PCBM", "pcb_breast_milk"),
    ("bisphenol_packaging_rights_engine.py",
     "Bisphénol dans les emballages alimentaires", "Wave 839",
     "BPA et substituts dans les emballages alimentaires exposant sans relâche les consommateurs.",
     "BPKP", "bisphenol_pack"),
    ("food_contact_chemical_rights_engine.py",
     "Produits chimiques de contact alimentaire non réglementés", "Wave 839",
     "Substances migrant des emballages vers les aliments sans évaluation toxicologique.",
     "FCCH", "food_contact"),

    # Wave 840 — Santé alimentaire & hôpital
    ("PFAS_cookware_contamination_rights_engine.py",
     "PFAS dans les ustensiles de cuisine & contamination", "Wave 840",
     "Revêtements antiadhésifs à base de PFAS contaminant les aliments à la cuisson.",
     "PFCK", "pfas_cookware"),
    ("hospital_acquired_infection_rights_engine.py",
     "Infections nosocomiales & manque de prévention", "Wave 840",
     "Patients contractant des infections mortelles à l'hôpital par défaut d'hygiène.",
     "HAIO", "hospital_infection"),
    ("antibiotic_overuse_farming_rights_engine.py",
     "Surutilisation d'antibiotiques en élevage & résistance", "Wave 840",
     "Élevages abusant des antibiotiques, accélérant la résistance antimicrobienne mondiale.",
     "ABOF", "antibiotic_farming"),
]
