# Specs waves 1249-1256 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1249 — Logement: situations critiques (inédits)
    ("mobile_home_park_closure_rights_engine.py",
     "Fermeture de parcs de maisons mobiles & droits des résidents à un préavis suffisant et aide à la relocalisation", "Wave 1249",
     "Résidents de parcs de maisons mobiles confrontés à la fermeture ou vente du parc sans délai suffisant ni aide financière pour déménager.",
     "MHPC", "mobile_home_park_clos"),
    ("rent_stabilization_exemption_rights_engine.py",
     "Exemptions de la stabilisation des loyers & droits des locataires dans les unités exclues des lois de contrôle des loyers", "Wave 1249",
     "Locataires dans des logements exemptés des lois de stabilisation des loyers confrontés à des augmentations massives sans recours légal.",
     "RSEX", "rent_stab_exempt"),
    ("landlord_bad_faith_renovation_rights_engine.py",
     "Rénovations de mauvaise foi pour forcer le départ & droits des locataires contre les travaux perturbateurs non nécessaires", "Wave 1249",
     "Locataires subissant des rénovations perturbatrice volontairement prolongées par des propriétaires voulant les faire partir sans expulsion légale.",
     "LHFE", "landlord_bad_faith_renov"),

    # Wave 1250 — Santé: maladies auto-immunes (inédits)
    ("rheumatoid_arthritis_step_therapy_rights_engine.py",
     "Thérapie par étapes imposée pour la polyarthrite rhumatoïde & droits des patients à accéder directement aux biologiques efficaces", "Wave 1250",
     "Patients atteints de polyarthrite rhumatoïde contraints d'essayer des médicaments moins efficaces avant d'accéder aux biologiques prescrits.",
     "RATS", "ra_step_therapy"),
    ("psoriatic_arthritis_biologic_insurance_rights_engine.py",
     "Couverture des biologiques pour le rhumatisme psoriasique & refus d'assurance exigeant l'échec de DMARDs conventionnels", "Wave 1250",
     "Patients atteints de rhumatisme psoriasique sévère se voyant refuser des biologiques approuvés en faveur de traitements moins adaptés.",
     "PSAB", "psoriatic_arth_biologic"),
    ("celiac_disease_food_service_rights_engine.py",
     "Droits des personnes cœliaques dans les établissements de restauration & obligations légales de proposer des options sans gluten sécurisées", "Wave 1250",
     "Personnes atteintes de la maladie cœliaque incapables d'obtenir une alimentation sans gluten sécurisée dans des restaurants et cafétérias.",
     "CFSR", "celiac_food_service"),

    # Wave 1251 — Immigration: procédures spécialisées (inédits)
    ("daca_renewal_processing_delay_rights_engine.py",
     "Délais de renouvellement DACA & droits des bénéficiaires à maintenir leur statut de travail légal sans interruption", "Wave 1251",
     "Bénéficiaires DACA perdant temporairement leur autorisation de travail à cause de délais USCIS excédant la période de grâce de 180 jours.",
     "DCRN", "daca_renewal_delay"),
    ("special_immigrant_juvenile_status_rights_engine.py",
     "Statut SIJ pour mineurs non accompagnés & droits des jeunes immigrants à une résidence permanente via la protection judiciaire des enfants", "Wave 1251",
     "Mineurs immigrants non accompagnés abandonnés, maltraités ou négligés éligibles au statut SIJ mais bloqués par les backlogs de visas.",
     "SIJV", "sij_status"),
    ("credible_fear_interview_rights_engine.py",
     "Entretiens de peur crédible à la frontière & droits des demandeurs d'asile à une évaluation équitable sans obstacles procéduraux", "Wave 1251",
     "Demandeurs d'asile détenus à la frontière dont les entretiens de peur crédible sont conduits sans interprète qualifié ni préparation légale.",
     "BCFI", "credible_fear_interv"),

    # Wave 1252 — Finance: dettes & pièges (inédits)
    ("debt_settlement_company_fraud_rights_engine.py",
     "Fraude des entreprises de règlement de dettes & droits des consommateurs contre les honoraires anticipés et promesses trompeuses", "Wave 1252",
     "Consommateurs endettés payant des milliers en honoraires à des entreprises de règlement de dettes qui ne réduisent pas réellement les soldes.",
     "DTSF", "debt_settlement_fraud"),
    ("payday_loan_collection_harassment_rights_engine.py",
     "Harcèlement des collecteurs de prêts payday & droits des emprunteurs contre les pratiques de recouvrement abusives", "Wave 1252",
     "Emprunteurs de prêts payday ciblés par des collecteurs utilisant des menaces, appels répétés et contacts avec l'employeur illégaux.",
     "PDCH", "payday_collect_harass"),
    ("tax_refund_anticipation_loan_rights_engine.py",
     "Prêts d'anticipation de remboursement fiscal & droits des déclarants à faibles revenus contre les frais cachés des RAL et RAC", "Wave 1252",
     "Déclarants à faibles revenus payant des taux annuels effectifs excessifs pour emprunter leur propre remboursement fiscal via des RAL.",
     "TRAL", "tax_refund_anticip"),

    # Wave 1253 — Travail: catégories spéciales (inédits)
    ("restaurant_tip_credit_minimum_wage_rights_engine.py",
     "Crédit de pourboire et salaire minimum des serveurs & droits des travailleurs à un salaire de base garanti indépendant des tips", "Wave 1253",
     "Serveurs dans des États autorisant le salaire de pourboire subminimal ne gagnant pas l'équivalent du salaire minimum quand les tips sont faibles.",
     "RTCM", "restaurant_tip_credit"),
    ("farmworker_heat_illness_protection_rights_engine.py",
     "Protection des travailleurs agricoles contre les maladies liées à la chaleur & droits à l'ombre, l'eau et des pauses réglementaires", "Wave 1253",
     "Travailleurs agricoles dans des États sans règlement de protection contre la chaleur exposés à des températures dangereuses sans protection légale.",
     "FHIT", "farmworker_heat_prot"),
    ("domestic_worker_paid_leave_rights_engine.py",
     "Congés payés pour travailleurs domestiques & exclusion des lois d'assurance invalidité temporaire et congés familiaux dans certains États", "Wave 1253",
     "Travailleurs domestiques non couverts par les lois de congés payés dans des États sans déclaration des droits des travailleurs domestiques.",
     "DPLD", "domestic_work_paid_leave"),

    # Wave 1254 — Éducation: accès & équité avancés (inédits)
    ("student_financial_aid_appeal_rights_engine.py",
     "Appels des décisions d'aide financière étudiante & droits des étudiants à contester les ajustements de package après soumission", "Wave 1254",
     "Étudiants dont les packages d'aide financière sont réduits unilatéralement par les universités sans procédure d'appel transparente.",
     "SFAA", "student_aid_appeal"),
    ("college_athlete_nil_rights_engine.py",
     "Droits Name Image Likeness des athlètes universitaires & restrictions institutionnelles limitant les opportunités de revenu NIL", "Wave 1254",
     "Athlètes universitaires éligibles aux accords NIL après les réformes NCAA confrontés à des restrictions institutionnelles ou conférencières.",
     "CANI", "college_athlete_nil"),
    ("school_zero_tolerance_pipeline_rights_engine.py",
     "Politiques de tolérance zéro dans les écoles & droits des élèves contre l'exclusion disproportionnée alimentant le pipeline école-prison", "Wave 1254",
     "Élèves, notamment de couleur, suspendus ou renvoyés de façon disproportionnée sous des politiques de tolérance zéro pour des infractions mineures.",
     "STPP", "school_zero_toleran"),

    # Wave 1255 — Technologie: surveillance & vie privée (inédits)
    ("employer_remote_monitoring_rights_engine.py",
     "Surveillance électronique des télétravailleurs par les employeurs & droits des employés à la vie privée pendant le télétravail", "Wave 1255",
     "Télétravailleurs soumis à une surveillance constante via keyloggers, captures d'écran ou caméras sans divulgation ni consentement éclairé.",
     "EMRW", "employer_remote_monit"),
    ("voice_biometric_customer_service_rights_engine.py",
     "Collecte des données biométriques vocales dans les centres d'appels & droits des consommateurs au consentement préalable et à la suppression", "Wave 1255",
     "Consommateurs dont la voix est analysée et stockée biométriquement par des centres d'appels sans consentement explicite ni politique de rétention.",
     "VBCS", "voice_biometric_cs"),
    ("childrens_app_coppa_data_rights_engine.py",
     "Protection des données des enfants sous COPPA & violations des apps ciblant les enfants collectant des données sans consentement parental", "Wave 1255",
     "Enfants utilisant des apps et jeux collectant secrètement des données personnelles en violation de la loi COPPA malgré l'obligation de consentement.",
     "CCOP", "children_coppa_app"),

    # Wave 1256 — Droits divers: protection avancée (inédits)
    ("service_dog_restaurant_denial_rights_engine.py",
     "Refus d'accès aux restaurants pour les chiens d'assistance & droits ADA à l'entrée dans tous les établissements publics", "Wave 1256",
     "Personnes handicapées avec chiens d'assistance refusées dans des restaurants et établissements alimentaires ignorant les obligations ADA.",
     "SDRD", "service_dog_restaur"),
    ("medicaid_estate_recovery_rights_engine.py",
     "Programme de récupération des successions Medicaid MERP & droits des héritiers à contester les réclamations sur les maisons de famille", "Wave 1256",
     "Héritiers découvrant que l'État réclame le remboursement de dépenses Medicaid sur la maison familiale après le décès d'un parent bénéficiaire.",
     "MERP", "medicaid_estate_recov"),
    ("adult_guardianship_review_rights_engine.py",
     "Révision des tutelles adultes & droits des personnes sous tutelle à contester et mettre fin à une tutelle devenue inutile", "Wave 1256",
     "Adultes sous tutelle légale qui ont retrouvé leur capacité décisionnelle incapables de mettre fin à leur tutelle sans procédure judiciaire coûteuse.",
     "AGVR", "adult_guardian_review"),
]
