# Specs waves 1217-1224 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 1217 — Finance: Sécurité Sociale & pensions fonctionnaires (inédits)
    ("government_pension_offset_widow_rights_engine.py",
     "Règle GPO de compensation pension gouvernementale & réduction des allocations de veuvage pour les veuves fonctionnaires", "Wave 1217",
     "Veuves d'enseignants et fonctionnaires voyant leurs allocations de survivants Social Security réduites jusqu'à zéro par la règle GPO.",
     "GPOW", "gov_pension_offset"),
    ("windfall_elimination_provision_rights_engine.py",
     "Disposition d'élimination des aubaines WEP & réduction injuste des prestations SS pour travailleurs avec pension mixte", "Wave 1217",
     "Travailleurs retraités avec à la fois une pension non couverte par la SS et des droits SS réduits par la WEP sans préavis.",
     "WEPC", "windfall_elim_provis"),
    ("social_security_earnings_limit_rights_engine.py",
     "Plafond de revenus pour les bénéficiaires SS avant l'âge plein de la retraite & pénalités sur les seniors en activité", "Wave 1217",
     "Seniors prenant leur retraite anticipée et reprenant un travail perdant des dollars de prestations SS pour chaque dollar gagné.",
     "SSWP", "ss_earnings_limit"),

    # Wave 1218 — Santé: soins longue durée (inédits)
    ("nursing_home_staffing_shortage_rights_engine.py",
     "Pénurie de personnel dans les maisons de retraite & droits des résidents à des ratios personnel-résidents minimaux garantis", "Wave 1218",
     "Résidents de maisons de retraite recevant des soins insuffisants faute de personnel adéquat dans des établissements sous-dotés.",
     "NSHF", "nursing_staff_short"),
    ("long_term_care_insurance_premium_hike_rights_engine.py",
     "Hausses massives des primes d'assurance soins longue durée & droits des assurés à des augmentations approuvées et plafonnées", "Wave 1218",
     "Assurés âgés voyant leurs primes d'assurance soins longue durée doubler ou tripler sans possibilité d'annulation sans perte.",
     "LNFC", "ltci_premium_hike"),
    ("home_health_aide_rural_shortage_rights_engine.py",
     "Pénurie d'aides à domicile en zones rurales & droits des seniors ruraux à recevoir des soins à domicile Medicare couverts", "Wave 1218",
     "Patients âgés ruraux ayant droit aux soins à domicile Medicare incapables de trouver des aides disponibles dans leur zone.",
     "ISDH", "home_health_rural"),

    # Wave 1219 — Droits familiaux & identité (inédits)
    ("tribal_disenrollment_rights_engine.py",
     "Expulsion de membres des tribus & droits des personnes désinscrites à contester la perte de leur citoyenneté tribale", "Wave 1219",
     "Membres de tribus expulsés par décision politique tribale perdant droits de santé, logement et avantages sans recours judiciaire.",
     "TRBD", "tribal_disenroll"),
    ("domestic_violence_survivor_housing_rights_engine.py",
     "Logement de remplacement pour survivantes de violence domestique & droits à un relogement d'urgence sans attente de liste", "Wave 1219",
     "Survivantes de violence domestique fuyant leur domicile sans pouvoir accéder rapidement à un logement d'urgence sécurisé.",
     "DVHS", "dv_survivor_housing"),
    ("advance_directive_hospital_recognition_rights_engine.py",
     "Reconnaissance des directives médicales anticipées par les hôpitaux & violations du droit des patients à des soins conformes", "Wave 1219",
     "Patients dont les directives anticipées sont ignorées par les équipes hospitalières qui prolongent les traitements contre leur volonté.",
     "EDCP", "adv_directive_hosp"),

    # Wave 1220 — Catastrophes & assurance climatique (inédits)
    ("disaster_price_gouging_protection_rights_engine.py",
     "Protection contre le gonflement des prix en cas de catastrophe & droits des victimes à des prix équitables après une urgence", "Wave 1220",
     "Sinistrés de catastrophes naturelles victimes de prix d'hôtels, eau, carburant et matériaux multipliés par 5 sans sanction.",
     "PGSF", "disaster_price_goug"),
    ("wildfire_homeowner_insurance_nonrenewal_rights_engine.py",
     "Non-renouvellement des assurances habitation en zone à risque incendie & droits des propriétaires à une couverture abordable", "Wave 1220",
     "Propriétaires en zones à risque d'incendie perdant leur couverture habitation sans assurance de remplacement accessible.",
     "WBPC", "wildfire_insur_nonren"),
    ("flood_insurance_private_market_rights_engine.py",
     "Marché privé d'assurance inondation & droits des propriétaires à des alternatives au NFIP gouvernemental souvent insuffisant", "Wave 1220",
     "Propriétaires en zone inondable cherchant des couvertures privées alternatives au NFIP confrontés à des refus ou des exclusions.",
     "FRGR", "flood_insur_private"),

    # Wave 1221 — Justice: recours & accès (inédits)
    ("court_appointed_counsel_ineffective_rights_engine.py",
     "Inefficacité de la défense publique commise d'office & droits des accusés à une représentation juridique adéquate garantie", "Wave 1221",
     "Accusés avec avocats commis d'office surchargés incapables de préparer une défense adéquate face à des procureurs bien dotés.",
     "CPRT", "court_appt_ineffect"),
    ("small_claims_appeal_right_rights_engine.py",
     "Droit d'appel des jugements de petites créances & restrictions procédurales laissant des décisions erronées sans recours", "Wave 1221",
     "Perdants de procès en petites créances confrontés à des limitations d'appel sévères pour des jugements manifestement incorrects.",
     "AETR", "small_claim_appeal"),
    ("consumer_arbitration_class_ban_rights_engine.py",
     "Interdictions de recours collectifs dans les clauses d'arbitrage & droits des consommateurs à des recours groupés effectifs", "Wave 1221",
     "Consommateurs lésés pour de petites sommes incapables de former un recours collectif en raison de clauses d'arbitration obligatoires.",
     "SSNB", "consumer_arb_class"),

    # Wave 1222 — Technologie: données & vie privée (inédits)
    ("tenant_screening_report_error_rights_engine.py",
     "Erreurs dans les rapports de vérification des locataires & droits des candidats à corriger les données fausses avant rejet", "Wave 1222",
     "Candidats locataires rejetés pour des erreurs dans leurs rapports de dossier locatif sans notification ni droit de correction préalable.",
     "TRDM", "tenant_screen_error"),
    ("location_data_broker_selling_rights_engine.py",
     "Vente des données de localisation par des courtiers de données & droits des utilisateurs à limiter le commerce de leur géolocalisation", "Wave 1222",
     "Consommateurs dont les données de géolocalisation précises sont vendues par des data brokers à des annonceurs, assureurs ou gouvernements.",
     "CBNF", "location_data_sell"),
    ("fitness_health_app_data_privacy_rights_engine.py",
     "Confidentialité des données de santé des apps fitness non couvertes par HIPAA & vente à des tiers sans consentement éclairé", "Wave 1222",
     "Utilisateurs d'apps de santé et fitness dont les données sensibles sont vendues à des assureurs ou courtiers sans protection HIPAA.",
     "HPWF", "fitness_app_privacy"),

    # Wave 1223 — Immigration: statuts de travail spéciaux (inédits)
    ("h4_visa_spouse_employment_rights_engine.py",
     "Droits professionnels des conjoints H-4 de titulaires H-1B & insécurité de l'autorisation de travail lors des changements de règles", "Wave 1223",
     "Conjoints H-4 hautement qualifiés perdant leur autorisation de travail lors de changements de règlementation ou de retards administratifs.",
     "SNIA", "h4_spouse_employ"),
    ("voluntary_departure_immigration_rights_engine.py",
     "Départ volontaire en droit de l'immigration & pièges des accords de départ affectant les droits futurs d'entrée aux USA", "Wave 1223",
     "Immigrants acceptant un départ volontaire sans comprendre les interdictions d'entrée future associées à cet accord.",
     "SLRS", "voluntary_depart"),
    ("asylum_administrative_closure_rights_engine.py",
     "Fermeture administrative des dossiers d'asile & droits des demandeurs à voir leur affaire réexaminée après clôture arbitraire", "Wave 1223",
     "Demandeurs d'asile dont les dossiers ont été administrativement clos sans décision de fond et qui cherchent à les rouvrir.",
     "ERAT", "asylum_admin_close"),

    # Wave 1224 — Santé & sécurité alimentaire (inédits)
    ("food_allergy_school_policy_rights_engine.py",
     "Politiques scolaires pour les allergies alimentaires graves & droits des enfants à un plan d'urgence 504 avec épinéphrine", "Wave 1224",
     "Enfants avec allergies alimentaires graves dans des écoles sans plans 504 ni épinéphrine disponible pour les réactions anaphylactiques.",
     "FSGR", "food_allergy_school"),
    ("hospital_price_transparency_rights_engine.py",
     "Transparence des prix hospitaliers & droits des patients à connaître les coûts avant les soins pour décider en connaissance", "Wave 1224",
     "Patients subissant des procédures médicales sans pouvoir obtenir les prix à l'avance malgré la règle fédérale de transparence.",
     "HHRR", "hospital_price_trans"),
    ("harm_reduction_syringe_program_rights_engine.py",
     "Programmes d'échange de seringues pour la réduction des risques & criminalisation persistante dans des États à overdose élevée", "Wave 1224",
     "Personnes utilisant des drogues injectables vivant dans des États criminalisé les programmes d'échange de seringues vitaux.",
     "SNKR", "harm_reduc_syringe"),
]
