# Specs waves 1329-1336 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Corrections: SPHR pris par solar_panel_hoa → HGAR (home_garden_hoa)
SPECS = [
    # Wave 1329 — Santé: couverture & continuité (inédits)
    ("cobra_health_coverage_continuation_rights_engine.py",
     "Continuation COBRA de l'assurance maladie & droits des travailleurs licenciés à maintenir leur couverture sans interruption de soins en cours pendant la transition", "Wave 1329",
     "Travailleurs licenciés perdant leur assurance maladie incapables de payer les primes COBRA élevées et ignorant les alternatives comme les Special Enrollment Periods ACA.",
     "COBR", "cobra_health_cover"),
    ("aca_special_enrollment_period_rights_engine.py",
     "Périodes d'inscription spéciale ACA & droits des consommateurs à s'inscrire dans les plans Marketplace hors période ouverte lors d'événements déclencheurs valides", "Wave 1329",
     "Consommateurs subissant des changements de vie comme la perte d'emploi ou le mariage ignorant qu'ils ont 60 jours pour s'inscrire à une couverture ACA hors saison.",
     "ASEP", "aca_special_enroll"),
    ("nonemergency_medical_transport_medicaid_rights_engine.py",
     "Transport médical non urgent Medicaid & droits des patients à un transport gratuit vers les rendez-vous médicaux sans refus arbitraires ou délais excessifs des prestataires", "Wave 1329",
     "Patients Medicaid vivant sans transport personnel incapables de se rendre à leurs rendez-vous médicaux en raison d'un accès insuffisant au NEMT prévu par leur plan.",
     "NEMT", "nemt_medicaid_rights"),

    # Wave 1330 — Logement: propriété & infrastructure (inédits)
    ("school_building_facility_condition_rights_engine.py",
     "État des bâtiments scolaires & droits des élèves à des environnements d'apprentissage sains sans moisissures, amiante ou systèmes de ventilation défaillants dangereux", "Wave 1330",
     "Élèves dans des bâtiments scolaires dégradés avec moisissures visibles, chauffage insuffisant ou ventilation défectueuse sans plan de réparation ni financement alloué.",
     "SBFR", "school_building_cond"),
    ("manufactured_home_title_conversion_rights_engine.py",
     "Conversion de titre des maisons préfabriquées en bien immobilier réel & droits des propriétaires à accéder au financement hypothécaire traditionnel sans obstacles administratifs", "Wave 1330",
     "Propriétaires de maisons préfabriquées sur terrain propre incapables de convertir leur titre en bien immobilier réel pour accéder à des financements hypothécaires avantageux.",
     "MHCT", "mfg_home_title_conv"),
    ("home_garden_hoa_restriction_rights_engine.py",
     "Restrictions HOA sur les jardins potagers résidentiels & droits des propriétaires à cultiver des légumes sans être contraints de supprimer leurs jardins pour raisons esthétiques", "Wave 1330",
     "Propriétaires dans des associations HOA recevant des avertissements pour des jardins potagers visibles malgré la légalité de l'agriculture urbaine dans leur municipalité.",
     "HGAR", "home_garden_hoa"),

    # Wave 1331 — Travail: maladies professionnelles & compensation (inédits)
    ("occupational_disease_latent_claim_rights_engine.py",
     "Réclamations de maladies professionnelles à manifestation tardive & droits des travailleurs exposés à des toxines dont les effets cliniques apparaissent des années après", "Wave 1331",
     "Anciens travailleurs développant des maladies professionnelles des années après leur exposition confrontés à des délais de prescription expirés et une causalité difficile à prouver.",
     "ODLC", "occup_dis_latent"),
    ("gig_worker_on_job_injury_rights_engine.py",
     "Blessures au travail pour les travailleurs de plateformes & droits des gig workers blessés en mission à une compensation sans être exclus par leur classification de travailleur indépendant", "Wave 1331",
     "Chauffeurs Uber, livreurs DoorDash blessés en mission sans accès à la workers' compensation car classifiés comme entrepreneurs indépendants plutôt qu'employés.",
     "GIWC", "gig_worker_injury"),
    ("joint_employer_temp_worker_liability_rights_engine.py",
     "Responsabilité de l'employeur conjoint pour les travailleurs temporaires & droits des intérimaires à tenir les employeurs d'origine et utilisateurs conjointement responsables", "Wave 1331",
     "Travailleurs temporaires exploités par des agences d'intérim dont les entreprises clientes contournent leur responsabilité en invoquant la relation d'emploi indirecte.",
     "JELT", "joint_emp_temp_liab"),

    # Wave 1332 — Finance: protection consommateurs avancée (inédits)
    ("robocall_tcpa_consumer_enforcement_rights_engine.py",
     "Application TCPA contre les robocalls non consentis & droits des consommateurs à faire valoir leurs droits malgré les obstacles pratiques et les défenses des entreprises", "Wave 1332",
     "Consommateurs recevant des dizaines de robocalls commerciaux non consentis malgré leur inscription au registre Do Not Call sans mécanisme de plainte accessible.",
     "RTCR", "robocall_tcpa_rights"),
    ("home_warranty_claim_denial_rights_engine.py",
     "Refus de réclamations de garantie habitation & droits des propriétaires à contester les exclusions abusives et les refus pour systèmes ménagers défaillants couverts", "Wave 1332",
     "Propriétaires avec garanties habitation se voyant refuser les réclamations pour des systèmes défaillants en raison d'exclusions ou clauses d'entretien préventif non divulguées.",
     "HWCR", "home_warranty_claim"),
    ("irs_innocent_spouse_tax_relief_rights_engine.py",
     "Soulagement de responsabilité fiscale pour conjoint innocent & droits des ex-conjoints à être exonérés de dettes fiscales créées à leur insu par leur ancien partenaire", "Wave 1332",
     "Personnes divorcées devant rembourser des impôts non payés ou des pénalités IRS générées par les actions fiscales frauduleuses de leur ex-conjoint sans leur consentement.",
     "IISR", "innocent_spouse_irs"),

    # Wave 1333 — Santé: dépistage préventif avancé (inédits)
    ("osteoporosis_bone_density_screening_rights_engine.py",
     "Dépistage de l'ostéoporose par densitométrie osseuse & droits des femmes ménopausées et personnes à risque à des tests DEXA remboursés sans obstacles bureaucratiques", "Wave 1333",
     "Femmes de plus de 65 ans et hommes à risque d'ostéoporose ne recevant pas de référence pour une densitométrie DEXA remboursée malgré les recommandations USPSTF.",
     "OBDS", "osteoporosis_screen"),
    ("abdominal_aortic_aneurysm_screening_rights_engine.py",
     "Dépistage de l'anévrisme aortique abdominal & droits des anciens fumeurs masculins de 65 à 75 ans à un dépistage échographique unique remboursé par Medicare", "Wave 1333",
     "Anciens fumeurs masculins de 65 à 75 ans ignorant leur éligibilité à un dépistage unique remboursé de l'anévrisme aortique lors de leur visite préventive Welcome to Medicare.",
     "AAAS", "aortic_aneurysm_screen"),
    ("depression_anxiety_primary_care_screening_rights_engine.py",
     "Dépistage de la dépression et de l'anxiété en soins primaires & droits des patients adultes à un dépistage annuel remboursé sans copaiement et à des suivis intégrés", "Wave 1333",
     "Adultes souffrant de dépression ou d'anxiété non diagnostiquées dont le médecin de soins primaires ne réalise pas de dépistage systématique malgré les recommandations.",
     "DASR", "depression_anx_screen"),

    # Wave 1334 — Éducation: équité avancée (inédits)
    ("school_indoor_air_quality_rights_engine.py",
     "Qualité de l'air intérieur dans les écoles & droits des élèves à des environnements d'apprentissage sains sans exposition à la moisissure, aux COV ou aux systèmes HVAC défaillants", "Wave 1334",
     "Élèves et enseignants dans des écoles avec problèmes chroniques de qualité de l'air intérieur signalant des problèmes respiratoires sans action corrective des districts scolaires.",
     "SIAQ", "school_indoor_air"),
    ("title_ix_athletic_equity_rights_engine.py",
     "Équité athlétique Title IX dans les lycées et universités & droits des athlètes féminines à des budgets, équipements et opportunités équivalents aux programmes masculins", "Wave 1334",
     "Équipes sportives féminines dans des établissements scolaires recevant des budgets, installations et soutien en coaching significativement inférieurs à ceux des équipes masculines.",
     "TIXA", "title_ix_athletic"),
    ("private_student_loan_disclosure_rights_engine.py",
     "Transparence des prêts étudiants privés & droits des emprunteurs à des informations claires sur les taux variables, frais et conditions avant signature d'engagements pluriannuels", "Wave 1334",
     "Étudiants signant des prêts privés avec des taux d'intérêt variables sans comprendre la différence avec les prêts fédéraux ni les risques de variation des paiements mensuels.",
     "SLPT", "private_loan_disclos"),

    # Wave 1335 — Immigration: procédures spéciales (inédits)
    ("employment_authorization_renewal_delay_rights_engine.py",
     "Délais de renouvellement des autorisations de travail EAD & droits des titulaires de visas à continuer à travailler légalement sans interruption pendant les renouvellements", "Wave 1335",
     "Travailleurs immigrants dont les autorisations d'emploi expirent avant le traitement de leur renouvellement, perdant légalement leur droit de travailler pendant des mois.",
     "EADR", "ead_renewal_delay"),
    ("consular_immigrant_visa_processing_rights_engine.py",
     "Traitement consulaire des visas d'immigrant & droits des demandeurs à une transparence sur les délais et à des procédures d'appel pour les refus sans motifs clairs", "Wave 1335",
     "Ressortissants étrangers attendant des années une entrevue consulaire pour un visa d'immigrant approuvé sans information sur la cause des délais ni voie d'appel accessible.",
     "CPIV", "consular_visa_proc"),
    ("immigrant_tenant_rights_enforcement_rights_engine.py",
     "Application des droits locatifs pour les locataires immigrants & droits des résidents sans statut légal à invoquer les protections locatives sans craindre des représailles d'immigration", "Wave 1335",
     "Locataires immigrants évitant de signaler des violations de logement ou de poursuivre des propriétaires abusifs par peur que les autorités d'immigration soient alertées.",
     "ITRE", "immigr_tenant_rights"),

    # Wave 1336 — Droits divers: accès & protection (inédits)
    ("state_public_records_access_rights_engine.py",
     "Accès aux documents publics d'État & droits des citoyens à obtenir des dossiers gouvernementaux sans frais prohibitifs, délais excessifs ou exemptions abusives", "Wave 1336",
     "Journalistes et citoyens soumettant des demandes d'accès aux documents publics d'État se heurtant à des frais de reproduction excessifs et des délais de réponse de plusieurs années.",
     "SPRA", "state_pub_records"),
    ("home_repair_contractor_fraud_rights_engine.py",
     "Fraude des entrepreneurs en rénovation domiciliaire & droits des propriétaires victimes d'escroqueries à des recours légaux, garanties de performance et compensation", "Wave 1336",
     "Propriétaires payant des acomptes importants à des entrepreneurs peu scrupuleux qui disparaissent sans terminer les travaux ou les réalisent si mal qu'une démolition est nécessaire.",
     "HRCF", "home_contractor_fraud"),
    ("prescription_drug_importation_rights_engine.py",
     "Importation légale de médicaments sur ordonnance & droits des patients à accéder à des médicaments canadiens ou étrangers certifiés quand les prix américains sont prohibitifs", "Wave 1336",
     "Patients incapables de payer les prix américains de leurs médicaments cherchant à les importer légalement du Canada sans savoir comment naviguer le cadre réglementaire actuel.",
     "PDRI", "prescription_drug_import"),
]
