# Specs waves 969-976 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 969 — Violences domestiques & accès aux soins
    ("domestic_violence_shelter_access_rights_engine.py",
     "Accès aux refuges pour victimes de violence domestique", "Wave 969",
     "Victimes de violence domestique sans hébergement d'urgence adapté, surpeuplé ou géographiquement inaccessible.",
     "DVSA", "dv_shelter_access"),
    ("domestic_violence_gun_removal_rights_engine.py",
     "Retrait d'armes aux agresseurs & protection des victimes DV", "Wave 969",
     "Abuseurs domestiques conservant leurs armes malgré des ordonnances de protection en raison de lacunes légales.",
     "DVGR", "dv_gun_removal"),
    ("healthcare_surprise_billing_rights_engine.py",
     "Facturation médicale surprise & droits des patients", "Wave 969",
     "Patients recevant des factures imprévues de prestataires hors réseau lors de soins d'urgence.",
     "HSBR", "surprise_billing"),

    # Wave 970 — LGBTQ+ droits adultes (nouvelles violations)
    ("anti_drag_show_ban_rights_engine.py",
     "Lois anti-drag show & censure des performances LGBTQ+", "Wave 970",
     "Lois étatiques interdisant ou restreignant les spectacles de drag en tant qu'expression culturelle.",
     "ADSB", "anti_drag_ban"),
    ("gender_neutral_restroom_rights_engine.py",
     "Toilettes neutres & droits des personnes non-binaires", "Wave 970",
     "Personnes non-binaires contraintes d'utiliser des toilettes ne correspondant pas à leur identité.",
     "GNRR", "gender_neutral_bath"),
    ("lgbtq_hospital_visitation_rights_engine.py",
     "Droits de visite hospitalière pour les couples LGBTQ+", "Wave 970",
     "Partenaires LGBTQ+ exclus des visites hospitalières d'urgence et des décisions médicales.",
     "LHVR", "lgbtq_hospital_visit"),

    # Wave 971 — Police & responsabilité civile
    ("qualified_immunity_police_rights_engine.py",
     "Immunité qualifiée policière & absence de responsabilité civile", "Wave 971",
     "Victimes de brutalité policière bloquées par l'immunité qualifiée empêchant tout recours civil.",
     "QIPR", "qualified_immunity"),
    ("police_body_camera_rights_engine.py",
     "Caméras corporelles policières & transparence des interventions", "Wave 971",
     "Agents désactivant leurs caméras corporelles ou refusant de divulguer les vidéos aux victimes.",
     "PBCR", "police_bodycam"),
    ("civilian_complaint_board_rights_engine.py",
     "Conseils civils de surveillance policière & pouvoir réel", "Wave 971",
     "Commissions de surveillance civile sans pouvoir disciplinaire réel sur les agents abusifs.",
     "CCBR", "civilian_complaint"),

    # Wave 972 — Armes à feu & violence armée
    ("ghost_gun_trafficking_rights_engine.py",
     "Trafic d'armes fantômes & lacunes de traçabilité légale", "Wave 972",
     "Armes sans numéro de série impossibles à tracer utilisées dans des crimes sans responsabilité.",
     "GGTR", "ghost_gun"),
    ("school_shooting_survivor_rights_engine.py",
     "Survivants de fusillades scolaires & droits à la protection", "Wave 972",
     "Élèves survivants de fusillades sans accès à un soutien psychologique ou à la protection légale.",
     "SSSR", "shooting_survivor"),
    ("gun_violence_public_health_rights_engine.py",
     "Violence armée, recherche en santé publique & censure politique", "Wave 972",
     "Financement de la recherche sur la violence armée bloqué politiquement, privant de données cruciales.",
     "GVPH", "gun_violence_research"),

    # Wave 973 — Soins médicaux refusés & victimes de crimes
    ("prison_medical_neglect_rights_engine.py",
     "Négligence médicale en prison & droits constitutionnels", "Wave 973",
     "Détenus mourant de maladies traitables faute de soins médicaux adéquats dans les prisons.",
     "PMNR", "prison_medical"),
    ("opioid_patient_undertreated_rights_engine.py",
     "Patients douloureux & sous-traitement des opioïdes par peur réglementaire", "Wave 973",
     "Patients en douleur chronique privés d'opioïdes nécessaires par la sur-régulation et la peur des médecins.",
     "OPUT", "opioid_undertreated"),
    ("hate_crime_victim_rights_engine.py",
     "Victimes de crimes haineux & droits à la protection renforcée", "Wave 973",
     "Victimes de crimes haineux sans accès aux protections spécifiques faute de signalement adéquat.",
     "HCVR", "hate_crime_victim"),

    # Wave 974 — Asile, appel & immigration (violences)
    ("asylum_mental_health_rights_engine.py",
     "Demandeurs d'asile, traumatismes & accès aux soins mentaux", "Wave 974",
     "Demandeurs d'asile traumatisés sans accès aux soins de santé mentale durant l'attente longue.",
     "AMHR", "asylum_mental"),
    ("asylum_appeal_rights_engine.py",
     "Appels des décisions d'asile & droits de procédure limités", "Wave 974",
     "Demandeurs déboutés avec des droits d'appel restreints et des délais insuffisants.",
     "AALR", "asylum_appeal"),
    ("immigration_status_dv_rights_engine.py",
     "Statut migratoire & victimes de violence domestique (T/U visa)", "Wave 974",
     "Victimes immigrantes de violence domestique craignant la déportation si elles signalent l'abus.",
     "ISDV", "immigration_dv"),

    # Wave 975 — Personnes âgées : isolation, emploi & mobilité
    ("elder_isolation_general_rights_engine.py",
     "Isolement général des personnes âgées & impacts sur la santé", "Wave 975",
     "Seniors vivant seuls sans lien social ni accès aux services, subissant déclin cognitif accéléré.",
     "EIGR", "elder_isolation"),
    ("ageism_employment_rights_engine.py",
     "Discrimination par l'âge dans l'emploi & violations ADEA", "Wave 975",
     "Travailleurs de plus de 40 ans licenciés ou refusés à l'embauche sur la base de leur âge.",
     "AGEM", "ageism_employ"),
    ("senior_transportation_access_rights_engine.py",
     "Accès au transport pour les seniors & mobilité autonome", "Wave 975",
     "Personnes âgées sans accès au paratransit ou aux transports adaptés, coupées des soins et services.",
     "STAS", "senior_transport"),

    # Wave 976 — Fracture numérique & protection des seniors
    ("digital_divide_elderly_rights_engine.py",
     "Fracture numérique & exclusion des personnes âgées des services en ligne", "Wave 976",
     "Seniors exclus des services publics et médicaux devenus exclusivement numériques.",
     "DDER", "digital_elderly"),
    ("elder_romance_scam_rights_engine.py",
     "Arnaques romantiques ciblant les personnes âgées & protection légale", "Wave 976",
     "Personnes âgées piégées par des arnaques romantiques perdant leurs économies sans recours efficace.",
     "EFRM", "elder_romance_scam"),
    ("automated_phone_barrier_elderly_rights_engine.py",
     "Systèmes téléphoniques automatisés & exclusion des seniors", "Wave 976",
     "Seniors incapables de naviguer les systèmes IVR complexes et chatbots pour accéder aux services essentiels.",
     "APBE", "auto_phone_barrier"),
]
