# Specs waves 1369-1376 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Corrections: FSFR pris par food_sovereignty → FSPR; ALPR pris par auto_loan_predatory → LPRP
SPECS = [
    # Wave 1369 — Santé: maladies chroniques invisibles (inédits)
    ("postural_tachycardia_pots_disability_rights_engine.py",
     "Syndrome de tachycardie posturale (POTS) comme handicap & droits des patients à une reconnaissance médicale et des accommodements face à un trouble dysautonomique invalidant et méconnu", "Wave 1369",
     "Patients atteints de POTS subissant des malaises et tachycardies invalidants se voyant refuser accommodements et reconnaissance médicale faute de connaissance de ce trouble dysautonomique.",
     "PTPD", "pots_disability"),
    ("fibromyalgia_workplace_accommodation_rights_engine.py",
     "Accommodements professionnels pour la fibromyalgie & droits des travailleurs atteints de douleurs chroniques diffuses à des ajustements raisonnables sans devoir prouver une cause objective", "Wave 1369",
     "Travailleurs atteints de fibromyalgie se voyant refuser des accommodements par des employeurs exigeant des preuves objectives impossibles pour une affection à la physiopathologie complexe.",
     "FBMW", "fibromyalgia_work"),
    ("trigeminal_neuralgia_treatment_access_rights_engine.py",
     "Accès au traitement de la névralgie du trijumeau & droits des patients souffrant de douleurs faciales extrêmes à des interventions spécialisées sans être limités aux antalgiques de base", "Wave 1369",
     "Patients atteints de névralgie du trijumeau subissant des douleurs faciales atroces se voyant refuser l'accès à la microchirurgie ou radiochirurgie par leur assureur.",
     "TGNT", "trigeminal_neuralgia"),

    # Wave 1370 — Santé rares & logement abordable (inédits)
    ("hidradenitis_suppurativa_treatment_access_rights_engine.py",
     "Accès au traitement de l'hidradénite suppurée & droits des patients atteints de cette maladie cutanée chronique douloureuse à des biothérapies sans diagnostic tardif ni stigmatisation", "Wave 1370",
     "Patients atteints d'hidradénite suppurée souffrant pendant des années avant un diagnostic correct et se voyant refuser les biothérapies efficaces par leur assurance.",
     "HDST", "hidradenitis_treat"),
    ("intractable_epilepsy_device_access_rights_engine.py",
     "Accès aux dispositifs pour l'épilepsie réfractaire & droits des patients dont les crises résistent aux médicaments à des dispositifs neurostimulateurs implantables remboursés", "Wave 1370",
     "Patients atteints d'épilepsie pharmacorésistante se voyant refuser l'accès à des dispositifs de neurostimulation vagale ou répondante par leur assurance malgré l'échec des médicaments.",
     "IEDA", "intractable_epilepsy"),
    ("accessory_dwelling_unit_zoning_rights_engine.py",
     "Zonage des unités d'habitation accessoires (ADU) & droits des propriétaires à construire des logements secondaires abordables sans obstacles réglementaires excessifs ni interdictions locales", "Wave 1370",
     "Propriétaires souhaitant construire une unité d'habitation accessoire pour un proche âgé ou un revenu locatif confrontés à des règles de zonage prohibitives et coûts d'autorisation excessifs.",
     "ADUZ", "adu_zoning"),

    # Wave 1371 — Logement: locataires & propriété (inédits)
    ("rooming_house_tenant_rights_engine.py",
     "Droits des locataires de maisons de chambres & protection des occupants de chambres individuelles à services partagés contre les expulsions arbitraires et conditions insalubres", "Wave 1371",
     "Occupants de maisons de chambres partageant cuisine et sanitaires confrontés à des expulsions sans procédure et des conditions insalubres sans la protection accordée aux locataires classiques.",
     "RMHT", "rooming_house_tenant"),
    ("land_contract_home_buyer_protection_rights_engine.py",
     "Protection des acheteurs en contrat foncier & droits des acquéreurs achetant via un contrat de vente à tempérament à la propriété équitable et contre les confiscations abusives", "Wave 1371",
     "Acheteurs de maisons via contrat foncier perdant tous leurs paiements et améliorations en cas de retard car le vendeur conserve le titre et peut résilier sans procédure de saisie.",
     "LCHB", "land_contract_buyer"),
    ("foreclosure_surplus_funds_recovery_rights_engine.py",
     "Récupération des fonds excédentaires de saisie immobilière & droits des anciens propriétaires à récupérer le surplus de la vente après remboursement de la dette hypothécaire", "Wave 1371",
     "Anciens propriétaires dont la maison saisie a été vendue au-dessus de la dette ignorant qu'ils ont droit au surplus, ciblés par des localisateurs facturant des commissions excessives.",
     "FSPR", "foreclosure_surplus"),

    # Wave 1372 — Finance: prédateur & accès (inédits)
    ("prepaid_debit_card_fee_disclosure_rights_engine.py",
     "Divulgation des frais des cartes prépayées & droits des consommateurs sans banque à des frais transparents sur les cartes prépayées sans charges cachées d'activation et de maintenance", "Wave 1372",
     "Consommateurs sans compte bancaire utilisant des cartes prépayées perdant une partie de leurs fonds en frais d'activation, de rechargement et d'inactivité non clairement divulgués.",
     "PPDF", "prepaid_card_fees"),
    ("installment_loan_flex_pay_trap_rights_engine.py",
     "Pièges des prêts à tempérament et paiements flexibles & droits des emprunteurs à comprendre le coût total réel des produits de paiement échelonné à taux élevés au point de vente", "Wave 1372",
     "Consommateurs souscrivant des prêts à tempérament au point de vente sous-estimant le coût total réel en raison de taux d'intérêt élevés et de structures de paiement trompeuses.",
     "ILFP", "installment_flex_pay"),
    ("credit_repair_organization_scam_rights_engine.py",
     "Arnaques des sociétés de réparation de crédit & droits des consommateurs à une protection contre les promesses frauduleuses et frais anticipés illégaux des réparateurs de crédit", "Wave 1372",
     "Consommateurs avec mauvais crédit payant des frais anticipés à des sociétés de réparation de crédit promettant illégalement d'effacer des informations exactes de leur dossier.",
     "CROS", "credit_repair_scam"),

    # Wave 1373 — Travail: classification & secteurs (inédits)
    ("staffing_agency_fee_worker_rights_engine.py",
     "Frais illégaux facturés aux travailleurs intérimaires & droits des employés d'agences de placement à ne pas payer pour obtenir un travail ni subir de déductions abusives de salaire", "Wave 1373",
     "Travailleurs intérimaires se voyant facturer des frais de placement, de transport ou d'équipement illégaux par des agences de staffing réduisant leur salaire net sous le minimum légal.",
     "SAFW", "staffing_agency_fee"),
    ("prevailing_wage_construction_rights_engine.py",
     "Salaire prévalant sur les chantiers publics & droits des ouvriers du bâtiment à percevoir le salaire prévalant légal sur les projets financés par des fonds publics", "Wave 1373",
     "Ouvriers de la construction sur des chantiers publics sous-payés par des entrepreneurs ne respectant pas les taux de salaire prévalant légalement requis pour les marchés publics.",
     "PWCW", "prevailing_wage_constr"),
    ("franchise_no_poach_worker_rights_engine.py",
     "Clauses anti-débauchage entre franchises & droits des employés à changer d'employeur au sein d'un réseau de franchises sans être bloqués par des accords no-poach illégaux", "Wave 1373",
     "Employés de chaînes franchisées empêchés de postuler dans un autre établissement de la même enseigne par des clauses no-poach secrètes limitant leur mobilité et leurs salaires.",
     "FNPW", "franchise_no_poach"),

    # Wave 1374 — Immigration & justice: procédure (inédits)
    ("asylum_detention_minor_separation_rights_engine.py",
     "Détention et séparation des mineurs demandeurs d'asile & droits des enfants migrants à ne pas être séparés de leur famille ni détenus dans des conditions inadaptées à leur âge", "Wave 1374",
     "Enfants demandeurs d'asile séparés de leurs parents ou détenus dans des installations inadaptées sans représentation légale ni garanties procédurales adaptées à leur âge.",
     "ADTM", "asylum_detention_minor"),
    ("citizenship_test_disability_waiver_rights_engine.py",
     "Dispenses du test de citoyenneté pour les personnes handicapées & droits des candidats à la naturalisation avec handicaps cognitifs à des exemptions ou accommodements de l'examen", "Wave 1374",
     "Candidats à la naturalisation avec handicaps cognitifs ou médicaux se voyant refuser l'exemption d'examen civique et linguistique malgré leur éligibilité au formulaire de dérogation médicale.",
     "CTDW", "citizenship_test_waiver"),
    ("clemency_pardon_application_process_rights_engine.py",
     "Processus de demande de clémence et de grâce & droits des condamnés à un examen équitable et transparent de leur demande de commutation de peine ou de pardon après réhabilitation", "Wave 1374",
     "Personnes condamnées cherchant clémence ou grâce confrontées à des processus opaques, des arriérés de plusieurs années et l'absence de critères clairs ni de retour sur leur demande.",
     "CPAP", "clemency_pardon"),

    # Wave 1375 — Justice: défense & procès équitable (inédits)
    ("digital_evidence_defendant_access_rights_engine.py",
     "Accès des accusés aux preuves numériques & droits de la défense à examiner les données, algorithmes et métadonnées utilisés à charge sans obstacles de propriété ou de format", "Wave 1375",
     "Accusés confrontés à des preuves issues de logiciels propriétaires ou de données numériques que la défense ne peut examiner indépendamment en raison de secrets commerciaux invoqués.",
     "DEDA", "digital_evidence_access"),
    ("prosecutor_brady_disclosure_violation_rights_engine.py",
     "Violations de l'obligation Brady de divulgation par les procureurs & droits des accusés à recevoir toutes les preuves à décharge détenues par l'accusation avant le procès", "Wave 1375",
     "Accusés condamnés à tort car les procureurs ont dissimulé des preuves à décharge en violation de l'arrêt Brady, sans mécanisme efficace de sanction de cette inconduite.",
     "PBDV", "brady_disclosure"),
    ("school_resource_officer_arrest_rights_engine.py",
     "Arrestations par les agents de sécurité scolaire & droits des élèves à ne pas être criminalisés pour des problèmes disciplinaires mineurs gérables par l'école sans intervention policière", "Wave 1375",
     "Élèves, souvent issus de minorités ou handicapés, arrêtés et inculpés par des agents de police scolaires pour des incidents disciplinaires mineurs relevant de la gestion éducative.",
     "SROA", "sro_arrest"),

    # Wave 1376 — Éducation & vie privée numérique (inédits)
    ("charter_school_special_ed_pushout_rights_engine.py",
     "Éviction des élèves handicapés par les écoles à charte & droits des élèves en éducation spéciale à ne pas être découragés ou refusés par des écoles publiques à charte sélectives", "Wave 1376",
     "Élèves handicapés découragés de s'inscrire ou poussés vers la sortie par des écoles à charte évitant les coûts des services d'éducation spéciale malgré leurs obligations légales.",
     "CSEP", "charter_sped_pushout"),
    ("data_minimization_consumer_rights_engine.py",
     "Minimisation de la collecte de données des consommateurs & droits des utilisateurs à ce que les entreprises ne collectent que les données strictement nécessaires au service fourni", "Wave 1376",
     "Consommateurs contraints de fournir des données personnelles excessives sans rapport avec le service demandé, exposés à des risques accrus de fuite et d'utilisation secondaire non consentie.",
     "DMCR", "data_minimization"),
    ("automated_license_plate_reader_privacy_rights_engine.py",
     "Vie privée et lecteurs automatiques de plaques d'immatriculation & droits des citoyens à limiter la collecte massive et la conservation des données de localisation de leurs véhicules", "Wave 1376",
     "Conducteurs dont les déplacements sont massivement enregistrés par des réseaux de lecteurs de plaques conservés indéfiniment sans soupçon ni encadrement de l'accès aux données.",
     "LPRP", "lpr_privacy"),
]
