# Specs waves 849-856 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 849 — Suppression du vote & démocratie
    ("voter_id_suppression_rights_engine.py",
     "Lois d'identité électorale & suppression du vote", "Wave 849",
     "Exigences de pièce d'identité éliminant les électeurs marginalisés des scrutins.",
     "VISP", "voter_id_suppression"),
    ("gerrymandering_extreme_rights_engine.py",
     "Gérymandering extrême & distorsion représentative", "Wave 849",
     "Découpage électoral partisan annulant l'influence des minorités dans les scrutins.",
     "GEEX", "gerrymandering"),
    ("polling_place_closure_rights_engine.py",
     "Fermeture de bureaux de vote & accès réduit", "Wave 849",
     "Fermetures massives de bureaux de vote allongeant les files dans les quartiers pauvres.",
     "PPLO", "polling_closure"),

    # Wave 850 — Restrictions électorales & accès
    ("drop_box_restriction_voting_rights_engine.py",
     "Restrictions des boîtes de dépôt de vote", "Wave 850",
     "Suppression des boîtes de dépôt de bulletins gênant les électeurs ruraux et précaires.",
     "DBRS", "dropbox_restriction"),
    ("vote_by_mail_attack_rights_engine.py",
     "Vote par correspondance & attaques législatives", "Wave 850",
     "Lois restreignant le vote postal ciblant les électeurs défavorisés et les personnes âgées.",
     "VBMA", "vote_mail_attack"),
    ("ballot_curing_notice_failure_rights_engine.py",
     "Défaut de notification pour bulletins invalides", "Wave 850",
     "Électeurs dont les bulletins sont rejetés sans notification permettant correction.",
     "BCNF", "ballot_cure_fail"),

    # Wave 851 — Prisonniers politiques & justice
    ("political_prisoner_family_rights_engine.py",
     "Prisonniers politiques & familles abandonnées", "Wave 851",
     "Familles de prisonniers politiques harcelées, précarisées et réduites au silence.",
     "PPFM", "political_prisoner_family"),
    ("overcrowding_juvenile_facility_rights_engine.py",
     "Surpopulation des centres pour mineurs", "Wave 851",
     "Mineurs détenus dans des centres surpeuplés violant les standards de protection.",
     "OJFA", "juvenile_overcrowd"),
    ("youth_court_transfer_adult_rights_engine.py",
     "Transfert de mineurs vers la juridiction adulte", "Wave 851",
     "Mineurs jugés comme adultes et incarcérés dans des prisons pour adultes.",
     "YCTA", "youth_adult_transfer"),

    # Wave 852 — Détention migratoire & mineurs
    ("solitary_immigration_detention_rights_engine.py",
     "Isolement en détention migratoire", "Wave 852",
     "Migrants en détention administrative placés à l'isolement sans recours légal.",
     "SIMD", "immigration_solitary"),
    ("immigrant_juvenile_deportation_rights_engine.py",
     "Expulsion de mineurs migrants non accompagnés", "Wave 852",
     "Mineurs non accompagnés expulsés sans tuteur légal ni évaluation de protection.",
     "IJDR", "juvenile_deportation"),
    ("stateless_veteran_rights_engine.py",
     "Anciens combattants apatrides & abandon", "Wave 852",
     "Vétérans militaires devenus apatrides après un service au péril de leur vie.",
     "SLVT", "stateless_veteran"),

    # Wave 853 — Vétérans & trauma militaire
    ("military_sexual_trauma_coverage_rights_engine.py",
     "Trauma sexuel militaire & couverture de soins", "Wave 853",
     "Vétéran·e·s victimes d'agressions sexuelles sans prise en charge post-service.",
     "MSTC", "military_sexual_trauma"),
    ("ptsd_treatment_veteran_access_rights_engine.py",
     "PTSD des vétérans & accès aux soins", "Wave 853",
     "Anciens combattants avec PTSD sévère sans accès rapide à un traitement psychiatrique.",
     "PTTV", "ptsd_veteran"),
    ("toxic_burn_pit_veteran_rights_engine.py",
     "Fosses d'incinération toxiques & maladies des vétérans", "Wave 853",
     "Vétérans malades des fosses d'incinération militaires se heurtant à des refus de prise en charge.",
     "TBPV", "burn_pit_veteran"),

    # Wave 854 — Sans-abri vétérans & soutien
    ("veteran_homeless_gap_rights_engine.py",
     "Vétérans sans abri & lacunes du soutien", "Wave 854",
     "Anciens combattants à la rue, tombant entre les mailles des systèmes d'aide.",
     "VHMG", "veteran_homeless"),
    ("service_dog_housing_denial_rights_engine.py",
     "Chiens d'assistance & refus de logement", "Wave 854",
     "Personnes handicapées avec chien d'assistance refusées par des propriétaires.",
     "SDHS", "service_dog_housing"),
    ("disability_travel_barrier_rights_engine.py",
     "Handicap & barrières au voyage", "Wave 854",
     "Voyageurs handicapés bloqués par des infrastructures de transport inaccessibles.",
     "DTRB", "disability_travel"),

    # Wave 855 — Accessibilité numérique & sensorielle
    ("accessible_transport_rural_rights_engine.py",
     "Transport adapté & désert rural", "Wave 855",
     "Personnes handicapées rurales sans transport adapté, coupées des soins et des emplois.",
     "ATRA", "accessible_rural_transport"),
    ("cochlear_implant_access_rights_engine.py",
     "Implants cochléaires & accès inégal", "Wave 855",
     "Sourds incapables d'accéder aux implants cochléaires faute de couverture sociale.",
     "CHIA", "cochlear_access"),
    ("screen_reader_web_accessibility_rights_engine.py",
     "Lecteurs d'écran & inaccessibilité du web", "Wave 855",
     "Sites web gouvernementaux et commerciaux illisibles par les lecteurs d'écran pour aveugles.",
     "SRWA", "screen_reader_web"),

    # Wave 856 — Communication accessible & urgences
    ("captioning_failure_deaf_rights_engine.py",
     "Sous-titrage défaillant & personnes sourdes", "Wave 856",
     "Médias, événements et tribunaux sans sous-titrage correct excluant les sourds.",
     "CPFL", "captioning_fail"),
    ("emergency_alert_deaf_rights_engine.py",
     "Alertes d'urgence inaccessibles aux sourds", "Wave 856",
     "Systèmes d'alerte d'urgence sonores ignorant les personnes sourdes et malentendantes.",
     "EADF", "emergency_deaf"),
    ("sign_language_interpreter_court_rights_engine.py",
     "Interprètes LSF & accès à la justice", "Wave 856",
     "Personnes sourdes sans interprète qualifié devant les tribunaux et administrations.",
     "SLIC", "sign_court_access"),
]
