# Specs waves 817-824 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 817 — Enfants & numérique toxique
    ("social_media_child_addiction_rights_engine.py",
     "Réseaux sociaux & addiction des enfants", "Wave 817",
     "Algorithmes conçus pour capter l'attention des enfants, provoquant dépendance et anxiété.",
     "SMCA", "social_media_addiction"),
    ("teen_influencer_exploitation_rights_engine.py",
     "Mineurs influenceurs & exploitation commerciale", "Wave 817",
     "Mineurs transformés en machines à contenu sans protection ni rémunération équitable.",
     "TINE", "teen_influencer"),
    ("gaming_loot_box_addiction_rights_engine.py",
     "Loot boxes & addiction des joueurs mineurs", "Wave 817",
     "Mécaniques de jeu prédatrices ciblant les mineurs avec des achats aléatoires compulsifs.",
     "GLLB", "gaming_lootbox"),

    # Wave 818 — Objets connectés & surveillance domestique
    ("surveillance_toy_child_rights_engine.py",
     "Jouets connectés & surveillance des enfants", "Wave 818",
     "Jouets espionnant les enfants et transmettant leurs données sans consentement parental.",
     "STCH", "surveillance_toy"),
    ("smart_home_privacy_exploitation_rights_engine.py",
     "Maisons connectées & exploitation de la vie privée", "Wave 818",
     "Appareils domestiques intelligents collectant et revendant les données intimes du foyer.",
     "SHPE", "smart_home_privacy"),
    ("elderly_smart_device_manipulation_rights_engine.py",
     "Appareils connectés & manipulation des aînés", "Wave 818",
     "Personnes âgées manipulées par des interfaces numériques conçues pour extorquer.",
     "ESDM", "elderly_device"),

    # Wave 819 — Biométrie & école
    ("biometric_school_children_rights_engine.py",
     "Biométrie scolaire & vie privée des élèves", "Wave 819",
     "Empreintes et données biométriques collectées sur les enfants dans les écoles.",
     "BMSC", "biometric_school"),
    ("facial_recognition_school_rights_engine.py",
     "Reconnaissance faciale à l'école", "Wave 819",
     "Surveillance faciale des élèves normalisant le contrôle biométrique dès l'enfance.",
     "FRSC", "facial_school"),
    ("voter_surveillance_digital_rights_engine.py",
     "Surveillance numérique des électeurs", "Wave 819",
     "Profilage massif des électeurs pour influencer leur comportement de vote.",
     "VSDI", "voter_digital_surveillance"),

    # Wave 820 — Finance politique & influence
    ("campaign_finance_dark_money_rights_engine.py",
     "Financement politique opaque & argent noir", "Wave 820",
     "Argent anonyme inondant les campagnes électorales et contournant la démocratie.",
     "CFDM", "dark_money"),
    ("corporate_lobbying_health_rights_engine.py",
     "Lobbying industriel & santé publique", "Wave 820",
     "Industries polluantes bloquant les réglementations sanitaires via le lobbying.",
     "CLHB", "lobby_health"),
    ("revolving_door_regulatory_capture_rights_engine.py",
     "Pantouflage & capture réglementaire", "Wave 820",
     "Régulateurs rejoignant les industries qu'ils contrôlaient, détruisant l'indépendance.",
     "RDRG", "revolving_door"),

    # Wave 821 — Abus corporatifs & brevets
    ("patent_trolling_ngo_rights_engine.py",
     "Brevets prédateurs & ONG de santé", "Wave 821",
     "Trolls de brevets bloquant les ONG humanitaires produisant des médicaments génériques.",
     "PTNG", "patent_trolling"),
    ("whistleblower_corporate_retaliation_rights_engine.py",
     "Lanceurs d'alerte & représailles corporatives", "Wave 821",
     "Employés signalant des fraudes réduits au silence par des contre-attaques juridiques.",
     "WTRC", "whistleblower_corp"),
    ("deforestation_carbon_offset_fraud_rights_engine.py",
     "Fraude aux crédits carbone & déforestation", "Wave 821",
     "Crédits carbone fictifs vendus pendant que les forêts et communautés sont détruites.",
     "DCOF", "carbon_offset_fraud"),

    # Wave 822 — Greenwashing & investissement
    ("greenwashing_corporate_rights_engine.py",
     "Greenwashing & tromperie environnementale", "Wave 822",
     "Entreprises affichant des bilans verts bidon pour esquiver la réglementation.",
     "GRWC", "greenwashing"),
    ("esg_fraud_investor_rights_engine.py",
     "Fraude ESG & droits des investisseurs", "Wave 822",
     "Fonds ESG frauduleux trompant épargnants et institutionnels sur leurs critères.",
     "ESGF", "esg_fraud"),
    ("pension_fund_fossil_risk_rights_engine.py",
     "Fonds de retraite & risques fossiles dissimulés", "Wave 822",
     "Fonds de pension surexposés aux actifs fossiles mettant les retraites en péril.",
     "PFOS", "pension_fossil"),

    # Wave 823 — Travail précaire & logement
    ("ghost_worker_platform_rights_engine.py",
     "Travailleurs fantômes des plateformes IA", "Wave 823",
     "Travailleurs invisibles annotant les données IA sans contrat ni protection sociale.",
     "GHWP", "ghost_worker"),
    ("gig_deliveryman_heat_exposure_rights_engine.py",
     "Livreurs & exposition à la chaleur extrême", "Wave 823",
     "Livreurs à vélo et moto travaillant sous chaleur mortelle sans aménagement.",
     "GDHP", "delivery_heat"),
    ("piece_rate_agricultural_wage_rights_engine.py",
     "Rémunération aux pièces & travailleurs agricoles", "Wave 823",
     "Travailleurs agricoles payés à la pièce sous le seuil légal sans recours.",
     "PRCA", "piece_rate_agri"),

    # Wave 824 — Consumérisme toxique & finance prédatrice
    ("health_hazard_cosmetic_rights_engine.py",
     "Cosmétiques dangereux & populations vulnérables", "Wave 824",
     "Produits cosmétiques toxiques ciblant les communautés noires et à faible revenu.",
     "HZCS", "hazard_cosmetic"),
    ("predatory_lending_student_rights_engine.py",
     "Prêts étudiants prédateurs & trappe à dette", "Wave 824",
     "Établissements d'enseignement privés piégeant les étudiants dans des dettes impayables.",
     "PLST", "predatory_student"),
    ("private_equity_hospital_closure_rights_engine.py",
     "Capital-investissement & fermeture d'hôpitaux", "Wave 824",
     "Fonds de capital-investissement fermant des hôpitaux ruraux après saignée financière.",
     "PEHO", "private_equity_hosp"),
]
