# Specs waves 841-848 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 841 — IA & corps numérique
    ("deepfake_voice_nonconsensual_rights_engine.py",
     "Deepfake vocal non consenti & atteinte à l'identité", "Wave 841",
     "Voix clonées par IA utilisées sans consentement pour diffamer ou arnaquer.",
     "DFNV", "deepfake_voice"),
    ("identity_theft_synthetic_ai_rights_engine.py",
     "Vol d'identité synthétique par IA", "Wave 841",
     "Identités synthétiques créées par IA pour frauder individus et institutions.",
     "ITHD", "synthetic_id_theft"),
    ("ai_hiring_filter_discrimination_rights_engine.py",
     "Filtres IA à l'embauche & discrimination", "Wave 841",
     "Algorithmes de tri de CV écartant les candidats sur des critères discriminatoires.",
     "AHFB", "ai_hiring_bias"),

    # Wave 842 — Automatisation & emploi
    ("automated_termination_worker_rights_engine.py",
     "Licenciement automatisé & absence de recours", "Wave 842",
     "Travailleurs licenciés par algorithme sans motif humain ni droit de contestation.",
     "ATWK", "automated_termination"),
    ("robot_tax_displacement_rights_engine.py",
     "Automatisation robotique & déplacement des travailleurs", "Wave 842",
     "Travailleurs déplacés par les robots sans filets sociaux ni reconversion financée.",
     "RBTX", "robot_displacement"),
    ("digital_twin_worker_exploitation_rights_engine.py",
     "Jumeau numérique du travailleur & exploitation", "Wave 842",
     "Modèles numériques de travailleurs utilisés pour les former sans compensation.",
     "DTWE", "digital_twin_worker"),

    # Wave 843 — Neurotechnologie & cerveau
    ("brain_computer_interface_data_rights_engine.py",
     "Interfaces cerveau-ordinateur & données neurales", "Wave 843",
     "Données neurales collectées via BCI sans cadre légal de protection de la pensée.",
     "BCID", "bci_data"),
    ("neuralink_privacy_cognitive_rights_engine.py",
     "Implants cérébraux & vie privée cognitive", "Wave 843",
     "Implants cérébraux commerciaux collectant et transmettant des données de pensée.",
     "NLKP", "neuralink_privacy"),
    ("predictive_health_insurance_bias_rights_engine.py",
     "Assurance santé prédictive & biais génomique", "Wave 843",
     "Assureurs utilisant des données génomiques pour refuser ou majorer les couvertures.",
     "PHIB", "health_predictive_bias"),

    # Wave 844 — ADN, police & surveillance génétique
    ("dna_ancestry_police_rights_engine.py",
     "ADN généalogique & accès policier non consenti", "Wave 844",
     "Police exploitant des bases ADN familiales sans consentement pour identifier des suspects.",
     "ANCL", "ancestry_police"),
    ("neural_implant_hacking_rights_engine.py",
     "Piratage d'implants neuraux", "Wave 844",
     "Implants cérébraux vulnérables au piratage exposant les porteurs à des manipulations.",
     "NIHA", "implant_hacking"),
    ("bionic_limb_access_rights_engine.py",
     "Membres bioniques & accès inégal", "Wave 844",
     "Prothèses avancées réservées aux plus riches creusant les inégalités corporelles.",
     "BLMA", "bionic_access"),

    # Wave 845 — Réalité virtuelle & exploitation
    ("virtual_reality_addiction_minor_rights_engine.py",
     "Réalité virtuelle & addiction des mineurs", "Wave 845",
     "Environnements de RV conçus pour captiver les mineurs au détriment de leur développement.",
     "VRDI", "vr_minor_addiction"),
    ("augmented_reality_ad_manipulation_rights_engine.py",
     "Réalité augmentée & publicité manipulatrice", "Wave 845",
     "Publicités intégrées à la RA exploitant l'immersion pour manipuler les comportements.",
     "ARDF", "ar_ad_manipulation"),
    ("extended_reality_minor_exploitation_rights_engine.py",
     "Réalité étendue & exploitation des mineurs", "Wave 845",
     "Mineurs ciblés dans les espaces XR par du contenu sexuel ou des arnaques virtuelles.",
     "ERME", "xr_minor_exploit"),

    # Wave 846 — Armes autonomes & droit humanitaire
    ("autonomous_weapon_targeting_rights_engine.py",
     "Armes autonomes & ciblage sans contrôle humain", "Wave 846",
     "Systèmes d'armes létales autonomes frappant sans décision humaine ni responsabilité.",
     "AWTG", "autonomous_weapon"),
    ("lethal_autonomous_robot_civilian_rights_engine.py",
     "Robots tueurs & victimes civiles", "Wave 846",
     "Robots militaires autonomes incapables de distinguer combattants et civils.",
     "LAUR", "lethal_robot"),
    ("predictive_policing_innocent_rights_engine.py",
     "Police prédictive & arrestations d'innocents", "Wave 846",
     "Algorithmes prédictifs envoyant la police vers des personnes innocentes profilées.",
     "PRPI", "predictive_policing"),

    # Wave 847 — Justice algorithmique
    ("predictive_sentencing_ai_rights_engine.py",
     "Peine prédictive par IA & biais judiciaire", "Wave 847",
     "Logiciels IA suggérant des peines sur la base de facteurs raciaux ou socioéconomiques.",
     "PSAI", "predictive_sentencing"),
    ("algorithmic_parole_bias_rights_engine.py",
     "Liberté conditionnelle algorithmique & biais", "Wave 847",
     "Outils de risque algorithmiques refusant la libération conditionnelle sur biais systémiques.",
     "APBI", "parole_algo_bias"),
    ("lie_detector_immigration_rights_engine.py",
     "Détecteur de mensonge & décisions d'immigration", "Wave 847",
     "Pseudo-tests de véracité influençant les décisions d'asile sans base scientifique.",
     "LDIM", "lie_detector_imm"),

    # Wave 848 — Espace & nouveaux fronts
    ("space_debris_risk_civilian_rights_engine.py",
     "Débris spatiaux & risques pour les populations", "Wave 848",
     "Chutes de débris spatiaux menaçant des zones habitées sans cadre de responsabilité.",
     "SDRI", "space_debris"),
    ("satellite_megaconstellation_dark_sky_rights_engine.py",
     "Méga-constellations & droit au ciel étoilé", "Wave 848",
     "Constellations de satellites polluant les cieux et impactant les peuples nocturnes.",
     "SMCD", "megaconstellation_sky"),
    ("orbital_militarization_rights_engine.py",
     "Militarisation de l'orbite & droit à la paix spatiale", "Wave 848",
     "Course aux armements orbitaux menaçant la neutralité de l'espace et les infractions civiles.",
     "ORMZ", "orbital_militarization"),
]
