# Specs waves 1385-1392 — 24 nouveaux moteurs de droits humains
# Préfixes vérifiés contre le dépôt restauré : 0 collision externe, 0 doublon interne
# (filename, title, wave, desc, prefix, idx)
# Drops sémantiques: strike_replacement(existe), religious_garb(existe), wrongful_conviction(existe),
#   surveillance_pricing(existe), parole_revocation(existe) → remplacés par syndicalisme/benefits/logement
SPECS = [
    # Wave 1385 — Santé: maladies rares (inédits)
    ("narcolepsy_treatment_access_rights_engine.py",
     "Accès au traitement de la narcolepsie & droits des patients à des stimulants et oxybate sans obstacles d'autorisation préalable ni pénuries répétées de médicaments contrôlés", "Wave 1385",
     "Patients narcoleptiques incapables d'obtenir leurs traitements en raison d'autorisations préalables répétées et de pénuries de médicaments contrôlés essentiels à leur fonctionnement diurne.",
     "NRTA", "narcolepsy_treatment"),
    ("wilson_disease_diagnosis_rights_engine.py",
     "Diagnostic et traitement de la maladie de Wilson & droits des patients à un dépistage de cette accumulation de cuivre rare avant des dommages hépatiques et neurologiques irréversibles", "Wave 1385",
     "Patients atteints de la maladie de Wilson subissant des années d'errance diagnostique avec symptômes hépatiques et psychiatriques avant l'identification de cette maladie génétique traitable.",
     "WLDD", "wilson_disease_diag"),
    ("short_bowel_syndrome_nutrition_rights_engine.py",
     "Nutrition parentérale pour le syndrome de l'intestin court & droits des patients à une couverture de la nutrition intraveineuse à domicile vitale sans plafonds arbitraires", "Wave 1385",
     "Patients atteints du syndrome de l'intestin court dépendants de nutrition parentérale se voyant refuser ou rationner cette alimentation intraveineuse vitale par leur assurance.",
     "SBSN", "short_bowel_nutrition"),

    # Wave 1386 — Santé: immunologie & génétique (inédits)
    ("primary_immunodeficiency_ivig_rights_engine.py",
     "Accès aux immunoglobulines pour l'immunodéficience primaire & droits des patients à un traitement IgIV ou IgSC régulier sans interruptions liées aux pénuries ou refus d'assurance", "Wave 1386",
     "Patients atteints d'immunodéficience primaire dépendants d'immunoglobulines se voyant rationner ou refuser ce traitement vital en raison de pénuries et de restrictions de couverture.",
     "PIDV", "primary_immuno_ivig"),
    ("hereditary_angioedema_treatment_rights_engine.py",
     "Traitement de l'angio-œdème héréditaire & droits des patients à des traitements préventifs et d'urgence pour des crises de gonflement potentiellement mortelles sans rationnement", "Wave 1386",
     "Patients atteints d'angio-œdème héréditaire subissant des crises de gonflement potentiellement mortelles se voyant refuser les traitements prophylactiques coûteux par leur assureur.",
     "HAET", "hereditary_angioedema"),
    ("utility_shutoff_medical_vulnerability_rights_engine.py",
     "Protection contre les coupures de services publics pour vulnérabilité médicale & droits des personnes dépendant d'équipements médicaux à un maintien de l'électricité malgré les impayés", "Wave 1386",
     "Personnes dépendant d'équipements médicaux électriques (oxygène, dialyse, réfrigération d'insuline) menacées de coupure d'électricité pour impayés sans protection de certificat médical.",
     "UTSM", "utility_shutoff_medical"),

    # Wave 1387 — Logement: financement & copropriété (inédits)
    ("cohousing_zoning_barrier_rights_engine.py",
     "Obstacles de zonage à l'habitat partagé & droits des résidents à créer des communautés d'habitat groupé et intergénérationnel sans interdictions de zonage des occupants non apparentés", "Wave 1387",
     "Personnes souhaitant créer un habitat partagé ou intergénérationnel bloquées par des codes de zonage limitant le nombre d'occupants non apparentés par logement.",
     "CHZB", "cohousing_zoning"),
    ("mortgage_servicer_transfer_error_rights_engine.py",
     "Erreurs lors des transferts de gestion hypothécaire & droits des emprunteurs à ne pas subir de pénalités, paiements perdus ou saisies erronées lors du changement de prestataire", "Wave 1387",
     "Emprunteurs dont le prêt hypothécaire est transféré à un nouveau gestionnaire subissant des paiements mal crédités, des frais erronés et des menaces de saisie injustifiées.",
     "MSTE", "mortgage_servicer_transfer"),
    ("lihtc_tenant_protection_rights_engine.py",
     "Protection des locataires en logement à crédit d'impôt LIHTC & droits des occupants de logements abordables financés par le LIHTC contre les expulsions et hausses après période de conformité", "Wave 1387",
     "Locataires de logements abordables LIHTC menacés d'expulsion ou de hausses de loyer au marché à l'expiration de la période de restriction de conformité de leur immeuble.",
     "LHTP", "lihtc_tenant_protect"),

    # Wave 1388 — Finance: crédit & automobile (inédits)
    ("buy_now_pay_later_credit_report_rights_engine.py",
     "Déclaration des achats fractionnés aux bureaux de crédit & droits des consommateurs à la transparence sur l'impact des prêts BNPL sur leur dossier de crédit et leur endettement", "Wave 1388",
     "Consommateurs accumulant des prêts achetez-maintenant-payez-plus-tard invisibles aux bureaux de crédit, conduisant à un surendettement caché et des décisions de prêt mal informées.",
     "BPCR", "bnpl_credit_report"),
    ("earned_income_advance_tip_rights_engine.py",
     "Pourboires obligatoires déguisés des avances sur salaire & droits des travailleurs à accéder à leur salaire gagné sans pourboires sollicités équivalant à des intérêts cachés", "Wave 1388",
     "Travailleurs utilisant des applications d'avance sur salaire sollicités pour des pourboires présentés comme volontaires mais conditionnant de fait l'accès au service à coût élevé.",
     "EITP", "earned_advance_tip"),
    ("dealer_markup_auto_loan_rights_engine.py",
     "Majoration des taux par les concessionnaires automobiles & droits des acheteurs à connaître la majoration du taux d'intérêt appliquée par le concessionnaire au-dessus du taux approuvé", "Wave 1388",
     "Acheteurs de voitures financées via le concessionnaire payant des taux d'intérêt majorés à leur insu, le concessionnaire empochant la différence avec le taux réellement approuvé par le prêteur.",
     "DMAL", "dealer_markup_auto"),

    # Wave 1389 — Travail: droit syndical & secteurs (inédits)
    ("home_health_overtime_companionship_rights_engine.py",
     "Heures supplémentaires des aides à domicile et exemption de compagnie & droits des aides-soignants à domicile aux heures supplémentaires malgré l'ancienne exemption companionship", "Wave 1389",
     "Aides à domicile travaillant de longues heures privés de majoration d'heures supplémentaires par une application abusive de l'exemption companionship pourtant restreinte par la réglementation.",
     "HHCC", "home_health_overtime"),
    ("farmworker_collective_bargaining_rights_engine.py",
     "Droit à la négociation collective des travailleurs agricoles & droits des ouvriers agricoles à se syndiquer malgré leur exclusion historique de la loi nationale sur les relations de travail", "Wave 1389",
     "Travailleurs agricoles exclus des protections de la NLRA incapables de se syndiquer et négocier collectivement leurs conditions de travail dans la plupart des États.",
     "FCBA", "farmworker_bargaining"),
    ("gig_worker_organizing_rights_engine.py",
     "Droit d'organisation des travailleurs de plateformes & droits des chauffeurs et livreurs à s'organiser collectivement sans représailles malgré leur classification d'indépendants", "Wave 1389",
     "Travailleurs de plateformes cherchant à s'organiser pour de meilleures conditions confrontés à des désactivations de représailles et à l'obstacle de leur statut d'entrepreneur indépendant.",
     "GWOR", "gig_worker_organizing"),

    # Wave 1390 — Travail & benefits: protections (inédits)
    ("public_sector_union_dues_rights_engine.py",
     "Cotisations syndicales dans le secteur public après Janus & droits des employés publics à un choix éclairé sur l'adhésion sans pressions ni prélèvements non autorisés", "Wave 1390",
     "Employés du secteur public confrontés à des pratiques de prélèvement de cotisations syndicales non clairement consenties ou à des obstacles à l'exercice de leur choix d'adhésion post-Janus.",
     "PSUD", "public_union_dues"),
    ("snap_work_requirement_waiver_rights_engine.py",
     "Exemptions des exigences de travail SNAP & droits des bénéficiaires en zones à fort chômage ou avec barrières à une dispense des obligations de travail ABAWD pour conserver l'aide alimentaire", "Wave 1390",
     "Bénéficiaires SNAP adultes sans personnes à charge perdant leur aide alimentaire pour non-respect des exigences de travail malgré des barrières d'emploi réelles et zones éligibles aux exemptions.",
     "SWRW", "snap_work_waiver"),
    ("workplace_temperature_extreme_rights_engine.py",
     "Protection contre les températures extrêmes au travail & droits des travailleurs intérieurs et extérieurs à des protections contre la chaleur et le froid dangereux sur le lieu de travail", "Wave 1390",
     "Travailleurs d'entrepôts non climatisés, cuisines et chantiers exposés à des chaleurs ou froids dangereux sans normes obligatoires de pauses, hydratation ou température maximale.",
     "WTEX", "workplace_temp_extreme"),

    # Wave 1391 — Immigration & éducation: accès (inédits)
    ("immigration_detainer_local_jail_rights_engine.py",
     "Détenteurs d'immigration dans les prisons locales & droits des personnes à ne pas être détenues au-delà de leur date de libération sur la seule base d'une demande ICE sans mandat", "Wave 1391",
     "Personnes maintenues en détention dans des prisons locales au-delà de leur libération sur la base de détenteurs ICE sans mandat judiciaire, en violation de leurs droits constitutionnels.",
     "IDLJ", "immigr_detainer_jail"),
    ("naturalization_oath_delay_rights_engine.py",
     "Délais de la cérémonie de prestation de serment de naturalisation & droits des candidats approuvés à prêter serment dans des délais raisonnables pour accéder à la citoyenneté et au vote", "Wave 1391",
     "Candidats à la naturalisation approuvés attendant des mois la cérémonie de serment, retardant leur citoyenneté, leur droit de vote et leur capacité à parrainer des proches.",
     "NZOD", "natz_oath_delay"),
    ("homeless_student_mckinney_vento_rights_engine.py",
     "Droits des élèves sans domicile sous la loi McKinney-Vento & droits des enfants en situation d'itinérance à la stabilité scolaire, au transport et à l'inscription immédiate", "Wave 1391",
     "Enfants en situation d'itinérance se voyant refuser l'inscription immédiate, le transport vers leur école d'origine ou les services auxquels la loi McKinney-Vento leur donne droit.",
     "HSMV", "homeless_student_mckinney"),

    # Wave 1392 — Éducation & travail domestique: protections (inédits)
    ("transcript_hold_community_college_rights_engine.py",
     "Rétention des relevés de notes en community college pour dettes & droits des étudiants à obtenir leur transcrit malgré de petits soldes impayés bloquant transfert et emploi", "Wave 1392",
     "Étudiants de community college incapables de transférer ou de prouver leurs acquis car l'établissement retient leur relevé de notes pour de petites dettes administratives.",
     "TPCC", "transcript_hold_cc"),
    ("teacher_misconduct_database_rights_engine.py",
     "Base de données nationale sur l'inconduite des enseignants & droits des élèves à une protection contre les enseignants ayant commis des fautes graves mutés sans signalement inter-États", "Wave 1392",
     "Élèves exposés à des enseignants ayant commis des fautes graves dans un autre État faute de base de données inter-États empêchant le phénomène de mutation silencieuse des fautifs.",
     "TMDB", "teacher_misconduct_db"),
    ("domestic_worker_bill_of_rights_engine.py",
     "Charte des droits des travailleurs domestiques & droits des employés de maison à un socle de protections (salaire, repos, préavis) là où les lois du travail standard les excluent", "Wave 1392",
     "Travailleurs domestiques exclus de nombreuses protections du travail standard sans charte étatique leur garantissant salaire minimum, jours de repos, préavis de licenciement et recours.",
     "DWBR", "domestic_worker_bill"),
]
