# Specs waves 865-872 — 24 nouveaux moteurs de droits humains
# (filename, title, wave, desc, prefix, idx)
SPECS = [
    # Wave 865 — Eau comme droit & privatisation
    ("water_right_privatization_rights_engine.py",
     "Privatisation de l'eau & accès au droit fondamental", "Wave 865",
     "Privatisation des ressources en eau excluant les ménages pauvres de l'eau potable.",
     "WTRP", "water_privatization"),
    ("bottled_water_displacement_rights_engine.py",
     "Eau en bouteille & déplacement communautaire", "Wave 865",
     "Industries de l'eau embouteillée épuisant les nappes phréatiques des communautés locales.",
     "BWDI", "bottled_water"),
    ("agricultural_water_theft_rights_engine.py",
     "Agro-industrie & vol de l'eau des petits agriculteurs", "Wave 865",
     "Grands irrigants captant l'eau de rivières au détriment des paysans en aval.",
     "AGTW", "agri_water_theft"),

    # Wave 866 — Lieux sacrés & patrimoine spirituel
    ("indigenous_water_ceremony_rights_engine.py",
     "Cérémonies de l'eau autochtones & profanation", "Wave 866",
     "Sources et rivières sacrées polluées ou détournées, effaçant les rites autochtones.",
     "IWCE", "water_ceremony"),
    ("religious_symbol_ban_rights_engine.py",
     "Interdiction de symboles religieux & liberté de culte", "Wave 866",
     "Interdictions de signes religieux excluant les pratiquants de l'espace public.",
     "RSYB", "religious_symbol"),
    ("burial_ground_development_rights_engine.py",
     "Développement sur sites funéraires & profanation", "Wave 866",
     "Projets immobiliers détruisant des cimetières et tombes de peuples autochtones.",
     "BGRD", "burial_ground"),

    # Wave 867 — Forêts & patrimoine naturel
    ("ancient_forest_logging_rights_engine.py",
     "Déforestation des forêts anciennes & biodiversité", "Wave 867",
     "Abattage de forêts millénaires irremplaçables pour l'industrie du bois.",
     "AFLG", "ancient_forest"),
    ("heritage_site_mining_rights_engine.py",
     "Extraction minière sur sites patrimoniaux", "Wave 867",
     "Mines installées sur des sites culturels ou naturels protégés, détruisant l'héritage.",
     "HSMI", "heritage_mining"),
    ("cultural_artifact_looting_rights_engine.py",
     "Pillage d'artefacts culturels & restitution", "Wave 867",
     "Artefacts culturels pillés pendant la colonisation et retenus dans des musées étrangers.",
     "CALT", "artifact_looting"),

    # Wave 868 — Réparations historiques & reconnaissance
    ("reparations_slavery_refused_rights_engine.py",
     "Réparations pour l'esclavage & refus étatique", "Wave 868",
     "Descendants d'esclaves réclamant des réparations systématiquement refusées.",
     "RSLV", "reparations_slavery"),
    ("historical_trauma_indigenous_rights_engine.py",
     "Trauma historique autochtone & droit à la guérison", "Wave 868",
     "Séquelles intergénérationnelles des pensionnats imposés aux peuples autochtones.",
     "HTIA", "historical_trauma"),
    ("apartheid_land_restitution_rights_engine.py",
     "Restitution des terres de l'apartheid", "Wave 868",
     "Terres confisquées sous l'apartheid non restituées malgré les promesses légales.",
     "ALRE", "apartheid_land"),

    # Wave 869 — Justice coloniale & mémoire
    ("colonial_wealth_return_rights_engine.py",
     "Retour des richesses coloniales & justice économique", "Wave 869",
     "Ressources et richesses extraites pendant la colonisation sans réparation aux nations spoliées.",
     "CWRL", "colonial_wealth"),
    ("mau_mau_reparation_rights_engine.py",
     "Réparations Mau Mau & atrocités coloniales reconnues", "Wave 869",
     "Victimes de la répression coloniale britannique attendant réparations et reconnaissance.",
     "MMRP", "mau_mau"),
    ("comfort_women_justice_rights_engine.py",
     "Femmes de réconfort & justice en attente", "Wave 869",
     "Survivantes d'esclavage sexuel militaire japonais sans justice ni réparation officielle.",
     "CWJU", "comfort_women"),

    # Wave 870 — Mémoire & reconnaissance génocidaire
    ("comfort_women_memorial_rights_engine.py",
     "Mémoriaux des femmes de réconfort & pression diplomatique", "Wave 870",
     "Statues commémoratives des femmes de réconfort retirées sous pression politique.",
     "CWMM", "comfort_memorial"),
    ("genocide_acknowledgment_rights_engine.py",
     "Reconnaissance du génocide & déni officiel", "Wave 870",
     "Génocides niés diplomatiquement, privant les survivants de reconnaissance et justice.",
     "GRKA", "genocide_acknowledge"),
    ("colonial_exploitation_remedy_rights_engine.py",
     "Remède à l'exploitation coloniale & transition", "Wave 870",
     "Ex-colonies dépourvues de mécanismes de transition équitable post-coloniale.",
     "CERR", "colonial_remedy"),

    # Wave 871 — Travail du sexe & criminalisation
    ("sex_work_decriminalization_rights_engine.py",
     "Décriminalisation du travail du sexe & sécurité", "Wave 871",
     "Travailleur·euse·s du sexe criminalisé·e·s, exposé·e·s à la violence sans recours.",
     "SWDC", "sex_work_decrim"),
    ("criminalize_client_sex_work_rights_engine.py",
     "Modèle nordique & risques pour les travailleurs du sexe", "Wave 871",
     "Modèle de criminalisation des clients poussant le travail du sexe dans la clandestinité.",
     "CCSW", "client_criminalization"),
    ("fosta_sesta_sex_worker_harm_rights_engine.py",
     "FOSTA-SESTA & aggravation des risques pour les travailleurs du sexe", "Wave 871",
     "Législation FOSTA-SESTA supprimant des plateformes de sécurité pour les travailleurs du sexe.",
     "FOSH", "fosta_sesta_harm"),

    # Wave 872 — Contenu adulte & plateformes
    ("platform_ban_adult_content_rights_engine.py",
     "Banissement du contenu adulte consenti & censure", "Wave 872",
     "Plateformes supprimant du contenu adulte consenti, précarisant les créateurs légaux.",
     "PBSC", "adult_content_ban"),
    ("UNESCO_site_development_rights_engine.py",
     "Développement sur sites UNESCO & patrimoine mondial", "Wave 872",
     "Sites du patrimoine mondial de l'UNESCO dégradés par des projets d'infrastructure.",
     "UNSN", "unesco_site"),
    ("heritage_erasure_forced_assimilation_rights_engine.py",
     "Effacement du patrimoine & assimilation forcée", "Wave 872",
     "Langues, noms et pratiques culturelles interdits au nom de l'assimilation nationale.",
     "HEFA", "heritage_erasure"),
]
