import { NextResponse } from "next/server";
import { sealResponse } from "@/lib/digital-seal";

if (!process.env.SWARM_API_URL) {
  console.warn("[anti-corruption-accountability-rights-engine] SWARM_API_URL is not set — falling back to mock data");
}

const MOCK = getMockData();

export async function GET() {
  if (!process.env.SWARM_API_URL) {
    return NextResponse.json(await sealResponse(MOCK));
  }
  try {
    const res = await fetch(`${process.env.SWARM_API_URL}/anti-corruption-accountability-rights-engine`, { next: { revalidate: 30 } });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    const data = await res.json();
    return NextResponse.json(await sealResponse(data));
  } catch {
    return NextResponse.json(await sealResponse(MOCK), { status: 502 });
  }
}

function getMockData() {
  const entities = [
    { id: "ACAR-001", name: "Somalie/IPC 11/100 Corruption Totale Institutionnelle", country: "Afrique de l'Est", sector: "Dernier IPC TI 2023, État Failli Corruption Totale, Al-Shabaab Taxes Parallèles, Fonds Aide Internationale Détournés & Impunité Absolue", composite_score: 88.85, systemic_corruption_impunity_severity_score: 92.0, public_funds_diversion_kleptocracy_scale_score: 88.0, whistleblower_anti_corruption_persecution_score: 85.0, transparency_accountability_institution_deficit_gap_score: 90.0, risk_level: "critique", primary_pattern: "kleptocracie_etat_capture", key_signals: ["Kleptocracie critique de Somalie/IPC 11/100 Corruption Totale Institutionnelle — corruption systémique totale avec État capturé par des réseaux de pouvoir utilisant les ressources publiques comme instrument d'enrichissement personnel et de contrôle politique", "Violation massive des droits économiques et sociaux — le détournement des fonds publics prive les populations d'accès à la santé, l'éducation et les services essentiels garantis par le Pacte ICESCR", "Impunité institutionnalisée — l'absence de poursuites contre les élites corrompues crée un système de deux poids deux mesures qui dévaste la confiance dans les institutions démocratiques"], estimated_anti_corruption_accountability_rights_index: 8.89, last_updated: "2026-06-21" },
    { id: "ACAR-002", name: "Venezuela/Pdvsa Kleptocracie 300B$ Détournés", country: "Amérique du Sud", sector: "PDVSA 300B$ Détournés 2000-2023, DOJ USA, Maduro Réseau Crypto & Or, Intermédiaires Offshore & Sanctions 300+ Personnes", composite_score: 87.5, systemic_corruption_impunity_severity_score: 88.0, public_funds_diversion_kleptocracy_scale_score: 92.0, whistleblower_anti_corruption_persecution_score: 82.0, transparency_accountability_institution_deficit_gap_score: 88.0, risk_level: "critique", primary_pattern: "detournement_fonds_publics", key_signals: ["Kleptocracie critique de Venezuela/Pdvsa Kleptocracie 300B$ Détournés — corruption systémique totale avec État capturé par des réseaux de pouvoir utilisant les ressources publiques comme instrument d'enrichissement personnel et de contrôle politique", "Violation massive des droits économiques et sociaux — le détournement des fonds publics prive les populations d'accès à la santé, l'éducation et les services essentiels garantis par le Pacte ICESCR", "Impunité institutionnalisée — l'absence de poursuites contre les élites corrompues crée un système de deux poids deux mesures qui dévaste la confiance dans les institutions démocratiques"], estimated_anti_corruption_accountability_rights_index: 8.75, last_updated: "2026-06-21" },
    { id: "ACAR-003", name: "Syrie/Assad Corruption Guerre", country: "MENA", sector: "Assad Famille 200B$ Avoirs, Guerre Civile Économie Corruption, Captagon Trafic État, Reconstruction Marchés Réseaux Proches & CPI Mandat", composite_score: 85.5, systemic_corruption_impunity_severity_score: 85.0, public_funds_diversion_kleptocracy_scale_score: 82.0, whistleblower_anti_corruption_persecution_score: 90.0, transparency_accountability_institution_deficit_gap_score: 85.0, risk_level: "critique", primary_pattern: "persecution_lanceurs_alerte", key_signals: ["Kleptocracie critique de Syrie/Assad Corruption Guerre — corruption systémique totale avec État capturé par des réseaux de pouvoir utilisant les ressources publiques comme instrument d'enrichissement personnel et de contrôle politique", "Violation massive des droits économiques et sociaux — le détournement des fonds publics prive les populations d'accès à la santé, l'éducation et les services essentiels garantis par le Pacte ICESCR", "Impunité institutionnalisée — l'absence de poursuites contre les élites corrompues crée un système de deux poids deux mesures qui dévaste la confiance dans les institutions démocratiques"], estimated_anti_corruption_accountability_rights_index: 8.55, last_updated: "2026-06-21" },
    { id: "ACAR-004", name: "Soudan/Al-Bashir 9B$ Caché CPI", country: "Afrique de l'Est", sector: "Al-Bashir 9B$ CPI 2019, Transition SAF/RSF Corruption Continuée, Or Darfour Trafic, Armée Économie Parallèle & Impunité Transfert", composite_score: 83.75, systemic_corruption_impunity_severity_score: 83.0, public_funds_diversion_kleptocracy_scale_score: 85.0, whistleblower_anti_corruption_persecution_score: 80.0, transparency_accountability_institution_deficit_gap_score: 88.0, risk_level: "critique", primary_pattern: "detournement_fonds_publics", key_signals: ["Kleptocracie critique de Soudan/Al-Bashir 9B$ Caché CPI — corruption systémique totale avec État capturé par des réseaux de pouvoir utilisant les ressources publiques comme instrument d'enrichissement personnel et de contrôle politique", "Violation massive des droits économiques et sociaux — le détournement des fonds publics prive les populations d'accès à la santé, l'éducation et les services essentiels garantis par le Pacte ICESCR", "Impunité institutionnalisée — l'absence de poursuites contre les élites corrompues crée un système de deux poids deux mesures qui dévaste la confiance dans les institutions démocratiques"], estimated_anti_corruption_accountability_rights_index: 8.38, last_updated: "2026-06-21" },
    { id: "ACAR-005", name: "Russie/Oligarques Sanctions Actifs Cachés", country: "Europe de l'Est", sector: "1T$ Avoirs Oligarques Post-Sanctions 2022, Yachts & Propriétés Gelés, Enablers Financiers Occidentaux & Anti-Corruption Sélective Navalny", composite_score: 58.6, systemic_corruption_impunity_severity_score: 55.0, public_funds_diversion_kleptocracy_scale_score: 62.0, whistleblower_anti_corruption_persecution_score: 60.0, transparency_accountability_institution_deficit_gap_score: 58.0, risk_level: "élevé", primary_pattern: "deficit_institutions_transparence", key_signals: ["Corruption institutionnalisée de Russie/Oligarques Sanctions Actifs Cachés — réseaux opaques d'enrichissement des élites au détriment des populations, avec défaillance systémique des mécanismes de contrôle et de redevabilité", "Réseaux financiers offshore — les flux financiers illicites transitant par des paradis fiscaux privent les États du Sud de ressources essentielles estimées à 1 000 milliards de dollars par an", "Entrave à la justice — les poursuites anti-corruption sont sélectives, ciblant les opposants politiques plutôt que les réseaux criminels proches du pouvoir"], estimated_anti_corruption_accountability_rights_index: 5.86, last_updated: "2026-06-21" },
    { id: "ACAR-006", name: "Chine/Anti-Corruption Sélective Xi Factionnelle", country: "Asie de l'Est", sector: "Campagne Anti-Corruption Xi 1.5M Fonctionnaires 2012-2023, Usage Factionnelle Élimination Rivaux, Opacité PCCC & Aucun Contrôle Externe", composite_score: 56.45, systemic_corruption_impunity_severity_score: 52.0, public_funds_diversion_kleptocracy_scale_score: 55.0, whistleblower_anti_corruption_persecution_score: 62.0, transparency_accountability_institution_deficit_gap_score: 58.0, risk_level: "élevé", primary_pattern: "deficit_institutions_transparence", key_signals: ["Corruption institutionnalisée de Chine/Anti-Corruption Sélective Xi Factionnelle — réseaux opaques d'enrichissement des élites au détriment des populations, avec défaillance systémique des mécanismes de contrôle et de redevabilité", "Réseaux financiers offshore — les flux financiers illicites transitant par des paradis fiscaux privent les États du Sud de ressources essentielles estimées à 1 000 milliards de dollars par an", "Entrave à la justice — les poursuites anti-corruption sont sélectives, ciblant les opposants politiques plutôt que les réseaux criminels proches du pouvoir"], estimated_anti_corruption_accountability_rights_index: 5.65, last_updated: "2026-06-21" },
    { id: "ACAR-007", name: "Transparency International/GRECO Standards", country: "Global", sector: "IPC 180 Pays, GRECO 49 États Évalués, Standards Anti-Corruption & Financement Sociétés Civile Anti-Corruption Locale", composite_score: 23.6, systemic_corruption_impunity_severity_score: 25.0, public_funds_diversion_kleptocracy_scale_score: 20.0, whistleblower_anti_corruption_persecution_score: 22.0, transparency_accountability_institution_deficit_gap_score: 28.0, risk_level: "modéré", primary_pattern: "deficit_institutions_transparence", key_signals: ["Déficits de transparence de Transparency International/GRECO Standards — institutions de contrôle insuffisamment indépendantes, budgets opaques et protection insuffisante des lanceurs d'alerte créant des conditions propices à la corruption", "Risques systémiques résiduels — la corruption dans les marchés publics et les permis administratifs persiste malgré l'existence de cadres légaux anti-corruption", "Progrès fragiles — les avancées en matière de transparence peuvent être inversées par des changements politiques ou des pressions des élites économiques bénéficiant de l'opacité"], estimated_anti_corruption_accountability_rights_index: 2.36, last_updated: "2026-06-21" },
    { id: "ACAR-008", name: "ONU/CNUCC 2003 Convention Anti-Corruption", country: "Global", sector: "CNUCC Ratifiée 189 États, Mécanisme Révision, Recouvrement Avoirs Art.57 & Assistance Technique Pays En Développement", composite_score: 5.6, systemic_corruption_impunity_severity_score: 5.0, public_funds_diversion_kleptocracy_scale_score: 4.0, whistleblower_anti_corruption_persecution_score: 6.0, transparency_accountability_institution_deficit_gap_score: 8.0, risk_level: "faible", primary_pattern: "standards_anticorruption_exemplaires", key_signals: ["ONU/CNUCC 2003 Convention Anti-Corruption incarne les standards exemplaires anti-corruption — institutions de contrôle indépendantes, protection robuste des lanceurs d'alerte et transparence budgétaire effective", "CNUCC et GRECO standards respectés — mécanismes de vérification des actifs des fonctionnaires, registres publics des bénéficiaires effectifs et budgets ouverts accessibles", "Modèle exportable — financement Transparency International, partage d'expertise avec les pays à haute corruption et soutien aux réformes institutionnelles anti-corruption"], estimated_anti_corruption_accountability_rights_index: 0.56, last_updated: "2026-06-21" },
  ];

  const avg = Math.round(entities.reduce((s, e) => s + e.composite_score, 0) / entities.length * 100) / 100;
  return {
    total_entities: 8,
    avg_composite: avg,
    risk_distribution: { critique: 4, "élevé": 2, "modéré": 1, faible: 1 },
    pattern_distribution: { kleptocracie_etat_capture: 1, detournement_fonds_publics: 2, persecution_lanceurs_alerte: 1, deficit_institutions_transparence: 3, standards_anticorruption_exemplaires: 1 },
    top_risk_entities: ["Somalie/IPC 11/100 Corruption Totale Institutionnelle", "Venezuela/Pdvsa Kleptocracie 300B$ Détournés", "Syrie/Assad Corruption Guerre", "Soudan/Al-Bashir 9B$ Caché CPI"],
    critical_alerts: ["Somalie/IPC 11/100: kleptocracie etat capture", "Venezuela/PDVSA: detournement fonds publics", "Syrie/Assad: persecution lanceurs alerte", "Soudan/Al-Bashir: detournement fonds publics"],
    last_analysis: "2026-06-21",
    engine_version: "1.0.0",
    domain: "anti_corruption_accountability_rights",
    confidence_score: 0.85,
    data_sources: ["transparency_international_cpi_2023", "un_office_drugs_crime_anticorruption", "fatf_financial_flows_illicit_reports", "greco_evaluation_reports_council_europe"],
    entities,
    avg_estimated_anti_corruption_accountability_rights_index: Math.round(avg / 100 * 10 * 100) / 100,
  };
}
